alter table public.formula_cards
  add column if not exists recall_data jsonb;

insert into public.formula_subjects (id, name, slug, exam, sort_order) values
  ('neet-biology', 'Biology', 'biology', 'NEET', 3)
on conflict (id) do update set
  name = excluded.name,
  slug = excluded.slug,
  exam = excluded.exam,
  sort_order = excluded.sort_order;

insert into public.formula_chapters (id, subject_id, title, slug, sort_order) values
  ('neet-biology-the-living-world', 'neet-biology', 'The Living World', 'the-living-world', 1),
  ('neet-biology-biological-classification', 'neet-biology', 'Biological Classification', 'biological-classification', 2),
  ('neet-biology-plant-kingdom', 'neet-biology', 'Plant Kingdom', 'plant-kingdom', 3),
  ('neet-biology-animal-kingdom', 'neet-biology', 'Animal Kingdom', 'animal-kingdom', 4)
on conflict (id) do update set
  title = excluded.title,
  slug = excluded.slug,
  sort_order = excluded.sort_order;

insert into public.formula_cards (
  id, chapter_id, title, card_type, body, formulas, variables, conditions, table_data, diagram_data, diagram_svg, recall_data, importance, source_page, sort_order, is_active
) values
  (
    'neet-biology-the-living-world-life-definition',
    'neet-biology-the-living-world',
    'Living Organism Core Description',
    'concept',
    'Life expresses through chemical reactions leading to growth, development, responsiveness, adaptation and reproduction.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    null,
    null,
    null,
    '{"recall_question":"How does the source describe a living organism?","reveal_answer":"A self-replicating, evolving and self-regulating interactive system capable of responding to external stimuli.","key_points":["Life is a unique, complex organization of molecules.","The expression of life is through chemical reactions."],"examples":[],"neet_traps":[]}'::jsonb,
    4,
    3,
    1,
    true
  ),
  (
    'neet-biology-the-living-world-growth-trap',
    'neet-biology-the-living-world',
    'Growth Is Not Perfectly Defining',
    'neet_trap',
    'Growth means increase in number and mass of cells by cell division, but non-living objects also grow by surface accumulation.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    null,
    null,
    null,
    '{"recall_question":"Why is growth not a perfect defining property of living organisms?","reveal_answer":"Because non-living objects also grow by surface accumulation of material.","key_points":["Plants grow throughout their lifespan.","Animals grow only up to a certain age, though cell division replaces lost cells.","In living organisms, growth is from inside."],"examples":[],"neet_traps":["Growth alone cannot define life."]}'::jsonb,
    5,
    3,
    2,
    true
  ),
  (
    'neet-biology-the-living-world-reproduction-trap',
    'neet-biology-the-living-world',
    'Reproduction Is Not Perfectly Defining',
    'neet_trap',
    'Reproduction produces progeny similar to parents, but many living organisms do not reproduce.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    null,
    null,
    null,
    '{"recall_question":"Why is reproduction not a perfect defining property of living organisms?","reveal_answer":"Many organisms do not reproduce, so reproduction cannot alone define life.","key_points":["Organisms reproduce asexually and sexually.","In unicellular organisms, growth and reproduction are same because they reproduce by cell division."],"examples":["mules","worker bees","infertile human couples"],"neet_traps":["Reproduction is absent in some living organisms."]}'::jsonb,
    5,
    3,
    3,
    true
  ),
  (
    'neet-biology-the-living-world-metabolism-defining',
    'neet-biology-the-living-world',
    'Metabolism',
    'concept',
    'Metabolism is the sum total of all biochemical reactions taking place inside a living system.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    null,
    null,
    null,
    '{"recall_question":"Which property is listed as a defining feature of living organisms: metabolism or isolated in vitro reactions?","reveal_answer":"Metabolism is defining; isolated metabolic reactions in vitro are living reactions but not living things.","key_points":["Metabolic reactions can be demonstrated outside the body in cell-free systems."],"examples":[],"neet_traps":["Metabolism is a defining feature of living organisms."]}'::jsonb,
    5,
    3,
    4,
    true
  ),
  (
    'neet-biology-the-living-world-cellular-organization',
    'neet-biology-the-living-world',
    'Cellular Organization',
    'concept',
    'Organisms are made up of one or more cells.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    null,
    null,
    null,
    '{"recall_question":"Why is cellular organization important as a life property?","reveal_answer":"It is a defining feature of living organisms.","key_points":["A living organism is organized at cellular level, whether one-celled or many-celled."],"examples":[],"neet_traps":[]}'::jsonb,
    5,
    3,
    5,
    true
  ),
  (
    'neet-biology-the-living-world-consciousness-defining',
    'neet-biology-the-living-world',
    'Consciousness',
    'neet_trap',
    'Consciousness is the ability to sense environment and respond to environmental stimuli.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    null,
    null,
    null,
    '{"recall_question":"What makes consciousness a defining property in the source?","reveal_answer":"All organisms are aware of their surroundings and respond to stimuli.","key_points":["Stimuli include light, water, temperature, other organisms, chemicals and pollutants.","Human is the only organism having self-consciousness."],"examples":[],"neet_traps":["Consciousness is a defining property."]}'::jsonb,
    5,
    3,
    6,
    true
  ),
  (
    'neet-biology-the-living-world-biodiversity-number',
    'neet-biology-the-living-world',
    'Biodiversity',
    'fact',
    'Biodiversity refers to the number and types of organisms present on earth.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    null,
    null,
    null,
    '{"recall_question":"How many species are described according to the source?","reveal_answer":"1.7-1.8 million species.","key_points":["Biodiversity means number and types of organisms on earth."],"examples":[],"neet_traps":[]}'::jsonb,
    4,
    3,
    7,
    true
  ),
  (
    'neet-biology-the-living-world-taxonomy-systematics',
    'neet-biology-the-living-world',
    'Taxonomy vs Systematics',
    'comparison',
    'Taxonomy and systematics are related but not identical.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Term","Recall answer"],"rows":[["Taxonomy","Study of identification, classification and nomenclature of organisms."],["Systematics","Deals with evolutionary relationships among organisms."],["Systema Naturae","Book written by Linnaeus."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"Taxonomy vs systematics: what is the NEET distinction?","reveal_answer":"Taxonomy covers identification, classification and nomenclature; systematics deals with evolutionary relationships.","key_points":["Systematics comes from Latin systema = systematic arrangement."],"examples":["Systema Naturae - Linnaeus"],"neet_traps":[]}'::jsonb,
    5,
    3,
    8,
    true
  ),
  (
    'neet-biology-the-living-world-taxonomy-processes',
    'neet-biology-the-living-world',
    'Basic Processes of Taxonomy',
    'classification',
    'The source lists four basic processes of taxonomy.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Process","Recall answer"],"rows":[["Characterization","Understanding characters such as external/internal structure, cell structure, development process and ecological information."],["Identification","Correct description of the organism so naming is possible."],["Classification","Grouping organisms into convenient categories (taxa) based on characters."],["Nomenclature","Standardization of names so an organism is known by the same name worldwide."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"Name the four basic taxonomy processes in order.","reveal_answer":"Characterization, identification, classification and nomenclature.","key_points":[],"examples":[],"neet_traps":["Do not merge identification with nomenclature."]}'::jsonb,
    5,
    3,
    9,
    true
  ),
  (
    'neet-biology-the-living-world-binomial-rules',
    'neet-biology-the-living-world',
    'Binomial Nomenclature Rules',
    'rule',
    'Binomial nomenclature is the two-component naming system proposed by Linnaeus.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Rule","Source-backed detail"],"rows":[["Components","First word is genus name; second word is species name/specific epithet."],["Typography","Scientific names are in Latin or Latinised and written in italics; handwritten names are underlined separately."],["Capitalization","Genus starts with capital letter; species starts with small letter."],["Author","Name of author in abbreviated form appears at the end of biological name."],["Codes","Botanical names follow ICBN; zoological names follow ICZN."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"What are the universal binomial nomenclature rules given in the source?","reveal_answer":"Latin/Latinised italic names, genus first and capitalized, species second and lowercase, with abbreviated author name when given.","key_points":[],"examples":["Homo sapiens","Mangifera indica Linn."],"neet_traps":["ICBN for botanical names; ICZN for zoological names."]}'::jsonb,
    5,
    3,
    10,
    true
  ),
  (
    'neet-biology-the-living-world-taxonomic-hierarchy-visual',
    'neet-biology-the-living-world',
    'Taxonomic Hierarchy',
    'diagram',
    'Classification involves hierarchy of taxonomic categories. All categories together form the taxonomic hierarchy.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Ascending rank","Example taxon"],"rows":[["Species","Sapiens"],["Genus","Homo"],["Family","Hominidae"],["Order","Primata"],["Class","Mammalia"],["Phylum/Division","Chordata"],["Kingdom","Animalia"]]}'::jsonb,
    '{"type":"bio-taxonomic-hierarchy"}'::jsonb,
    null,
    '{"recall_question":"Recall the taxonomic hierarchy in ascending order.","reveal_answer":"Species -> Genus -> Family -> Order -> Class -> Phylum/Division -> Kingdom.","key_points":["A group occupying a category is called a taxon."],"examples":["Class Mammalia"],"neet_traps":[]}'::jsonb,
    5,
    3,
    11,
    true
  ),
  (
    'neet-biology-the-living-world-species-genus',
    'neet-biology-the-living-world',
    'Species and Genus',
    'examples',
    'Species is the lowest category; genus aggregates closely related species.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Common name","Generic name","Specific epithet"],"rows":[["Mango","Mangifera","indica"],["Potato","Solanum","tuberosum"],["Nightshade","Solanum","nigrum"],["Tomato","Solanum","lycopersicum"],["Brinjal","Solanum","melongena"],["Lion","Panthera","leo"],["Tiger","Panthera","tigris"],["Leopard","Panthera","pardus"],["Modern man","Homo","sapiens"]]}'::jsonb,
    null,
    null,
    '{"recall_question":"Species vs genus: what should you recall?","reveal_answer":"Species is closely related interbreeding organisms producing fertile offspring; genus is an aggregate of closely related species.","key_points":["Species is the lowest category."],"examples":["Solanum: potato, tomato, brinjal","Panthera: lion, leopard, tiger"],"neet_traps":[]}'::jsonb,
    5,
    4,
    12,
    true
  ),
  (
    'neet-biology-the-living-world-higher-taxa',
    'neet-biology-the-living-world',
    'Family to Kingdom',
    'classification',
    'Higher taxa are assemblages of related lower taxa.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Category","Definition","Source examples"],"rows":[["Family","Group of closely related genera.","Solanaceae includes Solanum, Petunia, Datura; Felidae includes Panthera and Felis."],["Order","Assemblage of related families.","Polymoniales includes Convolvulaceae and Solanaceae; Carnivora includes Felidae and Canidae."],["Class","Assemblage of related orders.","Primata, Carnivora etc. placed in Mammalia."],["Phylum/Division","Assemblage of related classes.","Amphibia, Reptilia, Aves, Mammalia under Chordata."],["Kingdom","Assemblage of related phyla; highest category.","Plantae, Animalia."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"How do family, order, class, phylum/division and kingdom relate?","reveal_answer":"Each higher category is an assemblage of related lower categories.","key_points":[],"examples":[],"neet_traps":["Division is used in case of plants."]}'::jsonb,
    4,
    4,
    13,
    true
  ),
  (
    'neet-biology-the-living-world-organism-taxonomy-table',
    'neet-biology-the-living-world',
    'Organisms with Taxonomic Categories',
    'table',
    'The source compares taxonomic categories for man, housefly, mango and wheat.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Category","Man","Housefly","Mango","Wheat"],"rows":[["Biological name","Homo sapiens","Musca domestica","Mangifera indica","Triticum aestivum"],["Species","sapiens","domestica","indica","aestivum"],["Genus","Homo","Musca","Mangifera","Triticum"],["Family","Hominidae","Muscidae","Anacardiaceae","Poaceae"],["Order","Primata","Diptera","Sapindales","Poales"],["Class","Mammalia","Insecta","Dicotyledonae","Monocotyledonae"],["Phylum/Division","Chordata","Arthropoda","Angiospermae","Angiospermae"],["Kingdom","Animalia","Animalia","Plantae","Plantae"]]}'::jsonb,
    null,
    null,
    '{"recall_question":"What are the four organisms in the source taxonomy table?","reveal_answer":"Man, housefly, mango and wheat.","key_points":[],"examples":["Homo sapiens","Musca domestica","Mangifera indica","Triticum aestivum"],"neet_traps":[]}'::jsonb,
    5,
    4,
    14,
    true
  ),
  (
    'neet-biology-the-living-world-taxonomical-aids-comparison',
    'neet-biology-the-living-world',
    'Taxonomical Aids Comparison',
    'comparison',
    'Taxonomical aids support identification, study and reference.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Aid","Recall use","Key source detail"],"rows":[["Herbarium","Repository of dried, pressed and preserved plant specimens.","Sheets are labelled with date/place of collection, English/local/botanical names, family and collector''s name."],["Botanical gardens","Living plant collections for reference and identification.","Each plant is labelled with botanical name and family."],["Biological Museum","Collection of preserved plants and animals for study and reference.","Includes preservative jars, dry specimens, insect boxes, stuffed animals and skeletons."],["Zoological Parks","Live wild animals kept in protected environments under human care.","Helps learn food habits and behaviour."],["Key","Analytical method of identification based on similarities and dissimilarities.","Based on contrasting paired characters called couplet; each statement is a lead."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"Compare herbarium, botanical garden, museum, zoo and key.","reveal_answer":"Herbarium preserves plant specimens; botanical gardens keep living plants; museums keep preserved specimens; zoos keep live wild animals; keys identify by contrasting couplets.","key_points":[],"examples":["Royal Botanical Garden at Kew","Indian Botanical Garden, Howrah","National Botanical Research Institute, Lucknow"],"neet_traps":[]}'::jsonb,
    5,
    4,
    15,
    true
  ),
  (
    'neet-biology-the-living-world-flora-manuals-monographs-catalogue',
    'neet-biology-the-living-world',
    'Flora, Manuals, Monographs and Catalogue',
    'comparison',
    'The source gives four quick-reference records used in taxonomy.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Record","Recall answer"],"rows":[["Flora","Actual account of habitat and distribution of plant species of a given area."],["Manuals","Record containing information for identification of names of species found in an area."],["Monographs","Records containing information on any one taxon."],["Catalogue","Alphabetical list of species."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"Flora vs manuals vs monographs vs catalogue?","reveal_answer":"Flora = habitat/distribution; manuals = identification of names in an area; monographs = one taxon; catalogue = alphabetical species list.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb,
    4,
    4,
    16,
    true
  ),
  (
    'neet-biology-biological-classification-early-classification',
    'neet-biology-biological-classification',
    'Aristotle and Linnaeus',
    'classification',
    'The source contrasts Aristotle''s early scientific attempt with Linnaeus''s two-kingdom classification.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["System","Recall answer"],"rows":[["Aristotle","Plants into trees, shrubs and herbs; animals into those with red blood and without red blood."],["Linnaeus (1758)","Two kingdoms: Kingdom Plantae and Kingdom Animalia."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"What were Aristotle''s and Linnaeus''s classification bases?","reveal_answer":"Aristotle used plant habit and animal blood; Linnaeus used Plantae and Animalia.","key_points":[],"examples":[],"neet_traps":["Linnaeus year in source: 1758."]}'::jsonb,
    4,
    5,
    1,
    true
  ),
  (
    'neet-biology-biological-classification-two-kingdom-drawbacks',
    'neet-biology-biological-classification',
    'Drawbacks of Two-Kingdom Classification',
    'neet_trap',
    'The two-kingdom system grouped organisms together despite major differences.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    null,
    null,
    null,
    '{"recall_question":"What drawbacks of the two-kingdom classification are listed?","reveal_answer":"It grouped prokaryotes with eukaryotes, unicellular with multicellular forms, and heterotrophic fungi with autotrophic green plants.","key_points":["Bacteria/cyanobacteria and fungi/mosses/ferns/gymnosperms/angiosperms were included under plants based on cell wall.","Chlamydomonas and Spirogyra were placed under algae.","Fungi have chitinous cell wall; green plants have cellulosic cell wall."],"examples":[],"neet_traps":[]}'::jsonb,
    5,
    5,
    2,
    true
  ),
  (
    'neet-biology-biological-classification-five-kingdom-criteria',
    'neet-biology-biological-classification',
    'Whittaker Five Kingdom Classification',
    'classification',
    'R.H. Whittaker proposed five kingdoms in 1969.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    null,
    null,
    null,
    '{"recall_question":"What are Whittaker''s five kingdoms and criteria?","reveal_answer":"Monera, Protista, Fungi, Plantae and Animalia; based on cell structure, thallus organization, mode of nutrition, reproduction and phylogenetic relationships.","key_points":["Three-domain system divides Kingdom Monera into two domains; eukaryotic kingdoms are in the third domain."],"examples":[],"neet_traps":[]}'::jsonb,
    5,
    5,
    3,
    true
  ),
  (
    'neet-biology-biological-classification-five-kingdom-comparison',
    'neet-biology-biological-classification',
    'Five Kingdom Comparison',
    'comparison',
    'The source table compares the five kingdoms by cell type, wall, nuclear membrane, organization and nutrition.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Character","Monera","Protista","Fungi","Plantae","Animalia"],"rows":[["Cell type","Prokaryotic","Eukaryotic","Eukaryotic","Eukaryotic","Eukaryotic"],["Cell wall","Non-cellulosic (polysaccharide + amino acid)","Present in some","Present (Chitin & polysaccharides)","Present (Cellulose)","Absent"],["Nuclear membrane","Absent","Present","Present","Present","Present"],["Body organisation","Cellular","Cellular","Multicellular, loose tissue","Tissue/organ","Tissue/organ/organ system"],["Mode of nutrition","Autotrophic and heterotrophic","Autotrophic and heterotrophic","Heterotrophic","Autotrophic","Heterotrophic"]]}'::jsonb,
    null,
    null,
    '{"recall_question":"Fast compare the five kingdoms.","reveal_answer":"Monera is prokaryotic; the other four are eukaryotic. Animalia lacks cell wall; Plantae has cellulose wall; Fungi has chitin and polysaccharide wall.","key_points":[],"examples":[],"neet_traps":["Monera is the only one with absent nuclear membrane."]}'::jsonb,
    5,
    5,
    4,
    true
  ),
  (
    'neet-biology-biological-classification-monera-bacteria-shapes',
    'neet-biology-biological-classification',
    'Monera and Bacterial Shapes',
    'classification',
    'Bacteria are the most abundant microorganisms and occur even in extreme habitats.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Shape","Source term"],"rows":[["Spherical","Coccus"],["Rod-shaped","Bacillus"],["Comma-shaped","Vibrium"],["Spiral","Spirillum"]]}'::jsonb,
    null,
    null,
    '{"recall_question":"Name the four bacterial shapes in the source.","reveal_answer":"Coccus, Bacillus, Vibrium and Spirillum.","key_points":["Some bacteria are autotrophic; majority are heterotrophs."],"examples":[],"neet_traps":[]}'::jsonb,
    4,
    5,
    5,
    true
  ),
  (
    'neet-biology-biological-classification-archaebacteria-vs-eubacteria',
    'neet-biology-biological-classification',
    'Archaebacteria vs Eubacteria',
    'comparison',
    'The source separates archaebacteria from true bacteria.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Group","Key recall","Examples/source details"],"rows":[["Archaebacteria","Live in harshest habitats and have different cell wall structure.","Halophiles, thermoacidophiles, methanogens; methanogens occur in guts of cows and buffaloes and produce methane/biogas."],["Eubacteria","True bacteria with rigid cell wall and flagellum if motile.","Include autotrophs and heterotrophs."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"Archaebacteria vs eubacteria?","reveal_answer":"Archaebacteria survive extreme conditions with different cell wall structure; eubacteria are true bacteria with rigid wall and flagellum if motile.","key_points":[],"examples":["halophiles","thermoacidophiles","methanogens"],"neet_traps":[]}'::jsonb,
    5,
    5,
    6,
    true
  ),
  (
    'neet-biology-biological-classification-eubacteria-types',
    'neet-biology-biological-classification',
    'Eubacteria Types',
    'comparison',
    'Eubacteria include photosynthetic autotrophs, chemosynthetic autotrophs and heterotrophs.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Type","Recall answer","Examples/roles"],"rows":[["Cyanobacteria","Photosynthetic autotrophs with chlorophyll a similar to green plants.","Unicellular, colonial or filamentous; Nostoc and Anabaena fix atmospheric nitrogen in heterocysts."],["Chemosynthetic autotrophs","Oxidize inorganic substances such as nitrates, nitrites and ammonia for ATP production.","Recycle nitrogen, phosphorous, iron and sulphur."],["Heterotrophic bacteria","Most abundant in nature; major decomposers.","Curd, antibiotics, nitrogen fixation; diseases: cholera, typhoid, tetanus, citrus canker."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"What are the three eubacterial groups emphasized?","reveal_answer":"Cyanobacteria, chemosynthetic autotrophs and heterotrophic bacteria.","key_points":[],"examples":["Nostoc","Anabaena","cholera","typhoid","tetanus","citrus canker"],"neet_traps":[]}'::jsonb,
    5,
    5,
    7,
    true
  ),
  (
    'neet-biology-biological-classification-bacterial-reproduction-mycoplasma',
    'neet-biology-biological-classification',
    'Bacterial Reproduction and Mycoplasma',
    'fact',
    'Bacteria mainly reproduce by fission and produce spores under unfavourable conditions.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    null,
    null,
    null,
    '{"recall_question":"How do bacteria reproduce, and what is special about Mycoplasma?","reveal_answer":"Bacteria mainly reproduce by fission; they form spores in unfavourable conditions and can transfer DNA sexually. Mycoplasmas lack cell wall and are the smallest living cells.","key_points":["Mycoplasmas can survive without oxygen.","Many are pathogenic in animals and plants."],"examples":[],"neet_traps":[]}'::jsonb,
    5,
    6,
    8,
    true
  ),
  (
    'neet-biology-biological-classification-protista-overview',
    'neet-biology-biological-classification',
    'Kingdom Protista',
    'classification',
    'Protista includes single-celled eukaryotes and links plants, animals and fungi.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    null,
    null,
    null,
    '{"recall_question":"What are the source traits of Protista?","reveal_answer":"Single-celled eukaryotes with well-defined nucleus and membrane-bound organelles; primarily aquatic; reproduce asexually and sexually.","key_points":["Some protists have flagella or cilia.","Groups: Chrysophytes, Dianoflagellates, Euglenoids, Slime moulds, Protozoans."],"examples":[],"neet_traps":[]}'::jsonb,
    4,
    6,
    9,
    true
  ),
  (
    'neet-biology-biological-classification-protist-groups',
    'neet-biology-biological-classification',
    'Protist Groups',
    'comparison',
    'The source naturally compares major protist groups.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Group","Recall hook","Examples/source facts"],"rows":[["Chrysophytes","Diatoms and golden algae/desmids; planktonic, mostly photosynthetic.","Diatomaceous earth used in polishing and filtration of oils and syrups; diatoms are chief producers in oceans."],["Dinoflagellates","Mostly marine, photosynthetic, with stiff cellulose plates and two flagella.","Gonyaulax causes red tides and releases toxins that kill fishes."],["Euglenoids","Freshwater stagnant forms with protein-rich pellicle instead of cell wall.","Photosynthetic in sunlight; heterotrophic without sunlight; example Euglena."],["Slime moulds","Saprophytic protists forming plasmodium and resistant spores.","Spores survive many years and disperse by air."],["Protozoans","Heterotrophs, primitive relatives of animals.","Amoeba, Entamoeba, Trypanosoma, Paramoecium, Plasmodium."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"Compare the five protist groups from the source.","reveal_answer":"Chrysophytes, Dinoflagellates, Euglenoids, Slime moulds and Protozoans have distinct nutrition, coverings, movement and examples.","key_points":[],"examples":["Euglena","Gonyaulax","Amoeba","Entamoeba","Trypanosoma","Paramoecium","Plasmodium"],"neet_traps":[]}'::jsonb,
    5,
    6,
    10,
    true
  ),
  (
    'neet-biology-biological-classification-protozoan-groups',
    'neet-biology-biological-classification',
    'Four Protozoan Groups',
    'classification',
    'Protozoans are heterotrophs and primitive relatives of animals.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Protozoan group","Recall feature","Example"],"rows":[["Amoeboid protozoans","Move and capture prey by pseudopodia; marine forms may have silica shells.","Amoeba; Entamoeba"],["Flagellated protozoans","Free-living or parasitic with flagella; parasitic forms cause sleeping sickness.","Trypanosoma"],["Ciliated protozoans","Aquatic, actively moving with cilia; gullet opens outside.","Paramoecium"],["Sporozoans","Infectious spore-like stage in life cycle.","Plasmodium (malarial parasite)"]]}'::jsonb,
    null,
    null,
    '{"recall_question":"What are the four major protozoan groups?","reveal_answer":"Amoeboid, flagellated, ciliated and sporozoans.","key_points":[],"examples":["Amoeba","Entamoeba","Trypanosoma","Paramoecium","Plasmodium"],"neet_traps":[]}'::jsonb,
    5,
    6,
    11,
    true
  ),
  (
    'neet-biology-biological-classification-fungi-overview-hyphae',
    'neet-biology-biological-classification',
    'Fungi, Hyphae and Mycelium',
    'concept',
    'Fungi are a unique kingdom of heterotrophic organisms; except yeasts, fungi are filamentous.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Term","Recall answer"],"rows":[["Hyphae","Thread-like structures forming fungal body."],["Mycelium","Network of hyphae."],["Coenocytic hyphae","Continuous tubes filled with multinucleated cytoplasm."],["Septate hyphae","Hyphae with septae or cross walls."],["Cell wall","Made of chitin and polysaccharides."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"Coenocytic vs septate hyphae?","reveal_answer":"Coenocytic hyphae are continuous multinucleated tubes; septate hyphae have cross walls.","key_points":[],"examples":["yeast","Penicillium","Puccinia"],"neet_traps":[]}'::jsonb,
    5,
    6,
    12,
    true
  ),
  (
    'neet-biology-biological-classification-fungal-reproduction',
    'neet-biology-biological-classification',
    'Fungal Reproduction',
    'process',
    'Fungi reproduce vegetatively, asexually and sexually.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Mode","Source-backed recall"],"rows":[["Vegetative propagation","Fragmentation, fission and budding."],["Asexual reproduction","Spores such as conidia, sporangiospores and zoospores."],["Sexual reproduction","Oospores, ascospores and basidiospores in fruiting bodies."],["Sexual cycle","Plasmogamy, karyogamy and meiosis in zygote."],["Dikaryon","Dikaryotic stage (n + n) in ascomycetes and basidiomycetes."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"Recall the fungal sexual cycle.","reveal_answer":"Plasmogamy -> karyogamy -> meiosis in zygote to give haploid spores.","key_points":["Dikaryophase means two nuclei per cell, n + n."],"examples":[],"neet_traps":[]}'::jsonb,
    5,
    7,
    13,
    true
  ),
  (
    'neet-biology-biological-classification-fungal-classes-comparison',
    'neet-biology-biological-classification',
    'Fungal Classes Comparison',
    'comparison',
    'Fungi are classified by morphology of mycelium, mode of spore formation and fruiting bodies.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Class","Mycelium","Asexual","Sexual","Examples"],"rows":[["Phycomycetes","Aseptate and coenocytic","Motile zoospores or non-motile aplanospores in sporangium","Zygospores by fusion of gametes","Mucor, Rhizopus (bread mould), Albugo"],["Ascomycetes","Branched and septate","Conidia exogenously on conidiophores","Ascospores endogenously in asci; asci form ascocarps","Aspergillus, Claviceps, Neurospora"],["Basidiomycetes","Branched and septate","Generally not found; fragmentation common","Basidiospores exogenously on basidium; basidia in basidiocarps","Agaricus, Ustilago, Puccinia"],["Deuteromycetes","Septate and branched","Only asexual spores (conidia)","Sexual phase not known","Alternaria, Colletotrichum, Trichoderma"]]}'::jsonb,
    null,
    null,
    '{"recall_question":"Compare phycomycetes, ascomycetes, basidiomycetes and deuteromycetes.","reveal_answer":"Use mycelium and spore type: phycomycetes coenocytic; ascomycetes asci; basidiomycetes basidia; deuteromycetes only asexual/vegetative phase known.","key_points":[],"examples":["Mucor","Rhizopus","Albugo","Aspergillus","Claviceps","Neurospora","Agaricus","Ustilago","Puccinia","Alternaria","Colletotrichum","Trichoderma"],"neet_traps":[]}'::jsonb,
    5,
    7,
    14,
    true
  ),
  (
    'neet-biology-biological-classification-plantae-animalia',
    'neet-biology-biological-classification',
    'Plantae vs Animalia',
    'comparison',
    'The source summarizes Plantae and Animalia after fungi.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Kingdom","Recall answer","Examples/source details"],"rows":[["Plantae","Eukaryotic chlorophyll-containing organisms with cellulosic cell wall.","Includes algae, bryophytes, pteridophytes, gymnosperms and angiosperms; partial heterotrophs include bladderwort, Venus flytrap; parasite Cuscuta."],["Animalia","Multicellular, heterotrophic, eukaryotic organisms without cell wall.","Holozoic nutrition; reserve food as glycogen or fat; most can locomote."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"Plantae vs Animalia in five-kingdom classification?","reveal_answer":"Plantae are chlorophyll-containing with cellulosic wall; Animalia are multicellular heterotrophs without cell wall.","key_points":[],"examples":["bladderwort","Venus flytrap","Cuscuta"],"neet_traps":[]}'::jsonb,
    4,
    7,
    15,
    true
  ),
  (
    'neet-biology-biological-classification-virus-viroid-prion',
    'neet-biology-biological-classification',
    'Virus vs Viroid vs Prion',
    'comparison',
    'Acellular organisms are not included in five-kingdom classification.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Agent","Recall answer","Source facts"],"rows":[["Virus","Non-cellular, not truly living, obligate parasite; nucleoprotein with capsid and RNA or DNA.","No virus contains both RNA and DNA; plant viruses generally ssRNA; bacteriophages usually dsDNA."],["Viroid","Free low molecular weight RNA with no protein coat; smaller than viruses.","Discovered by T.O. Diener (1971); potato spindle tuber disease."],["Prion","Abnormally folded protein causing infectious neurological diseases.","BSE/mad cow disease in cattle and variant Cr-Jacob disease (CJD) in humans."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"Virus vs viroid vs prion?","reveal_answer":"Virus = nucleoprotein with capsid and one nucleic acid type; viroid = free low molecular weight RNA without protein coat; prion = abnormally folded protein.","key_points":[],"examples":["mumps","small pox","herpes","influenza","AIDS","potato spindle tuber disease","BSE","CJD"],"neet_traps":["No virus contains both RNA and DNA."]}'::jsonb,
    5,
    8,
    16,
    true
  ),
  (
    'neet-biology-biological-classification-virus-history',
    'neet-biology-biological-classification',
    'Virus Discovery Timeline',
    'sequence',
    'The source names four scientists in virus history.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Scientist","Year/source contribution"],"rows":[["Louis Pasteur","Gave the name virus, meaning venom or poisonous fluid."],["D.J. Ivanowsky","1892: discovered virus while studying tobacco mosaic disease."],["M.W. Beijerinek","1898: called infected extract Contagium vivum fluidum."],["W.M. Stanley","1935: showed viruses could be crystallized and crystals largely consist of proteins."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"Recall the virus-history sequence.","reveal_answer":"Pasteur named virus; Ivanowsky discovered virus in 1892; Beijerinek named infectious living fluid in 1898; Stanley crystallized viruses in 1935.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb,
    4,
    8,
    17,
    true
  ),
  (
    'neet-biology-biological-classification-lichens',
    'neet-biology-biological-classification',
    'Lichens',
    'concept',
    'Lichens are symbiotic associations between algae and fungi.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    null,
    null,
    null,
    '{"recall_question":"What is a lichen and why is it a pollution indicator?","reveal_answer":"It is a mutually useful association between algae and fungi; lichens do not grow in polluted areas.","key_points":["Algal component is phycobiont and is autotrophic.","Fungal component is mycobiont and is heterotrophic.","Algae prepare food; fungi provide shelter and absorb mineral nutrients and water."],"examples":[],"neet_traps":[]}'::jsonb,
    5,
    8,
    18,
    true
  ),
  (
    'neet-biology-plant-kingdom-classification-systems',
    'neet-biology-plant-kingdom',
    'Plant Classification Systems',
    'comparison',
    'The source compares artificial, natural and phylogenetic classification systems.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["System","Basis","Source detail"],"rows":[["Artificial","Vegetative or superficial morphological characters.","Linnaeus''s artificial system was based on androecium structure; drawbacks include separating related species and equal weightage to vegetative and sexual characters."],["Natural","Natural affinities among organisms.","Considers external and internal features: ultrastructure, anatomy, embryology and phytochemistry; Bentham and Hooker classification."],["Phylogenetic","Evolutionary relationships.","Assumes organisms in the same taxa have a common ancestor."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"Artificial vs natural vs phylogenetic plant classification?","reveal_answer":"Artificial uses superficial characters; natural uses natural affinities and internal/external features; phylogenetic uses evolutionary relationships.","key_points":[],"examples":["George Bentham","Joseph Dalton Hooker"],"neet_traps":[]}'::jsonb,
    5,
    9,
    1,
    true
  ),
  (
    'neet-biology-plant-kingdom-taxonomy-methods',
    'neet-biology-plant-kingdom',
    'Numerical, Cyto and Chemotaxonomy',
    'comparison',
    'The source lists three additional sources for resolving classification problems.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Method","Recall answer"],"rows":[["Numerical taxonomy","Based on all observable characteristics; numbers and codes are assigned and computer processed."],["Cytotaxonomy","Based on cytological information such as chromosome number, structure and behaviour."],["Chemotaxonomy","Uses chemical constituents of plants."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"Numerical taxonomy vs cytotaxonomy vs chemotaxonomy?","reveal_answer":"Numerical = observable coded characters; cytotaxonomy = chromosome/cytological information; chemotaxonomy = chemical constituents.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb,
    4,
    9,
    2,
    true
  ),
  (
    'neet-biology-plant-kingdom-algae-overview',
    'neet-biology-plant-kingdom',
    'Algae Overview',
    'concept',
    'Algae are simple, thalloid, autotrophic, chlorophyll-bearing aquatic organisms.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    null,
    null,
    null,
    '{"recall_question":"What are the source traits and forms of algae?","reveal_answer":"Simple thalloid autotrophs, mostly aquatic; forms vary from unicellular to colonial to filamentous.","key_points":["They also occur on moist stones, soils and wood.","Some occur with fungi in lichen and with animals such as on sloth bear."],"examples":["Chlamydomonas","Volvox","Ulothrix","Spirogyra"],"neet_traps":[]}'::jsonb,
    5,
    9,
    3,
    true
  ),
  (
    'neet-biology-plant-kingdom-algae-reproduction',
    'neet-biology-plant-kingdom',
    'Reproduction in Algae',
    'process',
    'Algae reproduce vegetatively, asexually and sexually.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Mode","Recall answer","Examples/source details"],"rows":[["Vegetative","By fragmentation; each fragment develops into a thallus.",""],["Asexual","By spores; zoospores are most common, flagellated and motile.","Zoospores germinate to new plants."],["Isogamous sexual","Fusion of gametes similar in size.","Flagellated Ulothrix; non-flagellated Spirogyra."],["Anisogamous sexual","Fusion of two gametes dissimilar in size.","Some species of Eudorina."],["Oogamous sexual","Large non-motile female gamete and smaller motile male gamete.","Volvox, Fucus."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"Isogamy vs anisogamy vs oogamy in algae?","reveal_answer":"Isogamy = similar gametes; anisogamy = dissimilar gametes; oogamy = large non-motile female and smaller motile male gamete.","key_points":[],"examples":["Ulothrix","Spirogyra","Eudorina","Volvox","Fucus"],"neet_traps":[]}'::jsonb,
    5,
    9,
    4,
    true
  ),
  (
    'neet-biology-plant-kingdom-algae-economic-importance',
    'neet-biology-plant-kingdom',
    'Algae Economic Importance',
    'examples',
    'The source lists ecological and commercial benefits of algae.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Benefit","Source detail"],"rows":[["Photosynthesis","Fix half of the total CO2 on earth and increase dissolved oxygen."],["Food cycles","Primary producers and basis of food cycles of all aquatic animals."],["Food","Many marine algae (70 species) used as food: Porphyra, Laminaria, Sargassum."],["Agar","From Gelidium and Gracilaria; used to grow microbes and in ice-creams and jellies."],["Hydrocolloids","Algin from brown algae and carrageen from red algae; commercially used."],["Food supplements","Chlorella and Spirullina used as food supplements by space travellers."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"Recall the source examples for economic importance of algae.","reveal_answer":"Porphyra, Laminaria, Sargassum, Gelidium, Gracilaria, Chlorella and Spirullina.","key_points":[],"examples":["algin","carrageen"],"neet_traps":[]}'::jsonb,
    5,
    9,
    5,
    true
  ),
  (
    'neet-biology-plant-kingdom-algae-groups-comparison',
    'neet-biology-plant-kingdom',
    'Green vs Brown vs Red Algae',
    'comparison',
    'The source table compares Chlorophyceae, Phaeophyceae and Rhodophyceae.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Character","Chlorophyceae","Phaeophyceae","Rhodophyceae"],"rows":[["Major pigments","Chlorophyll a, b","Chlorophyll a, c, Fucoxanthin","Chlorophyll a, d, Phycoerythrin"],["Stored food","Starch","Mannitol, laminarin","Floridean Starch"],["Cell wall","Cellulose","Cellulose and algin","Cellulose"],["Flagella","2-8, equal, apical","2, unequal, lateral","Absent"],["Habitat","Fresh water, salt water and brackish water","Fresh water (rare), salt water and brackish water","Fresh water (some), salt water (most) and brackish water"]]}'::jsonb,
    '{"type":"bio-algae-comparison"}'::jsonb,
    null,
    '{"recall_question":"Compare Chlorophyceae, Phaeophyceae and Rhodophyceae.","reveal_answer":"Green algae: chlorophyll a,b and starch; brown algae: chlorophyll a,c, fucoxanthin and mannitol/laminarin; red algae: chlorophyll a,d, phycoerythrin and floridean starch.","key_points":[],"examples":["Chlamydomonas","Volvox","Ulothrix","Spirogyra","Chara","Ectocarpus","Dictyota","Laminaria","Sargassum","Fucus","Polysiphonia","Porphyra","Gracilaria","Gelidium"],"neet_traps":[]}'::jsonb,
    5,
    10,
    6,
    true
  ),
  (
    'neet-biology-plant-kingdom-bryophytes',
    'neet-biology-plant-kingdom',
    'Bryophytes',
    'concept',
    'Bryophytes are called amphibians of the plant kingdom because they need water for sexual reproduction.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    null,
    null,
    null,
    '{"recall_question":"Why are bryophytes called amphibians of the plant kingdom?","reveal_answer":"They can live in soil but need water for sexual reproduction.","key_points":["They occur in damp, humid and shaded localities.","Main plant body is haploid gametophyte.","They lack true roots, stem or leaves but may possess root-like, leaf-like or stem-like structures."],"examples":[],"neet_traps":[]}'::jsonb,
    5,
    10,
    7,
    true
  ),
  (
    'neet-biology-plant-kingdom-liverworts-mosses',
    'neet-biology-plant-kingdom',
    'Liverworts vs Mosses',
    'comparison',
    'The source divides bryophytes into liverworts and mosses.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Group","Recall points","Examples"],"rows":[["Liverworts","Usually moist shady habitats; plant body thalloid; asexual reproduction by fragmentation or gemmae; sporophyte has foot, seta and capsule.","Marchantia"],["Mosses","Gametophyte has protonema and leafy stage; vegetative reproduction by fragmentation and budding; sporophyte has foot, seta and capsule with spores.","Funaria, Polytrichum, Sphagnum"]]}'::jsonb,
    null,
    null,
    '{"recall_question":"Liverworts vs mosses?","reveal_answer":"Liverworts have thalloid body and gemmae; mosses have protonema and leafy stages.","key_points":[],"examples":["Marchantia","Funaria","Polytrichum","Sphagnum"],"neet_traps":[]}'::jsonb,
    5,
    11,
    8,
    true
  ),
  (
    'neet-biology-plant-kingdom-bryophytes-vs-pteridophytes',
    'neet-biology-plant-kingdom',
    'Bryophytes vs Pteridophytes',
    'comparison',
    'The source contrasts dominant phases and vascular tissues.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Character","Bryophytes","Pteridophytes"],"rows":[["Dominant phase","Gametophyte","Sporophyte"],["Plant body","Thallus-like, prostrate or erect, with rhizoids","Differentiated into true root, stem and leaves"],["Vascular tissue","Not listed as present","First terrestrial plants with xylem and phloem"],["Fertilization","Needs water","Needs water for antherozoid transfer"],["Sporophyte","Attached to photosynthetic gametophyte","Main plant body"]]}'::jsonb,
    null,
    null,
    '{"recall_question":"Bryophytes vs pteridophytes in one line?","reveal_answer":"Bryophytes are gametophyte-dominant and non-vascular; pteridophytes are sporophyte-dominant vascular plants.","key_points":[],"examples":[],"neet_traps":["Pteridophytes are first terrestrial plants with vascular tissues."]}'::jsonb,
    5,
    11,
    9,
    true
  ),
  (
    'neet-biology-plant-kingdom-pteridophytes-spores-seed-habit',
    'neet-biology-plant-kingdom',
    'Pteridophytes, Homospory and Heterospory',
    'classification',
    'Pteridophytes include horsetails and ferns; the main plant body is a sporophyte.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Term","Recall answer","Examples"],"rows":[["Sporophylls","Leaf-like appendages subtending sporangia.","May form strobili/cones in Selaginella, Equisetum."],["Homospory","Similar kinds of spores.","Most pteridophytes."],["Heterospory","Macro/mega and micro spores.","Selaginella, Salvinia."],["Seed habit precursor","Female gametophytes retained on parent sporophyte; zygote develops into young embryo.","Important evolutionary step."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"How is heterospory linked to seed habit precursor?","reveal_answer":"Megaspores and microspores form female and male gametophytes; female gametophyte retention on parent sporophyte with embryo development is precursor to seed habit.","key_points":[],"examples":["Selaginella","Salvinia","Psilotum","Lycopodium","Equisetum","Dryopteris","Pteris","Adiantum"],"neet_traps":[]}'::jsonb,
    5,
    11,
    10,
    true
  ),
  (
    'neet-biology-plant-kingdom-gymnosperms',
    'neet-biology-plant-kingdom',
    'Gymnosperms',
    'concept',
    'Gymnosperms are plants with naked ovules and seeds.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    null,
    null,
    null,
    '{"recall_question":"What defines gymnosperms?","reveal_answer":"Ovules are not enclosed by ovary wall and remain exposed before and after fertilization; seeds are naked.","key_points":["Sequoia (giant redwood) is the tallest tree species.","Pinus roots may have mycorrhiza.","Cycas has coralloid roots with N2-fixing cyanobacteria.","Pinus and Cedrus have needle-like leaves with thick cuticle and sunken stomata to reduce water loss."],"examples":["Pinus","Cycas","Cedrus","Sequoia"],"neet_traps":[]}'::jsonb,
    5,
    12,
    11,
    true
  ),
  (
    'neet-biology-plant-kingdom-gymnosperm-reproduction',
    'neet-biology-plant-kingdom',
    'Gymnosperm Reproduction',
    'process',
    'Gymnosperms are heterosporous and produce microspores and megaspores.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    null,
    null,
    null,
    '{"recall_question":"Recall the gymnosperm reproductive flow.","reveal_answer":"Sporophylls form cones; microsporophylls produce pollen grains; megasporophylls bear ovules; pollen reaches ovule, pollen tube carries male gametes, fertilization makes embryo and ovule becomes seed.","key_points":["Male and female gametophytes do not have independent free-living existence.","Male/female cones may be on same tree (Pinus) or different trees (Cycas)."],"examples":[],"neet_traps":[]}'::jsonb,
    5,
    12,
    12,
    true
  ),
  (
    'neet-biology-plant-kingdom-angiosperms-monocots-dicots',
    'neet-biology-plant-kingdom',
    'Angiosperms and Monocots vs Dicots',
    'comparison',
    'Angiosperms are flowering plants and include dicotyledons and monocotyledons.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Class","Seed cotyledons","Leaf venation","Flower members"],"rows":[["Dicotyledons","2 cotyledons","Reticulate","Tetramerous or pentamerous (4 or 5 members in each floral whorl)"],["Monocotyledons","One cotyledon","Parallel","Trimerous (3 members in each floral whorl)"]]}'::jsonb,
    null,
    null,
    '{"recall_question":"Monocots vs dicots?","reveal_answer":"Dicots: 2 cotyledons, reticulate venation, 4/5 floral whorl members. Monocots: one cotyledon, parallel venation, 3 floral whorl members.","key_points":["Angiosperms range from Wolffia to Eucalyptus over 100 metres."],"examples":["Wolffia","Eucalyptus"],"neet_traps":[]}'::jsonb,
    5,
    12,
    13,
    true
  ),
  (
    'neet-biology-plant-kingdom-double-fertilisation',
    'neet-biology-plant-kingdom',
    'Double Fertilisation',
    'process',
    'Double fertilisation is unique to angiosperms.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    null,
    null,
    null,
    '{"recall_question":"What two fusions make double fertilisation?","reveal_answer":"One male gamete fuses with egg cell to form zygote (syngamy); the other fuses with diploid secondary nucleus to form triploid primary endosperm nucleus (PEN).","key_points":["PEN develops into endosperm.","Ovules develop into seeds and ovaries into fruit.","Synergids and antipodals degenerate after fertilization."],"examples":[],"neet_traps":["Double fertilisation is unique to angiosperms."]}'::jsonb,
    5,
    13,
    14,
    true
  ),
  (
    'neet-biology-plant-kingdom-alternation-flow',
    'neet-biology-plant-kingdom',
    'Alternation of Generations',
    'diagram',
    'Plant life cycles alternate between gametophyte (n) and sporophyte (2n).',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    null,
    '{"type":"bio-alternation-flow"}'::jsonb,
    null,
    '{"recall_question":"Recall alternation of generations flow.","reveal_answer":"Gametophyte produces gametes by mitosis; fertilization forms zygote; zygote forms sporophyte by mitosis; sporophyte forms haploid spores by meiosis; spores form gametophyte by mitosis.","key_points":["Both haploid and diploid cells can divide by mitosis in plants."],"examples":[],"neet_traps":[]}'::jsonb,
    5,
    13,
    15,
    true
  ),
  (
    'neet-biology-plant-kingdom-life-cycle-patterns',
    'neet-biology-plant-kingdom',
    'Haplontic vs Diplontic vs Haplo-diplontic',
    'comparison',
    'The source compares three plant life-cycle patterns.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Pattern","Dominant phase","Source examples"],"rows":[["Haplontic","Free-living gametophyte; sporophyte represented only by zygote.","Volvox, Spirogyra, some species of Chlamydomonas."],["Diplontic","Diploid sporophyte dominant, photosynthetic and independent; gametophyte single to few-celled.","Fucus sp.; all seed-bearing plants (gymnosperms and angiosperms)."],["Haplo-diplontic","Both gametophyte and sporophyte multicellular and often free-living; different dominant phases.","Bryophytes and Pteridophytes."]]}'::jsonb,
    '{"type":"bio-life-cycle-patterns"}'::jsonb,
    null,
    '{"recall_question":"Haplontic vs diplontic vs haplo-diplontic?","reveal_answer":"Haplontic = gametophyte dominant and zygote-only sporophyte; diplontic = sporophyte dominant; haplo-diplontic = both phases multicellular.","key_points":[],"examples":["Volvox","Spirogyra","Chlamydomonas","Fucus sp.","Bryophytes","Pteridophytes"],"neet_traps":[]}'::jsonb,
    5,
    13,
    16,
    true
  ),
  (
    'neet-biology-animal-kingdom-basis-overview',
    'neet-biology-animal-kingdom',
    'Basis of Animal Classification',
    'classification',
    'The source uses levels of organization, symmetry, germ layers, coelom, metamerism and notochord.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Basis","Recall answer"],"rows":[["Levels of organization","Cellular, tissue, organ, organ-system levels."],["Symmetry","Asymmetrical or symmetrical; radial or bilateral."],["Germinal layers","Diploblastic or triploblastic."],["Coelom","Acoelomate, pseudocoelomate or coelomate."],["Metamerism","Repeated external/internal segments."],["Notochord","Mesodermally derived supporting rod on dorsal side during embryonic development."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"What are the six bases of animal classification in this source?","reveal_answer":"Levels of organization, body symmetry, germinal layers, coelom, metamerism and notochord.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb,
    5,
    14,
    1,
    true
  ),
  (
    'neet-biology-animal-kingdom-levels-symmetry',
    'neet-biology-animal-kingdom',
    'Levels of Organization and Symmetry',
    'comparison',
    'The source gives examples for each organization and symmetry type.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"sections":[{"columns":["Level","Recall answer","Examples"],"rows":[["Cellular","Cells arranged as loose cell aggregates.","Porifera"],["Tissue","Cells arranged into tissues.","Cnidarians and Ctenophores"],["Organ","Tissues arranged into organs.","Higher animals: Platyhelminthes to chordates"],["Organ system","Organs associated into organ systems.","Higher animals"]]},{"columns":["Symmetry","Recall answer","Examples"],"rows":[["Asymmetrical","Cannot be divided into two equal halves.","Most Poriferans, Snails"],["Radial","Two equal halves in any vertical plane along oral-aboral axis.","Some Poriferans, Cnidarians, Ctenophores, adult Echinoderms"],["Bilateral","Right and left halves in only one plane.","Platyhelminthes to Chordata except adult Echinodermata"]]}]}'::jsonb,
    null,
    null,
    '{"recall_question":"Which examples go with levels and symmetry?","reveal_answer":"Porifera = cellular; cnidarians/ctenophores = tissue; Platyhelminthes to chordates = organ/organ-system; radial includes cnidarians, ctenophores and adult echinoderms.","key_points":[],"examples":[],"neet_traps":["Adult Echinodermata are the exception to bilateral trend."]}'::jsonb,
    5,
    14,
    2,
    true
  ),
  (
    'neet-biology-animal-kingdom-germ-layers-coelom',
    'neet-biology-animal-kingdom',
    'Germ Layers and Coelom',
    'comparison',
    'Germ layers and coelom separate major animal groups.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"sections":[{"columns":["Type","Recall answer","Examples"],"rows":[["Diploblastic","Two germ layers: ectoderm and endoderm, with mesoglea between.","Cnidaria and Ctenophora"],["Triploblastic","Three germ layers: ectoderm, mesoderm and endoderm.","Platyhelminthes to Chordata"]]},{"columns":["Coelom type","Recall answer","Examples"],"rows":[["Acoelomate","No coelom; space filled with parenchyma.","Porifera to Platyhelminthes"],["Pseudocoelomate","False coelom not lined by mesoderm; mesoderm in scattered pouches.","Aschelminthes"],["Coelomate","True coelom arising from mesoderm and lined by peritoneal layer.","Annelida to Chordata"]]}]}'::jsonb,
    null,
    null,
    '{"recall_question":"Diploblastic vs triploblastic and acoelomate vs pseudocoelomate vs coelomate?","reveal_answer":"Diploblastic has two germ layers; triploblastic has three. Acoelomate has no coelom, pseudocoelomate has false coelom, coelomate has true mesoderm-lined coelom.","key_points":[],"examples":[],"neet_traps":["Aschelminthes are pseudocoelomate."]}'::jsonb,
    5,
    14,
    3,
    true
  ),
  (
    'neet-biology-animal-kingdom-metamerism-notochord',
    'neet-biology-animal-kingdom',
    'Metamerism and Notochord',
    'fact',
    'Metamerism and notochord are quick classification markers.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    null,
    null,
    null,
    '{"recall_question":"Define metamerism and notochord from the source.","reveal_answer":"Metamerism is repeated external/internal segmentation; notochord is a mesodermally derived dorsal supporting rod formed during embryonic development.","key_points":["Metamerism examples: Annelids (earthworm etc.) and Arthropods.","Animals with notochord are chordates; those without are non-chordates."],"examples":[],"neet_traps":[]}'::jsonb,
    5,
    14,
    4,
    true
  ),
  (
    'neet-biology-animal-kingdom-porifera-cnidaria-ctenophora',
    'neet-biology-animal-kingdom',
    'Porifera vs Cnidaria vs Ctenophora',
    'comparison',
    'The source table compares the first three non-chordate phyla.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Feature","Porifera","Cnidaria","Ctenophora"],"rows":[["Organization","Cellular","Tissue","Tissue"],["Symmetry","Asymmetrical; some radial","Radial","Radial"],["Germ layers","-","Diploblastic","Diploblastic"],["Coelom","Acoelomate","Acoelomate","Acoelomate"],["Habit","Aquatic mostly marine, sedentary, solitary/colonial","Aquatic mostly marine, sessile/free swimming, solitary/colonial","Exclusively marine, solitary and pelagic"],["Digestion","Absent digestive system; intracellular digestion","Incomplete; intracellular and extracellular","Incomplete; intracellular and extracellular"],["Unique","Water canal system, ostia, spongocoel, choanocytes, spicules/spongin","Cnidoblasts, coelenteron, polyp/medusa, metagenesis, CaCO3 corals","8 rows of ciliated comb plates, tentacles, bioluminescence"],["Examples","Sycon (Scypha), Spongilla, Euspongia","Hydra, Obelia, Aurelia, Physalia, Adamsia, Pennatula, Gorgonia, Meandrina","Ctenoplana, Pleurobrachia"]]}'::jsonb,
    null,
    null,
    '{"recall_question":"Compare Porifera, Cnidaria and Ctenophora.","reveal_answer":"Porifera = cellular and water canal system; Cnidaria = cnidoblasts and polyp/medusa; Ctenophora = comb plates and bioluminescence.","key_points":[],"examples":["Sycon","Spongilla","Euspongia","Hydra","Obelia","Aurelia","Physalia","Adamsia","Pennatula","Gorgonia","Meandrina","Ctenoplana","Pleurobrachia"],"neet_traps":[]}'::jsonb,
    5,
    15,
    5,
    true
  ),
  (
    'neet-biology-animal-kingdom-cnidarian-special-terms',
    'neet-biology-animal-kingdom',
    'Cnidarian and Poriferan Special Terms',
    'fact',
    'The notes below the table define high-yield terms.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Term","Recall answer"],"rows":[["Water canal system","Water enters through ostia into spongocoel and exits through osculum; used for food gathering, gas exchange and waste removal."],["Hermaphrodite/monoecious","Male and female sex organs in same individual."],["Cnidoblast/cnidocyte","Stinging cell with poison-filled nematocyst; anchorage, defense and prey capture."],["Polyp","Tubular attached asexual form with upward mouth and tentacles; Hydra, Adamsia."],["Medusa","Umbrella-like free-swimming sexual form with downward mouth and tentacles; Aurelia."],["Metagenesis","Polyps produce medusae asexually and medusae form polyps sexually; Obelia."],["Bioluminescence","Property of some animals to emit light."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"Which special terms should you recall from Porifera/Cnidaria/Ctenophora?","reveal_answer":"Water canal system, cnidoblast, polyp, medusa, metagenesis and bioluminescence.","key_points":[],"examples":["Hydra","Adamsia","Aurelia","Obelia"],"neet_traps":[]}'::jsonb,
    5,
    15,
    6,
    true
  ),
  (
    'neet-biology-animal-kingdom-flat-round-ring-jointed-comparison',
    'neet-biology-animal-kingdom',
    'Platyhelminthes to Arthropoda',
    'comparison',
    'The source table compares flatworms, roundworms, segmented worms and joint-legged animals.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Feature","Platyhelminthes","Aschelminthes","Annelida","Arthropoda"],"rows":[["Coelom","Acoelomate","Pseudocoelomate","Coelomate","Coelomate"],["Digestive system","Incomplete","Complete tubular canal with muscular pharynx","Complete","Complete"],["Respiration","Absent","Absent","Cutaneous; some branchial","Gills/book gills/trachea/book lungs"],["Circulation","Absent","Absent","Closed type","Open type"],["Unique","Dorsoventrally flattened; flame cells; hooks and suckers in parasites","Circular cross-section; syncytial epidermis; thick cuticle; excretory tube; sexual dimorphism","Ring-like segmentation; setae/parapodia; nephridia; double ventral nerve cord","Jointed appendages; head, thorax, abdomen; chitinous exoskeleton; Malpighian tubules; antennae/eyes/statocysts"],["Examples","Taenia solium, Fasciola, Planaria","Ascaris, Ancylostoma, Wuchereria","Pheretima, Hirudinaria, Neries","Spider, Scorpion, Crab, Prawn, Apis, Bombyx, Laccifer, Anopheles, Culex, Aedes, Housefly, Locusta, Limulus"]]}'::jsonb,
    null,
    null,
    '{"recall_question":"Compare Platyhelminthes, Aschelminthes, Annelida and Arthropoda.","reveal_answer":"Flatworms are acoelomate with flame cells; roundworms are pseudocoelomate with thick cuticle; annelids are segmented coelomates with closed circulation; arthropods have jointed appendages, chitinous exoskeleton and open circulation.","key_points":[],"examples":["Taenia solium","Fasciola","Planaria","Ascaris","Ancylostoma","Wuchereria","Pheretima","Hirudinaria","Neries","Apis","Bombyx","Laccifer","Locusta","Limulus"],"neet_traps":[]}'::jsonb,
    5,
    16,
    7,
    true
  ),
  (
    'neet-biology-animal-kingdom-arthropoda-traps',
    'neet-biology-animal-kingdom',
    'Arthropoda NEET Facts',
    'neet_trap',
    'Arthropoda is the largest phylum; over two-thirds of all named species are arthropods.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    null,
    null,
    null,
    '{"recall_question":"What source examples are tied to Arthropoda?","reveal_answer":"Economically important insects: Apis, Bombyx, Laccifer; vectors: mosquitoes (Anopheles, Culex, Aedes), Housefly; gregarious pest: Locusta; living fossil: Limulus.","key_points":["Dioecious means sexes are separate.","Sexual dimorphism means morphological differences between male and female."],"examples":["Apis","Bombyx","Laccifer","Anopheles","Culex","Aedes","Housefly","Locusta","Limulus"],"neet_traps":["Arthropoda is the largest phylum."]}'::jsonb,
    5,
    16,
    8,
    true
  ),
  (
    'neet-biology-animal-kingdom-mollusca-echinodermata-hemichordata',
    'neet-biology-animal-kingdom',
    'Mollusca vs Echinodermata vs Hemichordata',
    'comparison',
    'The source table compares these coelomate non-chordate phyla.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Feature","Mollusca","Echinodermata","Hemichordata"],"rows":[["Symmetry","Bilateral","Adults radial; larvae bilateral","Bilateral"],["Habitat","Aquatic; few terrestrial","Exclusively marine","Exclusively marine"],["Respiration","Gills in aquatic forms and pulmonary sac in terrestrial forms","Dermal branchiae/papulae and tube feet","Gills"],["Circulation","Open type","Open type","Open type"],["Unique","Head, visceral mass and muscular foot; mantle and radula; calcareous shell","Calcareous ossicle endoskeleton; water vascular system; no head; no excretory system; autotomy/regeneration","Proboscis, collar and trunk; stomochord; proboscis gland"],["Examples","Pila, Pinctada, Sepia, Loligo, Octopus, Aplysia, Dentalium, Chaetopleura","Asterias, Echinus, Echinocardium, Antedon, Cucumaria, Ophiura","Balanoglossus, Saccoglossus"]]}'::jsonb,
    null,
    null,
    '{"recall_question":"Compare Mollusca, Echinodermata and Hemichordata.","reveal_answer":"Mollusca has mantle/radula; Echinodermata has water vascular system and adult radial symmetry; Hemichordata has proboscis-collar-trunk and stomochord.","key_points":[],"examples":["Pila","Pinctada","Sepia","Loligo","Octopus","Aplysia","Dentalium","Chaetopleura","Asterias","Echinus","Echinocardium","Antedon","Cucumaria","Ophiura","Balanoglossus","Saccoglossus"],"neet_traps":[]}'::jsonb,
    5,
    17,
    9,
    true
  ),
  (
    'neet-biology-animal-kingdom-mollusc-echinoderm-terms',
    'neet-biology-animal-kingdom',
    'Mollusc and Echinoderm Terms',
    'fact',
    'The source notes define mantle, radula and water vascular system.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Term","Recall answer"],"rows":[["Mollusca rank","Second largest phylum."],["Mantle/Pallium","Membrane covering visceral mass; space between hump and mantle is mantle cavity."],["Radula","File-like rasping organ in mouth of molluscs used for feeding."],["Water vascular system","Sea water enters through madreporite and reaches radiating canals and tube feet/podia."],["Hemichordata note","Earlier considered a sub-phylum of Chordata; has pharyngeal gill slits."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"What are mantle, radula and water vascular system?","reveal_answer":"Mantle covers visceral mass; radula is rasping feeding organ; water vascular system uses madreporite, canals and tube feet for locomotion, respiration, food capture/transport and excretion.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb,
    5,
    17,
    10,
    true
  ),
  (
    'neet-biology-animal-kingdom-chordata-vs-nonchordata',
    'neet-biology-animal-kingdom',
    'Chordata vs Non-Chordata',
    'comparison',
    'Chordates have notochord, dorsal tubular nerve cord and pharyngeal gill slits.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Character","Chordata","Non-Chordata"],"rows":[["Notochord","Found in embryonic stage","Absent"],["Central nervous system","Dorsal, hollow and single","Ventral, solid and double"],["Pharyngeal gill slits","Present","Absent"],["Heart","Ventral","Dorsal if present"],["Post-anal tail","Present","Absent"]]}'::jsonb,
    null,
    null,
    '{"recall_question":"Chordata vs Non-Chordata?","reveal_answer":"Chordata has embryonic notochord, dorsal hollow single CNS, pharyngeal gill slits, ventral heart and post-anal tail.","key_points":[],"examples":[],"neet_traps":["Notochord lies mid-dorsally between alimentary canal and nerve cord in embryo."]}'::jsonb,
    5,
    17,
    11,
    true
  ),
  (
    'neet-biology-animal-kingdom-chordata-subphyla',
    'neet-biology-animal-kingdom',
    'Urochordata vs Cephalochordata vs Vertebrata',
    'comparison',
    'Phylum Chordata is classified into Urochordata, Cephalochordata and Vertebrata.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Subphylum","Recall features","Examples"],"rows":[["Urochordata (Tunicata)","Notochord only in larval tail; body covered by test made of tunicin; exclusively marine; hermaphrodite.","Ascidia, Salpa, Doliolum"],["Cephalochordata","Notochord from head to tail and persistent throughout life; fish-like body; exclusively marine; sexes separate.","Branchiostoma (Amphioxus or Lancelet)"],["Vertebrata","Embryonic notochord replaced by cartilaginous/bony vertebral column in adult; ventral muscular heart; kidneys; paired appendages.","Cyclostomata to Mammalia"]]}'::jsonb,
    null,
    null,
    '{"recall_question":"Compare Urochordata, Cephalochordata and Vertebrata.","reveal_answer":"Urochordata has larval-tail notochord; Cephalochordata has persistent head-to-tail notochord; Vertebrata replaces embryonic notochord with vertebral column.","key_points":[],"examples":["Ascidia","Salpa","Doliolum","Branchiostoma","Amphioxus","Lancelet"],"neet_traps":[]}'::jsonb,
    5,
    18,
    12,
    true
  ),
  (
    'neet-biology-animal-kingdom-vertebrate-classification',
    'neet-biology-animal-kingdom',
    'Classification of Vertebrata',
    'diagram',
    'The source flow divides Vertebrata into Agnatha and Gnathostomata, then Pisces and Tetrapoda.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    null,
    '{"type":"bio-vertebrata-flow"}'::jsonb,
    null,
    '{"recall_question":"Recall the vertebrate classification flow.","reveal_answer":"Vertebrata -> Agnatha (jawless) -> Cyclostomata; Vertebrata -> Gnathostomata (bears jaws) -> Pisces (Chondrichthyes, Osteichthyes) and Tetrapoda (Amphibia, Reptilia, Aves, Mammalia).","key_points":[],"examples":[],"neet_traps":[]}'::jsonb,
    5,
    18,
    13,
    true
  ),
  (
    'neet-biology-animal-kingdom-cyclostomata',
    'neet-biology-animal-kingdom',
    'Class Cyclostomata',
    'classification',
    'Cyclostomes are jawless ectoparasites on some fishes.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    null,
    null,
    null,
    '{"recall_question":"What are the source traits of Cyclostomata?","reveal_answer":"Ectoparasites on fishes with elongated scaleless body, no paired fins, 6-15 pairs of gill slits, sucking circular jawless mouth, cartilaginous cranium and vertebral column, closed circulation.","key_points":["Marine, but migrate to freshwater for spawning; after spawning they die.","Larvae return to ocean after metamorphosis."],"examples":["Petromyzon (Lamprey)","Myxine (Hagfish)"],"neet_traps":[]}'::jsonb,
    5,
    18,
    14,
    true
  ),
  (
    'neet-biology-animal-kingdom-chondrichthyes-vs-osteichthyes',
    'neet-biology-animal-kingdom',
    'Chondrichthyes vs Osteichthyes',
    'comparison',
    'The source compares cartilaginous and bony fishes.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Feature","Chondrichthyes","Osteichthyes"],"rows":[["Habitat/body","Marine, streamlined, predaceous","Marine and fresh water, streamlined"],["Endoskeleton","Cartilaginous; notochord persistent throughout life","Bony"],["Mouth","Ventral","Terminal"],["Gills","Gill slits without operculum; powerful jaws","4 pairs of gills covered by operculum on each side"],["Scales","Placoid; teeth are backward modified placoid scales","Cycloid, ctenoid etc."],["Air bladder","Absent; must swim constantly to avoid sinking","Present for buoyancy"],["Heart/temp","Poikilotherm; two-chambered heart","Poikilotherm; two-chambered heart"],["Reproduction","Separate sexes; male pelvic fins bear claspers; internal fertilization; many viviparous","Separate sexes; external fertilisation; mostly oviparous; direct development"],["Examples","Scoliodon, Pristis, Carcharodon, Trygon, Torpedo","Exocoetus, Hippocampus, Labeo, Catla, Clarias, Betta, Pterophyllum"]]}'::jsonb,
    null,
    null,
    '{"recall_question":"Chondrichthyes vs Osteichthyes?","reveal_answer":"Chondrichthyes have cartilaginous skeleton, ventral mouth, no operculum or air bladder, placoid scales and internal fertilization; Osteichthyes have bony skeleton, terminal mouth, operculum, air bladder and mostly external fertilization.","key_points":[],"examples":["Scoliodon","Pristis","Carcharodon","Trygon","Torpedo","Exocoetus","Hippocampus","Labeo","Catla","Clarias","Betta","Pterophyllum"],"neet_traps":[]}'::jsonb,
    5,
    18,
    15,
    true
  ),
  (
    'neet-biology-animal-kingdom-tetrapoda-comparison',
    'neet-biology-animal-kingdom',
    'Amphibia vs Reptilia vs Aves vs Mammalia',
    'comparison',
    'The source table compares the four tetrapod classes.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Feature","Amphibia","Reptilia","Aves","Mammalia"],"rows":[["Body/skin","Aquatic and terrestrial; need water for breeding; moist skin without scales","Dry cornified skin with epidermal scales/scutes","Feathers and beak; dry skin except oil gland at tail base","Mammary glands; skin with hair"],["Limbs","Most have two pairs","Two pairs if present; crawling locomotion","Forelimbs as wings; hind limbs for walking/swimming/clasping","Two pairs for walking, running, climbing, burrowing, swimming or flying"],["Ear","Tympanum represents ear","Tympanum represents ear","Tympanum represents ear","External ear pinnae"],["Heart","3-chambered","3-chambered with partial septum; crocodiles 4-chambered","4-chambered","4-chambered"],["Temperature","Poikilotherms","Poikilotherms","Homoiotherms","Homoiotherms"],["Respiration","Gills in larva, lungs and skin","Lungs","Double respiration; air sacs connected to lungs","Lungs"],["Reproduction","External fertilisation, oviparous, indirect development","Internal fertilisation, oviparous, direct development","Internal fertilisation, oviparous, direct development","Internal fertilisation, viviparous except Echidna and Platypus, direct development"]]}'::jsonb,
    null,
    null,
    '{"recall_question":"Compare Amphibia, Reptilia, Aves and Mammalia.","reveal_answer":"Amphibia need water and have moist skin; Reptilia have dry scales; Aves have feathers, wings and air sacs; Mammalia have mammary glands, hair and pinnae.","key_points":[],"examples":[],"neet_traps":["Crocodiles have four-chambered heart; mammals are viviparous except Echidna and Platypus."]}'::jsonb,
    5,
    20,
    16,
    true
  ),
  (
    'neet-biology-animal-kingdom-tetrapoda-examples',
    'neet-biology-animal-kingdom',
    'Tetrapoda Examples',
    'examples',
    'The source examples for tetrapods are high-yield recall lists.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Class","Source examples"],"rows":[["Amphibia","Bufo (Toad), Rana (Frog), Hyla (Tree frog), Salamandra (Salamander), Ichthyophis (Limbless amphibia)"],["Reptilia","Chelone (Turtle), Testudo (Tortoise), Chameleon, Calotes, Crocodilus, Alligator, Hemidactylus; poisonous snakes: Naja, Bangarus, Vipera; non-poisonous snakes: Python"],["Aves","Corvus, Columba, Psittacula, Struthio, Pavo, Aptenodytes, Neophron"],["Mammalia","Ornithorhynchus, Macropus, Pteropus, Camelus, Macaca, Rattus, Canis, Felis, Elephas, Equus, Delphinus, Balaenoptera, Panthera tigris, Panthera leo"]]}'::jsonb,
    null,
    null,
    '{"recall_question":"Recall the tetrapod examples exactly from the source.","reveal_answer":"Amphibia: Bufo, Rana, Hyla, Salamandra, Ichthyophis. Reptilia: Chelone, Testudo, Chameleon, Calotes, Crocodilus, Alligator, Hemidactylus, Naja, Bangarus, Vipera, Python. Aves: Corvus, Columba, Psittacula, Struthio, Pavo, Aptenodytes, Neophron. Mammalia: Ornithorhynchus, Macropus, Pteropus, Camelus, Macaca, Rattus, Canis, Felis, Elephas, Equus, Delphinus, Balaenoptera, Panthera tigris, Panthera leo.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb,
    5,
    20,
    17,
    true
  ),
  (
    'neet-biology-animal-kingdom-poikilotherm-homoiotherm',
    'neet-biology-animal-kingdom',
    'Poikilotherms vs Homoiotherms',
    'comparison',
    'The source defines these temperature-regulation terms.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Term","Recall answer","Classes in table"],"rows":[["Poikilotherms","Cold-blooded animals that lack capacity to regulate body temperature.","Amphibia, Reptilia, Chondrichthyes, Osteichthyes"],["Homoiotherms","Warm-blooded animals having ability to maintain constant body temperature.","Aves, Mammalia"]]}'::jsonb,
    null,
    null,
    '{"recall_question":"Poikilotherms vs homoiotherms?","reveal_answer":"Poikilotherms lack body-temperature regulation; homoiotherms maintain constant body temperature.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb,
    4,
    20,
    18,
    true
  )
on conflict (id) do update set
  title = excluded.title,
  card_type = excluded.card_type,
  body = excluded.body,
  formulas = excluded.formulas,
  variables = excluded.variables,
  conditions = excluded.conditions,
  table_data = excluded.table_data,
  diagram_data = excluded.diagram_data,
  diagram_svg = excluded.diagram_svg,
  recall_data = excluded.recall_data,
  importance = excluded.importance,
  source_page = excluded.source_page,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active;
