alter table public.formula_cards
  add column if not exists recall_data jsonb;

insert into public.formula_subjects (id, name, slug, exam, sort_order) values
  ('neet-biology', 'Biology', 'biology', 'NEET', 3)
on conflict (id) do update set
  name = excluded.name,
  slug = excluded.slug,
  exam = excluded.exam,
  sort_order = excluded.sort_order;

insert into public.formula_chapters (id, subject_id, title, slug, sort_order) values
  ('neet-biology-structural-organization-in-animals', 'neet-biology', 'Structural Organization in Animals', 'structural-organization-in-animals', 7),
  ('neet-biology-cells-the-unit-of-life', 'neet-biology', 'Cells: The Unit of Life', 'cells-the-unit-of-life', 8),
  ('neet-biology-cell-cycle-and-cell-division', 'neet-biology', 'Cell Cycle and Cell Division', 'cell-cycle-and-cell-division', 9)
on conflict (id) do update set
  title = excluded.title,
  slug = excluded.slug,
  sort_order = excluded.sort_order;

insert into public.formula_cards (
  id, chapter_id, title, card_type, body, formulas, variables, conditions, table_data, diagram_data, diagram_svg, recall_data, importance, source_page, sort_order, is_active
) values
  (
    'neet-biology-structural-organization-in-animals-animal-tissues-overview',
    'neet-biology-structural-organization-in-animals',
    'Animal Tissues Overview',
    'classification',
    'Animal tissues are groups of cells with same origin, structure and function.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Animal tissue","Recall cue"],"rows":[["Epithelial","Covers or lines body or body parts."],["Connective","Links and supports other tissues/organs."],["Muscular","Muscle fibres contract and relax."],["Neural","Neurons carry impulses; neuroglia support them."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"Name the four animal tissue types in the source.","reveal_answer":"Epithelial, connective, muscular and neural.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb,
    5,
    32,
    1,
    true
  ),
  (
    'neet-biology-structural-organization-in-animals-epithelium-basics',
    'neet-biology-structural-organization-in-animals',
    'Epithelial Tissue',
    'concept',
    'Epithelial tissue has a free surface, covers or lines body parts, and has compactly packed cells with little intercellular matrix.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Type","Recall answer"],"rows":[["Simple epithelium","Single layer of cells; lines body cavities, ducts and tubes."],["Compound epithelium","More than one layer of cells; protects against chemical and mechanical stresses."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"What are the two types of epithelial tissues?","reveal_answer":"Simple and compound.","key_points":["Simple epithelium has a single layer of cells.","Compound epithelium is multi-layered."],"examples":[],"neet_traps":[]}'::jsonb,
    5,
    32,
    2,
    true
  ),
  (
    'neet-biology-structural-organization-in-animals-simple-epithelium-comparison',
    'neet-biology-structural-organization-in-animals',
    'Squamous vs Cuboidal vs Columnar',
    'comparison',
    'Simple epithelium is classified by structural modification of cells.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Type","Structure","Location","Function / trap"],"rows":[["Squamous","Thin layer of flattened cells with irregular boundaries.","Walls of blood vessels and lung alveoli.","Forms a diffusion boundary."],["Cuboidal","Cube-like cells.","Ducts of glands and tubular parts of nephrons.","Secretion and absorption; PCT epithelium has microvilli."],["Columnar","Tall and slender cells; nuclei at base; free surface may have microvilli.","Lining of stomach and intestine.","Secretion and absorption."]]}'::jsonb,
    '{"type":"bio-epithelium-types"}'::jsonb,
    null,
    '{"recall_question":"Which epithelium lines PCT and what special feature is noted?","reveal_answer":"Cuboidal epithelium; PCT epithelium has microvilli.","key_points":[],"examples":[],"neet_traps":["PCT epithelium has microvilli."]}'::jsonb,
    5,
    32,
    3,
    true
  ),
  (
    'neet-biology-structural-organization-in-animals-ciliated-glandular-epithelium',
    'neet-biology-structural-organization-in-animals',
    'Ciliated and Glandular Epithelium',
    'classification',
    'Ciliated and glandular epithelia are modifications of columnar or cuboidal cells.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Epithelium","Recall answer","Source examples"],"rows":[["Ciliated","Cells bear cilia on free surface; move particles or mucus in a specific direction.","Inner surface of bronchioles and fallopian tubes"],["Glandular","Modified for secretion.","Goblet cells of alimentary canal; salivary glands"],["Unicellular gland","Isolated glandular cells.","Goblet cells of the alimentary canal"],["Multicellular gland","Cluster of cells.","Salivary glands"]]}'::jsonb,
    null,
    null,
    '{"recall_question":"What is the function of ciliated epithelium?","reveal_answer":"To move particles or mucus in a specific direction over the epithelium.","key_points":[],"examples":["Bronchioles","Fallopian tubes"],"neet_traps":[]}'::jsonb,
    4,
    32,
    4,
    true
  ),
  (
    'neet-biology-structural-organization-in-animals-exocrine-endocrine',
    'neet-biology-structural-organization-in-animals',
    'Exocrine vs Endocrine Glands',
    'comparison',
    'Glands are grouped by mode of pouring secretions.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Gland","Recall answer","Source examples/products"],"rows":[["Exocrine","Secretions are released through ducts.","Mucus, saliva, earwax, oil, milk, digestive enzymes"],["Endocrine","Ductless; produce hormones.","Hormones"]]}'::jsonb,
    null,
    null,
    '{"recall_question":"Which glands are ductless?","reveal_answer":"Endocrine glands.","key_points":["Exocrine glands release secretions through ducts."],"examples":[],"neet_traps":[]}'::jsonb,
    5,
    32,
    5,
    true
  ),
  (
    'neet-biology-structural-organization-in-animals-compound-epithelium-junctions',
    'neet-biology-structural-organization-in-animals',
    'Compound Epithelium and Cell Junctions',
    'classification',
    'Compound epithelium has limited secretion and absorption and protects against chemical and mechanical stresses.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"sections":[{"title":"Compound epithelium","columns":["Feature","Source detail"],"rows":[["Layers","More than one layer of cells."],["Covers","Dry surface of skin, moist surface of buccal cavity, pharynx, inner lining of ducts of salivary glands and pancreatic ducts."],["Function","Protect against chemical & mechanical stresses."]]},{"title":"Cell junctions","columns":["Junction","Recall answer"],"rows":[["Tight junction","Help stop substances from leaking across a tissue."],["Adhering junction","Cement neighbouring cells together."],["Gap junction","Connect cytoplasm for rapid transfer of ions, small molecules and sometimes big molecules."]]}]}'::jsonb,
    null,
    null,
    '{"recall_question":"Which junction allows rapid transfer between adjoining cells?","reveal_answer":"Gap junction.","key_points":["Tight junctions prevent leakage.","Adhering junctions keep neighbouring cells together."],"examples":[],"neet_traps":[]}'::jsonb,
    5,
    32,
    6,
    true
  ),
  (
    'neet-biology-structural-organization-in-animals-connective-overview',
    'neet-biology-structural-organization-in-animals',
    'Connective Tissue',
    'classification',
    'Connective tissue is most abundant in complex animals and links/supports tissues and organs.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Feature","Recall answer"],"rows":[["Fibroblasts","All connective tissues except blood have fibroblast cells."],["Fibroblast products","Collagen and elastin give strength, elasticity and flexibility."],["Matrix","Modified polysaccharides accumulate between cells and fibres."],["Types","Loose, dense and specialised."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"Which connective tissue lacks fibroblast cells according to the source?","reveal_answer":"Blood.","key_points":[],"examples":[],"neet_traps":["Blood is connective tissue."]}'::jsonb,
    5,
    32,
    7,
    true
  ),
  (
    'neet-biology-structural-organization-in-animals-areolar-adipose',
    'neet-biology-structural-organization-in-animals',
    'Areolar vs Adipose Tissue',
    'comparison',
    'Loose connective tissues have cells and fibres loosely arranged in semi-fluid matrix.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Tissue","Recall answer","Location/function"],"rows":[["Areolar","Contains fibroblasts, macrophages, mast cells etc. with fibres in semi-fluid matrix.","Present beneath skin; support framework for epithelium."],["Adipose","Adipocytes store fats.","Seen mainly under skin; excess nutrients converted to fats are stored."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"Which loose connective tissue stores fat?","reveal_answer":"Adipose tissue.","key_points":["Its cells are adipocytes."],"examples":[],"neet_traps":[]}'::jsonb,
    5,
    33,
    8,
    true
  ),
  (
    'neet-biology-structural-organization-in-animals-dense-connective',
    'neet-biology-structural-organization-in-animals',
    'Dense Connective Tissue',
    'comparison',
    'Dense connective tissue has fibres and fibroblasts compactly packed.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Type","Recall answer","Source example"],"rows":[["Dense regular","Regular pattern; collagen fibres in rows between many parallel bundles of fibres.","Tendons & ligaments"],["Tendon","Attaches muscles to bones.",""],["Ligament","Attaches one bone to another.",""],["Dense irregular","Irregular pattern; fibroblasts and mostly collagen fibres oriented differently.","Skin"]]}'::jsonb,
    null,
    null,
    '{"recall_question":"Tendon vs ligament: what do they attach?","reveal_answer":"Tendon attaches muscles to bones; ligament attaches one bone to another.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb,
    5,
    33,
    9,
    true
  ),
  (
    'neet-biology-structural-organization-in-animals-cartilage-bone-blood',
    'neet-biology-structural-organization-in-animals',
    'Cartilage, Bone and Blood',
    'comparison',
    'Specialised connective tissues include cartilage, bone and blood.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Tissue","Recall answer","Source locations/functions"],"rows":[["Cartilage","Solid, pliable matrix due to chondroitin salts; resists compression; chondrocytes lie in cavities.","Tip of nose, outer ear, joints in vertebral column, limbs and hands."],["Bone","Hard, non-pliable matrix rich in calcium salts and collagen fibres; osteocytes in lacunae.","Structural frame, protection, locomotion, bone marrow makes blood cells."],["Blood","Fluid connective tissue with plasma, RBC, WBC and platelets.","Circulation of various substances."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"Why is blood a connective tissue in this source?","reveal_answer":"It is listed as a fluid connective tissue containing plasma, RBC, WBC and platelets.","key_points":[],"examples":[],"neet_traps":["Blood is connective tissue."]}'::jsonb,
    5,
    33,
    10,
    true
  ),
  (
    'neet-biology-structural-organization-in-animals-muscle-types',
    'neet-biology-structural-organization-in-animals',
    'Skeletal, Smooth and Cardiac Muscle',
    'comparison',
    'Muscle tissue is made of muscle fibres composed of many myofibrils.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Muscle","Control/structure","Source location/function"],"rows":[["Skeletal","Striated or voluntary; fibres bundled parallel and enclosed by tough connective tissue.","Attached to bones, e.g. Biceps."],["Smooth","Non-striated or visceral; involuntary and fusiform; no striations.","Walls of blood vessels, stomach and intestine."],["Cardiac","Involuntary; seen only in heart; intercalated discs allow cells to contract as a unit.","Heart."]]}'::jsonb,
    '{"type":"bio-muscle-types"}'::jsonb,
    null,
    '{"recall_question":"Which muscle is involuntary and present only in the heart?","reveal_answer":"Cardiac muscle.","key_points":["Gap junctions at intercalated discs allow contraction as a unit."],"examples":[],"neet_traps":["Cardiac muscle is involuntary."]}'::jsonb,
    5,
    33,
    11,
    true
  ),
  (
    'neet-biology-structural-organization-in-animals-neural-tissue',
    'neet-biology-structural-organization-in-animals',
    'Neural Tissue',
    'concept',
    'Neural tissue is made up of neurons and neuroglial cells and controls/co-ordinates the body.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Cell","Recall answer"],"rows":[["Neuron","Unit of neural system; excitable cells that carry impulses."],["Neuroglia","Protect and support neurons; make up more than half the volume of neural tissue."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"Which cells make up more than half the volume of neural tissue?","reveal_answer":"Neuroglia.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb,
    4,
    33,
    12,
    true
  ),
  (
    'neet-biology-structural-organization-in-animals-cockroach-intro',
    'neet-biology-structural-organization-in-animals',
    'Cockroach Identity and Classification',
    'classification',
    'Cockroach (Periplaneta americana) is nocturnal, omnivorous and lives in damp places.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Systematic position","Source value"],"rows":[["Phylum","Arthropoda"],["Class","Insecta"],["Genus","Periplaneta"],["Species","americana"],["Size","1/4 inches to 3 inches (0.6-7.6 cm); adults about 34-53 mm long."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"What is the genus and species of cockroach in the source?","reveal_answer":"Periplaneta americana.","key_points":["Cockroaches are nocturnal, omnivores and live in damp places."],"examples":[],"neet_traps":[]}'::jsonb,
    5,
    34,
    13,
    true
  ),
  (
    'neet-biology-structural-organization-in-animals-cockroach-morphology',
    'neet-biology-structural-organization-in-animals',
    'Cockroach Morphology',
    'classification',
    'Cockroach body has hard brown chitinous exoskeleton and three regions: head, thorax and abdomen.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Structure","Recall answer"],"rows":[["Exoskeleton","Hard brown chitinous; sclerites are dorsal tergites and ventral sternites joined by arthrodial membrane."],["Head","Triangular, formed by 6 fused segments; flexible neck gives mobility."],["Thorax","Prothorax, mesothorax and metathorax; each segment bears a pair of walking legs."],["Abdomen","10 segments."]]}'::jsonb,
    '{"type":"bio-cockroach-body"}'::jsonb,
    null,
    '{"recall_question":"What are the three body regions of cockroach?","reveal_answer":"Head, thorax and abdomen.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb,
    5,
    34,
    14,
    true
  ),
  (
    'neet-biology-structural-organization-in-animals-cockroach-head-mouthparts-wings',
    'neet-biology-structural-organization-in-animals',
    'Head, Mouthparts and Wings',
    'classification',
    'Cockroach has biting and chewing type mouthparts and two pairs of wings.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Part","Recall answer"],"rows":[["Head bears","Thread-like antennae, compound eyes and biting & chewing type mouth parts."],["Mouthparts","Labrum (upper lip), 2 mandibles, 2 maxillae, hypopharynx (tongue) & labium (lower lip)."],["Forewings / tegmina","Mesothoracic; opaque, dark and leathery; cover hind wings at rest."],["Hind wings","Metathoracic; transparent, membranous and used in flight."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"What are tegmina in cockroach?","reveal_answer":"Forewings: opaque, dark and leathery mesothoracic wings that cover hind wings at rest.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb,
    5,
    34,
    15,
    true
  ),
  (
    'neet-biology-structural-organization-in-animals-male-female-cockroach',
    'neet-biology-structural-organization-in-animals',
    'Male vs Female Cockroach',
    'comparison',
    'Sexes differ in size, wing extension, abdomen width, anal styles and brood pouch.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Feature","Male","Female"],"rows":[["Size","Larger size","Smaller"],["Wings","Extend beyond the tip of abdomen.","Do not extend beyond the tip of abdomen."],["Abdomen","Narrow abdomen","Broad abdomen"],["Anal styles","Present","Absent"],["Brood pouch","Absent","Present"]]}'::jsonb,
    null,
    null,
    '{"recall_question":"Which sex has anal styles in cockroach?","reveal_answer":"Male.","key_points":["Females have a brood pouch."],"examples":[],"neet_traps":[]}'::jsonb,
    5,
    34,
    16,
    true
  ),
  (
    'neet-biology-structural-organization-in-animals-cockroach-digestive',
    'neet-biology-structural-organization-in-animals',
    'Cockroach Digestive System',
    'sequence',
    'Cockroach alimentary canal has foregut, midgut and hindgut.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Part","Recall answer"],"rows":[["Foregut","Cuticle-lined: mouth -> pharynx -> oesophagus -> crop -> gizzard."],["Crop","Stores food."],["Gizzard","Grinds food; has thick circular muscles and 6 chitinous plates (teeth)."],["Midgut / mesenteron","Not lined by cuticle; 6-8 hepatic/gastric caecae secrete digestive juice."],["Malpighian tubules position","100-150 yellow thin filamentous tubules at junction of midgut and hindgut."],["Hindgut","Broader than midgut, cuticle-lined; ileum, colon and rectum; opens through anus."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"What are the three parts of cockroach alimentary canal?","reveal_answer":"Foregut, midgut and hindgut.","key_points":["The gizzard grinds food.","Malpighian tubules occur at the junction of midgut and hindgut."],"examples":[],"neet_traps":[]}'::jsonb,
    5,
    34,
    17,
    true
  ),
  (
    'neet-biology-structural-organization-in-animals-cockroach-circulatory-respiratory-excretory',
    'neet-biology-structural-organization-in-animals',
    'Cockroach Circulation, Respiration and Excretion',
    'comparison',
    'Cockroach has open circulation, tracheal respiration and Malpighian tubule excretion.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["System","Recall answer"],"rows":[["Circulatory","Open type; vessels poorly developed and open into haemocoel; haemolymph is colourless plasma + haemocytes."],["Heart","Elongated muscular tube along mid dorsal line with funnel-shaped chambers and ostia."],["Respiratory","Network of trachea opens through 10 pairs of spiracles; tracheoles carry oxygen to all parts; diffusion at tracheoles."],["Excretory","Uricotelic; excretory organ is Malpighian tubules; wastes converted to uric acid and excreted through hindgut."],["Other excretory helpers","Fat body, nephrocytes & urecose glands."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"What are the excretory organs of cockroach?","reveal_answer":"Malpighian tubules.","key_points":["Cockroach is uricotelic."],"examples":[],"neet_traps":["Cockroach respiratory system uses tracheae/tracheoles.","Malpighian tubules are excretory organs in cockroach."]}'::jsonb,
    5,
    35,
    18,
    true
  ),
  (
    'neet-biology-structural-organization-in-animals-cockroach-nervous-sensory',
    'neet-biology-structural-organization-in-animals',
    'Cockroach Nervous System and Mosaic Vision',
    'classification',
    'Cockroach nervous system is ventral and segmentally arranged.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Feature","Recall answer"],"rows":[["Nervous system","Segmentally arranged ganglia joined by paired longitudinal connectives on ventral side."],["Ganglia","3 in thorax and 6 in abdomen."],["Head note","Head holds only a bit of nervous system; cockroach can live one week after head is cut off."],["Brain","Supra-oesophageal ganglion supplies nerves to antennae and compound eyes."],["Sense organs","Antennae, eyes, maxillary palps, labial palps, anal cerci etc."],["Compound eye","About 2000 hexagonal ommatidia."],["Mosaic vision","Several images of an object; more sensitivity but less resolution; nocturnal vision."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"What produces mosaic vision in cockroach?","reveal_answer":"About 2000 hexagonal ommatidia in each compound eye.","key_points":["It has more sensitivity but less resolution and is common during night."],"examples":[],"neet_traps":[]}'::jsonb,
    5,
    35,
    19,
    true
  ),
  (
    'neet-biology-structural-organization-in-animals-cockroach-reproduction',
    'neet-biology-structural-organization-in-animals',
    'Cockroach Reproductive Systems',
    'comparison',
    'Cockroaches are dioecious.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["System","Recall answer"],"rows":[["Male components","Pair of testes, seminal vesicles, accessory glands and external genitalia."],["Testes","Lie laterally in 4th-6th abdominal segments."],["Male duct path","Each testis -> vas deferens -> seminal vesicle -> ejaculatory duct -> male gonopore."],["Spermatophores","Sperms are glued together to form bundles and discharged during copulation."],["Accessory glands","Mushroom gland in 6th-7th abdominal segments and phallic gland; secretions nourish sperms."],["Female components","2 large ovaries, oviducts, spermatheca, genital chamber, colleterial glands etc."],["Ovaries","Lie laterally in 2nd-6th abdominal segments; each has 8 ovarioles."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"How many ovarioles form each cockroach ovary?","reveal_answer":"8 ovarian tubules (ovarioles).","key_points":["Ovaries lie laterally in 2nd-6th abdominal segments."],"examples":[],"neet_traps":[]}'::jsonb,
    5,
    35,
    20,
    true
  ),
  (
    'neet-biology-structural-organization-in-animals-ootheca-development-economics',
    'neet-biology-structural-organization-in-animals',
    'Ootheca, Development and Economic Importance',
    'fact',
    'Fertilised eggs are encased in oothecae, and development is paurometabolous.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Topic","Recall answer"],"rows":[["Ootheca","Dark reddish to blackish brown capsule, 8 mm long."],["Egg count","Females lay 9-10 oothecae, each containing 14-16 eggs."],["Development","Paurometabolous, through nymphal stage."],["Nymphs","Look like adults, moult 13 times; next-to-last nymph has wing pads; only adults have wings."],["Economic importance","Pests that destroy food, contaminate it with smelly excreta, and transmit bacterial diseases like cholera, typhoid, tuberculosis etc."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"What is paurometabolous development in cockroach?","reveal_answer":"Development through nymphal stage.","key_points":["Nymphs look like adults and moult 13 times to reach adult form."],"examples":[],"neet_traps":[]}'::jsonb,
    5,
    35,
    21,
    true
  ),
  (
    'neet-biology-cells-the-unit-of-life-cell-definition-history',
    'neet-biology-cells-the-unit-of-life',
    'Cell Definition and Early Discoveries',
    'fact',
    'A cell is the fundamental, structural and functional unit of all living organisms.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Scientist","Source-backed contribution"],"rows":[["Robert Hooke","Discovered cell."],["Anton Von Leeuwenhoek","First observed and described a live cell."],["Matthias Schleiden (1838)","Observed that all plants are composed of different kinds of cells."],["Theodore Schwann (1839)","Found plasma membrane and plant cell wall; proposed that animals and plants are composed of cells and products of cells."],["Rudolf Virchow (1855)","Explained cells divide and new cells form from pre-existing cells; modified cell theory."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"Who first observed and described a live cell?","reveal_answer":"Anton Von Leeuwenhoek.","key_points":[],"examples":[],"neet_traps":["Robert Hooke discovered cell; Leeuwenhoek observed live cell."]}'::jsonb,
    5,
    36,
    1,
    true
  ),
  (
    'neet-biology-cells-the-unit-of-life-cell-theory',
    'neet-biology-cells-the-unit-of-life',
    'Cell Theory',
    'concept',
    'Schleiden and Schwann formulated cell theory; Virchow modified it.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Statement","Cell theory wording"],"rows":[["1","All living organisms are composed of cells and products of cells."],["2","All cells arise from pre-existing cells."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"State the two source statements of cell theory.","reveal_answer":"All living organisms are composed of cells and products of cells; all cells arise from pre-existing cells.","key_points":["Virchow''s phrase in source: Omnis cellula-e cellula."],"examples":[],"neet_traps":[]}'::jsonb,
    5,
    36,
    2,
    true
  ),
  (
    'neet-biology-cells-the-unit-of-life-cell-size-facts',
    'neet-biology-cells-the-unit-of-life',
    'Cell Size and Shape Facts',
    'fact',
    'Cells differ in size, shape and activities.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Fact","Source value"],"rows":[["Smallest cells","Mycoplasmas (0.3 micrometre in length)."],["Largest isolated single cell","Egg of ostrich."],["Longest cells","Nerve cell."],["Size of bacteria","3 to 5 micrometre; typical 1 to 2 micrometre."],["Human RBC diameter","About 7.0 micrometre."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"What is the smallest cell listed in the source?","reveal_answer":"Mycoplasmas, 0.3 micrometre in length.","key_points":["Largest isolated single cell is egg of ostrich.","Longest cells: nerve cell."],"examples":[],"neet_traps":[]}'::jsonb,
    5,
    36,
    3,
    true
  ),
  (
    'neet-biology-cells-the-unit-of-life-prokaryotic-cells',
    'neet-biology-cells-the-unit-of-life',
    'Prokaryotic Cells',
    'concept',
    'Prokaryotic cells have no membrane-bound nucleus and organelles.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Feature","Recall answer"],"rows":[["Includes","Bacteria, blue-green algae, mycoplasma & PPLO."],["Size/multiplication","Generally smaller and multiply more rapidly than eukaryotic cells."],["Bacterial shapes","Bacillus, Coccus, Vibrio and Spirillum."]]}'::jsonb,
    '{"type":"bio-prokaryotic-cell"}'::jsonb,
    null,
    '{"recall_question":"What do prokaryotic cells lack?","reveal_answer":"Membrane-bound nucleus and organelles.","key_points":[],"examples":["Bacteria, blue-green algae, mycoplasma & PPLO"],"neet_traps":[]}'::jsonb,
    5,
    36,
    4,
    true
  ),
  (
    'neet-biology-cells-the-unit-of-life-cell-envelope-gram',
    'neet-biology-cells-the-unit-of-life',
    'Cell Envelope and Gram Response',
    'comparison',
    'Prokaryotic cell envelope is a chemically complex protective covering of three tightly bound layers.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"sections":[{"title":"Cell envelope layers","columns":["Layer","Recall answer"],"rows":[["Glycocalyx","Outer layer; may be loose slime layer or thick tough capsule."],["Cell wall","Middle layer; absent in mycoplasma; gives shape and prevents bursting/collapsing."],["Plasma membrane","Inner semi-permeable layer; structurally similar to eukaryotes."]]},{"title":"Gram staining","columns":["Bacterium","Recall answer"],"rows":[["Gram positive","Take up and retain gram stain."],["Gram negative","Do not retain gram stain."]]}]}'::jsonb,
    null,
    null,
    '{"recall_question":"Which prokaryotes lack cell wall in the source?","reveal_answer":"Mycoplasma.","key_points":["Gram-positive bacteria retain gram stain; Gram-negative bacteria do not."],"examples":[],"neet_traps":[]}'::jsonb,
    5,
    36,
    5,
    true
  ),
  (
    'neet-biology-cells-the-unit-of-life-mesosome-chromatophore',
    'neet-biology-cells-the-unit-of-life',
    'Mesosomes and Chromatophores',
    'classification',
    'Mesosomes and chromatophores are membranous structures in prokaryotes.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Structure","Recall answer"],"rows":[["Mesosome","Infoldings of plasma membrane; includes vesicles, tubules and lamellae."],["Mesosome functions","Cell wall formation, DNA replication, chromosome distribution, respiration/secretion, increased plasma membrane surface and enzymatic content."],["Chromatophores","Pigment-containing membranous infoldings in some prokaryotes, e.g. cyanobacteria."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"What is a mesosome?","reveal_answer":"An infolding of plasma membrane in prokaryotes.","key_points":["It includes vesicles, tubules and lamellae."],"examples":[],"neet_traps":[]}'::jsonb,
    4,
    36,
    6,
    true
  ),
  (
    'neet-biology-cells-the-unit-of-life-nucleoid-plasmid',
    'neet-biology-cells-the-unit-of-life',
    'Nucleoid and Plasmid',
    'concept',
    'Nucleoid is non-membranous circular genomic DNA with protein.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Term","Recall answer"],"rows":[["Nucleoid","Non-membranous naked circular genomic DNA (single chromosome/genetic material) and protein."],["Plasmid","Small circular DNA outside genomic DNA; gives unique phenotypic characters such as antibiotic resistance."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"Which bacterial DNA can give antibiotic resistance?","reveal_answer":"Plasmid.","key_points":["It is small circular DNA outside genomic DNA."],"examples":[],"neet_traps":[]}'::jsonb,
    5,
    36,
    7,
    true
  ),
  (
    'neet-biology-cells-the-unit-of-life-flagella-pili-fimbriae',
    'neet-biology-cells-the-unit-of-life',
    'Flagella, Pili and Fimbriae',
    'comparison',
    'Bacterial surface structures differ in motility and attachment.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Structure","Recall answer"],"rows":[["Flagella","Thin filamentous cell-wall extensions of motile bacteria; bacterial flagellum has filament, hook and basal body."],["Pili","Elongated tubular structures made of pilin; no role in motility."],["Fimbriae","Small bristle-like fibres; help bacteria attach to rocks in streams and host tissues."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"What are the three parts of a bacterial flagellum?","reveal_answer":"Filament, hook and basal body.","key_points":["Pili and fimbriae have no role in motility."],"examples":[],"neet_traps":[]}'::jsonb,
    5,
    36,
    8,
    true
  ),
  (
    'neet-biology-cells-the-unit-of-life-ribosomes-inclusion',
    'neet-biology-cells-the-unit-of-life',
    'Prokaryotic Ribosomes and Inclusion Bodies',
    'classification',
    'Prokaryotic ribosomes are 70S and inclusion bodies are reserve materials.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Structure","Recall answer"],"rows":[["Ribosome size","About 15 nm by 20 nm."],["70S ribosome","50S and 30S subunits together."],["Polyribosome / polysome","Several ribosomes attach to one mRNA and translate it into proteins."],["Inclusion bodies","Non-membranous stored reserve material free in cytoplasm."],["Examples","Phosphate granules, cyanophycean granules, glycogen granules, gas vacuoles etc."],["Gas vacuoles","Found in blue green and purple and green photosynthetic bacteria."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"What subunits form a 70S prokaryotic ribosome?","reveal_answer":"50S and 30S.","key_points":["S is sedimentation coefficient."],"examples":[],"neet_traps":[]}'::jsonb,
    5,
    37,
    9,
    true
  ),
  (
    'neet-biology-cells-the-unit-of-life-prokaryote-eukaryote',
    'neet-biology-cells-the-unit-of-life',
    'Prokaryotic vs Eukaryotic Cells',
    'comparison',
    'The source gives a direct comparison between prokaryotic and eukaryotic cells.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Feature","Prokaryotic cells","Eukaryotic cells"],"rows":[["Size","Generally smaller","Larger"],["Genetic material","In the form of nucleoid","In the form of nucleus"],["Nuclear membrane","Absent","Present"],["Membrane-bound organelles","Absent","Present"],["DNA","Circular DNA","Linear DNA"],["Ribosomes","70S type","80S type (70S in plastids and mitochondria)"]]}'::jsonb,
    null,
    null,
    '{"recall_question":"What ribosomes are found in prokaryotes vs eukaryotic cytoplasm?","reveal_answer":"Prokaryotes have 70S; eukaryotic cytoplasm has 80S.","key_points":["Plastids and mitochondria have 70S ribosomes."],"examples":[],"neet_traps":[]}'::jsonb,
    5,
    38,
    10,
    true
  ),
  (
    'neet-biology-cells-the-unit-of-life-plant-animal-cell',
    'neet-biology-cells-the-unit-of-life',
    'Plant Cell vs Animal Cell',
    'comparison',
    'The source comparison separates plant and animal cells by cell wall, plastids, vacuoles and centrioles.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Feature","Plant cell","Animal cell"],"rows":[["Cell wall","Present","Absent"],["Plastids","Present","Absent"],["Vacuole","A large central vacuole","Many small vacuoles"],["Centrioles","Absent","Present"]]}'::jsonb,
    null,
    null,
    '{"recall_question":"Which has centrioles: plant cell or animal cell?","reveal_answer":"Animal cell.","key_points":["Plant cells have cell wall, plastids and a large central vacuole."],"examples":[],"neet_traps":[]}'::jsonb,
    5,
    38,
    11,
    true
  ),
  (
    'neet-biology-cells-the-unit-of-life-plasma-membrane-fluid-mosaic',
    'neet-biology-cells-the-unit-of-life',
    'Plasma Membrane and Fluid Mosaic Model',
    'diagram',
    'Cell membrane has lipid bilayer, protein and carbohydrate. Singer and Nicolson proposed the fluid mosaic model in 1972.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Feature","Recall answer"],"rows":[["Human RBC membrane","52% protein and 40% lipids."],["Lipids","Mainly phosphoglycerides with polar heads and hydrophobic tails."],["Integral proteins","Partially or totally buried in membrane."],["Peripheral proteins","Lie on the surface of membrane."],["Fluid mosaic model","Quasi-fluid lipid nature allows lateral movement of proteins; this ability is measured as fluidity."],["Functions","Transport, cell growth, intercellular junctions, secretion, endocytosis, cell division etc."]]}'::jsonb,
    '{"type":"bio-plasma-membrane"}'::jsonb,
    null,
    '{"recall_question":"Who proposed the fluid mosaic model and when?","reveal_answer":"Singer & Nicolson, 1972.","key_points":["Fluidity is the ability of proteins to move laterally within the membrane."],"examples":[],"neet_traps":[]}'::jsonb,
    5,
    37,
    12,
    true
  ),
  (
    'neet-biology-cells-the-unit-of-life-transport-types',
    'neet-biology-cells-the-unit-of-life',
    'Passive vs Active Transport',
    'comparison',
    'Transport across membrane may occur along or against concentration gradient.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Transport","Direction/energy","Source examples/details"],"rows":[["Passive transport","Along concentration gradient, without energy.","From higher to lower concentration."],["Simple diffusion","Passive movement of neutral solutes across membrane.","Neutral solutes."],["Osmosis","Movement of water by diffusion across membrane.","Water."],["Active transport","Against concentration gradient, with ATP expenditure.","Na+/K+ pump."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"Which transport uses ATP and moves against concentration gradient?","reveal_answer":"Active transport.","key_points":["Passive transport does not use energy and moves high to low."],"examples":[],"neet_traps":[]}'::jsonb,
    5,
    37,
    13,
    true
  ),
  (
    'neet-biology-cells-the-unit-of-life-cell-wall-middle-lamella',
    'neet-biology-cells-the-unit-of-life',
    'Cell Wall, Middle Lamella and Plasmodesmata',
    'classification',
    'Cell wall is a non-living rigid structure outside plasma membrane in fungi and plants.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Term","Recall answer"],"rows":[["Algal cell wall","Cellulose, galactans, mannans and minerals like CaCO3."],["Other plant cell wall","Cellulose, hemicellulose, pectins and proteins."],["Primary wall","Young plant cell wall capable of growth."],["Secondary wall","Formed on inner side towards membrane as cell matures."],["Middle lamella","Calcium pectate layer that glues neighbouring cells together."],["Plasmodesmata","Traverse cell wall/middle lamella and connect cytoplasm of neighbouring cells."],["Functions","Shape, protection, cell-to-cell interaction, barrier to undesirable macromolecules."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"What is middle lamella made of according to the source?","reveal_answer":"Calcium pectate.","key_points":["It glues neighbouring cells together."],"examples":[],"neet_traps":[]}'::jsonb,
    5,
    38,
    14,
    true
  ),
  (
    'neet-biology-cells-the-unit-of-life-endomembrane-er',
    'neet-biology-cells-the-unit-of-life',
    'Endomembrane System and ER',
    'comparison',
    'Endomembrane system includes ER, Golgi complex, lysosomes and vacuoles.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Structure","Recall answer"],"rows":[["Endoplasmic reticulum","Network of tiny tubular structures; divides intracellular space into luminal and extra luminal compartments."],["RER","Bears ribosomes; seen in cells involved in protein synthesis and secretion; extends to outer nuclear membrane."],["SER","Ribosomes absent; major site for lipid synthesis; steroidal hormones synthesized in animal cells."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"RER vs SER: which bears ribosomes and which synthesizes lipids?","reveal_answer":"RER bears ribosomes; SER lacks ribosomes and synthesizes lipids.","key_points":["Steroidal hormones are synthesized in SER in animal cells."],"examples":[],"neet_traps":[]}'::jsonb,
    5,
    38,
    15,
    true
  ),
  (
    'neet-biology-cells-the-unit-of-life-golgi-lysosome-vacuole',
    'neet-biology-cells-the-unit-of-life',
    'Golgi, Lysosomes and Vacuoles',
    'classification',
    'Golgi, lysosomes and vacuoles are parts of the endomembrane system.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Organelle","Recall answer"],"rows":[["Golgi apparatus","Densely stained reticular structures near nucleus, first observed by Camillo Golgi; stacked cisternae with cis and trans faces."],["Golgi functions","Secretion, vesicle packaging, modification of ER proteins, formation of glycoproteins and glycolipids."],["Lysosomes","Golgi-derived membrane-bound vesicles with hydrolases active at acidic pH."],["Vacuoles","Membrane-bound spaces containing water, sap, excretory product and other materials; tonoplast is single membrane."],["Plant vacuole","Can occupy up to 90% of cell volume; tonoplast helps transport ions/materials against gradients."],["Amoeba","Contractile vacuole helps excretion."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"Which organelle packages lysosomal vesicles?","reveal_answer":"Golgi apparatus.","key_points":["Lysosomal hydrolases digest carbohydrates, proteins, lipids and nucleic acids."],"examples":[],"neet_traps":[]}'::jsonb,
    5,
    38,
    16,
    true
  ),
  (
    'neet-biology-cells-the-unit-of-life-mitochondria',
    'neet-biology-cells-the-unit-of-life',
    'Mitochondria',
    'diagram',
    'Mitochondria are double membrane-bound sites of aerobic respiration and ATP production.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Feature","Recall answer"],"rows":[["Shape/size","Sausage-shaped or cylindrical; diameter 0.2-1.0 micrometre, length 1.0-4.1 micrometre."],["Membranes","Outer membrane and inner membrane divide lumen into outer compartment and matrix."],["Cristae","Inner membrane infoldings that increase surface area."],["Matrix","Circular DNA, RNA, 70S ribosomes and protein synthesis components."],["Division","Divide by fission."],["Function","Sites of aerobic respiration; produce ATP; called power houses of the cell."]]}'::jsonb,
    '{"type":"bio-mitochondrion"}'::jsonb,
    null,
    '{"recall_question":"Why are mitochondria called power houses of the cell?","reveal_answer":"They produce energy in the form of ATP.","key_points":["They are sites of aerobic respiration."],"examples":[],"neet_traps":[]}'::jsonb,
    5,
    38,
    17,
    true
  ),
  (
    'neet-biology-cells-the-unit-of-life-plastids-chloroplast',
    'neet-biology-cells-the-unit-of-life',
    'Plastids and Chloroplasts',
    'diagram',
    'Plastids occur in plant cells and euglenoides; chloroplasts trap light energy for photosynthesis.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"sections":[{"title":"Plastid types","columns":["Type","Recall answer"],"rows":[["Chloroplasts","Contain chlorophyll and carotenoid pigments."],["Chromoplasts","Contain fat-soluble carotenoid pigments like carotene and xanthophylls; yellow/orange/red colour."],["Leucoplasts","Colourless plastids with stored nutrients: amyloplasts store starch, elaioplasts store oils/fats, aleuroplasts store proteins."]]},{"title":"Chloroplast structure","columns":["Part","Recall answer"],"rows":[["Location","Mainly in mesophyll cells of leaves."],["Shape/size","Lens-shaped, oval, spherical, discoid or ribbon-like; 5-10 micrometre long, 2-4 micrometre wide."],["Stroma","Space limited by inner membrane; has circular DNA, ribosomes and enzymes."],["Thylakoids/grana","Thylakoids are flattened sacs; stacks are grana; stroma lamellae connect grana."],["Ribosomes","70S, smaller than cytoplasmic 80S."]]}]}'::jsonb,
    '{"type":"bio-chloroplast"}'::jsonb,
    null,
    '{"recall_question":"Which leucoplast stores starch?","reveal_answer":"Amyloplast.","key_points":["Elaioplast stores oils and fats; aleuroplast stores proteins."],"examples":["Potato"],"neet_traps":[]}'::jsonb,
    5,
    39,
    18,
    true
  ),
  (
    'neet-biology-cells-the-unit-of-life-ribosomes-cytoskeleton',
    'neet-biology-cells-the-unit-of-life',
    'Eukaryotic Ribosomes and Cytoskeleton',
    'comparison',
    'Ribosomes are non-membranous granular structures; cytoskeleton is a filamentous protein network.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Structure","Recall answer"],"rows":[["Ribosomes","RNA and proteins; first observed by George Palade (1953)."],["80S ribosome","60S large subunit + 40S small subunit."],["Cytoskeleton","Network of filamentous proteinaceous structures in cytoplasm."],["Cytoskeleton function","Mechanical support, motility, maintenance of cell shape etc."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"What subunits form 80S ribosomes?","reveal_answer":"60S and 40S.","key_points":["George Palade first observed ribosomes in 1953."],"examples":[],"neet_traps":[]}'::jsonb,
    5,
    39,
    19,
    true
  ),
  (
    'neet-biology-cells-the-unit-of-life-cilia-flagella-axoneme',
    'neet-biology-cells-the-unit-of-life',
    'Cilia, Flagella and 9+2 Axoneme',
    'diagram',
    'Cilia and flagella are hair-like outgrowths of the cell membrane with axoneme core.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Structure","Recall answer"],"rows":[["Cilia","Small structures working like oars; cause movement of cell or surrounding fluid."],["Flagella","Longer; responsible for cell movement; prokaryotic and eukaryotic flagella differ."],["Axoneme","Core with microtubules parallel to long axis."],["9+2 array","9 peripheral doublet pairs and a pair of central microtubules."],["Radial spokes","Central sheath connected to one tubule of each peripheral doublet by radial spoke; 9 radial spokes."],["Basal bodies","Cilium and flagellum emerge from centriole-like basal bodies."]]}'::jsonb,
    '{"type":"bio-axoneme"}'::jsonb,
    null,
    '{"recall_question":"What is the 9+2 arrangement?","reveal_answer":"9 pairs of peripheral doublets plus a pair of central microtubules.","key_points":["It is the axoneme arrangement of cilia and flagella."],"examples":[],"neet_traps":[]}'::jsonb,
    5,
    39,
    20,
    true
  ),
  (
    'neet-biology-cells-the-unit-of-life-centrosome-centriole',
    'neet-biology-cells-the-unit-of-life',
    'Centrosome and Centrioles',
    'classification',
    'Centrosome usually contains two non-membrane-bound cylindrical centrioles.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Feature","Recall answer"],"rows":[["Arrangement","Centrioles lie perpendicular to each other."],["Fibrils","9 evenly spaced peripheral fibrils of tubulin; each peripheral fibril is a triplet."],["Hub","Central proteinaceous part connected to peripheral triplets by radial spokes."],["Functions","Form basal body of cilia/flagella and spindle fibres for spindle apparatus in animal cell division."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"What do centrioles form during cell division?","reveal_answer":"Spindle fibres that give rise to spindle apparatus in animal cells.","key_points":["They also form basal bodies of cilia or flagella."],"examples":[],"neet_traps":[]}'::jsonb,
    4,
    39,
    21,
    true
  ),
  (
    'neet-biology-cells-the-unit-of-life-nucleus',
    'neet-biology-cells-the-unit-of-life',
    'Nucleus',
    'classification',
    'Nucleus was first described by Robert Brown in 1831.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Part","Recall answer"],"rows":[["Nuclear envelope","Double membrane with 10-50 nm perinuclear space; pores allow RNA/protein movement; outer membrane often continuous with ER and bears ribosomes."],["Nuclear matrix / nucleoplasm","Interphase nuclear matrix."],["Chromatin","Network of nucleoprotein fibres with DNA, histones, non-histone proteins and RNA; condenses into chromosomes during division."],["Nucleolus","Non-membranous spherical body continuous with nucleoplasm; site for rRNA synthesis."],["Anucleate mature cells","Mammalian RBC and sieve tube cells of vascular plants."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"Who first described the nucleus?","reveal_answer":"Robert Brown (1831).","key_points":["Chromatin was named by Flemming."],"examples":[],"neet_traps":[]}'::jsonb,
    5,
    39,
    22,
    true
  ),
  (
    'neet-biology-cells-the-unit-of-life-chromosome-types',
    'neet-biology-cells-the-unit-of-life',
    'Chromosome Types',
    'diagram',
    'Chromosomes are classified by centromere position.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Chromosome","Centromere position","Arms"],"rows":[["Metacentric","Middle","Two equal arms."],["Sub-metacentric","Nearer to one end","One shorter arm and one longer arm."],["Acrocentric","Close to end","One very short and one very long arm."],["Telocentric","Terminal","Terminal centromere."]]}'::jsonb,
    '{"type":"bio-chromosome-types"}'::jsonb,
    null,
    '{"recall_question":"Which chromosome has a terminal centromere?","reveal_answer":"Telocentric chromosome.","key_points":["Kinetochores are disc-shaped structures on the sides of centromere.","Satellite is a non-staining secondary constriction at a constant location."],"examples":[],"neet_traps":[]}'::jsonb,
    5,
    40,
    23,
    true
  ),
  (
    'neet-biology-cells-the-unit-of-life-microbodies',
    'neet-biology-cells-the-unit-of-life',
    'Microbodies',
    'fact',
    'Microbodies are membrane-bound minute vesicles containing various enzymes.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    null,
    null,
    null,
    '{"recall_question":"Where are microbodies present?","reveal_answer":"In both plant and animal cells.","key_points":["They contain various enzymes."],"examples":[],"neet_traps":[]}'::jsonb,
    3,
    40,
    24,
    true
  ),
  (
    'neet-biology-cells-the-unit-of-life-mitochondria-chloroplast-comparison',
    'neet-biology-cells-the-unit-of-life',
    'Mitochondria vs Chloroplast',
    'comparison',
    'Both organelles are double membrane-bound and contain circular DNA and 70S ribosomes in the source.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Feature","Mitochondria","Chloroplast"],"rows":[["Main role","Aerobic respiration and ATP production.","Photosynthesis; traps light energy."],["Internal membrane","Cristae are inner membrane infoldings.","Thylakoids stack as grana; stroma lamellae connect grana."],["Internal space","Matrix.","Stroma."],["Genetic/protein machinery","Circular DNA, RNA, 70S ribosomes.","Circular DNA, ribosomes and enzymes; chloroplast ribosomes are 70S."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"What is the internal fluid space called in mitochondria vs chloroplast?","reveal_answer":"Mitochondrial matrix; chloroplast stroma.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb,
    5,
    39,
    25,
    true
  ),
  (
    'neet-biology-cells-the-unit-of-life-ribosome-70s-80s',
    'neet-biology-cells-the-unit-of-life',
    '70S vs 80S Ribosomes',
    'comparison',
    'The source distinguishes prokaryotic and eukaryotic ribosomes by subunits.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Ribosome","Subunits","Where noted"],"rows":[["70S","50S + 30S","Prokaryotes; chloroplasts and mitochondria."],["80S","60S + 40S","Eukaryotic cytoplasmic ribosomes."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"Do 50S and 30S add numerically to 80S?","reveal_answer":"No. S is sedimentation coefficient, a measure of density and size.","key_points":[],"examples":[],"neet_traps":["70S = 50S + 30S by sedimentation behaviour, not arithmetic addition."]}'::jsonb,
    5,
    37,
    26,
    true
  ),
  (
    'neet-biology-cell-cycle-and-cell-division-cell-cycle-definition',
    'neet-biology-cell-cycle-and-cell-division',
    'Cell Cycle Definition',
    'concept',
    'Cell cycle is the life period of a cell during which it synthesizes DNA, grows and divides into two daughter cells.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    null,
    null,
    null,
    '{"recall_question":"What is the cell cycle?","reveal_answer":"The life period of a cell during which a cell synthesizes DNA, grows and divides into two daughter cells.","key_points":["Cell growth is continuous but DNA synthesis occurs only at a specific stage."],"examples":[],"neet_traps":[]}'::jsonb,
    5,
    41,
    1,
    true
  ),
  (
    'neet-biology-cell-cycle-and-cell-division-cell-cycle-phases',
    'neet-biology-cell-cycle-and-cell-division',
    'G1 -> S -> G2 -> M',
    'sequence',
    'Cell cycle has two basic phases: interphase and M phase.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Phase","Recall answer"],"rows":[["Interphase","Between two successive M phases; includes growth and DNA synthesis; lasts more than 95% of cell-cycle duration."],["G1","First growth phase; interval between mitosis and DNA replication; growth, metabolic activity, machinery for DNA replication, RNA/protein synthesis."],["S","DNA replication; DNA amount doubles but chromosome number does not increase; centriole duplicates in animal cells."],["G2","Second growth phase; cell growth and RNA/protein synthesis continue; cell prepared for mitosis."],["M phase","Actual cell division; includes karyokinesis and cytokinesis; about one hour in human cell cycle."]]}'::jsonb,
    '{"type":"bio-cell-cycle"}'::jsonb,
    null,
    '{"recall_question":"What is the correct cell-cycle sequence?","reveal_answer":"G1 -> S -> G2 -> M.","key_points":[],"examples":[],"neet_traps":["DNA doubles in S phase but chromosome number does not increase.","Interphase lasts more than 95% of cell-cycle duration."]}'::jsonb,
    5,
    41,
    2,
    true
  ),
  (
    'neet-biology-cell-cycle-and-cell-division-g0-quiescent',
    'neet-biology-cell-cycle-and-cell-division',
    'G0 / Quiescent Stage',
    'fact',
    'Cells that do not divide further exit G1 phase and enter the inactive G0 stage.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Feature","Recall answer"],"rows":[["G0 entry","Cells exit G1 phase."],["Activity","Metabolically active but do not proliferate."],["Non-dividing example","Heart cells."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"Are G0 cells metabolically active?","reveal_answer":"Yes, they remain metabolically active but do not proliferate.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb,
    4,
    41,
    3,
    true
  ),
  (
    'neet-biology-cell-cycle-and-cell-division-mitosis-basics',
    'neet-biology-cell-cycle-and-cell-division',
    'Mitosis Basics',
    'concept',
    'Mitosis occurs in somatic cells and is called equational division.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Feature","Recall answer"],"rows":[["Where","Somatic cells; generally diploid cells."],["Why equational","Chromosome number in parent and progeny cells is same."],["Exceptions noted","Occurs in haploid cells of some lower plants and some social insects."],["Stages","Prophase, metaphase, anaphase and telophase."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"Why is mitosis called equational division?","reveal_answer":"Because chromosome number in parent and progeny cells is same.","key_points":[],"examples":[],"neet_traps":["Mitosis is equational division."]}'::jsonb,
    5,
    41,
    4,
    true
  ),
  (
    'neet-biology-cell-cycle-and-cell-division-mitosis-stages',
    'neet-biology-cell-cycle-and-cell-division',
    'Mitosis Stages',
    'sequence',
    'Karyokinesis of mitosis has four stages.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Stage","Recall answer"],"rows":[["Prophase","Longest phase; chromatin fibres untangle and condense; centrosomes move to opposite poles; Golgi, ER, nucleolus and nuclear envelope disappear by end."],["Metaphase","Nuclear envelope disintegrates; chromosomes align at equator forming metaphase plate; spindle fibres attach to kinetochores."],["Anaphase","Shortest phase; centromeres divide longitudinally; daughter chromatids move to opposite poles."],["Telophase","Chromosomes cluster and uncoil; nuclear envelopes form; nucleolus, Golgi and ER reappear; spindle fibres disappear."]]}'::jsonb,
    '{"type":"bio-mitosis-sequence"}'::jsonb,
    null,
    '{"recall_question":"Which is the shortest phase of mitosis?","reveal_answer":"Anaphase.","key_points":["Prophase is the longest phase in mitosis."],"examples":[],"neet_traps":[]}'::jsonb,
    5,
    41,
    5,
    true
  ),
  (
    'neet-biology-cell-cycle-and-cell-division-cytokinesis',
    'neet-biology-cell-cycle-and-cell-division',
    'Plant vs Animal Cytokinesis',
    'comparison',
    'Cytokinesis divides cytoplasm to form two daughter cells and starts while telophase is in progress.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Feature","Animal cell","Plant cell"],"rows":[["Mechanism","Cleavage furrow appears in plasma membrane and deepens to divide cytoplasm.","Golgi vesicles accumulate at equator, grow outward and meet lateral walls."],["Final structure","Cytoplasm divides into two.","Cell-plate forms and later becomes middle lamella."],["Reason for difference","No cell wall issue stated.","Different due to presence of cell wall."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"What forms during plant cytokinesis?","reveal_answer":"Cell-plate.","key_points":["Later, the cell plate becomes the middle lamella.","Mitochondria and plastids get distributed during cytokinesis."],"examples":[],"neet_traps":[]}'::jsonb,
    5,
    42,
    6,
    true
  ),
  (
    'neet-biology-cell-cycle-and-cell-division-syncytium',
    'neet-biology-cell-cycle-and-cell-division',
    'Syncytium',
    'neet_trap',
    'If karyokinesis is not followed by cytokinesis, multinucleate condition arises.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    null,
    null,
    null,
    '{"recall_question":"What condition forms when karyokinesis is not followed by cytokinesis?","reveal_answer":"Syncytium.","key_points":["Source example: liquid endosperm in coconut."],"examples":[],"neet_traps":[]}'::jsonb,
    4,
    42,
    7,
    true
  ),
  (
    'neet-biology-cell-cycle-and-cell-division-significance-mitosis',
    'neet-biology-cell-cycle-and-cell-division',
    'Significance of Mitosis',
    'fact',
    'Mitosis produces genetically identical diploid daughter cells and maintains chromosome number.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Significance","Source detail"],"rows":[["Genome","Produces diploid daughter cells with identical genome."],["Chromosome number","Retains same chromosome number in all somatic cells."],["Growth","Body growth; meristematic tissues allow continuous plant growth throughout life."],["Ratio","Restores nucleo-cytoplasmic ratio disturbed by cell growth."],["Repair","Cell repair and replacement; upper epidermis, lining of gut and blood cells."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"How does mitosis help multicellular organisms?","reveal_answer":"Body growth, chromosome-number maintenance, nucleo-cytoplasmic ratio restoration, repair and replacement.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb,
    5,
    42,
    8,
    true
  ),
  (
    'neet-biology-cell-cycle-and-cell-division-meiosis-basics',
    'neet-biology-cell-cycle-and-cell-division',
    'Meiosis Basics',
    'concept',
    'Meiosis is division of diploid germ cells that halves chromosome number and forms haploid daughter cells.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Feature","Recall answer"],"rows":[["Where","Diploid germ cells during gametogenesis."],["Outcome","Haploid daughter cells (gametes); four haploid cells at end of meiosis II."],["DNA replication","One single cycle of DNA replication."],["Divisions","Two cycles: meiosis I and meiosis II."],["Pairing/recombination","Pairing of homologous chromosomes and recombination between non-sister chromatids."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"How many DNA replications and divisions occur in meiosis?","reveal_answer":"One DNA replication and two divisions.","key_points":[],"examples":[],"neet_traps":["Meiosis has one DNA replication but two divisions."]}'::jsonb,
    5,
    42,
    9,
    true
  ),
  (
    'neet-biology-cell-cycle-and-cell-division-mitosis-vs-meiosis',
    'neet-biology-cell-cycle-and-cell-division',
    'Mitosis vs Meiosis',
    'comparison',
    'The source contrasts mitosis as equational somatic division and meiosis as reductional germ-cell division.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Feature","Mitosis","Meiosis"],"rows":[["Cell type","Somatic cells.","Diploid germ cells."],["Chromosome number","Same in parent and progeny; equational division.","Reduced by half to haploid daughter cells."],["Divisions","One division.","Meiosis I and meiosis II."],["DNA replication","Before M phase in S phase.","Single cycle before meiosis I."],["Products","Two daughter cells.","Four haploid cells at end of meiosis II."],["Variation","Identical genome in daughter cells.","Genetic variation due to crossing over."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"Which division reduces chromosome number by half?","reveal_answer":"Meiosis.","key_points":["Mitosis is equational division."],"examples":[],"neet_traps":[]}'::jsonb,
    5,
    42,
    10,
    true
  ),
  (
    'neet-biology-cell-cycle-and-cell-division-prophase-i-substages',
    'neet-biology-cell-cycle-and-cell-division',
    'Prophase I Substages',
    'sequence',
    'Prophase I is typically longer and more complex and has five substages.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Substage","Recall answer"],"rows":[["Leptotene","Chromatin fibres become long slender chromosomes; nucleus enlarges."],["Zygotene","Chromosomes condense; synapsis begins with synaptonemal complex; homologous pair is bivalent."],["Pachytene","Longer phase; bivalent chromosomes split into similar chromatids called tetrads; recombination nodules appear and crossing over occurs."],["Diplotene","Synaptonemal complex dissolves; homologues separate except at chiasmata; can last months/years in oocytes of some vertebrates."],["Diakinesis","Terminalisation of chiasmata; chromosomes fully condensed; spindle fibres originate; nucleolus and nuclear envelope disappear."]]}'::jsonb,
    '{"type":"bio-prophase-one"}'::jsonb,
    null,
    '{"recall_question":"At which Prophase I stage does crossing over occur?","reveal_answer":"Pachytene.","key_points":["Recombination nodules appear and crossing over occurs between non-sister chromatids.","Recombination is completed by the end of pachytene."],"examples":[],"neet_traps":["Crossing over occurs during pachytene."]}'::jsonb,
    5,
    42,
    11,
    true
  ),
  (
    'neet-biology-cell-cycle-and-cell-division-synapsis-bivalent-tetrad-crossing',
    'neet-biology-cell-cycle-and-cell-division',
    'Synapsis, Bivalent, Tetrad and Crossing Over',
    'classification',
    'Key Prophase I terms are anchored to zygotene and pachytene.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Term","Recall answer"],"rows":[["Synapsis","Pairing of similar chromosomes during zygotene with synaptonemal complex."],["Bivalent","Each pair of homologous chromosomes."],["Tetrad","Bivalent chromosomes split into similar chromatids during pachytene."],["Crossing over","Exchange of genetic material between non-sister chromatids of two homologous chromosomes in presence of recombinase."],["Chiasmata","X-shaped sites of crossovers visible when homologues separate in diplotene."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"What is crossing over?","reveal_answer":"Exchange of genetic material between non-sister chromatids of homologous chromosomes in presence of recombinase.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb,
    5,
    42,
    12,
    true
  ),
  (
    'neet-biology-cell-cycle-and-cell-division-meiosis-i-stages',
    'neet-biology-cell-cycle-and-cell-division',
    'Meiosis I Stages',
    'sequence',
    'Meiosis I separates homologous chromosomes while sister chromatids remain associated.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Stage","Recall answer"],"rows":[["Prophase I","Longer and more complex; leptotene, zygotene, pachytene, diplotene and diakinesis."],["Metaphase I","Spindle formation completed; chromosomes align on equatorial plate; microtubules attach to homologous chromosome pairs."],["Anaphase I","Homologous chromosomes separate while sister chromatids remain associated at centromeres."],["Telophase I","Nuclear membrane and nucleolus reappear; two haploid daughter nuclei form, called diad."],["Interkinesis","Short stage between meiotic divisions; DNA replication does not occur."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"In Anaphase I, what separates and what remains associated?","reveal_answer":"Homologous chromosomes separate; sister chromatids remain associated at centromeres.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb,
    5,
    43,
    13,
    true
  ),
  (
    'neet-biology-cell-cycle-and-cell-division-meiosis-ii-stages',
    'neet-biology-cell-cycle-and-cell-division',
    'Meiosis II Stages',
    'sequence',
    'Meiosis II resembles mitosis.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Stage","Recall answer"],"rows":[["Prophase II","Immediately after cytokinesis; chromosomes compact; nucleolus and nuclear membrane disappear in both nuclei."],["Metaphase II","Chromosomes align at equator; microtubules attach to kinetochores of sister chromatids."],["Anaphase II","Centromeres split simultaneously; chromatids move toward opposite poles."],["Telophase II","Chromosome groups enclosed by nuclear envelope; cytokinesis forms tetrad of cells, i.e., four haploid daughter cells."]]}'::jsonb,
    '{"type":"bio-meiosis-flow"}'::jsonb,
    null,
    '{"recall_question":"Which meiosis stage splits centromeres?","reveal_answer":"Anaphase II.","key_points":["It begins with simultaneous splitting of centromere of each chromosome."],"examples":[],"neet_traps":[]}'::jsonb,
    5,
    43,
    14,
    true
  ),
  (
    'neet-biology-cell-cycle-and-cell-division-significance-meiosis',
    'neet-biology-cell-cycle-and-cell-division',
    'Significance of Meiosis',
    'fact',
    'Meiosis conserves chromosome number and produces variation.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Significance","Source detail"],"rows":[["Conservation","Conserves chromosome number of each species."],["Variation","Causes genetic variation due to crossing over in the population of organisms."],["Evolution","Genetic variation is important for evolution."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"How does meiosis create variation according to the source?","reveal_answer":"Due to crossing over.","key_points":["This variation is important for evolution."],"examples":[],"neet_traps":[]}'::jsonb,
    5,
    43,
    15,
    true
  )
on conflict (id) do update set
  title = excluded.title,
  card_type = excluded.card_type,
  body = excluded.body,
  formulas = excluded.formulas,
  variables = excluded.variables,
  conditions = excluded.conditions,
  table_data = excluded.table_data,
  diagram_data = excluded.diagram_data,
  diagram_svg = excluded.diagram_svg,
  recall_data = excluded.recall_data,
  importance = excluded.importance,
  source_page = excluded.source_page,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active;
