-- Biology Revision Cards Batch 11: Ecology
-- Source: NEET Biology Short Notes PDF, printed pages 135-146 only.

alter table public.formula_cards add column if not exists recall_data jsonb;

insert into public.formula_subjects (id, name, slug, exam, sort_order)
values ('neet-biology', 'Biology', 'biology', 'NEET', 3)
on conflict (id) do update set
  name = excluded.name,
  slug = excluded.slug,
  exam = excluded.exam,
  sort_order = excluded.sort_order;

insert into public.formula_chapters (id, subject_id, title, slug, sort_order)
values
  ('neet-biology-organisms-and-population', 'neet-biology', 'Organisms and Population', 'organisms-and-population', 33),
  ('neet-biology-ecosystem', 'neet-biology', 'Ecosystem', 'ecosystem', 34),
  ('neet-biology-biodiversity-and-conservation', 'neet-biology', 'Biodiversity and Conservation', 'biodiversity-and-conservation', 35)
on conflict (id) do update set
  subject_id = excluded.subject_id,
  title = excluded.title,
  slug = excluded.slug,
  sort_order = excluded.sort_order;

insert into public.formula_cards (
  id, chapter_id, title, card_type, body, formulas, variables, conditions, table_data, diagram_data, diagram_svg, recall_data, importance, source_page, sort_order, is_active
)
values
  ('neet-biology-organisms-and-population-ecology-habitat-niche', 'neet-biology-organisms-and-population', 'Habitat and Niche', 'comparison', 'Ecology studies interactions among organisms and between organisms and the abiotic environment.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Term","Source-backed recall","Examples/details"],"rows":[["Ecology","Study of interactions among organisms and between organism and physical environment","Organisms, Populations, Communities and Biomes"],["Habitat","Different habitats form due to regional and local variations within a biome","Rajasthan desert, rain-soaked Meghalaya forests, deep ocean trenches, thermal springs, compost pits and intestine microbes"],["Niche","Distinct role and position of an organism in its environment","Each organism tolerates conditions and uses resources"]]}'::jsonb, null, null, '{"recall_question":"What is niche?","reveal_answer":"Distinct role and position of an organism in its environment.","key_points":[],"examples":[],"neet_traps":["Habitat is place/context; niche is role and position."]}'::jsonb, 5, 135, 1, true),
  ('neet-biology-organisms-and-population-abiotic-factors', 'neet-biology-organisms-and-population', 'Major Abiotic Factors', 'classification', 'Temperature, water, light and soil shape organism distribution and survival.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Factor","Source-backed recall"],"rows":[["Temperature","Most ecologically relevant environmental factor; affects enzyme kinetics, basal metabolism and physiological functions"],["Water","Second most important factor; plant productivity and distribution depend on water"],["Light","Needed by plants for photosynthesis; photoperiod affects flowering, foraging, reproduction and migration"],["Soil","Composition, grain size, aggregation, pH, minerals and topography determine vegetation and animals"]]}'::jsonb, null, null, '{"recall_question":"Which abiotic factor is called most ecologically relevant?","reveal_answer":"Temperature.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb, 5, 135, 2, true),
  ('neet-biology-organisms-and-population-thermal-salinity-tolerance', 'neet-biology-organisms-and-population', 'Tolerance Terms', 'comparison', 'The source classifies organisms by temperature and salinity tolerance ranges.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Pair","Wide tolerance","Narrow tolerance"],"rows":[["Temperature","Eurythermal","Stenothermal"],["Salinity","Euryhaline","Stenohaline"]]}'::jsonb, null, null, '{"recall_question":"Which organisms tolerate a wide range of salinities?","reveal_answer":"Euryhaline organisms.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb, 5, 135, 3, true),
  ('neet-biology-organisms-and-population-regulator-conformer', 'neet-biology-organisms-and-population', 'Regulator vs Conformer', 'comparison', 'Regulators maintain homeostasis; conformers change with surroundings.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Feature","Regulator","Conformer"],"rows":[["Internal environment","Maintains stable internal environment by physiological and behavioural means","Body temperature or osmotic concentration changes with surroundings"],["Examples","All birds and mammals, very few lower vertebrates and invertebrates","99% animals and nearly all plants"],["Cost","Thermoregulation is energetically expensive, especially for small animals","Avoids the cost of maintaining constant internal environment"],["Graph cue","Internal level stays steady","Internal level follows external level"]]}'::jsonb, null, null, '{"recall_question":"Why are very small animals rare in Polar Regions?","reveal_answer":"They lose body heat very fast and must spend much energy to generate body heat.","key_points":[],"examples":[],"neet_traps":["Most animals are conformers, not regulators."]}'::jsonb, 5, 136, 4, true),
  ('neet-biology-organisms-and-population-migration-suspend', 'neet-biology-organisms-and-population', 'Migration vs Suspension', 'comparison', 'Organisms may escape stress temporarily or suspend activity through dormant forms.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Response","Source-backed recall","Examples"],"rows":[["Migrate","Move temporarily from stressful habitat to a hospitable area and return when stress is over","Migratory birds from Siberia at Keolado National Park, Bharatpur"],["Suspend in microbes/lower plants","Thick walled spores survive unfavourable conditions and germinate under suitable conditions","Bacteria, fungi and lower plants"],["Suspend in higher plants","Seeds and vegetative reproductive structures reduce metabolic activity during stress","Germinate under favourable moisture and temperature"],["Suspend in animals","Dormancy or slowed development","Hibernation, aestivation and diapause"]]}'::jsonb, null, null, '{"recall_question":"Which suspended-development stage is listed for zooplanktons?","reveal_answer":"Diapause.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb, 5, 136, 5, true),
  ('neet-biology-organisms-and-population-hibernation-aestivation-diapause', 'neet-biology-organisms-and-population', 'Hibernation, Aestivation and Diapause', 'neet_trap', 'The suspension examples differ by season or developmental state.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Term","Source-backed example"],"rows":[["Hibernation","Bears during winter"],["Aestivation","Some snails and fishes during summer"],["Diapause","Stage of suspended development of many zooplanktons in lakes and ponds"]]}'::jsonb, null, null, '{"recall_question":"Which term applies to summer dormancy in some snails and fishes?","reveal_answer":"Aestivation.","key_points":[],"examples":[],"neet_traps":["Hibernation is winter; aestivation is summer."]}'::jsonb, 5, 136, 6, true),
  ('neet-biology-organisms-and-population-adaptations', 'neet-biology-organisms-and-population', 'Adaptations', 'classification', 'Adaptation is a morphological, physiological or behavioural attribute enabling survival and reproduction.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Adaptation","Source-backed examples"],"rows":[["Kangaroo rat","Internal fat oxidation gives water; concentrated urine uses minimal water"],["Desert plants","Thick cuticle, sunken stomata, CAM pathway and Opuntia leaves reduced to spines"],["Allen''s Rule","Mammals from colder climates have shorter ears and limbs to reduce heat loss"],["Aquatic mammals","Seals have blubber below skin as insulator"],["High altitude","Acclimatization increases RBC and breathing rate and decreases haemoglobin binding capacity"],["Behavioural","Desert lizards bask in sun or move to shade; some species burrow into soil"]]}'::jsonb, null, null, '{"recall_question":"Which desert plant example has leaves reduced to spines?","reveal_answer":"Opuntia.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb, 5, 136, 7, true),
  ('neet-biology-organisms-and-population-population-attributes', 'neet-biology-organisms-and-population', 'Population Attributes', 'comparison', 'Population density changes through births, deaths and movement.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Attribute","Source-backed recall","Effect on density"],"rows":[["Population","Group of individuals of same species in a geographical area, sharing or competing for resources and potentially reproducing","Base unit"],["Natality (B)","Number of births in a population during a given period","Increases"],["Mortality (D)","Number of deaths in a population during a given period","Decreases"],["Immigration (I)","Individuals of same species coming into habitat from elsewhere","Increases"],["Emigration (E)","Individuals leaving the habitat","Decreases"],["Sex ratio","Population has a sex ratio, e.g. 60% females and 40% males","Attribute"]]}'::jsonb, null, null, '{"recall_question":"Which two factors increase population density?","reveal_answer":"Natality and immigration.","key_points":[],"examples":[],"neet_traps":["Emigration decreases density; immigration increases it."]}'::jsonb, 5, 137, 8, true),
  ('neet-biology-organisms-and-population-age-pyramids', 'neet-biology-organisms-and-population', 'Age Pyramids', 'diagram', 'Age pyramids show population age distribution and growth status.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Pyramid","Source label"],"rows":[["Expanding","Growing"],["Stable","Stable"],["Declining","Declining"]]}'::jsonb, '{"type":"bio-age-pyramids"}'::jsonb, null, '{"recall_question":"Which age-pyramid status indicates a growing population?","reveal_answer":"Expanding.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb, 5, 137, 9, true),
  ('neet-biology-organisms-and-population-population-growth-equations', 'neet-biology-organisms-and-population', 'Population Growth Equations', 'fact', 'The source gives exact symbols for density change and exponential growth.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Equation/value","Source-backed meaning"],"rows":[["Nt+1 = Nt + [(B + I) - (D + E)]","Population density at time t + 1"],["dN/dt = (b - d) x N","Increase or decrease in N during unit time"],["dN/dt = rN","When (b - d) = r"],["Nt = N0 ert","Integral form of exponential growth equation"],["e = 2.71828","Base of natural logarithms"]]}'::jsonb, null, null, '{"recall_question":"What does r represent in population growth?","reveal_answer":"Intrinsic rate of natural increase.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb, 5, 137, 10, true),
  ('neet-biology-organisms-and-population-growth-models', 'neet-biology-organisms-and-population', 'Exponential vs Logistic Growth', 'diagram', 'Unlimited resources give a J-shaped curve; limited resources give a sigmoid curve.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Feature","Exponential growth","Logistic growth"],"rows":[["Resource condition","Unlimited resources","Limited resources"],["Curve","J-shaped curve","Sigmoid curve"],["Source name","Exponential or geometric fashion","Verhulst-Pearl Logistic Growth"],["Equation","dN/dt = rN","dN/dt = rN((K - N) / K)"],["K","Not used","Carrying capacity"]]}'::jsonb, '{"type":"bio-population-growth-curves"}'::jsonb, null, '{"recall_question":"Which growth curve occurs under unlimited resources?","reveal_answer":"Exponential growth, J-shaped curve.","key_points":[],"examples":[],"neet_traps":["K represents carrying capacity in logistic growth."]}'::jsonb, 5, 138, 11, true),
  ('neet-biology-organisms-and-population-r-values-life-history', 'neet-biology-organisms-and-population', 'r Values and Life History', 'fact', 'Life-history traits evolve under limited abiotic and biotic components of habitat.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Cue","Source-backed value/example"],"rows":[["Norway rat r","0.015"],["Flour beetle r","0.12"],["Human population in India (1981) r","0.0205"],["Breed once","Pacific salmon fish and bamboo"],["Breed many times","Most birds and mammals"],["Many small offspring","Oysters and pelagic fishes"],["Few large offspring","Birds and mammals"]]}'::jsonb, null, null, '{"recall_question":"What r value is given for human population in India (1981)?","reveal_answer":"0.0205.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb, 5, 137, 12, true),
  ('neet-biology-organisms-and-population-interaction-matrix', 'neet-biology-organisms-and-population', 'Population Interaction Matrix', 'diagram', 'Interspecific interactions are represented with +, - and 0 effects.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Interaction","Species A","Species B","Source meaning"],"rows":[["Mutualism","+","+","Both species benefitted"],["Competition","-","-","Both species harmed"],["Predation","+","-","Predator benefitted; prey harmed"],["Parasitism","+","-","Parasite benefitted; host harmed"],["Commensalism","+","0","One benefitted; other unaffected"],["Amensalism","-","0","One harmed; other unaffected"]]}'::jsonb, '{"type":"bio-interaction-matrix"}'::jsonb, null, '{"recall_question":"Which interaction is + and 0?","reveal_answer":"Commensalism.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb, 5, 138, 13, true),
  ('neet-biology-organisms-and-population-predation', 'neet-biology-organisms-and-population', 'Predation', 'concept', 'Predators control prey populations and maintain species diversity.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Cue","Source-backed examples"],"rows":[["Predator context","Carnivores and herbivores are predators in a broad ecological context"],["Phytophagous insects","About 25% insects"],["Prickly pear cactus","Introduced in Australia in 1920''s and later controlled by cactus-feeding predator moth"],["Pisaster","Removal caused extinction of over 10 invertebrate species within a year"],["Prey defenses","Camouflage, poisons, thorns and chemicals"],["Chemical defenses","Calotropis cardiac glycosides; nicotine, caffeine, quinine, strychnine and opium"]]}'::jsonb, null, null, '{"recall_question":"Which starfish example shows predators maintain diversity?","reveal_answer":"Pisaster.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb, 5, 138, 14, true),
  ('neet-biology-organisms-and-population-competition', 'neet-biology-organisms-and-population', 'Competition', 'concept', 'Competition lowers fitness of one species in the presence of another.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Cue","Source-backed detail"],"rows":[["Definition","Fitness of one species or r value is significantly lower in presence of another species"],["Unrelated competitors","Flamingoes and fishes compete for zooplankton in shallow South American lakes"],["Interference competition","Feeding efficiency reduced by inhibitory presence of another species even when resources are abundant"],["Abingdon tortoise","Extinct within a decade after goats were introduced in Galapagos Islands"],["Connell experiment","Removing Balanus allowed Chthamalus to colonize intertidal zone"],["Gause principle","Two closely related species competing for same resources cannot co-exist indefinitely in limited resources"],["Resource partitioning","Species divide limited resources by feeding times or foraging patterns"]]}'::jsonb, null, null, '{"recall_question":"What is competitive release?","reveal_answer":"Expansion of distributional range when competing species is removed.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb, 5, 139, 15, true),
  ('neet-biology-organisms-and-population-parasitism', 'neet-biology-organisms-and-population', 'Parasitism', 'comparison', 'Parasites harm hosts and often show specialized adaptations.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Type/cue","Source-backed recall","Examples"],"rows":[["Parasite adaptations","Loss of sense organs, adhesive organs or suckers, loss of digestive system and high reproductive capacity","Host-specific parasites co-evolve"],["Ectoparasites","Feed on external surface of host","Lice on humans, ticks on dogs, copepods on marine fishes, Cuscuta on hedge plants"],["Endoparasites","Live inside host body at sites such as liver, kidney, lungs and RBC","Life cycles are more complex"],["Brood parasitism","Parasitic birds lay eggs in host nest and let host incubate them","Cuckoo and crow"],["Female mosquito","Not considered parasite in source","Needs blood for reproduction, not as food"]]}'::jsonb, null, null, '{"recall_question":"Why is female mosquito not considered a parasite in the source?","reveal_answer":"It needs blood only for reproduction, not as food.","key_points":[],"examples":[],"neet_traps":["Cuscuta has no chlorophyll and derives nutrition from host."]}'::jsonb, 5, 139, 16, true),
  ('neet-biology-organisms-and-population-commensalism-mutualism', 'neet-biology-organisms-and-population', 'Commensalism vs Mutualism', 'comparison', 'Commensalism benefits one without affecting the other; mutualism benefits both.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Interaction","Source-backed examples"],"rows":[["Commensalism","Orchid on mango branch; barnacles on whale; cattle egret with grazing cattle; clown fish with sea anemone"],["Mutualism","Lichen between fungus and algae/cyanobacteria; mycorrhizae between fungi and higher plant roots"],["Fig and wasp","Fig species pollinated only by partner wasp; fig offers developing seeds as larval food"],["Ophrys sexual deceit","Petal resembles female bee; male bee pseudocopulates and transfers pollen"]]}'::jsonb, null, null, '{"recall_question":"Which interaction is shown by lichen?","reveal_answer":"Mutualism.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb, 5, 139, 17, true),
  ('neet-biology-ecosystem-ecosystem-basics', 'neet-biology-ecosystem', 'Ecosystem Structure', 'classification', 'An ecosystem is a functional unit where organisms interact with each other and the physical environment.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Component","Source-backed recall"],"rows":[["Terrestrial ecosystems","Forest, grassland and desert"],["Aquatic ecosystems","Pond, lake, wetland, river and estuary"],["Man-made ecosystems","Crop fields and aquarium"],["Global ecosystem","Entire biosphere"],["Stratification","Vertical distribution of species at different levels; trees, shrubs, herbs and grasses in forest"]]}'::jsonb, null, null, '{"recall_question":"What is stratification in an ecosystem?","reveal_answer":"Vertical distribution of different species occupying different levels.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb, 5, 140, 1, true),
  ('neet-biology-ecosystem-pond-ecosystem', 'neet-biology-ecosystem', 'Pond as Ecosystem', 'concept', 'A pond is a shallow, simple, self-sustainable water body with all basic ecosystem components.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Component/function","Source-backed examples"],"rows":[["Abiotic components","Water and soil deposit"],["Climatic conditions","Solar input, temperature cycle and day-length"],["Autotrophs","Phytoplankton, some algae and floating, submerged and marginal plants"],["Consumers","Zooplankton, free swimming and bottom dwelling forms"],["Decomposers","Fungi, bacteria and flagellates"],["Four functions","Productivity, decomposition, energy flow and nutrient cycling"]]}'::jsonb, null, null, '{"recall_question":"What are the four basic ecosystem functions?","reveal_answer":"Productivity, decomposition, energy flow and nutrient cycling.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb, 5, 140, 2, true),
  ('neet-biology-ecosystem-productivity', 'neet-biology-ecosystem', 'GPP vs NPP', 'comparison', 'Primary productivity is biomass production by plants during photosynthesis.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Term","Source-backed recall"],"rows":[["Primary production","Biomass produced per unit area over time by plants during photosynthesis"],["Productivity","Rate of biomass production"],["GPP","Rate of production of organic matter during photosynthesis"],["NPP","Available biomass for consumption to heterotrophs"],["Equation","NPP = GPP - R"],["Secondary productivity","Rate of formation of new organic matter by consumers"]]}'::jsonb, null, null, '{"recall_question":"What is the source equation for NPP?","reveal_answer":"NPP = GPP - R.","key_points":[],"examples":[],"neet_traps":["GPP includes plant respiration losses; NPP is available biomass."]}'::jsonb, 5, 140, 3, true),
  ('neet-biology-ecosystem-productivity-values', 'neet-biology-ecosystem', 'Productivity Values', 'fact', 'The source gives whole-biosphere and ocean NPP values.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Cue","Source-backed value"],"rows":[["Annual NPP of whole biosphere","About 170 billion tons dry weight of organic matter"],["Ocean surface share","About 70% of surface"],["Ocean productivity","Only 55 billion tons"],["Primary production units","Weight (g-2) or energy (kcal m-2)"],["Productivity units","g-2 yr-1 or (kcal m-2) yr-1"]]}'::jsonb, null, null, '{"recall_question":"What annual NPP value is given for the whole biosphere?","reveal_answer":"About 170 billion tons dry weight.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb, 5, 140, 4, true),
  ('neet-biology-ecosystem-decomposition-process', 'neet-biology-ecosystem', 'Decomposition Process', 'process', 'Decomposition breaks complex organic matter into inorganic substances.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Step","Source-backed event"],"rows":[["Fragmentation","Detritivores such as earthworm break detritus into smaller particles"],["Leaching","Water soluble inorganic nutrients go into soil horizon and precipitate as unavailable salts"],["Catabolism","Bacterial and fungal enzymes degrade detritus into simpler inorganic substances"],["Humification","Humus accumulates; resistant to microbial action and serves as nutrient reservoir"],["Mineralization","Microbes degrade humus and release inorganic nutrients"]]}'::jsonb, '{"type":"bio-decomposition-flow"}'::jsonb, null, '{"recall_question":"What is raw material for decomposition called?","reveal_answer":"Detritus.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb, 5, 140, 5, true),
  ('neet-biology-ecosystem-decomposition-factors', 'neet-biology-ecosystem', 'Factors Affecting Decomposition', 'comparison', 'Detritus chemistry and climate control decomposition rate.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Factor","Slower","Faster"],"rows":[["Chemical composition","Lignin and chitin rich detritus","Nitrogen and water-soluble substances like sugars"],["Climate","Low temperature and anaerobiosis inhibit decomposition","Warm and moist environment favours decomposition"]]}'::jsonb, null, null, '{"recall_question":"Which detritus chemistry slows decomposition?","reveal_answer":"Rich in lignin and chitin.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb, 5, 140, 6, true),
  ('neet-biology-ecosystem-energy-flow', 'neet-biology-ecosystem', 'Energy Flow', 'process', 'Energy decreases at successive trophic levels, and the number of GFC trophic levels is restricted by 10% law.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Cue","Source-backed recall"],"rows":[["Energy source","Sun is the only source for all ecosystems except deep sea hydro-thermal ecosystem"],["PAR","Less than 50% of incident solar radiation is photosynthetically active radiation"],["Plant capture","Plants capture only 2-10% of PAR"],["10% law","Only 10% energy is transferred to each trophic level from the lower trophic level"],["Standing crop","Amount of living material in a trophic level at a given time"]]}'::jsonb, '{"type":"bio-trophic-energy"}'::jsonb, null, '{"recall_question":"What percentage of energy is transferred between trophic levels according to 10% law?","reveal_answer":"Only 10%.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb, 5, 141, 7, true),
  ('neet-biology-ecosystem-food-chain-types', 'neet-biology-ecosystem', 'Grazing vs Detritus Food Chain', 'comparison', 'The source distinguishes food chains by whether feeding begins with living plants or detritus.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Feature","Grazing Food Chain (GFC)","Detritus Food Chain (DFC)"],"rows":[["Beginning","Primary consumer feeds on living plants","Primary consumer feeds on dead organic matter"],["Aquatic ecosystem","Major conduit for energy flow","Less emphasized"],["Terrestrial ecosystem","Less energy than DFC","Much energy flows through DFC"],["Connections","May connect with DFC at some levels","Some DFC organisms are prey to GFC animals"],["Food web","Interconnections of food chains","Interconnections of food chains"]]}'::jsonb, null, null, '{"recall_question":"Which food chain is major energy conduit in aquatic ecosystems?","reveal_answer":"Grazing Food Chain.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb, 5, 141, 8, true),
  ('neet-biology-ecosystem-ecological-pyramids', 'neet-biology-ecosystem', 'Ecological Pyramids', 'diagram', 'Ecological pyramids represent food chains as number, biomass or energy pyramids.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Pyramid","Source-backed recall","Exception/trap"],"rows":[["Number","Grassland example upright","Inverted when insects feed on a tree"],["Biomass","Shows sharp decrease in biomass at higher trophic levels","In sea, inverted because fish biomass exceeds phytoplankton biomass"],["Energy","Primary producers convert only 1% of sunlight available to them into NPP","Always upright because energy is lost as heat at each trophic level"]]}'::jsonb, '{"type":"bio-ecological-pyramids"}'::jsonb, null, '{"recall_question":"Which ecological pyramid is always upright?","reveal_answer":"Pyramid of energy.","key_points":[],"examples":[],"neet_traps":["Number and biomass can be inverted; energy is always upright."]}'::jsonb, 5, 141, 9, true),
  ('neet-biology-ecosystem-pyramid-limitations', 'neet-biology-ecosystem', 'Ecological Pyramid Limitations', 'neet_trap', 'Pyramids simplify food chains and miss several real ecosystem features.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Limitation","Source-backed detail"],"rows":[["Same species","Does not consider same species belonging to two or more trophic levels"],["Food web","Assumes a simple food chain that never exists in nature and does not accommodate food web"],["Saprophytes","Saprophytes are not included"]]}'::jsonb, null, null, '{"recall_question":"Are saprophytes included in ecological pyramids in the source?","reveal_answer":"No.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb, 5, 142, 10, true),
  ('neet-biology-ecosystem-succession-basics', 'neet-biology-ecosystem', 'Ecological Succession', 'concept', 'Succession is gradual, slow and predictable change toward a climax community.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Term","Source-backed recall"],"rows":[["Succession","Change in species composition of an area leading to a climax community"],["Climax community","Community in equilibrium with environment"],["Sere","Entire sequence of communities that successively change in an area"],["Seral stage","Individual transitional community"],["Pioneer species","Species invading a bare area"],["During succession","Species diversity, number of species/organisms and total biomass increase"]]}'::jsonb, null, null, '{"recall_question":"What are species invading a bare area called?","reveal_answer":"Pioneer species.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb, 5, 142, 11, true),
  ('neet-biology-ecosystem-primary-secondary-succession', 'neet-biology-ecosystem', 'Primary vs Secondary Succession', 'comparison', 'Primary succession begins where no living organisms existed; secondary follows loss of existing organisms.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Feature","Primary succession","Secondary succession"],"rows":[["Starting area","No living organisms ever existed","Existing organisms are lost"],["Examples","Newly cooled lava, bare rock, newly created pond or reservoir","Abandoned farm lands, burned or cut forests, flooded lands"],["Soil/sediment","Fertile soil must be formed","Some soil or sediment is present"],["Speed","Very slow","Faster than primary succession"]]}'::jsonb, null, null, '{"recall_question":"Which succession is faster in the source?","reveal_answer":"Secondary succession.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb, 5, 142, 12, true),
  ('neet-biology-ecosystem-hydrarch-xerarch', 'neet-biology-ecosystem', 'Hydrarch vs Xerarch Succession', 'comparison', 'Both plant succession paths lead toward mesic conditions.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Type","Starting condition","Direction"],"rows":[["Hydrarch succession","Wetter areas","Hydric to mesic conditions"],["Xerarch succession","Dry areas","Xeric to mesic conditions"]]}'::jsonb, null, null, '{"recall_question":"Which succession progresses from xeric to mesic conditions?","reveal_answer":"Xerarch succession.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb, 5, 142, 13, true),
  ('neet-biology-ecosystem-succession-sequences', 'neet-biology-ecosystem', 'Succession Sequences', 'sequence', 'The source gives stage orders for primary succession on rocks and in water.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Succession","Source-backed sequence"],"rows":[["Primary succession on rocks","Lichens -> small plants like bryophytes -> bigger plants -> forest"],["Primary succession in water","Phytoplankton -> rooted-submerged plants -> rooted-floating angiosperms -> free-floating plants -> reed-swamp -> marsh-meadow -> scrub -> trees"]]}'::jsonb, '{"type":"bio-succession-sequence"}'::jsonb, null, '{"recall_question":"What pioneer species begins primary succession on rocks?","reveal_answer":"Lichens.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb, 5, 142, 14, true),
  ('neet-biology-ecosystem-nutrient-cycling', 'neet-biology-ecosystem', 'Nutrient Cycling', 'comparison', 'Nutrients are recycled through ecosystem components and reservoirs.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Term/cycle","Source-backed recall"],"rows":[["Standing state","Amount of nutrients such as C, N, P and Ca in soil at a given time"],["Nutrient cycling","Movement of nutrient elements through various components of ecosystem"],["Gaseous cycle","Reservoir exists in atmosphere; examples Nitrogen and Carbon cycles"],["Sedimentary cycle","Reservoir located in Earth''s crust; examples Sulphur and Phosphorus cycles"]]}'::jsonb, null, null, '{"recall_question":"Which nutrient cycle type has reservoir in Earth''s crust?","reveal_answer":"Sedimentary cycle.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb, 5, 142, 15, true),
  ('neet-biology-ecosystem-carbon-phosphorus', 'neet-biology-ecosystem', 'Carbon vs Phosphorus Cycle', 'comparison', 'The source contrasts carbon and phosphorus by atmospheric input and gaseous exchange.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Feature","Carbon cycle","Phosphorus cycle"],"rows":[["Reservoir","Atmosphere about 1%, organisms 49% dry weight, oceans 71% dissolved carbon, fossil fuel etc.","Rock in the form of phosphates"],["Annual fixation","4 x 10^13 kg carbon fixed in biosphere through photosynthesis annually","No annual fixation value given"],["Atmospheric input","Higher","Much smaller"],["Gaseous exchange","There is gaseous exchange between organism and environment","Gaseous exchange is negligible"]]}'::jsonb, null, null, '{"recall_question":"What is the natural reservoir of phosphorus?","reveal_answer":"Rock in the form of phosphates.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb, 5, 143, 16, true),
  ('neet-biology-ecosystem-ecosystem-services', 'neet-biology-ecosystem', 'Ecosystem Services', 'fact', 'Ecosystem services are products of ecosystem processes.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Cue","Source-backed detail"],"rows":[["Forest services","Purify air and water, mitigate droughts and floods, cycle nutrients, generate fertile soils, provide wildlife habitat, maintain biodiversity, pollinate crops and store carbon"],["Robert Costanza","Tried to put price tags on nature''s life-support services"],["Total value","US $ 33 trillion a year"],["Global GNP comparison","Nearly twice global gross national product, US $ 18 trillion"],["Soil formation","About 50% of total cost"],["Climate regulation and wildlife habitat","About 6% each"]]}'::jsonb, null, null, '{"recall_question":"What average annual value is given for ecosystem services?","reveal_answer":"US $ 33 trillion a year.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb, 5, 143, 17, true),
  ('neet-biology-biodiversity-and-conservation-biodiversity-levels', 'neet-biology-biodiversity-and-conservation', 'Levels of Biodiversity', 'comparison', 'Biodiversity ranges from cellular macromolecules to biomes.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Level","Source-backed recall","Example"],"rows":[["Genetic diversity","Diversity shown by a single species at genetic level","Rauwolfia vomitoria potency and concentration of reserpine; India has >50,000 rice strains and 1000 mango varieties"],["Species diversity","Diversity at species level","Western Ghats have greater amphibian species than Eastern Ghats"],["Ecological diversity","Diversity at ecosystem level","India has deserts, rain forests, mangroves, coral reefs, wetlands, estuaries and alpine meadows"]]}'::jsonb, null, null, '{"recall_question":"Who popularized the term biodiversity?","reveal_answer":"Edward Wilson.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb, 5, 144, 1, true),
  ('neet-biology-biodiversity-and-conservation-global-india-biodiversity', 'neet-biology-biodiversity-and-conservation', 'Global and Indian Species Diversity', 'fact', 'The source uses IUCN 2004 and Robert May''s estimates for species counts.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Cue","Source-backed value"],"rows":[["IUCN 2004 described species","More than 1.5 million"],["Robert May global estimate","About 7 million species"],["Recorded so far","Only 22% of total species"],["Animals vs plants/fungi","Animals above 70%; plants including Plantae and Fungi 22%"],["Insects","70% of animals; out of every 10 animals, 7 are insects"],["India land area/species share","2.4% land area and 8.1% species diversity"],["India recorded species","Nearly 45,000 plant species and twice as many animals"]]}'::jsonb, null, null, '{"recall_question":"What percentage of world land area does India have in the source?","reveal_answer":"2.4%.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb, 5, 144, 2, true),
  ('neet-biology-biodiversity-and-conservation-latitudinal-gradient', 'neet-biology-biodiversity-and-conservation', 'Latitudinal Gradient', 'comparison', 'Species diversity decreases from equator to poles.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Region","Source-backed value/detail"],"rows":[["Tropics","23.5° N to 23.5° S; more species than temperate or polar areas"],["Colombia","About 1400 bird species"],["India","> 1200 bird species"],["New York (41° N)","105 bird species"],["Greenland (71° N)","56 bird species"],["Ecuador","Up to 10 times vascular plant species compared to Midwest USA temperate forest"]]}'::jsonb, null, null, '{"recall_question":"How does species diversity change from equator to poles?","reveal_answer":"It decreases from the equator to the poles.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb, 5, 144, 3, true),
  ('neet-biology-biodiversity-and-conservation-amazon-biodiversity', 'neet-biology-biodiversity-and-conservation', 'Amazonian Rain Forest Diversity', 'fact', 'The source calls tropical Amazonian rain forest the greatest biodiversity on earth.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Group","Source-backed count"],"rows":[["Plants","> 40000 species"],["Fishes","3000 species"],["Birds","1300 species"],["Mammals","427 species"],["Amphibians","427 species"],["Reptiles","378 species"],["Invertebrates","> 1,25,000 species"]]}'::jsonb, null, null, '{"recall_question":"Which rainforest is called greatest biodiversity on earth?","reveal_answer":"Tropical Amazonian rain forest.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb, 5, 144, 4, true),
  ('neet-biology-biodiversity-and-conservation-species-area', 'neet-biology-biodiversity-and-conservation', 'Species-Area Relationship', 'diagram', 'Alexander von Humboldt found species richness increases with explored area up to a limit.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Equation/value","Source-backed meaning"],"rows":[["S = CA^Z","Species richness-area relationship"],["S","Species richness"],["A","Area"],["C","Y-intercept"],["Z","Slope of the line or regression coefficient"],["Log S = log C + Z log A","Straight line on logarithmic scale"],["Small areas Z","0.1 to 0.2"],["Large areas Z","0.6 to 1.2"],["Frugivorous birds and mammals Z","1.15"]]}'::jsonb, '{"type":"bio-species-area"}'::jsonb, null, '{"recall_question":"What does Z represent in species-area relationship?","reveal_answer":"Slope of the line, or regression coefficient.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb, 5, 144, 5, true),
  ('neet-biology-biodiversity-and-conservation-importance-rivet', 'neet-biology-biodiversity-and-conservation', 'Species Diversity Importance', 'concept', 'More species stabilise ecosystem processes and productivity.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Cue","Source-backed recall"],"rows":[["David Tilman","Plots with more species show less year-to-year variation in total biomass"],["Diversity effect","Increased diversity contributes to higher productivity"],["Rivet popper hypothesis","Analogy proposed by Paul Ehrlich"],["Rivet analogy","Species are rivets in an airplane ecosystem"],["Key species","Loss of rivets on wings is more dangerous than loss from seats/windows"]]}'::jsonb, null, null, '{"recall_question":"Who proposed rivet popper hypothesis?","reveal_answer":"Paul Ehrlich.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb, 5, 145, 6, true),
  ('neet-biology-biodiversity-and-conservation-biodiversity-loss-stats', 'neet-biology-biodiversity-and-conservation', 'Biodiversity Loss Statistics', 'fact', 'The source uses IUCN Red List 2004 values for extinction and threat.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Cue","Source-backed value"],"rows":[["Extinct in last 500 years","784 species: 338 vertebrates, 359 invertebrates and 87 plants"],["Examples","Dodo, Quagga, Thylacine, Stellar''s sea cow and 3 tiger subspecies Bali, Javan, Caspian"],["Disappeared in last 20 years","27 species"],["Threatened","More than 15,500 species"],["Threat percentages","12% birds, 23% mammals, 32% amphibians, 31% gymnosperms"],["Current extinction rate","100 - 1000 times faster than pre-human times"],["Future trend","Nearly 50% species might be extinct within next 100 years"]]}'::jsonb, null, null, '{"recall_question":"How many species were extinct in the last 500 years according to IUCN Red List 2004?","reveal_answer":"784 species.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb, 5, 145, 7, true),
  ('neet-biology-biodiversity-and-conservation-evil-quartet', 'neet-biology-biodiversity-and-conservation', 'The Evil Quartet', 'diagram', 'The source frames the four major causes of biodiversity loss as the Evil Quartet.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Cause","Source-backed examples"],"rows":[["Habitat loss and fragmentation","Tropical rain forests lost from 14% to 6%; Amazon cut for soya beans or cattle grasslands"],["Over-exploitation","Stellar''s sea cow and Passenger pigeon extinct"],["Alien species invasions","Nile Perch in Lake Victoria; Parthenium, Lantana, Eicchornia; African Catfish Clarias gariepinus"],["Co-extinction","Host extinction causes parasite extinction; plant-pollinator mutualism loss"]]}'::jsonb, '{"type":"bio-evil-quartet"}'::jsonb, null, '{"recall_question":"What is the most important cause of biodiversity loss in the source?","reveal_answer":"Habitat loss and fragmentation.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb, 5, 145, 8, true),
  ('neet-biology-biodiversity-and-conservation-conservation-reasons', 'neet-biology-biodiversity-and-conservation', 'Why Conserve Biodiversity?', 'comparison', 'The source gives narrowly utilitarian, broadly utilitarian and ethical arguments.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Reason","Source-backed recall"],"rows":[["Narrowly utilitarian","Economic benefits: food, firewood, fibre, construction material, industrial products and medicines"],["Drug/medicine value","More than 25% drugs are derived from plants; 25,000 plant species have medicinal value"],["Broadly utilitarian","Ecosystem services such as Amazon producing 20% of earth''s atmospheric O2, pollination and aesthetic pleasures"],["Ethical","Every species has intrinsic value and humans have a moral duty to care for well-being"]]}'::jsonb, null, null, '{"recall_question":"Which forest is called lung of the planet?","reveal_answer":"Amazon forest.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb, 5, 145, 9, true),
  ('neet-biology-biodiversity-and-conservation-in-situ-ex-situ', 'neet-biology-biodiversity-and-conservation', 'In Situ vs Ex Situ Conservation', 'diagram', 'Biodiversity conservation is on site or off site.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Feature","In situ conservation","Ex situ conservation"],"rows":[["Meaning","Conservation of genetic resources within natural or human-made ecosystems in which they occur","Conservation of organisms outside their habitats"],["Examples","National Parks, Sanctuaries, Biosphere reserves, cultural landscapes and natural monuments","Genetic resource centres, zoological parks, wildlife safari parks, botanical gardens, gene banks and cryopreservation"],["National Park","Strictly reserved for wildlife; private ownership, cultivation and grazing prohibited","Not applicable"],["Sanctuary","Protection only to animals; timber/minor forest products/private ownership allowed if animals are not harmed","Not applicable"]]}'::jsonb, '{"type":"bio-conservation-types"}'::jsonb, null, '{"recall_question":"Which conservation type occurs outside natural habitat?","reveal_answer":"Ex situ conservation.","key_points":[],"examples":[],"neet_traps":["In situ is on site; ex situ is off site."]}'::jsonb, 5, 145, 10, true),
  ('neet-biology-biodiversity-and-conservation-protected-areas-sacred-groves', 'neet-biology-biodiversity-and-conservation', 'Protected Areas and Sacred Groves', 'fact', 'The source gives India protected-area counts and sacred grove examples.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Cue","Source-backed detail"],"rows":[["India protected-area counts","14 Biosphere Reserves, 90 National Parks and 448 wildlife sanctuaries"],["National park example","Eravikulam National Park in Kerala"],["Sanctuary example","Periyar wildlife sanctuary in Kerala"],["Sacred groves","Forest fragments communally protected based on religious beliefs"],["Sacred grove examples","Khasi and Jaintia Hills, Aravalli Hills, Western Ghat regions of Karnataka and Maharashtra, Sarguja, Chanda and Bastar"]]}'::jsonb, null, null, '{"recall_question":"How many National Parks does India have in the source?","reveal_answer":"90 National Parks.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb, 5, 145, 11, true),
  ('neet-biology-biodiversity-and-conservation-hotspots-international', 'neet-biology-biodiversity-and-conservation', 'Hotspots and International Efforts', 'classification', 'Hotspots are rich, endemic and threatened regions; international efforts set conservation objectives.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Cue","Source-backed detail"],"rows":[["Hotspots","Regions with very high species richness, high endemism and high threat"],["World hotspots","34 hotspots"],["Indian biodiversity regions","Western Ghats & Sri Lanka, Indo-Burma and Himalaya"],["Hotspot land area","All hotspots together cover only < 2% of earth''s land area"],["Extinction reduction","Protection of hotspots reduced ongoing extinctions by 30%"],["Earth Summit/CBD","Rio de Jeneiro, 1992; conservation, sustainable use and benefit sharing"],["World Summit","Johannesburg, South Africa, 2002; 190 countries pledged to reduce current biodiversity-loss rate"]]}'::jsonb, null, null, '{"recall_question":"Name the three hotspots covering India''s biodiversity regions in the source.","reveal_answer":"Western Ghats & Sri Lanka, Indo-Burma and Himalaya.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb, 5, 146, 12, true)
on conflict (id) do update set
  chapter_id = excluded.chapter_id,
  title = excluded.title,
  card_type = excluded.card_type,
  body = excluded.body,
  formulas = excluded.formulas,
  variables = excluded.variables,
  conditions = excluded.conditions,
  table_data = excluded.table_data,
  diagram_data = excluded.diagram_data,
  diagram_svg = excluded.diagram_svg,
  recall_data = excluded.recall_data,
  importance = excluded.importance,
  source_page = excluded.source_page,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active;
