alter table public.formula_cards
  add column if not exists recall_data jsonb;

insert into public.formula_subjects (id, name, slug, exam, sort_order) values
  ('neet-biology', 'Biology', 'biology', 'NEET', 3)
on conflict (id) do update set
  name = excluded.name,
  slug = excluded.slug,
  exam = excluded.exam,
  sort_order = excluded.sort_order;

insert into public.formula_chapters (id, subject_id, title, slug, sort_order) values
  ('neet-biology-morphology-of-flowering-plants', 'neet-biology', 'Morphology of Flowering Plants', 'morphology-of-flowering-plants', 5),
  ('neet-biology-anatomy-of-flowering-plants', 'neet-biology', 'Anatomy of Flowering Plants', 'anatomy-of-flowering-plants', 6)
on conflict (id) do update set
  title = excluded.title,
  slug = excluded.slug,
  sort_order = excluded.sort_order;

insert into public.formula_cards (
  id, chapter_id, title, card_type, body, formulas, variables, conditions, table_data, diagram_data, diagram_svg, recall_data, importance, source_page, sort_order, is_active
) values
  (
    'neet-biology-morphology-of-flowering-plants-plant-body-root-shoot',
    'neet-biology-morphology-of-flowering-plants',
    'Morphology and Plant Body',
    'concept',
    'Morphology is the study of external forms of organisms. A flowering plant has a root system and a shoot system.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    null,
    null,
    null,
    '{"recall_question":"What are the two main parts of a flowering plant?","reveal_answer":"Root system and shoot system.","key_points":["Root system is the underground part.","Shoot system is the portion above the ground."],"examples":[],"neet_traps":[]}'::jsonb,
    4,
    21,
    1,
    true
  ),
  (
    'neet-biology-morphology-of-flowering-plants-root-systems-comparison',
    'neet-biology-morphology-of-flowering-plants',
    'Tap, Fibrous and Adventitious Roots',
    'comparison',
    'Root systems are grouped by origin of the primary root and replacement roots.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Root system","Recall cue","Source examples"],"rows":[["Tap root","Primary root from radicle persists with lateral roots; seen in dicots.","Mustard plant"],["Fibrous root","Primary root is short lived and replaced by many roots from base of stem; seen in monocots.","Wheat"],["Adventitious root","Roots arise from parts other than radicle.","Grass, Monstera and banyan tree"]]}'::jsonb,
    '{"type":"bio-root-systems"}'::jsonb,
    null,
    '{"recall_question":"How do tap, fibrous and adventitious roots differ?","reveal_answer":"Tap root persists from radicle; fibrous roots replace the short-lived primary root; adventitious roots arise from parts other than radicle.","key_points":[],"examples":["Mustard plant","Wheat","Grass, Monstera and banyan tree"],"neet_traps":[]}'::jsonb,
    5,
    21,
    2,
    true
  ),
  (
    'neet-biology-morphology-of-flowering-plants-root-regions',
    'neet-biology-morphology-of-flowering-plants',
    'Regions of the Root',
    'diagram',
    'The root tip has root cap, meristematic region, elongation region and maturation region.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Region","Recall answer"],"rows":[["Root cap","Covering at apex; protects tender apex."],["Meristematic activity","Above root cap; small, thin-walled cells with dense protoplasm divide repeatedly."],["Elongation","Just above meristematic region; cells elongate and enlarge, helping root grow in length."],["Maturation","Proximal to elongation zone; cells differentiate and mature."],["Root hairs","Very fine thread-like epidermal structures behind elongation region; absorb water and minerals."]]}'::jsonb,
    '{"type":"bio-root-regions"}'::jsonb,
    null,
    '{"recall_question":"In which region are root hairs formed?","reveal_answer":"Behind the region of elongation, in the region of maturation.","key_points":["Root hairs are very fine, delicate, thread-like structures formed from epidermal cells."],"examples":[],"neet_traps":["Root hairs belong to the maturation region, not the meristematic region."]}'::jsonb,
    5,
    21,
    3,
    true
  ),
  (
    'neet-biology-morphology-of-flowering-plants-root-modifications',
    'neet-biology-morphology-of-flowering-plants',
    'Root Modifications',
    'comparison',
    'Roots may be modified for functions other than absorption and conduction.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Modification","Recall cue","Source examples"],"rows":[["Storage roots","Swollen roots for food storage.","Tap roots of carrot, turnips and adventitious roots of sweet potato"],["Prop roots","Hanging structures that support banyan tree.","Banyan tree"],["Stilt roots","Supporting roots from lower nodes of stem.","Maize & sugarcane"],["Pneumatophores","Roots come out of ground and grow vertically upwards to get oxygen for respiration.","Rhizophora growing in swampy areas"]]}'::jsonb,
    null,
    null,
    '{"recall_question":"Which root modification helps plants growing in swampy areas get oxygen?","reveal_answer":"Pneumatophores.","key_points":["They come out of the ground and grow vertically upwards to get oxygen for respiration."],"examples":["Rhizophora"],"neet_traps":["Do not confuse stilt roots for support with pneumatophores for respiration."]}'::jsonb,
    5,
    21,
    4,
    true
  ),
  (
    'neet-biology-morphology-of-flowering-plants-root-functions',
    'neet-biology-morphology-of-flowering-plants',
    'Functions of Root',
    'fact',
    'The source lists absorption, anchorage, storage and synthesis of plant growth regulators as root functions.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Function","Source wording"],"rows":[["Absorption","Absorption of water and minerals from the soil."],["Anchorage","Provide a proper anchorage to the plant parts."],["Storage","Storage of reserve food material."],["Synthesis","Synthesis of plant growth regulators."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"List the four functions of root given in the source.","reveal_answer":"Absorption, anchorage, storage and synthesis of plant growth regulators.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb,
    4,
    21,
    5,
    true
  ),
  (
    'neet-biology-morphology-of-flowering-plants-stem-definition-functions',
    'neet-biology-morphology-of-flowering-plants',
    'Stem, Nodes and Internodes',
    'concept',
    'Stem is the ascending axis from plumule. Nodes bear leaves; internodes are portions between two nodes.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Stem feature","Recall answer"],"rows":[["Origin","Ascending part of the axis that develops from plumule of a germinating seed."],["Bears","Branches, leaves, flowers, fruits, terminal or axillary buds, nodes and internodes."],["Nodes","Regions of stem where leaves are born."],["Internodes","Portions between two nodes."],["Functions","Spreading branches, conduction of water/minerals/photosynthates, food storage, support, protection and vegetative propagation."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"What is the difference between node and internode?","reveal_answer":"Nodes are stem regions where leaves are born; internodes are portions between two nodes.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb,
    4,
    21,
    6,
    true
  ),
  (
    'neet-biology-morphology-of-flowering-plants-stem-modifications',
    'neet-biology-morphology-of-flowering-plants',
    'Stem Modifications',
    'comparison',
    'Modified stems perform storage, climbing, protection, photosynthesis and vegetative propagation.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Modification","Recall cue","Source examples"],"rows":[["Underground stems","Food storage and perennation.","Potato, ginger, turmeric, zaminkand, Colocasia"],["Stem tendrils","Slender, spirally coiled axillary-bud structures for climbing.","Gourds (cucumber, pumpkins, watermelon) & grapevines"],["Thorns","Woody, straight, pointed structures from axillary buds for protection.","Citrus, Bougainvillea"],["Phylloclade","Green, flattened or fleshy cylindrical stem with chlorophyll for photosynthesis in arid regions.","Opuntia (flattened stem), Euphorbia (cylindrical stem)"],["Stolon","Slender lateral branch from base; grows aerially then arches down to touch ground.","Mint & jasmine"],["Offset","Lateral branch with short internodes; node bears rosette of leaves and tuft of roots.","Pistia and Eichhornia"],["Sucker","Lateral branches from basal underground part, grow horizontally below soil and come out obliquely upward.","Banana, Pineapple & Chrysanthemum"]]}'::jsonb,
    null,
    null,
    '{"recall_question":"Which stem modifications are source examples of vegetative spread?","reveal_answer":"Stolon, offset and sucker.","key_points":["Underground stems of grass, strawberry etc. spread to new niches."],"examples":["Mint & jasmine","Pistia and Eichhornia","Banana, Pineapple & Chrysanthemum"],"neet_traps":[]}'::jsonb,
    5,
    21,
    7,
    true
  ),
  (
    'neet-biology-morphology-of-flowering-plants-leaf-parts',
    'neet-biology-morphology-of-flowering-plants',
    'Parts of a Leaf',
    'diagram',
    'A typical leaf has leaf base, petiole and lamina.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Part","Recall answer"],"rows":[["Leaf base","Attaches leaf to stem; may bear stipules; in monocots expands into a sheath; in some leguminous plants becomes pulvinus."],["Petiole","Helps hold leaf blade to light; flexible petioles allow fluttering in wind."],["Lamina","Green expanded part with veins and veinlets; prominent middle vein is midrib."]]}'::jsonb,
    '{"type":"bio-leaf-parts"}'::jsonb,
    null,
    '{"recall_question":"Name the three main parts of a typical leaf.","reveal_answer":"Leaf base, petiole and lamina.","key_points":["Lamina is also called leaf blade."],"examples":[],"neet_traps":["Pulvinus is a swollen leaf base in some leguminous plants."]}'::jsonb,
    5,
    22,
    8,
    true
  ),
  (
    'neet-biology-morphology-of-flowering-plants-venation-comparison',
    'neet-biology-morphology-of-flowering-plants',
    'Reticulate vs Parallel Venation',
    'comparison',
    'Venation is arrangement of veins and veinlets in leaf lamina.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Venation","Recall answer","Seen in"],"rows":[["Reticulate","Veinlets form a network.","Dicotyledons"],["Parallel","Veins run parallel to each other within a lamina.","Monocotyledons"]]}'::jsonb,
    '{"type":"bio-venation"}'::jsonb,
    null,
    '{"recall_question":"Which venation is typical of dicots and which of monocots?","reveal_answer":"Reticulate in dicotyledons; parallel in monocotyledons.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb,
    5,
    22,
    9,
    true
  ),
  (
    'neet-biology-morphology-of-flowering-plants-simple-compound-leaves',
    'neet-biology-morphology-of-flowering-plants',
    'Simple vs Compound Leaf',
    'comparison',
    'The difference depends on whether lamina incisions reach the midrib and form leaflets.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Leaf type","Recall answer","Bud trap"],"rows":[["Simple leaf","Lamina is entire or incisions do not touch midrib.","Bud is seen in axil of petiole."],["Compound leaf","Incisions reach midrib, breaking lamina into several leaflets.","Bud is seen in axil of petiole, not in axil of leaflets."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"What is the key difference between simple and compound leaves?","reveal_answer":"In compound leaves, incisions reach the midrib and form leaflets; in simple leaves they do not.","key_points":[],"examples":[],"neet_traps":["A bud is not seen in the axil of leaflets of a compound leaf."]}'::jsonb,
    5,
    22,
    10,
    true
  ),
  (
    'neet-biology-morphology-of-flowering-plants-pinnate-palmate-compound',
    'neet-biology-morphology-of-flowering-plants',
    'Pinnately vs Palmately Compound Leaf',
    'comparison',
    'Compound leaves are grouped by how leaflets attach.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Type","Recall answer","Source example"],"rows":[["Pinnately compound","Many leaflets are present on a common axis, the rachis, which represents the midrib.","Neem"],["Palmately compound","Leaflets are attached at a common point at the tip of petiole.","Silk cotton"]]}'::jsonb,
    null,
    null,
    '{"recall_question":"Which compound leaf has leaflets on a rachis?","reveal_answer":"Pinnately compound leaf.","key_points":["Palmately compound leaf has leaflets at a common point."],"examples":["Neem","Silk cotton"],"neet_traps":[]}'::jsonb,
    4,
    22,
    11,
    true
  ),
  (
    'neet-biology-morphology-of-flowering-plants-phyllotaxy',
    'neet-biology-morphology-of-flowering-plants',
    'Phyllotaxy Types',
    'diagram',
    'Phyllotaxy is the pattern of arrangement of leaves on the stem or branch.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Type","Recall answer","Source examples"],"rows":[["Alternate","A single leaf arises at each node in alternate manner.","China rose, mustard & sun flower"],["Opposite","A pair of leaves arise at each node and lie opposite to each other.","Calotropis and guava"],["Whorled","More than two leaves arise at a node and form a whorl.","Alstonia"]]}'::jsonb,
    '{"type":"bio-phyllotaxy"}'::jsonb,
    null,
    '{"recall_question":"What are the three types of phyllotaxy?","reveal_answer":"Alternate, opposite and whorled.","key_points":[],"examples":["China rose, mustard & sun flower","Calotropis and guava","Alstonia"],"neet_traps":[]}'::jsonb,
    5,
    22,
    12,
    true
  ),
  (
    'neet-biology-morphology-of-flowering-plants-leaf-modifications',
    'neet-biology-morphology-of-flowering-plants',
    'Leaf Modifications',
    'examples',
    'Leaves can be modified for climbing, defence, storage, food synthesis or insectivory.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Modification","Recall cue","Source examples"],"rows":[["Tendrils","For climbing.","Peas"],["Spines","For defense.","Cacti"],["Fleshy leaves","To store food.","Onion and garlic"],["Expanded green petioles","Leaves are small and short-lived; petioles synthesise food.","Australian acacia"],["Insectivorous leaves","Modified leaves.","Pitcher plant, Venus-fly trap"]]}'::jsonb,
    null,
    null,
    '{"recall_question":"In Australian acacia, which part expands and synthesises food?","reveal_answer":"The petiole.","key_points":["Leaves are small and short-lived."],"examples":["Australian acacia"],"neet_traps":[]}'::jsonb,
    4,
    22,
    13,
    true
  ),
  (
    'neet-biology-morphology-of-flowering-plants-flower-inflorescence',
    'neet-biology-morphology-of-flowering-plants',
    'Flower and Inflorescence',
    'concept',
    'A flower is a modified shoot. Inflorescence is the arrangement of a cluster of flowers on the floral axis.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Term","Recall answer"],"rows":[["Flower","Modified shoot where shoot apical meristem changes to floral meristem."],["Solitary flower","When a shoot tip transforms into a flower."],["Inflorescence","Arrangement of cluster of flowers on the floral axis."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"What happens to internodes when shoot apex becomes a flower?","reveal_answer":"Internodes do not elongate and the axis gets condensed.","key_points":["The apex produces floral appendages laterally at successive nodes instead of leaves."],"examples":[],"neet_traps":[]}'::jsonb,
    4,
    22,
    14,
    true
  ),
  (
    'neet-biology-morphology-of-flowering-plants-racemose-cymose',
    'neet-biology-morphology-of-flowering-plants',
    'Racemose vs Cymose Inflorescence',
    'comparison',
    'Inflorescences differ by whether the main axis keeps growing or terminates in a flower.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Type","Main axis","Flower order"],"rows":[["Racemose","Continues to grow.","Flowers are borne laterally in acropetal succession."],["Cymose","Terminates in a flower and is limited in growth.","Flowers are borne in basipetal order."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"Racemose vs cymose: what is the growth and flower-order distinction?","reveal_answer":"Racemose has a continuously growing main axis with acropetal succession; cymose terminates in a flower with basipetal order.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb,
    5,
    22,
    15,
    true
  ),
  (
    'neet-biology-morphology-of-flowering-plants-flower-general-terms',
    'neet-biology-morphology-of-flowering-plants',
    'Basic Flower Terms',
    'classification',
    'A flower has pedicel, thalamus and four whorls; bracts and sex are useful classification cues.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Cue","Recall answer"],"rows":[["Pedicel","Stalk of flower."],["Thalamus/receptacle","Swollen end of pedicel."],["Bract","Reduced leaf found at base of pedicel."],["Bracteate / ebracteate","Flowers with bracts / without bracts."],["Whorls","Calyx, corolla, androecium and gynoecium."],["Accessory organs","Calyx and corolla."],["Reproductive organs","Androecium and gynoecium."],["Perianth","Calyx and corolla not distinct, as in lily."],["Bisexual / unisexual","Both androecium and gynoecium / either only androecium or only gynoecium."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"Which floral whorls are accessory and which are reproductive?","reveal_answer":"Accessory: calyx and corolla. Reproductive: androecium and gynoecium.","key_points":[],"examples":[],"neet_traps":["Perianth is used when calyx and corolla are not distinct."]}'::jsonb,
    5,
    23,
    16,
    true
  ),
  (
    'neet-biology-morphology-of-flowering-plants-flower-symmetry',
    'neet-biology-morphology-of-flowering-plants',
    'Flower Symmetry',
    'diagram',
    'Flowers are classified as actinomorphic, zygomorphic or asymmetric based on symmetry.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Type","Recall answer","Source examples"],"rows":[["Actinomorphic","Can be divided into two equal radial halves in any radial plane through centre.","Mustard, datura, chilli"],["Zygomorphic","Can be divided into two similar halves only in a particular vertical plane.","Pea, gulmohur, bean, Cassia"],["Asymmetric","Cannot be divided into two similar halves by any vertical plane through centre.","Canna"]]}'::jsonb,
    '{"type":"bio-flower-symmetry"}'::jsonb,
    null,
    '{"recall_question":"Which flower symmetry has only one vertical plane of division?","reveal_answer":"Zygomorphic.","key_points":[],"examples":["Pea, gulmohur, bean, Cassia"],"neet_traps":[]}'::jsonb,
    5,
    23,
    17,
    true
  ),
  (
    'neet-biology-morphology-of-flowering-plants-floral-appendage-numbers',
    'neet-biology-morphology-of-flowering-plants',
    'Trimerous, Tetramerous, Pentamerous',
    'fact',
    'Flowers are also classified by number of floral appendages.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Term","Recall answer"],"rows":[["Trimerous","Floral appendages are multiple of 3."],["Tetramerous","Floral appendages are multiple of 4."],["Pentamerous","Floral appendages are multiple of 5."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"What do trimerous, tetramerous and pentamerous mean?","reveal_answer":"Floral appendages in multiples of 3, 4 and 5 respectively.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb,
    4,
    23,
    18,
    true
  ),
  (
    'neet-biology-morphology-of-flowering-plants-ovary-position',
    'neet-biology-morphology-of-flowering-plants',
    'Hypogynous, Perigynous and Epigynous',
    'diagram',
    'These types depend on the position of calyx, corolla and androecium with respect to ovary on thalamus.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Type","Position cue","Ovary","Source examples"],"rows":[["Hypogynous","Gynoecium highest; other parts below it.","Superior","Mustard, China rose & brinjal"],["Perigynous","Gynoecium in centre; other parts on rim of thalamus at same level.","Half inferior","Plum, rose, peach"],["Epigynous","Thalamus encloses and fuses with ovary; other parts arise above ovary.","Inferior","Guava, cucumber, ray florets of sunflower"]]}'::jsonb,
    '{"type":"bio-ovary-position"}'::jsonb,
    null,
    '{"recall_question":"Which ovary type is found in epigynous flowers?","reveal_answer":"Inferior ovary.","key_points":[],"examples":["Guava, cucumber, ray florets of sunflower"],"neet_traps":["Perigynous has a half inferior ovary."]}'::jsonb,
    5,
    23,
    19,
    true
  ),
  (
    'neet-biology-morphology-of-flowering-plants-calyx-corolla-aestivation',
    'neet-biology-morphology-of-flowering-plants',
    'Calyx, Corolla and Aestivation',
    'comparison',
    'Calyx is made of sepals, corolla of petals, and aestivation is their arrangement in the floral bud.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"sections":[{"title":"Calyx and corolla","columns":["Whorl","Recall answer"],"rows":[["Calyx","Outermost whorl made of sepals; may be gamosepalous or polysepalous."],["Corolla","Whorl inner to calyx made of petals; may be gamopetalous or polypetalous."]]},{"title":"Aestivation types","columns":["Type","Recall cue","Source examples"],"rows":[["Valvate","Margins just touch without overlapping.","Calotropis"],["Twisted","One margin overlaps next one and so on.","China rose, lady''s finger & cotton"],["Imbricate","Margins overlap, but not in any particular direction.","Cassia & gulmohur"],["Vexillary","Standard overlaps wings, which overlap keel.","Pea & bean"]]}]}'::jsonb,
    '{"type":"bio-aestivation"}'::jsonb,
    null,
    '{"recall_question":"Which aestivation has standard, wings and keel?","reveal_answer":"Vexillary (papilionaceous).","key_points":["Largest standard overlaps two lateral wings; wings overlap two smallest anterior petals (keel)."],"examples":["Pea & bean"],"neet_traps":[]}'::jsonb,
    5,
    23,
    20,
    true
  ),
  (
    'neet-biology-morphology-of-flowering-plants-androecium-terms',
    'neet-biology-morphology-of-flowering-plants',
    'Androecium Terms',
    'classification',
    'Androecium is the male reproductive part composed of stamens.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Term","Recall answer","Source examples"],"rows":[["Stamen","Male reproductive organ with filament and anther.",""],["Anther","Usually bilobed; each lobe has two pollen-sacs where pollen grains are produced.",""],["Staminode","Sterile stamen.",""],["Epipetalous","Stamens attached to petals.","Brinjal"],["Epiphyllous","Stamens attached to perianth.","Lily"],["Polyandrous","Stamens are free.",""],["Monadelphous","Stamens united into one bundle.","China rose"],["Diadelphous","Stamens united into two bundles.","Pea"],["Polyadelphous","Stamens united into more than two bundles.","Citrus"]]}'::jsonb,
    null,
    null,
    '{"recall_question":"What is a staminode?","reveal_answer":"A sterile stamen.","key_points":["Epipetalous: stamens attached to petals.","Epiphyllous: stamens attached to perianth."],"examples":["Brinjal","Lily"],"neet_traps":[]}'::jsonb,
    5,
    23,
    21,
    true
  ),
  (
    'neet-biology-morphology-of-flowering-plants-gynoecium-terms',
    'neet-biology-morphology-of-flowering-plants',
    'Gynoecium and Pistil Terms',
    'classification',
    'Gynoecium is the female reproductive part made of one or more carpels.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Term","Recall answer","Source examples"],"rows":[["Stigma","Receptive surface for pollen grains, usually at tip of style.",""],["Style","Elongated tube connecting ovary to stigma.",""],["Ovary","Enlarged basal part bearing one or more ovules attached to placenta.",""],["Placenta","Flattened, cushion-like structure to which ovules attach.",""],["Apocarpous","Carpels are free.","Lotus and rose"],["Syncarpous","Carpels are fused.","Mustard and tomato"]]}'::jsonb,
    null,
    null,
    '{"recall_question":"Apocarpous vs syncarpous: what is the difference?","reveal_answer":"Apocarpous carpels are free; syncarpous carpels are fused.","key_points":[],"examples":["Lotus and rose","Mustard and tomato"],"neet_traps":[]}'::jsonb,
    5,
    24,
    22,
    true
  ),
  (
    'neet-biology-morphology-of-flowering-plants-placentation-types',
    'neet-biology-morphology-of-flowering-plants',
    'Placentation Types',
    'diagram',
    'Placentation is the arrangement of ovules on placenta within the ovary.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Type","Recall cue","Source examples"],"rows":[["Marginal","Placenta forms a ridge along ventral suture; ovules borne in two rows.","Pea"],["Axile","Placenta is axial; ovules attached in multilocular ovary.","China rose, tomato and lemon"],["Parietal","Ovules develop on inner wall or peripheral part; one-chambered ovary may become two-chambered by false septum.","Mustard and Argemone"],["Basal","Placenta develops at base of ovary with a single ovule.","Sunflower, marigold"],["Free central","Ovules borne on central axis and septa are absent.","Dianthus and Primrose"]]}'::jsonb,
    '{"type":"bio-placentation"}'::jsonb,
    null,
    '{"recall_question":"Which placentation has ovules on a central axis with septa absent?","reveal_answer":"Free central placentation.","key_points":[],"examples":["Dianthus and Primrose"],"neet_traps":["Axile is axial in a multilocular ovary; free central has septa absent."]}'::jsonb,
    5,
    24,
    23,
    true
  ),
  (
    'neet-biology-morphology-of-flowering-plants-fruit-drupe',
    'neet-biology-morphology-of-flowering-plants',
    'Fruit and Drupe',
    'fact',
    'Fruit is a ripened ovary developed after fertilisation; parthenocarpic fruit forms without fertilisation.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Term","Recall answer","Source examples"],"rows":[["Fruit","Ripened ovary developed after fertilisation; characteristic feature of flowering plants.",""],["Parthenocarpic fruit","Fruit formed without fertilisation of the ovary.",""],["Drupe","One seeded fruit from monocarpellary superior ovary.","Mango & coconut"],["Pericarp","Fruit wall, dry or fleshy; fleshy pericarp has epicarp, mesocarp and endocarp.",""],["Mango pericarp","Thin epicarp, fleshy edible mesocarp and stony hard endocarp.","Mango"],["Coconut mesocarp","Fibrous.","Coconut"]]}'::jsonb,
    null,
    null,
    '{"recall_question":"What is a drupe according to the source examples?","reveal_answer":"Mango and coconut are drupes; they are one seeded and develop from monocarpellary superior ovaries.","key_points":["Pericarp may be dry or fleshy."],"examples":[],"neet_traps":[]}'::jsonb,
    4,
    24,
    24,
    true
  ),
  (
    'neet-biology-morphology-of-flowering-plants-dicot-monocot-seed',
    'neet-biology-morphology-of-flowering-plants',
    'Dicot vs Monocot Seed',
    'diagram',
    'Seed is a mature ovule developed after fertilisation and is made of seed coat and embryo.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Feature","Dicot seed","Monocot seed"],"rows":[["Cotyledons","Two cotyledons.","One large shield-shaped cotyledon called scutellum."],["Examples","Gram & pea; bean, gram and pea are non-endospermous.","Wheat, maize; orchids are non-endospermic."],["Seed coat","Outer testa and inner tegmen; hilum and micropyle present.","In cereals such as maize, seed coat is membranous and generally fused with fruit wall."],["Food storage","Cotyledons often fleshy and full of reserve food; castor has endosperm formed due to double fertilisation.","Endosperm bulky; aleurone layer separates embryo."],["Protective sheaths","Radicle and plumule at ends of embryonal axis.","Plumule protected by coleoptile; radicle by coleorhiza."]]}'::jsonb,
    '{"type":"bio-seed-comparison"}'::jsonb,
    null,
    '{"recall_question":"Which monocot seed structure is the shield-shaped cotyledon?","reveal_answer":"Scutellum.","key_points":["Coleoptile protects plumule; coleorhiza protects radicle.","Aleurone layer is the protein layer outside the embryo in monocot seed."],"examples":["Wheat, maize","Orchids"],"neet_traps":[]}'::jsonb,
    5,
    24,
    25,
    true
  ),
  (
    'neet-biology-morphology-of-flowering-plants-floral-formula-symbols',
    'neet-biology-morphology-of-flowering-plants',
    'Floral Formula Symbols',
    'fact',
    'Semi-technical description begins with habit, vegetative characters, then floral characters, followed by floral diagram and formula.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Symbol","Meaning in source"],"rows":[["Br","Bracteates"],["K","Calyx"],["C","Corolla"],["P","Perianth"],["A","Androecium"],["G","Gynoecium"],["G","Superior ovary"],["G","Inferior ovary"],["♂","Male"],["♀","Female"],["⚥","Bisexual"],["⊕","Actinomorphic"],["%","Zygomorphic"]]}'::jsonb,
    null,
    null,
    '{"recall_question":"What do K, C, A and G denote in a floral formula?","reveal_answer":"K = calyx, C = corolla, A = androecium, G = gynoecium.","key_points":["Fusion is shown by brackets; adhesion by a line above symbols.","A floral diagram gives number, arrangement and relation of floral parts."],"examples":[],"neet_traps":[]}'::jsonb,
    5,
    25,
    26,
    true
  ),
  (
    'neet-biology-morphology-of-flowering-plants-fabaceae-family',
    'neet-biology-morphology-of-flowering-plants',
    'Fabaceae Family',
    'classification',
    'Fabaceae was earlier called Papilonoideae, a subfamily of Leguminosae.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"sections":[{"title":"Vegetative characters","columns":["Character","Source detail"],"rows":[["Habit","Trees, shrubs, herbs; root with root nodules."],["Stem","Erect or climber."],["Leaves","Alternate, pinnately compound or simple; leaf base, pulvinate; stipulate; venation reticulate."]]},{"title":"Floral characters","columns":["Character","Source detail"],"rows":[["Inflorescence","Racemose."],["Flower","Bisexual, zygomorphic."],["Calyx","Sepals five, gamosepalous; valvate/imbricate aestivation."],["Corolla","Petals five, polypetalous, papilionaceous; vexillary aestivation."],["Androecium","Ten, diadelphous, anther dithecous."],["Gynoecium","Ovary superior, mono carpellary, unilocular with many ovules, style single."],["Fruit/seed","Fruit: legume; seed: one to many, non-endospermic."],["Floral formula","%⚥K(5) C1+2+(2) A(9)+1 G1"]]},{"title":"Economic importance","columns":["Use","Source examples"],"rows":[["Pulses","Gram, arhar, sem, moong, soyabean"],["Edible oil","Soyabean, groundnut"],["Dye","Indigofera"],["Fibres","Sun hemp"],["Fodder","Sesbania, Trifolium"],["Ornamentals","Lupin, sweet pea"],["Medicine","Muliathi"]]}]}'::jsonb,
    null,
    null,
    '{"recall_question":"Which family has vexillary aestivation and diadelphous androecium?","reveal_answer":"Fabaceae.","key_points":["Flower is bisexual and zygomorphic.","Fruit is legume; seed is one to many and non-endospermic."],"examples":["Pisum sativum (pea)"],"neet_traps":[]}'::jsonb,
    5,
    25,
    27,
    true
  ),
  (
    'neet-biology-morphology-of-flowering-plants-solanaceae-family',
    'neet-biology-morphology-of-flowering-plants',
    'Solanaceae Family',
    'classification',
    'Solanaceae is the potato family, widely distributed in tropics, subtropics and temperate zones.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"sections":[{"title":"Vegetative characters","columns":["Character","Source detail"],"rows":[["Habit","Plants mostly herbs, shrubs and small trees."],["Stem","Herbaceous rarely woody, aerial; erect, cylindrical, branched, solid or hollow, hairy or glabrous, underground stem in potato (Solanum tuberosum)."],["Leaves","Alternate, simple, rarely pinnately compound, exstipulate; venation reticulate."]]},{"title":"Floral characters","columns":["Character","Source detail"],"rows":[["Inflorescence","Solitary, axillary or cymose as in Solanum."],["Flower","Bisexual, actinomorphic."],["Calyx","Sepals five, united, persistent, valvate aestivation."],["Corolla","Petals five, united; valvate aestivation."],["Androecium","Stamens five, epipetalous."],["Gynoecium","Bicarpellary obligately placed, syncarpous; ovary superior, bilocular, placenta swollen with many ovules, axile."],["Fruits/seeds","Fruits: berry or capsule. Seeds: many, endospermous."],["Floral formula","⊕⚥K(5) C(5) A(5) G(2)"]]},{"title":"Economic importance","columns":["Use","Source examples"],"rows":[["Food","Tomato, brinjal, potato"],["Spice","Chilli"],["Medicine","Belladonna, ashwagandha"],["Fumigatory","Tobacco"],["Ornamentals","Petunia"]]}]}'::jsonb,
    null,
    null,
    '{"recall_question":"Which family has epipetalous stamens and axile placentation with many ovules?","reveal_answer":"Solanaceae.","key_points":["Flower is bisexual and actinomorphic.","Fruits are berry or capsule; seeds are many and endospermous."],"examples":["Solanum nigrum (makoi)"],"neet_traps":[]}'::jsonb,
    5,
    25,
    28,
    true
  ),
  (
    'neet-biology-morphology-of-flowering-plants-liliaceae-family',
    'neet-biology-morphology-of-flowering-plants',
    'Liliaceae Family',
    'classification',
    'Liliaceae is a characteristic representative of monocotyledonous plants.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"sections":[{"title":"Vegetative characters","columns":["Character","Source detail"],"rows":[["Habit","Perennial herbs with underground bulbs/corms/rhizomes."],["Leaves","Mostly basal, alternate, linear, exstipulate with parallel venation."]]},{"title":"Floral characters","columns":["Character","Source detail"],"rows":[["Inflorescence","Solitary / cymose; often umbellate clusters."],["Flower","Bisexual; actinomorphic."],["Perianth","Tepal six (3+3), often united into tube; valvate aestivation."],["Androecium","Stamen six, (3+3)."],["Gynoecium","Tricarpellary, syncarpous, ovary superior, trilocular with many ovules; axile placentation."],["Fruit/seed","Fruit: capsule, rarely berry. Seed: endospermous."],["Floral formula","⊕⚥P(3+3) A3+3 G(3)"]]},{"title":"Economic importance","columns":["Use","Source examples"],"rows":[["Ornamentals","Tulip, Gloriosa"],["Medicine","Aloe"],["Vegetables","Asparagus"],["Colchicines","Colchicum autumnale"]]}]}'::jsonb,
    null,
    null,
    '{"recall_question":"Which family has six tepals arranged 3+3 and parallel venation?","reveal_answer":"Liliaceae.","key_points":["Perianth often united into tube with valvate aestivation.","Gynoecium is tricarpellary, syncarpous, superior and trilocular."],"examples":["Allium cepa (onion)"],"neet_traps":[]}'::jsonb,
    5,
    26,
    29,
    true
  ),
  (
    'neet-biology-morphology-of-flowering-plants-family-comparison',
    'neet-biology-morphology-of-flowering-plants',
    'Fabaceae vs Solanaceae vs Liliaceae',
    'comparison',
    'Family recall is fastest when habit, symmetry, perianth/corolla, androecium, gynoecium and examples are compared.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Feature","Fabaceae","Solanaceae","Liliaceae"],"rows":[["Representative identity","Earlier called Papilonoideae; subfamily of Leguminosae.","Potato family.","Representative of monocotyledonous plants."],["Flower","Bisexual, zygomorphic.","Bisexual, actinomorphic.","Bisexual; actinomorphic."],["Corolla/perianth","Papilionaceous, vexillary.","Corolla united, valvate.","Perianth tepal six (3+3), often united into tube."],["Androecium","Ten, diadelphous.","Stamens five, epipetalous.","Stamen six, (3+3)."],["Ovary/placentation","Superior, mono carpellary, unilocular.","Superior, bilocular, axile.","Superior, trilocular, axile."],["Source plant shown","Pisum sativum (pea)","Solanum nigrum (makoi)","Allium cepa (onion)"]]}'::jsonb,
    null,
    null,
    '{"recall_question":"How do the three source families separate in one line?","reveal_answer":"Fabaceae is zygomorphic with papilionaceous/vexillary corolla; Solanaceae is actinomorphic with epipetalous stamens; Liliaceae is monocot with tepals 3+3.","key_points":[],"examples":["Pisum sativum (pea)","Solanum nigrum (makoi)","Allium cepa (onion)"],"neet_traps":[]}'::jsonb,
    5,
    26,
    30,
    true
  ),
  (
    'neet-biology-anatomy-of-flowering-plants-anatomy-tissues',
    'neet-biology-anatomy-of-flowering-plants',
    'Anatomy and Tissue',
    'concept',
    'Anatomy is the study of internal structure. A tissue is a group of cells having common origin and function.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    null,
    null,
    null,
    '{"recall_question":"How are plant tissues grouped by capability of cell division?","reveal_answer":"Meristematic and permanent.","key_points":["Meristematic tissues divide actively; permanent tissues lose ability to divide."],"examples":[],"neet_traps":[]}'::jsonb,
    4,
    27,
    1,
    true
  ),
  (
    'neet-biology-anatomy-of-flowering-plants-meristem-types',
    'neet-biology-anatomy-of-flowering-plants',
    'Meristematic Tissues',
    'classification',
    'Meristems are grouped by position into apical, intercalary and lateral meristems.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Meristem","Position/function","Source notes/examples"],"rows":[["Apical","Tips of roots and shoots; produce primary tissues.","Root apical meristem, shoot apical meristem; axillary bud can form branch or flower."],["Intercalary","Occur between mature tissues.","Occur in grasses and regenerate parts removed by grazing herbivores."],["Secondary/lateral","Occur in mature regions of roots and shoots; cylindrical meristems.","Seen in gymnosperms and dicots; fascicular vascular cambium, interfascicular cambium & cork cambium."]]}'::jsonb,
    '{"type":"bio-meristem-positions"}'::jsonb,
    null,
    '{"recall_question":"Which meristems are primary and which produce secondary tissues?","reveal_answer":"Apical and intercalary are primary; secondary/lateral meristems produce secondary tissues.","key_points":["Lateral meristems are seen in gymnosperms and dicots."],"examples":[],"neet_traps":[]}'::jsonb,
    5,
    27,
    2,
    true
  ),
  (
    'neet-biology-anatomy-of-flowering-plants-permanent-tissues',
    'neet-biology-anatomy-of-flowering-plants',
    'Permanent Tissues',
    'classification',
    'Cells produced by primary and secondary meristems become specialized and lose ability to divide.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Type","Recall answer"],"rows":[["Simple permanent tissues","All cells similar in structure and function."],["Complex permanent tissues","Made of more than one type of cells that work together as a unit."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"What are the two types of permanent tissues?","reveal_answer":"Simple and complex.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb,
    4,
    27,
    3,
    true
  ),
  (
    'neet-biology-anatomy-of-flowering-plants-simple-permanent-comparison',
    'neet-biology-anatomy-of-flowering-plants',
    'Parenchyma, Collenchyma and Sclerenchyma',
    'comparison',
    'Simple permanent tissues are parenchyma, collenchyma and sclerenchyma.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Tissue","Cell/wall features","Functions / examples"],"rows":[["Parenchyma","Cells generally isodiametric; thin cellulose walls; closely packed or small intercellular spaces.","Photosynthesis, storage, secretion etc."],["Collenchyma","Below epidermis in dicot plants; cells with thickened corners due to cellulose, hemicellulose and pectin; no intercellular spaces.","Mechanical support to young stem and petiole; chloroplast-containing cells assimilate food."],["Sclerenchyma","Long, narrow cells with thick lignified walls and pits; usually dead without protoplasts.","Mechanical support; fibres and sclereids."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"Which simple permanent tissue is usually dead and lignified?","reveal_answer":"Sclerenchyma.","key_points":["It has thick and lignified cell walls and usually no protoplasts.","It includes fibres and sclereids."],"examples":[],"neet_traps":[]}'::jsonb,
    5,
    27,
    4,
    true
  ),
  (
    'neet-biology-anatomy-of-flowering-plants-fibres-sclereids',
    'neet-biology-anatomy-of-flowering-plants',
    'Fibres vs Sclereids',
    'comparison',
    'Sclerenchyma is divided by form, structure, origin and development.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Type","Recall answer","Source examples"],"rows":[["Fibres","Thick-walled, elongated and pointed cells, generally occurring in groups.",""],["Sclereids","Spherical, oval or cylindrical, highly thickened dead cells with very narrow lumen.","Fruit walls of nuts; pulp of guava, pear and sapota; seed coats of legumes and leaves of tea"]]}'::jsonb,
    null,
    null,
    '{"recall_question":"Where does the source place sclereids?","reveal_answer":"Fruit walls of nuts; pulp of guava, pear and sapota; seed coats of legumes and leaves of tea.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb,
    4,
    27,
    5,
    true
  ),
  (
    'neet-biology-anatomy-of-flowering-plants-xylem-elements',
    'neet-biology-anatomy-of-flowering-plants',
    'Xylem Elements',
    'comparison',
    'Xylem conducts water and minerals and provides mechanical strength.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Element","Recall answer"],"rows":[["Tracheids","Elongated tube-like dead cells with thick lignified walls and tapering ends; protoplasm absent."],["Vessels","Long cylindrical tube-like structures made of vessel members with lignified walls and large central cavity; characteristic of angiosperms; gymnosperms lack vessels."],["Xylem fibres","Highly thickened walls and obliterated central lumens; septate or aseptate."],["Xylem parenchyma","Living, thin-walled cells with cellulosic walls; store starch/fat and tannins; ray parenchyma conducts water radially."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"Which xylem element is characteristic of angiosperms and absent in gymnosperms?","reveal_answer":"Vessels.","key_points":["Tracheids and vessels are main water transporting elements in flowering plants."],"examples":[],"neet_traps":[]}'::jsonb,
    5,
    28,
    6,
    true
  ),
  (
    'neet-biology-anatomy-of-flowering-plants-protoxylem-metaxylem-endarch-exarch',
    'neet-biology-anatomy-of-flowering-plants',
    'Protoxylem, Metaxylem, Endarch and Exarch',
    'comparison',
    'Primary xylem is protoxylem and metaxylem; their position gives endarch or exarch arrangement.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Term","Recall answer"],"rows":[["Protoxylem","First formed primary xylem."],["Metaxylem","Later formed primary xylem."],["Endarch","In stems, protoxylem lies towards centre (pith), metaxylem towards periphery."],["Exarch","In roots, protoxylem lies towards periphery, metaxylem towards centre."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"Endarch vs exarch: where is protoxylem?","reveal_answer":"Endarch: protoxylem towards centre; exarch: protoxylem towards periphery.","key_points":[],"examples":[],"neet_traps":["Stems are endarch; roots are exarch."]}'::jsonb,
    5,
    28,
    7,
    true
  ),
  (
    'neet-biology-anatomy-of-flowering-plants-phloem-elements',
    'neet-biology-anatomy-of-flowering-plants',
    'Phloem Elements',
    'comparison',
    'In angiosperms, phloem has sieve tube elements, companion cells, phloem parenchyma and phloem fibres.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Element","Recall answer"],"rows":[["Sieve tube elements","Long tube-like structures arranged longitudinally; associated with companion cells; end walls form sieve plates; mature element lacks nucleus."],["Companion cells","Specialized parenchymatous cells closely associated with sieve tube elements; maintain pressure gradient in sieve tubes."],["Phloem parenchyma","Elongated tapering cylindrical cells with dense cytoplasm and nucleus; stores food and substances like resins, latex and mucilage; absent in most monocots."],["Phloem fibres","Sclerenchymatous bast fibres; generally absent in primary phloem but found in secondary phloem; dead at maturity; jute, flax and hemp used commercially."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"Which phloem elements are absent in gymnosperms?","reveal_answer":"Sieve tubes and companion cells.","key_points":["Gymnosperms have albuminous cells and sieve cells."],"examples":[],"neet_traps":["Phloem parenchyma is absent in most monocots."]}'::jsonb,
    5,
    28,
    8,
    true
  ),
  (
    'neet-biology-anatomy-of-flowering-plants-xylem-vs-phloem',
    'neet-biology-anatomy-of-flowering-plants',
    'Xylem vs Phloem',
    'comparison',
    'Xylem and phloem are complex permanent tissues that work as conducting tissues.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Feature","Xylem","Phloem"],"rows":[["Main transport","Water and minerals from roots to stem and leaves.","Food materials from leaves to other parts."],["Strength/support","Also provides mechanical strength.","Phloem fibres provide mechanical support and protection to soft tissues."],["Angiosperm elements","Tracheids, vessels, xylem fibres, xylem parenchyma.","Sieve tube elements, companion cells, phloem parenchyma, phloem fibres."],["Gymnosperm note","Gymnosperms lack vessels.","Gymnosperms lack sieve tubes and companion cells."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"What do xylem and phloem transport?","reveal_answer":"Xylem transports water and minerals; phloem transports food materials.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb,
    5,
    28,
    9,
    true
  ),
  (
    'neet-biology-anatomy-of-flowering-plants-tissue-systems',
    'neet-biology-anatomy-of-flowering-plants',
    'Tissue Systems',
    'classification',
    'Based on structure and location, tissue systems are epidermal, ground and vascular.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Tissue system","Recall answer"],"rows":[["Epidermal","Outer-most covering; comprises epidermal cells, stomata and epidermal appendages."],["Ground","All tissues except epidermis and vascular bundles; simple tissues in cortex, pericycle, pith and medullary rays; mesophyll in leaves."],["Vascular","Complex tissues xylem and phloem."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"Which tissues constitute ground tissue?","reveal_answer":"All tissues except epidermis and vascular bundles.","key_points":["In leaves, ground tissue is chloroplast-containing mesophyll."],"examples":[],"neet_traps":[]}'::jsonb,
    4,
    29,
    10,
    true
  ),
  (
    'neet-biology-anatomy-of-flowering-plants-epidermis-stomata-appendages',
    'neet-biology-anatomy-of-flowering-plants',
    'Epidermis, Stomata and Appendages',
    'classification',
    'Epidermal tissue system covers the plant body and includes epidermis, stomata, root hairs and trichomes.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Structure","Recall answer"],"rows":[["Epidermis","Outermost layer of primary plant body; usually single-layered; compact parenchymatous cells; cuticle prevents water loss and is absent in roots."],["Stomata","Present in epidermis of leaves; regulate transpiration and gaseous exchange."],["Guard cells","Bean-shaped, dumbbell-shaped in grasses; possess chloroplasts and regulate opening/closing."],["Subsidiary cells","Specialized epidermal cells near guard cells."],["Stomatal apparatus","Stomatal aperture, guard cells and surrounding subsidiary cells together."],["Root hairs","Unicellular epidermal elongations that absorb water and minerals."],["Trichomes","Stem epidermal hairs, usually multicellular; may be branched/unbranched, soft/stiff, secretory; reduce water loss."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"What makes up the stomatal apparatus?","reveal_answer":"Stomatal aperture, guard cells and surrounding subsidiary cells.","key_points":[],"examples":[],"neet_traps":["Guard cells are dumbbell shaped in grasses."]}'::jsonb,
    5,
    29,
    11,
    true
  ),
  (
    'neet-biology-anatomy-of-flowering-plants-vascular-bundles',
    'neet-biology-anatomy-of-flowering-plants',
    'Vascular Bundle Types',
    'diagram',
    'Xylem and phloem together constitute vascular bundles.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Basis","Type","Recall answer","Seen in / example"],"rows":[["Cambium","Open","Cambium present between phloem and xylem; forms secondary xylem and phloem.","Dicotyledonous stems"],["Cambium","Closed","Cambium absent; secondary tissues not formed.","Monocotyledons"],["Arrangement","Radial","Xylem and phloem arranged alternately on different radii.","Roots"],["Arrangement","Conjoint","Xylem and phloem jointly situated at same radius; phloem usually outer to xylem.","Stems and leaves"]]}'::jsonb,
    '{"type":"bio-vascular-bundles"}'::jsonb,
    null,
    '{"recall_question":"Open vs closed vascular bundle: what is the decisive feature?","reveal_answer":"Presence or absence of cambium.","key_points":["Open bundles can form secondary xylem and phloem.","Closed bundles do not form secondary tissues."],"examples":[],"neet_traps":[]}'::jsonb,
    5,
    29,
    12,
    true
  ),
  (
    'neet-biology-anatomy-of-flowering-plants-dicot-monocot-root',
    'neet-biology-anatomy-of-flowering-plants',
    'Dicot Root vs Monocot Root',
    'comparison',
    'Root T.S. comparison focuses on stele, xylem patches, pith and secondary growth.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Feature","Dicot root","Monocot root"],"rows":[["Tissue organization","Epiblema, cortex, endodermis and stele.","Epidermis, cortex, endodermis, pericycle, vascular bundles and pith."],["Root hairs","Many epiblema cells protrude as unicellular root hairs.","Shown with epidermis/root hair."],["Xylem bundles","2-4 xylem and phloem patches.","Usually more than six (polyarch) xylem bundles."],["Pith","Small or inconspicuous.","Large and well developed."],["Secondary growth","Cambium ring later develops between xylem and phloem.","Does not undergo secondary growth."]]}'::jsonb,
    '{"type":"bio-dicot-monocot-root"}'::jsonb,
    null,
    '{"recall_question":"Which root is polyarch in the source?","reveal_answer":"Monocot root.","key_points":["Monocot root has usually more than six xylem bundles.","Pith is large and well developed."],"examples":[],"neet_traps":["Lateral roots and vascular cambium initiation occur in pericycle of dicot root."]}'::jsonb,
    5,
    29,
    13,
    true
  ),
  (
    'neet-biology-anatomy-of-flowering-plants-dicot-root-stele-trap',
    'neet-biology-anatomy-of-flowering-plants',
    'Dicot Root Stele and Pericycle',
    'neet_trap',
    'In dicot root, all tissues inner to endodermis constitute stele.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Stele part","Source detail"],"rows":[["Pericycle","A few layers of thick-walled parenchymatous cells next to endodermis; initiation of lateral roots and vascular cambium during secondary growth occurs here."],["Pith","Innermost region; small or inconspicuous."],["Conjunctive tissue","Parenchymatous cells between xylem and phloem."],["Vascular bundles","2-4 xylem and phloem patches; cambium ring later develops."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"From which tissue do lateral roots initiate in dicot root according to the source?","reveal_answer":"Pericycle.","key_points":["Vascular cambium during secondary growth also initiates in pericycle cells."],"examples":[],"neet_traps":["Lateral roots arise from pericycle."]}'::jsonb,
    5,
    29,
    14,
    true
  ),
  (
    'neet-biology-anatomy-of-flowering-plants-dicot-monocot-stem',
    'neet-biology-anatomy-of-flowering-plants',
    'Dicot Stem vs Monocot Stem',
    'comparison',
    'Stem anatomy differs in bundle arrangement, bundle type, hypodermis and ground tissue.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Feature","Dicot stem","Monocot stem"],"rows":[["Hypodermis","Few layers of collenchymatous cells below epidermis.","Sclerenchymatous hypodermis."],["Vascular bundles","Large in number, arranged in a ring; characteristic of dicot stem.","Many scattered vascular bundles."],["Bundle type","Each bundle is conjoint, open, with endarch protoxylem.","Bundles are conjoint and closed."],["Ground tissue","Cortex, pericycle, medullary rays and pith distinct.","Large, conspicuous parenchymatous ground tissue."],["Extra note","Endodermis has starch grains, called starch sheath.","Phloem parenchyma absent; water-containing cavities in vascular bundles."]]}'::jsonb,
    '{"type":"bio-dicot-monocot-stem"}'::jsonb,
    null,
    '{"recall_question":"What is the vascular bundle type of dicot stem?","reveal_answer":"Conjoint, open and with endarch protoxylem.","key_points":[],"examples":[],"neet_traps":["Monocot stem bundles are conjoint and closed."]}'::jsonb,
    5,
    30,
    15,
    true
  ),
  (
    'neet-biology-anatomy-of-flowering-plants-dicot-monocot-leaf',
    'neet-biology-anatomy-of-flowering-plants',
    'Dicot Leaf vs Monocot Leaf',
    'comparison',
    'Dicot leaf is dorsiventral; monocot leaf is isobilateral.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Feature","Dicot dorsiventral leaf","Monocot isobilateral leaf"],"rows":[["Main parts","Epidermis, mesophyll and vascular system.","Similar in many ways but shows listed differences."],["Stomata","Abaxial epidermis generally bears more stomata than adaxial epidermis; adaxial may lack stomata.","Stomata present on both epidermal surfaces."],["Mesophyll","Differentiated into palisade and spongy parenchyma.","Not differentiated into palisade and spongy parenchyma."],["Special cells","Bundle sheath surrounds vascular bundles.","Bulliform cells in grasses along veins on adaxial epidermis."],["Venation reflection","Reticulate venation varies vein thickness.","Parallel venation reflected in nearly similar vascular bundle sizes except main veins."]]}'::jsonb,
    '{"type":"bio-leaf-anatomy"}'::jsonb,
    null,
    '{"recall_question":"Where are bulliform cells found according to the source?","reveal_answer":"In grasses, certain adaxial epidermal cells along the veins become bulliform cells.","key_points":["Turgid bulliform cells expose leaf surface; flaccid cells make leaves curl inward to minimize water loss."],"examples":[],"neet_traps":["Abaxial epidermis generally has more stomata in dorsiventral dicot leaf."]}'::jsonb,
    5,
    30,
    16,
    true
  ),
  (
    'neet-biology-anatomy-of-flowering-plants-secondary-growth-basics',
    'neet-biology-anatomy-of-flowering-plants',
    'Secondary Growth Basics',
    'process',
    'Primary growth increases length; secondary growth increases girth of dicot plants.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Term","Recall answer"],"rows":[["Primary growth","Growth of roots and stems in length with apical meristem."],["Secondary growth","Increase in girth of dicot plants."],["Lateral meristems involved","Vascular cambium and cork cambium."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"Which meristems are involved in secondary growth?","reveal_answer":"Vascular cambium and cork cambium.","key_points":["Secondary growth is increase in girth of dicot plants."],"examples":[],"neet_traps":["Secondary growth does not occur in monocotyledons as stated in source."]}'::jsonb,
    5,
    30,
    17,
    true
  ),
  (
    'neet-biology-anatomy-of-flowering-plants-cambial-ring',
    'neet-biology-anatomy-of-flowering-plants',
    'Formation of Cambial Ring',
    'sequence',
    'In young dicot stem, vascular cambium begins in patches and later forms a complete ring.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Step","Recall answer"],"rows":[["1","Cambium present between primary xylem and primary phloem is intrafascicular cambium."],["2","Medullary cells adjoining intrafascicular cambium become meristematic."],["3","They form interfascicular cambium."],["4","A continuous cambium ring is formed."]]}'::jsonb,
    '{"type":"bio-secondary-growth"}'::jsonb,
    null,
    '{"recall_question":"What is the difference between intra- and interfascicular cambium?","reveal_answer":"Intrafascicular cambium is between primary xylem and phloem; interfascicular cambium forms from adjoining medullary cells.","key_points":["Together they form a continuous cambial ring."],"examples":[],"neet_traps":[]}'::jsonb,
    5,
    30,
    18,
    true
  ),
  (
    'neet-biology-anatomy-of-flowering-plants-cambial-ring-activity',
    'neet-biology-anatomy-of-flowering-plants',
    'Activity of Cambial Ring',
    'process',
    'Cambial ring cuts off cells inward and outward, producing secondary vascular tissues.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Direction","Product / effect"],"rows":[["Towards pith","Cells mature into secondary xylem."],["Towards periphery","Cells mature into secondary phloem."],["Inner side activity","More active; more secondary xylem than secondary phloem is produced."],["Phloem fate","Primary and secondary phloems gradually get crushed due to accumulation of secondary xylem."],["Medullary rays","Narrow parenchyma bands through secondary xylem and phloem in radial directions."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"Does cambium produce more secondary xylem or secondary phloem?","reveal_answer":"More secondary xylem.","key_points":["Cambium is more active on the inner side than on the outer side."],"examples":[],"neet_traps":[]}'::jsonb,
    5,
    31,
    19,
    true
  ),
  (
    'neet-biology-anatomy-of-flowering-plants-spring-autumn-wood',
    'neet-biology-anatomy-of-flowering-plants',
    'Spring Wood vs Autumn Wood',
    'comparison',
    'Seasonal cambial activity produces alternate rings of spring wood and autumn wood.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Feature","Spring wood / early wood","Autumn wood / late wood"],"rows":[["Seasonal cambium activity","Spring: cambium very active.","Winter: cambium less active."],["Xylary elements","Many, vessels with wider cavities.","Fewer, vessels narrow."],["Colour/density","Lighter in colour and lower density.","Darker and higher density."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"Which wood is lighter and lower density?","reveal_answer":"Spring wood (early wood).","key_points":["Autumn wood is darker and higher density.","Alternate concentric rings form annual rings."],"examples":[],"neet_traps":["Annual rings are used to estimate age of tree: dendrochronology."]}'::jsonb,
    5,
    31,
    20,
    true
  ),
  (
    'neet-biology-anatomy-of-flowering-plants-heartwood-sapwood',
    'neet-biology-anatomy-of-flowering-plants',
    'Heartwood vs Sapwood',
    'comparison',
    'Secondary xylem of old trees differentiates into central heartwood and peripheral sapwood.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Feature","Heartwood","Sapwood"],"rows":[["Position","Central part of secondary xylem.","Peripheral region of secondary xylem."],["State/colour","Hard, dead, dark brown, highly lignified, non-functional.","Living and lighter in colour."],["Deposits","Tannins, resins, oils, gums, aromatic substances, essential oils etc.",""],["Function","Mechanical support to stem.","Conduction of water and minerals from root to leaf."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"Which part conducts water: heartwood or sapwood?","reveal_answer":"Sapwood.","key_points":["Heartwood is hard, dead, dark brown and non-functional.","Sapwood is living and lighter in colour."],"examples":[],"neet_traps":[]}'::jsonb,
    5,
    31,
    21,
    true
  ),
  (
    'neet-biology-anatomy-of-flowering-plants-cork-cambium-periderm-bark',
    'neet-biology-anatomy-of-flowering-plants',
    'Cork Cambium, Periderm and Bark',
    'classification',
    'Cork cambium replaces broken outer protective layers during secondary growth.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Term","Recall answer"],"rows":[["Phellogen / cork cambium","Meristematic tissue usually developing in cortex; couple of layers thick, narrow, thin-walled, nearly rectangular cells."],["Phellem / cork","Outer cells cut off by phellogen; impervious to water due to suberin deposition."],["Phelloderm / secondary cortex","Inner cells cut off by phellogen; parenchymatous."],["Periderm","Phellogen, phellem and phelloderm collectively."],["Bark","Non-technical term for all tissues exterior to vascular cambium, such as periderm and secondary phloem."],["Early/soft bark","Formed early in season."],["Late/hard bark","Formed towards end of season."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"What three tissues collectively form periderm?","reveal_answer":"Phellogen, phellem and phelloderm.","key_points":["Phellem is cork; phelloderm is secondary cortex."],"examples":[],"neet_traps":["Bark is a non-technical term."]}'::jsonb,
    5,
    31,
    22,
    true
  ),
  (
    'neet-biology-anatomy-of-flowering-plants-lenticels',
    'neet-biology-anatomy-of-flowering-plants',
    'Lenticels',
    'fact',
    'At certain regions, phellogen cuts off closely arranged parenchymatous cells on the outer side; these rupture epidermis and form lenticels.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    null,
    null,
    null,
    '{"recall_question":"What is the function of lenticels?","reveal_answer":"They permit gas exchange between the outer atmosphere and internal tissue of the stem.","key_points":["Lenticels are lens-shaped openings and occur in most woody trees."],"examples":[],"neet_traps":[]}'::jsonb,
    4,
    31,
    23,
    true
  ),
  (
    'neet-biology-anatomy-of-flowering-plants-secondary-growth-roots',
    'neet-biology-anatomy-of-flowering-plants',
    'Secondary Growth in Roots',
    'process',
    'In dicot root, vascular cambium is completely secondary in origin.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '{"columns":["Stage","Recall answer"],"rows":[["Origin","From tissue just below phloem bundles, a portion of pericycle above protoxylem."],["Shape","Forms complete and continuous wavy ring."],["Later","Becomes circular."],["Further events","Similar to dicotyledon stem."],["Occurrence","Also occurs in stems and roots of gymnosperms; does not occur in monocotyledons."]]}'::jsonb,
    null,
    null,
    '{"recall_question":"In dicot root, what is the origin of vascular cambium?","reveal_answer":"Completely secondary in origin, from tissue below phloem bundles: a portion of pericycle above protoxylem.","key_points":[],"examples":[],"neet_traps":["Secondary growth does not occur in monocotyledons."]}'::jsonb,
    5,
    31,
    24,
    true
  )
on conflict (id) do update set
  title = excluded.title,
  card_type = excluded.card_type,
  body = excluded.body,
  formulas = excluded.formulas,
  variables = excluded.variables,
  conditions = excluded.conditions,
  table_data = excluded.table_data,
  diagram_data = excluded.diagram_data,
  diagram_svg = excluded.diagram_svg,
  recall_data = excluded.recall_data,
  importance = excluded.importance,
  source_page = excluded.source_page,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active;
