-- Biology Revision Cards Batch 10: Biotechnology
-- Source: NEET Biology Short Notes PDF, printed pages 128-134 only.

alter table public.formula_cards add column if not exists recall_data jsonb;

insert into public.formula_subjects (id, name, slug, exam, sort_order)
values ('neet-biology', 'Biology', 'biology', 'NEET', 3)
on conflict (id) do update set
  name = excluded.name,
  slug = excluded.slug,
  exam = excluded.exam,
  sort_order = excluded.sort_order;

insert into public.formula_chapters (id, subject_id, title, slug, sort_order)
values
  ('neet-biology-biotechnology-principles-and-process', 'neet-biology', 'Biotechnology: Principles and Process', 'biotechnology-principles-and-process', 31),
  ('neet-biology-biotechnology-and-its-applications', 'neet-biology', 'Biotechnology and its Applications', 'biotechnology-and-its-applications', 32)
on conflict (id) do update set
  subject_id = excluded.subject_id,
  title = excluded.title,
  slug = excluded.slug,
  sort_order = excluded.sort_order;

insert into public.formula_cards (
  id, chapter_id, title, card_type, body, formulas, variables, conditions, table_data, diagram_data, diagram_svg, recall_data, importance, source_page, sort_order, is_active
)
values
  ('neet-biology-biotechnology-principles-and-process-biotechnology-basics', 'neet-biology-biotechnology-principles-and-process', 'Biotechnology Basics', 'concept', 'Biotechnology uses live organisms or their enzymes for products and processes useful to humans.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Cue","Source-backed recall"],"rows":[["Biotechnology","Technique of using live organisms or their enzymes for products and processes useful to humans"],["EFB definition","Integration of natural science and organisms, cells, parts thereof, and molecular analogues for products and services"],["Deals with","Microbe-mediated processes, in vitro fertilization, synthesis and using of a gene, DNA vaccine preparation and correcting a defective gene"]]}'::jsonb, null, null, '{"recall_question":"What does biotechnology use for useful products and processes?","reveal_answer":"Live organisms or their enzymes.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb, 5, 128, 1, true),
  ('neet-biology-biotechnology-principles-and-process-core-techniques', 'neet-biology-biotechnology-principles-and-process', 'Core Techniques of Modern Biotechnology', 'comparison', 'The source frames modern biotechnology around genetic engineering and bioprocess engineering.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Technique","Source-backed recall"],"rows":[["Genetic engineering","Genetic material DNA and RNA is chemically altered and introduced into host organisms to change the phenotype"],["Bioprocess engineering","Maintenance of sterile ambience in chemical engineering processes for growing desired microbe/eukaryotic cell to manufacture antibiotics, vaccines, enzymes etc."]]}'::jsonb, null, null, '{"recall_question":"Which biotechnology core technique maintains sterile ambience for product manufacture?","reveal_answer":"Bioprocess engineering.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb, 5, 128, 2, true),
  ('neet-biology-biotechnology-principles-and-process-genetic-modification-steps', 'neet-biology-biotechnology-principles-and-process', 'Basic Genetic Modification Steps', 'sequence', 'The source lists three basic steps in genetically modifying an organism.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Step","Source-backed event"],"rows":[["1","Identification of DNA with desirable genes"],["2","Introduction of the identified DNA into the host using a vector such as plasmid"],["3","Maintenance of introduced DNA in the host and transfer of DNA to its progeny"]]}'::jsonb, null, null, '{"recall_question":"Why does alien DNA need ori or genome integration?","reveal_answer":"Without origin of replication it cannot multiply in progeny cells.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb, 5, 128, 3, true),
  ('neet-biology-biotechnology-principles-and-process-recombinant-dna-history', 'neet-biology-biotechnology-principles-and-process', 'First Recombinant DNA', 'fact', 'Recombinant DNA technology joins and inserts foreign DNA into a host organism.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Cue","Source-backed detail"],"rows":[["Recombinant DNA technology","Process of joining and inserting a foreign piece of DNA into a host organism to produce new genetic combinations"],["First rDNA","Produced by Stanley Cohen and Herbert Boyer in 1972"],["Gene source","Antibiotic resistance gene from a plasmid of Salmonella typhimurium"],["Host","Transferred into E. coli, where the gene was expressed and multiplied"]]}'::jsonb, null, null, '{"recall_question":"Who produced the first recombinant DNA?","reveal_answer":"Stanley Cohen and Herbert Boyer.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb, 5, 128, 4, true),
  ('neet-biology-biotechnology-principles-and-process-restriction-enzymes', 'neet-biology-biotechnology-principles-and-process', 'Restriction Enzymes', 'comparison', 'Restriction enzymes are nucleases that cut DNA at specific sites.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Type/cue","Source-backed recall"],"rows":[["Restriction enzymes","Enzymes that cut DNA at specific sites into fragments"],["Exonucleases","Remove nucleotides from the ends of DNA"],["Endonucleases","Cut at specific positions within DNA"],["First restriction endonuclease","Hind II; recognizes a specific sequence of 6 base pairs"],["Scale","More than 900 restriction enzymes from over 230 strains of bacteria"]]}'::jsonb, null, null, '{"recall_question":"Which restriction enzyme type cuts within DNA?","reveal_answer":"Endonuclease.","key_points":[],"examples":[],"neet_traps":["Exonucleases remove nucleotides from DNA ends."]}'::jsonb, 5, 128, 5, true),
  ('neet-biology-biotechnology-principles-and-process-restriction-enzyme-naming', 'neet-biology-biotechnology-principles-and-process', 'Restriction Enzyme Naming', 'fact', 'Restriction enzyme names indicate the source organism and strain/order details.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Name part","Source-backed meaning"],"rows":[["First letter","Genus"],["Second two letters","Species of prokaryotic cell"],["EcoRI","Comes from E. coli RY 13"],["R","Strain"],["Roman number","Order in which enzyme was isolated from that strain"]]}'::jsonb, null, null, '{"recall_question":"In EcoRI naming, what does the Roman number indicate?","reveal_answer":"Order in which the enzyme was isolated from that strain.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb, 5, 128, 6, true),
  ('neet-biology-biotechnology-principles-and-process-ecori-palindrome', 'neet-biology-biotechnology-principles-and-process', 'EcoRI Palindromic Sequence', 'diagram', 'EcoRI recognizes a palindromic nucleotide sequence read in 5'' to 3'' direction on both strands.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Cue","Source-backed detail"],"rows":[["Palindromic sequence","Base-pair sequence read the same on the two strands in 5'' -> 3'' and 3'' -> 5'' directions"],["EcoRI sequence","5'' - GAATTC - 3'' / 3'' - CTTAAG - 5''"],["Cutting","Cuts strands a little away from centre of palindrome sites between same two bases on opposite strands"],["Sticky ends","Single stranded overhanging stretches; form H-bonds with complementary cut counterparts"]]}'::jsonb, '{"type":"bio-restriction-cut"}'::jsonb, null, '{"recall_question":"What is the EcoRI palindromic sequence shown in the source?","reveal_answer":"5'' - GAATTC - 3'' / 3'' - CTTAAG - 5''.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb, 5, 128, 7, true),
  ('neet-biology-biotechnology-principles-and-process-ligase-sticky-ends', 'neet-biology-biotechnology-principles-and-process', 'Sticky Ends and DNA Ligase', 'process', 'DNA fragments cut by the same restriction enzyme can be joined by DNA ligase.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Cue","Source-backed recall"],"rows":[["Same enzyme cut","Resultant DNA fragments have the same kind of sticky ends"],["Sticky-end role","Facilitates action of DNA ligase"],["DNA ligase","Joins DNA fragments to create recombinant DNA"]]}'::jsonb, null, null, '{"recall_question":"Which enzyme joins DNA fragments during recombinant DNA formation?","reveal_answer":"DNA ligase.","key_points":[],"examples":[],"neet_traps":["Restriction enzymes cut DNA; DNA ligase joins fragments."]}'::jsonb, 5, 129, 8, true),
  ('neet-biology-biotechnology-principles-and-process-cloning-vector-basics', 'neet-biology-biotechnology-principles-and-process', 'Cloning Vector Basics', 'concept', 'A cloning vector carries foreign DNA and replicates inside host cells.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Cue","Source-backed recall"],"rows":[["Cloning vector","DNA molecule that can carry a foreign DNA segment and replicate inside host cells"],["Examples","Plasmids and bacteriophages"],["Plasmids","Autonomously replicating circular extra-chromosomal DNA of bacteria"],["Plasmid copy number","Some plasmids have 1-2 copies per cell; others have 15-100 copies per cell"],["Bacteriophages","Have very high copy numbers of genome within bacterial cells"]]}'::jsonb, null, null, '{"recall_question":"What is a cloning vector?","reveal_answer":"DNA molecule that can carry foreign DNA and replicate inside host cells.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb, 5, 129, 9, true),
  ('neet-biology-biotechnology-principles-and-process-vector-features', 'neet-biology-biotechnology-principles-and-process', 'Vector Components', 'comparison', 'A useful cloning vector needs ori, selectable marker and cloning sites.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Feature","Source-backed function"],"rows":[["Origin of replication or ori","Sequence where replication starts; controls copy number of linked DNA"],["Selectable marker","Gene that helps select transformants and eliminate non-transformants"],["Cloning sites","Recognition sites for restriction enzymes"],["Single/few recognition sites","Needed to link alien DNA without generating several fragments"]]}'::jsonb, null, null, '{"recall_question":"What is the role of ori in a cloning vector?","reveal_answer":"It is where replication starts and it controls copy number of linked DNA.","key_points":[],"examples":[],"neet_traps":["ori is not the selectable marker."]}'::jsonb, 5, 129, 10, true),
  ('neet-biology-biotechnology-principles-and-process-pbr322', 'neet-biology-biotechnology-principles-and-process', 'pBR322 Map Recall', 'diagram', 'The source labels pBR322 with ori, rop, antibiotic resistance genes and restriction sites.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Label","Source-backed detail"],"rows":[["Restriction sites","Hind III, EcoR I, BamH I, Sal I, Pvu II, Pst I and Cla I"],["ori","Origin of replication"],["Antibiotic resistance genes","ampR and tetR"],["Rop","Codes for proteins involved in replication of plasmid"],["Example ligation","Foreign DNA ligated at Bam H I site of tetracycline resistance gene"]]}'::jsonb, '{"type":"bio-pbr322-map"}'::jsonb, null, '{"recall_question":"Which pBR322 site example inserts foreign DNA into tetracycline resistance gene?","reveal_answer":"Bam H I site.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb, 5, 129, 11, true),
  ('neet-biology-biotechnology-principles-and-process-insertional-inactivation', 'neet-biology-biotechnology-principles-and-process', 'Insertional Inactivation', 'neet_trap', 'Insertion of foreign DNA within a bacterial gene inactivates that gene.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Cell/plasmid type","Source-backed selection result"],"rows":[["Non-transformants","No plasmid; not resistant to tetracycline or ampicillin"],["Transformants with non-recombinant plasmid","Resistant to both tetracycline and ampicillin"],["Transformants with recombinant plasmid","Resistant only to ampicillin"],["Blue colony alternative","No insert gives blue coloured colonies with chromogenic substrate"],["Recombinant colonies","Do not produce colour when beta-galactosidase gene is inactivated"]]}'::jsonb, null, null, '{"recall_question":"In the pBR322 example, recombinant plasmids grow on which antibiotic medium only?","reveal_answer":"Ampicillin medium only.","key_points":[],"examples":[],"neet_traps":["Loss of tetracycline resistance marks insertional inactivation here."]}'::jsonb, 5, 129, 12, true),
  ('neet-biology-biotechnology-principles-and-process-plant-animal-vectors', 'neet-biology-biotechnology-principles-and-process', 'Vectors for Plants and Animals', 'comparison', 'Pathogen genetic tools can be transformed into useful vectors.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Vector/pathogen","Source-backed use"],"rows":[["Agrobacterium tumefaciens","Pathogen of many dicot plants that delivers T-DNA to transform normal plant cells into tumour cells"],["Ti plasmid","Modified into a non-pathogenic cloning vector that delivers genes of interest into plants"],["Retroviruses","Transform normal animal cells into cancerous cells; used to deliver desirable genes into animal cells"]]}'::jsonb, null, null, '{"recall_question":"Which modified plasmid of Agrobacterium is used as plant cloning vector?","reveal_answer":"Ti plasmid.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb, 5, 130, 13, true),
  ('neet-biology-biotechnology-principles-and-process-competent-host', 'neet-biology-biotechnology-principles-and-process', 'Competent Host and Heat Shock', 'sequence', 'Bacterial cells are made competent because DNA is hydrophilic and cannot pass through cell membranes.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Step","Source-backed event"],"rows":[["1","Treat bacterial cells with a specific concentration of divalent cation such as calcium"],["2","DNA enters bacterium through pores in cell wall"],["3","Incubate cells with recombinant DNA on ice"],["4","Place briefly at 42°C for heat shock"],["5","Put cells back on ice"],["6","Bacteria take up recombinant DNA"]]}'::jsonb, null, null, '{"recall_question":"At what temperature is heat shock shown in the source?","reveal_answer":"42°C.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb, 5, 130, 14, true),
  ('neet-biology-biotechnology-principles-and-process-dna-entry-methods', 'neet-biology-biotechnology-principles-and-process', 'DNA Entry Methods', 'comparison', 'Alien DNA can enter host cells through competence treatment or direct delivery methods.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Method","Source-backed recall"],"rows":[["Competent bacterial cells","Divalent cation treatment and heat shock help uptake recombinant DNA"],["Micro-injection","Recombinant DNA is directly injected into nucleus of an animal cell"],["Biolistics or gene gun","Cells bombarded with high velocity gold or tungsten micro-particles coated with DNA; suitable for plants"],["Disarmed pathogen vectors","Infect the cell and transfer recombinant DNA into host; example A. tumefaciens"]]}'::jsonb, null, null, '{"recall_question":"Which DNA-entry method uses gold or tungsten particles?","reveal_answer":"Biolistics or gene gun.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb, 5, 130, 15, true),
  ('neet-biology-biotechnology-principles-and-process-rdna-process', 'neet-biology-biotechnology-principles-and-process', 'Recombinant DNA Technology Process', 'diagram', 'The source lists six process stages from DNA isolation to downstream processing.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Order","Stage"],"rows":[["1","Isolation of the genetic material (DNA)"],["2","Cutting of DNA at specific locations"],["3","Amplification of gene of interest using PCR"],["4","Insertion of recombinant DNA into host cell"],["5","Obtaining the foreign gene product"],["6","Downstream processing"]]}'::jsonb, '{"type":"bio-rdna-workflow"}'::jsonb, null, '{"recall_question":"What comes after cutting DNA at specific locations in the source process?","reveal_answer":"Amplification of gene of interest using PCR.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb, 5, 130, 16, true),
  ('neet-biology-biotechnology-principles-and-process-dna-isolation', 'neet-biology-biotechnology-principles-and-process', 'DNA Isolation', 'process', 'DNA isolation removes cell barriers, RNA, proteins and other macromolecules before precipitation.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Target","Source-backed treatment"],"rows":[["Bacterial cells","Lysozyme"],["Plant tissue","Cellulase"],["Fungus","Chitinase"],["RNA","Ribonuclease"],["Proteins","Protease"],["Purified DNA","Chilled ethanol precipitates DNA as fine threads"]]}'::jsonb, null, null, '{"recall_question":"Which enzyme breaks fungal cell wall during DNA isolation?","reveal_answer":"Chitinase.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb, 5, 130, 17, true),
  ('neet-biology-biotechnology-principles-and-process-gel-electrophoresis', 'neet-biology-biotechnology-principles-and-process', 'Agarose Gel Electrophoresis', 'diagram', 'Agarose gel electrophoresis separates DNA fragments by size.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Cue","Source-backed recall"],"rows":[["DNA charge","Negatively charged"],["Movement","Moves towards the anode"],["Separation","Fragments separated by size through sieving effect of agarose gel"],["Small fragments","Move farther"],["Agarose source","Sea weeds"],["Visualization","Ethidium bromide staining and UV radiation show bright orange bands"],["Elution","DNA bands cut out from agarose gel"]]}'::jsonb, '{"type":"bio-gel-electrophoresis"}'::jsonb, null, '{"recall_question":"In agarose gel electrophoresis, DNA moves towards which electrode?","reveal_answer":"Anode.","key_points":[],"examples":[],"neet_traps":["DNA is negatively charged, so it moves towards the anode."]}'::jsonb, 5, 130, 18, true),
  ('neet-biology-biotechnology-principles-and-process-pcr-overview', 'neet-biology-biotechnology-principles-and-process', 'PCR Overview', 'concept', 'PCR synthesizes multiple copies of the gene of interest in vitro.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Cue","Source-backed recall"],"rows":[["Full form","Polymerase Chain Reaction"],["Definition","Synthesis of multiple copies of gene of interest in vitro"],["Needs","Two sets of primers and DNA polymerase"],["Primers","Small chemically synthesized oligonucleotides complementary to DNA regions"],["Amplification","DNA segment amplified up to 1 billion copies"]]}'::jsonb, null, null, '{"recall_question":"What does PCR amplify?","reveal_answer":"Gene of interest.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb, 5, 130, 19, true),
  ('neet-biology-biotechnology-principles-and-process-pcr-stages', 'neet-biology-biotechnology-principles-and-process', 'PCR Stages', 'diagram', 'PCR cycles through denaturation, annealing and extension.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Stage","Source-backed event","Temperature"],"rows":[["Denaturation","Heating target DNA to separate strands; each strand acts as template","94°C"],["Annealing","Joining of two primers at 3'' end of DNA templates","52°C"],["Extension","Addition of nucleotides to primer using Taq polymerase","High-temperature active polymerase"]]}'::jsonb, '{"type":"bio-pcr-cycle"}'::jsonb, null, '{"recall_question":"Which thermostable enzyme is used in PCR?","reveal_answer":"Taq polymerase.","key_points":["It is isolated from Thermus aquaticus."],"examples":[],"neet_traps":["Denaturation separates strands; annealing joins primers."]}'::jsonb, 5, 130, 20, true),
  ('neet-biology-biotechnology-principles-and-process-host-selection-product', 'neet-biology-biotechnology-principles-and-process', 'Host Transfer, Selection and Product', 'process', 'Ligated DNA is introduced into host cells and transformants are selected before recombinant protein production.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Stage","Source-backed recall"],"rows":[["Host transfer","Ligated DNA introduced into recipient host cell or organism"],["Ampicillin example","Recombinant DNA bearing ampicillin resistant gene makes E. coli ampicillin-resistant"],["Selection plate","On ampicillin agar plates only transformants grow; untransformed cells die"],["Recombinant protein","Protein encoded by foreign gene and expressed in heterologous host"],["Continuous culture","Used medium drained from one side and fresh medium added from other side to keep cells physiologically active"]]}'::jsonb, null, null, '{"recall_question":"What is a recombinant protein?","reveal_answer":"Protein encoded by a foreign gene expressed in a heterologous host.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb, 5, 131, 21, true),
  ('neet-biology-biotechnology-principles-and-process-bioreactor', 'neet-biology-biotechnology-principles-and-process', 'Bioreactor', 'diagram', 'Bioreactors biologically convert raw materials to products, enzymes etc. using cells.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Cue","Source-backed detail"],"rows":[["Capacity","Can process 100-1000 litres of culture"],["Growth conditions","pH, temperature, substrate, salts, vitamins and oxygen"],["Common type","Stirred-tank bioreactor"],["Shape","Usually cylindrical or with a curved base"],["Stirrer role","Even mixing and oxygen availability"],["Systems","Agitator, oxygen delivery, foam control, temperature control, pH control and sampling ports"]]}'::jsonb, '{"type":"bio-bioreactor"}'::jsonb, null, '{"recall_question":"What is the most common bioreactor type in the source?","reveal_answer":"Stirred-tank bioreactor.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb, 5, 131, 22, true),
  ('neet-biology-biotechnology-principles-and-process-downstream-processing', 'neet-biology-biotechnology-principles-and-process', 'Downstream Processing', 'process', 'Downstream processing prepares a biosynthetic product for use.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Step/cue","Source-backed recall"],"rows":[["Meaning","Series of processes after biosynthetic stage"],["Processes","Separation and purification of products"],["Formulation","Product formulated with suitable preservatives"],["Testing","Clinical trials and strict quality control testing"]]}'::jsonb, null, null, '{"recall_question":"What two processes are named in downstream processing?","reveal_answer":"Separation and purification.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb, 5, 131, 23, true),
  ('neet-biology-biotechnology-and-its-applications-application-areas', 'neet-biology-biotechnology-and-its-applications', 'Biotechnology Application Areas', 'classification', 'Biotechnology has applications in health, agriculture, food, environment and energy.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Cue","Source-backed recall"],"rows":[["Applications","Biopharmaceuticals, therapeutics, diagnostics, genetically modified crops, processed food, bioremediation, waste treatment and energy production"],["Research area 1","Providing best catalyst as improved organism, usually microbe or enzyme"],["Research area 2","Creating optimal conditions through engineering for catalyst to act"],["Research area 3","Downstream processing technologies to purify protein/organic compound"]]}'::jsonb, null, null, '{"recall_question":"What are the three critical biotech research areas centered on?","reveal_answer":"Best catalyst, optimal conditions and downstream processing.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb, 5, 132, 1, true),
  ('neet-biology-biotechnology-and-its-applications-agriculture-options-gmo', 'neet-biology-biotechnology-and-its-applications', 'Agriculture Options and GMOs', 'comparison', 'The source compares three options for increasing food production and defines GMOs.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Option/cue","Source-backed recall"],"rows":[["Agro-chemical based agriculture","Uses fertilizers and pesticides; expensive and causes environmental pollution"],["Organic agriculture","Expensive"],["Genetically engineered crop-based agriculture","Uses genetically modified crops"],["GMO","Plants, bacteria, fungi and animals whose genes are altered by manipulation"]]}'::jsonb, null, null, '{"recall_question":"What is a GMO in the source?","reveal_answer":"Plant, bacterium, fungus or animal whose genes are altered by manipulation.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb, 5, 132, 2, true),
  ('neet-biology-biotechnology-and-its-applications-gm-plant-advantages', 'neet-biology-biotechnology-and-its-applications', 'Genetic Modification in Plants', 'classification', 'Genetic modification improves stress tolerance, pest resistance, nutrition and industrial supply.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Advantage","Source-backed detail"],"rows":[["Abiotic stress tolerance","Cold, drought, salt, heat etc."],["Pest resistance","Reduces use of chemical pesticides"],["Post-harvest losses","Reduces post-harvest losses"],["Mineral usage","Increases efficiency and prevents early exhaustion of soil fertility"],["Nutrition","Enhances nutritional value; Golden rice is Vitamin A enriched rice"],["Industrial resources","Tailor-made plants supply starches, fuels, pharmaceuticals etc."]]}'::jsonb, null, null, '{"recall_question":"Which GM crop example is Vitamin A enriched?","reveal_answer":"Golden rice.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb, 5, 132, 3, true),
  ('neet-biology-biotechnology-and-its-applications-bt-crops', 'neet-biology-biotechnology-and-its-applications', 'Bt Crops and Cry Genes', 'comparison', 'Bt toxins are insect-group specific proteins encoded by cry genes.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Cue","Source-backed detail"],"rows":[["Bacterium","Bacillus thuringiensis"],["Bt toxin","Insecticidal protein crystal formed during a phase of bacterial growth"],["Insects killed by some strains","Coleopterans, lepidopterans and dipterans"],["Bt crops listed","Bt cotton, Bt corn, rice, tomato, potato and soyabean"],["cryIAc and cryIIAb","Control cotton bollworms"],["cryIAb","Controls corn borer"]]}'::jsonb, null, null, '{"recall_question":"Which cry genes control cotton bollworms in the source?","reveal_answer":"cryIAc and cryIIAb.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb, 5, 132, 4, true),
  ('neet-biology-biotechnology-and-its-applications-bt-toxin-mechanism', 'neet-biology-biotechnology-and-its-applications', 'Bt Toxin Mechanism', 'diagram', 'Bt toxin is inactive in Bacillus and becomes active in the insect gut.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Step","Source-backed event"],"rows":[["1","Bt toxin exists as inactive protoxin in Bacillus"],["2","Insect ingests toxin"],["3","Alkaline gut pH solubilises crystals and activates toxin"],["4","Toxin binds mid-gut epithelial cells and creates pores"],["5","Cell swelling and lysis cause insect death"]]}'::jsonb, '{"type":"bio-bt-toxin"}'::jsonb, null, '{"recall_question":"Why does Bt toxin not kill Bacillus in the source?","reveal_answer":"It exists as inactive protoxin in Bacillus.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb, 5, 132, 5, true),
  ('neet-biology-biotechnology-and-its-applications-rnai', 'neet-biology-biotechnology-and-its-applications', 'RNA Interference in Tobacco', 'diagram', 'RNAi prevents Meloidogyne incognita survival in transgenic tobacco roots.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Cue","Source-backed detail"],"rows":[["Nematode","Meloidogyne incognita infects tobacco roots and reduces yield"],["RNAi","Cellular defense in all eukaryotic organisms"],["Mechanism","Prevents translation of specific mRNA due to complementary dsRNA"],["Gene introduction","Nematode-specific genes introduced into host plant using Agrobacterium vectors"],["RNA products","Sense and anti-sense RNA form double stranded RNA"],["Outcome","Specific nematode mRNA is silenced; parasite cannot survive in transgenic host"]]}'::jsonb, '{"type":"bio-rnai-sequence"}'::jsonb, null, '{"recall_question":"Which nematode is controlled by RNAi in tobacco?","reveal_answer":"Meloidogyne incognita.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb, 5, 132, 6, true),
  ('neet-biology-biotechnology-and-its-applications-insulin', 'neet-biology-biotechnology-and-its-applications', 'Genetically Engineered Insulin', 'diagram', 'Human insulin can be produced in bacteria and avoids reactions caused by non-human insulin.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Cue","Source-backed recall"],"rows":[["Use","Manage adult-onset diabetes"],["Old source issue","Insulin from cattle and pigs caused allergy or other reactions to foreign protein"],["Mature insulin","Two short polypeptide chains, A and B, linked by disulphide bridges"],["Proinsulin","Pro-hormone with extra C peptide removed during maturation"],["Eli Lilly, 1983","Prepared DNA sequences for A and B chains, introduced them into E. coli plasmids and combined chains by disulfide bonds"],["Product","Human insulin, Humulin"]]}'::jsonb, '{"type":"bio-recombinant-insulin"}'::jsonb, null, '{"recall_question":"What is removed from proinsulin during maturation?","reveal_answer":"C peptide.","key_points":[],"examples":[],"neet_traps":["C peptide is not part of mature insulin chains A and B."]}'::jsonb, 5, 132, 7, true),
  ('neet-biology-biotechnology-and-its-applications-gene-therapy-ada', 'neet-biology-biotechnology-and-its-applications', 'ADA Gene Therapy', 'diagram', 'Gene therapy corrects a gene defect by inserting genes into a person''s cells and tissues.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Cue","Source-backed detail"],"rows":[["First clinical gene therapy","1990, given to a 4-year old girl with ADA deficiency"],["ADA deficiency cause","Deletion of gene for adenosine deaminase, needed for immune system functioning"],["Not completely curative","Bone marrow transplantation or enzyme replacement therapy by ADA injection"],["Process","Collect lymphocytes, grow in culture, introduce functional ADA cDNA using retroviral vector, return cells to patient"],["Repeat need","Periodically repeated because lymphocytes are not immortal"],["Permanent cure possibility","Introduce ADA gene from marrow cells into cells at early embryonic stages"]]}'::jsonb, '{"type":"bio-ada-gene-therapy"}'::jsonb, null, '{"recall_question":"Why must ADA lymphocyte gene therapy be repeated?","reveal_answer":"Lymphocytes are not immortal.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb, 5, 133, 8, true),
  ('neet-biology-biotechnology-and-its-applications-molecular-diagnosis', 'neet-biology-biotechnology-and-its-applications', 'Molecular Diagnosis', 'comparison', 'PCR and ELISA enable earlier disease diagnosis than conventional serum and urine analysis.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Technique","Source-backed use/principle"],"rows":[["PCR","Detects very low concentration of bacteria or virus by amplification of nucleic acid"],["PCR uses","Detect HIV in suspected patients, detect gene mutations in suspected cancer patients, identify genetic disorders"],["Probe hybridisation","Radioactive single stranded DNA or RNA probe hybridizes to complementary DNA; mutated clone will not appear on photographic film"],["ELISA","Based on antigen-antibody interaction"],["ELISA detection","Detects antigens or antibodies synthesized against pathogen"]]}'::jsonb, null, null, '{"recall_question":"Which molecular diagnosis method is based on antigen-antibody interaction?","reveal_answer":"ELISA.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb, 5, 133, 9, true),
  ('neet-biology-biotechnology-and-its-applications-transgenic-animals', 'neet-biology-biotechnology-and-its-applications', 'Transgenic Animals', 'classification', 'Transgenic animals have genomes altered by introduction of a foreign gene.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Use","Source-backed example/detail"],"rows":[["Examples","Transgenic rats, rabbits, pigs, sheep, cows and fish"],["Frequency","Over 95% of transgenic animals are mice"],["Normal physiology/development","Study insulin-like growth factor by introducing genes that alter its formation"],["Disease models","Cancer, cystic fibrosis, rheumatoid arthritis and Alzheimer''s"],["Biological products","Human protein alpha-1-antitrypsin for emphysema"],["Vaccine safety","Transgenic mice used to test polio vaccine safety"],["Toxicity testing","Animals made more sensitive to toxic substances for immediate results"]]}'::jsonb, null, null, '{"recall_question":"Over 95% of transgenic animals are which animal?","reveal_answer":"Mice.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb, 5, 133, 10, true),
  ('neet-biology-biotechnology-and-its-applications-rosie', 'neet-biology-biotechnology-and-its-applications', 'Rosie the Transgenic Cow', 'fact', 'Rosie produced human protein-enriched milk.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Cue","Source-backed detail"],"rows":[["Year","1997"],["Identity","First transgenic cow"],["Milk","Human protein-enriched milk, 2.4 gm per litre"],["Protein","Human alpha-lactalbumin"],["Claim","Nutritionally more balanced product for human babies than natural cow-milk"]]}'::jsonb, null, null, '{"recall_question":"Which protein did Rosie''s milk contain?","reveal_answer":"Human alpha-lactalbumin.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb, 5, 133, 11, true),
  ('neet-biology-biotechnology-and-its-applications-ethical-issues-geac', 'neet-biology-biotechnology-and-its-applications', 'GEAC and GM Safety', 'fact', 'Genetic modification may cause unpredictable results, so GM research and organisms require safety decisions.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Cue","Source-backed detail"],"rows":[["Problem","Genetic modification may cause unpredictable results"],["Organization","GEAC"],["Expansion","Genetic Engineering Approval Committee"],["Role","Decisions about validity of GM research and safety of GM-organisms for public services"]]}'::jsonb, null, null, '{"recall_question":"Expand GEAC as written in the source.","reveal_answer":"Genetic Engineering Approval Committee.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb, 5, 133, 12, true),
  ('neet-biology-biotechnology-and-its-applications-biopiracy', 'neet-biology-biotechnology-and-its-applications', 'Biopiracy', 'concept', 'Biopiracy is unauthorized use of bio-resources by companies or organizations.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Cue","Source-backed detail"],"rows":[["Biopiracy","Use of bio-resources by multinational companies and other organizations without proper authorization from countries and people concerned"],["Examples of resources","Basmati rice, herbal medicines such as turmeric and neem"],["Basmati varieties","India has 27 varieties of Basmati"],["Patent event","In 1997, an American company got patent rights on Basmati rice through US Patent and Trademark Office"],["Claim","New variety was derived from Indian farmer''s varieties crossed with semi-dwarf varieties"]]}'::jsonb, null, null, '{"recall_question":"How many Basmati varieties does India have according to the source?","reveal_answer":"27 varieties.","key_points":[],"examples":[],"neet_traps":[]}'::jsonb, 5, 133, 13, true),
  ('neet-biology-biotechnology-and-its-applications-biotech-traps', 'neet-biology-biotechnology-and-its-applications', 'Biotechnology NEET Traps', 'neet_trap', 'Common Biotechnology traps involve confusing organism, gene, toxin, enzyme and product.', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"columns":["Trap pair","Source-backed distinction"],"rows":[["Bt bacterium vs Bt genes","Bacillus thuringiensis is the bacterium; cry genes code Bt toxins"],["Protoxin vs active toxin","Bt toxin exists as inactive protoxin in Bacillus; alkaline insect gut activates it"],["PCR vs ELISA","PCR amplifies nucleic acid; ELISA is antigen-antibody interaction"],["Proinsulin vs insulin","Proinsulin has C peptide; mature insulin has A and B chains linked by disulphide bridges"],["GEAC role","Approves/safety-validates GM research and organisms; it is not a cloning vector"]]}'::jsonb, null, null, '{"recall_question":"Which method detects low pathogen concentration by nucleic-acid amplification?","reveal_answer":"PCR.","key_points":[],"examples":[],"neet_traps":["ELISA is based on antigen-antibody interaction."]}'::jsonb, 5, 132, 14, true)
on conflict (id) do update set
  chapter_id = excluded.chapter_id,
  title = excluded.title,
  card_type = excluded.card_type,
  body = excluded.body,
  formulas = excluded.formulas,
  variables = excluded.variables,
  conditions = excluded.conditions,
  table_data = excluded.table_data,
  diagram_data = excluded.diagram_data,
  diagram_svg = excluded.diagram_svg,
  recall_data = excluded.recall_data,
  importance = excluded.importance,
  source_page = excluded.source_page,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active;
