export const BIOLOGY_BATCH_9_CHAPTER_DEFINITIONS = [
  { title: "Human Health and Diseases", slug: "human-health-and-diseases", sort_order: 28, source_page: 117 },
  { title: "Enhancement of Food Production", slug: "enhancement-of-food-production", sort_order: 29, source_page: 122 },
  { title: "Microbes in Human Welfare", slug: "microbes-in-human-welfare", sort_order: 30, source_page: 126 },
];

const chapter = (slug) => `neet-biology-${slug}`;

function table(columns, rows) {
  return { columns, rows };
}

function recall(question, answer, key_points = [], examples = [], neet_traps = []) {
  return { recall_question: question, reveal_answer: answer, key_points, examples, neet_traps };
}

function card(chapterId, slug, payload) {
  return {
    id: `${chapterId}-${slug}`,
    chapter_id: chapterId,
    formulas: [],
    variables: [],
    conditions: [],
    table_data: null,
    diagram_data: null,
    diagram_svg: null,
    is_active: true,
    ...payload,
  };
}

function humanHealthCards(chapterId) {
  return [
    card(chapterId, "health-disease-basics", {
      title: "Health and Disease Basics",
      card_type: "concept",
      body: "Health is complete physical, mental and social well-being; disease adversely affects organ or system functioning.",
      table_data: table(["Cue", "Source-backed recall"], [
        ["Health", "Complete physical, mental and social well-being"],
        ["Affected by", "Genetic disorders, infections and lifestyle including food, water, rest, exercise and habits"],
        ["Disease", "Adverse effect on functioning of organs or systems"],
        ["Infectious disease", "Transmits from person to person"],
        ["Non-infectious disease", "Does not transmit; cancer is the source example"],
      ]),
      recall_data: recall("Which disease type transmits person to person?", "Infectious disease."),
      importance: 5,
      source_page: 117,
      sort_order: 1,
    }),
    card(chapterId, "major-infectious-diseases", {
      title: "Major Infectious Diseases",
      card_type: "comparison",
      body: "The source lists bacterial, viral, protozoan, helminthic and fungal diseases with their agents and routes.",
      table_data: table(["Disease", "Causative organism", "Transmission/vector", "Major source feature"], [
        ["Typhoid", "Salmonella typhi", "Food and water; enters small intestine and migrates via blood", "Widal test confirms"],
        ["Pneumonia", "Streptococcus pneumoniae and Haemophilus influenzae", "Droplets/aerosols or sharing utensils", "Alveoli become fluid-filled"],
        ["Common cold", "Rhinoviruses", "Droplets or contaminated objects", "Infects nose and respiratory passage, not lungs"],
        ["Malaria", "Plasmodium sp.", "Female Anopheles mosquito", "Haemozoin causes chill and high fever every 3-4 days"],
        ["Amoebiasis", "Entamoeba histolytica", "Houseflies contaminate food and water", "Stools with excess mucus and blood clots"],
        ["Ascariasis", "Ascaris", "Food/water contaminated with eggs", "May block intestinal passage"],
        ["Filariasis", "Wuchereria bancrofti and W. malayi", "Female Culex mosquito", "Chronic inflammation of lymphatic vessels"],
        ["Ring worm", "Microsporum, Trichophyton and Epidermophyton", "Soil or shared towels, clothes, combs etc.", "Dry scaly lesions with intense itching"],
      ]),
      recall_data: recall("Which test confirms typhoid in the source?", "Widal test.", [], [], ["Disease, pathogen and vector are separate recall hooks."]),
      importance: 5,
      source_page: 117,
      sort_order: 2,
    }),
    card(chapterId, "typhoid", {
      title: "Typhoid Recall",
      card_type: "fact",
      body: "Typhoid is caused by Salmonella typhi and spreads through contaminated food and water.",
      table_data: table(["Cue", "Source-backed detail"], [
        ["Entry", "Small intestine through food and water"],
        ["Migration", "Migrates to other organs through blood"],
        ["Symptoms", "Sustained high fever 39°-40°C, headache, weakness, stomach pain, constipation and loss of appetite"],
        ["Severe outcome", "Intestinal perforation and death may occur"],
        ["Carrier example", "Mary Mallon, Typhoid Mary, spread typhoid through food as a professional cook"],
      ]),
      recall_data: recall("Which bacterium causes typhoid?", "Salmonella typhi.", ["Widal test confirms the disease."]),
      importance: 5,
      source_page: 117,
      sort_order: 3,
    }),
    card(chapterId, "pneumonia-common-cold", {
      title: "Pneumonia vs Common Cold",
      card_type: "comparison",
      body: "Both involve the respiratory system, but their sites and agents differ.",
      table_data: table(["Feature", "Pneumonia", "Common cold"], [
        ["Agent", "Streptococcus pneumoniae and Haemophilus influenzae", "Rhinoviruses"],
        ["Site", "Lung alveoli", "Nose and respiratory passage, not lungs"],
        ["Transmission", "Droplets/aerosols or shared glasses and utensils", "Droplets or contaminated objects such as pens, books, cups, doorknobs and computer accessories"],
        ["Features", "Respiratory problems, fever, chills, cough and headache; severe cases grey to bluish lips/fingernails", "Nasal congestion/discharge, fever, headache, sore throat, cough, hoarseness and tiredness"],
        ["Duration", "Not specified here", "3-7 days"],
      ]),
      recall_data: recall("Which common respiratory infection does not infect lungs in the source?", "Common cold.", [], [], ["Common cold infects nose and respiratory passage, not lungs."]),
      importance: 5,
      source_page: 117,
      sort_order: 4,
    }),
    card(chapterId, "vector-disease-traps", {
      title: "Disease, Pathogen and Vector Traps",
      card_type: "neet_trap",
      body: "NEET-style recall often swaps pathogen, vector and carrier.",
      table_data: table(["Disease", "Pathogen", "Vector/carrier"], [
        ["Malaria", "Plasmodium sp.; P. falciparum causes malignant malaria", "Female Anopheles mosquito"],
        ["Amoebiasis", "Entamoeba histolytica", "Houseflies are mechanical carriers"],
        ["Filariasis", "Wuchereria bancrofti and W. malayi", "Female Culex mosquito"],
        ["Ring worm", "Microsporum, Trichophyton and Epidermophyton", "Soil or infected towels, clothes and combs"],
      ]),
      recall_data: recall("Which mosquito transmits filariasis?", "Female Culex mosquito.", [], [], ["Female Anopheles transmits malaria; female Culex transmits filariasis."]),
      importance: 5,
      source_page: 117,
      sort_order: 5,
    }),
    card(chapterId, "prevention-control", {
      title: "Prevention and Control",
      card_type: "classification",
      body: "Personal hygiene, public hygiene, vector control, vaccination and antibiotics are listed as control measures.",
      table_data: table(["Control route", "Source-backed actions"], [
        ["Personal hygiene", "Clean body; clean drinking water and food"],
        ["Public hygiene", "Proper disposal of wastes and excreta; periodic cleaning and disinfection of water reservoirs, pools, cesspools and tanks"],
        ["Airborne disease control", "Avoid contact with infected persons and their belongings"],
        ["Vector control", "Avoid stagnant water; clean coolers; use mosquito nets, larvivorous fish Gambusia, insecticides and wire mesh"],
        ["Vaccines/immunisation", "Controlled smallpox, polio, diphtheria, pneumonia and tetanus"],
        ["Antibiotics", "Treat infectious diseases"],
      ]),
      recall_data: recall("Which larvivorous fish is listed for mosquito control?", "Gambusia."),
      importance: 5,
      source_page: 118,
      sort_order: 6,
    }),
    card(chapterId, "lymphoid-organs", {
      title: "Primary vs Secondary Lymphoid Organs",
      card_type: "comparison",
      body: "Primary lymphoid organs mature lymphocytes; secondary lymphoid organs provide sites for antigen interaction.",
      table_data: table(["Type", "Source-backed role", "Examples"], [
        ["Primary lymphoid organs", "Lymphocytes mature and differentiate into antigen-sensitive lymphocytes", "Bone marrow and thymus"],
        ["Secondary lymphoid organs", "Mature lymphocytes migrate, interact with antigens and proliferate into effector cells", "Spleen, lymph nodes, tonsils, Peyer's patches, MALT and appendix"],
      ]),
      recall_data: recall("Which primary lymphoid organ is bilobed near the heart?", "Thymus."),
      importance: 5,
      source_page: 118,
      sort_order: 7,
    }),
    card(chapterId, "immune-classification", {
      title: "Innate vs Acquired Immunity",
      card_type: "diagram",
      body: "Innate immunity is present at birth; acquired immunity is pathogen-specific and has memory.",
      diagram_data: { type: "bio-immune-classification" },
      table_data: table(["Feature", "Innate immunity", "Acquired immunity"], [
        ["Specificity", "Non-specific", "Pathogen-specific"],
        ["Timing", "Present at birth", "Developed during lifetime"],
        ["Memory", "Not emphasized", "Has memory"],
        ["Response pattern", "Barriers act immediately", "Primary response is low intensity; secondary/anamnestic response is high intensity"],
      ]),
      recall_data: recall("Which immunity has memory?", "Acquired immunity.", [], [], ["Innate immunity is non-specific and present at birth."]),
      importance: 5,
      source_page: 118,
      sort_order: 8,
    }),
    card(chapterId, "innate-barriers", {
      title: "Four Innate Barriers",
      card_type: "classification",
      body: "The source groups innate immunity into physical, physiological, cellular and cytokine barriers.",
      table_data: table(["Barrier", "Source-backed examples"], [
        ["Physical", "Skin; mucus coating respiratory, gastrointestinal and urinogenital tracts"],
        ["Physiological", "Gastric HCl, saliva and tears prevent microbial growth"],
        ["Cellular", "Phagocytes such as PMNL/neutrophils, monocytes, natural killer lymphocytes and macrophages"],
        ["Cytokine", "Virus-infected cells secrete interferon to protect non-infected cells"],
      ]),
      recall_data: recall("Which cytokine barrier is secreted by virus-infected cells?", "Interferon."),
      importance: 5,
      source_page: 118,
      sort_order: 9,
    }),
    card(chapterId, "humoral-cell-mediated", {
      title: "Humoral vs Cell-Mediated Immunity",
      card_type: "comparison",
      body: "Acquired immunity works through antibodies and T-cell mediated responses.",
      table_data: table(["Feature", "Humoral immunity", "Cell-mediated immunity"], [
        ["Mediator", "Antibodies in blood plasma", "T cells"],
        ["Also called", "Antibody-mediated immune response or AMI", "CMI"],
        ["Source-linked role", "B lymphocytes produce antibodies; T cells help B cells produce antibodies", "Helps body differentiate self and non-self; important in graft rejection"],
      ]),
      recall_data: recall("Which immune response involves antibodies in blood plasma?", "Humoral immunity."),
      importance: 5,
      source_page: 118,
      sort_order: 10,
    }),
    card(chapterId, "antibody-structure", {
      title: "Antibody Structure",
      card_type: "diagram",
      body: "An antibody has four polypeptide chains arranged as H2L2.",
      diagram_data: { type: "bio-antibody-structure" },
      table_data: table(["Part", "Source-backed detail"], [
        ["Light chains", "Two small chains"],
        ["Heavy chains", "Two longer chains"],
        ["Formula", "H2L2"],
        ["Types listed", "IgG, IgA, IgM, IgE and IgD"],
      ]),
      recall_data: recall("What is the antibody chain formula in the source?", "H2L2."),
      importance: 5,
      source_page: 118,
      sort_order: 11,
    }),
    card(chapterId, "active-passive-immunity", {
      title: "Active vs Passive Immunity",
      card_type: "comparison",
      body: "Active immunity requires antibody production in the host; passive immunity directly supplies ready-made antibodies.",
      table_data: table(["Feature", "Active immunity", "Passive immunity"], [
        ["Basic idea", "Antibodies are produced in the host after exposure to antigens", "Ready-made antibodies are directly given"],
        ["Speed", "Slow", "Quick response"],
        ["Natural example", "Natural infection by microbes", "IgG from mother through placenta; IgA in colostrum"],
        ["Artificial example", "Microbes injected deliberately during immunization", "Anti-tetanus serum"],
      ]),
      recall_data: recall("Which immunity is quick because ready-made antibodies are given?", "Passive immunity.", [], [], ["IgA in colostrum is natural passive immunity in the source."]),
      importance: 5,
      source_page: 119,
      sort_order: 12,
    }),
    card(chapterId, "immunisation-vaccines", {
      title: "Immunisation Recall",
      card_type: "process",
      body: "Vaccination introduces antigenic proteins or inactivated pathogens to generate antibodies and memory B/T cells.",
      table_data: table(["Cue", "Source-backed detail"], [
        ["Basis", "Memory of acquired immunity"],
        ["Vaccine material", "Antigenic proteins of pathogen or inactivated pathogen"],
        ["Later infection", "Antibodies neutralize pathogenic agents"],
        ["Memory cells", "Memory B and T cells are generated"],
        ["Examples", "Polio vaccine, Hepatitis B vaccine and DPT vaccine"],
        ["Recombinant example", "Hepatitis B vaccine produced from Yeast"],
      ]),
      recall_data: recall("Which vaccine example is produced from Yeast by DNA recombinant technology?", "Hepatitis B vaccine."),
      importance: 5,
      source_page: 119,
      sort_order: 13,
    }),
    card(chapterId, "allergy-autoimmunity", {
      title: "Allergy and Autoimmunity",
      card_type: "comparison",
      body: "Allergy is exaggerated response to environmental antigens; autoimmunity is attack on self cells.",
      table_data: table(["Condition", "Source-backed recall", "Examples/details"], [
        ["Allergy", "Exaggerated immune response to environmental antigens", "Allergens include mites in dust, pollens, animal dander and fur"],
        ["Allergy molecules", "IgE binds mast cells and releases histamine and serotonin", "Symptoms include sneezing, watery eyes, running nose, difficulty breathing, wheezing and skin rashes"],
        ["Treatment listed", "Anti-histamine, adrenaline and steroids", "Asthma is listed as a respiratory disease due to allergy"],
        ["Autoimmunity", "Body attacks self cells due to genetic or unknown reasons", "Rheumatoid arthritis"],
      ]),
      recall_data: recall("Which antibody is linked with allergy in the source?", "IgE.", [], [], ["Autoimmunity is self-cell attack, not allergy."]),
      importance: 5,
      source_page: 119,
      sort_order: 14,
    }),
    card(chapterId, "aids-overview-transmission", {
      title: "AIDS: Transmission and Non-Transmission",
      card_type: "neet_trap",
      body: "AIDS is caused by HIV, a retrovirus with RNA genome, and spreads through body fluids.",
      table_data: table(["Cue", "Source-backed detail"], [
        ["Full form", "Acquired Immuno Deficiency Syndrome"],
        ["Cause", "HIV, Human Immunodeficiency Virus; retrovirus with RNA genome"],
        ["Transmission", "Sexual contact, contaminated blood/blood products, infected needles and infected mother to child through placenta"],
        ["Does not spread by", "Touch or physical contact"],
        ["Time lag", "Few months to 5-10 years"],
        ["Diagnosis", "ELISA test"],
      ]),
      recall_data: recall("Which test diagnoses AIDS in the source?", "ELISA test.", [], [], ["HIV does not spread by touch or physical contact."]),
      importance: 5,
      source_page: 119,
      sort_order: 15,
    }),
    card(chapterId, "hiv-life-cycle", {
      title: "HIV Infection Sequence",
      card_type: "diagram",
      body: "HIV first uses macrophages as virus factories and then reduces helper T-cell count.",
      diagram_data: { type: "bio-hiv-sequence" },
      table_data: table(["Step", "Source-backed event"], [
        ["1", "HIV enters macrophages after entering the body"],
        ["2", "Reverse transcriptase uses RNA genome to make viral DNA"],
        ["3", "Viral DNA incorporates into host DNA"],
        ["4", "Infected cells produce virus particles"],
        ["5", "HIV enters helper T-cells and produces progeny viruses"],
        ["6", "Helper T-cell number decreases and immunity weakens"],
      ]),
      recall_data: recall("Which enzyme converts HIV RNA to viral DNA?", "Reverse transcriptase."),
      importance: 5,
      source_page: 119,
      sort_order: 16,
    }),
    card(chapterId, "cancer-basics", {
      title: "Cancer Basics",
      card_type: "concept",
      body: "Cancer cells multiply abnormally and lose contact inhibition.",
      table_data: table(["Cue", "Source-backed recall"], [
        ["Cancer", "Abnormal uncontrolled multiplication of cells forming tumour"],
        ["Normal cells", "Show contact inhibition"],
        ["Cancer cells", "Do not show contact inhibition"],
        ["Metastasis", "Tumour cells travel through blood to form new tumours"],
      ]),
      recall_data: recall("What property is lost in cancer cells?", "Contact inhibition."),
      importance: 5,
      source_page: 120,
      sort_order: 17,
    }),
    card(chapterId, "benign-malignant", {
      title: "Benign vs Malignant Tumour",
      card_type: "diagram",
      body: "Benign tumours stay confined; malignant tumours invade and metastasize.",
      diagram_data: { type: "bio-cancer-metastasis" },
      table_data: table(["Feature", "Benign tumour", "Malignant tumour"], [
        ["Spread", "Confined to original location", "Invades and damages surrounding tissues"],
        ["Damage", "Causes little damage", "Proliferating neoplastic cells starve normal cells"],
        ["Metastasis", "Not described as spreading", "Cells travel through blood and form new tumours"],
      ]),
      recall_data: recall("Which tumour type shows metastasis?", "Malignant tumour.", [], [], ["Benign tumours remain confined to origin."]),
      importance: 5,
      source_page: 120,
      sort_order: 18,
    }),
    card(chapterId, "carcinogens-diagnosis-treatment", {
      title: "Cancer: Causes, Diagnosis and Treatment",
      card_type: "classification",
      body: "The source groups carcinogens and lists major diagnostic and treatment approaches.",
      table_data: table(["Category", "Source-backed details"], [
        ["Physical carcinogens", "Ionizing radiations such as X-rays and gamma rays; non-ionizing UV rays"],
        ["Chemical carcinogens", "Tobacco smoke, vinyl chloride, caffeine, nicotine and mustard gas"],
        ["Biological carcinogens", "Oncogenic viruses; activated c-onc proto-oncogenes"],
        ["Diagnosis", "Biopsy/histopathology; blood and bone marrow tests for leukemia; radiography, CT, MRI; antibodies; molecular biology"],
        ["Treatment", "Radiotherapy, chemotherapy, immunotherapy with alpha-interferon and surgery"],
      ]),
      recall_data: recall("Which biological response modifier is named for cancer immunotherapy?", "Alpha-interferon."),
      importance: 5,
      source_page: 120,
      sort_order: 19,
    }),
    card(chapterId, "drug-categories", {
      title: "Drug Categories and Sources",
      card_type: "comparison",
      body: "The source links abused substances to plant or microbial sources and physiological effects.",
      table_data: table(["Category", "Source/example", "Major source-backed effect"], [
        ["Opioids", "Morphine and heroin from Papaver somniferum latex", "Bind opioid receptors; heroin is a depressant and slows body functions"],
        ["Cannabinoids", "Cannabis sativa; marijuana, hashish, charas and ganja", "Interact with cannabinoid receptors and affect cardiovascular system"],
        ["Coca alkaloid", "Cocaine from Erythroxylum coca", "Interferes dopamine transport; stimulates CNS causing euphoria and increased energy"],
        ["Hallucinogenic plants", "Atropa belladona and Datura", "Listed as hallucinogenic plants"],
        ["Medicinal sedatives/stimulants", "Barbiturates, amphetamines and benzodiazepines", "Abuse impairs physical, physiological and psychological functions"],
      ]),
      recall_data: recall("Which plant yields cocaine?", "Erythroxylum coca."),
      importance: 5,
      source_page: 120,
      sort_order: 20,
    }),
    card(chapterId, "smoking-tobacco", {
      title: "Smoking and Tobacco Effects",
      card_type: "fact",
      body: "Nicotine stimulates adrenal hormone release, while smoking lowers oxygen delivery.",
      table_data: table(["Cue", "Source-backed detail"], [
        ["Nicotine", "Stimulates adrenal gland to release adrenaline and noradrenaline"],
        ["Effect of nicotine", "Raises blood pressure and heart rate"],
        ["Diseases listed", "Lung, urinary bladder and throat cancers; bronchitis, emphysema, coronary heart disease and gastric ulcer"],
        ["Chewing tobacco", "Associated with oral cancer"],
        ["Carbon monoxide", "Increases in blood and reduces oxyhaemoglobin concentration, causing oxygen deficiency"],
      ]),
      recall_data: recall("Why does smoking cause oxygen deficiency in the source?", "It increases CO in blood and reduces oxyhaemoglobin concentration."),
      importance: 5,
      source_page: 120,
      sort_order: 21,
    }),
    card(chapterId, "addiction-dependence", {
      title: "Addiction vs Dependence",
      card_type: "comparison",
      body: "Addiction is psychological attachment; dependence appears as withdrawal when regular dose is stopped.",
      table_data: table(["Feature", "Addiction", "Dependence"], [
        ["Meaning", "Psychological attachment to drugs/alcohol", "Body shows unpleasant withdrawal syndrome if regular dose is abruptly discontinued"],
        ["Dose pattern", "Tolerance at receptor level leads to higher doses", "Regular dose discontinuation causes symptoms"],
        ["Symptoms/effects", "Compulsive use despite problems", "Anxiety, shakiness, nausea, sweating and social adjustment problems"],
      ]),
      recall_data: recall("Which term describes withdrawal symptoms after stopping regular dose?", "Dependence."),
      importance: 5,
      source_page: 121,
      sort_order: 22,
    }),
    card(chapterId, "abuse-prevention-control", {
      title: "Drug and Alcohol Abuse Control",
      card_type: "classification",
      body: "The source emphasizes education, family/peer support and professional help.",
      table_data: table(["Area", "Source-backed recall"], [
        ["Adolescence", "Bridge between childhood and adulthood, 12-18 years"],
        ["Causes of use", "Curiosity, adventure, escape from problems, academic pressure, media, unstable family and peer pressure"],
        ["Possible effects", "Reckless behaviour, coma/death, nervous system damage, liver cirrhosis, family distress, AIDS/hepatitis B spread"],
        ["Prevention/control", "Avoid peer pressure; education and counselling; help from parents and peers; look for danger signs; professional and medical help"],
      ]),
      recall_data: recall("What age range is adolescence in the source?", "12-18 years."),
      importance: 4,
      source_page: 121,
      sort_order: 23,
    }),
    card(chapterId, "malaria", {
      title: "Malaria Recall",
      card_type: "fact",
      body: "Malaria is caused by Plasmodium sp. and transmitted by female Anopheles mosquito.",
      table_data: table(["Cue", "Source-backed detail"], [
        ["Pathogens listed", "Plasmodium vivax, P. malariae and P. falciparum"],
        ["Most serious form", "Malignant malaria caused by P. falciparum"],
        ["Vector", "Female Anopheles mosquito"],
        ["Toxin", "Haemozoin"],
        ["Symptom rhythm", "Chill and high fever every 3-4 days"],
      ]),
      recall_data: recall("Which Plasmodium causes malignant malaria in the source?", "P. falciparum."),
      importance: 5,
      source_page: 117,
      sort_order: 24,
    }),
    card(chapterId, "amoebiasis", {
      title: "Amoebiasis Recall",
      card_type: "fact",
      body: "Amoebiasis or amoebic dysentery is caused by Entamoeba histolytica.",
      table_data: table(["Cue", "Source-backed detail"], [
        ["Causative organism", "Entamoeba histolytica"],
        ["Carrier", "Houseflies act as mechanical carriers"],
        ["Transmission route", "Houseflies transfer parasite from faeces to food and water"],
        ["Symptoms", "Constipation, abdominal pain and cramps; stools with excess mucus and blood clots"],
      ]),
      recall_data: recall("Which organism causes amoebiasis?", "Entamoeba histolytica.", [], [], ["Houseflies are mechanical carriers in amoebiasis."]),
      importance: 5,
      source_page: 117,
      sort_order: 25,
    }),
    card(chapterId, "ascariasis", {
      title: "Ascariasis Recall",
      card_type: "fact",
      body: "Ascariasis is caused by Ascaris, an intestinal parasite.",
      table_data: table(["Cue", "Source-backed detail"], [
        ["Pathogen", "Ascaris"],
        ["Transmission", "Soil, water, vegetables and fruits contaminated with faeces containing eggs"],
        ["Symptoms", "Internal bleeding, muscular pain, fever and anaemia"],
        ["Severe effect", "Blockage of intestinal passage"],
      ]),
      recall_data: recall("Which helminth can block the intestinal passage in the source?", "Ascaris."),
      importance: 5,
      source_page: 117,
      sort_order: 26,
    }),
    card(chapterId, "filariasis", {
      title: "Filariasis Recall",
      card_type: "fact",
      body: "Filariasis or elephantiasis is caused by Wuchereria worms.",
      table_data: table(["Cue", "Source-backed detail"], [
        ["Pathogens", "Wuchereria bancrofti and W. malayi"],
        ["Vector", "Female Culex mosquito"],
        ["Site", "Lymphatic vessels of lower limbs"],
        ["Effect", "Chronic inflammation over many years"],
        ["Deformity", "Lower limbs and genital organs may be deformed"],
      ]),
      recall_data: recall("Which mosquito transmits filariasis?", "Female Culex mosquito.", [], [], ["Female Anopheles is malaria; female Culex is filariasis."]),
      importance: 5,
      source_page: 117,
      sort_order: 27,
    }),
    card(chapterId, "ringworm", {
      title: "Ring Worm Recall",
      card_type: "fact",
      body: "Ring worm is a fungal infection supported by heat and moisture.",
      table_data: table(["Cue", "Source-backed detail"], [
        ["Pathogens", "Microsporum, Trichophyton and Epidermophyton"],
        ["Common sites", "Groin, between toes and other areas"],
        ["Transmission", "Soil or infected towels, clothes, combs etc."],
        ["Symptoms", "Dry scaly lesions on skin, nails and scalp with intense itching"],
        ["Favouring conditions", "Heat and moisture"],
      ]),
      recall_data: recall("Name one fungus causing ring worm from the source.", "Microsporum, Trichophyton or Epidermophyton."),
      importance: 5,
      source_page: 117,
      sort_order: 28,
    }),
  ];
}

function foodProductionCards(chapterId) {
  return [
    card(chapterId, "animal-husbandry-overview", {
      title: "Animal Husbandry Overview",
      card_type: "concept",
      body: "Animal husbandry is the scientific practice of breeding and raising livestock.",
      table_data: table(["Cue", "Source-backed detail"], [
        ["Scope", "Care and breeding of livestock such as buffaloes, cows, pigs, horses, cattle, sheep, camels and goats"],
        ["Also includes", "Poultry and fisheries"],
        ["Problem noted", "India and China have over 70% of world livestock but only 25% of world farm produce"],
        ["Need", "New technologies to increase productivity per unit"],
      ]),
      recall_data: recall("What is animal husbandry?", "Scientific agricultural practice of breeding and raising livestock."),
      importance: 5,
      source_page: 122,
      sort_order: 1,
    }),
    card(chapterId, "dairy-poultry-management", {
      title: "Dairy and Poultry Management",
      card_type: "comparison",
      body: "Both focus on suitable breeds, disease control, feeding and hygiene.",
      table_data: table(["Area", "Dairy management", "Poultry management"], [
        ["Purpose", "Increase yield and quality of milk/products", "Food and eggs from domesticated birds"],
        ["Breed focus", "Good breeds with high yield and disease resistance", "Disease-free suitable breeds"],
        ["Management", "Housing, adequate water, disease-free animals, quality/quantity fodder, hygiene in milking/storage/transport", "Safe farm conditions, proper feed and water, hygiene and health care"],
        ["Examples", "Cattle and milk animals", "Chicken, ducks, turkey and geese"],
      ]),
      recall_data: recall("In dairy management, milk yield depends mainly on what?", "Quality of breeds."),
      importance: 5,
      source_page: 122,
      sort_order: 2,
    }),
    card(chapterId, "inbreeding", {
      title: "Inbreeding",
      card_type: "concept",
      body: "Inbreeding mates closely related individuals of the same breed for 4-6 generations.",
      table_data: table(["Cue", "Source-backed detail"], [
        ["Method", "Identify and mate superior males and females of same breed; evaluate progeny"],
        ["Superior female in cattle", "Produces more milk per lactation"],
        ["Superior bull", "Gives superior progeny"],
        ["Advantages", "Increases homozygosity, evolves pure line, exposes harmful recessives, accumulates superior genes"],
        ["Risk", "Continued close inbreeding reduces fertility and productivity, called inbreeding depression"],
      ]),
      recall_data: recall("What is the risk of continued close inbreeding?", "Inbreeding depression.", ["It reduces fertility and productivity."]),
      importance: 5,
      source_page: 122,
      sort_order: 3,
    }),
    card(chapterId, "outbreeding-comparison", {
      title: "Outcrossing, Cross-Breeding and Interspecific Hybridisation",
      card_type: "comparison",
      body: "Outbreeding includes mating unrelated animals by several routes.",
      table_data: table(["Method", "Source-backed recall", "Example/use"], [
        ["Out-crossing", "Same breed animals with no common ancestors on either side for 4-6 generations", "Best for low milk productivity/growth rate; overcomes inbreeding depression"],
        ["Cross-breeding", "Superior males of one breed mated with superior females of another breed", "Hisardale sheep in Punjab from Bikaneri ewes x Merino rams"],
        ["Interspecific hybridisation", "Male and female animals of different related species are mated", "Mule from male ass x female horse"],
      ]),
      recall_data: recall("Which breeding method produced Hisardale sheep?", "Cross-breeding.", [], [], ["Out-crossing is within the same breed; cross-breeding uses two breeds."]),
      importance: 5,
      source_page: 122,
      sort_order: 4,
    }),
    card(chapterId, "ai-moet", {
      title: "Artificial Insemination vs MOET",
      card_type: "diagram",
      body: "Both are controlled breeding techniques; MOET rapidly multiplies elite germplasm.",
      diagram_data: { type: "bio-moet-flow" },
      table_data: table(["Technique", "Source-backed recall"], [
        ["Artificial insemination", "Semen from male parent is injected into reproductive tract of selected female; semen may be used immediately or frozen and transported"],
        ["MOET hormone step", "Cow receives hormones such as FSH for follicular maturation and super ovulation"],
        ["MOET ovulation", "6-8 eggs per cycle instead of one"],
        ["MOET transfer", "Fertilised eggs at 8-32 cells are recovered non-surgically and transferred to surrogate mothers"],
        ["Used in", "Cattle, sheep, rabbits, buffaloes, mares etc."],
      ]),
      recall_data: recall("In MOET, fertilised eggs are recovered at which stage?", "8-32 cells."),
      importance: 5,
      source_page: 122,
      sort_order: 5,
    }),
    card(chapterId, "apiculture-fisheries", {
      title: "Apiculture and Fisheries",
      card_type: "comparison",
      body: "Apiculture manages honeybee hives; fisheries handle fish and aquatic animals.",
      table_data: table(["Area", "Source-backed recall", "Examples/uses"], [
        ["Apiculture", "Maintenance of hives of honeybees for honey and beeswax", "Common reared species Apis indica; beeswax used in cosmetics and polishes"],
        ["Bee crop value", "Beehives during flowering increase pollination, crop yield and honey yield", "Sunflower, Brassica, apple and pear"],
        ["Fisheries", "Industry of catching, processing and selling fish, shellfish or aquatic animals", "Prawn, crab, lobster and edible oyster"],
        ["Freshwater fishes", "Catla, Rohu and common carp", "Aquaculture is farming aquatic organisms; pisciculture is farming fishes"],
        ["Marine fishes", "Hilsa, Sardines, Mackerel and Pomfrets", "Blue Revolution is development/flourishing fishery industry"],
      ]),
      recall_data: recall("Which honeybee species is listed as commonly reared?", "Apis indica."),
      importance: 5,
      source_page: 123,
      sort_order: 6,
    }),
    card(chapterId, "plant-breeding-steps", {
      title: "Plant Breeding Steps",
      card_type: "diagram",
      body: "Plant breeding manipulates plant species to create desired plant types.",
      diagram_data: { type: "bio-plant-breeding-sequence" },
      table_data: table(["Step", "Source-backed recall"], [
        ["1. Collection of variability", "Collect and preserve wild varieties, species and relatives; germplasm collection contains all alleles for all genes in a crop"],
        ["2. Evaluation and selection of parents", "Evaluate germplasm for desirable characters; multiply selected plants"],
        ["3. Cross hybridisation", "Combine desired characters from two parents"],
        ["4. Selection/testing of superior recombinants", "Select plants superior to parents and self-pollinate for uniformity/homozygosity"],
        ["5. Testing/release/commercialisation", "Test in research and farmers' fields for at least 3 growing seasons across locations"],
      ]),
      recall_data: recall("What is germplasm collection?", "Entire collection of plants or seeds with all alleles for all genes in a crop."),
      importance: 5,
      source_page: 123,
      sort_order: 7,
    }),
    card(chapterId, "green-revolution-varieties", {
      title: "Green Revolution Varieties",
      card_type: "examples",
      body: "The source links semi-dwarf wheat and rice varieties with India's food production increase.",
      table_data: table(["Crop", "Source-backed varieties/details"], [
        ["Wheat", "Norman E. Borlaug developed semi-dwarf wheat; Sonalika and Kalyan Sona introduced in India in 1963"],
        ["Rice", "Semi-dwarf varieties from IR-8 at IRRI Philippines and Taichung Native-1 from Taiwan; later Jaya and Ratna in India"],
        ["Production change", "Wheat rose from 11 million tons to 75 million tons; rice from 35 million tons to 89.5 million tons during 1960-2000"],
        ["Sugar cane", "Saccharum barberi crossed with S. officinarum to combine north adaptation with thick stems and high sugar"],
        ["Millets", "Hybrid maize, jowar and bajra are high yielding and resistant to water stress"],
      ]),
      recall_data: recall("Which two wheat varieties were introduced in India in 1963?", "Sonalika and Kalyan Sona."),
      importance: 5,
      source_page: 123,
      sort_order: 8,
    }),
    card(chapterId, "disease-resistance-varieties", {
      title: "Disease-Resistant Crop Varieties",
      card_type: "examples",
      body: "Resistant cultivars reduce dependence on fungicides and bactericides.",
      table_data: table(["Crop", "Variety", "Resistant to"], [
        ["Wheat", "Himgiri", "Leaf and stripe rust, hill bunt"],
        ["Brassica", "Pusa swarnim / Karan rai", "White rust"],
        ["Cauliflower", "Pusa Shubhra; Pusa Snowball K-1", "Black rot and curl blight black rot"],
        ["Cowpea", "Pusa Komal", "Bacterial blight"],
        ["Chilli", "Pusa Sadabahar", "Chilly mosaic virus, tobacco mosaic virus and leaf curl"],
      ]),
      recall_data: recall("Which wheat variety resists leaf and stripe rust and hill bunt?", "Himgiri."),
      importance: 5,
      source_page: 124,
      sort_order: 9,
    }),
    card(chapterId, "mutation-insect-resistance", {
      title: "Mutation and Insect Resistance",
      card_type: "classification",
      body: "Mutation breeding and resistance traits provide new crop protection routes.",
      table_data: table(["Cue", "Source-backed detail"], [
        ["Mutation breeding", "Uses chemicals or radiations such as gamma rays to produce desirable mutations"],
        ["Mung bean", "Resistance to yellow mosaic virus and powdery mildew induced by mutations"],
        ["Bhindi", "Parbhani kranti developed by transferring yellow mosaic virus resistance from a wild species"],
        ["Hairy leaves", "Resistance to jassids in cotton and cereal leaf beetle in wheat"],
        ["Solid stems", "Wheat non-preference by stem sawfly"],
        ["Biochemical trait", "High aspartic acid and low nitrogen/sugar in maize resist maize stem borers"],
      ]),
      recall_data: recall("Which bhindi variety resists yellow mosaic virus?", "Parbhani kranti."),
      importance: 5,
      source_page: 124,
      sort_order: 10,
    }),
    card(chapterId, "insect-resistant-varieties", {
      title: "Insect-Resistant Varieties",
      card_type: "examples",
      body: "The source lists crop varieties produced by hybridisation and selection for insect resistance.",
      table_data: table(["Crop", "Variety", "Insect pests"], [
        ["Brassica rapeseed mustard", "Pusa Gaurav", "Aphids"],
        ["Flat bean", "Pusa Sem 2 and Pusa Sem 3", "Jassids, aphids and fruit borer"],
        ["Okra/Bhindi", "Pusa Sawani and Pusa A-4", "Shoot and fruit borer"],
      ]),
      recall_data: recall("Which Brassica variety resists aphids?", "Pusa Gaurav."),
      importance: 5,
      source_page: 124,
      sort_order: 11,
    }),
    card(chapterId, "biofortification", {
      title: "Biofortification",
      card_type: "concept",
      body: "Biofortification is breeding crops with higher nutrient levels to improve public health.",
      table_data: table(["Objective", "Source-backed focus"], [
        ["Protein", "Improve protein content and quality"],
        ["Oil", "Improve oil content and quality"],
        ["Vitamins", "Improve vitamin content"],
        ["Micronutrients/minerals", "Improve micronutrient and mineral content"],
        ["Need", "Hidden hunger from micronutrient, protein and vitamin deficiencies"],
      ]),
      recall_data: recall("What is biofortification?", "Breeding crops with higher levels of nutrients."),
      importance: 5,
      source_page: 124,
      sort_order: 12,
    }),
    card(chapterId, "biofortification-examples", {
      title: "Biofortification Examples",
      card_type: "examples",
      body: "Use only source-listed nutrient-rich crop examples.",
      table_data: table(["Improvement", "Source-backed examples"], [
        ["Amino acids", "Maize hybrids with twice lysine and tryptophan compared to existing maize hybrids"],
        ["Protein", "Wheat variety Atlas 66 with high protein content"],
        ["Iron", "Iron-fortified rice variety containing over five times as much iron as common varieties"],
        ["Vitamin A", "Carrots, spinach and pumpkin"],
        ["Vitamin C", "Bitter gourd, bathua, mustard and tomato"],
        ["Iron and calcium", "Spinach and bathua"],
        ["Protein", "Beans: broad, lablab, French and garden peas"],
      ]),
      recall_data: recall("Which wheat variety has high protein content?", "Atlas 66."),
      importance: 5,
      source_page: 124,
      sort_order: 13,
    }),
    card(chapterId, "single-cell-protein", {
      title: "Single Cell Protein",
      card_type: "fact",
      body: "SCP is protein derived from single-celled organisms and is an alternate protein source.",
      table_data: table(["Cue", "Source-backed detail"], [
        ["Examples", "Spirulina and Methylophilus methylotrophus"],
        ["Spirulina nutrients", "Rich in protein, minerals, fats, carbohydrate and vitamins"],
        ["Spirulina growth materials", "Waste water from potato processing plants, straw, molasses, animal manure and sewage"],
        ["Comparison value", "A 250 Kg cow produces only 200 g protein/day; 250 g Methylophilus methylotrophus produces 25 tonnes protein"],
        ["Reason", "High rate of biomass production and growth"],
      ]),
      recall_data: recall("Which bacterium is listed as an SCP example?", "Methylophilus methylotrophus."),
      importance: 5,
      source_page: 125,
      sort_order: 14,
    }),
    card(chapterId, "tissue-culture-micropropagation", {
      title: "Tissue Culture and Micropropagation",
      card_type: "process",
      body: "Tissue culture grows plant cells, tissues or organs in sterile medium under controlled aseptic conditions.",
      table_data: table(["Term", "Source-backed recall"], [
        ["Totipotency", "Ability to generate a whole plant from any cell or explant"],
        ["Explant", "Any part of a plant grown in a test tube under sterile nutrient media"],
        ["Medium", "Carbon source such as sucrose, inorganic salts, vitamins, amino acids and growth regulators such as auxins and cytokinins"],
        ["Micropropagation", "Producing thousands of plants in a very short time through tissue culture"],
        ["Somaclones", "Plants genetically identical to original plant"],
        ["Examples", "Tomato, banana and apple"],
      ]),
      recall_data: recall("What is totipotency?", "Ability to generate a whole plant from any cell or explant."),
      importance: 5,
      source_page: 125,
      sort_order: 15,
    }),
    card(chapterId, "virus-free-somatic-hybridisation", {
      title: "Virus-Free Plants and Somatic Hybridisation",
      card_type: "comparison",
      body: "Tissue culture can recover healthy plants and create somatic hybrids.",
      table_data: table(["Use", "Source-backed method", "Examples/details"], [
        ["Virus-free plants", "Remove meristem from infected plant and grow in vitro", "Banana, sugarcane, potato etc."],
        ["Somatic hybridisation", "Fuse protoplasts from two varieties after digesting cell walls", "Hybrid protoplast can grow into somatic hybrid"],
        ["Pomato", "Protoplast of tomato + protoplast of potato -> pomato", "Hybrid has characteristics of tomato and potato but not all desired traits for commercial utilization"],
      ]),
      recall_data: recall("Which plant part is used to recover virus-free plants?", "Meristem."),
      importance: 5,
      source_page: 125,
      sort_order: 16,
    }),
  ];
}

function microbesCards(chapterId) {
  return [
    card(chapterId, "household-products", {
      title: "Microbes in Household Products",
      card_type: "examples",
      body: "Household microbial products depend mainly on fermentation.",
      table_data: table(["Product/process", "Microbe", "Source-backed recall"], [
        ["Curd", "Lactobacillus or LAB", "Converts milk to curd by acids that coagulate and partially digest milk proteins; increases vitamin B12"],
        ["Dosa/idli dough", "Bacteria", "Anaerobic fermentation produces CO2 and puffs up dough"],
        ["Bread", "Baker's Yeast, Saccharomyces cerevisiae", "Ferments dough"],
        ["Toddy", "Microbes in palm sap", "Made by fermenting sap from palms"],
        ["Swiss cheese", "Propionibacterium sharmanii", "Large holes due to CO2"],
        ["Roquefort cheese", "Penicillium roqueforti", "Ripened by growing fungus on cheese"],
      ]),
      recall_data: recall("Which bacterium produces holes in Swiss cheese?", "Propionibacterium sharmanii."),
      importance: 5,
      source_page: 126,
      sort_order: 1,
    }),
    card(chapterId, "industrial-products", {
      title: "Industrial Microbial Products",
      card_type: "classification",
      body: "Industrial products require growing microbes in large vessels called fermentors.",
      table_data: table(["Product group", "Source-backed examples"], [
        ["Fermented beverages", "Saccharomyces cerevisiae ferments malted cereals and fruit juices to ethanol"],
        ["Without distillation", "Wine and beer"],
        ["With distillation", "Whisky, Brandy, Rum, Gin and Arrack"],
        ["Antibiotics", "Chemical substances produced by microbes that kill or retard pathogen growth"],
        ["Antibiotic uses", "Treat plague, whooping cough, diphtheria, leprosy etc."],
      ]),
      recall_data: recall("Which yeast is used in fermented beverages?", "Saccharomyces cerevisiae."),
      importance: 5,
      source_page: 126,
      sort_order: 2,
    }),
    card(chapterId, "penicillin", {
      title: "Penicillin Recall",
      card_type: "fact",
      body: "Penicillin was the first antibiotic discovered by Alexander Fleming.",
      table_data: table(["Cue", "Source-backed detail"], [
        ["Observation", "Staphylococci could not grow around Penicillium notatum on unwashed culture plates"],
        ["Discovery", "Alexander Fleming extracted penicillin from the mould"],
        ["Full potential", "Earnest Chain and Howard Florey established its full potential as an effective antibiotic"],
        ["Nobel Prize", "Fleming, Chain and Florey were awarded Nobel Prize in 1945"],
      ]),
      recall_data: recall("Which mould produced penicillin in Fleming's observation?", "Penicillium notatum."),
      importance: 5,
      source_page: 126,
      sort_order: 3,
    }),
    card(chapterId, "organic-acids", {
      title: "Organic Acid Producers",
      card_type: "examples",
      body: "The source lists exact microbe-acid pairs.",
      table_data: table(["Microorganism", "Product"], [
        ["Aspergillus niger", "Citric acid"],
        ["Acetobacter aceti", "Acetic acid"],
        ["Clostridium butylicum", "Butyric acid"],
        ["Lactobacillus", "Lactic acid"],
      ]),
      recall_data: recall("Which fungus produces citric acid?", "Aspergillus niger."),
      importance: 5,
      source_page: 126,
      sort_order: 4,
    }),
    card(chapterId, "enzymes-bioactive", {
      title: "Enzymes and Bioactive Molecules",
      card_type: "examples",
      body: "Microbes produce enzymes and bioactive molecules used in medicine and industry.",
      table_data: table(["Product", "Microbe/source", "Use"], [
        ["Lipases", "Microbes", "Detergent formulations; remove oily stains from laundry"],
        ["Pectinases and Proteases", "Microbes", "Clarify bottled juices"],
        ["Streptokinase", "Streptococcus", "Clot buster for blood clots in myocardial infarction patients"],
        ["Cyclosporine A", "Trichoderma polysporum", "Immunosuppressive agent in organ transplant patients"],
        ["Statins", "Monascus purpureus", "Blood-cholesterol lowering agents; inhibit enzymes for cholesterol synthesis"],
      ]),
      recall_data: recall("Which microbe produces Streptokinase?", "Streptococcus.", [], [], ["Trichoderma polysporum produces Cyclosporine A, not Streptokinase."]),
      importance: 5,
      source_page: 126,
      sort_order: 5,
    }),
    card(chapterId, "sewage-treatment-flow", {
      title: "Sewage Treatment Flow",
      card_type: "diagram",
      body: "Sewage treatment makes municipal waste-water less polluting before release.",
      diagram_data: { type: "bio-sewage-treatment" },
      table_data: table(["Stage", "Source-backed event"], [
        ["Sewage", "Municipal waste-water contains large organic matter and microbes"],
        ["Primary treatment", "Sequential filtration removes floating debris; sedimentation removes grit"],
        ["Primary sludge/effluent", "Settled solids form primary sludge; supernatant forms primary effluent"],
        ["Secondary treatment", "Primary effluent enters aeration tanks; useful aerobic microbes grow into flocs"],
        ["BOD reduction", "Microbes consume organic matter and reduce BOD"],
        ["Activated sludge", "Flocs sediment in settling tank; small part pumped back as inoculum"],
        ["Anaerobic digesters", "Remaining sludge produces gases such as CH4, H2S and CO2"],
      ]),
      recall_data: recall("What is activated sludge?", "Sediment of bacterial flocs from the settling tank."),
      importance: 5,
      source_page: 126,
      sort_order: 6,
    }),
    card(chapterId, "primary-secondary-sewage", {
      title: "Primary vs Secondary Sewage Treatment",
      card_type: "comparison",
      body: "Primary treatment is physical; secondary treatment is biological.",
      table_data: table(["Feature", "Primary treatment", "Secondary treatment"], [
        ["Nature", "Physical removal of particles", "Biological treatment"],
        ["Processes", "Sequential filtration and sedimentation", "Aeration, growth of flocs, organic matter consumption and settling"],
        ["Output terms", "Primary sludge and primary effluent", "Activated sludge and treated effluent"],
        ["Key effect", "Removes floating debris, soil and pebbles", "Reduces BOD"],
      ]),
      recall_data: recall("Which sewage treatment stage reduces BOD?", "Secondary treatment."),
      importance: 5,
      source_page: 126,
      sort_order: 7,
    }),
    card(chapterId, "bod-trap", {
      title: "BOD Recall Trap",
      card_type: "neet_trap",
      body: "BOD measures organic matter and polluting potential through oxygen consumption.",
      table_data: table(["Cue", "Source-backed recall"], [
        ["Full form", "Biochemical Oxygen Demand"],
        ["Definition", "Amount of O2 consumed by bacteria to oxidize all organic matter in one litre of water"],
        ["Indicates", "Measure of organic matter present in water"],
        ["Trap", "Greater BOD means greater polluting potential"],
      ]),
      recall_data: recall("What does greater BOD indicate?", "Greater polluting potential.", [], [], ["BOD rises with organic matter/polluting potential."]),
      importance: 5,
      source_page: 126,
      sort_order: 8,
    }),
    card(chapterId, "biogas-process", {
      title: "Biogas Production",
      card_type: "diagram",
      body: "Biogas is mainly CH4 produced by microbial activity under anaerobic conditions.",
      diagram_data: { type: "bio-biogas-process" },
      table_data: table(["Cue", "Source-backed detail"], [
        ["Biogas", "Mixture of gases, mainly CH4, used for cooking and lighting"],
        ["Methanogens", "Grow anaerobically on cellulosic material and produce CH4"],
        ["Example", "Methanobacterium"],
        ["Natural locations", "Anaerobic sludge and rumen of cattle"],
        ["Dung", "Rich in these bacteria; used to generate Gobar gas"],
        ["Developed in India by", "IARI and KVIC"],
      ]),
      recall_data: recall("Which methanogen example is given for biogas?", "Methanobacterium."),
      importance: 5,
      source_page: 127,
      sort_order: 9,
    }),
    card(chapterId, "biocontrol-agents", {
      title: "Biocontrol Agents",
      card_type: "comparison",
      body: "Biocontrol uses biological methods to control plant diseases and pests.",
      table_data: table(["Agent", "Target/use", "Source-backed note"], [
        ["Lady bird beetle", "Aphids", "Example of biological control"],
        ["Dragon flies", "Mosquitoes", "Example of biological control"],
        ["Bacillus thuringiensis (Bt)", "Butterfly caterpillar", "Spores sprayed on brassicas and fruit trees; toxin released in larval gut"],
        ["Bt cotton", "Insect control", "B. thuringiensis toxin genes introduced into plants"],
        ["Trichoderma sp.", "Several plant pathogens", "Free living fungus in root ecosystems"],
        ["Baculoviruses, especially Nucleopolyhedrovirus", "Insects and other arthropods", "Species-specific, narrow spectrum; useful in IPM"],
      ]),
      recall_data: recall("Which bacterial biocontrol agent controls butterfly caterpillar?", "Bacillus thuringiensis (Bt)."),
      importance: 5,
      source_page: 127,
      sort_order: 10,
    }),
    card(chapterId, "biocontrol-vs-chemical", {
      title: "Biocontrol vs Chemical Control",
      card_type: "comparison",
      body: "The source contrasts broad chemical damage with targeted biological control.",
      table_data: table(["Feature", "Biocontrol", "Chemical pesticides/insecticides"], [
        ["Method", "Uses biological methods for controlling pests and diseases", "Uses chemical pesticides and insecticides"],
        ["Effect on organisms", "Conserves beneficial insects in IPM when narrow-spectrum agents are used", "Kills both useful and harmful organisms"],
        ["Pollution", "No such problems stated for biocontrol", "Causes pollution"],
      ]),
      recall_data: recall("Which control method avoids killing both useful and harmful organisms?", "Biocontrol method."),
      importance: 5,
      source_page: 127,
      sort_order: 11,
    }),
    card(chapterId, "biofertiliser-map", {
      title: "Biofertiliser Types",
      card_type: "diagram",
      body: "Biofertilisers enrich nutrient quality of soil.",
      diagram_data: { type: "bio-biofertiliser-map" },
      table_data: table(["Type", "Examples", "Source-backed role"], [
        ["Symbiotic bacteria", "Rhizobium", "Root nodules of leguminous plants; fix atmospheric N2"],
        ["Free-living bacteria", "Azospirillum and Azotobacter", "Enrich nitrogen content of soil"],
        ["Fungi", "Glomus in mycorrhiza", "Absorbs phosphorus and passes it to plant; improves resistance/tolerance and growth"],
        ["Cyanobacteria", "Anabaena, Nostoc and Oscillatoria", "Fix atmospheric nitrogen; important in paddy fields; add organic matter"],
      ]),
      recall_data: recall("Which fungal genus is listed for mycorrhiza?", "Glomus."),
      importance: 5,
      source_page: 127,
      sort_order: 12,
    }),
  ];
}

const biologyBatch9CardsBySlug = {
  "human-health-and-diseases": humanHealthCards,
  "enhancement-of-food-production": foodProductionCards,
  "microbes-in-human-welfare": microbesCards,
};

export function getBiologyBatch9Chapters() {
  return BIOLOGY_BATCH_9_CHAPTER_DEFINITIONS.map((item) => ({
    id: chapter(item.slug),
    subject_id: "neet-biology",
    title: item.title,
    slug: item.slug,
    sort_order: item.sort_order,
    source_page: item.source_page,
  }));
}

export function getBiologyBatch9Cards() {
  return BIOLOGY_BATCH_9_CHAPTER_DEFINITIONS.flatMap((item) => biologyBatch9CardsBySlug[item.slug](chapter(item.slug)));
}
