export const BIOLOGY_BATCH_3_CHAPTER_DEFINITIONS = [
  { title: "Structural Organization in Animals", slug: "structural-organization-in-animals", sort_order: 7, source_page: 32 },
  { title: "Cells: The Unit of Life", slug: "cells-the-unit-of-life", sort_order: 8, source_page: 36 },
  { title: "Cell Cycle and Cell Division", slug: "cell-cycle-and-cell-division", sort_order: 9, source_page: 41 },
];

const chapter = (slug) => `neet-biology-${slug}`;

function table(columns, rows) {
  return { columns, rows };
}

function sections(items) {
  return { sections: items };
}

function recall(question, answer, key_points = [], examples = [], neet_traps = []) {
  return { recall_question: question, reveal_answer: answer, key_points, examples, neet_traps };
}

function card(chapterId, slug, payload) {
  return {
    id: `${chapterId}-${slug}`,
    chapter_id: chapterId,
    formulas: [],
    variables: [],
    conditions: [],
    table_data: null,
    diagram_data: null,
    diagram_svg: null,
    is_active: true,
    ...payload,
  };
}

function structuralCards(chapterId) {
  return [
    card(chapterId, "animal-tissues-overview", {
      title: "Animal Tissues Overview",
      card_type: "classification",
      body: "Animal tissues are groups of cells with same origin, structure and function.",
      table_data: table(["Animal tissue", "Recall cue"], [
        ["Epithelial", "Covers or lines body or body parts."],
        ["Connective", "Links and supports other tissues/organs."],
        ["Muscular", "Muscle fibres contract and relax."],
        ["Neural", "Neurons carry impulses; neuroglia support them."],
      ]),
      recall_data: recall("Name the four animal tissue types in the source.", "Epithelial, connective, muscular and neural."),
      importance: 5,
      source_page: 32,
      sort_order: 1,
    }),
    card(chapterId, "epithelium-basics", {
      title: "Epithelial Tissue",
      card_type: "concept",
      body: "Epithelial tissue has a free surface, covers or lines body parts, and has compactly packed cells with little intercellular matrix.",
      table_data: table(["Type", "Recall answer"], [
        ["Simple epithelium", "Single layer of cells; lines body cavities, ducts and tubes."],
        ["Compound epithelium", "More than one layer of cells; protects against chemical and mechanical stresses."],
      ]),
      recall_data: recall("What are the two types of epithelial tissues?", "Simple and compound.", ["Simple epithelium has a single layer of cells.", "Compound epithelium is multi-layered."]),
      importance: 5,
      source_page: 32,
      sort_order: 2,
    }),
    card(chapterId, "simple-epithelium-comparison", {
      title: "Squamous vs Cuboidal vs Columnar",
      card_type: "comparison",
      body: "Simple epithelium is classified by structural modification of cells.",
      diagram_data: { type: "bio-epithelium-types" },
      table_data: table(["Type", "Structure", "Location", "Function / trap"], [
        ["Squamous", "Thin layer of flattened cells with irregular boundaries.", "Walls of blood vessels and lung alveoli.", "Forms a diffusion boundary."],
        ["Cuboidal", "Cube-like cells.", "Ducts of glands and tubular parts of nephrons.", "Secretion and absorption; PCT epithelium has microvilli."],
        ["Columnar", "Tall and slender cells; nuclei at base; free surface may have microvilli.", "Lining of stomach and intestine.", "Secretion and absorption."],
      ]),
      recall_data: recall("Which epithelium lines PCT and what special feature is noted?", "Cuboidal epithelium; PCT epithelium has microvilli.", [], [], ["PCT epithelium has microvilli."]),
      importance: 5,
      source_page: 32,
      sort_order: 3,
    }),
    card(chapterId, "ciliated-glandular-epithelium", {
      title: "Ciliated and Glandular Epithelium",
      card_type: "classification",
      body: "Ciliated and glandular epithelia are modifications of columnar or cuboidal cells.",
      table_data: table(["Epithelium", "Recall answer", "Source examples"], [
        ["Ciliated", "Cells bear cilia on free surface; move particles or mucus in a specific direction.", "Inner surface of bronchioles and fallopian tubes"],
        ["Glandular", "Modified for secretion.", "Goblet cells of alimentary canal; salivary glands"],
        ["Unicellular gland", "Isolated glandular cells.", "Goblet cells of the alimentary canal"],
        ["Multicellular gland", "Cluster of cells.", "Salivary glands"],
      ]),
      recall_data: recall("What is the function of ciliated epithelium?", "To move particles or mucus in a specific direction over the epithelium.", [], ["Bronchioles", "Fallopian tubes"]),
      importance: 4,
      source_page: 32,
      sort_order: 4,
    }),
    card(chapterId, "exocrine-endocrine", {
      title: "Exocrine vs Endocrine Glands",
      card_type: "comparison",
      body: "Glands are grouped by mode of pouring secretions.",
      table_data: table(["Gland", "Recall answer", "Source examples/products"], [
        ["Exocrine", "Secretions are released through ducts.", "Mucus, saliva, earwax, oil, milk, digestive enzymes"],
        ["Endocrine", "Ductless; produce hormones.", "Hormones"],
      ]),
      recall_data: recall("Which glands are ductless?", "Endocrine glands.", ["Exocrine glands release secretions through ducts."]),
      importance: 5,
      source_page: 32,
      sort_order: 5,
    }),
    card(chapterId, "compound-epithelium-junctions", {
      title: "Compound Epithelium and Cell Junctions",
      card_type: "classification",
      body: "Compound epithelium has limited secretion and absorption and protects against chemical and mechanical stresses.",
      table_data: sections([
        {
          title: "Compound epithelium",
          columns: ["Feature", "Source detail"],
          rows: [["Layers", "More than one layer of cells."], ["Covers", "Dry surface of skin, moist surface of buccal cavity, pharynx, inner lining of ducts of salivary glands and pancreatic ducts."], ["Function", "Protect against chemical & mechanical stresses."]],
        },
        {
          title: "Cell junctions",
          columns: ["Junction", "Recall answer"],
          rows: [["Tight junction", "Help stop substances from leaking across a tissue."], ["Adhering junction", "Cement neighbouring cells together."], ["Gap junction", "Connect cytoplasm for rapid transfer of ions, small molecules and sometimes big molecules."]],
        },
      ]),
      recall_data: recall("Which junction allows rapid transfer between adjoining cells?", "Gap junction.", ["Tight junctions prevent leakage.", "Adhering junctions keep neighbouring cells together."]),
      importance: 5,
      source_page: 32,
      sort_order: 6,
    }),
    card(chapterId, "connective-overview", {
      title: "Connective Tissue",
      card_type: "classification",
      body: "Connective tissue is most abundant in complex animals and links/supports tissues and organs.",
      table_data: table(["Feature", "Recall answer"], [
        ["Fibroblasts", "All connective tissues except blood have fibroblast cells."],
        ["Fibroblast products", "Collagen and elastin give strength, elasticity and flexibility."],
        ["Matrix", "Modified polysaccharides accumulate between cells and fibres."],
        ["Types", "Loose, dense and specialised."],
      ]),
      recall_data: recall("Which connective tissue lacks fibroblast cells according to the source?", "Blood.", [], [], ["Blood is connective tissue."]),
      importance: 5,
      source_page: 32,
      sort_order: 7,
    }),
    card(chapterId, "areolar-adipose", {
      title: "Areolar vs Adipose Tissue",
      card_type: "comparison",
      body: "Loose connective tissues have cells and fibres loosely arranged in semi-fluid matrix.",
      table_data: table(["Tissue", "Recall answer", "Location/function"], [
        ["Areolar", "Contains fibroblasts, macrophages, mast cells etc. with fibres in semi-fluid matrix.", "Present beneath skin; support framework for epithelium."],
        ["Adipose", "Adipocytes store fats.", "Seen mainly under skin; excess nutrients converted to fats are stored."],
      ]),
      recall_data: recall("Which loose connective tissue stores fat?", "Adipose tissue.", ["Its cells are adipocytes."]),
      importance: 5,
      source_page: 33,
      sort_order: 8,
    }),
    card(chapterId, "dense-connective", {
      title: "Dense Connective Tissue",
      card_type: "comparison",
      body: "Dense connective tissue has fibres and fibroblasts compactly packed.",
      table_data: table(["Type", "Recall answer", "Source example"], [
        ["Dense regular", "Regular pattern; collagen fibres in rows between many parallel bundles of fibres.", "Tendons & ligaments"],
        ["Tendon", "Attaches muscles to bones.", ""],
        ["Ligament", "Attaches one bone to another.", ""],
        ["Dense irregular", "Irregular pattern; fibroblasts and mostly collagen fibres oriented differently.", "Skin"],
      ]),
      recall_data: recall("Tendon vs ligament: what do they attach?", "Tendon attaches muscles to bones; ligament attaches one bone to another."),
      importance: 5,
      source_page: 33,
      sort_order: 9,
    }),
    card(chapterId, "cartilage-bone-blood", {
      title: "Cartilage, Bone and Blood",
      card_type: "comparison",
      body: "Specialised connective tissues include cartilage, bone and blood.",
      table_data: table(["Tissue", "Recall answer", "Source locations/functions"], [
        ["Cartilage", "Solid, pliable matrix due to chondroitin salts; resists compression; chondrocytes lie in cavities.", "Tip of nose, outer ear, joints in vertebral column, limbs and hands."],
        ["Bone", "Hard, non-pliable matrix rich in calcium salts and collagen fibres; osteocytes in lacunae.", "Structural frame, protection, locomotion, bone marrow makes blood cells."],
        ["Blood", "Fluid connective tissue with plasma, RBC, WBC and platelets.", "Circulation of various substances."],
      ]),
      recall_data: recall("Why is blood a connective tissue in this source?", "It is listed as a fluid connective tissue containing plasma, RBC, WBC and platelets.", [], [], ["Blood is connective tissue."]),
      importance: 5,
      source_page: 33,
      sort_order: 10,
    }),
    card(chapterId, "muscle-types", {
      title: "Skeletal, Smooth and Cardiac Muscle",
      card_type: "comparison",
      body: "Muscle tissue is made of muscle fibres composed of many myofibrils.",
      diagram_data: { type: "bio-muscle-types" },
      table_data: table(["Muscle", "Control/structure", "Source location/function"], [
        ["Skeletal", "Striated or voluntary; fibres bundled parallel and enclosed by tough connective tissue.", "Attached to bones, e.g. Biceps."],
        ["Smooth", "Non-striated or visceral; involuntary and fusiform; no striations.", "Walls of blood vessels, stomach and intestine."],
        ["Cardiac", "Involuntary; seen only in heart; intercalated discs allow cells to contract as a unit.", "Heart."],
      ]),
      recall_data: recall("Which muscle is involuntary and present only in the heart?", "Cardiac muscle.", ["Gap junctions at intercalated discs allow contraction as a unit."], [], ["Cardiac muscle is involuntary."]),
      importance: 5,
      source_page: 33,
      sort_order: 11,
    }),
    card(chapterId, "neural-tissue", {
      title: "Neural Tissue",
      card_type: "concept",
      body: "Neural tissue is made up of neurons and neuroglial cells and controls/co-ordinates the body.",
      table_data: table(["Cell", "Recall answer"], [
        ["Neuron", "Unit of neural system; excitable cells that carry impulses."],
        ["Neuroglia", "Protect and support neurons; make up more than half the volume of neural tissue."],
      ]),
      recall_data: recall("Which cells make up more than half the volume of neural tissue?", "Neuroglia."),
      importance: 4,
      source_page: 33,
      sort_order: 12,
    }),
    card(chapterId, "cockroach-intro", {
      title: "Cockroach Identity and Classification",
      card_type: "classification",
      body: "Cockroach (Periplaneta americana) is nocturnal, omnivorous and lives in damp places.",
      table_data: table(["Systematic position", "Source value"], [
        ["Phylum", "Arthropoda"],
        ["Class", "Insecta"],
        ["Genus", "Periplaneta"],
        ["Species", "americana"],
        ["Size", "1/4 inches to 3 inches (0.6-7.6 cm); adults about 34-53 mm long."],
      ]),
      recall_data: recall("What is the genus and species of cockroach in the source?", "Periplaneta americana.", ["Cockroaches are nocturnal, omnivores and live in damp places."]),
      importance: 5,
      source_page: 34,
      sort_order: 13,
    }),
    card(chapterId, "cockroach-morphology", {
      title: "Cockroach Morphology",
      card_type: "classification",
      body: "Cockroach body has hard brown chitinous exoskeleton and three regions: head, thorax and abdomen.",
      diagram_data: { type: "bio-cockroach-body" },
      table_data: table(["Structure", "Recall answer"], [
        ["Exoskeleton", "Hard brown chitinous; sclerites are dorsal tergites and ventral sternites joined by arthrodial membrane."],
        ["Head", "Triangular, formed by 6 fused segments; flexible neck gives mobility."],
        ["Thorax", "Prothorax, mesothorax and metathorax; each segment bears a pair of walking legs."],
        ["Abdomen", "10 segments."],
      ]),
      recall_data: recall("What are the three body regions of cockroach?", "Head, thorax and abdomen."),
      importance: 5,
      source_page: 34,
      sort_order: 14,
    }),
    card(chapterId, "cockroach-head-mouthparts-wings", {
      title: "Head, Mouthparts and Wings",
      card_type: "classification",
      body: "Cockroach has biting and chewing type mouthparts and two pairs of wings.",
      table_data: table(["Part", "Recall answer"], [
        ["Head bears", "Thread-like antennae, compound eyes and biting & chewing type mouth parts."],
        ["Mouthparts", "Labrum (upper lip), 2 mandibles, 2 maxillae, hypopharynx (tongue) & labium (lower lip)."],
        ["Forewings / tegmina", "Mesothoracic; opaque, dark and leathery; cover hind wings at rest."],
        ["Hind wings", "Metathoracic; transparent, membranous and used in flight."],
      ]),
      recall_data: recall("What are tegmina in cockroach?", "Forewings: opaque, dark and leathery mesothoracic wings that cover hind wings at rest."),
      importance: 5,
      source_page: 34,
      sort_order: 15,
    }),
    card(chapterId, "male-female-cockroach", {
      title: "Male vs Female Cockroach",
      card_type: "comparison",
      body: "Sexes differ in size, wing extension, abdomen width, anal styles and brood pouch.",
      table_data: table(["Feature", "Male", "Female"], [
        ["Size", "Larger size", "Smaller"],
        ["Wings", "Extend beyond the tip of abdomen.", "Do not extend beyond the tip of abdomen."],
        ["Abdomen", "Narrow abdomen", "Broad abdomen"],
        ["Anal styles", "Present", "Absent"],
        ["Brood pouch", "Absent", "Present"],
      ]),
      recall_data: recall("Which sex has anal styles in cockroach?", "Male.", ["Females have a brood pouch."]),
      importance: 5,
      source_page: 34,
      sort_order: 16,
    }),
    card(chapterId, "cockroach-digestive", {
      title: "Cockroach Digestive System",
      card_type: "sequence",
      body: "Cockroach alimentary canal has foregut, midgut and hindgut.",
      table_data: table(["Part", "Recall answer"], [
        ["Foregut", "Cuticle-lined: mouth -> pharynx -> oesophagus -> crop -> gizzard."],
        ["Crop", "Stores food."],
        ["Gizzard", "Grinds food; has thick circular muscles and 6 chitinous plates (teeth)."],
        ["Midgut / mesenteron", "Not lined by cuticle; 6-8 hepatic/gastric caecae secrete digestive juice."],
        ["Malpighian tubules position", "100-150 yellow thin filamentous tubules at junction of midgut and hindgut."],
        ["Hindgut", "Broader than midgut, cuticle-lined; ileum, colon and rectum; opens through anus."],
      ]),
      recall_data: recall("What are the three parts of cockroach alimentary canal?", "Foregut, midgut and hindgut.", ["The gizzard grinds food.", "Malpighian tubules occur at the junction of midgut and hindgut."]),
      importance: 5,
      source_page: 34,
      sort_order: 17,
    }),
    card(chapterId, "cockroach-circulatory-respiratory-excretory", {
      title: "Cockroach Circulation, Respiration and Excretion",
      card_type: "comparison",
      body: "Cockroach has open circulation, tracheal respiration and Malpighian tubule excretion.",
      table_data: table(["System", "Recall answer"], [
        ["Circulatory", "Open type; vessels poorly developed and open into haemocoel; haemolymph is colourless plasma + haemocytes."],
        ["Heart", "Elongated muscular tube along mid dorsal line with funnel-shaped chambers and ostia."],
        ["Respiratory", "Network of trachea opens through 10 pairs of spiracles; tracheoles carry oxygen to all parts; diffusion at tracheoles."],
        ["Excretory", "Uricotelic; excretory organ is Malpighian tubules; wastes converted to uric acid and excreted through hindgut."],
        ["Other excretory helpers", "Fat body, nephrocytes & urecose glands."],
      ]),
      recall_data: recall("What are the excretory organs of cockroach?", "Malpighian tubules.", ["Cockroach is uricotelic."], [], ["Cockroach respiratory system uses tracheae/tracheoles.", "Malpighian tubules are excretory organs in cockroach."]),
      importance: 5,
      source_page: 35,
      sort_order: 18,
    }),
    card(chapterId, "cockroach-nervous-sensory", {
      title: "Cockroach Nervous System and Mosaic Vision",
      card_type: "classification",
      body: "Cockroach nervous system is ventral and segmentally arranged.",
      table_data: table(["Feature", "Recall answer"], [
        ["Nervous system", "Segmentally arranged ganglia joined by paired longitudinal connectives on ventral side."],
        ["Ganglia", "3 in thorax and 6 in abdomen."],
        ["Head note", "Head holds only a bit of nervous system; cockroach can live one week after head is cut off."],
        ["Brain", "Supra-oesophageal ganglion supplies nerves to antennae and compound eyes."],
        ["Sense organs", "Antennae, eyes, maxillary palps, labial palps, anal cerci etc."],
        ["Compound eye", "About 2000 hexagonal ommatidia."],
        ["Mosaic vision", "Several images of an object; more sensitivity but less resolution; nocturnal vision."],
      ]),
      recall_data: recall("What produces mosaic vision in cockroach?", "About 2000 hexagonal ommatidia in each compound eye.", ["It has more sensitivity but less resolution and is common during night."]),
      importance: 5,
      source_page: 35,
      sort_order: 19,
    }),
    card(chapterId, "cockroach-reproduction", {
      title: "Cockroach Reproductive Systems",
      card_type: "comparison",
      body: "Cockroaches are dioecious.",
      table_data: table(["System", "Recall answer"], [
        ["Male components", "Pair of testes, seminal vesicles, accessory glands and external genitalia."],
        ["Testes", "Lie laterally in 4th-6th abdominal segments."],
        ["Male duct path", "Each testis -> vas deferens -> seminal vesicle -> ejaculatory duct -> male gonopore."],
        ["Spermatophores", "Sperms are glued together to form bundles and discharged during copulation."],
        ["Accessory glands", "Mushroom gland in 6th-7th abdominal segments and phallic gland; secretions nourish sperms."],
        ["Female components", "2 large ovaries, oviducts, spermatheca, genital chamber, colleterial glands etc."],
        ["Ovaries", "Lie laterally in 2nd-6th abdominal segments; each has 8 ovarioles."],
      ]),
      recall_data: recall("How many ovarioles form each cockroach ovary?", "8 ovarian tubules (ovarioles).", ["Ovaries lie laterally in 2nd-6th abdominal segments."]),
      importance: 5,
      source_page: 35,
      sort_order: 20,
    }),
    card(chapterId, "ootheca-development-economics", {
      title: "Ootheca, Development and Economic Importance",
      card_type: "fact",
      body: "Fertilised eggs are encased in oothecae, and development is paurometabolous.",
      table_data: table(["Topic", "Recall answer"], [
        ["Ootheca", "Dark reddish to blackish brown capsule, 8 mm long."],
        ["Egg count", "Females lay 9-10 oothecae, each containing 14-16 eggs."],
        ["Development", "Paurometabolous, through nymphal stage."],
        ["Nymphs", "Look like adults, moult 13 times; next-to-last nymph has wing pads; only adults have wings."],
        ["Economic importance", "Pests that destroy food, contaminate it with smelly excreta, and transmit bacterial diseases like cholera, typhoid, tuberculosis etc."],
      ]),
      recall_data: recall("What is paurometabolous development in cockroach?", "Development through nymphal stage.", ["Nymphs look like adults and moult 13 times to reach adult form."]),
      importance: 5,
      source_page: 35,
      sort_order: 21,
    }),
  ];
}

function cellCards(chapterId) {
  return [
    card(chapterId, "cell-definition-history", {
      title: "Cell Definition and Early Discoveries",
      card_type: "fact",
      body: "A cell is the fundamental, structural and functional unit of all living organisms.",
      table_data: table(["Scientist", "Source-backed contribution"], [
        ["Robert Hooke", "Discovered cell."],
        ["Anton Von Leeuwenhoek", "First observed and described a live cell."],
        ["Matthias Schleiden (1838)", "Observed that all plants are composed of different kinds of cells."],
        ["Theodore Schwann (1839)", "Found plasma membrane and plant cell wall; proposed that animals and plants are composed of cells and products of cells."],
        ["Rudolf Virchow (1855)", "Explained cells divide and new cells form from pre-existing cells; modified cell theory."],
      ]),
      recall_data: recall("Who first observed and described a live cell?", "Anton Von Leeuwenhoek.", [], [], ["Robert Hooke discovered cell; Leeuwenhoek observed live cell."]),
      importance: 5,
      source_page: 36,
      sort_order: 1,
    }),
    card(chapterId, "cell-theory", {
      title: "Cell Theory",
      card_type: "concept",
      body: "Schleiden and Schwann formulated cell theory; Virchow modified it.",
      table_data: table(["Statement", "Cell theory wording"], [
        ["1", "All living organisms are composed of cells and products of cells."],
        ["2", "All cells arise from pre-existing cells."],
      ]),
      recall_data: recall("State the two source statements of cell theory.", "All living organisms are composed of cells and products of cells; all cells arise from pre-existing cells.", ["Virchow's phrase in source: Omnis cellula-e cellula."]),
      importance: 5,
      source_page: 36,
      sort_order: 2,
    }),
    card(chapterId, "cell-size-facts", {
      title: "Cell Size and Shape Facts",
      card_type: "fact",
      body: "Cells differ in size, shape and activities.",
      table_data: table(["Fact", "Source value"], [
        ["Smallest cells", "Mycoplasmas (0.3 micrometre in length)."],
        ["Largest isolated single cell", "Egg of ostrich."],
        ["Longest cells", "Nerve cell."],
        ["Size of bacteria", "3 to 5 micrometre; typical 1 to 2 micrometre."],
        ["Human RBC diameter", "About 7.0 micrometre."],
      ]),
      recall_data: recall("What is the smallest cell listed in the source?", "Mycoplasmas, 0.3 micrometre in length.", ["Largest isolated single cell is egg of ostrich.", "Longest cells: nerve cell."]),
      importance: 5,
      source_page: 36,
      sort_order: 3,
    }),
    card(chapterId, "prokaryotic-cells", {
      title: "Prokaryotic Cells",
      card_type: "concept",
      body: "Prokaryotic cells have no membrane-bound nucleus and organelles.",
      diagram_data: { type: "bio-prokaryotic-cell" },
      table_data: table(["Feature", "Recall answer"], [
        ["Includes", "Bacteria, blue-green algae, mycoplasma & PPLO."],
        ["Size/multiplication", "Generally smaller and multiply more rapidly than eukaryotic cells."],
        ["Bacterial shapes", "Bacillus, Coccus, Vibrio and Spirillum."],
      ]),
      recall_data: recall("What do prokaryotic cells lack?", "Membrane-bound nucleus and organelles.", [], ["Bacteria, blue-green algae, mycoplasma & PPLO"]),
      importance: 5,
      source_page: 36,
      sort_order: 4,
    }),
    card(chapterId, "cell-envelope-gram", {
      title: "Cell Envelope and Gram Response",
      card_type: "comparison",
      body: "Prokaryotic cell envelope is a chemically complex protective covering of three tightly bound layers.",
      table_data: sections([
        {
          title: "Cell envelope layers",
          columns: ["Layer", "Recall answer"],
          rows: [["Glycocalyx", "Outer layer; may be loose slime layer or thick tough capsule."], ["Cell wall", "Middle layer; absent in mycoplasma; gives shape and prevents bursting/collapsing."], ["Plasma membrane", "Inner semi-permeable layer; structurally similar to eukaryotes."]],
        },
        {
          title: "Gram staining",
          columns: ["Bacterium", "Recall answer"],
          rows: [["Gram positive", "Take up and retain gram stain."], ["Gram negative", "Do not retain gram stain."]],
        },
      ]),
      recall_data: recall("Which prokaryotes lack cell wall in the source?", "Mycoplasma.", ["Gram-positive bacteria retain gram stain; Gram-negative bacteria do not."]),
      importance: 5,
      source_page: 36,
      sort_order: 5,
    }),
    card(chapterId, "mesosome-chromatophore", {
      title: "Mesosomes and Chromatophores",
      card_type: "classification",
      body: "Mesosomes and chromatophores are membranous structures in prokaryotes.",
      table_data: table(["Structure", "Recall answer"], [
        ["Mesosome", "Infoldings of plasma membrane; includes vesicles, tubules and lamellae."],
        ["Mesosome functions", "Cell wall formation, DNA replication, chromosome distribution, respiration/secretion, increased plasma membrane surface and enzymatic content."],
        ["Chromatophores", "Pigment-containing membranous infoldings in some prokaryotes, e.g. cyanobacteria."],
      ]),
      recall_data: recall("What is a mesosome?", "An infolding of plasma membrane in prokaryotes.", ["It includes vesicles, tubules and lamellae."]),
      importance: 4,
      source_page: 36,
      sort_order: 6,
    }),
    card(chapterId, "nucleoid-plasmid", {
      title: "Nucleoid and Plasmid",
      card_type: "concept",
      body: "Nucleoid is non-membranous circular genomic DNA with protein.",
      table_data: table(["Term", "Recall answer"], [
        ["Nucleoid", "Non-membranous naked circular genomic DNA (single chromosome/genetic material) and protein."],
        ["Plasmid", "Small circular DNA outside genomic DNA; gives unique phenotypic characters such as antibiotic resistance."],
      ]),
      recall_data: recall("Which bacterial DNA can give antibiotic resistance?", "Plasmid.", ["It is small circular DNA outside genomic DNA."]),
      importance: 5,
      source_page: 36,
      sort_order: 7,
    }),
    card(chapterId, "flagella-pili-fimbriae", {
      title: "Flagella, Pili and Fimbriae",
      card_type: "comparison",
      body: "Bacterial surface structures differ in motility and attachment.",
      table_data: table(["Structure", "Recall answer"], [
        ["Flagella", "Thin filamentous cell-wall extensions of motile bacteria; bacterial flagellum has filament, hook and basal body."],
        ["Pili", "Elongated tubular structures made of pilin; no role in motility."],
        ["Fimbriae", "Small bristle-like fibres; help bacteria attach to rocks in streams and host tissues."],
      ]),
      recall_data: recall("What are the three parts of a bacterial flagellum?", "Filament, hook and basal body.", ["Pili and fimbriae have no role in motility."]),
      importance: 5,
      source_page: 36,
      sort_order: 8,
    }),
    card(chapterId, "ribosomes-inclusion", {
      title: "Prokaryotic Ribosomes and Inclusion Bodies",
      card_type: "classification",
      body: "Prokaryotic ribosomes are 70S and inclusion bodies are reserve materials.",
      table_data: table(["Structure", "Recall answer"], [
        ["Ribosome size", "About 15 nm by 20 nm."],
        ["70S ribosome", "50S and 30S subunits together."],
        ["Polyribosome / polysome", "Several ribosomes attach to one mRNA and translate it into proteins."],
        ["Inclusion bodies", "Non-membranous stored reserve material free in cytoplasm."],
        ["Examples", "Phosphate granules, cyanophycean granules, glycogen granules, gas vacuoles etc."],
        ["Gas vacuoles", "Found in blue green and purple and green photosynthetic bacteria."],
      ]),
      recall_data: recall("What subunits form a 70S prokaryotic ribosome?", "50S and 30S.", ["S is sedimentation coefficient."]),
      importance: 5,
      source_page: 37,
      sort_order: 9,
    }),
    card(chapterId, "prokaryote-eukaryote", {
      title: "Prokaryotic vs Eukaryotic Cells",
      card_type: "comparison",
      body: "The source gives a direct comparison between prokaryotic and eukaryotic cells.",
      table_data: table(["Feature", "Prokaryotic cells", "Eukaryotic cells"], [
        ["Size", "Generally smaller", "Larger"],
        ["Genetic material", "In the form of nucleoid", "In the form of nucleus"],
        ["Nuclear membrane", "Absent", "Present"],
        ["Membrane-bound organelles", "Absent", "Present"],
        ["DNA", "Circular DNA", "Linear DNA"],
        ["Ribosomes", "70S type", "80S type (70S in plastids and mitochondria)"],
      ]),
      recall_data: recall("What ribosomes are found in prokaryotes vs eukaryotic cytoplasm?", "Prokaryotes have 70S; eukaryotic cytoplasm has 80S.", ["Plastids and mitochondria have 70S ribosomes."]),
      importance: 5,
      source_page: 38,
      sort_order: 10,
    }),
    card(chapterId, "plant-animal-cell", {
      title: "Plant Cell vs Animal Cell",
      card_type: "comparison",
      body: "The source comparison separates plant and animal cells by cell wall, plastids, vacuoles and centrioles.",
      table_data: table(["Feature", "Plant cell", "Animal cell"], [
        ["Cell wall", "Present", "Absent"],
        ["Plastids", "Present", "Absent"],
        ["Vacuole", "A large central vacuole", "Many small vacuoles"],
        ["Centrioles", "Absent", "Present"],
      ]),
      recall_data: recall("Which has centrioles: plant cell or animal cell?", "Animal cell.", ["Plant cells have cell wall, plastids and a large central vacuole."]),
      importance: 5,
      source_page: 38,
      sort_order: 11,
    }),
    card(chapterId, "plasma-membrane-fluid-mosaic", {
      title: "Plasma Membrane and Fluid Mosaic Model",
      card_type: "diagram",
      body: "Cell membrane has lipid bilayer, protein and carbohydrate. Singer and Nicolson proposed the fluid mosaic model in 1972.",
      diagram_data: { type: "bio-plasma-membrane" },
      table_data: table(["Feature", "Recall answer"], [
        ["Human RBC membrane", "52% protein and 40% lipids."],
        ["Lipids", "Mainly phosphoglycerides with polar heads and hydrophobic tails."],
        ["Integral proteins", "Partially or totally buried in membrane."],
        ["Peripheral proteins", "Lie on the surface of membrane."],
        ["Fluid mosaic model", "Quasi-fluid lipid nature allows lateral movement of proteins; this ability is measured as fluidity."],
        ["Functions", "Transport, cell growth, intercellular junctions, secretion, endocytosis, cell division etc."],
      ]),
      recall_data: recall("Who proposed the fluid mosaic model and when?", "Singer & Nicolson, 1972.", ["Fluidity is the ability of proteins to move laterally within the membrane."]),
      importance: 5,
      source_page: 37,
      sort_order: 12,
    }),
    card(chapterId, "transport-types", {
      title: "Passive vs Active Transport",
      card_type: "comparison",
      body: "Transport across membrane may occur along or against concentration gradient.",
      table_data: table(["Transport", "Direction/energy", "Source examples/details"], [
        ["Passive transport", "Along concentration gradient, without energy.", "From higher to lower concentration."],
        ["Simple diffusion", "Passive movement of neutral solutes across membrane.", "Neutral solutes."],
        ["Osmosis", "Movement of water by diffusion across membrane.", "Water."],
        ["Active transport", "Against concentration gradient, with ATP expenditure.", "Na+/K+ pump."],
      ]),
      recall_data: recall("Which transport uses ATP and moves against concentration gradient?", "Active transport.", ["Passive transport does not use energy and moves high to low."]),
      importance: 5,
      source_page: 37,
      sort_order: 13,
    }),
    card(chapterId, "cell-wall-middle-lamella", {
      title: "Cell Wall, Middle Lamella and Plasmodesmata",
      card_type: "classification",
      body: "Cell wall is a non-living rigid structure outside plasma membrane in fungi and plants.",
      table_data: table(["Term", "Recall answer"], [
        ["Algal cell wall", "Cellulose, galactans, mannans and minerals like CaCO3."],
        ["Other plant cell wall", "Cellulose, hemicellulose, pectins and proteins."],
        ["Primary wall", "Young plant cell wall capable of growth."],
        ["Secondary wall", "Formed on inner side towards membrane as cell matures."],
        ["Middle lamella", "Calcium pectate layer that glues neighbouring cells together."],
        ["Plasmodesmata", "Traverse cell wall/middle lamella and connect cytoplasm of neighbouring cells."],
        ["Functions", "Shape, protection, cell-to-cell interaction, barrier to undesirable macromolecules."],
      ]),
      recall_data: recall("What is middle lamella made of according to the source?", "Calcium pectate.", ["It glues neighbouring cells together."]),
      importance: 5,
      source_page: 38,
      sort_order: 14,
    }),
    card(chapterId, "endomembrane-er", {
      title: "Endomembrane System and ER",
      card_type: "comparison",
      body: "Endomembrane system includes ER, Golgi complex, lysosomes and vacuoles.",
      table_data: table(["Structure", "Recall answer"], [
        ["Endoplasmic reticulum", "Network of tiny tubular structures; divides intracellular space into luminal and extra luminal compartments."],
        ["RER", "Bears ribosomes; seen in cells involved in protein synthesis and secretion; extends to outer nuclear membrane."],
        ["SER", "Ribosomes absent; major site for lipid synthesis; steroidal hormones synthesized in animal cells."],
      ]),
      recall_data: recall("RER vs SER: which bears ribosomes and which synthesizes lipids?", "RER bears ribosomes; SER lacks ribosomes and synthesizes lipids.", ["Steroidal hormones are synthesized in SER in animal cells."]),
      importance: 5,
      source_page: 38,
      sort_order: 15,
    }),
    card(chapterId, "golgi-lysosome-vacuole", {
      title: "Golgi, Lysosomes and Vacuoles",
      card_type: "classification",
      body: "Golgi, lysosomes and vacuoles are parts of the endomembrane system.",
      table_data: table(["Organelle", "Recall answer"], [
        ["Golgi apparatus", "Densely stained reticular structures near nucleus, first observed by Camillo Golgi; stacked cisternae with cis and trans faces."],
        ["Golgi functions", "Secretion, vesicle packaging, modification of ER proteins, formation of glycoproteins and glycolipids."],
        ["Lysosomes", "Golgi-derived membrane-bound vesicles with hydrolases active at acidic pH."],
        ["Vacuoles", "Membrane-bound spaces containing water, sap, excretory product and other materials; tonoplast is single membrane."],
        ["Plant vacuole", "Can occupy up to 90% of cell volume; tonoplast helps transport ions/materials against gradients."],
        ["Amoeba", "Contractile vacuole helps excretion."],
      ]),
      recall_data: recall("Which organelle packages lysosomal vesicles?", "Golgi apparatus.", ["Lysosomal hydrolases digest carbohydrates, proteins, lipids and nucleic acids."]),
      importance: 5,
      source_page: 38,
      sort_order: 16,
    }),
    card(chapterId, "mitochondria", {
      title: "Mitochondria",
      card_type: "diagram",
      body: "Mitochondria are double membrane-bound sites of aerobic respiration and ATP production.",
      diagram_data: { type: "bio-mitochondrion" },
      table_data: table(["Feature", "Recall answer"], [
        ["Shape/size", "Sausage-shaped or cylindrical; diameter 0.2-1.0 micrometre, length 1.0-4.1 micrometre."],
        ["Membranes", "Outer membrane and inner membrane divide lumen into outer compartment and matrix."],
        ["Cristae", "Inner membrane infoldings that increase surface area."],
        ["Matrix", "Circular DNA, RNA, 70S ribosomes and protein synthesis components."],
        ["Division", "Divide by fission."],
        ["Function", "Sites of aerobic respiration; produce ATP; called power houses of the cell."],
      ]),
      recall_data: recall("Why are mitochondria called power houses of the cell?", "They produce energy in the form of ATP.", ["They are sites of aerobic respiration."]),
      importance: 5,
      source_page: 38,
      sort_order: 17,
    }),
    card(chapterId, "plastids-chloroplast", {
      title: "Plastids and Chloroplasts",
      card_type: "diagram",
      body: "Plastids occur in plant cells and euglenoides; chloroplasts trap light energy for photosynthesis.",
      diagram_data: { type: "bio-chloroplast" },
      table_data: sections([
        {
          title: "Plastid types",
          columns: ["Type", "Recall answer"],
          rows: [["Chloroplasts", "Contain chlorophyll and carotenoid pigments."], ["Chromoplasts", "Contain fat-soluble carotenoid pigments like carotene and xanthophylls; yellow/orange/red colour."], ["Leucoplasts", "Colourless plastids with stored nutrients: amyloplasts store starch, elaioplasts store oils/fats, aleuroplasts store proteins."]],
        },
        {
          title: "Chloroplast structure",
          columns: ["Part", "Recall answer"],
          rows: [["Location", "Mainly in mesophyll cells of leaves."], ["Shape/size", "Lens-shaped, oval, spherical, discoid or ribbon-like; 5-10 micrometre long, 2-4 micrometre wide."], ["Stroma", "Space limited by inner membrane; has circular DNA, ribosomes and enzymes."], ["Thylakoids/grana", "Thylakoids are flattened sacs; stacks are grana; stroma lamellae connect grana."], ["Ribosomes", "70S, smaller than cytoplasmic 80S."]],
        },
      ]),
      recall_data: recall("Which leucoplast stores starch?", "Amyloplast.", ["Elaioplast stores oils and fats; aleuroplast stores proteins."], ["Potato"]),
      importance: 5,
      source_page: 39,
      sort_order: 18,
    }),
    card(chapterId, "ribosomes-cytoskeleton", {
      title: "Eukaryotic Ribosomes and Cytoskeleton",
      card_type: "comparison",
      body: "Ribosomes are non-membranous granular structures; cytoskeleton is a filamentous protein network.",
      table_data: table(["Structure", "Recall answer"], [
        ["Ribosomes", "RNA and proteins; first observed by George Palade (1953)."],
        ["80S ribosome", "60S large subunit + 40S small subunit."],
        ["Cytoskeleton", "Network of filamentous proteinaceous structures in cytoplasm."],
        ["Cytoskeleton function", "Mechanical support, motility, maintenance of cell shape etc."],
      ]),
      recall_data: recall("What subunits form 80S ribosomes?", "60S and 40S.", ["George Palade first observed ribosomes in 1953."]),
      importance: 5,
      source_page: 39,
      sort_order: 19,
    }),
    card(chapterId, "cilia-flagella-axoneme", {
      title: "Cilia, Flagella and 9+2 Axoneme",
      card_type: "diagram",
      body: "Cilia and flagella are hair-like outgrowths of the cell membrane with axoneme core.",
      diagram_data: { type: "bio-axoneme" },
      table_data: table(["Structure", "Recall answer"], [
        ["Cilia", "Small structures working like oars; cause movement of cell or surrounding fluid."],
        ["Flagella", "Longer; responsible for cell movement; prokaryotic and eukaryotic flagella differ."],
        ["Axoneme", "Core with microtubules parallel to long axis."],
        ["9+2 array", "9 peripheral doublet pairs and a pair of central microtubules."],
        ["Radial spokes", "Central sheath connected to one tubule of each peripheral doublet by radial spoke; 9 radial spokes."],
        ["Basal bodies", "Cilium and flagellum emerge from centriole-like basal bodies."],
      ]),
      recall_data: recall("What is the 9+2 arrangement?", "9 pairs of peripheral doublets plus a pair of central microtubules.", ["It is the axoneme arrangement of cilia and flagella."]),
      importance: 5,
      source_page: 39,
      sort_order: 20,
    }),
    card(chapterId, "centrosome-centriole", {
      title: "Centrosome and Centrioles",
      card_type: "classification",
      body: "Centrosome usually contains two non-membrane-bound cylindrical centrioles.",
      table_data: table(["Feature", "Recall answer"], [
        ["Arrangement", "Centrioles lie perpendicular to each other."],
        ["Fibrils", "9 evenly spaced peripheral fibrils of tubulin; each peripheral fibril is a triplet."],
        ["Hub", "Central proteinaceous part connected to peripheral triplets by radial spokes."],
        ["Functions", "Form basal body of cilia/flagella and spindle fibres for spindle apparatus in animal cell division."],
      ]),
      recall_data: recall("What do centrioles form during cell division?", "Spindle fibres that give rise to spindle apparatus in animal cells.", ["They also form basal bodies of cilia or flagella."]),
      importance: 4,
      source_page: 39,
      sort_order: 21,
    }),
    card(chapterId, "nucleus", {
      title: "Nucleus",
      card_type: "classification",
      body: "Nucleus was first described by Robert Brown in 1831.",
      table_data: table(["Part", "Recall answer"], [
        ["Nuclear envelope", "Double membrane with 10-50 nm perinuclear space; pores allow RNA/protein movement; outer membrane often continuous with ER and bears ribosomes."],
        ["Nuclear matrix / nucleoplasm", "Interphase nuclear matrix."],
        ["Chromatin", "Network of nucleoprotein fibres with DNA, histones, non-histone proteins and RNA; condenses into chromosomes during division."],
        ["Nucleolus", "Non-membranous spherical body continuous with nucleoplasm; site for rRNA synthesis."],
        ["Anucleate mature cells", "Mammalian RBC and sieve tube cells of vascular plants."],
      ]),
      recall_data: recall("Who first described the nucleus?", "Robert Brown (1831).", ["Chromatin was named by Flemming."]),
      importance: 5,
      source_page: 39,
      sort_order: 22,
    }),
    card(chapterId, "chromosome-types", {
      title: "Chromosome Types",
      card_type: "diagram",
      body: "Chromosomes are classified by centromere position.",
      diagram_data: { type: "bio-chromosome-types" },
      table_data: table(["Chromosome", "Centromere position", "Arms"], [
        ["Metacentric", "Middle", "Two equal arms."],
        ["Sub-metacentric", "Nearer to one end", "One shorter arm and one longer arm."],
        ["Acrocentric", "Close to end", "One very short and one very long arm."],
        ["Telocentric", "Terminal", "Terminal centromere."],
      ]),
      recall_data: recall("Which chromosome has a terminal centromere?", "Telocentric chromosome.", ["Kinetochores are disc-shaped structures on the sides of centromere.", "Satellite is a non-staining secondary constriction at a constant location."]),
      importance: 5,
      source_page: 40,
      sort_order: 23,
    }),
    card(chapterId, "microbodies", {
      title: "Microbodies",
      card_type: "fact",
      body: "Microbodies are membrane-bound minute vesicles containing various enzymes.",
      recall_data: recall("Where are microbodies present?", "In both plant and animal cells.", ["They contain various enzymes."]),
      importance: 3,
      source_page: 40,
      sort_order: 24,
    }),
    card(chapterId, "mitochondria-chloroplast-comparison", {
      title: "Mitochondria vs Chloroplast",
      card_type: "comparison",
      body: "Both organelles are double membrane-bound and contain circular DNA and 70S ribosomes in the source.",
      table_data: table(["Feature", "Mitochondria", "Chloroplast"], [
        ["Main role", "Aerobic respiration and ATP production.", "Photosynthesis; traps light energy."],
        ["Internal membrane", "Cristae are inner membrane infoldings.", "Thylakoids stack as grana; stroma lamellae connect grana."],
        ["Internal space", "Matrix.", "Stroma."],
        ["Genetic/protein machinery", "Circular DNA, RNA, 70S ribosomes.", "Circular DNA, ribosomes and enzymes; chloroplast ribosomes are 70S."],
      ]),
      recall_data: recall("What is the internal fluid space called in mitochondria vs chloroplast?", "Mitochondrial matrix; chloroplast stroma."),
      importance: 5,
      source_page: 39,
      sort_order: 25,
    }),
    card(chapterId, "ribosome-70s-80s", {
      title: "70S vs 80S Ribosomes",
      card_type: "comparison",
      body: "The source distinguishes prokaryotic and eukaryotic ribosomes by subunits.",
      table_data: table(["Ribosome", "Subunits", "Where noted"], [
        ["70S", "50S + 30S", "Prokaryotes; chloroplasts and mitochondria."],
        ["80S", "60S + 40S", "Eukaryotic cytoplasmic ribosomes."],
      ]),
      recall_data: recall("Do 50S and 30S add numerically to 80S?", "No. S is sedimentation coefficient, a measure of density and size.", [], [], ["70S = 50S + 30S by sedimentation behaviour, not arithmetic addition."]),
      importance: 5,
      source_page: 37,
      sort_order: 26,
    }),
  ];
}

function cellCycleCards(chapterId) {
  return [
    card(chapterId, "cell-cycle-definition", {
      title: "Cell Cycle Definition",
      card_type: "concept",
      body: "Cell cycle is the life period of a cell during which it synthesizes DNA, grows and divides into two daughter cells.",
      recall_data: recall("What is the cell cycle?", "The life period of a cell during which a cell synthesizes DNA, grows and divides into two daughter cells.", ["Cell growth is continuous but DNA synthesis occurs only at a specific stage."]),
      importance: 5,
      source_page: 41,
      sort_order: 1,
    }),
    card(chapterId, "cell-cycle-phases", {
      title: "G1 -> S -> G2 -> M",
      card_type: "sequence",
      body: "Cell cycle has two basic phases: interphase and M phase.",
      diagram_data: { type: "bio-cell-cycle" },
      table_data: table(["Phase", "Recall answer"], [
        ["Interphase", "Between two successive M phases; includes growth and DNA synthesis; lasts more than 95% of cell-cycle duration."],
        ["G1", "First growth phase; interval between mitosis and DNA replication; growth, metabolic activity, machinery for DNA replication, RNA/protein synthesis."],
        ["S", "DNA replication; DNA amount doubles but chromosome number does not increase; centriole duplicates in animal cells."],
        ["G2", "Second growth phase; cell growth and RNA/protein synthesis continue; cell prepared for mitosis."],
        ["M phase", "Actual cell division; includes karyokinesis and cytokinesis; about one hour in human cell cycle."],
      ]),
      recall_data: recall("What is the correct cell-cycle sequence?", "G1 -> S -> G2 -> M.", [], [], ["DNA doubles in S phase but chromosome number does not increase.", "Interphase lasts more than 95% of cell-cycle duration."]),
      importance: 5,
      source_page: 41,
      sort_order: 2,
    }),
    card(chapterId, "g0-quiescent", {
      title: "G0 / Quiescent Stage",
      card_type: "fact",
      body: "Cells that do not divide further exit G1 phase and enter the inactive G0 stage.",
      table_data: table(["Feature", "Recall answer"], [
        ["G0 entry", "Cells exit G1 phase."],
        ["Activity", "Metabolically active but do not proliferate."],
        ["Non-dividing example", "Heart cells."],
      ]),
      recall_data: recall("Are G0 cells metabolically active?", "Yes, they remain metabolically active but do not proliferate."),
      importance: 4,
      source_page: 41,
      sort_order: 3,
    }),
    card(chapterId, "mitosis-basics", {
      title: "Mitosis Basics",
      card_type: "concept",
      body: "Mitosis occurs in somatic cells and is called equational division.",
      table_data: table(["Feature", "Recall answer"], [
        ["Where", "Somatic cells; generally diploid cells."],
        ["Why equational", "Chromosome number in parent and progeny cells is same."],
        ["Exceptions noted", "Occurs in haploid cells of some lower plants and some social insects."],
        ["Stages", "Prophase, metaphase, anaphase and telophase."],
      ]),
      recall_data: recall("Why is mitosis called equational division?", "Because chromosome number in parent and progeny cells is same.", [], [], ["Mitosis is equational division."]),
      importance: 5,
      source_page: 41,
      sort_order: 4,
    }),
    card(chapterId, "mitosis-stages", {
      title: "Mitosis Stages",
      card_type: "sequence",
      body: "Karyokinesis of mitosis has four stages.",
      diagram_data: { type: "bio-mitosis-sequence" },
      table_data: table(["Stage", "Recall answer"], [
        ["Prophase", "Longest phase; chromatin fibres untangle and condense; centrosomes move to opposite poles; Golgi, ER, nucleolus and nuclear envelope disappear by end."],
        ["Metaphase", "Nuclear envelope disintegrates; chromosomes align at equator forming metaphase plate; spindle fibres attach to kinetochores."],
        ["Anaphase", "Shortest phase; centromeres divide longitudinally; daughter chromatids move to opposite poles."],
        ["Telophase", "Chromosomes cluster and uncoil; nuclear envelopes form; nucleolus, Golgi and ER reappear; spindle fibres disappear."],
      ]),
      recall_data: recall("Which is the shortest phase of mitosis?", "Anaphase.", ["Prophase is the longest phase in mitosis."]),
      importance: 5,
      source_page: 41,
      sort_order: 5,
    }),
    card(chapterId, "cytokinesis", {
      title: "Plant vs Animal Cytokinesis",
      card_type: "comparison",
      body: "Cytokinesis divides cytoplasm to form two daughter cells and starts while telophase is in progress.",
      table_data: table(["Feature", "Animal cell", "Plant cell"], [
        ["Mechanism", "Cleavage furrow appears in plasma membrane and deepens to divide cytoplasm.", "Golgi vesicles accumulate at equator, grow outward and meet lateral walls."],
        ["Final structure", "Cytoplasm divides into two.", "Cell-plate forms and later becomes middle lamella."],
        ["Reason for difference", "No cell wall issue stated.", "Different due to presence of cell wall."],
      ]),
      recall_data: recall("What forms during plant cytokinesis?", "Cell-plate.", ["Later, the cell plate becomes the middle lamella.", "Mitochondria and plastids get distributed during cytokinesis."]),
      importance: 5,
      source_page: 42,
      sort_order: 6,
    }),
    card(chapterId, "syncytium", {
      title: "Syncytium",
      card_type: "neet_trap",
      body: "If karyokinesis is not followed by cytokinesis, multinucleate condition arises.",
      recall_data: recall("What condition forms when karyokinesis is not followed by cytokinesis?", "Syncytium.", ["Source example: liquid endosperm in coconut."]),
      importance: 4,
      source_page: 42,
      sort_order: 7,
    }),
    card(chapterId, "significance-mitosis", {
      title: "Significance of Mitosis",
      card_type: "fact",
      body: "Mitosis produces genetically identical diploid daughter cells and maintains chromosome number.",
      table_data: table(["Significance", "Source detail"], [
        ["Genome", "Produces diploid daughter cells with identical genome."],
        ["Chromosome number", "Retains same chromosome number in all somatic cells."],
        ["Growth", "Body growth; meristematic tissues allow continuous plant growth throughout life."],
        ["Ratio", "Restores nucleo-cytoplasmic ratio disturbed by cell growth."],
        ["Repair", "Cell repair and replacement; upper epidermis, lining of gut and blood cells."],
      ]),
      recall_data: recall("How does mitosis help multicellular organisms?", "Body growth, chromosome-number maintenance, nucleo-cytoplasmic ratio restoration, repair and replacement."),
      importance: 5,
      source_page: 42,
      sort_order: 8,
    }),
    card(chapterId, "meiosis-basics", {
      title: "Meiosis Basics",
      card_type: "concept",
      body: "Meiosis is division of diploid germ cells that halves chromosome number and forms haploid daughter cells.",
      table_data: table(["Feature", "Recall answer"], [
        ["Where", "Diploid germ cells during gametogenesis."],
        ["Outcome", "Haploid daughter cells (gametes); four haploid cells at end of meiosis II."],
        ["DNA replication", "One single cycle of DNA replication."],
        ["Divisions", "Two cycles: meiosis I and meiosis II."],
        ["Pairing/recombination", "Pairing of homologous chromosomes and recombination between non-sister chromatids."],
      ]),
      recall_data: recall("How many DNA replications and divisions occur in meiosis?", "One DNA replication and two divisions.", [], [], ["Meiosis has one DNA replication but two divisions."]),
      importance: 5,
      source_page: 42,
      sort_order: 9,
    }),
    card(chapterId, "mitosis-vs-meiosis", {
      title: "Mitosis vs Meiosis",
      card_type: "comparison",
      body: "The source contrasts mitosis as equational somatic division and meiosis as reductional germ-cell division.",
      table_data: table(["Feature", "Mitosis", "Meiosis"], [
        ["Cell type", "Somatic cells.", "Diploid germ cells."],
        ["Chromosome number", "Same in parent and progeny; equational division.", "Reduced by half to haploid daughter cells."],
        ["Divisions", "One division.", "Meiosis I and meiosis II."],
        ["DNA replication", "Before M phase in S phase.", "Single cycle before meiosis I."],
        ["Products", "Two daughter cells.", "Four haploid cells at end of meiosis II."],
        ["Variation", "Identical genome in daughter cells.", "Genetic variation due to crossing over."],
      ]),
      recall_data: recall("Which division reduces chromosome number by half?", "Meiosis.", ["Mitosis is equational division."]),
      importance: 5,
      source_page: 42,
      sort_order: 10,
    }),
    card(chapterId, "prophase-i-substages", {
      title: "Prophase I Substages",
      card_type: "sequence",
      body: "Prophase I is typically longer and more complex and has five substages.",
      diagram_data: { type: "bio-prophase-one" },
      table_data: table(["Substage", "Recall answer"], [
        ["Leptotene", "Chromatin fibres become long slender chromosomes; nucleus enlarges."],
        ["Zygotene", "Chromosomes condense; synapsis begins with synaptonemal complex; homologous pair is bivalent."],
        ["Pachytene", "Longer phase; bivalent chromosomes split into similar chromatids called tetrads; recombination nodules appear and crossing over occurs."],
        ["Diplotene", "Synaptonemal complex dissolves; homologues separate except at chiasmata; can last months/years in oocytes of some vertebrates."],
        ["Diakinesis", "Terminalisation of chiasmata; chromosomes fully condensed; spindle fibres originate; nucleolus and nuclear envelope disappear."],
      ]),
      recall_data: recall("At which Prophase I stage does crossing over occur?", "Pachytene.", ["Recombination nodules appear and crossing over occurs between non-sister chromatids.", "Recombination is completed by the end of pachytene."], [], ["Crossing over occurs during pachytene."]),
      importance: 5,
      source_page: 42,
      sort_order: 11,
    }),
    card(chapterId, "synapsis-bivalent-tetrad-crossing", {
      title: "Synapsis, Bivalent, Tetrad and Crossing Over",
      card_type: "classification",
      body: "Key Prophase I terms are anchored to zygotene and pachytene.",
      table_data: table(["Term", "Recall answer"], [
        ["Synapsis", "Pairing of similar chromosomes during zygotene with synaptonemal complex."],
        ["Bivalent", "Each pair of homologous chromosomes."],
        ["Tetrad", "Bivalent chromosomes split into similar chromatids during pachytene."],
        ["Crossing over", "Exchange of genetic material between non-sister chromatids of two homologous chromosomes in presence of recombinase."],
        ["Chiasmata", "X-shaped sites of crossovers visible when homologues separate in diplotene."],
      ]),
      recall_data: recall("What is crossing over?", "Exchange of genetic material between non-sister chromatids of homologous chromosomes in presence of recombinase."),
      importance: 5,
      source_page: 42,
      sort_order: 12,
    }),
    card(chapterId, "meiosis-i-stages", {
      title: "Meiosis I Stages",
      card_type: "sequence",
      body: "Meiosis I separates homologous chromosomes while sister chromatids remain associated.",
      table_data: table(["Stage", "Recall answer"], [
        ["Prophase I", "Longer and more complex; leptotene, zygotene, pachytene, diplotene and diakinesis."],
        ["Metaphase I", "Spindle formation completed; chromosomes align on equatorial plate; microtubules attach to homologous chromosome pairs."],
        ["Anaphase I", "Homologous chromosomes separate while sister chromatids remain associated at centromeres."],
        ["Telophase I", "Nuclear membrane and nucleolus reappear; two haploid daughter nuclei form, called diad."],
        ["Interkinesis", "Short stage between meiotic divisions; DNA replication does not occur."],
      ]),
      recall_data: recall("In Anaphase I, what separates and what remains associated?", "Homologous chromosomes separate; sister chromatids remain associated at centromeres."),
      importance: 5,
      source_page: 43,
      sort_order: 13,
    }),
    card(chapterId, "meiosis-ii-stages", {
      title: "Meiosis II Stages",
      card_type: "sequence",
      body: "Meiosis II resembles mitosis.",
      diagram_data: { type: "bio-meiosis-flow" },
      table_data: table(["Stage", "Recall answer"], [
        ["Prophase II", "Immediately after cytokinesis; chromosomes compact; nucleolus and nuclear membrane disappear in both nuclei."],
        ["Metaphase II", "Chromosomes align at equator; microtubules attach to kinetochores of sister chromatids."],
        ["Anaphase II", "Centromeres split simultaneously; chromatids move toward opposite poles."],
        ["Telophase II", "Chromosome groups enclosed by nuclear envelope; cytokinesis forms tetrad of cells, i.e., four haploid daughter cells."],
      ]),
      recall_data: recall("Which meiosis stage splits centromeres?", "Anaphase II.", ["It begins with simultaneous splitting of centromere of each chromosome."]),
      importance: 5,
      source_page: 43,
      sort_order: 14,
    }),
    card(chapterId, "significance-meiosis", {
      title: "Significance of Meiosis",
      card_type: "fact",
      body: "Meiosis conserves chromosome number and produces variation.",
      table_data: table(["Significance", "Source detail"], [
        ["Conservation", "Conserves chromosome number of each species."],
        ["Variation", "Causes genetic variation due to crossing over in the population of organisms."],
        ["Evolution", "Genetic variation is important for evolution."],
      ]),
      recall_data: recall("How does meiosis create variation according to the source?", "Due to crossing over.", ["This variation is important for evolution."]),
      importance: 5,
      source_page: 43,
      sort_order: 15,
    }),
  ];
}

export function getBiologyBatch3Chapters() {
  return BIOLOGY_BATCH_3_CHAPTER_DEFINITIONS.map((chapterDef) => ({
    id: chapter(chapterDef.slug),
    subject_id: "neet-biology",
    title: chapterDef.title,
    slug: chapterDef.slug,
    sort_order: chapterDef.sort_order,
  }));
}

export function getBiologyBatch3Cards() {
  return [
    ...structuralCards(chapter("structural-organization-in-animals")),
    ...cellCards(chapter("cells-the-unit-of-life")),
    ...cellCycleCards(chapter("cell-cycle-and-cell-division")),
  ];
}
