export const BIOLOGY_BATCH_10_CHAPTER_DEFINITIONS = [
  { title: "Biotechnology: Principles and Process", slug: "biotechnology-principles-and-process", sort_order: 31, source_page: 128 },
  { title: "Biotechnology and its Applications", slug: "biotechnology-and-its-applications", sort_order: 32, source_page: 132 },
];

const chapter = (slug) => `neet-biology-${slug}`;

function table(columns, rows) {
  return { columns, rows };
}

function recall(question, answer, key_points = [], examples = [], neet_traps = []) {
  return { recall_question: question, reveal_answer: answer, key_points, examples, neet_traps };
}

function card(chapterId, slug, payload) {
  return {
    id: `${chapterId}-${slug}`,
    chapter_id: chapterId,
    formulas: [],
    variables: [],
    conditions: [],
    table_data: null,
    diagram_data: null,
    diagram_svg: null,
    is_active: true,
    ...payload,
  };
}

function principlesCards(chapterId) {
  return [
    card(chapterId, "biotechnology-basics", {
      title: "Biotechnology Basics",
      card_type: "concept",
      body: "Biotechnology uses live organisms or their enzymes for products and processes useful to humans.",
      table_data: table(["Cue", "Source-backed recall"], [
        ["Biotechnology", "Technique of using live organisms or their enzymes for products and processes useful to humans"],
        ["EFB definition", "Integration of natural science and organisms, cells, parts thereof, and molecular analogues for products and services"],
        ["Deals with", "Microbe-mediated processes, in vitro fertilization, synthesis and using of a gene, DNA vaccine preparation and correcting a defective gene"],
      ]),
      recall_data: recall("What does biotechnology use for useful products and processes?", "Live organisms or their enzymes."),
      importance: 5,
      source_page: 128,
      sort_order: 1,
    }),
    card(chapterId, "core-techniques", {
      title: "Core Techniques of Modern Biotechnology",
      card_type: "comparison",
      body: "The source frames modern biotechnology around genetic engineering and bioprocess engineering.",
      table_data: table(["Technique", "Source-backed recall"], [
        ["Genetic engineering", "Genetic material DNA and RNA is chemically altered and introduced into host organisms to change the phenotype"],
        ["Bioprocess engineering", "Maintenance of sterile ambience in chemical engineering processes for growing desired microbe/eukaryotic cell to manufacture antibiotics, vaccines, enzymes etc."],
      ]),
      recall_data: recall("Which biotechnology core technique maintains sterile ambience for product manufacture?", "Bioprocess engineering."),
      importance: 5,
      source_page: 128,
      sort_order: 2,
    }),
    card(chapterId, "genetic-modification-steps", {
      title: "Basic Genetic Modification Steps",
      card_type: "sequence",
      body: "The source lists three basic steps in genetically modifying an organism.",
      table_data: table(["Step", "Source-backed event"], [
        ["1", "Identification of DNA with desirable genes"],
        ["2", "Introduction of the identified DNA into the host using a vector such as plasmid"],
        ["3", "Maintenance of introduced DNA in the host and transfer of DNA to its progeny"],
      ]),
      recall_data: recall("Why does alien DNA need ori or genome integration?", "Without origin of replication it cannot multiply in progeny cells."),
      importance: 5,
      source_page: 128,
      sort_order: 3,
    }),
    card(chapterId, "recombinant-dna-history", {
      title: "First Recombinant DNA",
      card_type: "fact",
      body: "Recombinant DNA technology joins and inserts foreign DNA into a host organism.",
      table_data: table(["Cue", "Source-backed detail"], [
        ["Recombinant DNA technology", "Process of joining and inserting a foreign piece of DNA into a host organism to produce new genetic combinations"],
        ["First rDNA", "Produced by Stanley Cohen and Herbert Boyer in 1972"],
        ["Gene source", "Antibiotic resistance gene from a plasmid of Salmonella typhimurium"],
        ["Host", "Transferred into E. coli, where the gene was expressed and multiplied"],
      ]),
      recall_data: recall("Who produced the first recombinant DNA?", "Stanley Cohen and Herbert Boyer."),
      importance: 5,
      source_page: 128,
      sort_order: 4,
    }),
    card(chapterId, "restriction-enzymes", {
      title: "Restriction Enzymes",
      card_type: "comparison",
      body: "Restriction enzymes are nucleases that cut DNA at specific sites.",
      table_data: table(["Type/cue", "Source-backed recall"], [
        ["Restriction enzymes", "Enzymes that cut DNA at specific sites into fragments"],
        ["Exonucleases", "Remove nucleotides from the ends of DNA"],
        ["Endonucleases", "Cut at specific positions within DNA"],
        ["First restriction endonuclease", "Hind II; recognizes a specific sequence of 6 base pairs"],
        ["Scale", "More than 900 restriction enzymes from over 230 strains of bacteria"],
      ]),
      recall_data: recall("Which restriction enzyme type cuts within DNA?", "Endonuclease.", [], [], ["Exonucleases remove nucleotides from DNA ends."]),
      importance: 5,
      source_page: 128,
      sort_order: 5,
    }),
    card(chapterId, "restriction-enzyme-naming", {
      title: "Restriction Enzyme Naming",
      card_type: "fact",
      body: "Restriction enzyme names indicate the source organism and strain/order details.",
      table_data: table(["Name part", "Source-backed meaning"], [
        ["First letter", "Genus"],
        ["Second two letters", "Species of prokaryotic cell"],
        ["EcoRI", "Comes from E. coli RY 13"],
        ["R", "Strain"],
        ["Roman number", "Order in which enzyme was isolated from that strain"],
      ]),
      recall_data: recall("In EcoRI naming, what does the Roman number indicate?", "Order in which the enzyme was isolated from that strain."),
      importance: 5,
      source_page: 128,
      sort_order: 6,
    }),
    card(chapterId, "ecori-palindrome", {
      title: "EcoRI Palindromic Sequence",
      card_type: "diagram",
      body: "EcoRI recognizes a palindromic nucleotide sequence read in 5' to 3' direction on both strands.",
      diagram_data: { type: "bio-restriction-cut" },
      table_data: table(["Cue", "Source-backed detail"], [
        ["Palindromic sequence", "Base-pair sequence read the same on the two strands in 5' -> 3' and 3' -> 5' directions"],
        ["EcoRI sequence", "5' - GAATTC - 3' / 3' - CTTAAG - 5'"],
        ["Cutting", "Cuts strands a little away from centre of palindrome sites between same two bases on opposite strands"],
        ["Sticky ends", "Single stranded overhanging stretches; form H-bonds with complementary cut counterparts"],
      ]),
      recall_data: recall("What is the EcoRI palindromic sequence shown in the source?", "5' - GAATTC - 3' / 3' - CTTAAG - 5'."),
      importance: 5,
      source_page: 128,
      sort_order: 7,
    }),
    card(chapterId, "ligase-sticky-ends", {
      title: "Sticky Ends and DNA Ligase",
      card_type: "process",
      body: "DNA fragments cut by the same restriction enzyme can be joined by DNA ligase.",
      table_data: table(["Cue", "Source-backed recall"], [
        ["Same enzyme cut", "Resultant DNA fragments have the same kind of sticky ends"],
        ["Sticky-end role", "Facilitates action of DNA ligase"],
        ["DNA ligase", "Joins DNA fragments to create recombinant DNA"],
      ]),
      recall_data: recall("Which enzyme joins DNA fragments during recombinant DNA formation?", "DNA ligase.", [], [], ["Restriction enzymes cut DNA; DNA ligase joins fragments."]),
      importance: 5,
      source_page: 129,
      sort_order: 8,
    }),
    card(chapterId, "cloning-vector-basics", {
      title: "Cloning Vector Basics",
      card_type: "concept",
      body: "A cloning vector carries foreign DNA and replicates inside host cells.",
      table_data: table(["Cue", "Source-backed recall"], [
        ["Cloning vector", "DNA molecule that can carry a foreign DNA segment and replicate inside host cells"],
        ["Examples", "Plasmids and bacteriophages"],
        ["Plasmids", "Autonomously replicating circular extra-chromosomal DNA of bacteria"],
        ["Plasmid copy number", "Some plasmids have 1-2 copies per cell; others have 15-100 copies per cell"],
        ["Bacteriophages", "Have very high copy numbers of genome within bacterial cells"],
      ]),
      recall_data: recall("What is a cloning vector?", "DNA molecule that can carry foreign DNA and replicate inside host cells."),
      importance: 5,
      source_page: 129,
      sort_order: 9,
    }),
    card(chapterId, "vector-features", {
      title: "Vector Components",
      card_type: "comparison",
      body: "A useful cloning vector needs ori, selectable marker and cloning sites.",
      table_data: table(["Feature", "Source-backed function"], [
        ["Origin of replication or ori", "Sequence where replication starts; controls copy number of linked DNA"],
        ["Selectable marker", "Gene that helps select transformants and eliminate non-transformants"],
        ["Cloning sites", "Recognition sites for restriction enzymes"],
        ["Single/few recognition sites", "Needed to link alien DNA without generating several fragments"],
      ]),
      recall_data: recall("What is the role of ori in a cloning vector?", "It is where replication starts and it controls copy number of linked DNA.", [], [], ["ori is not the selectable marker."]),
      importance: 5,
      source_page: 129,
      sort_order: 10,
    }),
    card(chapterId, "pbr322", {
      title: "pBR322 Map Recall",
      card_type: "diagram",
      body: "The source labels pBR322 with ori, rop, antibiotic resistance genes and restriction sites.",
      diagram_data: { type: "bio-pbr322-map" },
      table_data: table(["Label", "Source-backed detail"], [
        ["Restriction sites", "Hind III, EcoR I, BamH I, Sal I, Pvu II, Pst I and Cla I"],
        ["ori", "Origin of replication"],
        ["Antibiotic resistance genes", "ampR and tetR"],
        ["Rop", "Codes for proteins involved in replication of plasmid"],
        ["Example ligation", "Foreign DNA ligated at Bam H I site of tetracycline resistance gene"],
      ]),
      recall_data: recall("Which pBR322 site example inserts foreign DNA into tetracycline resistance gene?", "Bam H I site."),
      importance: 5,
      source_page: 129,
      sort_order: 11,
    }),
    card(chapterId, "insertional-inactivation", {
      title: "Insertional Inactivation",
      card_type: "neet_trap",
      body: "Insertion of foreign DNA within a bacterial gene inactivates that gene.",
      table_data: table(["Cell/plasmid type", "Source-backed selection result"], [
        ["Non-transformants", "No plasmid; not resistant to tetracycline or ampicillin"],
        ["Transformants with non-recombinant plasmid", "Resistant to both tetracycline and ampicillin"],
        ["Transformants with recombinant plasmid", "Resistant only to ampicillin"],
        ["Blue colony alternative", "No insert gives blue coloured colonies with chromogenic substrate"],
        ["Recombinant colonies", "Do not produce colour when beta-galactosidase gene is inactivated"],
      ]),
      recall_data: recall("In the pBR322 example, recombinant plasmids grow on which antibiotic medium only?", "Ampicillin medium only.", [], [], ["Loss of tetracycline resistance marks insertional inactivation here."]),
      importance: 5,
      source_page: 129,
      sort_order: 12,
    }),
    card(chapterId, "plant-animal-vectors", {
      title: "Vectors for Plants and Animals",
      card_type: "comparison",
      body: "Pathogen genetic tools can be transformed into useful vectors.",
      table_data: table(["Vector/pathogen", "Source-backed use"], [
        ["Agrobacterium tumefaciens", "Pathogen of many dicot plants that delivers T-DNA to transform normal plant cells into tumour cells"],
        ["Ti plasmid", "Modified into a non-pathogenic cloning vector that delivers genes of interest into plants"],
        ["Retroviruses", "Transform normal animal cells into cancerous cells; used to deliver desirable genes into animal cells"],
      ]),
      recall_data: recall("Which modified plasmid of Agrobacterium is used as plant cloning vector?", "Ti plasmid."),
      importance: 5,
      source_page: 130,
      sort_order: 13,
    }),
    card(chapterId, "competent-host", {
      title: "Competent Host and Heat Shock",
      card_type: "sequence",
      body: "Bacterial cells are made competent because DNA is hydrophilic and cannot pass through cell membranes.",
      table_data: table(["Step", "Source-backed event"], [
        ["1", "Treat bacterial cells with a specific concentration of divalent cation such as calcium"],
        ["2", "DNA enters bacterium through pores in cell wall"],
        ["3", "Incubate cells with recombinant DNA on ice"],
        ["4", "Place briefly at 42°C for heat shock"],
        ["5", "Put cells back on ice"],
        ["6", "Bacteria take up recombinant DNA"],
      ]),
      recall_data: recall("At what temperature is heat shock shown in the source?", "42°C."),
      importance: 5,
      source_page: 130,
      sort_order: 14,
    }),
    card(chapterId, "dna-entry-methods", {
      title: "DNA Entry Methods",
      card_type: "comparison",
      body: "Alien DNA can enter host cells through competence treatment or direct delivery methods.",
      table_data: table(["Method", "Source-backed recall"], [
        ["Competent bacterial cells", "Divalent cation treatment and heat shock help uptake recombinant DNA"],
        ["Micro-injection", "Recombinant DNA is directly injected into nucleus of an animal cell"],
        ["Biolistics or gene gun", "Cells bombarded with high velocity gold or tungsten micro-particles coated with DNA; suitable for plants"],
        ["Disarmed pathogen vectors", "Infect the cell and transfer recombinant DNA into host; example A. tumefaciens"],
      ]),
      recall_data: recall("Which DNA-entry method uses gold or tungsten particles?", "Biolistics or gene gun."),
      importance: 5,
      source_page: 130,
      sort_order: 15,
    }),
    card(chapterId, "rdna-process", {
      title: "Recombinant DNA Technology Process",
      card_type: "diagram",
      body: "The source lists six process stages from DNA isolation to downstream processing.",
      diagram_data: { type: "bio-rdna-workflow" },
      table_data: table(["Order", "Stage"], [
        ["1", "Isolation of the genetic material (DNA)"],
        ["2", "Cutting of DNA at specific locations"],
        ["3", "Amplification of gene of interest using PCR"],
        ["4", "Insertion of recombinant DNA into host cell"],
        ["5", "Obtaining the foreign gene product"],
        ["6", "Downstream processing"],
      ]),
      recall_data: recall("What comes after cutting DNA at specific locations in the source process?", "Amplification of gene of interest using PCR."),
      importance: 5,
      source_page: 130,
      sort_order: 16,
    }),
    card(chapterId, "dna-isolation", {
      title: "DNA Isolation",
      card_type: "process",
      body: "DNA isolation removes cell barriers, RNA, proteins and other macromolecules before precipitation.",
      table_data: table(["Target", "Source-backed treatment"], [
        ["Bacterial cells", "Lysozyme"],
        ["Plant tissue", "Cellulase"],
        ["Fungus", "Chitinase"],
        ["RNA", "Ribonuclease"],
        ["Proteins", "Protease"],
        ["Purified DNA", "Chilled ethanol precipitates DNA as fine threads"],
      ]),
      recall_data: recall("Which enzyme breaks fungal cell wall during DNA isolation?", "Chitinase."),
      importance: 5,
      source_page: 130,
      sort_order: 17,
    }),
    card(chapterId, "gel-electrophoresis", {
      title: "Agarose Gel Electrophoresis",
      card_type: "diagram",
      body: "Agarose gel electrophoresis separates DNA fragments by size.",
      diagram_data: { type: "bio-gel-electrophoresis" },
      table_data: table(["Cue", "Source-backed recall"], [
        ["DNA charge", "Negatively charged"],
        ["Movement", "Moves towards the anode"],
        ["Separation", "Fragments separated by size through sieving effect of agarose gel"],
        ["Small fragments", "Move farther"],
        ["Agarose source", "Sea weeds"],
        ["Visualization", "Ethidium bromide staining and UV radiation show bright orange bands"],
        ["Elution", "DNA bands cut out from agarose gel"],
      ]),
      recall_data: recall("In agarose gel electrophoresis, DNA moves towards which electrode?", "Anode.", [], [], ["DNA is negatively charged, so it moves towards the anode."]),
      importance: 5,
      source_page: 130,
      sort_order: 18,
    }),
    card(chapterId, "pcr-overview", {
      title: "PCR Overview",
      card_type: "concept",
      body: "PCR synthesizes multiple copies of the gene of interest in vitro.",
      table_data: table(["Cue", "Source-backed recall"], [
        ["Full form", "Polymerase Chain Reaction"],
        ["Definition", "Synthesis of multiple copies of gene of interest in vitro"],
        ["Needs", "Two sets of primers and DNA polymerase"],
        ["Primers", "Small chemically synthesized oligonucleotides complementary to DNA regions"],
        ["Amplification", "DNA segment amplified up to 1 billion copies"],
      ]),
      recall_data: recall("What does PCR amplify?", "Gene of interest."),
      importance: 5,
      source_page: 130,
      sort_order: 19,
    }),
    card(chapterId, "pcr-stages", {
      title: "PCR Stages",
      card_type: "diagram",
      body: "PCR cycles through denaturation, annealing and extension.",
      diagram_data: { type: "bio-pcr-cycle" },
      table_data: table(["Stage", "Source-backed event", "Temperature"], [
        ["Denaturation", "Heating target DNA to separate strands; each strand acts as template", "94°C"],
        ["Annealing", "Joining of two primers at 3' end of DNA templates", "52°C"],
        ["Extension", "Addition of nucleotides to primer using Taq polymerase", "High-temperature active polymerase"],
      ]),
      recall_data: recall("Which thermostable enzyme is used in PCR?", "Taq polymerase.", ["It is isolated from Thermus aquaticus."], [], ["Denaturation separates strands; annealing joins primers."]),
      importance: 5,
      source_page: 130,
      sort_order: 20,
    }),
    card(chapterId, "host-selection-product", {
      title: "Host Transfer, Selection and Product",
      card_type: "process",
      body: "Ligated DNA is introduced into host cells and transformants are selected before recombinant protein production.",
      table_data: table(["Stage", "Source-backed recall"], [
        ["Host transfer", "Ligated DNA introduced into recipient host cell or organism"],
        ["Ampicillin example", "Recombinant DNA bearing ampicillin resistant gene makes E. coli ampicillin-resistant"],
        ["Selection plate", "On ampicillin agar plates only transformants grow; untransformed cells die"],
        ["Recombinant protein", "Protein encoded by foreign gene and expressed in heterologous host"],
        ["Continuous culture", "Used medium drained from one side and fresh medium added from other side to keep cells physiologically active"],
      ]),
      recall_data: recall("What is a recombinant protein?", "Protein encoded by a foreign gene expressed in a heterologous host."),
      importance: 5,
      source_page: 131,
      sort_order: 21,
    }),
    card(chapterId, "bioreactor", {
      title: "Bioreactor",
      card_type: "diagram",
      body: "Bioreactors biologically convert raw materials to products, enzymes etc. using cells.",
      diagram_data: { type: "bio-bioreactor" },
      table_data: table(["Cue", "Source-backed detail"], [
        ["Capacity", "Can process 100-1000 litres of culture"],
        ["Growth conditions", "pH, temperature, substrate, salts, vitamins and oxygen"],
        ["Common type", "Stirred-tank bioreactor"],
        ["Shape", "Usually cylindrical or with a curved base"],
        ["Stirrer role", "Even mixing and oxygen availability"],
        ["Systems", "Agitator, oxygen delivery, foam control, temperature control, pH control and sampling ports"],
      ]),
      recall_data: recall("What is the most common bioreactor type in the source?", "Stirred-tank bioreactor."),
      importance: 5,
      source_page: 131,
      sort_order: 22,
    }),
    card(chapterId, "downstream-processing", {
      title: "Downstream Processing",
      card_type: "process",
      body: "Downstream processing prepares a biosynthetic product for use.",
      table_data: table(["Step/cue", "Source-backed recall"], [
        ["Meaning", "Series of processes after biosynthetic stage"],
        ["Processes", "Separation and purification of products"],
        ["Formulation", "Product formulated with suitable preservatives"],
        ["Testing", "Clinical trials and strict quality control testing"],
      ]),
      recall_data: recall("What two processes are named in downstream processing?", "Separation and purification."),
      importance: 5,
      source_page: 131,
      sort_order: 23,
    }),
  ];
}

function applicationsCards(chapterId) {
  return [
    card(chapterId, "application-areas", {
      title: "Biotechnology Application Areas",
      card_type: "classification",
      body: "Biotechnology has applications in health, agriculture, food, environment and energy.",
      table_data: table(["Cue", "Source-backed recall"], [
        ["Applications", "Biopharmaceuticals, therapeutics, diagnostics, genetically modified crops, processed food, bioremediation, waste treatment and energy production"],
        ["Research area 1", "Providing best catalyst as improved organism, usually microbe or enzyme"],
        ["Research area 2", "Creating optimal conditions through engineering for catalyst to act"],
        ["Research area 3", "Downstream processing technologies to purify protein/organic compound"],
      ]),
      recall_data: recall("What are the three critical biotech research areas centered on?", "Best catalyst, optimal conditions and downstream processing."),
      importance: 5,
      source_page: 132,
      sort_order: 1,
    }),
    card(chapterId, "agriculture-options-gmo", {
      title: "Agriculture Options and GMOs",
      card_type: "comparison",
      body: "The source compares three options for increasing food production and defines GMOs.",
      table_data: table(["Option/cue", "Source-backed recall"], [
        ["Agro-chemical based agriculture", "Uses fertilizers and pesticides; expensive and causes environmental pollution"],
        ["Organic agriculture", "Expensive"],
        ["Genetically engineered crop-based agriculture", "Uses genetically modified crops"],
        ["GMO", "Plants, bacteria, fungi and animals whose genes are altered by manipulation"],
      ]),
      recall_data: recall("What is a GMO in the source?", "Plant, bacterium, fungus or animal whose genes are altered by manipulation."),
      importance: 5,
      source_page: 132,
      sort_order: 2,
    }),
    card(chapterId, "gm-plant-advantages", {
      title: "Genetic Modification in Plants",
      card_type: "classification",
      body: "Genetic modification improves stress tolerance, pest resistance, nutrition and industrial supply.",
      table_data: table(["Advantage", "Source-backed detail"], [
        ["Abiotic stress tolerance", "Cold, drought, salt, heat etc."],
        ["Pest resistance", "Reduces use of chemical pesticides"],
        ["Post-harvest losses", "Reduces post-harvest losses"],
        ["Mineral usage", "Increases efficiency and prevents early exhaustion of soil fertility"],
        ["Nutrition", "Enhances nutritional value; Golden rice is Vitamin A enriched rice"],
        ["Industrial resources", "Tailor-made plants supply starches, fuels, pharmaceuticals etc."],
      ]),
      recall_data: recall("Which GM crop example is Vitamin A enriched?", "Golden rice."),
      importance: 5,
      source_page: 132,
      sort_order: 3,
    }),
    card(chapterId, "bt-crops", {
      title: "Bt Crops and Cry Genes",
      card_type: "comparison",
      body: "Bt toxins are insect-group specific proteins encoded by cry genes.",
      table_data: table(["Cue", "Source-backed detail"], [
        ["Bacterium", "Bacillus thuringiensis"],
        ["Bt toxin", "Insecticidal protein crystal formed during a phase of bacterial growth"],
        ["Insects killed by some strains", "Coleopterans, lepidopterans and dipterans"],
        ["Bt crops listed", "Bt cotton, Bt corn, rice, tomato, potato and soyabean"],
        ["cryIAc and cryIIAb", "Control cotton bollworms"],
        ["cryIAb", "Controls corn borer"],
      ]),
      recall_data: recall("Which cry genes control cotton bollworms in the source?", "cryIAc and cryIIAb."),
      importance: 5,
      source_page: 132,
      sort_order: 4,
    }),
    card(chapterId, "bt-toxin-mechanism", {
      title: "Bt Toxin Mechanism",
      card_type: "diagram",
      body: "Bt toxin is inactive in Bacillus and becomes active in the insect gut.",
      diagram_data: { type: "bio-bt-toxin" },
      table_data: table(["Step", "Source-backed event"], [
        ["1", "Bt toxin exists as inactive protoxin in Bacillus"],
        ["2", "Insect ingests toxin"],
        ["3", "Alkaline gut pH solubilises crystals and activates toxin"],
        ["4", "Toxin binds mid-gut epithelial cells and creates pores"],
        ["5", "Cell swelling and lysis cause insect death"],
      ]),
      recall_data: recall("Why does Bt toxin not kill Bacillus in the source?", "It exists as inactive protoxin in Bacillus."),
      importance: 5,
      source_page: 132,
      sort_order: 5,
    }),
    card(chapterId, "rnai", {
      title: "RNA Interference in Tobacco",
      card_type: "diagram",
      body: "RNAi prevents Meloidogyne incognita survival in transgenic tobacco roots.",
      diagram_data: { type: "bio-rnai-sequence" },
      table_data: table(["Cue", "Source-backed detail"], [
        ["Nematode", "Meloidogyne incognita infects tobacco roots and reduces yield"],
        ["RNAi", "Cellular defense in all eukaryotic organisms"],
        ["Mechanism", "Prevents translation of specific mRNA due to complementary dsRNA"],
        ["Gene introduction", "Nematode-specific genes introduced into host plant using Agrobacterium vectors"],
        ["RNA products", "Sense and anti-sense RNA form double stranded RNA"],
        ["Outcome", "Specific nematode mRNA is silenced; parasite cannot survive in transgenic host"],
      ]),
      recall_data: recall("Which nematode is controlled by RNAi in tobacco?", "Meloidogyne incognita."),
      importance: 5,
      source_page: 132,
      sort_order: 6,
    }),
    card(chapterId, "insulin", {
      title: "Genetically Engineered Insulin",
      card_type: "diagram",
      body: "Human insulin can be produced in bacteria and avoids reactions caused by non-human insulin.",
      diagram_data: { type: "bio-recombinant-insulin" },
      table_data: table(["Cue", "Source-backed recall"], [
        ["Use", "Manage adult-onset diabetes"],
        ["Old source issue", "Insulin from cattle and pigs caused allergy or other reactions to foreign protein"],
        ["Mature insulin", "Two short polypeptide chains, A and B, linked by disulphide bridges"],
        ["Proinsulin", "Pro-hormone with extra C peptide removed during maturation"],
        ["Eli Lilly, 1983", "Prepared DNA sequences for A and B chains, introduced them into E. coli plasmids and combined chains by disulfide bonds"],
        ["Product", "Human insulin, Humulin"],
      ]),
      recall_data: recall("What is removed from proinsulin during maturation?", "C peptide.", [], [], ["C peptide is not part of mature insulin chains A and B."]),
      importance: 5,
      source_page: 132,
      sort_order: 7,
    }),
    card(chapterId, "gene-therapy-ada", {
      title: "ADA Gene Therapy",
      card_type: "diagram",
      body: "Gene therapy corrects a gene defect by inserting genes into a person's cells and tissues.",
      diagram_data: { type: "bio-ada-gene-therapy" },
      table_data: table(["Cue", "Source-backed detail"], [
        ["First clinical gene therapy", "1990, given to a 4-year old girl with ADA deficiency"],
        ["ADA deficiency cause", "Deletion of gene for adenosine deaminase, needed for immune system functioning"],
        ["Not completely curative", "Bone marrow transplantation or enzyme replacement therapy by ADA injection"],
        ["Process", "Collect lymphocytes, grow in culture, introduce functional ADA cDNA using retroviral vector, return cells to patient"],
        ["Repeat need", "Periodically repeated because lymphocytes are not immortal"],
        ["Permanent cure possibility", "Introduce ADA gene from marrow cells into cells at early embryonic stages"],
      ]),
      recall_data: recall("Why must ADA lymphocyte gene therapy be repeated?", "Lymphocytes are not immortal."),
      importance: 5,
      source_page: 133,
      sort_order: 8,
    }),
    card(chapterId, "molecular-diagnosis", {
      title: "Molecular Diagnosis",
      card_type: "comparison",
      body: "PCR and ELISA enable earlier disease diagnosis than conventional serum and urine analysis.",
      table_data: table(["Technique", "Source-backed use/principle"], [
        ["PCR", "Detects very low concentration of bacteria or virus by amplification of nucleic acid"],
        ["PCR uses", "Detect HIV in suspected patients, detect gene mutations in suspected cancer patients, identify genetic disorders"],
        ["Probe hybridisation", "Radioactive single stranded DNA or RNA probe hybridizes to complementary DNA; mutated clone will not appear on photographic film"],
        ["ELISA", "Based on antigen-antibody interaction"],
        ["ELISA detection", "Detects antigens or antibodies synthesized against pathogen"],
      ]),
      recall_data: recall("Which molecular diagnosis method is based on antigen-antibody interaction?", "ELISA."),
      importance: 5,
      source_page: 133,
      sort_order: 9,
    }),
    card(chapterId, "transgenic-animals", {
      title: "Transgenic Animals",
      card_type: "classification",
      body: "Transgenic animals have genomes altered by introduction of a foreign gene.",
      table_data: table(["Use", "Source-backed example/detail"], [
        ["Examples", "Transgenic rats, rabbits, pigs, sheep, cows and fish"],
        ["Frequency", "Over 95% of transgenic animals are mice"],
        ["Normal physiology/development", "Study insulin-like growth factor by introducing genes that alter its formation"],
        ["Disease models", "Cancer, cystic fibrosis, rheumatoid arthritis and Alzheimer's"],
        ["Biological products", "Human protein alpha-1-antitrypsin for emphysema"],
        ["Vaccine safety", "Transgenic mice used to test polio vaccine safety"],
        ["Toxicity testing", "Animals made more sensitive to toxic substances for immediate results"],
      ]),
      recall_data: recall("Over 95% of transgenic animals are which animal?", "Mice."),
      importance: 5,
      source_page: 133,
      sort_order: 10,
    }),
    card(chapterId, "rosie", {
      title: "Rosie the Transgenic Cow",
      card_type: "fact",
      body: "Rosie produced human protein-enriched milk.",
      table_data: table(["Cue", "Source-backed detail"], [
        ["Year", "1997"],
        ["Identity", "First transgenic cow"],
        ["Milk", "Human protein-enriched milk, 2.4 gm per litre"],
        ["Protein", "Human alpha-lactalbumin"],
        ["Claim", "Nutritionally more balanced product for human babies than natural cow-milk"],
      ]),
      recall_data: recall("Which protein did Rosie's milk contain?", "Human alpha-lactalbumin."),
      importance: 5,
      source_page: 133,
      sort_order: 11,
    }),
    card(chapterId, "ethical-issues-geac", {
      title: "GEAC and GM Safety",
      card_type: "fact",
      body: "Genetic modification may cause unpredictable results, so GM research and organisms require safety decisions.",
      table_data: table(["Cue", "Source-backed detail"], [
        ["Problem", "Genetic modification may cause unpredictable results"],
        ["Organization", "GEAC"],
        ["Expansion", "Genetic Engineering Approval Committee"],
        ["Role", "Decisions about validity of GM research and safety of GM-organisms for public services"],
      ]),
      recall_data: recall("Expand GEAC as written in the source.", "Genetic Engineering Approval Committee."),
      importance: 5,
      source_page: 133,
      sort_order: 12,
    }),
    card(chapterId, "biopiracy", {
      title: "Biopiracy",
      card_type: "concept",
      body: "Biopiracy is unauthorized use of bio-resources by companies or organizations.",
      table_data: table(["Cue", "Source-backed detail"], [
        ["Biopiracy", "Use of bio-resources by multinational companies and other organizations without proper authorization from countries and people concerned"],
        ["Examples of resources", "Basmati rice, herbal medicines such as turmeric and neem"],
        ["Basmati varieties", "India has 27 varieties of Basmati"],
        ["Patent event", "In 1997, an American company got patent rights on Basmati rice through US Patent and Trademark Office"],
        ["Claim", "New variety was derived from Indian farmer's varieties crossed with semi-dwarf varieties"],
      ]),
      recall_data: recall("How many Basmati varieties does India have according to the source?", "27 varieties."),
      importance: 5,
      source_page: 133,
      sort_order: 13,
    }),
    card(chapterId, "biotech-traps", {
      title: "Biotechnology NEET Traps",
      card_type: "neet_trap",
      body: "Common Biotechnology traps involve confusing organism, gene, toxin, enzyme and product.",
      table_data: table(["Trap pair", "Source-backed distinction"], [
        ["Bt bacterium vs Bt genes", "Bacillus thuringiensis is the bacterium; cry genes code Bt toxins"],
        ["Protoxin vs active toxin", "Bt toxin exists as inactive protoxin in Bacillus; alkaline insect gut activates it"],
        ["PCR vs ELISA", "PCR amplifies nucleic acid; ELISA is antigen-antibody interaction"],
        ["Proinsulin vs insulin", "Proinsulin has C peptide; mature insulin has A and B chains linked by disulphide bridges"],
        ["GEAC role", "Approves/safety-validates GM research and organisms; it is not a cloning vector"],
      ]),
      recall_data: recall("Which method detects low pathogen concentration by nucleic-acid amplification?", "PCR.", [], [], ["ELISA is based on antigen-antibody interaction."]),
      importance: 5,
      source_page: 132,
      sort_order: 14,
    }),
  ];
}

const biologyBatch10CardsBySlug = {
  "biotechnology-principles-and-process": principlesCards,
  "biotechnology-and-its-applications": applicationsCards,
};

export function getBiologyBatch10Chapters() {
  return BIOLOGY_BATCH_10_CHAPTER_DEFINITIONS.map((item) => ({
    id: chapter(item.slug),
    subject_id: "neet-biology",
    title: item.title,
    slug: item.slug,
    sort_order: item.sort_order,
    source_page: item.source_page,
  }));
}

export function getBiologyBatch10Cards() {
  return BIOLOGY_BATCH_10_CHAPTER_DEFINITIONS.flatMap((item) => biologyBatch10CardsBySlug[item.slug](chapter(item.slug)));
}
