export const BIOLOGY_BATCH_4_CHAPTER_DEFINITIONS = [
  { title: "Transport in Plants", slug: "transportation-in-plants", sort_order: 10, source_page: 42 },
  { title: "Minerals Nutrition", slug: "minerals-nutrition", sort_order: 11, source_page: 47 },
  { title: "Photosynthesis", slug: "photosynthesis", sort_order: 12, source_page: 51 },
  { title: "Respiration in Plants", slug: "respiration-in-plants", sort_order: 13, source_page: 56 },
  { title: "Plant Growth and Development", slug: "plant-growth-and-development", sort_order: 14, source_page: 60 },
];

const chapter = (slug) => `neet-biology-${slug}`;

function table(columns, rows) {
  return { columns, rows };
}

function sections(items) {
  return { sections: items };
}

function recall(question, answer, key_points = [], examples = [], neet_traps = []) {
  return { recall_question: question, reveal_answer: answer, key_points, examples, neet_traps };
}

function card(chapterId, slug, payload) {
  return {
    id: `${chapterId}-${slug}`,
    chapter_id: chapterId,
    formulas: [],
    variables: [],
    conditions: [],
    table_data: null,
    diagram_data: null,
    diagram_svg: null,
    is_active: true,
    ...payload,
  };
}

function transportationCards(chapterId) {
  return [
    card(chapterId, "direction-of-transport", {
      title: "Direction of Transport in Plants",
      card_type: "comparison",
      body: "Plants move water, minerals, organic nutrients and growth regulators over long distances without an animal-like circulatory system.",
      table_data: table(["Direction", "Source-backed recall"], [
        ["Unidirectional", "Water and minerals move in xylem from roots to stems and leaves."],
        ["Multidirectional", "Photosynthates and mineral nutrients are transported in different directions."],
        ["Polarized or unidirectional", "Plant hormones and chemical stimuli may move from where they are synthesised to other parts."],
      ]),
      recall_data: recall("Which plant transport is always upward in the source?", "Xylem movement is always upwards and unidirectional."),
      importance: 4,
      source_page: 42,
      sort_order: 1,
    }),
    card(chapterId, "diffusion", {
      title: "Diffusion",
      card_type: "concept",
      body: "Diffusion is the slow movement of gases, liquids and solutes from higher concentration to lower concentration without energy expenditure.",
      table_data: table(["Recall cue", "Source detail"], [
        ["Living system", "It is not dependent on a living system."],
        ["Plant body", "It is the only means for gaseous movement in the plant body."],
        ["Best use", "Cell-to-cell, short distances, or from one part of a cell to another."],
      ]),
      recall_data: recall("What is the only means for gaseous movement in the plant body?", "Diffusion.", ["It does not require energy.", "It is slow and short-distance."]),
      importance: 5,
      source_page: 42,
      sort_order: 2,
    }),
    card(chapterId, "diffusion-rate-factors", {
      title: "Factors Affecting Diffusion Rate",
      card_type: "fact",
      body: "Diffusion rate changes with gradient, membrane and physical properties.",
      table_data: table(["Factor", "Source-backed cue"], [
        ["Concentration gradient", "Diffusion follows the gradient."],
        ["Membrane permeability", "Permeability affects movement."],
        ["Temperature and pressure", "Both affect diffusion rates."],
        ["Size or density", "Smaller substances diffuse faster."],
        ["Solubility in lipids", "Lipid-soluble substances diffuse through the membrane faster."],
      ]),
      recall_data: recall("Which substances diffuse through membranes faster according to the source?", "Substances soluble in lipids."),
      importance: 4,
      source_page: 42,
      sort_order: 3,
    }),
    card(chapterId, "facilitated-diffusion", {
      title: "Facilitated Diffusion",
      card_type: "concept",
      body: "Facilitated diffusion moves hydrophilic substances with membrane protein channels and without expenditure of energy.",
      table_data: table(["Feature", "Source-backed recall"], [
        ["Gradient", "Needs a concentration gradient."],
        ["Specificity", "Very specific; cell selects substances for uptake."],
        ["Saturation", "Transport reaches a maximum when all protein transporters are used."],
        ["Inhibitors", "Sensitive to inhibitors that react with protein side chains."],
        ["Porins", "Huge pores in outer membranes of plastids, mitochondria & some bacteria."],
      ]),
      recall_data: recall("Does facilitated diffusion require ATP?", "No.", ["It requires membrane proteins.", "It is downhill and saturable."]),
      importance: 5,
      source_page: 42,
      sort_order: 4,
    }),
    card(chapterId, "uniport-symport-antiport", {
      title: "Uniport, Symport and Antiport",
      card_type: "classification",
      body: "Carrier proteins move molecules singly, together, or in opposite directions.",
      table_data: table(["Carrier mode", "Recall answer"], [
        ["Uniport", "A molecule alone moves across a membrane through a transport or carrier protein."],
        ["Symport", "Two molecules together cross the membrane in the same direction."],
        ["Antiport", "Two molecules move in opposite directions."],
      ]),
      recall_data: recall("Which carrier mode moves two molecules in opposite directions?", "Antiport."),
      importance: 4,
      source_page: 42,
      sort_order: 5,
    }),
    card(chapterId, "simple-facilitated-active-comparison", {
      title: "Simple Diffusion vs Facilitated Transport vs Active Transport",
      card_type: "comparison",
      body: "The source compares the three transport processes by protein use, selectivity, saturation, uphill movement and ATP need.",
      table_data: table(["Property", "Simple diffusion", "Facilitated transport", "Active transport"], [
        ["Requires special membrane proteins", "No", "Yes", "Yes"],
        ["Highly selective", "No", "Yes", "Yes"],
        ["Transport saturates", "No", "Yes", "Yes"],
        ["Uphill transport", "No", "No", "Yes"],
        ["Requires ATP energy", "No", "No", "Yes"],
      ]),
      recall_data: recall("Which transport process is uphill and ATP-dependent?", "Active transport.", [], [], ["Facilitated transport is selective and saturable, but not uphill."]),
      importance: 5,
      source_page: 42,
      sort_order: 6,
    }),
    card(chapterId, "water-potential", {
      title: "Water Potential",
      card_type: "fact",
      body: "Water potential (Ψw) is the potential energy of water and measures the ability of water molecules to move freely.",
      formulas: [{ label: "Water potential relationship", latex: "\\Psi_w = \\Psi_s + \\Psi_p" }],
      table_data: table(["Term", "Source-backed meaning"], [
        ["Ψw", "Water potential; pure water at standard temperature and no pressure is zero."],
        ["Ψs", "Solute potential or osmotic potential; always negative."],
        ["Ψp", "Pressure potential; usually positive, though tension in xylem is negative."],
        ["At atmospheric pressure", "Ψw = Ψs"],
      ]),
      recall_data: recall("What is the source equation for water potential?", "Ψw = Ψs + Ψp", ["Ψs is always negative.", "Pressure potential is usually positive."]),
      importance: 5,
      source_page: 43,
      sort_order: 7,
    }),
    card(chapterId, "osmosis", {
      title: "Osmosis",
      card_type: "process",
      body: "Osmosis is spontaneous diffusion of water across a differentially- or semi-permeable membrane.",
      table_data: table(["Recall cue", "Source-backed detail"], [
        ["Membranes", "Cell membrane and tonoplast determine movement; cell wall is freely permeable."],
        ["Direction/rate", "Depends on pressure gradient and concentration gradient."],
        ["Movement", "Water moves from higher chemical potential to lower chemical potential until equilibrium."],
        ["Osmotic pressure", "Pressure required to prevent water from diffusing."],
        ["Sign", "Osmotic pressure is positive; osmotic potential is negative."],
      ]),
      recall_data: recall("How is osmotic pressure related to osmotic potential in the source?", "They are numerically equivalent, but the sign is opposite.", [], [], ["Osmotic pressure is positive while osmotic potential is negative."]),
      importance: 5,
      source_page: 43,
      sort_order: 8,
    }),
    card(chapterId, "plasmolysis-tonicity", {
      title: "Plasmolysis and Tonicity",
      card_type: "comparison",
      body: "Tonicity determines whether water enters, leaves, or shows no net flow in plant cells.",
      table_data: table(["External solution", "Water movement / cell state"], [
        ["Isotonic", "No net water flow; cells are flaccid."],
        ["Hypotonic", "Water enters; cells swell and become turgid."],
        ["Hypertonic", "Water moves out; cell shrinks and becomes plasmolysed."],
      ]),
      recall_data: recall("In which external solution does plasmolysis occur?", "Hypertonic solution.", ["Water is first lost from the cytoplasm and then from the vacuole.", "Plasmolysis is usually reversible."]),
      importance: 5,
      source_page: 43,
      sort_order: 9,
    }),
    card(chapterId, "imbibition", {
      title: "Imbibition",
      card_type: "concept",
      body: "Imbibition is a type of diffusion in which water is absorbed by solids (colloids), causing them to increase in volume.",
      table_data: table(["Recall cue", "Source detail"], [
        ["Examples", "Absorption of water by seeds and dry wood."],
        ["Force", "Swelling pressure of wood can split rocks."],
        ["Seedlings", "Seedlings emerge out of soil due to imbibition pressure."],
        ["Requirements", "Concentration gradient, water potential gradient and affinity between adsorbent and liquid."],
      ]),
      recall_data: recall("What pressure helps seedlings emerge out of the soil?", "Imbibition pressure."),
      importance: 4,
      source_page: 44,
      sort_order: 10,
    }),
    card(chapterId, "long-distance-transport", {
      title: "Long-Distance Transport and Mass Flow",
      card_type: "concept",
      body: "Long-distance transport moves substances faster than diffusion by bulk flow.",
      table_data: table(["Term", "Source-backed recall"], [
        ["Diffusion example", "Movement across a typical plant cell (about 50 µm) takes about 2.5 s."],
        ["Mass (bulk) flow", "Movement of substances en masse due to pressure differences."],
        ["Positive gradient", "Like a garden hose."],
        ["Negative gradient", "Like suction through a straw."],
        ["Translocation", "Bulk movement through conducting tissues, xylem and phloem."],
      ]),
      recall_data: recall("What is translocation in this source?", "Bulk movement of substances in long distance through conducting tissues, xylem and phloem."),
      importance: 4,
      source_page: 44,
      sort_order: 11,
    }),
    card(chapterId, "apoplast-vs-symplast", {
      title: "Apoplast vs Symplast",
      card_type: "comparison",
      body: "Water absorbed by root hairs moves deeper through apoplast and symplast pathways.",
      diagram_data: { type: "bio-apoplast-symplast" },
      table_data: table(["Pathway", "Source-backed recall"], [
        ["Apoplast", "Adjacent cell walls and intercellular spaces; does not cross cell membrane; dependent on gradient and mass flow."],
        ["Symplast", "Interconnected protoplasts; water travels through cytoplasm and plasmodesmata; slower because it enters through cell membrane."],
        ["Endodermis", "Casparian strip makes endodermis impervious, directing water to non-suberised wall regions and symplast."],
        ["Final entry", "Ultimately symplastic in endodermis; the only way water and solutes enter the vascular cylinder."],
      ]),
      recall_data: recall("Why is the symplast required at the endodermis?", "The Casparian strip makes the endodermis impervious, so water must pass through the symplast to enter the vascular cylinder.", [], [], ["Apoplast movement does not cross the cell membrane until the endodermal barrier."]),
      importance: 5,
      source_page: 44,
      sort_order: 12,
    }),
    card(chapterId, "mycorrhiza", {
      title: "Mycorrhiza",
      card_type: "examples",
      body: "Mycorrhiza is a symbiotic association of a fungus with a root system.",
      table_data: table(["Partner", "Source-backed contribution"], [
        ["Fungal hyphae", "Absorb mineral ions and water from soil."],
        ["Roots", "Provide sugars and N compounds to the mycorrhiza."],
        ["Source example", "Pinus seeds cannot germinate and establish without mycorrhizae."],
      ]),
      recall_data: recall("Which source example cannot germinate and establish without mycorrhizae?", "Pinus seeds."),
      importance: 4,
      source_page: 44,
      sort_order: 13,
    }),
    card(chapterId, "root-pressure-guttation", {
      title: "Root Pressure and Guttation",
      card_type: "comparison",
      body: "Root pressure is a positive xylem pressure generated when ions are actively transported into root vascular tissues and water follows.",
      table_data: table(["Term", "Source-backed recall"], [
        ["Root pressure", "Helps push water to small heights in the stem; modest push only, no major role in tall trees."],
        ["Experiment", "Cut soft stem near the base early morning with high atmospheric moisture; drops ooze due to positive root pressure."],
        ["Guttation", "Liquid-phase water loss from special vein openings near tips of grass blades and leaves of many herbaceous parts."],
        ["Role", "Re-establishes continuous water chains in xylem that break under transpiration tensions."],
      ]),
      recall_data: recall("Does root pressure explain water movement in tall trees?", "No. It provides only a modest push and has no major role in water movement up tall trees.", [], [], ["Most plants move most water by transpiration pull."]),
      importance: 5,
      source_page: 45,
      sort_order: 14,
    }),
    card(chapterId, "transpiration-pull", {
      title: "Transpiration Pull",
      card_type: "process",
      body: "Most water transport occurs by transpiration pull, also called the cohesion-tension-transpiration pull model.",
      diagram_data: { type: "bio-transpiration-pull" },
      table_data: table(["Step", "Source-backed process"], [
        ["Evaporation", "Water evaporates through stomata from a thin film over leaf cells."],
        ["Pull", "Evaporation pulls water into the leaf from xylem."],
        ["Water properties", "Cohesion, adhesion and surface tension give high tensile strength and capillarity."],
        ["Column height", "Generated forces can lift a xylem-sized column over 130 m high."],
      ]),
      recall_data: recall("Which model explains the driving force of transpiration pull?", "Cohesion-tension-transpiration pull model."),
      importance: 5,
      source_page: 45,
      sort_order: 15,
    }),
    card(chapterId, "stomatal-transpiration", {
      title: "Stomatal Transpiration",
      card_type: "concept",
      body: "Transpiration is evaporative loss of water through stomata in leaves.",
      table_data: table(["Recall cue", "Source-backed answer"], [
        ["Water use", "Less than 1% of water reaching leaves is used in photosynthesis and plant growth; the rest is lost by transpiration."],
        ["Study aid", "Cobalt chloride paper turns colour on absorbing water."],
        ["Timing", "Stomata are open in the day time and close during night."],
        ["Guard cells", "Opening and closing are due to change in turgidity of guard cells."],
        ["Distribution", "Usually lower surface of a dicot leaf has more stomata; monocot leaves have about equal on both surfaces."],
      ]),
      recall_data: recall("Which cells control stomatal opening and closing?", "Guard cells.", ["Their turgidity changes the stomatal aperture."]),
      importance: 5,
      source_page: 45,
      sort_order: 16,
    }),
    card(chapterId, "factors-and-uses-of-transpiration", {
      title: "Factors and Uses of Transpiration",
      card_type: "classification",
      body: "Transpiration is affected by external factors and plant factors, and it supports transport and cooling.",
      table_data: sections([
        {
          title: "Factors affecting transpiration",
          columns: ["Factor group", "Source details"],
          rows: [["External factors", "Temperature, light, humidity, wind etc."], ["Plant factors", "Number & distribution of stomata, number of stomata open, water status of plant, canopy structure etc."]],
        },
        {
          title: "Uses of transpiration",
          columns: ["Use", "Source-backed cue"],
          rows: [["Transport", "Creates transpiration pull for absorption and transport."], ["Photosynthesis", "Supplies water for photosynthesis."], ["Minerals", "Transports minerals from soil to all parts of the plant."], ["Cooling", "Cools leaf surfaces, sometimes 10-15°, by evaporation."], ["Turgidity", "Maintains shape & structure by keeping cells turgid."]],
        },
      ]),
      recall_data: recall("Name two plant factors affecting transpiration.", "Number/distribution of stomata and water status of the plant.", ["Canopy structure and number of open stomata are also listed."]),
      importance: 5,
      source_page: 45,
      sort_order: 17,
    }),
    card(chapterId, "mineral-uptake-and-xylem", {
      title: "Mineral Uptake and Xylem Transport",
      card_type: "process",
      body: "Most minerals are actively absorbed by roots because ions cannot move across cell membranes and their soil concentration is lower than in the root.",
      table_data: table(["Step / cue", "Source-backed detail"], [
        ["Root hair proteins", "Specific membrane proteins actively pump ions from soil into epidermal cells."],
        ["Endodermis", "Transport proteins control quantity and type of solutes that reach the xylem."],
        ["Suberin", "Allows active one-way transport of ions."],
        ["Translocation", "Mineral salts move through xylem along with the ascending stream of water."],
        ["Chief sinks", "Apical/lateral meristems, young leaves, developing flowers/fruits/seeds and storage organs."],
      ]),
      recall_data: recall("Why are most minerals actively absorbed by roots?", "Because ions cannot move across cell membranes and mineral concentration in soil is lower than that in the root."),
      importance: 5,
      source_page: 46,
      sort_order: 18,
    }),
    card(chapterId, "xylem-phloem-transport", {
      title: "Xylem vs Phloem Transport",
      card_type: "comparison",
      body: "Xylem transport and phloem transport differ in direction and transported material, but there is exchange between them.",
      table_data: table(["Feature", "Xylem", "Phloem"], [
        ["Main material", "Water and mineral salts in ascending stream.", "Food, primarily sucrose, plus other sugars, hormones and amino acids."],
        ["Direction", "Always upwards, unidirectional.", "Upwards or downwards, bidirectional."],
        ["Organic/inorganic trap", "Cannot clearly say xylem transports only inorganic nutrients.", "Cannot clearly say phloem transports only organic materials."],
      ]),
      recall_data: recall("Why is it unsafe to say xylem only inorganic and phloem only organic?", "The source states there is exchange of materials between xylem and phloem, with some P and S carried as organic compounds and nitrogen mainly in organic forms."),
      importance: 5,
      source_page: 46,
      sort_order: 19,
    }),
    card(chapterId, "pressure-flow-hypothesis", {
      title: "Pressure Flow Hypothesis",
      card_type: "process",
      body: "The pressure flow or mass flow hypothesis explains translocation of sugar through phloem.",
      diagram_data: { type: "bio-source-sink-flow" },
      table_data: table(["Step", "Source-backed process"], [
        ["Source", "Glucose prepared by photosynthesis is converted to sucrose."],
        ["Loading", "Sucrose moves into companion cells and then sieve tube by active transport."],
        ["Water entry", "Phloem becomes hypertonic; water from adjacent xylem moves in by osmosis."],
        ["Flow", "Hydrostatic/osmotic pressure builds and sap moves to areas of lower osmotic pressure."],
        ["Sink", "Sucrose actively moves into sink cells and is converted to energy, starch, or cellulose."],
        ["Water exit", "As sugar is removed, osmotic pressure decreases and water moves out of phloem."],
      ]),
      recall_data: recall("What happens to water when sucrose is loaded into the phloem sieve tube?", "Water from adjacent xylem moves into the phloem by osmosis because phloem becomes hypertonic."),
      importance: 5,
      source_page: 46,
      sort_order: 20,
    }),
    card(chapterId, "girdling-experiment", {
      title: "Girdling Experiment",
      card_type: "neet_trap",
      body: "Removing a ring of bark including phloem from a tree trunk makes the bark above the ring swollen after a few weeks.",
      table_data: table(["Observation", "Inference"], [
        ["Bark above ring swells", "Downward food movement is absent."],
        ["Source conclusion", "Phloem is responsible for translocation of food and transport takes place towards the roots."],
      ]),
      recall_data: recall("What does the girdling experiment identify?", "The tissue that transports food: phloem.", [], [], ["Swelling above the ring is due to absence of downward food movement."]),
      importance: 5,
      source_page: 46,
      sort_order: 21,
    }),
  ];
}

function mineralsCards(chapterId) {
  return [
    card(chapterId, "hydroponics", {
      title: "Hydroponics",
      card_type: "concept",
      body: "Hydroponics is the technique of growing plants in a defined nutrient solution without soil.",
      table_data: table(["Recall cue", "Source-backed detail"], [
        ["Scientist", "Demonstrated by Julius von Sachs (Germany, 1860)."],
        ["Setup", "Nutrient solution is aerated for optimum growth."],
        ["Use in study", "Identify essential elements and deficiency symptoms by adding, removing or varying an element."],
        ["Commercial examples", "Tomato, seedless cucumber & lettuce."],
      ]),
      recall_data: recall("Who demonstrated hydroponics in the source?", "Julius von Sachs (Germany, 1860).", [], ["Tomato", "Seedless cucumber", "Lettuce"]),
      importance: 5,
      source_page: 47,
      sort_order: 1,
    }),
    card(chapterId, "essentiality-criteria", {
      title: "Criteria for Essentiality",
      card_type: "classification",
      body: "Only 17 elements are absolutely essential for plant growth and metabolism.",
      table_data: table(["Criterion", "Source-backed recall"], [
        ["Growth and reproduction", "Needed for normal growth and reproduction; without it plants do not complete life cycle or set seeds."],
        ["Specific requirement", "Deficiency cannot be met by another element."],
        ["Direct metabolism", "Element must be directly involved in plant metabolism."],
      ]),
      recall_data: recall("How many elements are absolutely essential for plant growth and metabolism in this source?", "17 elements."),
      importance: 5,
      source_page: 47,
      sort_order: 2,
    }),
    card(chapterId, "macro-vs-micro-elements", {
      title: "Macro vs Micro Nutrients",
      card_type: "comparison",
      body: "Essential elements are classified by amount present in plant tissues.",
      table_data: table(["Group", "Amount", "Elements in source"], [
        ["Macronutrients", "Large amounts; more than 10 mmole Kg−1 of dry matter.", "C, H, O, N, P, S, K, Ca, Mg"],
        ["Micronutrients", "Very small amounts; less than 10 mmole Kg−1 of dry matter.", "Fe, Mn, Cu, Mo, Zn, B, Cl, Ni"],
        ["Higher-plant additional needs", "Listed separately in source.", "Sodium, silicon, cobalt, selenium etc."],
      ]),
      recall_data: recall("What threshold separates macro- and micronutrients in the source?", "Macronutrients are more than 10 mmole Kg−1 dry matter; micronutrients are less than 10 mmole Kg−1 dry matter.", [], [], ["Do not treat sodium, silicon, cobalt and selenium as the listed 17 essential elements here."]),
      importance: 5,
      source_page: 47,
      sort_order: 3,
    }),
    card(chapterId, "functions-of-minerals-categories", {
      title: "Four Function Groups of Essential Elements",
      card_type: "classification",
      body: "The source groups essential element functions into structural, energy-related, enzyme-related and osmotic roles.",
      table_data: table(["Function group", "Source examples"], [
        ["Components of biomolecules & structural elements", "C, H, O, N"],
        ["Components of energy-related compounds", "Mg in chlorophyll and phosphorus in ATP."],
        ["Activate or inhibit enzymes", "Mg2+ for RuBisCO & PEP carboxylase; Zn2+ for alcohol dehydrogenase; Mo of nitrogenase."],
        ["Alter osmotic potential", "Potassium helps in opening & closing of stomata."],
      ]),
      recall_data: recall("Which element example alters osmotic potential of a cell?", "Potassium, in opening and closing of stomata."),
      importance: 5,
      source_page: 47,
      sort_order: 4,
    }),
    card(chapterId, "element-function-table", {
      title: "Element Function Recall Table",
      card_type: "table",
      body: "Major roles are taken only from the source element descriptions.",
      table_data: table(["Element", "Major function", "Deficiency symptom stated here"], [
        ["N", "Major constituent of amino acids, proteins, nucleic acids, chlorophyll, vitamins and hormones.", "Chlorosis; inhibits cell division; delays flowering."],
        ["P", "Constituent of cell membranes, certain proteins, all nucleic acids and nucleotides; required for phosphorylation reactions.", ""],
        ["K", "Anion-cation balance, protein synthesis, stomatal opening/closing, enzyme activation and cell turgidity.", "Chlorosis; necrosis."],
        ["Ca", "Cell wall synthesis, calcium pectate in middle lamella, mitotic spindle, membrane function and enzyme activation.", "Necrosis."],
        ["Mg", "Activates respiration/photosynthesis enzymes, DNA/RNA synthesis, chlorophyll ring and ribosome structure.", "Chlorosis; necrosis."],
        ["S", "Cysteine, methionine, coenzymes, vitamins and ferredoxin.", "Chlorosis; inhibits cell division; delays flowering."],
        ["Fe", "Electron transfer proteins; activates catalase; essential for chlorophyll formation.", "Chlorosis."],
        ["Mn", "Enzyme activation; best-defined function is water splitting to liberate O2 in photosynthesis.", "Chlorosis."],
        ["Zn", "Activates enzymes especially carboxylases; needed in auxin synthesis.", "Chlorosis."],
        ["Cu", "Metabolism and redox enzymes.", "Necrosis."],
        ["B", "Ca2+ uptake/use, membrane function, pollen germination, cell elongation/differentiation and carbohydrate translocation.", ""],
        ["Mo", "Component of nitrogenase and nitrate reductase; nitrogen metabolism.", "Chlorosis; inhibits cell division; delays flowering."],
        ["Cl", "Solute concentration, anion-cation balance and water-splitting reaction leading to oxygen evolution.", ""],
      ]),
      recall_data: recall("Which element has the best-defined function in water splitting to liberate O2?", "Manganese."),
      importance: 5,
      source_page: 48,
      sort_order: 5,
    }),
    card(chapterId, "deficiency-symptoms", {
      title: "Deficiency Symptoms",
      card_type: "classification",
      body: "Deficiency symptoms are morphological changes due to deficiency or absence of an element.",
      table_data: table(["Symptom / term", "Source-backed detail"], [
        ["Critical concentration", "Concentration below which plant growth is retarded."],
        ["Mobile elements", "Symptoms first appear in older tissues; examples N, K, Mg."],
        ["Immobile elements", "Symptoms first appear in young tissues; examples S and Ca."],
        ["Chlorosis", "Loss of chlorophyll leading to yellowing in leaves."],
        ["Necrosis", "Death of tissue, particularly leaf tissue."],
        ["Other symptoms", "Stunted growth, premature fall of leaves & buds, inhibition of cell division."],
      ]),
      recall_data: recall("Where do deficiency symptoms first appear for mobile elements?", "Older tissues.", ["N, K and Mg are source examples."], [], ["S and Ca are structural components and symptoms appear first in young tissues."]),
      importance: 5,
      source_page: 48,
      sort_order: 6,
    }),
    card(chapterId, "chlorosis-necrosis-elements", {
      title: "Chlorosis vs Necrosis Element Traps",
      card_type: "neet_trap",
      body: "The source lists overlapping deficiency symptoms, so the whole symptom pattern must be studied.",
      table_data: table(["Symptom", "Due to deficiency of"], [
        ["Chlorosis", "N, K, Mg, S, Fe, Mn, Zn and Mo"],
        ["Necrosis", "Ca, Mg, Cu and K"],
        ["Inhibition of cell division", "Low concentration of N, K, S and Mo"],
        ["Delayed flowering", "Low concentration of N, S and Mo"],
      ]),
      recall_data: recall("Which elements are listed for chlorosis in the source?", "N, K, Mg, S, Fe, Mn, Zn and Mo.", [], [], ["Different element deficiencies may cause the same symptoms."]),
      importance: 5,
      source_page: 48,
      sort_order: 7,
    }),
    card(chapterId, "micronutrient-toxicity", {
      title: "Micronutrient Toxicity",
      card_type: "neet_trap",
      body: "A moderate increase in micronutrients causes toxicity; any mineral concentration reducing tissue dry weight by about 10% is considered toxic.",
      table_data: table(["Toxicity cue", "Source-backed detail"], [
        ["Element interaction", "Excess of an element may inhibit uptake of another element."],
        ["Mn example", "Excess Mn induces deficiencies of Fe, Mg and Ca."],
        ["Mechanism", "Mn competes with Fe and Mg for uptake and with Mg for enzyme binding; it inhibits Ca translocation to shoot apex."],
        ["Symptom", "Brown spots surrounded by chlorotic veins."],
      ]),
      recall_data: recall("What is the main symptom of manganese toxicity in the source?", "Brown spots surrounded by chlorotic veins."),
      importance: 5,
      source_page: 48,
      sort_order: 8,
    }),
    card(chapterId, "absorption-of-elements", {
      title: "Mechanism of Absorption of Elements",
      card_type: "process",
      body: "Absorption of mineral ions has passive and active phases.",
      table_data: table(["Phase", "Source-backed recall"], [
        ["Influx", "Inward movement of ions into cells."],
        ["Efflux", "Outward movement of ions."],
        ["First phase", "Initial rapid and passive uptake into apoplast, usually through ion-channels."],
        ["Second phase", "Slow active uptake into symplast; requires energy."],
        ["Translocation", "Mineral salts move through xylem along with ascending stream of water."],
      ]),
      recall_data: recall("Which phase of mineral absorption is active and where do ions enter?", "The second phase; ions are taken slowly into the symplast or cytoplasm."),
      importance: 4,
      source_page: 49,
      sort_order: 9,
    }),
    card(chapterId, "soil-reservoir", {
      title: "Soil as Reservoir of Essential Elements",
      card_type: "fact",
      body: "Weathering and breakdown of rocks enrich soil with dissolved ions and inorganic salts.",
      table_data: table(["Role of soil", "Source-backed detail"], [
        ["Minerals and water", "Supplies minerals and holds water."],
        ["Microbes", "Harbours nitrogen-fixing bacteria and other microbes."],
        ["Air", "Supplies air to roots."],
        ["Support", "Acts as a matrix that stabilizes the plant."],
        ["Fertilisers", "Supply macro-nutrients and micro-nutrients."],
      ]),
      recall_data: recall("Name two source-listed roles of soil.", "It supplies minerals/holds water and harbours nitrogen-fixing bacteria and other microbes."),
      importance: 3,
      source_page: 49,
      sort_order: 10,
    }),
    card(chapterId, "nitrogen-cycle", {
      title: "Nitrogen Cycle",
      card_type: "process",
      body: "Nitrogen is a limiting nutrient for natural and agricultural ecosystems.",
      diagram_data: { type: "bio-nitrogen-cycle" },
      table_data: table(["Process", "Source-backed recall"], [
        ["Nitrogen fixation", "Conversion of atmospheric nitrogen to ammonia."],
        ["Ammonification", "Decomposition of organic nitrogen of dead plants and animals into ammonia."],
        ["Nitrification", "Ammonia is oxidised into nitrate by nitrifying bacteria."],
        ["Assimilation", "Plants absorb nitrate; in leaves it is reduced to ammonia that forms amine groups of amino acids."],
        ["Denitrification", "Nitrate is reduced to nitrogen by Pseudomonas and Thiobacillus."],
      ]),
      recall_data: recall("Which bacteria carry out denitrification in the source?", "Pseudomonas and Thiobacillus."),
      importance: 5,
      source_page: 49,
      sort_order: 11,
    }),
    card(chapterId, "nitrification-equations", {
      title: "Nitrification Equations",
      card_type: "sequence",
      body: "The source presents nitrification as two oxidation steps by chemo-autotrophic bacteria.",
      formulas: [
        { label: "Nitrite formation", latex: "2NH_3 + 3O_2 \\xrightarrow{Nitrosomonas,\\ Nitrococcus} 2NO_2^- + 2H^+ + 2H_2O" },
        { label: "Nitrate formation", latex: "2NO_2^- + O_2 \\xrightarrow{Nitrobacter} 2NO_3^-" },
      ],
      table_data: table(["Step", "Organism"], [
        ["NH3 to NO2−", "Nitrosomonas, Nitrococcus"],
        ["NO2− to NO3−", "Nitrobacter"],
      ]),
      recall_data: recall("Which organism oxidises nitrite to nitrate?", "Nitrobacter."),
      importance: 5,
      source_page: 49,
      sort_order: 12,
    }),
    card(chapterId, "biological-nitrogen-fixation", {
      title: "Biological Nitrogen Fixation",
      card_type: "classification",
      body: "Biological nitrogen fixation is the reduction of N2 to NH3 by living organisms in presence of nitrogenase enzyme.",
      table_data: table(["Type", "Source examples"], [
        ["Free-living aerobic", "Azotobacter & Beijerinckia"],
        ["Free-living anaerobic", "Rhodospirillum & Bacillus"],
        ["Cyanobacteria", "Anabaena & Nostoc"],
        ["Symbiotic", "Rhizobium (aerobic)"],
      ]),
      recall_data: recall("What enzyme is required for biological nitrogen fixation?", "Nitrogenase.", ["Only certain prokaryotic species have nitrogenase and can fix N2."]),
      importance: 5,
      source_page: 49,
      sort_order: 13,
    }),
    card(chapterId, "symbiotic-nitrogen-fixation", {
      title: "Symbiotic Nitrogen Fixation",
      card_type: "examples",
      body: "Rhizobium species are most prominent in roots of legumes; the most common association is as nodules.",
      table_data: table(["Recall cue", "Source detail"], [
        ["Legume examples", "Alfalfa, sweet clover, sweet pea, lentils, garden pea, broad bean, clover beans etc."],
        ["Non-legume example", "Frankia produces N2 fixing nodules on roots of Alnus."],
        ["Nodule colour", "Red or pink due to leguminous haemoglobin (leg-haemoglobin)."],
        ["Nodule contents", "Nitrogenase enzyme & leg-haemoglobin."],
      ]),
      recall_data: recall("Why are nodules red or pink?", "Due to leguminous haemoglobin (leg-haemoglobin)."),
      importance: 5,
      source_page: 49,
      sort_order: 14,
    }),
    card(chapterId, "nodule-formation", {
      title: "Nodule Formation Sequence",
      card_type: "sequence",
      body: "Rhizobium infection proceeds from root-hair attachment to vascular connection.",
      diagram_data: { type: "bio-nodule-formation" },
      table_data: table(["Order", "Source-backed step"], [
        ["1", "Rhizobia multiply, colonise surrounding roots and attach to epidermal/root-hair cells."],
        ["2", "Root hairs curl and bacteria invade the root hair."],
        ["3", "An infection thread carries bacteria into root cortex."],
        ["4", "Bacteria initiate nodule formation in cortex."],
        ["5", "Bacteria are released into cells, forming specialised nitrogen-fixing cells."],
        ["6", "Nodule establishes direct vascular connection with host for nutrient exchange."],
      ]),
      recall_data: recall("What carries Rhizobium into the root cortex?", "An infection thread."),
      importance: 5,
      source_page: 50,
      sort_order: 15,
    }),
    card(chapterId, "nitrogenase-equation", {
      title: "Nitrogenase and Oxygen Trap",
      card_type: "neet_trap",
      body: "Nitrogenase is a Mo-Fe protein that catalyses conversion of nitrogen to NH3, the first stable product of N2 fixation.",
      formulas: [{ label: "Nitrogenase reaction", latex: "N_2 + 8e^- + 8H^+ + 16ATP \\rightarrow 2NH_3 + H_2 + 16ADP + 16P_i" }],
      table_data: table(["Recall cue", "Source-backed detail"], [
        ["Energy", "Ammonia synthesis needs high energy input: 8 ATP for each NH3."],
        ["Oxygen", "Nitrogenase is highly sensitive to molecular oxygen."],
        ["Protection", "Leg-haemoglobin acts as an oxygen scavenger."],
        ["Rhizobia state", "Aerobic free-living; become anaerobic during N2 fixing events to protect nitrogenase."],
      ]),
      recall_data: recall("Why is leg-haemoglobin important in nitrogen fixation?", "It acts as an oxygen scavenger, protecting oxygen-sensitive nitrogenase.", [], [], ["Nitrogenase requires anaerobic conditions."]),
      importance: 5,
      source_page: 50,
      sort_order: 16,
    }),
    card(chapterId, "ammonia-assimilation", {
      title: "Fate of Ammonia",
      card_type: "process",
      body: "At physiological pH, NH3 is protonated to form NH4+, but NH4+ is toxic and cannot accumulate.",
      table_data: table(["Pathway", "Source-backed recall"], [
        ["Reductive amination", "Ammonia reacts with α-ketoglutaric acid to form glutamic acid."],
        ["Transamination", "Transfer of amino group (NH2) from one amino acid to keto group of a keto acid in presence of transaminase."],
        ["Main amino donor", "Glutamic acid is the main amino acid from which NH2 transfer takes place."],
      ]),
      recall_data: recall("Which amino acid is the main source of NH2 transfer in transamination?", "Glutamic acid."),
      importance: 5,
      source_page: 50,
      sort_order: 17,
    }),
    card(chapterId, "amides", {
      title: "Amides in Nitrogen Metabolism",
      card_type: "fact",
      body: "Asparagine and glutamine are the most important amides found in plants.",
      table_data: table(["Recall cue", "Source-backed answer"], [
        ["Formation", "Formed from aspartic acid and glutamic acid by addition of another amino group."],
        ["Nitrogen content", "Contain more nitrogen than amino acids."],
        ["Transport", "Transported to other parts of the plant via xylem vessels."],
        ["Soyabean nodules", "Export fixed nitrogen as ureides, which have high nitrogen to carbon ratio."],
      ]),
      recall_data: recall("Which two amides are most important in plants according to the source?", "Asparagine and glutamine."),
      importance: 4,
      source_page: 50,
      sort_order: 18,
    }),
  ];
}

function photosynthesisCards(chapterId) {
  return [
    card(chapterId, "photosynthesis-definition", {
      title: "Photosynthesis Definition and Importance",
      card_type: "concept",
      body: "Photosynthesis is a physico-chemical process by which green plants use light energy to synthesise organic compounds.",
      table_data: table(["Recall cue", "Source-backed detail"], [
        ["Basis", "Basis of life on earth."],
        ["Food", "Primary source of all food on earth."],
        ["Atmosphere", "Releases oxygen into the atmosphere."],
        ["Energy", "Ultimately, all living forms depend on sunlight for energy."],
      ]),
      recall_data: recall("What energy source do green plants use in photosynthesis?", "Light energy or solar energy."),
      importance: 5,
      source_page: 51,
      sort_order: 1,
    }),
    card(chapterId, "photosynthesis-experiments", {
      title: "Photosynthesis Experiments",
      card_type: "classification",
      body: "The source lists early and related experiments that establish light, chlorophyll, CO2, oxygen evolution and action spectrum.",
      table_data: table(["Experiment / scientist", "Source-backed conclusion"], [
        ["Variegated leaf experiment", "Photosynthesis occurs only in green parts of leaves in presence of light."],
        ["Half-leaf experiment", "CO2 is required for photosynthesis."],
        ["Joseph Priestley (1770)", "Plants restore air that animals and burning candles remove; oxygen discovered in 1774."],
        ["Jan Ingenhousz", "Sunlight is essential; only green parts release O2."],
        ["Julius von Sachs (1854)", "Glucose is produced when plants grow and usually stored as starch; chlorophyll is in chloroplasts."],
        ["T.W. Engelmann", "Aerobic bacteria accumulated mainly in blue and red light; first action spectrum described."],
        ["Cornelius van Niel", "O2 evolved by green plants comes from H2O, not CO2."],
      ]),
      recall_data: recall("Which experiment proves CO2 is required for photosynthesis?", "The half-leaf experiment with KOH-soaked cotton."),
      importance: 5,
      source_page: 51,
      sort_order: 2,
    }),
    card(chapterId, "photosynthesis-equations", {
      title: "Photosynthesis Equations",
      card_type: "fact",
      body: "The source distinguishes the empirical equation from the overall correct equation after van Niel's inference.",
      formulas: [
        { label: "Empirical equation", latex: "CO_2 + H_2O \\xrightarrow{Light} [CH_2O] + O_2" },
        { label: "Overall correct equation", latex: "6CO_2 + 12H_2O \\xrightarrow{Light} C_6H_{12}O_6 + 6H_2O + 6O_2" },
      ],
      recall_data: recall("According to van Niel's inference, evolved O2 in green plants comes from which molecule?", "H2O, not CO2.", [], [], ["Do not attribute evolved O2 to CO2 in this source."]),
      importance: 5,
      source_page: 51,
      sort_order: 3,
    }),
    card(chapterId, "site-and-pigments", {
      title: "Photosynthesis Site and Pigments",
      card_type: "classification",
      body: "Photosynthesis occurs in green leaves and other green parts, in chloroplasts of mesophyll cells.",
      table_data: table(["Structure / pigment", "Source-backed recall"], [
        ["Chloroplast system", "Grana, stroma lamellae and matrix stroma."],
        ["Thylakoids", "Membrane-bound sacs in each granum; contain leaf pigments."],
        ["Chlorophyll a", "Bright or blue green in chromatogram; chief pigment associated with photosynthesis."],
        ["Chlorophyll b", "Yellow green."],
        ["Xanthophylls", "Yellow accessory pigments."],
        ["Carotenoids", "Yellow to yellow-orange accessory pigments."],
      ]),
      recall_data: recall("Which pigment is the chief pigment associated with photosynthesis?", "Chlorophyll a."),
      importance: 5,
      source_page: 52,
      sort_order: 4,
    }),
    card(chapterId, "absorption-action-spectrum", {
      title: "Absorption Spectrum and Action Spectrum",
      card_type: "concept",
      body: "The absorption spectrum and action spectrum coincide closely, showing photosynthesis is maximum in blue and red regions of the spectrum.",
      table_data: table(["Term", "Source-backed cue"], [
        ["Pigments", "Absorb light at specific wavelengths."],
        ["Accessory pigment function", "Absorb light at different wavelength and transfer energy to chlorophyll a."],
        ["Protection", "Protect chlorophyll a from photo-oxidation."],
        ["Graph conclusion", "Chlorophyll a is the chief pigment associated with photosynthesis."],
      ]),
      recall_data: recall("In which spectral regions is photosynthesis maximum according to the source?", "Blue and red regions."),
      importance: 5,
      source_page: 52,
      sort_order: 5,
    }),
    card(chapterId, "psi-vs-psii", {
      title: "PSI vs PSII",
      card_type: "comparison",
      body: "Photosystems are named in the sequence of their discovery.",
      table_data: table(["Feature", "PSI", "PSII"], [
        ["Reaction centre", "P700", "P680"],
        ["Absorbs", "Red light at 700 nm.", "Red light at 680 nm."],
        ["Role in electron flow", "Receives electrons from PSII and passes them toward NADP+.", "Supplies electrons into the Z scheme after water splitting replaces lost electrons."],
        ["Cyclic flow", "Only PSI is functional in stroma lamellae.", "Stroma lamellae membranes lack PSII."],
      ]),
      recall_data: recall("Which photosystem is associated with P680?", "Photosystem II.", [], [], ["PSI is P700; PSII is P680."]),
      importance: 5,
      source_page: 52,
      sort_order: 6,
    }),
    card(chapterId, "light-reaction-z-scheme", {
      title: "Light Reaction and Z Scheme",
      card_type: "process",
      body: "Light reactions include light absorption, water splitting, oxygen release and formation of ATP & NADPH.",
      diagram_data: { type: "bio-light-reaction-flow" },
      table_data: table(["Step", "Source-backed process"], [
        ["PSII", "Absorbs red light of 680 nm; electrons are excited and transferred to an electron acceptor."],
        ["ETS", "Electron acceptor passes electrons to a chain consisting of cytochromes."],
        ["PSI", "Electrons are transferred to pigments of PSI; PSI electrons are also excited by red light of 700 nm."],
        ["NADP+", "Electrons move downhill to NADP+; NADP+ is reduced to NADPH + H+."],
        ["Z scheme", "Transfer from PSII to PSI and finally to NADP+ forms the zigzag Z scheme."],
      ]),
      recall_data: recall("What is the Z scheme?", "Transfer of electrons from PSII to PSI and finally downhill to NADP+, arranged in zigzag shape on a redox potential scale."),
      importance: 5,
      source_page: 52,
      sort_order: 7,
    }),
    card(chapterId, "photolysis", {
      title: "Splitting of Water",
      card_type: "fact",
      body: "The water splitting complex in PSII is located on the inner side of the thylakoid membrane.",
      formulas: [{ label: "Photolysis", latex: "2H_2O \\rightarrow 4H^+ + O_2 + 4e^-" }],
      table_data: table(["Recall cue", "Source-backed detail"], [
        ["Purpose", "PSII can supply electrons continuously by replacing electrons from water splitting."],
        ["Protons", "Used to reduce NADP to NADPH."],
        ["Oxygen", "Liberated as a by-product of photosynthesis."],
      ]),
      recall_data: recall("Where is the water splitting complex located?", "On the inner side of the thylakoid membrane in PSII."),
      importance: 5,
      source_page: 52,
      sort_order: 8,
    }),
    card(chapterId, "cyclic-vs-noncyclic", {
      title: "Cyclic vs Non-Cyclic Photophosphorylation",
      card_type: "comparison",
      body: "Photophosphorylation is synthesis of ATP from ADP in chloroplasts in presence of light.",
      diagram_data: { type: "bio-cyclic-noncyclic" },
      table_data: table(["Feature", "Non-cyclic", "Cyclic"], [
        ["Photosystems", "PSII then PSI work in series.", "Only PSI is functional."],
        ["Location cue", "Through electron transport chain as seen in Z scheme.", "Occurs in stroma lamellae."],
        ["Products", "ATP and NADPH + H+.", "Only ATP; no NADPH + H+."],
        ["Electron fate", "Electrons lost by PSII do not come back but pass to NADP+.", "Electron cycles back to PSI through electron transport chain."],
        ["Condition", "", "Also occurs when only light beyond 680 nm is available."],
      ]),
      recall_data: recall("Which photophosphorylation produces only ATP and no NADPH + H+?", "Cyclic photophosphorylation.", [], [], ["Cyclic flow uses only PSI."]),
      importance: 5,
      source_page: 53,
      sort_order: 9,
    }),
    card(chapterId, "chemiosmosis", {
      title: "Chemiosmotic Hypothesis in Chloroplast",
      card_type: "process",
      body: "Chemiosmosis explains the mechanism of ATP synthesis in chloroplasts.",
      table_data: table(["Need / event", "Source-backed recall"], [
        ["Requirements", "A membrane, a proton pump, a proton gradient and ATP synthase."],
        ["Water splitting", "Occurs on inner side of membrane; protons accumulate in lumen."],
        ["Electron movement", "As electrons move through photosystems, protons are transported across the membrane."],
        ["NADP reductase", "Located on stroma side and removes protons from stroma to reduce NADP+."],
        ["Gradient result", "Protons decrease in stroma and accumulate in lumen; pH decreases in lumen."],
        ["ATP synthase", "Breakdown of proton gradient leads to ATP synthesis."],
      ]),
      recall_data: recall("What creates the proton gradient across the thylakoid membrane?", "Water splitting and electron transport remove protons from stroma and accumulate them in the thylakoid lumen."),
      importance: 5,
      source_page: 53,
      sort_order: 10,
    }),
    card(chapterId, "dark-reaction", {
      title: "Dark Reaction",
      card_type: "concept",
      body: "Dark reaction uses ATP and NADPH to drive synthesis of food (sugars).",
      table_data: table(["Recall cue", "Source-backed answer"], [
        ["Products of light reaction", "ATP, NADPH and O2."],
        ["Dependency", "Does not directly depend on light but depends on products of light reaction."],
        ["Not darkness", "It does not mean they occur in darkness or are not light dependent."],
        ["Assimilation types", "C3 pathway and C4 pathway."],
      ]),
      recall_data: recall("Does dark reaction mean the reaction occurs in darkness?", "No. It depends on products of the light reaction."),
      importance: 5,
      source_page: 53,
      sort_order: 11,
    }),
    card(chapterId, "calvin-cycle", {
      title: "Calvin Cycle",
      card_type: "process",
      body: "The C3 pathway or Calvin cycle occurs in all photosynthetic plants and has three stages: carboxylation, reduction and regeneration.",
      diagram_data: { type: "bio-calvin-cycle" },
      table_data: table(["Stage", "Source-backed recall"], [
        ["Carboxylation", "RuBP, a 5-carbon ketose sugar, is the primary CO2 acceptor; CO2 is fixed by RuBP to two 3-PGA in presence of RuBP carboxylase."],
        ["Reduction", "Series of reactions leading to glucose formation; uses 2 ATP and 2 NADPH per CO2."],
        ["Regeneration", "Crucial for continuation; requires one ATP to form RuBP."],
        ["Per CO2", "3 ATP and 2 NADPH are required."],
        ["Per glucose", "6 turns of the cycle are needed."],
      ]),
      recall_data: recall("What are the three stages of the Calvin cycle?", "Carboxylation, reduction and regeneration."),
      importance: 5,
      source_page: 54,
      sort_order: 12,
    }),
    card(chapterId, "rubisco", {
      title: "RuBisCO Trap",
      card_type: "neet_trap",
      body: "RuBP carboxylase also has oxygenation activity, so it is called RuBP carboxylase-oxygenase (RuBisCO).",
      table_data: table(["Recall cue", "Source-backed detail"], [
        ["Primary acceptor in C3", "RuBP."],
        ["Enzyme", "RuBP carboxylase-oxygenase (RuBisCO)."],
        ["Abundance", "Most abundant enzyme in the world."],
        ["Binding", "Active site can bind CO2 and O2; relative concentrations determine binding."],
      ]),
      recall_data: recall("Why is RuBP carboxylase called RuBisCO?", "Because it also has oxygenation activity: RuBP carboxylase-oxygenase.", [], [], ["RuBisCO can bind both CO2 and O2."]),
      importance: 5,
      source_page: 54,
      sort_order: 13,
    }),
    card(chapterId, "calvin-input-output", {
      title: "Calvin Cycle Input and Output",
      card_type: "fact",
      body: "The source gives the inputs and outputs needed to remove one glucose molecule from the Calvin pathway.",
      table_data: table(["In", "Out"], [
        ["6 CO2", "1 glucose"],
        ["18 ATP", "18 ADP"],
        ["12 NADPH", "12 NADP"],
      ]),
      recall_data: recall("How many ATP and NADPH are needed per glucose in the source Calvin-cycle table?", "18 ATP and 12 NADPH."),
      importance: 5,
      source_page: 54,
      sort_order: 14,
    }),
    card(chapterId, "c4-pathway", {
      title: "C4 Pathway",
      card_type: "process",
      body: "The C4 pathway is present in plants adapted to dry tropical regions and is also called Hatch & Slack pathway.",
      diagram_data: { type: "bio-c4-pathway" },
      table_data: table(["Step / feature", "Source-backed recall"], [
        ["Primary CO2 acceptor", "Phosphoenol pyruvate (PEP), a 3-carbon molecule in mesophyll cells."],
        ["Enzyme", "PEP carboxylase (PEPcase)."],
        ["First product", "OAA, a 4-carbon organic acid."],
        ["Transport", "OAA forms malic acid or aspartic acid, transported to bundle sheath cells."],
        ["Bundle sheath", "C4 acids break down to release CO2 and a C3 molecule."],
        ["Return", "C3 molecule returns to mesophyll and is converted to PEP again."],
      ]),
      recall_data: recall("What is the primary CO2 acceptor in the C4 pathway?", "Phosphoenol pyruvate (PEP).", ["PEPcase fixes CO2 in mesophyll cells."]),
      importance: 5,
      source_page: 54,
      sort_order: 15,
    }),
    card(chapterId, "kranz-anatomy", {
      title: "Kranz Anatomy",
      card_type: "concept",
      body: "Large cells around vascular bundles of C4 plants are called bundle sheath cells; such anatomy is called Kranz anatomy.",
      table_data: table(["Bundle sheath feature", "Source-backed detail"], [
        ["Arrangement", "May form several layers around vascular bundles."],
        ["Chloroplasts", "Large number of chloroplasts."],
        ["Walls", "Thick walls impervious to gas exchange."],
        ["Spaces", "No intercellular spaces."],
        ["Enzymes", "Rich in RuBisCO but lack PEPcase."],
      ]),
      recall_data: recall("Which C4 cells are rich in RuBisCO but lack PEPcase?", "Bundle sheath cells."),
      importance: 5,
      source_page: 54,
      sort_order: 16,
    }),
    card(chapterId, "photorespiration", {
      title: "Photorespiration",
      card_type: "neet_trap",
      body: "Photorespiration occurs when RuBP binds with O2 in C3 plants, decreasing CO2 fixation.",
      table_data: table(["Recall cue", "Source-backed detail"], [
        ["Products", "One molecule of phosphoglycerate and phosphoglycolate."],
        ["Wastefulness", "No synthesis of sugars, ATP and NADPH; releases CO2 by using ATP."],
        ["C4 plants", "Photorespiration does not occur because they increase CO2 concentration at the enzyme site."],
        ["C4 result", "Productivity and yields are better; tolerance to higher temperatures."],
      ]),
      recall_data: recall("Why is photorespiration called wasteful in the source?", "There is no synthesis of sugars, ATP and NADPH; it releases CO2 by using ATP.", [], [], ["C4 plants lack photorespiration by increasing CO2 concentration at the enzyme site."]),
      importance: 5,
      source_page: 54,
      sort_order: 17,
    }),
    card(chapterId, "c3-vs-c4", {
      title: "C3 vs C4 Plants",
      card_type: "comparison",
      body: "The handbook compares C3 and C4 plants across anatomy, first product, chloroplasts, photorespiration and temperature.",
      table_data: table(["Feature", "C3 plants", "C4 plants"], [
        ["Photosynthesis occurs", "Mesophyll cells.", "Mesophyll and bundle sheath cells."],
        ["Kranz anatomy", "Absent.", "Present."],
        ["Primary CO2 acceptor", "RuBP.", "PEP."],
        ["First stable product", "3-PGA, a 3-C compound.", "OAA, a 4-C compound."],
        ["Chloroplasts", "Only one type (granal).", "Dimorphic: granal in mesophyll and agranal in bundle sheath."],
        ["Photorespiration", "High.", "Absent or negligible."],
        ["CO2 compensation point", "25-100 µl. CO2 l−1.", "0-10 µl. CO2 l−1."],
        ["Optimum temperature", "About 25°C.", "About 35°C - 45°C."],
        ["Examples", "Rice, wheat, bean, potato.", "Maize, sugarcane, amaranth, sorghum."],
      ]),
      recall_data: recall("Which plants have PEP as primary CO2 acceptor?", "C4 plants.", [], ["Maize", "Sugarcane", "Amaranth", "Sorghum"]),
      importance: 5,
      source_page: 55,
      sort_order: 18,
    }),
    card(chapterId, "blackmans-law", {
      title: "Blackman's Law of Limiting Factors",
      card_type: "fact",
      body: "If a biochemical process is affected by more than one factor, its rate is determined by the factor nearest to its minimal value.",
      table_data: table(["Source example", "Recall answer"], [
        ["Green leaf with optimal light & CO2 but very low temperature", "May not photosynthesize."],
        ["If optimal temperature is given", "It will start photosynthesis."],
      ]),
      recall_data: recall("Which factor determines rate under Blackman's law?", "The factor nearest to its minimal value, directly affecting the process if changed."),
      importance: 5,
      source_page: 55,
      sort_order: 19,
    }),
    card(chapterId, "photosynthesis-factors", {
      title: "Factors Affecting Photosynthesis",
      card_type: "classification",
      body: "Photosynthesis is affected by internal plant factors and external environmental factors.",
      table_data: sections([
        {
          title: "Factor groups",
          columns: ["Group", "Source details"],
          rows: [["Internal", "Number, size, age and orientation of leaves, mesophyll cells and chloroplasts, internal CO2 concentration and amount of chlorophyll."], ["External", "Sunlight, temperature, CO2 concentration and water."]],
        },
        {
          title: "Major external factor cues",
          columns: ["Factor", "Source-backed cue"],
          rows: [["Light", "Linear relationship at low intensity; saturation at 10% full sunlight; high incident light breaks down chlorophyll."], ["CO2", "0.03-0.04% in atmosphere; increase up to 0.05% increases fixation; beyond can damage over long periods."], ["Temperature", "Dark reactions are temperature controlled; C4 respond to higher temperatures."], ["Water", "Water stress closes stomata and wilts leaves."]],
        },
      ]),
      recall_data: recall("At what light level does saturation occur in the source?", "At 10% of full sunlight."),
      importance: 5,
      source_page: 55,
      sort_order: 20,
    }),
  ];
}

function respirationCards(chapterId) {
  return [
    card(chapterId, "cellular-respiration", {
      title: "Cellular Respiration",
      card_type: "concept",
      body: "Oxidation of food materials within the cell to release energy for ATP synthesis is called cellular respiration.",
      table_data: table(["Recall cue", "Source-backed detail"], [
        ["Respiratory substrates", "Carbohydrates, proteins, fats and organic acids."],
        ["Most common substrate", "Carbohydrates."],
        ["Energy use", "Energy released is used to synthesize ATP."],
        ["ATP", "Energy currency of the cell."],
        ["Ultimate source", "Photosynthesis."],
      ]),
      recall_data: recall("What is the ultimate source of food respired by plants?", "Photosynthesis."),
      importance: 5,
      source_page: 56,
      sort_order: 1,
    }),
    card(chapterId, "breathing-in-plants", {
      title: "Breathing in Plants",
      card_type: "classification",
      body: "Plants get O2 and give out CO2, with gas exchange through stomata and lenticels.",
      formulas: [{ label: "Complete glucose combustion", latex: "C_6H_{12}O_6 + 6O_2 \\rightarrow 6CO_2 + 6H_2O + Energy" }],
      table_data: table(["Why no specialised respiratory organs?", "Source-backed detail"], [
        ["Part-wise needs", "Each plant part takes care of its own gas-exchange needs."],
        ["Limited transport", "Gas transport is very limited."],
        ["Low exchange", "Very low gas exchange compared with animals."],
        ["Cell exposure", "Most living cells have contact with air or interconnected air spaces."],
      ]),
      recall_data: recall("Through which structures does gas exchange occur in plants?", "Stomata and lenticels."),
      importance: 4,
      source_page: 56,
      sort_order: 2,
    }),
    card(chapterId, "glycolysis", {
      title: "Glycolysis (EMP Pathway)",
      card_type: "process",
      body: "Glycolysis is partial oxidation of glucose to 2 molecules of pyruvic acid (C3H4O3) in the absence of O2.",
      diagram_data: { type: "bio-respiration-overview" },
      table_data: table(["Recall cue", "Source-backed answer"], [
        ["Location", "Cytoplasm of all living organisms."],
        ["Name", "Scheme given by Gustav Embden, Otto Meyerhof & J. Parnas; also EMP pathway."],
        ["Anaerobes", "Only process in respiration."],
        ["ATP used", "Conversion of glucose to glucose 6-phosphate and fructose 6-phosphate to fructose 1, 6-diphosphate."],
        ["ATP directly made", "4 ATP molecules from one glucose molecule."],
        ["Key product", "Pyruvic acid (pyruvate); metabolic fate depends on cellular need."],
      ]),
      recall_data: recall("Where does glycolysis occur?", "In the cytoplasm of all living organisms."),
      importance: 5,
      source_page: 56,
      sort_order: 3,
    }),
    card(chapterId, "glycolysis-sequence", {
      title: "Glycolysis Sequence Recall",
      card_type: "sequence",
      body: "The source lists the major glycolytic conversions without needing a full dense diagram.",
      table_data: table(["Order", "Source-backed step"], [
        ["1", "Sucrose converts to glucose and fructose by invertase."],
        ["2", "Glucose and fructose are phosphorylated to glucose-6-phosphate by hexokinase."],
        ["3", "Glucose-6-phosphate is isomerised to fructose-6-phosphate."],
        ["4", "Fructose 1, 6-diphosphate splits into DHAP and PGAL."],
        ["5", "PGAL is oxidised to BPGA with NAD+ forming NADH + H+."],
        ["6", "BPGA becomes PGA yielding ATP."],
        ["7", "PEP converts to pyruvic acid, forming ATP."],
      ]),
      recall_data: recall("Which molecule is the key product of glycolysis?", "Pyruvic acid (pyruvate)."),
      importance: 5,
      source_page: 56,
      sort_order: 4,
    }),
    card(chapterId, "fate-of-pyruvate", {
      title: "Fate of Pyruvate",
      card_type: "classification",
      body: "In different cells, pyruvic acid is handled in three ways.",
      table_data: table(["Fate", "Source-backed cue"], [
        ["Lactic acid fermentation", "Pyruvic acid is converted to lactic acid."],
        ["Alcoholic fermentation", "Pyruvic acid is converted to CO2 and ethanol."],
        ["Aerobic respiration", "Pyruvic acid enters Krebs' cycle after transport into mitochondria."],
      ]),
      recall_data: recall("Name the three source-listed fates of pyruvic acid.", "Lactic acid fermentation, alcoholic fermentation and aerobic respiration."),
      importance: 5,
      source_page: 56,
      sort_order: 5,
    }),
    card(chapterId, "fermentation", {
      title: "Fermentation",
      card_type: "comparison",
      body: "Fermentation is incomplete oxidation of glucose under anaerobic condition.",
      table_data: table(["Type / cue", "Source-backed detail"], [
        ["Alcoholic fermentation", "Pyruvic acid is converted to CO2 and ethanol by pyruvic acid decarboxylase and alcohol dehydrogenase; example yeast."],
        ["Lactic acid fermentation", "Pyruvic acid is converted to lactic acid; example some bacteria."],
        ["Reducing agent", "NADH+H+ is reoxidised to NAD+ in both processes."],
        ["Animal example", "During inadequate oxygen in exercise, muscle pyruvic acid is reduced to lactic acid by lactate dehydrogenase."],
        ["Net ATP", "2 ATP per glucose molecule."],
      ]),
      recall_data: recall("What is net ATP production from fermentation of one glucose molecule?", "2 ATP.", [], ["Yeast", "Some bacteria"]),
      importance: 5,
      source_page: 57,
      sort_order: 6,
    }),
    card(chapterId, "fermentation-drawbacks", {
      title: "Drawbacks of Fermentation",
      card_type: "neet_trap",
      body: "Fermentation has limited energy production and hazardous products.",
      table_data: table(["Drawback", "Source-backed detail"], [
        ["Low energy", "Less than 7% of the energy in glucose is released and not all is trapped as ATP."],
        ["Products", "Hazardous products, acid or alcohol, are formed."],
        ["Yeast trap", "Yeasts poison themselves to death when alcohol reaches about 13%."],
      ]),
      recall_data: recall("At about what alcohol concentration do yeasts poison themselves to death?", "About 13%."),
      importance: 5,
      source_page: 57,
      sort_order: 7,
    }),
    card(chapterId, "aerobic-respiration", {
      title: "Aerobic Respiration",
      card_type: "process",
      body: "Aerobic respiration is complete oxidation of organic substances in presence of oxygen, releasing CO2, water and energy.",
      table_data: table(["Event", "Source-backed recall"], [
        ["Location", "Mitochondria."],
        ["Pyruvate entry", "Transported from cytoplasm into mitochondria."],
        ["Complete oxidation", "Stepwise removal of all hydrogen atoms, leaving 3 CO2 molecules; matrix of mitochondria."],
        ["Electron passing", "Electrons pass to molecular O2 with ATP synthesis; inner membrane of mitochondria."],
        ["Oxidative decarboxylation", "Pyruvate needs pyruvic dehydrogenase, NAD+ and Coenzyme A; 2 NADH from 2 pyruvic acid molecules."],
      ]),
      recall_data: recall("Where does complete oxidation of pyruvate take place?", "In the matrix of mitochondria."),
      importance: 5,
      source_page: 57,
      sort_order: 8,
    }),
    card(chapterId, "krebs-cycle", {
      title: "Krebs Cycle",
      card_type: "sequence",
      body: "TCA cycle was first elucidated by Hans Krebs.",
      diagram_data: { type: "bio-krebs-ets" },
      table_data: table(["Order", "Source-backed step"], [
        ["1", "Acetyl group condenses with oxaloacetic acid and water to form citric acid in presence of citrate synthase."],
        ["2", "Citrate is isomerised to isocitrate."],
        ["3", "Decarboxylation of isocitrate to α-ketoglutaric acid."],
        ["4", "Decarboxylation of α-ketoglutaric acid to succinyl-CoA."],
        ["5", "Succinyl-CoA converts to succinic acid and GTP is synthesised."],
        ["6", "Succinate oxidises to fumarate and then malate."],
        ["7", "Malate oxidises to OAA."],
      ]),
      recall_data: recall("Who first elucidated the TCA cycle?", "Hans Krebs."),
      importance: 5,
      source_page: 57,
      sort_order: 9,
    }),
    card(chapterId, "krebs-output", {
      title: "Krebs Cycle Output",
      card_type: "fact",
      body: "For one glucose, the source states Krebs-cycle breakdown gives fixed reduced coenzymes and ATP.",
      table_data: table(["Output from glucose", "Source amount"], [
        ["CO2", "6 CO2"],
        ["NADH+H+", "8 NADH+H+"],
        ["FADH2", "2 FADH2"],
        ["ATP", "2 ATP"],
      ]),
      recall_data: recall("How many NADH+H+ are produced from glucose according to the Krebs-cycle summary?", "8 NADH+H+.", [], [], ["Use the source ATP/accounting values as written."]),
      importance: 5,
      source_page: 57,
      sort_order: 10,
    }),
    card(chapterId, "ets", {
      title: "Electron Transport System",
      card_type: "process",
      body: "ETS is the metabolic pathway in the inner mitochondrial membrane through which electrons pass from one carrier to another.",
      table_data: table(["Carrier / complex", "Source-backed recall"], [
        ["Complex I", "NADH dehydrogenase oxidises electrons from NADH."],
        ["Ubiquinone", "Receives electrons from complex I and reducing equivalents via FADH2 (complex II)."],
        ["Complex III", "Cytochrome bc1 transfers electrons to cytochrome c."],
        ["Cytochrome c", "Small protein on outer surface of inner membrane; mobile carrier between complex III and IV."],
        ["Complex IV", "Cytochrome c oxidase contains cytochromes a and a3 and two copper centres."],
        ["Complex V", "ATP synthase coupled to electron transfer for ATP production."],
      ]),
      recall_data: recall("Which complex is ATP synthase in the source?", "Complex V."),
      importance: 5,
      source_page: 58,
      sort_order: 11,
    }),
    card(chapterId, "oxidative-phosphorylation", {
      title: "Oxidative Phosphorylation",
      card_type: "process",
      body: "In respiration, energy of oxidation-reduction is used for phosphorylation, so the process is called oxidative phosphorylation.",
      formulas: [
        { label: "NADH ATP value", latex: "1\\ NADH \\rightarrow 3\\ ATP" },
        { label: "FADH2 ATP value", latex: "1\\ FADH_2 \\rightarrow 2\\ ATP" },
      ],
      table_data: table(["Recall cue", "Source-backed detail"], [
        ["Final acceptor", "Oxygen acts as the final hydrogen acceptor."],
        ["ATP synthase parts", "F1 and F0."],
        ["F1", "Peripheral headpiece; site for ATP synthesis from ADP and inorganic phosphate."],
        ["F0", "Integral membrane protein complex; channel through which protons cross inner membrane."],
        ["Protons per ATP", "For each ATP produced, 2H+ passes through F0 from inter-membrane space to matrix."],
      ]),
      recall_data: recall("What is the final hydrogen acceptor in aerobic respiration?", "Oxygen.", [], [], ["Oxygen's role is terminal, but vital."]),
      importance: 5,
      source_page: 58,
      sort_order: 12,
    }),
    card(chapterId, "respiratory-balance-sheet", {
      title: "Respiratory Balance Sheet",
      card_type: "table",
      body: "The source calculates ATP from one glucose using stated assumptions and then gives net gain after transport cost.",
      table_data: table(["Stage", "Source ATP accounting"], [
        ["Glycolysis", "2 ATP directly = 2 ATP; 2 molecules of NADH = 6 ATP"],
        ["Oxidative decarboxylation", "2 NADH = 6 ATP"],
        ["TCA cycle", "6 NADH = 18 ATP; 2 FADH = 4 ATP; 2 GTP = 2 ATP"],
        ["Total", "38 ATP"],
        ["Transport cost", "2 ATP spent for transporting 2 NADH molecules formed during glycolysis to mitochondria."],
        ["Net gain", "36 ATP molecules"],
      ]),
      recall_data: recall("What net ATP gain from one glucose does the source give?", "36 ATP molecules.", [], [], ["Do not correct the handbook's ATP accounting with another convention."]),
      importance: 5,
      source_page: 58,
      sort_order: 13,
    }),
    card(chapterId, "fermentation-vs-aerobic", {
      title: "Fermentation vs Aerobic Respiration",
      card_type: "comparison",
      body: "The source directly compares fermentation with aerobic respiration.",
      table_data: table(["Feature", "Fermentation", "Aerobic respiration"], [
        ["Glucose breakdown", "Partial breakdown of glucose.", "Complete breakdown of glucose to CO2 & H2O."],
        ["Net ATP", "Only 2 ATP.", "36 ATP."],
        ["NADH oxidation", "NADH is oxidised to NAD+ rather slowly.", "NADH is oxidised to NAD+ very vigorously."],
      ]),
      recall_data: recall("Which pathway gives net gain of only 2 ATP in the source comparison?", "Fermentation."),
      importance: 5,
      source_page: 59,
      sort_order: 14,
    }),
    card(chapterId, "amphibolic-pathway", {
      title: "Amphibolic Pathway",
      card_type: "concept",
      body: "The respiratory pathway is better called amphibolic because it involves both anabolism and catabolism.",
      table_data: table(["Source example", "Recall answer"], [
        ["Fatty acids", "Break down to acetyl CoA before entering respiration; acetyl CoA can be withdrawn to synthesise fatty acids."],
        ["Glycerol", "Converted to PGAL and enters the pathway."],
        ["Proteins", "Proteases degrade proteins to amino acids; after deamination each enters Krebs' cycle or as pyruvate or acetyl CoA."],
      ]),
      recall_data: recall("Why is the respiratory pathway amphibolic?", "It involves both anabolism (synthesis) and catabolism (breakdown)."),
      importance: 5,
      source_page: 59,
      sort_order: 15,
    }),
    card(chapterId, "respiratory-quotient", {
      title: "Respiratory Quotient",
      card_type: "fact",
      body: "Respiratory quotient (RQ) is the ratio of CO2 evolved to O2 consumed in respiration.",
      formulas: [
        { label: "RQ", latex: "RQ = \\frac{Volume\\ of\\ CO_2\\ evolved}{Volume\\ of\\ O_2\\ consumed}" },
        { label: "Carbohydrate RQ", latex: "\\frac{6CO_2}{6O_2}=1.0" },
        { label: "Tripalmitin RQ", latex: "\\frac{102CO_2}{145O_2}=0.7" },
      ],
      table_data: table(["Substrate", "Source RQ"], [
        ["Carbohydrates", "1"],
        ["Fats", "< 1; tripalmitin example = 0.7"],
        ["Proteins", "0.9"],
      ]),
      recall_data: recall("What is RQ for carbohydrates in the source?", "1.0."),
      importance: 5,
      source_page: 59,
      sort_order: 16,
    }),
  ];
}

function growthCards(chapterId) {
  return [
    card(chapterId, "growth-definition", {
      title: "Growth",
      card_type: "concept",
      body: "Growth is an irreversible permanent increase in size of an organ or its parts or an individual cell.",
      table_data: table(["Recall cue", "Source-backed detail"], [
        ["Energy", "Growth involves metabolic processes that consume energy."],
        ["Indeterminate growth", "Plant growth continues throughout life due to meristems."],
        ["Open form of growth", "New cells are always added to plant body by meristems."],
        ["Primary growth", "Root apical meristem and shoot apical meristem; elongation along axis."],
        ["Secondary growth", "In gymnosperms and dicots; lateral meristems, vascular cambium and cork-cambium increase girth."],
      ]),
      recall_data: recall("Why is plant growth generally indeterminate?", "Because plant growth continues throughout life due to the presence of meristems."),
      importance: 5,
      source_page: 60,
      sort_order: 1,
    }),
    card(chapterId, "growth-measurable", {
      title: "Growth Is Measurable",
      card_type: "examples",
      body: "At cellular level, growth occurs due to increase in protoplasm, but protoplasm is difficult to measure directly.",
      table_data: table(["Parameter", "Source example"], [
        ["Cell number", "A maize root apical meristem can produce more than 17,500 new cells per hour."],
        ["Cell size", "Cells in a watermelon can increase in size by up to 3,50,000 times."],
        ["Length", "Growth of a pollen tube."],
        ["Surface area", "Growth in a dorsi-ventral leaf."],
        ["Other measures", "Fresh weight, dry weight, length, area, volume and cell number."],
      ]),
      recall_data: recall("What source example shows growth by cell number?", "A maize root apical meristem can produce more than 17,500 new cells per hour."),
      importance: 5,
      source_page: 60,
      sort_order: 2,
    }),
    card(chapterId, "phases-of-growth", {
      title: "Phases of Growth",
      card_type: "sequence",
      body: "The source lists three phases of growth: meristematic, elongation and maturation.",
      diagram_data: { type: "bio-growth-phases" },
      table_data: table(["Phase", "Source-backed recall"], [
        ["Meristematic", "Occurs in meristems at root apex and shoot apex; cells have rich protoplasm, large nuclei, thin cellulosic walls and abundant plasmodesmata."],
        ["Elongation", "Occurs in cells proximal to meristematic zone; increased vacuolation, size and new cell wall deposition."],
        ["Maturation", "Occurs farther from apex; cells attain maximal size in wall thickening and protoplasmic modifications."],
      ]),
      recall_data: recall("Name the three phases of growth in order.", "Meristematic, elongation and maturation."),
      importance: 5,
      source_page: 60,
      sort_order: 3,
    }),
    card(chapterId, "arithmetic-vs-geometric-growth", {
      title: "Arithmetic vs Geometrical Growth",
      card_type: "comparison",
      body: "Growth rate is increased growth per unit time and may be arithmetic or geometrical.",
      diagram_data: { type: "bio-growth-curves" },
      formulas: [
        { label: "Arithmetic growth", latex: "L_t = L_0 + rt" },
        { label: "Exponential growth", latex: "W_1 = W_0e^{rt}" },
      ],
      table_data: table(["Feature", "Arithmetic growth", "Geometrical growth"], [
        ["Cell division result", "Only one daughter cell continues to divide; the other differentiates and matures.", "Both daughter cells continue mitotic cell division."],
        ["Curve", "Linear curve.", "Typical sigmoid (S) curve in natural environment."],
        ["Phases", "", "Lag phase, log/exponential phase and stationary phase."],
        ["Equation", "Lt = L0 + rt.", "W1 = W0ert."],
      ]),
      recall_data: recall("Which growth form gives a sigmoid curve?", "Geometrical growth.", [], [], ["Arithmetic growth gives a linear curve."]),
      importance: 5,
      source_page: 60,
      sort_order: 4,
    }),
    card(chapterId, "absolute-vs-relative-growth", {
      title: "Absolute vs Relative Growth Rate",
      card_type: "comparison",
      body: "Quantitative comparisons of growth can be made by absolute growth rate or relative growth rate.",
      table_data: table(["Growth rate", "Source-backed recall"], [
        ["Relative growth rate", "Measure of ability of plant to produce new plant material; efficiency index."],
        ["Absolute growth rate", "Measurement and comparison of total growth per unit time."],
        ["Relative growth rate comparison", "Growth per unit time expressed on a common basis, e.g. per unit initial parameter."],
      ]),
      recall_data: recall("Which growth-rate measure is called efficiency index in the source?", "Relative growth rate."),
      importance: 5,
      source_page: 61,
      sort_order: 5,
    }),
    card(chapterId, "conditions-for-growth", {
      title: "Conditions for Growth",
      card_type: "classification",
      body: "The source lists five essential conditions for growth.",
      table_data: table(["Condition", "Source-backed role"], [
        ["Water", "Essential for cell enlargement; turgidity helps extension growth; medium for enzymatic activities."],
        ["Oxygen", "Helps release metabolic energy for growth."],
        ["Nutrients", "Macro and micro elements synthesize protoplasm and act as source of energy."],
        ["Temperature", "Growth is maximum at optimum temperature; deviations may harm plants."],
        ["Light & gravity", "Affect certain phases/stages of growth."],
      ]),
      recall_data: recall("Which condition helps cell enlargement through turgidity?", "Water."),
      importance: 4,
      source_page: 61,
      sort_order: 6,
    }),
    card(chapterId, "differentiation-dedifferentiation-redifferentiation", {
      title: "Differentiation vs Dedifferentiation vs Redifferentiation",
      card_type: "comparison",
      body: "Plant cells can mature, regain division capacity, and mature again for specialised functions.",
      table_data: table(["Process", "Source-backed recall", "Example / cue"], [
        ["Differentiation", "Cells in meristems and cambium mature to perform specific functions; capacity of cell division is lost.", "Loss of protoplasm to form a tracheary element."],
        ["Dedifferentiation", "Living differentiated cells regain capacity of division under certain conditions.", "Formation of interfascicular cambium and cork cambium from differentiated parenchyma cells."],
        ["Redifferentiation", "Dedifferentiated cells divide and produce cells that again lose capacity to divide but mature to perform specific functions.", ""],
      ]),
      recall_data: recall("What is dedifferentiation?", "Living differentiated cells regaining the capacity of division under certain conditions."),
      importance: 5,
      source_page: 61,
      sort_order: 7,
    }),
    card(chapterId, "development-and-plasticity", {
      title: "Development and Plasticity",
      card_type: "concept",
      body: "Development includes all changes in the life cycle from seed germination to senescence and is the sum of growth and differentiation.",
      table_data: table(["Term", "Source-backed recall"], [
        ["Plasticity", "Ability of plants to follow different pathways in response to environment or phases of life and form different structures."],
        ["Phase heterophylly", "Cotton, coriander and larkspur juvenile and mature leaves differ in shape."],
        ["Environmental heterophylly", "Leaves produced in air and water differ, e.g. buttercup."],
        ["Intrinsic factors", "Intracellular/genetic or intercellular factors such as plant growth regulators."],
        ["Extrinsic factors", "Light, temperature, water, oxygen, nutrition etc."],
      ]),
      recall_data: recall("What is development in plants?", "All changes in the life cycle from seed germination to senescence; the sum of growth and differentiation."),
      importance: 5,
      source_page: 61,
      sort_order: 8,
    }),
    card(chapterId, "pgr-overview", {
      title: "Plant Growth Regulators",
      card_type: "classification",
      body: "Plant growth regulators are small, simple molecules that regulate plant growth.",
      table_data: table(["Group", "Source-backed recall"], [
        ["Growth promoters", "Growth-promoting activities such as cell division/enlargement, tropic growth, pattern formation, flowering, fruiting and seed formation."],
        ["Promoter examples", "Auxins, gibberellins and cytokinins."],
        ["Growth inhibitors", "Growth-inhibiting activities like dormancy and abscission; response to wounds and stresses."],
        ["Inhibitor examples", "Abscisic acid and ethylene; ethylene fits either group but is largely a growth inhibitor."],
      ]),
      recall_data: recall("Which PGR fits either group but is largely a growth inhibitor?", "Ethylene."),
      importance: 5,
      source_page: 62,
      sort_order: 9,
    }),
    card(chapterId, "auxins", {
      title: "Auxins",
      card_type: "examples",
      body: "Auxins are produced by growing apices of stems and roots and migrate to regions of action.",
      table_data: table(["Recall cue", "Source-backed detail"], [
        ["Darwin observation", "Coleoptiles of canary grass responded to unilateral illumination by growing towards light source."],
        ["Went", "F.W. Went isolated auxin from tips of coleoptiles of oat seedlings."],
        ["Natural auxins", "Indole-3-acetic acid (IAA) and indole butyric acid (IBA)."],
        ["Synthetic auxins", "NAA and 2, 4-D."],
        ["Functions", "Rooting in stem cuttings, flowering in pineapples, prevents early fruit/leaf drop, abscission of older leaves/fruits, parthenocarpy in tomatoes, herbicide use, xylem differentiation and cell division."],
        ["Apical dominance", "Growing apical bud inhibits lateral buds; decapitation promotes lateral buds and is used in tea plantations & hedge-making."],
      ]),
      recall_data: recall("Which auxin is used to kill dicot weeds without affecting mature monocot plants?", "2, 4-D."),
      importance: 5,
      source_page: 62,
      sort_order: 10,
    }),
    card(chapterId, "gibberellins", {
      title: "Gibberellins",
      card_type: "examples",
      body: "Gibberellins are acidic PGRs; GA3 is one of the first discovered and most intensively studied gibberellins.",
      table_data: table(["Recall cue", "Source-backed detail"], [
        ["Kurosawa", "Sterile filtrates of Gibberalla fujikuroi caused bakane or foolish seedling symptoms in healthy rice seedlings."],
        ["Number", "More than 100 gibberellins (GA1, GA2, GA3 and so on)."],
        ["Axis length", "Increase length of axis; used to increase length of grape stalks."],
        ["Fruit", "Elongate and improve shape of fruits such as apple; delay senescence to extend market period."],
        ["Industry", "GA3 speeds malting in brewing industry."],
        ["Sugarcane", "Spraying with gibberellins increases stem length and yield by as much as 20 tonnes per acre."],
        ["Bolting", "Used for bolting in beet, cabbages and many rosette plants."],
      ]),
      recall_data: recall("Which fungus is linked with discovery of gibberellins in the source?", "Gibberalla fujikuroi."),
      importance: 5,
      source_page: 62,
      sort_order: 11,
    }),
    card(chapterId, "cytokinins", {
      title: "Cytokinins",
      card_type: "examples",
      body: "Cytokinins were discovered as kinetin and natural cytokinins are synthesized in regions of rapid cell division.",
      table_data: table(["Recall cue", "Source-backed detail"], [
        ["Skoog observation", "Tobacco stem callus proliferated only when medium had vascular tissue extract, yeast extract, coconut milk or DNA."],
        ["Kinetin", "Identified and crystallized by Skoog & Miller; does not occur naturally in plants."],
        ["Zeatin", "From corn-kernels and coconut milk; natural substance with cytokinin-like activities."],
        ["Natural synthesis sites", "Root apices, shoot buds, young fruits etc."],
        ["Functions", "Cytokinesis, new leaves, chloroplasts in leaves, lateral shoot growth, adventitious shoot formation, overcoming apical dominance and nutrient mobilization delaying leaf senescence."],
      ]),
      recall_data: recall("Which natural substance with cytokinin-like activity comes from corn-kernels and coconut milk?", "Zeatin."),
      importance: 5,
      source_page: 62,
      sort_order: 12,
    }),
    card(chapterId, "ethylene", {
      title: "Ethylene",
      card_type: "examples",
      body: "Ethylene is a simple gaseous PGR synthesized in large amounts by senescing tissues and ripening fruits.",
      table_data: table(["Recall cue", "Source-backed detail"], [
        ["Cousins", "Ripened oranges released a volatile substance that hastened ripening of stored bananas."],
        ["Seedlings", "Influences horizontal growth, swelling of axis and apical hook formation in dicot seedlings."],
        ["Ripening", "Promotes fruit ripening and enhances respiration rate; called respiratory climactic."],
        ["Dormancy", "Breaks seed and bud dormancy; initiates germination in peanut seeds and sprouting of potato tubers."],
        ["Deep water rice", "Promotes rapid internode/petiole elongation so upper shoot remains above water."],
        ["Agriculture", "Ethephon is widely used; hastens ripening in tomatoes and apples, accelerates abscission in cotton/cherry/walnut, promotes female flowers in cucumbers."],
      ]),
      recall_data: recall("What is the most widely used source of ethylene in agriculture?", "Ethephon."),
      importance: 5,
      source_page: 63,
      sort_order: 13,
    }),
    card(chapterId, "aba", {
      title: "Abscisic Acid",
      card_type: "examples",
      body: "Abscisic acid (ABA) is derived from carotenoids and regulates abscission and dormancy.",
      table_data: table(["Recall cue", "Source-backed detail"], [
        ["Names", "Inhibitor-B, abscisin II and dormin were chemically identical and now known as abscisic acid."],
        ["Growth", "Inhibitor of plant growth and metabolism."],
        ["Seed", "Inhibits seed germination; helps seed development, maturation and dormancy."],
        ["Stomata", "Stimulates closure of stomata in epidermis."],
        ["Stress", "Increases tolerance to stresses; called stress hormone."],
        ["Interaction", "In most situations, ABA acts as antagonist to GAs."],
      ]),
      recall_data: recall("Which PGR is called the stress hormone in the source?", "Abscisic acid (ABA).", [], [], ["ABA acts as an antagonist to GAs in most situations."]),
      importance: 5,
      source_page: 63,
      sort_order: 14,
    }),
    card(chapterId, "pgr-comparison", {
      title: "Auxin vs GA vs Cytokinin vs Ethylene vs ABA",
      card_type: "comparison",
      body: "The source separates PGRs by major actions and applications.",
      table_data: table(["Regulator", "Main source-backed actions", "Special applications/examples"], [
        ["Auxin", "Root initiation, flowering, fruit/leaf drop control, abscission of older leaves/fruits, parthenocarpy, xylem differentiation and cell division.", "IAA, IBA; NAA and 2, 4-D; parthenocarpy in tomatoes; tea plantations and hedge-making by decapitation."],
        ["Gibberellin", "Axis elongation, fruit shape/market period, early seed production, bolting.", "GA3; grape stalks, apple, brewing malting, sugarcane yield, beet/cabbages/rosette plants."],
        ["Cytokinin", "Cytokinesis, new leaves, chloroplasts, lateral/adventitious shoots, overcoming apical dominance, nutrient mobilization.", "Kinetin, zeatin from corn-kernels and coconut milk."],
        ["Ethylene", "Senescence, abscission, fruit ripening, dormancy breaking, root hair formation, deep-water rice elongation.", "Ethephon; tomatoes, apples, cotton, cherry, walnut, cucumbers."],
        ["ABA", "Growth/metabolism inhibition, seed germination inhibition, stomatal closure, stress tolerance, seed maturation/dormancy.", "Stress hormone; antagonist to GAs."],
      ]),
      recall_data: recall("Which PGR delays leaf senescence through nutrient mobilization?", "Cytokinins."),
      importance: 5,
      source_page: 63,
      sort_order: 15,
    }),
    card(chapterId, "photoperiodism", {
      title: "Photoperiodism",
      card_type: "classification",
      body: "Photoperiodism is the response of plants to periods of day/night.",
      table_data: table(["Plant group / cue", "Source-backed recall"], [
        ["Long day plants", "Require exposure to light for a period exceeding a well-defined critical duration."],
        ["Short day plants", "Require exposure to light for a period less than critical duration before flowering is initiated."],
        ["Day-neutral plants", "No correlation between exposure to light duration and induction of flowering."],
        ["Perception site", "Leaves perceive light/dark duration, not shoot apices."],
        ["Flowering hormone", "Hypothesised hormone migrates from leaves to shoot apices when enough photoperiod is received."],
      ]),
      recall_data: recall("Which plant part perceives photoperiod in the source?", "Leaves.", [], [], ["Shoot apices cannot themselves perceive photoperiods."]),
      importance: 5,
      source_page: 63,
      sort_order: 16,
    }),
    card(chapterId, "vernalisation", {
      title: "Vernalisation",
      card_type: "concept",
      body: "Vernalisation is the phenomenon in which some plants depend quantitatively or qualitatively on exposure to low temperature for flowering.",
      table_data: table(["Recall cue", "Source-backed detail"], [
        ["Function", "Prevents precocious reproductive development late in the growing season and enables plant to have sufficient time to reach maturity."],
        ["Food plant examples", "Wheat, barley and rye have spring and winter varieties."],
        ["Spring varieties", "Planted in spring and produce grain before end of growing season."],
        ["Winter varieties", "Planted in autumn; over winter as seedlings, resume growth in spring, harvested around mid-summer."],
        ["Biennial examples", "Sugar beet, cabbages, carrots etc."],
      ]),
      recall_data: recall("What temperature exposure is required in vernalisation?", "Exposure to low temperature."),
      importance: 5,
      source_page: 63,
      sort_order: 17,
    }),
    card(chapterId, "seed-dormancy", {
      title: "Seed Dormancy",
      card_type: "classification",
      body: "Certain seeds fail to germinate even under favourable external conditions; such seeds are in dormancy.",
      table_data: table(["Dormancy cue", "Source-backed detail"], [
        ["Causes", "Endogenous conditions: hard seed coat, chemical inhibitors such as ABA, phenolic acids, para-ascorbic acid, and immature embryos."],
        ["Breaking seed coat barrier", "Mechanical abrasions using knives, sandpaper etc. or vigorous shaking; natural abrasions by microbes and digestive tract passage."],
        ["Removing inhibitors", "Chilling conditions or chemicals like gibberellic acid and nitrates."],
        ["Environmental change", "Changing light and temperature."],
      ]),
      recall_data: recall("Name two source-listed ways to overcome seed dormancy.", "Breaking the seed coat barrier and removing inhibitory substances.", ["Changing light and temperature is also listed."]),
      importance: 4,
      source_page: 64,
      sort_order: 18,
    }),
  ];
}

export function getBiologyBatch4Chapters() {
  return BIOLOGY_BATCH_4_CHAPTER_DEFINITIONS.map((item) => ({
    id: chapter(item.slug),
    subject_id: "neet-biology",
    title: item.title,
    slug: item.slug,
    sort_order: item.sort_order,
    source_page: item.source_page,
  }));
}

export function getBiologyBatch4Cards() {
  const transport = chapter("transportation-in-plants");
  const minerals = chapter("minerals-nutrition");
  const photosynthesis = chapter("photosynthesis");
  const respiration = chapter("respiration-in-plants");
  const growth = chapter("plant-growth-and-development");

  return [
    ...transportationCards(transport),
    ...mineralsCards(minerals),
    ...photosynthesisCards(photosynthesis),
    ...respirationCards(respiration),
    ...growthCards(growth),
  ];
}
