export const BIOLOGY_BATCH_1_CHAPTER_DEFINITIONS = [
  { title: "The Living World", slug: "the-living-world", sort_order: 1, source_page: 3 },
  { title: "Biological Classification", slug: "biological-classification", sort_order: 2, source_page: 5 },
  { title: "Plant Kingdom", slug: "plant-kingdom", sort_order: 3, source_page: 9 },
  { title: "Animal Kingdom", slug: "animal-kingdom", sort_order: 4, source_page: 14 },
];

const chapter = (slug) => `neet-biology-${slug}`;

function table(columns, rows) {
  return { columns, rows };
}

function sections(items) {
  return { sections: items };
}

function recall(question, answer, key_points = [], examples = [], neet_traps = []) {
  return { recall_question: question, reveal_answer: answer, key_points, examples, neet_traps };
}

function card(chapterId, slug, payload) {
  return {
    id: `${chapterId}-${slug}`,
    chapter_id: chapterId,
    formulas: [],
    variables: [],
    conditions: [],
    table_data: null,
    diagram_data: null,
    diagram_svg: null,
    is_active: true,
    ...payload,
  };
}

function livingWorldCards(chapterId) {
  return [
    card(chapterId, "life-definition", {
      title: "Living Organism Core Description",
      card_type: "concept",
      body: "Life expresses through chemical reactions leading to growth, development, responsiveness, adaptation and reproduction.",
      recall_data: recall("How does the source describe a living organism?", "A self-replicating, evolving and self-regulating interactive system capable of responding to external stimuli.", [
        "Life is a unique, complex organization of molecules.",
        "The expression of life is through chemical reactions.",
      ]),
      importance: 4,
      source_page: 3,
      sort_order: 1,
    }),
    card(chapterId, "growth-trap", {
      title: "Growth Is Not Perfectly Defining",
      card_type: "neet_trap",
      body: "Growth means increase in number and mass of cells by cell division, but non-living objects also grow by surface accumulation.",
      recall_data: recall("Why is growth not a perfect defining property of living organisms?", "Because non-living objects also grow by surface accumulation of material.", [
        "Plants grow throughout their lifespan.",
        "Animals grow only up to a certain age, though cell division replaces lost cells.",
        "In living organisms, growth is from inside.",
      ], [], ["Growth alone cannot define life."]),
      importance: 5,
      source_page: 3,
      sort_order: 2,
    }),
    card(chapterId, "reproduction-trap", {
      title: "Reproduction Is Not Perfectly Defining",
      card_type: "neet_trap",
      body: "Reproduction produces progeny similar to parents, but many living organisms do not reproduce.",
      recall_data: recall("Why is reproduction not a perfect defining property of living organisms?", "Many organisms do not reproduce, so reproduction cannot alone define life.", [
        "Organisms reproduce asexually and sexually.",
        "In unicellular organisms, growth and reproduction are same because they reproduce by cell division.",
      ], ["mules", "worker bees", "infertile human couples"], ["Reproduction is absent in some living organisms."]),
      importance: 5,
      source_page: 3,
      sort_order: 3,
    }),
    card(chapterId, "metabolism-defining", {
      title: "Metabolism",
      card_type: "concept",
      body: "Metabolism is the sum total of all biochemical reactions taking place inside a living system.",
      recall_data: recall("Which property is listed as a defining feature of living organisms: metabolism or isolated in vitro reactions?", "Metabolism is defining; isolated metabolic reactions in vitro are living reactions but not living things.", [
        "Metabolic reactions can be demonstrated outside the body in cell-free systems.",
      ], [], ["Metabolism is a defining feature of living organisms."]),
      importance: 5,
      source_page: 3,
      sort_order: 4,
    }),
    card(chapterId, "cellular-organization", {
      title: "Cellular Organization",
      card_type: "concept",
      body: "Organisms are made up of one or more cells.",
      recall_data: recall("Why is cellular organization important as a life property?", "It is a defining feature of living organisms.", ["A living organism is organized at cellular level, whether one-celled or many-celled."]),
      importance: 5,
      source_page: 3,
      sort_order: 5,
    }),
    card(chapterId, "consciousness-defining", {
      title: "Consciousness",
      card_type: "neet_trap",
      body: "Consciousness is the ability to sense environment and respond to environmental stimuli.",
      recall_data: recall("What makes consciousness a defining property in the source?", "All organisms are aware of their surroundings and respond to stimuli.", [
        "Stimuli include light, water, temperature, other organisms, chemicals and pollutants.",
        "Human is the only organism having self-consciousness.",
      ], [], ["Consciousness is a defining property."]),
      importance: 5,
      source_page: 3,
      sort_order: 6,
    }),
    card(chapterId, "biodiversity-number", {
      title: "Biodiversity",
      card_type: "fact",
      body: "Biodiversity refers to the number and types of organisms present on earth.",
      recall_data: recall("How many species are described according to the source?", "1.7-1.8 million species.", ["Biodiversity means number and types of organisms on earth."]),
      importance: 4,
      source_page: 3,
      sort_order: 7,
    }),
    card(chapterId, "taxonomy-systematics", {
      title: "Taxonomy vs Systematics",
      card_type: "comparison",
      body: "Taxonomy and systematics are related but not identical.",
      table_data: table(["Term", "Recall answer"], [
        ["Taxonomy", "Study of identification, classification and nomenclature of organisms."],
        ["Systematics", "Deals with evolutionary relationships among organisms."],
        ["Systema Naturae", "Book written by Linnaeus."],
      ]),
      recall_data: recall("Taxonomy vs systematics: what is the NEET distinction?", "Taxonomy covers identification, classification and nomenclature; systematics deals with evolutionary relationships.", ["Systematics comes from Latin systema = systematic arrangement."], ["Systema Naturae - Linnaeus"]),
      importance: 5,
      source_page: 3,
      sort_order: 8,
    }),
    card(chapterId, "taxonomy-processes", {
      title: "Basic Processes of Taxonomy",
      card_type: "classification",
      body: "The source lists four basic processes of taxonomy.",
      table_data: table(["Process", "Recall answer"], [
        ["Characterization", "Understanding characters such as external/internal structure, cell structure, development process and ecological information."],
        ["Identification", "Correct description of the organism so naming is possible."],
        ["Classification", "Grouping organisms into convenient categories (taxa) based on characters."],
        ["Nomenclature", "Standardization of names so an organism is known by the same name worldwide."],
      ]),
      recall_data: recall("Name the four basic taxonomy processes in order.", "Characterization, identification, classification and nomenclature.", [], [], ["Do not merge identification with nomenclature."]),
      importance: 5,
      source_page: 3,
      sort_order: 9,
    }),
    card(chapterId, "binomial-rules", {
      title: "Binomial Nomenclature Rules",
      card_type: "rule",
      body: "Binomial nomenclature is the two-component naming system proposed by Linnaeus.",
      table_data: table(["Rule", "Source-backed detail"], [
        ["Components", "First word is genus name; second word is species name/specific epithet."],
        ["Typography", "Scientific names are in Latin or Latinised and written in italics; handwritten names are underlined separately."],
        ["Capitalization", "Genus starts with capital letter; species starts with small letter."],
        ["Author", "Name of author in abbreviated form appears at the end of biological name."],
        ["Codes", "Botanical names follow ICBN; zoological names follow ICZN."],
      ]),
      recall_data: recall("What are the universal binomial nomenclature rules given in the source?", "Latin/Latinised italic names, genus first and capitalized, species second and lowercase, with abbreviated author name when given.", [], ["Homo sapiens", "Mangifera indica Linn."], ["ICBN for botanical names; ICZN for zoological names."]),
      importance: 5,
      source_page: 3,
      sort_order: 10,
    }),
    card(chapterId, "taxonomic-hierarchy-visual", {
      title: "Taxonomic Hierarchy",
      card_type: "diagram",
      body: "Classification involves hierarchy of taxonomic categories. All categories together form the taxonomic hierarchy.",
      diagram_data: { type: "bio-taxonomic-hierarchy" },
      table_data: table(["Ascending rank", "Example taxon"], [
        ["Species", "Sapiens"],
        ["Genus", "Homo"],
        ["Family", "Hominidae"],
        ["Order", "Primata"],
        ["Class", "Mammalia"],
        ["Phylum/Division", "Chordata"],
        ["Kingdom", "Animalia"],
      ]),
      recall_data: recall("Recall the taxonomic hierarchy in ascending order.", "Species -> Genus -> Family -> Order -> Class -> Phylum/Division -> Kingdom.", ["A group occupying a category is called a taxon."], ["Class Mammalia"]),
      importance: 5,
      source_page: 3,
      sort_order: 11,
    }),
    card(chapterId, "species-genus", {
      title: "Species and Genus",
      card_type: "examples",
      body: "Species is the lowest category; genus aggregates closely related species.",
      table_data: table(["Common name", "Generic name", "Specific epithet"], [
        ["Mango", "Mangifera", "indica"],
        ["Potato", "Solanum", "tuberosum"],
        ["Nightshade", "Solanum", "nigrum"],
        ["Tomato", "Solanum", "lycopersicum"],
        ["Brinjal", "Solanum", "melongena"],
        ["Lion", "Panthera", "leo"],
        ["Tiger", "Panthera", "tigris"],
        ["Leopard", "Panthera", "pardus"],
        ["Modern man", "Homo", "sapiens"],
      ]),
      recall_data: recall("Species vs genus: what should you recall?", "Species is closely related interbreeding organisms producing fertile offspring; genus is an aggregate of closely related species.", ["Species is the lowest category."], ["Solanum: potato, tomato, brinjal", "Panthera: lion, leopard, tiger"]),
      importance: 5,
      source_page: 4,
      sort_order: 12,
    }),
    card(chapterId, "higher-taxa", {
      title: "Family to Kingdom",
      card_type: "classification",
      body: "Higher taxa are assemblages of related lower taxa.",
      table_data: table(["Category", "Definition", "Source examples"], [
        ["Family", "Group of closely related genera.", "Solanaceae includes Solanum, Petunia, Datura; Felidae includes Panthera and Felis."],
        ["Order", "Assemblage of related families.", "Polymoniales includes Convolvulaceae and Solanaceae; Carnivora includes Felidae and Canidae."],
        ["Class", "Assemblage of related orders.", "Primata, Carnivora etc. placed in Mammalia."],
        ["Phylum/Division", "Assemblage of related classes.", "Amphibia, Reptilia, Aves, Mammalia under Chordata."],
        ["Kingdom", "Assemblage of related phyla; highest category.", "Plantae, Animalia."],
      ]),
      recall_data: recall("How do family, order, class, phylum/division and kingdom relate?", "Each higher category is an assemblage of related lower categories.", [], [], ["Division is used in case of plants."]),
      importance: 4,
      source_page: 4,
      sort_order: 13,
    }),
    card(chapterId, "organism-taxonomy-table", {
      title: "Organisms with Taxonomic Categories",
      card_type: "table",
      body: "The source compares taxonomic categories for man, housefly, mango and wheat.",
      table_data: table(["Category", "Man", "Housefly", "Mango", "Wheat"], [
        ["Biological name", "Homo sapiens", "Musca domestica", "Mangifera indica", "Triticum aestivum"],
        ["Species", "sapiens", "domestica", "indica", "aestivum"],
        ["Genus", "Homo", "Musca", "Mangifera", "Triticum"],
        ["Family", "Hominidae", "Muscidae", "Anacardiaceae", "Poaceae"],
        ["Order", "Primata", "Diptera", "Sapindales", "Poales"],
        ["Class", "Mammalia", "Insecta", "Dicotyledonae", "Monocotyledonae"],
        ["Phylum/Division", "Chordata", "Arthropoda", "Angiospermae", "Angiospermae"],
        ["Kingdom", "Animalia", "Animalia", "Plantae", "Plantae"],
      ]),
      recall_data: recall("What are the four organisms in the source taxonomy table?", "Man, housefly, mango and wheat.", [], ["Homo sapiens", "Musca domestica", "Mangifera indica", "Triticum aestivum"]),
      importance: 5,
      source_page: 4,
      sort_order: 14,
    }),
    card(chapterId, "taxonomical-aids-comparison", {
      title: "Taxonomical Aids Comparison",
      card_type: "comparison",
      body: "Taxonomical aids support identification, study and reference.",
      table_data: table(["Aid", "Recall use", "Key source detail"], [
        ["Herbarium", "Repository of dried, pressed and preserved plant specimens.", "Sheets are labelled with date/place of collection, English/local/botanical names, family and collector's name."],
        ["Botanical gardens", "Living plant collections for reference and identification.", "Each plant is labelled with botanical name and family."],
        ["Biological Museum", "Collection of preserved plants and animals for study and reference.", "Includes preservative jars, dry specimens, insect boxes, stuffed animals and skeletons."],
        ["Zoological Parks", "Live wild animals kept in protected environments under human care.", "Helps learn food habits and behaviour."],
        ["Key", "Analytical method of identification based on similarities and dissimilarities.", "Based on contrasting paired characters called couplet; each statement is a lead."],
      ]),
      recall_data: recall("Compare herbarium, botanical garden, museum, zoo and key.", "Herbarium preserves plant specimens; botanical gardens keep living plants; museums keep preserved specimens; zoos keep live wild animals; keys identify by contrasting couplets.", [], ["Royal Botanical Garden at Kew", "Indian Botanical Garden, Howrah", "National Botanical Research Institute, Lucknow"]),
      importance: 5,
      source_page: 4,
      sort_order: 15,
    }),
    card(chapterId, "flora-manuals-monographs-catalogue", {
      title: "Flora, Manuals, Monographs and Catalogue",
      card_type: "comparison",
      body: "The source gives four quick-reference records used in taxonomy.",
      table_data: table(["Record", "Recall answer"], [
        ["Flora", "Actual account of habitat and distribution of plant species of a given area."],
        ["Manuals", "Record containing information for identification of names of species found in an area."],
        ["Monographs", "Records containing information on any one taxon."],
        ["Catalogue", "Alphabetical list of species."],
      ]),
      recall_data: recall("Flora vs manuals vs monographs vs catalogue?", "Flora = habitat/distribution; manuals = identification of names in an area; monographs = one taxon; catalogue = alphabetical species list."),
      importance: 4,
      source_page: 4,
      sort_order: 16,
    }),
  ];
}

function biologicalClassificationCards(chapterId) {
  return [
    card(chapterId, "early-classification", {
      title: "Aristotle and Linnaeus",
      card_type: "classification",
      body: "The source contrasts Aristotle's early scientific attempt with Linnaeus's two-kingdom classification.",
      table_data: table(["System", "Recall answer"], [
        ["Aristotle", "Plants into trees, shrubs and herbs; animals into those with red blood and without red blood."],
        ["Linnaeus (1758)", "Two kingdoms: Kingdom Plantae and Kingdom Animalia."],
      ]),
      recall_data: recall("What were Aristotle's and Linnaeus's classification bases?", "Aristotle used plant habit and animal blood; Linnaeus used Plantae and Animalia.", [], [], ["Linnaeus year in source: 1758."]),
      importance: 4,
      source_page: 5,
      sort_order: 1,
    }),
    card(chapterId, "two-kingdom-drawbacks", {
      title: "Drawbacks of Two-Kingdom Classification",
      card_type: "neet_trap",
      body: "The two-kingdom system grouped organisms together despite major differences.",
      recall_data: recall("What drawbacks of the two-kingdom classification are listed?", "It grouped prokaryotes with eukaryotes, unicellular with multicellular forms, and heterotrophic fungi with autotrophic green plants.", [
        "Bacteria/cyanobacteria and fungi/mosses/ferns/gymnosperms/angiosperms were included under plants based on cell wall.",
        "Chlamydomonas and Spirogyra were placed under algae.",
        "Fungi have chitinous cell wall; green plants have cellulosic cell wall.",
      ]),
      importance: 5,
      source_page: 5,
      sort_order: 2,
    }),
    card(chapterId, "five-kingdom-criteria", {
      title: "Whittaker Five Kingdom Classification",
      card_type: "classification",
      body: "R.H. Whittaker proposed five kingdoms in 1969.",
      recall_data: recall("What are Whittaker's five kingdoms and criteria?", "Monera, Protista, Fungi, Plantae and Animalia; based on cell structure, thallus organization, mode of nutrition, reproduction and phylogenetic relationships.", [
        "Three-domain system divides Kingdom Monera into two domains; eukaryotic kingdoms are in the third domain.",
      ]),
      importance: 5,
      source_page: 5,
      sort_order: 3,
    }),
    card(chapterId, "five-kingdom-comparison", {
      title: "Five Kingdom Comparison",
      card_type: "comparison",
      body: "The source table compares the five kingdoms by cell type, wall, nuclear membrane, organization and nutrition.",
      table_data: table(["Character", "Monera", "Protista", "Fungi", "Plantae", "Animalia"], [
        ["Cell type", "Prokaryotic", "Eukaryotic", "Eukaryotic", "Eukaryotic", "Eukaryotic"],
        ["Cell wall", "Non-cellulosic (polysaccharide + amino acid)", "Present in some", "Present (Chitin & polysaccharides)", "Present (Cellulose)", "Absent"],
        ["Nuclear membrane", "Absent", "Present", "Present", "Present", "Present"],
        ["Body organisation", "Cellular", "Cellular", "Multicellular, loose tissue", "Tissue/organ", "Tissue/organ/organ system"],
        ["Mode of nutrition", "Autotrophic and heterotrophic", "Autotrophic and heterotrophic", "Heterotrophic", "Autotrophic", "Heterotrophic"],
      ]),
      recall_data: recall("Fast compare the five kingdoms.", "Monera is prokaryotic; the other four are eukaryotic. Animalia lacks cell wall; Plantae has cellulose wall; Fungi has chitin and polysaccharide wall.", [], [], ["Monera is the only one with absent nuclear membrane."]),
      importance: 5,
      source_page: 5,
      sort_order: 4,
    }),
    card(chapterId, "monera-bacteria-shapes", {
      title: "Monera and Bacterial Shapes",
      card_type: "classification",
      body: "Bacteria are the most abundant microorganisms and occur even in extreme habitats.",
      table_data: table(["Shape", "Source term"], [
        ["Spherical", "Coccus"],
        ["Rod-shaped", "Bacillus"],
        ["Comma-shaped", "Vibrium"],
        ["Spiral", "Spirillum"],
      ]),
      recall_data: recall("Name the four bacterial shapes in the source.", "Coccus, Bacillus, Vibrium and Spirillum.", ["Some bacteria are autotrophic; majority are heterotrophs."]),
      importance: 4,
      source_page: 5,
      sort_order: 5,
    }),
    card(chapterId, "archaebacteria-vs-eubacteria", {
      title: "Archaebacteria vs Eubacteria",
      card_type: "comparison",
      body: "The source separates archaebacteria from true bacteria.",
      table_data: table(["Group", "Key recall", "Examples/source details"], [
        ["Archaebacteria", "Live in harshest habitats and have different cell wall structure.", "Halophiles, thermoacidophiles, methanogens; methanogens occur in guts of cows and buffaloes and produce methane/biogas."],
        ["Eubacteria", "True bacteria with rigid cell wall and flagellum if motile.", "Include autotrophs and heterotrophs."],
      ]),
      recall_data: recall("Archaebacteria vs eubacteria?", "Archaebacteria survive extreme conditions with different cell wall structure; eubacteria are true bacteria with rigid wall and flagellum if motile.", [], ["halophiles", "thermoacidophiles", "methanogens"]),
      importance: 5,
      source_page: 5,
      sort_order: 6,
    }),
    card(chapterId, "eubacteria-types", {
      title: "Eubacteria Types",
      card_type: "comparison",
      body: "Eubacteria include photosynthetic autotrophs, chemosynthetic autotrophs and heterotrophs.",
      table_data: table(["Type", "Recall answer", "Examples/roles"], [
        ["Cyanobacteria", "Photosynthetic autotrophs with chlorophyll a similar to green plants.", "Unicellular, colonial or filamentous; Nostoc and Anabaena fix atmospheric nitrogen in heterocysts."],
        ["Chemosynthetic autotrophs", "Oxidize inorganic substances such as nitrates, nitrites and ammonia for ATP production.", "Recycle nitrogen, phosphorous, iron and sulphur."],
        ["Heterotrophic bacteria", "Most abundant in nature; major decomposers.", "Curd, antibiotics, nitrogen fixation; diseases: cholera, typhoid, tetanus, citrus canker."],
      ]),
      recall_data: recall("What are the three eubacterial groups emphasized?", "Cyanobacteria, chemosynthetic autotrophs and heterotrophic bacteria.", [], ["Nostoc", "Anabaena", "cholera", "typhoid", "tetanus", "citrus canker"]),
      importance: 5,
      source_page: 5,
      sort_order: 7,
    }),
    card(chapterId, "bacterial-reproduction-mycoplasma", {
      title: "Bacterial Reproduction and Mycoplasma",
      card_type: "fact",
      body: "Bacteria mainly reproduce by fission and produce spores under unfavourable conditions.",
      recall_data: recall("How do bacteria reproduce, and what is special about Mycoplasma?", "Bacteria mainly reproduce by fission; they form spores in unfavourable conditions and can transfer DNA sexually. Mycoplasmas lack cell wall and are the smallest living cells.", [
        "Mycoplasmas can survive without oxygen.",
        "Many are pathogenic in animals and plants.",
      ]),
      importance: 5,
      source_page: 6,
      sort_order: 8,
    }),
    card(chapterId, "protista-overview", {
      title: "Kingdom Protista",
      card_type: "classification",
      body: "Protista includes single-celled eukaryotes and links plants, animals and fungi.",
      recall_data: recall("What are the source traits of Protista?", "Single-celled eukaryotes with well-defined nucleus and membrane-bound organelles; primarily aquatic; reproduce asexually and sexually.", [
        "Some protists have flagella or cilia.",
        "Groups: Chrysophytes, Dianoflagellates, Euglenoids, Slime moulds, Protozoans.",
      ]),
      importance: 4,
      source_page: 6,
      sort_order: 9,
    }),
    card(chapterId, "protist-groups", {
      title: "Protist Groups",
      card_type: "comparison",
      body: "The source naturally compares major protist groups.",
      table_data: table(["Group", "Recall hook", "Examples/source facts"], [
        ["Chrysophytes", "Diatoms and golden algae/desmids; planktonic, mostly photosynthetic.", "Diatomaceous earth used in polishing and filtration of oils and syrups; diatoms are chief producers in oceans."],
        ["Dinoflagellates", "Mostly marine, photosynthetic, with stiff cellulose plates and two flagella.", "Gonyaulax causes red tides and releases toxins that kill fishes."],
        ["Euglenoids", "Freshwater stagnant forms with protein-rich pellicle instead of cell wall.", "Photosynthetic in sunlight; heterotrophic without sunlight; example Euglena."],
        ["Slime moulds", "Saprophytic protists forming plasmodium and resistant spores.", "Spores survive many years and disperse by air."],
        ["Protozoans", "Heterotrophs, primitive relatives of animals.", "Amoeba, Entamoeba, Trypanosoma, Paramoecium, Plasmodium."],
      ]),
      recall_data: recall("Compare the five protist groups from the source.", "Chrysophytes, Dinoflagellates, Euglenoids, Slime moulds and Protozoans have distinct nutrition, coverings, movement and examples.", [], ["Euglena", "Gonyaulax", "Amoeba", "Entamoeba", "Trypanosoma", "Paramoecium", "Plasmodium"]),
      importance: 5,
      source_page: 6,
      sort_order: 10,
    }),
    card(chapterId, "protozoan-groups", {
      title: "Four Protozoan Groups",
      card_type: "classification",
      body: "Protozoans are heterotrophs and primitive relatives of animals.",
      table_data: table(["Protozoan group", "Recall feature", "Example"], [
        ["Amoeboid protozoans", "Move and capture prey by pseudopodia; marine forms may have silica shells.", "Amoeba; Entamoeba"],
        ["Flagellated protozoans", "Free-living or parasitic with flagella; parasitic forms cause sleeping sickness.", "Trypanosoma"],
        ["Ciliated protozoans", "Aquatic, actively moving with cilia; gullet opens outside.", "Paramoecium"],
        ["Sporozoans", "Infectious spore-like stage in life cycle.", "Plasmodium (malarial parasite)"],
      ]),
      recall_data: recall("What are the four major protozoan groups?", "Amoeboid, flagellated, ciliated and sporozoans.", [], ["Amoeba", "Entamoeba", "Trypanosoma", "Paramoecium", "Plasmodium"]),
      importance: 5,
      source_page: 6,
      sort_order: 11,
    }),
    card(chapterId, "fungi-overview-hyphae", {
      title: "Fungi, Hyphae and Mycelium",
      card_type: "concept",
      body: "Fungi are a unique kingdom of heterotrophic organisms; except yeasts, fungi are filamentous.",
      table_data: table(["Term", "Recall answer"], [
        ["Hyphae", "Thread-like structures forming fungal body."],
        ["Mycelium", "Network of hyphae."],
        ["Coenocytic hyphae", "Continuous tubes filled with multinucleated cytoplasm."],
        ["Septate hyphae", "Hyphae with septae or cross walls."],
        ["Cell wall", "Made of chitin and polysaccharides."],
      ]),
      recall_data: recall("Coenocytic vs septate hyphae?", "Coenocytic hyphae are continuous multinucleated tubes; septate hyphae have cross walls.", [], ["yeast", "Penicillium", "Puccinia"]),
      importance: 5,
      source_page: 6,
      sort_order: 12,
    }),
    card(chapterId, "fungal-reproduction", {
      title: "Fungal Reproduction",
      card_type: "process",
      body: "Fungi reproduce vegetatively, asexually and sexually.",
      table_data: table(["Mode", "Source-backed recall"], [
        ["Vegetative propagation", "Fragmentation, fission and budding."],
        ["Asexual reproduction", "Spores such as conidia, sporangiospores and zoospores."],
        ["Sexual reproduction", "Oospores, ascospores and basidiospores in fruiting bodies."],
        ["Sexual cycle", "Plasmogamy, karyogamy and meiosis in zygote."],
        ["Dikaryon", "Dikaryotic stage (n + n) in ascomycetes and basidiomycetes."],
      ]),
      recall_data: recall("Recall the fungal sexual cycle.", "Plasmogamy -> karyogamy -> meiosis in zygote to give haploid spores.", ["Dikaryophase means two nuclei per cell, n + n."]),
      importance: 5,
      source_page: 7,
      sort_order: 13,
    }),
    card(chapterId, "fungal-classes-comparison", {
      title: "Fungal Classes Comparison",
      card_type: "comparison",
      body: "Fungi are classified by morphology of mycelium, mode of spore formation and fruiting bodies.",
      table_data: table(["Class", "Mycelium", "Asexual", "Sexual", "Examples"], [
        ["Phycomycetes", "Aseptate and coenocytic", "Motile zoospores or non-motile aplanospores in sporangium", "Zygospores by fusion of gametes", "Mucor, Rhizopus (bread mould), Albugo"],
        ["Ascomycetes", "Branched and septate", "Conidia exogenously on conidiophores", "Ascospores endogenously in asci; asci form ascocarps", "Aspergillus, Claviceps, Neurospora"],
        ["Basidiomycetes", "Branched and septate", "Generally not found; fragmentation common", "Basidiospores exogenously on basidium; basidia in basidiocarps", "Agaricus, Ustilago, Puccinia"],
        ["Deuteromycetes", "Septate and branched", "Only asexual spores (conidia)", "Sexual phase not known", "Alternaria, Colletotrichum, Trichoderma"],
      ]),
      recall_data: recall("Compare phycomycetes, ascomycetes, basidiomycetes and deuteromycetes.", "Use mycelium and spore type: phycomycetes coenocytic; ascomycetes asci; basidiomycetes basidia; deuteromycetes only asexual/vegetative phase known.", [], ["Mucor", "Rhizopus", "Albugo", "Aspergillus", "Claviceps", "Neurospora", "Agaricus", "Ustilago", "Puccinia", "Alternaria", "Colletotrichum", "Trichoderma"]),
      importance: 5,
      source_page: 7,
      sort_order: 14,
    }),
    card(chapterId, "plantae-animalia", {
      title: "Plantae vs Animalia",
      card_type: "comparison",
      body: "The source summarizes Plantae and Animalia after fungi.",
      table_data: table(["Kingdom", "Recall answer", "Examples/source details"], [
        ["Plantae", "Eukaryotic chlorophyll-containing organisms with cellulosic cell wall.", "Includes algae, bryophytes, pteridophytes, gymnosperms and angiosperms; partial heterotrophs include bladderwort, Venus flytrap; parasite Cuscuta."],
        ["Animalia", "Multicellular, heterotrophic, eukaryotic organisms without cell wall.", "Holozoic nutrition; reserve food as glycogen or fat; most can locomote."],
      ]),
      recall_data: recall("Plantae vs Animalia in five-kingdom classification?", "Plantae are chlorophyll-containing with cellulosic wall; Animalia are multicellular heterotrophs without cell wall.", [], ["bladderwort", "Venus flytrap", "Cuscuta"]),
      importance: 4,
      source_page: 7,
      sort_order: 15,
    }),
    card(chapterId, "virus-viroid-prion", {
      title: "Virus vs Viroid vs Prion",
      card_type: "comparison",
      body: "Acellular organisms are not included in five-kingdom classification.",
      table_data: table(["Agent", "Recall answer", "Source facts"], [
        ["Virus", "Non-cellular, not truly living, obligate parasite; nucleoprotein with capsid and RNA or DNA.", "No virus contains both RNA and DNA; plant viruses generally ssRNA; bacteriophages usually dsDNA."],
        ["Viroid", "Free low molecular weight RNA with no protein coat; smaller than viruses.", "Discovered by T.O. Diener (1971); potato spindle tuber disease."],
        ["Prion", "Abnormally folded protein causing infectious neurological diseases.", "BSE/mad cow disease in cattle and variant Cr-Jacob disease (CJD) in humans."],
      ]),
      recall_data: recall("Virus vs viroid vs prion?", "Virus = nucleoprotein with capsid and one nucleic acid type; viroid = free low molecular weight RNA without protein coat; prion = abnormally folded protein.", [], ["mumps", "small pox", "herpes", "influenza", "AIDS", "potato spindle tuber disease", "BSE", "CJD"], ["No virus contains both RNA and DNA."]),
      importance: 5,
      source_page: 8,
      sort_order: 16,
    }),
    card(chapterId, "virus-history", {
      title: "Virus Discovery Timeline",
      card_type: "sequence",
      body: "The source names four scientists in virus history.",
      table_data: table(["Scientist", "Year/source contribution"], [
        ["Louis Pasteur", "Gave the name virus, meaning venom or poisonous fluid."],
        ["D.J. Ivanowsky", "1892: discovered virus while studying tobacco mosaic disease."],
        ["M.W. Beijerinek", "1898: called infected extract Contagium vivum fluidum."],
        ["W.M. Stanley", "1935: showed viruses could be crystallized and crystals largely consist of proteins."],
      ]),
      recall_data: recall("Recall the virus-history sequence.", "Pasteur named virus; Ivanowsky discovered virus in 1892; Beijerinek named infectious living fluid in 1898; Stanley crystallized viruses in 1935."),
      importance: 4,
      source_page: 8,
      sort_order: 17,
    }),
    card(chapterId, "lichens", {
      title: "Lichens",
      card_type: "concept",
      body: "Lichens are symbiotic associations between algae and fungi.",
      recall_data: recall("What is a lichen and why is it a pollution indicator?", "It is a mutually useful association between algae and fungi; lichens do not grow in polluted areas.", [
        "Algal component is phycobiont and is autotrophic.",
        "Fungal component is mycobiont and is heterotrophic.",
        "Algae prepare food; fungi provide shelter and absorb mineral nutrients and water.",
      ]),
      importance: 5,
      source_page: 8,
      sort_order: 18,
    }),
  ];
}

function plantKingdomCards(chapterId) {
  return [
    card(chapterId, "classification-systems", {
      title: "Plant Classification Systems",
      card_type: "comparison",
      body: "The source compares artificial, natural and phylogenetic classification systems.",
      table_data: table(["System", "Basis", "Source detail"], [
        ["Artificial", "Vegetative or superficial morphological characters.", "Linnaeus's artificial system was based on androecium structure; drawbacks include separating related species and equal weightage to vegetative and sexual characters."],
        ["Natural", "Natural affinities among organisms.", "Considers external and internal features: ultrastructure, anatomy, embryology and phytochemistry; Bentham and Hooker classification."],
        ["Phylogenetic", "Evolutionary relationships.", "Assumes organisms in the same taxa have a common ancestor."],
      ]),
      recall_data: recall("Artificial vs natural vs phylogenetic plant classification?", "Artificial uses superficial characters; natural uses natural affinities and internal/external features; phylogenetic uses evolutionary relationships.", [], ["George Bentham", "Joseph Dalton Hooker"]),
      importance: 5,
      source_page: 9,
      sort_order: 1,
    }),
    card(chapterId, "taxonomy-methods", {
      title: "Numerical, Cyto and Chemotaxonomy",
      card_type: "comparison",
      body: "The source lists three additional sources for resolving classification problems.",
      table_data: table(["Method", "Recall answer"], [
        ["Numerical taxonomy", "Based on all observable characteristics; numbers and codes are assigned and computer processed."],
        ["Cytotaxonomy", "Based on cytological information such as chromosome number, structure and behaviour."],
        ["Chemotaxonomy", "Uses chemical constituents of plants."],
      ]),
      recall_data: recall("Numerical taxonomy vs cytotaxonomy vs chemotaxonomy?", "Numerical = observable coded characters; cytotaxonomy = chromosome/cytological information; chemotaxonomy = chemical constituents."),
      importance: 4,
      source_page: 9,
      sort_order: 2,
    }),
    card(chapterId, "algae-overview", {
      title: "Algae Overview",
      card_type: "concept",
      body: "Algae are simple, thalloid, autotrophic, chlorophyll-bearing aquatic organisms.",
      recall_data: recall("What are the source traits and forms of algae?", "Simple thalloid autotrophs, mostly aquatic; forms vary from unicellular to colonial to filamentous.", [
        "They also occur on moist stones, soils and wood.",
        "Some occur with fungi in lichen and with animals such as on sloth bear.",
      ], ["Chlamydomonas", "Volvox", "Ulothrix", "Spirogyra"]),
      importance: 5,
      source_page: 9,
      sort_order: 3,
    }),
    card(chapterId, "algae-reproduction", {
      title: "Reproduction in Algae",
      card_type: "process",
      body: "Algae reproduce vegetatively, asexually and sexually.",
      table_data: table(["Mode", "Recall answer", "Examples/source details"], [
        ["Vegetative", "By fragmentation; each fragment develops into a thallus.", ""],
        ["Asexual", "By spores; zoospores are most common, flagellated and motile.", "Zoospores germinate to new plants."],
        ["Isogamous sexual", "Fusion of gametes similar in size.", "Flagellated Ulothrix; non-flagellated Spirogyra."],
        ["Anisogamous sexual", "Fusion of two gametes dissimilar in size.", "Some species of Eudorina."],
        ["Oogamous sexual", "Large non-motile female gamete and smaller motile male gamete.", "Volvox, Fucus."],
      ]),
      recall_data: recall("Isogamy vs anisogamy vs oogamy in algae?", "Isogamy = similar gametes; anisogamy = dissimilar gametes; oogamy = large non-motile female and smaller motile male gamete.", [], ["Ulothrix", "Spirogyra", "Eudorina", "Volvox", "Fucus"]),
      importance: 5,
      source_page: 9,
      sort_order: 4,
    }),
    card(chapterId, "algae-economic-importance", {
      title: "Algae Economic Importance",
      card_type: "examples",
      body: "The source lists ecological and commercial benefits of algae.",
      table_data: table(["Benefit", "Source detail"], [
        ["Photosynthesis", "Fix half of the total CO2 on earth and increase dissolved oxygen."],
        ["Food cycles", "Primary producers and basis of food cycles of all aquatic animals."],
        ["Food", "Many marine algae (70 species) used as food: Porphyra, Laminaria, Sargassum."],
        ["Agar", "From Gelidium and Gracilaria; used to grow microbes and in ice-creams and jellies."],
        ["Hydrocolloids", "Algin from brown algae and carrageen from red algae; commercially used."],
        ["Food supplements", "Chlorella and Spirullina used as food supplements by space travellers."],
      ]),
      recall_data: recall("Recall the source examples for economic importance of algae.", "Porphyra, Laminaria, Sargassum, Gelidium, Gracilaria, Chlorella and Spirullina.", [], ["algin", "carrageen"]),
      importance: 5,
      source_page: 9,
      sort_order: 5,
    }),
    card(chapterId, "algae-groups-comparison", {
      title: "Green vs Brown vs Red Algae",
      card_type: "comparison",
      body: "The source table compares Chlorophyceae, Phaeophyceae and Rhodophyceae.",
      diagram_data: { type: "bio-algae-comparison" },
      table_data: table(["Character", "Chlorophyceae", "Phaeophyceae", "Rhodophyceae"], [
        ["Major pigments", "Chlorophyll a, b", "Chlorophyll a, c, Fucoxanthin", "Chlorophyll a, d, Phycoerythrin"],
        ["Stored food", "Starch", "Mannitol, laminarin", "Floridean Starch"],
        ["Cell wall", "Cellulose", "Cellulose and algin", "Cellulose"],
        ["Flagella", "2-8, equal, apical", "2, unequal, lateral", "Absent"],
        ["Habitat", "Fresh water, salt water and brackish water", "Fresh water (rare), salt water and brackish water", "Fresh water (some), salt water (most) and brackish water"],
      ]),
      recall_data: recall("Compare Chlorophyceae, Phaeophyceae and Rhodophyceae.", "Green algae: chlorophyll a,b and starch; brown algae: chlorophyll a,c, fucoxanthin and mannitol/laminarin; red algae: chlorophyll a,d, phycoerythrin and floridean starch.", [], ["Chlamydomonas", "Volvox", "Ulothrix", "Spirogyra", "Chara", "Ectocarpus", "Dictyota", "Laminaria", "Sargassum", "Fucus", "Polysiphonia", "Porphyra", "Gracilaria", "Gelidium"]),
      importance: 5,
      source_page: 10,
      sort_order: 6,
    }),
    card(chapterId, "bryophytes", {
      title: "Bryophytes",
      card_type: "concept",
      body: "Bryophytes are called amphibians of the plant kingdom because they need water for sexual reproduction.",
      recall_data: recall("Why are bryophytes called amphibians of the plant kingdom?", "They can live in soil but need water for sexual reproduction.", [
        "They occur in damp, humid and shaded localities.",
        "Main plant body is haploid gametophyte.",
        "They lack true roots, stem or leaves but may possess root-like, leaf-like or stem-like structures.",
      ]),
      importance: 5,
      source_page: 10,
      sort_order: 7,
    }),
    card(chapterId, "liverworts-mosses", {
      title: "Liverworts vs Mosses",
      card_type: "comparison",
      body: "The source divides bryophytes into liverworts and mosses.",
      table_data: table(["Group", "Recall points", "Examples"], [
        ["Liverworts", "Usually moist shady habitats; plant body thalloid; asexual reproduction by fragmentation or gemmae; sporophyte has foot, seta and capsule.", "Marchantia"],
        ["Mosses", "Gametophyte has protonema and leafy stage; vegetative reproduction by fragmentation and budding; sporophyte has foot, seta and capsule with spores.", "Funaria, Polytrichum, Sphagnum"],
      ]),
      recall_data: recall("Liverworts vs mosses?", "Liverworts have thalloid body and gemmae; mosses have protonema and leafy stages.", [], ["Marchantia", "Funaria", "Polytrichum", "Sphagnum"]),
      importance: 5,
      source_page: 11,
      sort_order: 8,
    }),
    card(chapterId, "bryophytes-vs-pteridophytes", {
      title: "Bryophytes vs Pteridophytes",
      card_type: "comparison",
      body: "The source contrasts dominant phases and vascular tissues.",
      table_data: table(["Character", "Bryophytes", "Pteridophytes"], [
        ["Dominant phase", "Gametophyte", "Sporophyte"],
        ["Plant body", "Thallus-like, prostrate or erect, with rhizoids", "Differentiated into true root, stem and leaves"],
        ["Vascular tissue", "Not listed as present", "First terrestrial plants with xylem and phloem"],
        ["Fertilization", "Needs water", "Needs water for antherozoid transfer"],
        ["Sporophyte", "Attached to photosynthetic gametophyte", "Main plant body"],
      ]),
      recall_data: recall("Bryophytes vs pteridophytes in one line?", "Bryophytes are gametophyte-dominant and non-vascular; pteridophytes are sporophyte-dominant vascular plants.", [], [], ["Pteridophytes are first terrestrial plants with vascular tissues."]),
      importance: 5,
      source_page: 11,
      sort_order: 9,
    }),
    card(chapterId, "pteridophytes-spores-seed-habit", {
      title: "Pteridophytes, Homospory and Heterospory",
      card_type: "classification",
      body: "Pteridophytes include horsetails and ferns; the main plant body is a sporophyte.",
      table_data: table(["Term", "Recall answer", "Examples"], [
        ["Sporophylls", "Leaf-like appendages subtending sporangia.", "May form strobili/cones in Selaginella, Equisetum."],
        ["Homospory", "Similar kinds of spores.", "Most pteridophytes."],
        ["Heterospory", "Macro/mega and micro spores.", "Selaginella, Salvinia."],
        ["Seed habit precursor", "Female gametophytes retained on parent sporophyte; zygote develops into young embryo.", "Important evolutionary step."],
      ]),
      recall_data: recall("How is heterospory linked to seed habit precursor?", "Megaspores and microspores form female and male gametophytes; female gametophyte retention on parent sporophyte with embryo development is precursor to seed habit.", [], ["Selaginella", "Salvinia", "Psilotum", "Lycopodium", "Equisetum", "Dryopteris", "Pteris", "Adiantum"]),
      importance: 5,
      source_page: 11,
      sort_order: 10,
    }),
    card(chapterId, "gymnosperms", {
      title: "Gymnosperms",
      card_type: "concept",
      body: "Gymnosperms are plants with naked ovules and seeds.",
      recall_data: recall("What defines gymnosperms?", "Ovules are not enclosed by ovary wall and remain exposed before and after fertilization; seeds are naked.", [
        "Sequoia (giant redwood) is the tallest tree species.",
        "Pinus roots may have mycorrhiza.",
        "Cycas has coralloid roots with N2-fixing cyanobacteria.",
        "Pinus and Cedrus have needle-like leaves with thick cuticle and sunken stomata to reduce water loss.",
      ], ["Pinus", "Cycas", "Cedrus", "Sequoia"]),
      importance: 5,
      source_page: 12,
      sort_order: 11,
    }),
    card(chapterId, "gymnosperm-reproduction", {
      title: "Gymnosperm Reproduction",
      card_type: "process",
      body: "Gymnosperms are heterosporous and produce microspores and megaspores.",
      recall_data: recall("Recall the gymnosperm reproductive flow.", "Sporophylls form cones; microsporophylls produce pollen grains; megasporophylls bear ovules; pollen reaches ovule, pollen tube carries male gametes, fertilization makes embryo and ovule becomes seed.", [
        "Male and female gametophytes do not have independent free-living existence.",
        "Male/female cones may be on same tree (Pinus) or different trees (Cycas).",
      ]),
      importance: 5,
      source_page: 12,
      sort_order: 12,
    }),
    card(chapterId, "angiosperms-monocots-dicots", {
      title: "Angiosperms and Monocots vs Dicots",
      card_type: "comparison",
      body: "Angiosperms are flowering plants and include dicotyledons and monocotyledons.",
      table_data: table(["Class", "Seed cotyledons", "Leaf venation", "Flower members"], [
        ["Dicotyledons", "2 cotyledons", "Reticulate", "Tetramerous or pentamerous (4 or 5 members in each floral whorl)"],
        ["Monocotyledons", "One cotyledon", "Parallel", "Trimerous (3 members in each floral whorl)"],
      ]),
      recall_data: recall("Monocots vs dicots?", "Dicots: 2 cotyledons, reticulate venation, 4/5 floral whorl members. Monocots: one cotyledon, parallel venation, 3 floral whorl members.", ["Angiosperms range from Wolffia to Eucalyptus over 100 metres."], ["Wolffia", "Eucalyptus"]),
      importance: 5,
      source_page: 12,
      sort_order: 13,
    }),
    card(chapterId, "double-fertilisation", {
      title: "Double Fertilisation",
      card_type: "process",
      body: "Double fertilisation is unique to angiosperms.",
      recall_data: recall("What two fusions make double fertilisation?", "One male gamete fuses with egg cell to form zygote (syngamy); the other fuses with diploid secondary nucleus to form triploid primary endosperm nucleus (PEN).", [
        "PEN develops into endosperm.",
        "Ovules develop into seeds and ovaries into fruit.",
        "Synergids and antipodals degenerate after fertilization.",
      ], [], ["Double fertilisation is unique to angiosperms."]),
      importance: 5,
      source_page: 13,
      sort_order: 14,
    }),
    card(chapterId, "alternation-flow", {
      title: "Alternation of Generations",
      card_type: "diagram",
      body: "Plant life cycles alternate between gametophyte (n) and sporophyte (2n).",
      diagram_data: { type: "bio-alternation-flow" },
      recall_data: recall("Recall alternation of generations flow.", "Gametophyte produces gametes by mitosis; fertilization forms zygote; zygote forms sporophyte by mitosis; sporophyte forms haploid spores by meiosis; spores form gametophyte by mitosis.", [
        "Both haploid and diploid cells can divide by mitosis in plants.",
      ]),
      importance: 5,
      source_page: 13,
      sort_order: 15,
    }),
    card(chapterId, "life-cycle-patterns", {
      title: "Haplontic vs Diplontic vs Haplo-diplontic",
      card_type: "comparison",
      body: "The source compares three plant life-cycle patterns.",
      diagram_data: { type: "bio-life-cycle-patterns" },
      table_data: table(["Pattern", "Dominant phase", "Source examples"], [
        ["Haplontic", "Free-living gametophyte; sporophyte represented only by zygote.", "Volvox, Spirogyra, some species of Chlamydomonas."],
        ["Diplontic", "Diploid sporophyte dominant, photosynthetic and independent; gametophyte single to few-celled.", "Fucus sp.; all seed-bearing plants (gymnosperms and angiosperms)."],
        ["Haplo-diplontic", "Both gametophyte and sporophyte multicellular and often free-living; different dominant phases.", "Bryophytes and Pteridophytes."],
      ]),
      recall_data: recall("Haplontic vs diplontic vs haplo-diplontic?", "Haplontic = gametophyte dominant and zygote-only sporophyte; diplontic = sporophyte dominant; haplo-diplontic = both phases multicellular.", [], ["Volvox", "Spirogyra", "Chlamydomonas", "Fucus sp.", "Bryophytes", "Pteridophytes"]),
      importance: 5,
      source_page: 13,
      sort_order: 16,
    }),
  ];
}

const animalFeatureColumns = ["Feature", "Porifera", "Cnidaria", "Ctenophora"];

function animalKingdomCards(chapterId) {
  return [
    card(chapterId, "basis-overview", {
      title: "Basis of Animal Classification",
      card_type: "classification",
      body: "The source uses levels of organization, symmetry, germ layers, coelom, metamerism and notochord.",
      table_data: table(["Basis", "Recall answer"], [
        ["Levels of organization", "Cellular, tissue, organ, organ-system levels."],
        ["Symmetry", "Asymmetrical or symmetrical; radial or bilateral."],
        ["Germinal layers", "Diploblastic or triploblastic."],
        ["Coelom", "Acoelomate, pseudocoelomate or coelomate."],
        ["Metamerism", "Repeated external/internal segments."],
        ["Notochord", "Mesodermally derived supporting rod on dorsal side during embryonic development."],
      ]),
      recall_data: recall("What are the six bases of animal classification in this source?", "Levels of organization, body symmetry, germinal layers, coelom, metamerism and notochord."),
      importance: 5,
      source_page: 14,
      sort_order: 1,
    }),
    card(chapterId, "levels-symmetry", {
      title: "Levels of Organization and Symmetry",
      card_type: "comparison",
      body: "The source gives examples for each organization and symmetry type.",
      table_data: sections([
        table(["Level", "Recall answer", "Examples"], [
          ["Cellular", "Cells arranged as loose cell aggregates.", "Porifera"],
          ["Tissue", "Cells arranged into tissues.", "Cnidarians and Ctenophores"],
          ["Organ", "Tissues arranged into organs.", "Higher animals: Platyhelminthes to chordates"],
          ["Organ system", "Organs associated into organ systems.", "Higher animals"],
        ]),
        table(["Symmetry", "Recall answer", "Examples"], [
          ["Asymmetrical", "Cannot be divided into two equal halves.", "Most Poriferans, Snails"],
          ["Radial", "Two equal halves in any vertical plane along oral-aboral axis.", "Some Poriferans, Cnidarians, Ctenophores, adult Echinoderms"],
          ["Bilateral", "Right and left halves in only one plane.", "Platyhelminthes to Chordata except adult Echinodermata"],
        ]),
      ]),
      recall_data: recall("Which examples go with levels and symmetry?", "Porifera = cellular; cnidarians/ctenophores = tissue; Platyhelminthes to chordates = organ/organ-system; radial includes cnidarians, ctenophores and adult echinoderms.", [], [], ["Adult Echinodermata are the exception to bilateral trend."]),
      importance: 5,
      source_page: 14,
      sort_order: 2,
    }),
    card(chapterId, "germ-layers-coelom", {
      title: "Germ Layers and Coelom",
      card_type: "comparison",
      body: "Germ layers and coelom separate major animal groups.",
      table_data: sections([
        table(["Type", "Recall answer", "Examples"], [
          ["Diploblastic", "Two germ layers: ectoderm and endoderm, with mesoglea between.", "Cnidaria and Ctenophora"],
          ["Triploblastic", "Three germ layers: ectoderm, mesoderm and endoderm.", "Platyhelminthes to Chordata"],
        ]),
        table(["Coelom type", "Recall answer", "Examples"], [
          ["Acoelomate", "No coelom; space filled with parenchyma.", "Porifera to Platyhelminthes"],
          ["Pseudocoelomate", "False coelom not lined by mesoderm; mesoderm in scattered pouches.", "Aschelminthes"],
          ["Coelomate", "True coelom arising from mesoderm and lined by peritoneal layer.", "Annelida to Chordata"],
        ]),
      ]),
      recall_data: recall("Diploblastic vs triploblastic and acoelomate vs pseudocoelomate vs coelomate?", "Diploblastic has two germ layers; triploblastic has three. Acoelomate has no coelom, pseudocoelomate has false coelom, coelomate has true mesoderm-lined coelom.", [], [], ["Aschelminthes are pseudocoelomate."]),
      importance: 5,
      source_page: 14,
      sort_order: 3,
    }),
    card(chapterId, "metamerism-notochord", {
      title: "Metamerism and Notochord",
      card_type: "fact",
      body: "Metamerism and notochord are quick classification markers.",
      recall_data: recall("Define metamerism and notochord from the source.", "Metamerism is repeated external/internal segmentation; notochord is a mesodermally derived dorsal supporting rod formed during embryonic development.", [
        "Metamerism examples: Annelids (earthworm etc.) and Arthropods.",
        "Animals with notochord are chordates; those without are non-chordates.",
      ]),
      importance: 5,
      source_page: 14,
      sort_order: 4,
    }),
    card(chapterId, "porifera-cnidaria-ctenophora", {
      title: "Porifera vs Cnidaria vs Ctenophora",
      card_type: "comparison",
      body: "The source table compares the first three non-chordate phyla.",
      table_data: table(animalFeatureColumns, [
        ["Organization", "Cellular", "Tissue", "Tissue"],
        ["Symmetry", "Asymmetrical; some radial", "Radial", "Radial"],
        ["Germ layers", "-", "Diploblastic", "Diploblastic"],
        ["Coelom", "Acoelomate", "Acoelomate", "Acoelomate"],
        ["Habit", "Aquatic mostly marine, sedentary, solitary/colonial", "Aquatic mostly marine, sessile/free swimming, solitary/colonial", "Exclusively marine, solitary and pelagic"],
        ["Digestion", "Absent digestive system; intracellular digestion", "Incomplete; intracellular and extracellular", "Incomplete; intracellular and extracellular"],
        ["Unique", "Water canal system, ostia, spongocoel, choanocytes, spicules/spongin", "Cnidoblasts, coelenteron, polyp/medusa, metagenesis, CaCO3 corals", "8 rows of ciliated comb plates, tentacles, bioluminescence"],
        ["Examples", "Sycon (Scypha), Spongilla, Euspongia", "Hydra, Obelia, Aurelia, Physalia, Adamsia, Pennatula, Gorgonia, Meandrina", "Ctenoplana, Pleurobrachia"],
      ]),
      recall_data: recall("Compare Porifera, Cnidaria and Ctenophora.", "Porifera = cellular and water canal system; Cnidaria = cnidoblasts and polyp/medusa; Ctenophora = comb plates and bioluminescence.", [], ["Sycon", "Spongilla", "Euspongia", "Hydra", "Obelia", "Aurelia", "Physalia", "Adamsia", "Pennatula", "Gorgonia", "Meandrina", "Ctenoplana", "Pleurobrachia"]),
      importance: 5,
      source_page: 15,
      sort_order: 5,
    }),
    card(chapterId, "cnidarian-special-terms", {
      title: "Cnidarian and Poriferan Special Terms",
      card_type: "fact",
      body: "The notes below the table define high-yield terms.",
      table_data: table(["Term", "Recall answer"], [
        ["Water canal system", "Water enters through ostia into spongocoel and exits through osculum; used for food gathering, gas exchange and waste removal."],
        ["Hermaphrodite/monoecious", "Male and female sex organs in same individual."],
        ["Cnidoblast/cnidocyte", "Stinging cell with poison-filled nematocyst; anchorage, defense and prey capture."],
        ["Polyp", "Tubular attached asexual form with upward mouth and tentacles; Hydra, Adamsia."],
        ["Medusa", "Umbrella-like free-swimming sexual form with downward mouth and tentacles; Aurelia."],
        ["Metagenesis", "Polyps produce medusae asexually and medusae form polyps sexually; Obelia."],
        ["Bioluminescence", "Property of some animals to emit light."],
      ]),
      recall_data: recall("Which special terms should you recall from Porifera/Cnidaria/Ctenophora?", "Water canal system, cnidoblast, polyp, medusa, metagenesis and bioluminescence.", [], ["Hydra", "Adamsia", "Aurelia", "Obelia"]),
      importance: 5,
      source_page: 15,
      sort_order: 6,
    }),
    card(chapterId, "flat-round-ring-jointed-comparison", {
      title: "Platyhelminthes to Arthropoda",
      card_type: "comparison",
      body: "The source table compares flatworms, roundworms, segmented worms and joint-legged animals.",
      table_data: table(["Feature", "Platyhelminthes", "Aschelminthes", "Annelida", "Arthropoda"], [
        ["Coelom", "Acoelomate", "Pseudocoelomate", "Coelomate", "Coelomate"],
        ["Digestive system", "Incomplete", "Complete tubular canal with muscular pharynx", "Complete", "Complete"],
        ["Respiration", "Absent", "Absent", "Cutaneous; some branchial", "Gills/book gills/trachea/book lungs"],
        ["Circulation", "Absent", "Absent", "Closed type", "Open type"],
        ["Unique", "Dorsoventrally flattened; flame cells; hooks and suckers in parasites", "Circular cross-section; syncytial epidermis; thick cuticle; excretory tube; sexual dimorphism", "Ring-like segmentation; setae/parapodia; nephridia; double ventral nerve cord", "Jointed appendages; head, thorax, abdomen; chitinous exoskeleton; Malpighian tubules; antennae/eyes/statocysts"],
        ["Examples", "Taenia solium, Fasciola, Planaria", "Ascaris, Ancylostoma, Wuchereria", "Pheretima, Hirudinaria, Neries", "Spider, Scorpion, Crab, Prawn, Apis, Bombyx, Laccifer, Anopheles, Culex, Aedes, Housefly, Locusta, Limulus"],
      ]),
      recall_data: recall("Compare Platyhelminthes, Aschelminthes, Annelida and Arthropoda.", "Flatworms are acoelomate with flame cells; roundworms are pseudocoelomate with thick cuticle; annelids are segmented coelomates with closed circulation; arthropods have jointed appendages, chitinous exoskeleton and open circulation.", [], ["Taenia solium", "Fasciola", "Planaria", "Ascaris", "Ancylostoma", "Wuchereria", "Pheretima", "Hirudinaria", "Neries", "Apis", "Bombyx", "Laccifer", "Locusta", "Limulus"]),
      importance: 5,
      source_page: 16,
      sort_order: 7,
    }),
    card(chapterId, "arthropoda-traps", {
      title: "Arthropoda NEET Facts",
      card_type: "neet_trap",
      body: "Arthropoda is the largest phylum; over two-thirds of all named species are arthropods.",
      recall_data: recall("What source examples are tied to Arthropoda?", "Economically important insects: Apis, Bombyx, Laccifer; vectors: mosquitoes (Anopheles, Culex, Aedes), Housefly; gregarious pest: Locusta; living fossil: Limulus.", [
        "Dioecious means sexes are separate.",
        "Sexual dimorphism means morphological differences between male and female.",
      ], ["Apis", "Bombyx", "Laccifer", "Anopheles", "Culex", "Aedes", "Housefly", "Locusta", "Limulus"], ["Arthropoda is the largest phylum."]),
      importance: 5,
      source_page: 16,
      sort_order: 8,
    }),
    card(chapterId, "mollusca-echinodermata-hemichordata", {
      title: "Mollusca vs Echinodermata vs Hemichordata",
      card_type: "comparison",
      body: "The source table compares these coelomate non-chordate phyla.",
      table_data: table(["Feature", "Mollusca", "Echinodermata", "Hemichordata"], [
        ["Symmetry", "Bilateral", "Adults radial; larvae bilateral", "Bilateral"],
        ["Habitat", "Aquatic; few terrestrial", "Exclusively marine", "Exclusively marine"],
        ["Respiration", "Gills in aquatic forms and pulmonary sac in terrestrial forms", "Dermal branchiae/papulae and tube feet", "Gills"],
        ["Circulation", "Open type", "Open type", "Open type"],
        ["Unique", "Head, visceral mass and muscular foot; mantle and radula; calcareous shell", "Calcareous ossicle endoskeleton; water vascular system; no head; no excretory system; autotomy/regeneration", "Proboscis, collar and trunk; stomochord; proboscis gland"],
        ["Examples", "Pila, Pinctada, Sepia, Loligo, Octopus, Aplysia, Dentalium, Chaetopleura", "Asterias, Echinus, Echinocardium, Antedon, Cucumaria, Ophiura", "Balanoglossus, Saccoglossus"],
      ]),
      recall_data: recall("Compare Mollusca, Echinodermata and Hemichordata.", "Mollusca has mantle/radula; Echinodermata has water vascular system and adult radial symmetry; Hemichordata has proboscis-collar-trunk and stomochord.", [], ["Pila", "Pinctada", "Sepia", "Loligo", "Octopus", "Aplysia", "Dentalium", "Chaetopleura", "Asterias", "Echinus", "Echinocardium", "Antedon", "Cucumaria", "Ophiura", "Balanoglossus", "Saccoglossus"]),
      importance: 5,
      source_page: 17,
      sort_order: 9,
    }),
    card(chapterId, "mollusc-echinoderm-terms", {
      title: "Mollusc and Echinoderm Terms",
      card_type: "fact",
      body: "The source notes define mantle, radula and water vascular system.",
      table_data: table(["Term", "Recall answer"], [
        ["Mollusca rank", "Second largest phylum."],
        ["Mantle/Pallium", "Membrane covering visceral mass; space between hump and mantle is mantle cavity."],
        ["Radula", "File-like rasping organ in mouth of molluscs used for feeding."],
        ["Water vascular system", "Sea water enters through madreporite and reaches radiating canals and tube feet/podia."],
        ["Hemichordata note", "Earlier considered a sub-phylum of Chordata; has pharyngeal gill slits."],
      ]),
      recall_data: recall("What are mantle, radula and water vascular system?", "Mantle covers visceral mass; radula is rasping feeding organ; water vascular system uses madreporite, canals and tube feet for locomotion, respiration, food capture/transport and excretion."),
      importance: 5,
      source_page: 17,
      sort_order: 10,
    }),
    card(chapterId, "chordata-vs-nonchordata", {
      title: "Chordata vs Non-Chordata",
      card_type: "comparison",
      body: "Chordates have notochord, dorsal tubular nerve cord and pharyngeal gill slits.",
      table_data: table(["Character", "Chordata", "Non-Chordata"], [
        ["Notochord", "Found in embryonic stage", "Absent"],
        ["Central nervous system", "Dorsal, hollow and single", "Ventral, solid and double"],
        ["Pharyngeal gill slits", "Present", "Absent"],
        ["Heart", "Ventral", "Dorsal if present"],
        ["Post-anal tail", "Present", "Absent"],
      ]),
      recall_data: recall("Chordata vs Non-Chordata?", "Chordata has embryonic notochord, dorsal hollow single CNS, pharyngeal gill slits, ventral heart and post-anal tail.", [], [], ["Notochord lies mid-dorsally between alimentary canal and nerve cord in embryo."]),
      importance: 5,
      source_page: 17,
      sort_order: 11,
    }),
    card(chapterId, "chordata-subphyla", {
      title: "Urochordata vs Cephalochordata vs Vertebrata",
      card_type: "comparison",
      body: "Phylum Chordata is classified into Urochordata, Cephalochordata and Vertebrata.",
      table_data: table(["Subphylum", "Recall features", "Examples"], [
        ["Urochordata (Tunicata)", "Notochord only in larval tail; body covered by test made of tunicin; exclusively marine; hermaphrodite.", "Ascidia, Salpa, Doliolum"],
        ["Cephalochordata", "Notochord from head to tail and persistent throughout life; fish-like body; exclusively marine; sexes separate.", "Branchiostoma (Amphioxus or Lancelet)"],
        ["Vertebrata", "Embryonic notochord replaced by cartilaginous/bony vertebral column in adult; ventral muscular heart; kidneys; paired appendages.", "Cyclostomata to Mammalia"],
      ]),
      recall_data: recall("Compare Urochordata, Cephalochordata and Vertebrata.", "Urochordata has larval-tail notochord; Cephalochordata has persistent head-to-tail notochord; Vertebrata replaces embryonic notochord with vertebral column.", [], ["Ascidia", "Salpa", "Doliolum", "Branchiostoma", "Amphioxus", "Lancelet"]),
      importance: 5,
      source_page: 18,
      sort_order: 12,
    }),
    card(chapterId, "vertebrate-classification", {
      title: "Classification of Vertebrata",
      card_type: "diagram",
      body: "The source flow divides Vertebrata into Agnatha and Gnathostomata, then Pisces and Tetrapoda.",
      diagram_data: { type: "bio-vertebrata-flow" },
      recall_data: recall("Recall the vertebrate classification flow.", "Vertebrata -> Agnatha (jawless) -> Cyclostomata; Vertebrata -> Gnathostomata (bears jaws) -> Pisces (Chondrichthyes, Osteichthyes) and Tetrapoda (Amphibia, Reptilia, Aves, Mammalia)."),
      importance: 5,
      source_page: 18,
      sort_order: 13,
    }),
    card(chapterId, "cyclostomata", {
      title: "Class Cyclostomata",
      card_type: "classification",
      body: "Cyclostomes are jawless ectoparasites on some fishes.",
      recall_data: recall("What are the source traits of Cyclostomata?", "Ectoparasites on fishes with elongated scaleless body, no paired fins, 6-15 pairs of gill slits, sucking circular jawless mouth, cartilaginous cranium and vertebral column, closed circulation.", [
        "Marine, but migrate to freshwater for spawning; after spawning they die.",
        "Larvae return to ocean after metamorphosis.",
      ], ["Petromyzon (Lamprey)", "Myxine (Hagfish)"]),
      importance: 5,
      source_page: 18,
      sort_order: 14,
    }),
    card(chapterId, "chondrichthyes-vs-osteichthyes", {
      title: "Chondrichthyes vs Osteichthyes",
      card_type: "comparison",
      body: "The source compares cartilaginous and bony fishes.",
      table_data: table(["Feature", "Chondrichthyes", "Osteichthyes"], [
        ["Habitat/body", "Marine, streamlined, predaceous", "Marine and fresh water, streamlined"],
        ["Endoskeleton", "Cartilaginous; notochord persistent throughout life", "Bony"],
        ["Mouth", "Ventral", "Terminal"],
        ["Gills", "Gill slits without operculum; powerful jaws", "4 pairs of gills covered by operculum on each side"],
        ["Scales", "Placoid; teeth are backward modified placoid scales", "Cycloid, ctenoid etc."],
        ["Air bladder", "Absent; must swim constantly to avoid sinking", "Present for buoyancy"],
        ["Heart/temp", "Poikilotherm; two-chambered heart", "Poikilotherm; two-chambered heart"],
        ["Reproduction", "Separate sexes; male pelvic fins bear claspers; internal fertilization; many viviparous", "Separate sexes; external fertilisation; mostly oviparous; direct development"],
        ["Examples", "Scoliodon, Pristis, Carcharodon, Trygon, Torpedo", "Exocoetus, Hippocampus, Labeo, Catla, Clarias, Betta, Pterophyllum"],
      ]),
      recall_data: recall("Chondrichthyes vs Osteichthyes?", "Chondrichthyes have cartilaginous skeleton, ventral mouth, no operculum or air bladder, placoid scales and internal fertilization; Osteichthyes have bony skeleton, terminal mouth, operculum, air bladder and mostly external fertilization.", [], ["Scoliodon", "Pristis", "Carcharodon", "Trygon", "Torpedo", "Exocoetus", "Hippocampus", "Labeo", "Catla", "Clarias", "Betta", "Pterophyllum"]),
      importance: 5,
      source_page: 18,
      sort_order: 15,
    }),
    card(chapterId, "tetrapoda-comparison", {
      title: "Amphibia vs Reptilia vs Aves vs Mammalia",
      card_type: "comparison",
      body: "The source table compares the four tetrapod classes.",
      table_data: table(["Feature", "Amphibia", "Reptilia", "Aves", "Mammalia"], [
        ["Body/skin", "Aquatic and terrestrial; need water for breeding; moist skin without scales", "Dry cornified skin with epidermal scales/scutes", "Feathers and beak; dry skin except oil gland at tail base", "Mammary glands; skin with hair"],
        ["Limbs", "Most have two pairs", "Two pairs if present; crawling locomotion", "Forelimbs as wings; hind limbs for walking/swimming/clasping", "Two pairs for walking, running, climbing, burrowing, swimming or flying"],
        ["Ear", "Tympanum represents ear", "Tympanum represents ear", "Tympanum represents ear", "External ear pinnae"],
        ["Heart", "3-chambered", "3-chambered with partial septum; crocodiles 4-chambered", "4-chambered", "4-chambered"],
        ["Temperature", "Poikilotherms", "Poikilotherms", "Homoiotherms", "Homoiotherms"],
        ["Respiration", "Gills in larva, lungs and skin", "Lungs", "Double respiration; air sacs connected to lungs", "Lungs"],
        ["Reproduction", "External fertilisation, oviparous, indirect development", "Internal fertilisation, oviparous, direct development", "Internal fertilisation, oviparous, direct development", "Internal fertilisation, viviparous except Echidna and Platypus, direct development"],
      ]),
      recall_data: recall("Compare Amphibia, Reptilia, Aves and Mammalia.", "Amphibia need water and have moist skin; Reptilia have dry scales; Aves have feathers, wings and air sacs; Mammalia have mammary glands, hair and pinnae.", [], [], ["Crocodiles have four-chambered heart; mammals are viviparous except Echidna and Platypus."]),
      importance: 5,
      source_page: 20,
      sort_order: 16,
    }),
    card(chapterId, "tetrapoda-examples", {
      title: "Tetrapoda Examples",
      card_type: "examples",
      body: "The source examples for tetrapods are high-yield recall lists.",
      table_data: table(["Class", "Source examples"], [
        ["Amphibia", "Bufo (Toad), Rana (Frog), Hyla (Tree frog), Salamandra (Salamander), Ichthyophis (Limbless amphibia)"],
        ["Reptilia", "Chelone (Turtle), Testudo (Tortoise), Chameleon, Calotes, Crocodilus, Alligator, Hemidactylus; poisonous snakes: Naja, Bangarus, Vipera; non-poisonous snakes: Python"],
        ["Aves", "Corvus, Columba, Psittacula, Struthio, Pavo, Aptenodytes, Neophron"],
        ["Mammalia", "Ornithorhynchus, Macropus, Pteropus, Camelus, Macaca, Rattus, Canis, Felis, Elephas, Equus, Delphinus, Balaenoptera, Panthera tigris, Panthera leo"],
      ]),
      recall_data: recall("Recall the tetrapod examples exactly from the source.", "Amphibia: Bufo, Rana, Hyla, Salamandra, Ichthyophis. Reptilia: Chelone, Testudo, Chameleon, Calotes, Crocodilus, Alligator, Hemidactylus, Naja, Bangarus, Vipera, Python. Aves: Corvus, Columba, Psittacula, Struthio, Pavo, Aptenodytes, Neophron. Mammalia: Ornithorhynchus, Macropus, Pteropus, Camelus, Macaca, Rattus, Canis, Felis, Elephas, Equus, Delphinus, Balaenoptera, Panthera tigris, Panthera leo."),
      importance: 5,
      source_page: 20,
      sort_order: 17,
    }),
    card(chapterId, "poikilotherm-homoiotherm", {
      title: "Poikilotherms vs Homoiotherms",
      card_type: "comparison",
      body: "The source defines these temperature-regulation terms.",
      table_data: table(["Term", "Recall answer", "Classes in table"], [
        ["Poikilotherms", "Cold-blooded animals that lack capacity to regulate body temperature.", "Amphibia, Reptilia, Chondrichthyes, Osteichthyes"],
        ["Homoiotherms", "Warm-blooded animals having ability to maintain constant body temperature.", "Aves, Mammalia"],
      ]),
      recall_data: recall("Poikilotherms vs homoiotherms?", "Poikilotherms lack body-temperature regulation; homoiotherms maintain constant body temperature."),
      importance: 4,
      source_page: 20,
      sort_order: 18,
    }),
  ];
}

export function getBiologyBatch1Chapters() {
  return BIOLOGY_BATCH_1_CHAPTER_DEFINITIONS.map((item) => ({
    id: chapter(item.slug),
    subject_id: "neet-biology",
    title: item.title,
    slug: item.slug,
    sort_order: item.sort_order,
  }));
}

export function getBiologyBatch1Cards() {
  return [
    ...livingWorldCards(chapter("the-living-world")),
    ...biologicalClassificationCards(chapter("biological-classification")),
    ...plantKingdomCards(chapter("plant-kingdom")),
    ...animalKingdomCards(chapter("animal-kingdom")),
  ];
}
