export const BIOLOGY_BATCH_6_CHAPTER_DEFINITIONS = [
  { title: "Neural Control and Co-ordination", slug: "neural-control-and-co-ordination", sort_order: 19, source_page: 82 },
  { title: "Chemical Co-ordination and Integration", slug: "chemical-co-ordination-and-integration", sort_order: 20, source_page: 87 },
];

const chapter = (slug) => `neet-biology-${slug}`;

function table(columns, rows) {
  return { columns, rows };
}

function recall(question, answer, key_points = [], examples = [], neet_traps = []) {
  return { recall_question: question, reveal_answer: answer, key_points, examples, neet_traps };
}

function card(chapterId, slug, payload) {
  return {
    id: `${chapterId}-${slug}`,
    chapter_id: chapterId,
    formulas: [],
    variables: [],
    conditions: [],
    table_data: null,
    diagram_data: null,
    diagram_svg: null,
    is_active: true,
    ...payload,
  };
}

function neuralCards(chapterId) {
  return [
    card(chapterId, "neural-system-overview", {
      title: "Neural System Overview",
      card_type: "concept",
      body: "The neural system controls and coordinates body activities, conducts and integrates information and responds to stimuli.",
      table_data: table(["Recall cue", "Source-backed answer"], [
        ["Includes", "Brain, spinal cord and nerves"],
        ["Made of", "Specialized cells known as neurons"],
        ["Neuron", "Structural and functional unit of neural system"],
      ]),
      recall_data: recall("What is the structural and functional unit of the neural system?", "Neuron."),
      importance: 5,
      source_page: 82,
      sort_order: 1,
    }),
    card(chapterId, "neuron-structure", {
      title: "Neuron Structure",
      card_type: "classification",
      body: "A neuron has a cell body, dendron with dendrites and an axon.",
      diagram_data: { type: "bio-neuron-structure" },
      table_data: table(["Part", "Source-backed recall"], [
        ["Cell body or cyton", "Contains cytoplasm, cell organelles and Nissl's granules"],
        ["Dendron", "Short fibres projecting from the cyton"],
        ["Dendrites", "Sub-branches that transmit impulses towards the cyton"],
        ["Axon", "Long fibre transmitting impulses away from the cell body"],
        ["Axonite", "Branching of axon"],
        ["Synaptic knob", "Bulb-like end of each axonite"],
      ]),
      recall_data: recall("Which neuron process carries impulses away from the cell body?", "Axon.", [], [], ["Dendrites transmit impulses towards the cyton."]),
      importance: 5,
      source_page: 82,
      sort_order: 2,
    }),
    card(chapterId, "types-of-neurons", {
      title: "Types of Neurons",
      card_type: "classification",
      body: "The source classifies neurons by axon and dendron count.",
      table_data: table(["Type", "Structure", "Source location"], [
        ["Unipolar", "One axon and no dendron", "Embryo"],
        ["Bipolar", "One axon and one dendron", "Retina"],
        ["Multipolar", "One axon and 2 or more dendrons", "Most common; CNS and PNS"],
      ]),
      recall_data: recall("Which neuron type is most common?", "Multipolar neuron."),
      importance: 4,
      source_page: 82,
      sort_order: 3,
    }),
    card(chapterId, "myelinated-vs-non-myelinated", {
      title: "Myelinated vs Non-Myelinated Axon",
      card_type: "comparison",
      body: "Schwann cells are present in both types, but only myelinated axons have a myelin sheath.",
      table_data: table(["Feature", "Myelinated axon", "Non-myelinated axon"], [
        ["Schwann cells", "Envelope the axon and form myelin sheath", "Present but no myelin sheath"],
        ["Matter colour", "White matter is formed of myelinated nerve fibres", "Gray matter is without myelin sheath"],
        ["Nodes", "Gaps between adjacent myelin sheaths are nodes of Ranvier", "No myelin sheath gaps"],
        ["Source location", "Spinal and cranial nerves", "Autonomous and somatic neural systems"],
      ]),
      recall_data: recall("What are nodes of Ranvier?", "Gaps between two adjacent myelin sheaths.", [], [], ["Non-myelinated axons still have Schwann cells, but no myelin sheath."]),
      importance: 5,
      source_page: 82,
      sort_order: 4,
    }),
    card(chapterId, "resting-membrane-potential", {
      title: "Resting Membrane Potential",
      card_type: "concept",
      body: "In a resting neuron, the axonal membrane is polarized.",
      diagram_data: { type: "bio-action-potential-flow" },
      table_data: table(["Cue", "Source-backed detail"], [
        ["Membrane permeability", "More permeable to K+ and nearly impermeable to Na+"],
        ["Inside axoplasm", "High K+ and negatively charged proteins; low Na+"],
        ["Outside axon", "Low K+ and high Na+"],
        ["Na-K pump", "Transports 3 Na+ outwards for 2 K+ into the cell"],
        ["Polarity", "Outer surface positive and inner surface negative"],
        ["Resting potential", "Electrical potential difference across resting plasma membrane"],
      ]),
      recall_data: recall("What does the Na-K pump do in the source?", "It transports 3 Na+ outwards for 2 K+ into the cell."),
      importance: 5,
      source_page: 82,
      sort_order: 5,
    }),
    card(chapterId, "action-potential", {
      title: "Action Potential",
      card_type: "process",
      body: "A stimulus makes the membrane permeable to Na+, causing depolarization and nerve impulse generation.",
      table_data: table(["Step", "Source-backed event"], [
        ["1", "Stimulus is applied at site A"],
        ["2", "Membrane becomes permeable to Na+"],
        ["3", "Rapid influx of Na+ reverses polarity"],
        ["4", "Outer surface becomes negative and inner surface becomes positive"],
        ["5", "This depolarization produces action potential or nerve impulse"],
      ]),
      recall_data: recall("What ion rapidly enters during depolarization?", "Na+.", ["The source calls the electrical potential difference during depolarization action potential."]),
      importance: 5,
      source_page: 82,
      sort_order: 6,
    }),
    card(chapterId, "propagation-and-repolarization", {
      title: "Propagation and Repolarization",
      card_type: "sequence",
      body: "Action potential at one site generates action potential at the next site, then K+ movement restores the resting membrane.",
      table_data: table(["Phase", "Source-backed recall"], [
        ["Propagation", "Current flows from site A to site B on inner surface and from site B to site A on outer surface"],
        ["Next action potential", "Polarity is reversed and action potential is generated at site B"],
        ["Na+ permeability", "Rise is extremely short lived"],
        ["K+ permeability", "Quickly rises after Na+ permeability"],
        ["Restoration", "K+ diffuses outside and restores the resting membrane"],
      ]),
      recall_data: recall("Which ion diffuses out to restore the resting membrane?", "K+.", [], [], ["The source does not include saltatory conduction here."]),
      importance: 5,
      source_page: 82,
      sort_order: 7,
    }),
    card(chapterId, "electrical-vs-chemical-synapse", {
      title: "Electrical vs Chemical Synapse",
      card_type: "comparison",
      body: "Synapse is a functional junction between two neurons.",
      table_data: table(["Feature", "Electrical synapse", "Chemical synapse"], [
        ["Membrane relation", "Pre- and post-synaptic membranes are in close proximity", "Fluid-filled synaptic cleft between neurons"],
        ["Transmission", "Similar to transmission along an axon", "Uses neurotransmitters"],
        ["Speed", "Faster than chemical synapse", "Slower than electrical synapse"],
        ["Human system", "Very rare", "Commonly described with synaptic vesicles and receptors"],
      ]),
      recall_data: recall("Which synapse is very rare in the human system?", "Electrical synapse.", [], [], ["Chemical synapses have a synaptic cleft."]),
      importance: 5,
      source_page: 82,
      sort_order: 8,
    }),
    card(chapterId, "chemical-synapse-transmission", {
      title: "Chemical Synapse Transmission",
      card_type: "sequence",
      body: "The source gives chemical synapse transmission as a receptor-mediated flow.",
      diagram_data: { type: "bio-synapse-flow" },
      table_data: table(["Step", "Event"], [
        ["1", "Impulse reaches axon terminal"],
        ["2", "Synaptic vesicles bind on plasma membrane"],
        ["3", "Neurotransmitter is released"],
        ["4", "Neurotransmitter diffuses across synaptic cleft"],
        ["5", "It combines with receptors on post-synaptic membrane"],
        ["6", "Ion channels open, ions enter and action potential is generated"],
      ]),
      recall_data: recall("Name two neurotransmitters listed in the source.", "Acetylcholine and adrenaline."),
      importance: 5,
      source_page: 83,
      sort_order: 9,
    }),
    card(chapterId, "cns-vs-pns", {
      title: "CNS vs PNS",
      card_type: "comparison",
      body: "The human nervous system has central and peripheral parts.",
      table_data: table(["System", "Source-backed components"], [
        ["Central neural system (CNS)", "Brain and spinal cord"],
        ["Peripheral nervous system (PNS)", "All nerves; includes cranial nerves and spinal nerves"],
      ]),
      recall_data: recall("What are the two parts of CNS?", "Brain and spinal cord."),
      importance: 5,
      source_page: 83,
      sort_order: 10,
    }),
    card(chapterId, "brain-classification", {
      title: "Brain Classification",
      card_type: "classification",
      body: "Brain has three divisions: forebrain, midbrain and hindbrain.",
      diagram_data: { type: "bio-brain-classification" },
      table_data: table(["Division", "Source-backed parts"], [
        ["Forebrain", "Cerebrum and diencephalon"],
        ["Midbrain", "Corpora quadrigemina and cerebral aqueduct region"],
        ["Hindbrain", "Cerebellum, pons and medulla oblongata"],
        ["Brain stem", "Midbrain and hindbrain"],
      ]),
      recall_data: recall("Which brain divisions form the brain stem?", "Midbrain and hindbrain."),
      importance: 5,
      source_page: 83,
      sort_order: 11,
    }),
    card(chapterId, "brain-protection", {
      title: "Brain Protection",
      card_type: "fact",
      body: "The brain is protected in the cranial cavity and covered by cranial meninges.",
      table_data: table(["Structure", "Source-backed recall"], [
        ["Meninges", "Outer dura mater, middle arachnoid mater and inner pia mater"],
        ["Subarachnoid space", "Between pia mater and arachnoid mater; filled with cerebrospinal fluid"],
        ["Ventricles", "Also filled with CSF"],
      ]),
      recall_data: recall("Which space contains cerebrospinal fluid?", "Subarachnoid space.", ["The ventricles of the brain are also filled with CSF."]),
      importance: 4,
      source_page: 83,
      sort_order: 12,
    }),
    card(chapterId, "cerebrum-cortex", {
      title: "Cerebrum and Cerebral Cortex",
      card_type: "classification",
      body: "The cerebrum is the largest part of the brain.",
      table_data: table(["Structure", "Source-backed recall"], [
        ["Cerebral hemispheres", "Two hemispheres held together by corpus callosum"],
        ["Cerebral cortex", "Outer part with convolutions and depressions; formed of gray matter"],
        ["White matter", "Inner part of cerebrum"],
        ["Motor area", "Controls voluntary movements of muscles"],
        ["Sensory area", "Controls functioning of sense organs"],
        ["Association area", "Responsible for intersensory associations, memory and communication"],
      ]),
      recall_data: recall("Which tract holds the two cerebral hemispheres together?", "Corpus callosum."),
      importance: 5,
      source_page: 83,
      sort_order: 13,
    }),
    card(chapterId, "thalamus-hypothalamus", {
      title: "Thalamus vs Hypothalamus",
      card_type: "comparison",
      body: "Diencephalon includes thalamus and hypothalamus.",
      table_data: table(["Structure", "Source-backed function"], [
        ["Thalamus", "Coordinating centre or relay station for sensory and motor impulses"],
        ["Hypothalamus", "Regulates temperature, thirst, hunger and emotions"],
        ["Hypothalamus", "Secretes hypothalamic hormones and controls pituitary gland"],
        ["Hypothalamus", "Controls sleep, wakefulness, blood pressure and heart rate"],
      ]),
      recall_data: recall("Which part regulates hunger and body temperature?", "Hypothalamus."),
      importance: 5,
      source_page: 83,
      sort_order: 14,
    }),
    card(chapterId, "midbrain-hindbrain-functions", {
      title: "Midbrain and Hindbrain Functions",
      card_type: "comparison",
      body: "The source gives compact structure-function points for midbrain and hindbrain.",
      table_data: table(["Part", "Function/detail"], [
        ["Corpora quadrigemina", "Anterior pair is centre of visual reflexes; posterior pair is centre of auditory reflex"],
        ["Cerebellum", "Coordinates muscular activities and body equilibrium"],
        ["Pons varoli", "Interconnects brain regions; coordinates eye and ear activities and regulates respiration"],
        ["Medulla oblongata", "Controls respiration, cardiovascular reflexes, gastric secretions, peristalsis, salivation, vomiting, sneezing and coughing"],
      ]),
      recall_data: recall("Which hindbrain part coordinates muscular activities and body equilibrium?", "Cerebellum."),
      importance: 5,
      source_page: 83,
      sort_order: 15,
    }),
    card(chapterId, "spinal-cord", {
      title: "Spinal Cord",
      card_type: "fact",
      body: "Spinal cord is enclosed within the spinal canal and protected by meninges.",
      table_data: table(["Cue", "Source-backed detail"], [
        ["Central canal", "Contains CSF"],
        ["Matter arrangement", "Outer white matter and inner gray matter"],
        ["Function 1", "Conduction of impulses to and from the brain"],
        ["Function 2", "Centre of spinal reflexes"],
      ]),
      recall_data: recall("What are the two functions of spinal cord in the source?", "Conduction of impulses to and from the brain, and centre of spinal reflexes."),
      importance: 4,
      source_page: 83,
      sort_order: 16,
    }),
    card(chapterId, "afferent-vs-efferent", {
      title: "Afferent vs Efferent Fibres",
      card_type: "comparison",
      body: "PNS nerve fibres are sensory or motor by direction of impulse.",
      table_data: table(["Fibre", "Direction"], [
        ["Afferent or sensory", "Carry impulses from sense organs to CNS"],
        ["Efferent or motor", "Carry impulses from CNS to muscles and glands"],
      ]),
      recall_data: recall("Which fibre carries impulses from sense organs to CNS?", "Afferent or sensory fibre."),
      importance: 5,
      source_page: 84,
      sort_order: 17,
    }),
    card(chapterId, "somatic-vs-autonomic", {
      title: "Somatic vs Autonomic Neural System",
      card_type: "comparison",
      body: "PNS has somatic and autonomic divisions.",
      table_data: table(["Division", "Source-backed role"], [
        ["Somatic neural system", "Relays impulses from CNS to skeletal muscles"],
        ["Autonomic neural system", "Transmits impulses from CNS to involuntary organs and smooth muscles"],
        ["Visceral nervous system", "Nerves, fibres, ganglia and plexus carrying impulses between CNS and viscera"],
      ]),
      recall_data: recall("Which PNS division relays impulses to skeletal muscles?", "Somatic neural system."),
      importance: 5,
      source_page: 84,
      sort_order: 18,
    }),
    card(chapterId, "sympathetic-vs-parasympathetic", {
      title: "Sympathetic vs Parasympathetic",
      card_type: "comparison",
      body: "The source contrasts emergency preparation with resting-state return.",
      table_data: table(["System", "Source-backed effect"], [
        ["Sympathetic", "Prepares body for emergencies, stresses and dangers"],
        ["Sympathetic", "Increases heartbeat and breathing rate, constricts arteries and elevates BP"],
        ["Parasympathetic", "Returns body to resting state after stressful situations"],
        ["Parasympathetic", "Slows heartbeat, dilates arteries and lowers BP"],
      ]),
      recall_data: recall("Which autonomic division elevates BP in the source?", "Sympathetic system.", [], [], ["Parasympathetic lowers BP."]),
      importance: 5,
      source_page: 84,
      sort_order: 19,
    }),
    card(chapterId, "reflex-action", {
      title: "Reflex Action",
      card_type: "concept",
      body: "Reflex action is a rapid, involuntary and unconscious action of the body in response to a stimulus.",
      table_data: table(["Source examples", "Recall detail"], [
        ["Hot object", "Withdrawal of hand"],
        ["Nursing baby", "Touching lips evokes sucking reflex"],
        ["Light", "Closing of eyelids"],
        ["Knee jerk", "Knee jerk phenomenon"],
        ["Conditioned reflex", "Repeated seeing or smelling a food before tasting can evoke salivation"],
      ]),
      recall_data: recall("What is reflex action?", "Rapid, involuntary and unconscious action of body in response to a stimulus."),
      importance: 5,
      source_page: 84,
      sort_order: 20,
    }),
    card(chapterId, "reflex-arc", {
      title: "Reflex Arc",
      card_type: "sequence",
      body: "Reflex arc is the pathway of impulses in a reflex action.",
      diagram_data: { type: "bio-reflex-arc" },
      table_data: table(["Order", "Component"], [
        ["1", "Receptor organ receives stimulus"],
        ["2", "Sensory or afferent neuron transmits impulse to CNS"],
        ["3", "Intermediate or connector neuron connects sensory and motor neurons"],
        ["4", "Motor or efferent neuron conducts impulse to effector organ"],
        ["5", "Effector organ, muscle or gland, responds"],
      ]),
      recall_data: recall("Which neuron connects sensory and motor neurons in a reflex arc?", "Intermediate or connector neuron."),
      importance: 5,
      source_page: 84,
      sort_order: 21,
    }),
    card(chapterId, "eye-layers", {
      title: "Eye Layers and Front Structures",
      card_type: "classification",
      body: "The eyeball has three layers: sclera, choroid and retina.",
      diagram_data: { type: "bio-eye-layout" },
      table_data: table(["Structure", "Source-backed recall"], [
        ["Sclera", "External layer formed of dense connective tissue"],
        ["Cornea", "Anterior transparent portion of sclera"],
        ["Choroid", "Bluish middle layer containing many blood vessels"],
        ["Ciliary body", "Thick anterior choroid forms ciliary body"],
        ["Iris", "Visible pigmented opaque portion with pupil"],
        ["Pupil", "Diameter regulated by muscle fibres of iris"],
        ["Lens", "Transparent crystalline lens held by ligaments attached to ciliary body"],
      ]),
      recall_data: recall("Which eye layer forms the cornea anteriorly?", "Sclera."),
      importance: 5,
      source_page: 84,
      sort_order: 22,
    }),
    card(chapterId, "retina-rods-cones", {
      title: "Rods vs Cones",
      card_type: "comparison",
      body: "Retina contains ganglion cells, bipolar cells and photoreceptor cells.",
      table_data: table(["Feature", "Cones", "Rods"], [
        ["Function", "Daylight or photopic vision and colour vision", "Twilight or scotopic vision"],
        ["Photopigment", "Photopsin responding to red, green and blue lights", "Rhodopsin or visual purple"],
        ["Vitamin link", "Photopigments are formed of opsin and retinal", "Rhodopsin contains a derivative of Vitamin A"],
        ["Special location", "Only cones are densely packed in fovea", "-"],
      ]),
      recall_data: recall("Which photoreceptors are responsible for twilight vision?", "Rod cells.", [], [], ["Cones are for daylight and colour vision."]),
      importance: 5,
      source_page: 84,
      sort_order: 23,
    }),
    card(chapterId, "blind-spot-fovea", {
      title: "Blind Spot and Fovea",
      card_type: "fact",
      body: "The source distinguishes the blind spot from macula lutea and fovea.",
      table_data: table(["Structure", "Source-backed recall"], [
        ["Blind spot", "Region where optic nerves leave eye and retinal blood vessels enter; photoreceptors absent"],
        ["Macula lutea", "Yellowish pigmented spot lateral to blind spot"],
        ["Fovea", "Central pit of macula lutea with only densely packed cones; point of greatest visual acuity"],
      ]),
      recall_data: recall("Where is visual acuity greatest?", "Fovea."),
      importance: 5,
      source_page: 84,
      sort_order: 24,
    }),
    card(chapterId, "aqueous-vs-vitreous", {
      title: "Aqueous vs Vitreous Humour",
      card_type: "comparison",
      body: "The source names two chambers and their contents.",
      table_data: table(["Chamber", "Location", "Content"], [
        ["Aqueous chamber", "Between cornea and lens", "Aqueous humor, a thin watery fluid"],
        ["Vitreous chamber", "Between lens and retina", "Vitreous humor, a transparent gel"],
      ]),
      recall_data: recall("Which chamber contains a transparent gel?", "Vitreous chamber."),
      importance: 4,
      source_page: 85,
      sort_order: 25,
    }),
    card(chapterId, "vision-mechanism", {
      title: "Mechanism of Vision",
      card_type: "sequence",
      body: "Vision begins with light focusing on retina and ends with analysis in visual cortex.",
      table_data: table(["Step", "Source-backed event"], [
        ["1", "Light reflected from object enters through cornea and lens"],
        ["2", "Light focuses on retina"],
        ["3", "Retinal dissociates from opsin"],
        ["4", "Membrane permeability changes and impulse forms in photoreceptors"],
        ["5", "Action potentials form in ganglion cells through bipolar cells"],
        ["6", "Optic nerves transmit impulses to brain visual cortex"],
        ["7", "Image is recognized based on memory and experience"],
      ]),
      recall_data: recall("Which nerve transmits visual impulses to the brain?", "Optic nerve."),
      importance: 5,
      source_page: 85,
      sort_order: 26,
    }),
    card(chapterId, "ear-divisions", {
      title: "Outer vs Middle vs Inner Ear",
      card_type: "comparison",
      body: "The ear is the stato-acoustic organ for hearing and balancing.",
      diagram_data: { type: "bio-ear-layout" },
      table_data: table(["Division", "Source-backed structures/functions"], [
        ["External ear", "Pinna and auditory meatus; wax and hairs protect ears from foreign objects"],
        ["Middle ear", "Tympanic cavity and ear ossicles; Eustachian canal maintains equal pressure on either side of eardrum"],
        ["Inner ear", "Bony labyrinth and membranous labyrinth; cochlea and vestibular apparatus"],
      ]),
      recall_data: recall("Which tube connects middle ear to pharynx?", "Auditory tube or Eustachian canal."),
      importance: 5,
      source_page: 85,
      sort_order: 27,
    }),
    card(chapterId, "ear-ossicles-cochlea", {
      title: "Ear Ossicles and Cochlea",
      card_type: "classification",
      body: "The source gives key small-bone and cochlear membrane details.",
      table_data: table(["Structure", "Source-backed recall"], [
        ["Malleus", "Attached to tympanum"],
        ["Incus", "One of the three ear ossicles"],
        ["Stapes", "Smallest bone of the body; attached to oval window"],
        ["Scala vestibula and scala media", "Separated by Reissner's membrane"],
        ["Scala media and scala tympani", "Separated by basilar membrane"],
        ["Organ of Corti", "Complex receptor organ with sensory hair cells"],
      ]),
      recall_data: recall("What is the smallest bone of the body?", "Stapes."),
      importance: 5,
      source_page: 85,
      sort_order: 28,
    }),
    card(chapterId, "hearing-mechanism", {
      title: "Mechanism of Hearing",
      card_type: "sequence",
      body: "Sound becomes auditory nerve impulses through eardrum, ossicles, cochlear fluid and hair cells.",
      table_data: table(["Step", "Event"], [
        ["1", "Pinna collects sound waves"],
        ["2", "Waves reach tympanic membrane via ear canal"],
        ["3", "Tympanic membrane vibrates"],
        ["4", "Vibrations transmit to ear ossicles and oval window"],
        ["5", "Perilymph in vestibular canal vibrates"],
        ["6", "Basilar membrane vibrates and hair cells press against tectorial membrane"],
        ["7", "Auditory nerve carries impulses to auditory centre of brain"],
      ]),
      recall_data: recall("Which membrane do sensory hair cell endings press against?", "Tectorial membrane."),
      importance: 5,
      source_page: 85,
      sort_order: 29,
    }),
    card(chapterId, "vestibular-apparatus", {
      title: "Vestibular Apparatus",
      card_type: "classification",
      body: "Vestibular apparatus is responsible for equilibrium and posture.",
      table_data: table(["Part", "Source-backed detail"], [
        ["Semicircular canals", "Three canals; two vertical and one horizontal"],
        ["Ampulla", "Bulging at one end of each canal"],
        ["Crista ampullaris", "Lump inside ampulla; long cilia form cupula"],
        ["Otolith organ", "Consists of utricle and saccule"],
        ["Macula", "Projecting ridge of utricle and saccule"],
        ["Crista and Macula", "Specific receptors containing sensory hair cells"],
      ]),
      recall_data: recall("Which receptors are responsible for equilibrium and posture?", "Crista and Macula."),
      importance: 4,
      source_page: 85,
      sort_order: 30,
    }),
    card(chapterId, "nose-tongue-skin", {
      title: "Nose, Tongue and Skin",
      card_type: "classification",
      body: "The source closes sense organs with smell, taste and skin receptors.",
      table_data: table(["Organ", "Source-backed recall"], [
        ["Nose", "Organ of smell; olfactory receptors are made of olfactory epithelium"],
        ["Tongue", "Organ of taste; four primary tastes are sweet, salt, sour and bitter"],
        ["Nose and tongue", "Chemoreceptors; taste and smell are functionally similar and interrelated"],
        ["Skin", "Largest sense organ; receptors for heat, cold, touch, pain and pressure"],
      ]),
      recall_data: recall("Which sense organ is the largest?", "Skin."),
      importance: 4,
      source_page: 86,
      sort_order: 31,
    }),
  ];
}

function endocrineCards(chapterId) {
  return [
    card(chapterId, "endocrine-system-overview", {
      title: "Endocrine System Overview",
      card_type: "concept",
      body: "Endocrine system includes endocrine or ductless glands and their secretions called hormones.",
      table_data: table(["Term", "Source-backed meaning"], [
        ["Endocrine glands", "Ductless glands"],
        ["Hormones", "Non-nutrient chemicals acting as intercellular messengers"],
        ["Amount", "Produced in trace amounts"],
      ]),
      recall_data: recall("What are hormones in the source?", "Non-nutrient chemicals that act as intercellular messengers and are produced in trace amounts."),
      importance: 5,
      source_page: 87,
      sort_order: 1,
    }),
    card(chapterId, "human-endocrine-glands", {
      title: "Human Endocrine Glands",
      card_type: "classification",
      body: "The source lists nine human endocrine gland groups.",
      table_data: table(["Order", "Gland"], [
        ["1", "Hypothalamus"],
        ["2", "Pituitary"],
        ["3", "Pineal"],
        ["4", "Thyroid"],
        ["5", "Parathyroid"],
        ["6", "Thymus"],
        ["7", "Adrenals"],
        ["8", "Pancreas or Islets of Langerhans"],
        ["9", "Gonads: testis and ovary"],
      ]),
      recall_data: recall("Which endocrine gland is listed as Islets of Langerhans?", "Pancreas."),
      importance: 4,
      source_page: 87,
      sort_order: 2,
    }),
    card(chapterId, "hypothalamus-hormones", {
      title: "Hypothalamus Hormones",
      card_type: "classification",
      body: "Neurosecretory cells of hypothalamus secrete releasing hormones, inhibiting hormones, oxytocin and vasopressin.",
      table_data: table(["Hormone type", "Source-backed role/example"], [
        ["Releasing hormones", "Stimulate secretion of pituitary hormones"],
        ["GnRH", "Stimulates pituitary to release gonadotropins FSH and LH"],
        ["Inhibiting hormones", "Inhibit secretion of pituitary hormones"],
        ["Somatostatin", "Inhibits release of growth hormone from pituitary"],
        ["Oxytocin and vasopressin", "Transported axonally and stored in pituitary"],
      ]),
      recall_data: recall("Which hypothalamic hormone inhibits GH release in the source?", "Somatostatin."),
      importance: 5,
      source_page: 87,
      sort_order: 3,
    }),
    card(chapterId, "pituitary-lobes", {
      title: "Anterior vs Posterior Pituitary",
      card_type: "comparison",
      body: "Pituitary is in sella tursica and attached to hypothalamus by a stalk.",
      diagram_data: { type: "bio-hypothalamus-pituitary" },
      table_data: table(["Feature", "Adenohypophysis", "Neurohypophysis"], [
        ["Position/name", "Anterior pituitary", "Posterior pituitary"],
        ["Parts", "Pars distalis and pars intermedia", "Stores oxytocin and vasopressin from hypothalamus"],
        ["Source role", "Produces pituitary hormones", "Storage and release of hypothalamic hormones"],
      ]),
      recall_data: recall("Which pituitary part stores oxytocin and vasopressin?", "Neurohypophysis.", [], [], ["They are from hypothalamus and transported axonally."]),
      importance: 5,
      source_page: 87,
      sort_order: 4,
    }),
    card(chapterId, "anterior-pituitary-hormones", {
      title: "Anterior Pituitary Hormones",
      card_type: "table",
      body: "Pars distalis produces major anterior pituitary hormones.",
      table_data: table(["Hormone", "Source-backed function"], [
        ["GH or somatotropin", "Body growth"],
        ["PRL or prolactin", "Growth of mammary glands and milk production"],
        ["TSH", "Stimulates thyroid gland to secrete thyroid hormones"],
        ["ACTH", "Stimulates adrenal cortex to synthesise and secrete steroid hormones or glucocorticoids"],
        ["FSH", "Stimulates gonadal activity; spermatogenesis in males and ovarian follicle growth/development in females"],
        ["LH", "Stimulates gonadal activity; androgen secretion in males, ovulation and corpus luteum maintenance in females"],
        ["MSH", "From pars intermedia; acts on melanocytes to regulate skin pigmentation"],
      ]),
      recall_data: recall("Which anterior pituitary hormone stimulates thyroid hormone secretion?", "TSH."),
      importance: 5,
      source_page: 87,
      sort_order: 5,
    }),
    card(chapterId, "gh-disorders", {
      title: "Growth Hormone Disorders",
      card_type: "neet_trap",
      body: "GH secretion level and timing produce different disorders.",
      table_data: table(["GH condition", "Source-backed effect"], [
        ["Over-secretion", "Gigantism or abnormal growth"],
        ["Hyposecretion", "Dwarfism or stunted growth"],
        ["Adult over-secretion", "Acromegaly, severe disfigurement especially of face; serious complications and premature death"],
      ]),
      recall_data: recall("Which GH disorder occurs due to adult over-secretion?", "Acromegaly.", [], [], ["Hyposecretion causes dwarfism; over-secretion causes gigantism."]),
      importance: 5,
      source_page: 87,
      sort_order: 6,
    }),
    card(chapterId, "posterior-pituitary-hormones", {
      title: "Oxytocin and ADH",
      card_type: "comparison",
      body: "Neurohypophysis stores oxytocin and vasopressin from hypothalamus.",
      table_data: table(["Hormone", "Source-backed function/disorder"], [
        ["Oxytocin", "Contracts smooth muscles; in females stimulates uterus contraction during childbirth and milk ejection"],
        ["Vasopressin or ADH", "Stimulates reabsorption of water and electrolytes by DCT of kidney and reduces diuresis"],
        ["ADH deficiency", "Diminished ability of kidney to conserve water, water loss and dehydration; Diabetes insipidus"],
      ]),
      recall_data: recall("Which posterior pituitary hormone reduces diuresis?", "Vasopressin or ADH."),
      importance: 5,
      source_page: 87,
      sort_order: 7,
    }),
    card(chapterId, "pineal-melatonin", {
      title: "Pineal Gland and Melatonin",
      card_type: "fact",
      body: "Pineal is the smallest endocrine gland and is located on dorsal side of forebrain.",
      table_data: table(["Cue", "Source-backed detail"], [
        ["Hormone", "Melatonin"],
        ["Rhythm", "Regulates diurnal or 24-hour rhythm such as sleep-wake cycle and body temperature"],
        ["Other effects", "Influences metabolism, pigmentation, menstrual cycle and defense capability"],
      ]),
      recall_data: recall("Which gland is the smallest endocrine gland in the source?", "Pineal gland."),
      importance: 4,
      source_page: 87,
      sort_order: 8,
    }),
    card(chapterId, "thyroid-hormones", {
      title: "Thyroid Hormones",
      card_type: "classification",
      body: "The thyroid is the largest endocrine gland and contains follicles and stromal tissues.",
      table_data: table(["Hormone", "Source-backed function"], [
        ["T4 and T3", "Regulate basal metabolic rate"],
        ["T4 and T3", "Support physical, mental and sexual development"],
        ["T4 and T3", "Support RBC formation"],
        ["T4 and T3", "Control metabolism of carbohydrates, proteins and fats"],
        ["T4 and T3", "Maintain water and electrolyte balance"],
        ["Thyrocalcitonin or TCT", "Lowers blood calcium levels; hypocalcaemic hormone"],
      ]),
      recall_data: recall("Which thyroid hormone lowers blood calcium level?", "Thyrocalcitonin or TCT."),
      importance: 5,
      source_page: 88,
      sort_order: 9,
    }),
    card(chapterId, "thyroid-disorders", {
      title: "Thyroid Disorders",
      card_type: "comparison",
      body: "The source connects iodine deficiency, thyroid hormone excess and specific symptoms.",
      table_data: table(["Condition", "Source-backed recall"], [
        ["Goiter", "Enlargement of thyroid gland due to deficiency of iodine"],
        ["Hypothyroidism in adult women", "Irregular menstrual cycle"],
        ["Hypothyroidism during pregnancy", "Stunted growth or cretinism, mental retardation, low intelligence quotient, abnormal skin, deaf-mutism etc."],
        ["Hyperthyroidism", "Abnormal increase of thyroid hormones with adverse physiological effects"],
        ["Exophthalmic goiter or Grave's disease", "Hyperthyroidism with enlarged thyroid, protruded eyeballs, increased BMR and weight loss"],
      ]),
      recall_data: recall("What causes goiter in the source?", "Deficiency of iodine.", [], [], ["Grave's disease is a form of hyperthyroidism."]),
      importance: 5,
      source_page: 88,
      sort_order: 10,
    }),
    card(chapterId, "parathyroid-pth", {
      title: "Parathyroid Hormone",
      card_type: "concept",
      body: "Four parathyroid glands secrete parathyroid hormone or PTH, a peptide hormone.",
      table_data: table(["Function", "Source-backed detail"], [
        ["Blood calcium", "Increases Ca2+ level in blood; hypercalcaemic hormone"],
        ["Bone", "Stimulates bone resorption or demineralization"],
        ["Kidney", "Stimulates reabsorption of Ca2+ by renal tubules"],
        ["Digestive food", "Increases Ca2+ absorption from digested food"],
        ["Balance", "Along with TCT, helps calcium balance in the body"],
      ]),
      recall_data: recall("Which hormone is hypercalcaemic in the source?", "Parathyroid hormone (PTH).", [], [], ["TCT is hypocalcaemic."]),
      importance: 5,
      source_page: 88,
      sort_order: 11,
    }),
    card(chapterId, "thymus-thymosins", {
      title: "Thymus and Thymosins",
      card_type: "fact",
      body: "Thymus is located between lungs behind sternum on the ventral side of aorta.",
      table_data: table(["Cue", "Source-backed detail"], [
        ["Hormone", "Thymosins, peptide hormones"],
        ["Cell-mediated immunity", "Differentiation of T-lymphocytes"],
        ["Humoral immunity", "Promote antibody production"],
        ["Old age", "Thymus degenerates, thymosin production decreases and immune responses weaken"],
      ]),
      recall_data: recall("Which hormone promotes T-lymphocyte differentiation?", "Thymosins."),
      importance: 4,
      source_page: 88,
      sort_order: 12,
    }),
    card(chapterId, "adrenal-cortex-vs-medulla", {
      title: "Adrenal Cortex vs Medulla",
      card_type: "comparison",
      body: "Adrenal gland has cortex and medulla with different hormone classes.",
      table_data: table(["Feature", "Adrenal cortex", "Adrenal medulla"], [
        ["Layers/part", "Inner zona reticularis, middle zona fasciculata and outer zona glomerulosa", "Medullary part"],
        ["Hormones", "Corticoid hormones", "Catecholamines: adrenaline and noradrenaline"],
        ["Main role", "Metabolism, electrolyte/water balance and androgenic effects", "Emergency hormones or fight-or-flight response"],
        ["Disorder/effect", "Deficiency causes Addison's disease", "Increases alertness, heartbeat and respiratory rate"],
      ]),
      recall_data: recall("Which adrenal part secretes adrenaline and noradrenaline?", "Adrenal medulla.", [], [], ["Adrenal cortex produces corticoid hormones."]),
      importance: 5,
      source_page: 88,
      sort_order: 13,
    }),
    card(chapterId, "adrenal-cortex-hormones", {
      title: "Adrenal Cortex Hormones",
      card_type: "table",
      body: "The source separates adrenal cortex hormones into glucocorticoids, mineralocorticoids and androgenic corticoids.",
      table_data: table(["Hormone group", "Main source-backed functions"], [
        ["Glucocorticoids mainly cortisol", "Carbohydrate metabolism; stimulate gluconeogenesis, lipolysis and proteolysis; inhibit amino acid uptake; maintain cardiovascular and kidney functions; stimulate RBC production; anti-inflammatory and immune suppression"],
        ["Mineralocorticoids mainly aldosterone", "Regulate body fluid volume, electrolyte balance, osmotic pressure and blood pressure"],
        ["Aldosterone", "Stimulates reabsorption of Na+ and water from renal tubules and excretion of K+ and PO43- ions"],
        ["Androgenic corticoids", "Growth of axial hair, pubic hair and facial hair during puberty"],
      ]),
      recall_data: recall("Which mineralocorticoid is named in the source?", "Aldosterone."),
      importance: 5,
      source_page: 88,
      sort_order: 14,
    }),
    card(chapterId, "adrenal-medulla-hormones", {
      title: "Adrenal Medulla Hormones",
      card_type: "concept",
      body: "Adrenaline and noradrenaline are catecholamines secreted rapidly in stress emergency situations.",
      table_data: table(["Effect", "Source-backed detail"], [
        ["Name", "Emergency hormones or hormones of fight or flight"],
        ["Body effects", "Increase alertness, pupillary dilation, piloerection, sweating, heartbeat, heart contraction and respiratory rate"],
        ["Metabolic effects", "Stimulate glycogenolysis to increase blood glucose; also stimulate lipolysis and proteolysis"],
      ]),
      recall_data: recall("Which hormones are called fight-or-flight hormones in the source?", "Adrenaline and noradrenaline."),
      importance: 5,
      source_page: 88,
      sort_order: 15,
    }),
    card(chapterId, "pancreas-islets", {
      title: "Pancreas and Islets of Langerhans",
      card_type: "fact",
      body: "Pancreas is a composite or heterocrine gland: exocrine plus endocrine.",
      table_data: table(["Cue", "Source-backed detail"], [
        ["Endocrine part", "Islets of Langerhans"],
        ["Islet number", "About 1-2 million islets"],
        ["Pancreatic tissue", "1-2% of pancreatic tissue"],
        ["Alpha cells", "Secrete glucagon"],
        ["Beta cells", "Secrete insulin"],
        ["Shared role", "Maintain glucose homeostasis in blood"],
      ]),
      recall_data: recall("Which pancreatic cells secrete insulin?", "Beta cells."),
      importance: 5,
      source_page: 88,
      sort_order: 16,
    }),
    card(chapterId, "insulin-vs-glucagon", {
      title: "Insulin vs Glucagon",
      card_type: "comparison",
      body: "Glucagon raises blood sugar; insulin lowers blood sugar.",
      diagram_data: { type: "bio-blood-glucose-regulation" },
      table_data: table(["Feature", "Glucagon", "Insulin"], [
        ["Cell source", "Alpha cells", "Beta cells"],
        ["Factor", "Hyperglycemic factor", "Hypoglycemic factor"],
        ["Target cells", "Hepatocytes", "Hepatocytes and adipocytes"],
        ["Main effect", "Stimulates glycogenolysis and gluconeogenesis", "Enhances cellular glucose uptake and utilization"],
        ["Additional effect", "Reduces cellular glucose uptake and utilization", "Stimulates glycogenesis"],
      ]),
      recall_data: recall("Which pancreatic hormone is hypoglycemic?", "Insulin.", [], [], ["Glucagon is hyperglycemic."]),
      importance: 5,
      source_page: 88,
      sort_order: 17,
    }),
    card(chapterId, "diabetes-mellitus", {
      title: "Diabetes Mellitus",
      card_type: "neet_trap",
      body: "Prolonged hyperglycemia leads to diabetes mellitus in the source.",
      table_data: table(["Cue", "Source-backed detail"], [
        ["Cause phrase", "Prolonged hyperglycemia"],
        ["Effect", "Loss of glucose through urine and formation of harmful compounds like ketone bodies"],
        ["Treatment", "Insulin therapy"],
      ]),
      recall_data: recall("What treatment is stated for diabetes mellitus?", "Insulin therapy."),
      importance: 5,
      source_page: 88,
      sort_order: 18,
    }),
    card(chapterId, "testis-androgens", {
      title: "Testis and Androgens",
      card_type: "concept",
      body: "Leydig or interstitial cells in inter-tubular spaces produce androgens, mainly testosterone.",
      table_data: table(["Function", "Source-backed detail"], [
        ["Accessory sex organs", "Regulate development, maturation and functions"],
        ["Spermatogenesis", "Sperm production"],
        ["Behaviour/characters", "Stimulate sexual behavior, growth of muscles, hairs, aggressiveness, low pitch voice etc."],
        ["Metabolism", "Help in anabolism of protein and carbohydrate"],
      ]),
      recall_data: recall("Which cells produce testosterone in the source?", "Leydig or interstitial cells."),
      importance: 5,
      source_page: 89,
      sort_order: 19,
    }),
    card(chapterId, "estrogen-vs-progesterone", {
      title: "Estrogen vs Progesterone",
      card_type: "comparison",
      body: "Ovarian follicles produce estrogen; corpus luteum secretes progesterone.",
      table_data: table(["Feature", "Estrogen", "Progesterone"], [
        ["Source", "Ovarian follicles", "Corpus luteum after ovulation"],
        ["Hormone type", "Steroid hormone", "Steroid hormone"],
        ["Functions", "Growth and activities of female secondary sex organs; ovarian follicles and mammary glands; secondary sex characters and sexual behavior", "Supports pregnancy; acts on mammary glands to form alveoli and milk secretion"],
      ]),
      recall_data: recall("Which ovarian structure secretes progesterone?", "Corpus luteum.", [], [], ["Ovarian follicles produce estrogen."]),
      importance: 5,
      source_page: 89,
      sort_order: 20,
    }),
    card(chapterId, "heart-kidney-gi-hormones", {
      title: "Heart, Kidney and GI Hormones",
      card_type: "table",
      body: "The source includes hormones from heart, kidney and gastrointestinal tract.",
      table_data: table(["Source", "Hormone", "Main function"], [
        ["Atrial wall of heart", "Atrial natriuretic factor (ANF)", "When BP increases, dilates blood vessels to reduce BP"],
        ["JGA of kidney", "Erythropoietin", "Stimulates erythropoiesis or formation of RBC"],
        ["GI tract", "Gastrin", "Stimulates gastric glands to secrete HCl and pepsinogen"],
        ["GI tract", "Secretin", "Stimulates exocrine pancreas to secrete water and bicarbonate ions"],
        ["GI tract", "Cholecystokinin (CCK)", "Stimulates secretion of bile and pancreatic enzymes"],
        ["GI tract", "Gastric inhibitory peptide (GIP)", "Inhibits gastric secretion"],
      ]),
      recall_data: recall("Which kidney region produces erythropoietin in the source?", "JGA of kidney."),
      importance: 5,
      source_page: 89,
      sort_order: 21,
    }),
    card(chapterId, "hormone-chemical-classes", {
      title: "Chemical Classes of Hormones",
      card_type: "classification",
      body: "Hormones are classified by chemical nature.",
      table_data: table(["Class", "Source examples"], [
        ["Peptide, polypeptide, protein hormones", "Insulin, glucagon, pituitary hormones, hypothalamic hormones etc."],
        ["Steroids", "Cortisol, testosterone, estradiol and progesterone"],
        ["Iodothyronines", "Thyroid hormones"],
        ["Amino-acid derivatives", "Adrenaline, nor-adrenaline etc."],
      ]),
      recall_data: recall("Which hormone class includes cortisol and testosterone?", "Steroids."),
      importance: 4,
      source_page: 89,
      sort_order: 22,
    }),
    card(chapterId, "hormone-receptors-overview", {
      title: "Hormone Receptors",
      card_type: "concept",
      body: "Hormones act by binding specific receptor proteins in target tissues.",
      table_data: table(["Step", "Source-backed event"], [
        ["1", "Hormone binds a specific receptor"],
        ["2", "Hormone-receptor complex forms"],
        ["3", "Biochemical changes occur in target tissue"],
        ["4", "Metabolism and physiological functions are regulated"],
      ]),
      recall_data: recall("What complex forms when a hormone binds its receptor?", "Hormone-receptor complex."),
      importance: 4,
      source_page: 89,
      sort_order: 23,
    }),
    card(chapterId, "membrane-vs-intracellular-receptors", {
      title: "Membrane-Bound vs Intracellular Receptors",
      card_type: "comparison",
      body: "Hormone receptors are membrane-bound or intracellular.",
      diagram_data: { type: "bio-hormone-receptor-types" },
      table_data: table(["Feature", "Membrane-bound receptors", "Intracellular receptors"], [
        ["Hormone examples", "Protein hormone, FSH", "Steroid hormones, iodothyronines"],
        ["Cell entry", "Hormones do not enter target cell", "Hormones interact with intracellular receptors"],
        ["Messenger/action", "Generate second messengers such as cyclic AMP, IP3 and Ca2+", "Mostly regulate gene expression or chromosome function"],
        ["Effect", "Regulate cellular metabolism and physiological effects", "Physiological and developmental effects"],
      ]),
      recall_data: recall("Which receptor type generates second messengers?", "Membrane-bound receptors.", [], [], ["Steroid hormones and iodothyronines use intracellular receptors in the source."]),
      importance: 5,
      source_page: 89,
      sort_order: 24,
    }),
  ];
}

const biologyBatch6CardsBySlug = {
  "neural-control-and-co-ordination": neuralCards,
  "chemical-co-ordination-and-integration": endocrineCards,
};

export function getBiologyBatch6Chapters() {
  return BIOLOGY_BATCH_6_CHAPTER_DEFINITIONS.map((item) => ({
    id: chapter(item.slug),
    subject_id: "neet-biology",
    title: item.title,
    slug: item.slug,
    sort_order: item.sort_order,
    source_page: item.source_page,
  }));
}

export function getBiologyBatch6Cards() {
  return BIOLOGY_BATCH_6_CHAPTER_DEFINITIONS.flatMap((item) => biologyBatch6CardsBySlug[item.slug](chapter(item.slug)));
}
