export const BATCH_6_CHAPTER_DEFINITIONS = [
  { title: "Gravitation", slug: "gravitation", sort_order: 23 },
  { title: "Fluid Mechanics & Properties of Matter", slug: "fluid-mechanics-properties-matter", sort_order: 24 },
  { title: "Sound Waves", slug: "sound-waves", sort_order: 25 },
  { title: "Electromagnetic Waves", slug: "electromagnetic-waves", sort_order: 26 },
  { title: "Error and Measurement", slug: "error-and-measurement", sort_order: 27 },
  { title: "Principle of Communication", slug: "principle-of-communication", sort_order: 28 },
  { title: "Semiconductor", slug: "semiconductor", sort_order: 29 },
];

const chapter = (track, slug) => `${track}-physics-${slug}`;

const vars = {
  G: { latex: "G", symbol: "$G$", meaning: "universal gravitational constant" },
  g: { latex: "g", symbol: "$g$", meaning: "acceleration due to gravity" },
  P: { latex: "P", symbol: "$P$", meaning: "pressure, power, or source power depending on context" },
  E: { latex: "E", symbol: "$E$", meaning: "field, modulus, or electric field depending on context" },
  lambda: { latex: "\\lambda", symbol: "$\\lambda$", meaning: "wavelength" },
  I: { latex: "I", symbol: "$I$", meaning: "intensity or current depending on context" },
  rho: { latex: "\\rho", symbol: "$\\rho$", meaning: "density or resistivity depending on context" },
  sigma: { latex: "\\sigma", symbol: "$\\sigma$", meaning: "conductivity" },
};

function card(chapterId, slug, payload) {
  return {
    id: `${chapterId}-${slug}`,
    chapter_id: chapterId,
    table_data: null,
    diagram_data: null,
    diagram_svg: null,
    is_active: true,
    ...payload,
  };
}

function gravitationCards(chapterId) {
  return [
    card(chapterId, "universal-law-vector-form", {
      title: "Universal Law and Vector Form",
      card_type: "mixed",
      body: "The source begins Gravitation with Newton's law and the equal-opposite force relation in vector form.",
      formulas: [
        { latex: "F\\propto\\frac{m_1m_2}{r^2}" },
        { latex: "F=G\\frac{m_1m_2}{r^2}" },
        { latex: "\\vec F_{12}=\\frac{Gm_1m_2}{r^2}\\hat r_{12}" },
        { latex: "\\hat r_{12}=-\\hat r_{21}\\Rightarrow \\vec F_{12}=-\\vec F_{21}" },
      ],
      variables: [vars.G],
      conditions: ["$G=6.67\\times10^{-11}\\ \\text{N m}^2\\text{kg}^{-2}$."],
      diagram_data: { type: "gravitation-vector" },
      importance: 5,
      source_page: 73,
      sort_order: 1,
    }),
    card(chapterId, "field-and-potential", {
      title: "Gravitational Field and Potential",
      card_type: "formula",
      body: "The handbook defines gravitational field and potential for a point mass.",
      formulas: [
        { latex: "E=\\frac{F}{m}=\\frac{GM}{r^2}" },
        { latex: "V=-\\frac{GM}{r}" },
        { latex: "E=-\\frac{dV}{dr}" },
      ],
      variables: [vars.E, vars.G],
      conditions: [],
      importance: 5,
      source_page: 73,
      sort_order: 2,
    }),
    card(chapterId, "ring-and-disc", {
      title: "Ring and Thin Circular Disc",
      card_type: "mixed",
      body: "The source lists potential and field for a ring and a thin circular disc.",
      formulas: [
        { label: "Ring", latex: "V=-\\frac{GM}{\\sqrt{a^2+r^2}}" },
        { latex: "\\vec E=-\\frac{GMr}{(a^2+r^2)^{3/2}}\\hat r" },
        { latex: "E=-\\frac{GM\\cos\\theta}{x^2}" },
        { label: "Thin disc", latex: "V=-\\frac{2GM}{a^2}\\left[\\sqrt{a^2+r^2}-r\\right]" },
        { latex: "E=-\\frac{2GM}{a^2}\\left[1-\\frac{r}{\\sqrt{r^2+a^2}}\\right]= -\\frac{2GM}{a^2}(1-\\cos\\theta)" },
      ],
      variables: [vars.E, vars.G],
      conditions: ["For the ring, the field is maximum at $r=\\pm a/\\sqrt2$."],
      diagram_data: { type: "grav-ring-disc" },
      importance: 4,
      source_page: 74,
      sort_order: 3,
    }),
    card(chapterId, "sphere-shell-field", {
      title: "Solid Sphere and Spherical Shell",
      card_type: "table",
      body: "The handbook compares inside/outside potential and field for a non-conducting solid sphere and a uniform thin spherical shell.",
      formulas: [],
      variables: [vars.E, vars.G],
      conditions: [],
      table_data: {
        columns: ["Body and region", "Potential", "Field"],
        rows: [
          ["Solid sphere, $r<a$", "$V=-\\frac{GM}{2a^3}(3a^2-r^2)$", "$E=-\\frac{GMr}{a^3}$"],
          ["Solid sphere centre", "$V=-\\frac{3GM}{2a}$", "$E=0$"],
          ["Solid sphere, $r>a$", "$V=-\\frac{GM}{r}$", "$E=-\\frac{GM}{r^2}$"],
          ["Thin spherical shell, $r<a$", "$V=-\\frac{GM}{a}$", "$E=0$"],
          ["Thin spherical shell, $r>a$", "$V=-\\frac{GM}{r}$", "$E=-\\frac{GM}{r^2}$"],
        ],
      },
      diagram_data: { type: "grav-sphere-shell" },
      importance: 5,
      source_page: 74,
      sort_order: 4,
    }),
    card(chapterId, "variation-of-g", {
      title: "Variation of g",
      card_type: "mixed",
      body: "The source gives the variation of acceleration due to gravity with altitude, depth, and Earth surface location.",
      formulas: [
        { latex: "g_h=\\frac{GM_e}{(R_e+h)^2}=g\\left(1+\\frac{h}{R_e}\\right)^{-2}" },
        { latex: "g_h\\approx g\\left(1-\\frac{2h}{R_e}\\right),\\ h\\ll R_e" },
        { latex: "g_d=g\\left(1-\\frac{d}{R_e}\\right)" },
      ],
      variables: [vars.g],
      conditions: ["The source notes Earth's equatorial radius is about 21 km longer than polar radius, so $g_{pole}>g_{equator}$."],
      importance: 5,
      source_page: 74,
      sort_order: 5,
    }),
    card(chapterId, "satellite-velocity-period", {
      title: "Satellite Velocity and Time Period",
      card_type: "mixed",
      body: "The source gives orbital velocity and satellite period at altitude $h$.",
      formulas: [
        { latex: "v_0=\\left[\\frac{GM_e}{R_e+h}\\right]^{1/2}=\\left[\\frac{gR_e^2}{R_e+h}\\right]^{1/2}" },
        { latex: "h\\ll R_e\\Rightarrow v_0=\\sqrt{gR_e}=7.92\\ \\text{km s}^{-1}" },
        { latex: "T=\\frac{2\\pi(R_e+h)}{\\left[\\frac{gR_e^2}{R_e+h}\\right]^{1/2}}" },
        { latex: "T=\\frac{2\\pi}{R_e}\\left[\\frac{(R_e+h)^3}{g}\\right]^{1/2}" },
      ],
      variables: [vars.g],
      conditions: [],
      diagram_data: { type: "satellite-orbit" },
      importance: 5,
      source_page: 75,
      sort_order: 6,
    }),
    card(chapterId, "satellite-energy-kepler", {
      title: "Satellite Energy and Kepler Laws",
      card_type: "mixed",
      body: "The source lists satellite potential, kinetic, and total energy, then states Kepler's law of area and periods.",
      formulas: [
        { latex: "U=-\\frac{GM_em}{r}" },
        { latex: "K.E.=\\frac{GM_em}{2r}" },
        { latex: "E=-\\frac{GM_em}{2R_e}" },
        { latex: "\\text{Areal velocity}=\\frac{1}{2}r^2\\frac{d\\theta}{dt}=\\text{constant}" },
        { latex: "\\frac{1}{2}r^2\\omega=\\text{constant}" },
        { latex: "\\frac{T^2}{R^3}=\\text{constant}" },
      ],
      variables: [vars.G],
      conditions: ["The energy formula in the source is listed after the satellite section."],
      importance: 5,
      source_page: 75,
      sort_order: 7,
    }),
  ];
}

function fluidCards(chapterId) {
  return [
    card(chapterId, "hydraulic-press-elevator-fluid", {
      title: "Hydraulic Press and Elevator Fluid",
      card_type: "mixed",
      body: "The source opens the fluids section with hydraulic press, hydrostatic paradox, and upward accelerating elevator fluid.",
      formulas: [
        { latex: "p=\\frac{f}{a}=\\frac{F}{A}\\quad\\text{or}\\quad F=\\frac{A}{a}f" },
        { latex: "P_A=P_B=P_C" },
        { latex: "p=\\rho h(g+a_0)" },
        { latex: "B=m(g+a_0)" },
      ],
      variables: [vars.P, vars.rho],
      conditions: ["Elevator relation is for upward acceleration $a_0$."],
      diagram_data: { type: "fluid-elevator" },
      importance: 5,
      source_page: 75,
      sort_order: 1,
    }),
    card(chapterId, "accelerating-and-rotating-liquid", {
      title: "Accelerating and Rotating Liquid Surface",
      card_type: "mixed",
      body: "Horizontal acceleration tilts the free surface; rotation gives height rise as a function of radius.",
      formulas: [
        { latex: "\\tan\\theta=\\frac{a_0}{g}" },
        { latex: "p_1-p_2=\\rho l a_0" },
        { latex: "h_1-h_2=\\frac{la_0}{g}" },
        { latex: "h=\\frac{v^2}{2g}=\\frac{\\omega^2r^2}{2g}" },
      ],
      variables: [vars.g, vars.rho],
      conditions: [],
      diagram_data: { type: "fluid-accel-rotation" },
      importance: 5,
      source_page: 76,
      sort_order: 2,
    }),
    card(chapterId, "continuity-bernoulli-torricelli", {
      title: "Continuity, Bernoulli and Torricelli",
      card_type: "formula",
      body: "The source groups flow continuity, Bernoulli theorem, and speed of efflux.",
      formulas: [
        { latex: "a_1v_1=a_2v_2" },
        { latex: "av=\\text{constant}" },
        { latex: "\\frac{P}{\\rho}+\\frac{1}{2}v^2+gh=\\text{constant}" },
        { latex: "v=\\sqrt{\\frac{2gh}{1-A_2^2/A_1^2}}" },
      ],
      variables: [vars.P, vars.rho],
      conditions: ["In Torricelli's theorem, $A_2$ is area of hole and $A_1$ is area of vessel."],
      importance: 5,
      source_page: 76,
      sort_order: 3,
    }),
    card(chapterId, "stress-strain-young", {
      title: "Stress, Strain and Young's Modulus",
      card_type: "mixed",
      body: "The elasticity section defines stress, strain types, Young's modulus, elastic energy density, and inter-atomic force constant.",
      formulas: [
        { latex: "\\text{stress}=\\frac{F}{A}" },
        { latex: "\\epsilon=\\frac{\\text{change in configuration}}{\\text{original configuration}}" },
        { latex: "\\text{longitudinal strain}=\\frac{\\Delta L}{L}" },
        { latex: "\\epsilon_v=\\frac{\\Delta V}{V}" },
        { latex: "\\phi=\\frac{x}{l}" },
        { latex: "Y=\\frac{F/A}{\\Delta L/L}=\\frac{FL}{A\\Delta L}" },
        { latex: "u=\\frac{1}{2}(\\text{stress}\\times\\text{strain})=\\frac{1}{2}Y(\\text{strain})^2" },
        { latex: "k=Yr_0" },
      ],
      variables: [],
      conditions: [],
      importance: 5,
      source_page: 76,
      sort_order: 4,
    }),
    card(chapterId, "viscosity-stokes-terminal", {
      title: "Viscosity, Stokes Law and Terminal Velocity",
      card_type: "formula",
      body: "The source lists Newton's law of viscosity, Stokes law, and terminal velocity.",
      formulas: [
        { latex: "F=-\\eta A\\frac{dv}{dx}" },
        { latex: "F=6\\pi\\eta rv" },
        { latex: "v_T=\\frac{2r^2(\\rho-\\sigma)g}{9\\eta}" },
      ],
      variables: [vars.rho],
      conditions: [],
      importance: 5,
      source_page: 77,
      sort_order: 5,
    }),
    card(chapterId, "surface-tension-energy", {
      title: "Surface Tension and Surface Energy",
      card_type: "formula",
      body: "The handbook defines surface tension and identifies it with work per unit increase in surface area.",
      formulas: [
        { latex: "T=\\frac{\\text{total force on imaginary line}}{l}" },
        { latex: "T=S=\\frac{\\Delta W}{A}" },
      ],
      variables: [],
      conditions: ["Surface tension is numerically equal to surface energy or work done per unit increase in surface area."],
      importance: 4,
      source_page: 77,
      sort_order: 6,
    }),
    card(chapterId, "bubbles-drops-capillary", {
      title: "Bubbles, Drops and Capillary Rise",
      card_type: "mixed",
      body: "The source lists excess pressure for bubbles/drops and capillary rise.",
      formulas: [
        { label: "Bubble", latex: "p-p_a=\\frac{4T}{r}=p_{excess}" },
        { label: "Drop", latex: "p-p_a=\\frac{2T}{r}=p_{excess}" },
        { label: "Air bubble in liquid", latex: "p-p_a=\\frac{2T}{r}=p_{excess}" },
        { latex: "h=\\frac{2T\\cos\\theta}{r\\rho g}" },
      ],
      variables: [vars.P, vars.rho],
      conditions: [],
      diagram_data: { type: "capillary-bubble" },
      importance: 5,
      source_page: 77,
      sort_order: 7,
    }),
  ];
}

function soundCards(chapterId) {
  return [
    card(chapterId, "displacement-pressure-excess", {
      title: "Displacement and Pressure Excess",
      card_type: "formula",
      body: "The source writes longitudinal displacement and pressure excess for a travelling sound wave.",
      formulas: [
        { latex: "\\xi=A\\sin(\\omega t-kx)" },
        { latex: "P_{ex}=-B\\frac{\\partial\\xi}{\\partial x}=BAk\\cos(\\omega t-kx)" },
        { latex: "P_{m}=BAk" },
      ],
      variables: [vars.P],
      conditions: ["The pressure-excess relation is marked true for travelling and standing waves."],
      importance: 5,
      source_page: 77,
      sort_order: 1,
    }),
    card(chapterId, "speed-of-sound", {
      title: "Speed of Sound in Media",
      card_type: "table",
      body: "The source gives the general speed relation and the solid, liquid, and gas forms.",
      formulas: [{ latex: "C=\\sqrt{\\frac{E}{\\rho}}" }],
      variables: [vars.E, vars.rho],
      conditions: [],
      table_data: {
        columns: ["Medium", "Speed"],
        rows: [
          ["Solid", "$C=\\sqrt{\\frac{Y}{\\rho}}$"],
          ["Liquid", "$C=\\sqrt{\\frac{B}{\\rho}}$"],
          ["Gas", "$C=\\sqrt{\\frac{B}{\\rho}}=\\sqrt{\\frac{\\gamma P}{\\rho}}=\\sqrt{\\frac{\\gamma RT}{M_0}}$"],
        ],
      },
      importance: 5,
      source_page: 78,
      sort_order: 2,
    }),
    card(chapterId, "intensity-loudness-point-source", {
      title: "Intensity, Loudness and Point Source",
      card_type: "formula",
      body: "The handbook lists sound intensity, loudness in decibels, and point-source intensity.",
      formulas: [
        { latex: "\\langle I\\rangle=2\\pi^2f^2A^2\\rho v=\\frac{P_m^2}{2\\rho v}" },
        { latex: "\\langle I\\rangle\\propto P_m^2" },
        { latex: "L=10\\log_{10}\\left(\\frac{I}{I_0}\\right)\\ \\text{dB}" },
        { latex: "I_0=10^{-12}\\ \\text{W/m}^2" },
        { latex: "I=\\frac{P}{4\\pi r^2}" },
      ],
      variables: [vars.I, vars.P, vars.rho],
      conditions: ["$I_0$ is the minimum intensity human ears can listen to, per the source."],
      importance: 5,
      source_page: 78,
      sort_order: 3,
    }),
    card(chapterId, "sound-interference-pressure", {
      title: "Sound Interference by Pressure",
      card_type: "formula",
      body: "The source writes resultant excess pressure for two sound waves.",
      formulas: [
        { latex: "P_1=p_{m1}\\sin(\\omega t-kx_1+\\theta_1)" },
        { latex: "P_2=p_{m2}\\sin(\\omega t-kx_2+\\theta_2)" },
        { latex: "p=p_0\\sin(\\omega t-kx+\\theta)" },
        { latex: "p_0=\\sqrt{p_{m1}^2+p_{m2}^2+2p_{m1}p_{m2}\\cos\\phi}" },
        { latex: "\\phi=k(x_2-x_1)+(\\theta_1-\\theta_2)" },
        { latex: "I=I_1+I_2+2\\sqrt{I_1I_2}" },
      ],
      variables: [vars.I],
      conditions: [],
      importance: 4,
      source_page: 78,
      sort_order: 4,
    }),
    card(chapterId, "sound-interference-conditions", {
      title: "Constructive and Destructive Sound",
      card_type: "formula",
      body: "Constructive and destructive interference conditions are given in phase and path difference forms.",
      formulas: [
        { label: "Constructive", latex: "\\phi=2n\\pi\\Rightarrow p_0=p_{m1}+p_{m2}" },
        { label: "Destructive", latex: "\\phi=(2n+1)\\pi\\Rightarrow p_0=|p_{m1}-p_{m2}|" },
        { latex: "\\phi=\\frac{2\\pi}{\\lambda}\\Delta x" },
        { latex: "\\Delta x=n\\lambda" },
        { latex: "\\Delta x=(2n+1)\\frac{\\lambda}{2}" },
      ],
      variables: [vars.lambda],
      conditions: ["If $p_{m1}=p_{m2}$ and $\\phi=0,2\\pi,4\\pi,\\ldots$, then $p_0=2p_m$ and $I_0=4I_1$."],
      importance: 5,
      source_page: 78,
      sort_order: 5,
    }),
    card(chapterId, "organ-pipes", {
      title: "Open and Closed Organ Pipes",
      card_type: "mixed",
      body: "The source lists the harmonic frequencies for closed and open organ pipes.",
      formulas: [
        { label: "Closed organ pipe", latex: "f=\\frac{v}{4l},\\frac{3v}{4l},\\frac{5v}{4l},\\ldots,\\frac{(2n+1)v}{4l}" },
        { label: "Open organ pipe", latex: "f=\\frac{v}{2l},\\frac{2v}{2l},\\frac{3v}{2l},\\ldots,\\frac{nv}{2l}" },
      ],
      variables: [],
      conditions: ["In the closed-pipe expression, $n$ is overtone."],
      diagram_data: { type: "organ-pipe-modes" },
      importance: 5,
      source_page: 79,
      sort_order: 6,
    }),
    card(chapterId, "beats-doppler", {
      title: "Beats and Doppler Effect",
      card_type: "formula",
      body: "The source ends Sound Waves with beat frequency and Doppler observed frequency/wavelength.",
      formulas: [
        { latex: "f_{beats}=|f_1-f_2|" },
        { latex: "f'=f\\left(\\frac{v-v_o}{v-v_s}\\right)" },
        { latex: "\\lambda'=\\lambda\\left(\\frac{v-v_s}{v}\\right)" },
      ],
      variables: [vars.lambda],
      conditions: [],
      importance: 5,
      source_page: 79,
      sort_order: 7,
    }),
  ];
}

function emWaveCards(chapterId) {
  return [
    card(chapterId, "maxwell-equations", {
      title: "Maxwell Equations",
      card_type: "table",
      body: "The source lists the integral forms of Maxwell's equations.",
      formulas: [],
      variables: [vars.E],
      conditions: [],
      table_data: {
        columns: ["Law", "Equation"],
        rows: [
          ["Gauss law for electricity", "$\\oint \\vec E\\cdot d\\vec A=\\frac{Q}{\\epsilon_0}$"],
          ["Gauss law for magnetism", "$\\oint \\vec B\\cdot d\\vec A=0$"],
          ["Faraday law", "$\\oint \\vec E\\cdot d\\vec l=-\\frac{d\\Phi_B}{dt}$"],
          ["Ampere-Maxwell law", "$\\oint \\vec B\\cdot d\\vec l=\\mu_0 i_c+\\mu_0\\epsilon_0\\frac{d\\Phi_E}{dt}$"],
        ],
      },
      importance: 5,
      source_page: 79,
      sort_order: 1,
    }),
    card(chapterId, "oscillating-fields-speed", {
      title: "Oscillating Fields and Wave Speed",
      card_type: "mixed",
      body: "The source writes the electric field wave form, electric/magnetic amplitude relation, and wave speeds.",
      formulas: [
        { latex: "E=E_x(t)=E_0\\sin(kz-\\omega t)" },
        { latex: "E=E_0\\sin\\left[2\\pi\\left(\\frac{z}{\\lambda}-vt\\right)\\right]=E_0\\sin\\left[2\\pi\\left(\\frac{z}{\\lambda}-\\frac{t}{T}\\right)\\right]" },
        { latex: "\\frac{E_0}{B_0}=c" },
        { latex: "c=\\frac{1}{\\sqrt{\\mu_0\\epsilon_0}}" },
        { latex: "v=\\frac{1}{\\sqrt{\\mu\\epsilon}}" },
      ],
      variables: [vars.E, vars.lambda],
      conditions: ["$c$ is speed of light in vacuum; $v$ is speed of light in medium."],
      diagram_data: { type: "em-wave-orientation" },
      importance: 5,
      source_page: 79,
      sort_order: 2,
    }),
    card(chapterId, "em-momentum", {
      title: "Momentum Delivered by EM Wave",
      card_type: "formula",
      body: "For complete absorption, the source gives total momentum delivered to a surface from transferred energy.",
      formulas: [{ latex: "p=\\frac{U}{c}" }],
      variables: [],
      conditions: ["$U$ is energy transferred to a surface in time $t$."],
      importance: 4,
      source_page: 80,
      sort_order: 3,
    }),
    card(chapterId, "em-spectrum", {
      title: "Electromagnetic Spectrum",
      card_type: "table",
      body: "The handbook gives spectrum type, wavelength range, production, and detection.",
      formulas: [],
      variables: [vars.lambda],
      conditions: [],
      table_data: {
        columns: ["Type", "Wavelength range", "Production", "Detection"],
        rows: [
          ["Radio", "$>0.1\\ \\text{m}$", "Rapid acceleration and deceleration of electrons in aerials", "Receiver's aerials"],
          ["Microwave", "$0.1\\ \\text{m}$ to $1\\ \\text{mm}$", "Klystron valve or magnetron valve", "Point contact diodes"],
          ["Infra-red", "$1\\ \\text{mm}$ to $700\\ \\text{nm}$", "Vibration of atoms and molecules", "Thermopiles, bolometer, infrared photographic film"],
          ["Light", "$700\\ \\text{nm}$ to $400\\ \\text{nm}$", "Electrons in atoms emit light when they move to lower energy level", "Eye, photocells, photographic film"],
          ["Ultraviolet", "$400\\ \\text{nm}$ to $1\\ \\text{nm}$", "Inner shell electrons moving to lower level", "Photocells, photographic film"],
          ["X-rays", "$1\\ \\text{nm}$ to $10^{-3}\\ \\text{nm}$", "X-ray tubes or inner shell electrons", "Photographic film, Geiger tubes, ionisation chamber"],
          ["Gamma rays", "$<10^{-3}\\ \\text{nm}$", "Radioactive decay of the nucleus", "Same as X-rays in source table"],
        ],
      },
      importance: 5,
      source_page: 80,
      sort_order: 4,
    }),
  ];
}

function errorCards(chapterId) {
  return [
    card(chapterId, "least-count-significant-figures", {
      title: "Least Count and Significant Figures",
      card_type: "table",
      body: "The source lists instrument least counts and key significant-figure rules.",
      formulas: [],
      variables: [],
      conditions: ["Non-zero digits are significant.", "Zeros between two non-zero digits are significant.", "Change of units cannot change significant figures.", "For numbers less than one, zeros after decimal and before first non-zero digit are insignificant.", "Trailing zeros without a decimal point are not significant."],
      table_data: {
        columns: ["Instrument", "Least count"],
        rows: [
          ["mm scale", "$1\\ \\text{mm}$"],
          ["Vernier", "$0.1\\ \\text{mm}$"],
          ["Screw gauge", "$0.1\\ \\text{mm}$"],
          ["Stop watch", "$0.1\\ \\text{s}$"],
          ["Temperature thermometer", "$0.1^\\circ\\text{C}$"],
        ],
      },
      importance: 5,
      source_page: 80,
      sort_order: 1,
    }),
    card(chapterId, "permissible-error-propagation", {
      title: "Permissible Error and Propagation",
      card_type: "formula",
      body: "The handbook defines maximum permissible error and gives propagation forms for sums and products/powers.",
      formulas: [
        { latex: "\\Delta f_{max}=\\max(\\pm\\Delta X\\pm\\Delta Y),\\quad f(x,y)=x+y" },
        { latex: "\\left(\\frac{\\Delta f}{f}\\right)_{max}=\\max\\left(\\pm a\\frac{\\Delta x}{x}\\pm b\\frac{\\Delta y}{y}\\pm c\\frac{\\Delta z}{z}\\right)" },
      ],
      variables: [],
      conditions: ["Maximum permissible error is least count; if least count is not given, use place value of the last number.", "The product/power rule is for $f(x,y,z)=\\text{constant}\\ x^ay^bz^c$."],
      importance: 5,
      source_page: 81,
      sort_order: 2,
    }),
    card(chapterId, "averaging-errors", {
      title: "Errors in Averaging",
      card_type: "formula",
      body: "Absolute, mean absolute, relative, and percentage error are listed together in the source.",
      formulas: [
        { latex: "\\Delta a_n=|a_{mean}-a_n|" },
        { latex: "\\Delta a_{mean}=\\frac{\\sum_{i=1}^{n}|\\Delta a_i|}{n}" },
        { latex: "\\text{Relative error}=\\frac{\\Delta a_{mean}}{a_{mean}}" },
        { latex: "\\text{Percentage error}=\\frac{\\Delta a_{mean}}{a_{mean}}\\times100" },
      ],
      variables: [],
      conditions: [],
      importance: 5,
      source_page: 81,
      sort_order: 3,
    }),
    card(chapterId, "screw-gauge-vernier", {
      title: "Screw Gauge and Vernier Calipers",
      card_type: "formula",
      body: "The experiments section gives reading formulae and least-count formulae for screw gauge and vernier calipers.",
      formulas: [
        { label: "Screw gauge reading", latex: "\\text{thickness}=\\text{main scale reading}+\\text{circular scale reading}\\times\\text{least count}" },
        { latex: "\\text{least count}=\\frac{\\text{pitch}}{\\text{number of circular scale divisions}}" },
        { label: "Vernier reading", latex: "\\text{thickness}=\\text{main scale reading}+\\text{vernier scale reading}\\times\\text{least count}" },
        { latex: "\\text{least count}=1\\ \\text{MSD}-1\\ \\text{VSD}" },
      ],
      variables: [],
      conditions: [],
      importance: 5,
      source_page: 81,
      sort_order: 4,
    }),
  ];
}

function communicationCards(chapterId) {
  return [
    card(chapterId, "tower-horizon-distance", {
      title: "Tower Horizon Distance",
      card_type: "mixed",
      body: "The source gives transmission distance from a tower of height $h$ and maximum distance with receiver height.",
      formulas: [
        { latex: "d_T=\\sqrt{2Rh_T}" },
        { latex: "d_M=\\sqrt{2Rh_T}+\\sqrt{2Rh_R}" },
      ],
      variables: [],
      conditions: [],
      diagram_data: { type: "communication-horizon" },
      importance: 5,
      source_page: 82,
      sort_order: 1,
    }),
    card(chapterId, "am-signal-index-sidebands", {
      title: "AM Signal, Index and Sidebands",
      card_type: "mixed",
      body: "The amplitude modulation section gives the modulated signal, modulation index, total modulation index, sidebands, and bandwidth.",
      formulas: [
        { latex: "c_m(t)=A_c\\sin\\omega_ct+\\frac{\\mu A_c}{2}\\cos(\\omega_c-\\omega_m)t-\\frac{\\mu A_c}{2}\\cos(\\omega_c+\\omega_m)t" },
        { latex: "m_a=\\frac{\\text{change in amplitude of carrier wave}}{\\text{amplitude of original carrier wave}}=\\frac{kA_m}{A_c}" },
        { latex: "k=1\\Rightarrow m_a=\\frac{A_m}{A_c}=\\frac{A_{max}-A_{min}}{A_{max}+A_{min}}" },
        { latex: "m_t=\\sqrt{m_1^2+m_2^2+m_3^2+\\cdots}" },
        { latex: "f_c+f_m=\\text{USB},\\quad f_c-f_m=\\text{LSB}" },
        { latex: "\\text{Bandwidth}=2f_m" },
      ],
      variables: [],
      conditions: [],
      diagram_data: { type: "am-fm-signal" },
      importance: 5,
      source_page: 82,
      sort_order: 2,
    }),
    card(chapterId, "am-power", {
      title: "AM Power Relations",
      card_type: "formula",
      body: "The source lists carrier, sideband, total AM power, power ratios, maximum undistorted modulation, and current relation.",
      formulas: [
        { latex: "P=\\frac{V_{rms}^2}{R}" },
        { latex: "P_c=\\frac{A_c^2}{2R}" },
        { latex: "P_{sb}=\\frac{m_a^2A_c^2}{4R}" },
        { latex: "P_{Total}=P_c+P_{sb}=\\frac{A_c^2}{2R}\\left(1+\\frac{m_a^2}{2}\\right)" },
        { latex: "\\frac{P_t}{P_c}=1+\\frac{m_a^2}{2}" },
        { latex: "\\frac{P_{sb}}{P_t}=\\frac{m_a^2/2}{1+m_a^2/2}" },
        { latex: "m_a=1\\Rightarrow P_t=1.5P_c=3P_{sb}" },
        { latex: "\\frac{I_t}{I_c}=\\sqrt{1+\\frac{m_a^2}{2}}" },
      ],
      variables: [vars.P],
      conditions: ["Maximum AM power without distortion occurs when $m_a=1$."],
      importance: 5,
      source_page: 83,
      sort_order: 3,
    }),
    card(chapterId, "frequency-modulation", {
      title: "Frequency Modulation",
      card_type: "formula",
      body: "The FM section lists frequency deviation, carrier swing, modulation index, sideband pattern, deviation ratio, and percent modulation.",
      formulas: [
        { latex: "\\delta=f_{max}-f_c=f_c-f_{min}=\\frac{k_fE_m}{2\\pi}" },
        { latex: "CS=2\\Delta f" },
        { latex: "m_f=\\frac{\\delta}{f_m}=\\frac{f_{max}-f_c}{f_m}=\\frac{f_c-f_{min}}{f_m}=\\frac{k_fE_m}{f_m}" },
        { latex: "f_c\\pm f_m,\\ f_c\\pm2f_m,\\ f_c\\pm3f_m,\\ldots" },
        { latex: "\\text{Deviation ratio}=\\frac{(\\Delta f)_{max}}{(f_m)_{max}}" },
        { latex: "m=\\frac{(\\Delta f)_{actual}}{(\\Delta f)_{max}}" },
      ],
      variables: [],
      conditions: ["The source states FM sideband modulated signal consists of an infinite number of sidebands."],
      importance: 5,
      source_page: 83,
      sort_order: 4,
    }),
  ];
}

function semiconductorCards(chapterId) {
  return [
    card(chapterId, "conductivity-resistivity-ranges", {
      title: "Conductivity and Resistivity Ranges",
      card_type: "table",
      body: "The source opens Semiconductor with ranges for metals, semiconductors, and insulators.",
      formulas: [],
      variables: [vars.rho, vars.sigma],
      conditions: [],
      table_data: {
        columns: ["Material", "Resistivity", "Conductivity"],
        rows: [
          ["Metals", "$10^{-2}$-$10^{-6}$", "$10^2$-$10^8$"],
          ["Semiconductors", "$10^{-5}$-$10^{-6}$", "$10^5$-$10^{-6}$"],
          ["Insulators", "$10^{11}$-$10^{19}$", "$10^{-11}$-$10^{-19}$"],
        ],
      },
      importance: 4,
      source_page: 84,
      sort_order: 1,
    }),
    card(chapterId, "carrier-concentration-current", {
      title: "Carrier Concentration and Current",
      card_type: "formula",
      body: "The handbook lists intrinsic and doped semiconductor carrier relations plus current and conductivity.",
      formulas: [
        { latex: "n_n=n_e\\quad\\text{intrinsic semiconductor}" },
        { latex: "i=i_e+i_h" },
        { latex: "n_en_h=n_i^2" },
        { latex: "n=AT^{3/2}e^{-E_g/2kT}" },
        { latex: "\\sigma=e(n_e\\mu_e+n_h\\mu_h)" },
      ],
      variables: [vars.sigma],
      conditions: ["The source lists p-type and n-type majority-carrier statements; exact extracted symbols are noisy, so they are not expanded beyond source-safe carrier dominance."],
      importance: 5,
      source_page: 84,
      sort_order: 2,
    }),
    card(chapterId, "pn-junction-dynamic-resistance", {
      title: "PN Junction Dynamic Resistance",
      card_type: "formula",
      body: "For a forward-biased P-N junction, the source gives dynamic resistance as a voltage-current ratio.",
      formulas: [{ latex: "r_d=\\frac{\\Delta V}{\\Delta I}" }],
      variables: [],
      conditions: ["Forward biasing."],
      importance: 4,
      source_page: 84,
      sort_order: 3,
    }),
    card(chapterId, "cb-amplifier", {
      title: "CB Amplifier",
      card_type: "mixed",
      body: "The common-base amplifier section lists current gain, voltage gain, power gain, phase, and application.",
      formulas: [
        { latex: "\\alpha_{ac}=\\frac{\\Delta i_c}{\\Delta i_e}" },
        { latex: "\\alpha_{dc}=\\frac{i_c}{i_e}" },
        { latex: "A_V=\\frac{\\Delta V_o}{\\Delta V_i}" },
        { latex: "A_V=\\alpha_{ac}\\times\\text{resistance gain}" },
        { latex: "\\text{Power gain}=\\alpha_{ac}^2\\times\\text{resistance gain}" },
      ],
      variables: [],
      conditions: ["The source gives $\\alpha_{dc}$ between 0.95 and 0.99.", "Output and input are in the same phase.", "Application: high frequency."],
      diagram_data: { type: "transistor-amplifier" },
      importance: 5,
      source_page: 84,
      sort_order: 4,
    }),
    card(chapterId, "ce-amplifier", {
      title: "CE Amplifier",
      card_type: "formula",
      body: "The common-emitter amplifier section lists current gain, voltage gain, power gain, and transconductance.",
      formulas: [
        { latex: "\\beta_{ac}=\\left(\\frac{\\Delta i_c}{\\Delta i_b}\\right)_{V_{CE}=\\text{constant}}" },
        { latex: "\\beta_{dc}=\\frac{i_c}{i_b}" },
        { latex: "A_V=\\frac{\\Delta V_o}{\\Delta V_i}=\\beta_{ac}\\times\\text{resistance gain}" },
        { latex: "\\text{Power gain}=\\beta_{ac}^2\\times\\text{resistance gain}" },
        { latex: "g_m=\\frac{\\Delta i_c}{\\Delta V_{EB}}" },
        { latex: "g_m=\\frac{A_V}{R_L}" },
      ],
      variables: [],
      conditions: ["$R_L$ is load resistance in the source."],
      importance: 5,
      source_page: 85,
      sort_order: 5,
    }),
    card(chapterId, "alpha-beta-relation", {
      title: "Relation Between Alpha and Beta",
      card_type: "formula",
      body: "The source ends the transistor section with the relation between current gains alpha and beta.",
      formulas: [
        { latex: "\\beta=\\frac{\\alpha}{1-\\alpha}" },
        { latex: "\\alpha=\\frac{\\beta}{1+\\beta}" },
      ],
      variables: [],
      conditions: [],
      importance: 5,
      source_page: 85,
      sort_order: 6,
    }),
  ];
}

const CARD_BUILDERS = {
  gravitation: gravitationCards,
  "fluid-mechanics-properties-matter": fluidCards,
  "sound-waves": soundCards,
  "electromagnetic-waves": emWaveCards,
  "error-and-measurement": errorCards,
  "principle-of-communication": communicationCards,
  semiconductor: semiconductorCards,
};

export function getBatch6Chapters(track) {
  return BATCH_6_CHAPTER_DEFINITIONS.map((item) => ({
    id: chapter(track, item.slug),
    subject_id: `${track}-physics`,
    title: item.title,
    slug: item.slug,
    sort_order: item.sort_order,
  }));
}

export function getBatch6Cards(track) {
  return BATCH_6_CHAPTER_DEFINITIONS.flatMap((item) => CARD_BUILDERS[item.slug](chapter(track, item.slug)));
}
