export const BIOLOGY_BATCH_7_CHAPTER_DEFINITIONS = [
  { title: "Reproduction in Organisms", slug: "reproduction-in-organisms", sort_order: 21, source_page: 90 },
  { title: "Sexual Reproduction in Flowering Plants", slug: "sexual-reproduction-in-flowering-plants", sort_order: 22, source_page: 93 },
  { title: "Human Reproduction", slug: "human-reproduction", sort_order: 23, source_page: 99 },
  { title: "Reproductive Health", slug: "reproductive-health", sort_order: 24, source_page: 104 },
];

const chapter = (slug) => `neet-biology-${slug}`;

function table(columns, rows) {
  return { columns, rows };
}

function recall(question, answer, key_points = [], examples = [], neet_traps = []) {
  return { recall_question: question, reveal_answer: answer, key_points, examples, neet_traps };
}

function card(chapterId, slug, payload) {
  return {
    id: `${chapterId}-${slug}`,
    chapter_id: chapterId,
    formulas: [],
    variables: [],
    conditions: [],
    table_data: null,
    diagram_data: null,
    diagram_svg: null,
    is_active: true,
    ...payload,
  };
}

function reproductionOrganismsCards(chapterId) {
  return [
    card(chapterId, "lifespan-and-reproduction", {
      title: "Lifespan and Reproduction",
      card_type: "concept",
      body: "Lifespan is the period from birth to natural death. Reproduction produces young ones similar to the organism.",
      table_data: table(["Cue", "Source-backed recall"], [
        ["Lifespan", "Period from birth to natural death"],
        ["Reproduction", "Production of young ones similar to itself"],
        ["Unicellular organisms", "No natural death; the source notes they are an exception to individual immortality"],
      ]),
      recall_data: recall("What is lifespan?", "The period from birth to natural death."),
      importance: 5,
      source_page: 90,
      sort_order: 1,
    }),
    card(chapterId, "lifespan-examples", {
      title: "Lifespan Examples",
      card_type: "fact",
      body: "The source gives exact lifespan examples for plants and animals.",
      table_data: table(["Organism", "Lifespan"], [
        ["Rose", "5-7 years"],
        ["Rice plant", "3-7 months"],
        ["Banyan tree", "400+ yrs"],
        ["Banana tree", "2-3 yrs"],
        ["Dog", "22 yrs"],
        ["Butterfly", "1-2 weeks"],
        ["Fruit fly", "2 weeks"],
        ["Parrot", "140 yrs"],
        ["Crocodile", "60 yrs"],
        ["Horse", "40-50 yrs"],
        ["Tortoise", "100-150 yrs"],
        ["Elephant", "50-70 yrs"],
      ]),
      recall_data: recall("Which listed organism has a 400+ year lifespan?", "Banyan tree."),
      importance: 4,
      source_page: 90,
      sort_order: 2,
    }),
    card(chapterId, "asexual-reproduction", {
      title: "Asexual Reproduction",
      card_type: "concept",
      body: "Asexual reproduction is production of offspring by a single parent.",
      table_data: table(["Feature", "Source-backed detail"], [
        ["Parent", "Single parent"],
        ["Typical organisms", "Unicellular organisms, simple plants and simple animals"],
        ["Offspring", "Identical to one another and to the parent"],
        ["Clone", "Morphologically and genetically similar individuals"],
      ]),
      recall_data: recall("What is a clone in this chapter?", "Morphologically and genetically similar individuals."),
      importance: 5,
      source_page: 90,
      sort_order: 3,
    }),
    card(chapterId, "binary-vs-multiple-fission", {
      title: "Binary vs Multiple Fission",
      card_type: "comparison",
      body: "Fission is division of the parent cell into two or more individuals.",
      table_data: table(["Type", "Recall", "Examples"], [
        ["Binary fission", "Parent divides into two individuals", "Amoeba, Paramecium"],
        ["Multiple fission", "Parent divides into many individuals", "Plasmodium, Amoeba"],
      ]),
      recall_data: recall("Which fission type forms many individuals from one parent?", "Multiple fission."),
      importance: 5,
      source_page: 90,
      sort_order: 4,
    }),
    card(chapterId, "amoeba-encystation", {
      title: "Amoeba Encystation and Sporulation",
      card_type: "sequence",
      body: "Amoeba forms a cyst in unfavourable conditions and releases pseudopodiospores under favourable conditions.",
      table_data: table(["Step", "Source-backed event"], [
        ["1", "Amoeba withdraws pseudopodia under unfavourable conditions"],
        ["2", "It secretes a three-layered hard covering or cyst"],
        ["3", "On return of favourable conditions, multiple fission occurs inside the cyst"],
        ["4", "Many minute amoebae or pseudopodiospores are formed"],
        ["5", "Cyst wall bursts and spores are liberated"],
      ]),
      recall_data: recall("What are formed inside the Amoeba cyst during favourable conditions?", "Many minute amoebae or pseudopodiospores."),
      importance: 4,
      source_page: 90,
      sort_order: 5,
    }),
    card(chapterId, "budding-fragmentation", {
      title: "Budding and Fragmentation",
      card_type: "comparison",
      body: "Budding forms a new individual from a bud; fragmentation forms adults from body fragments.",
      table_data: table(["Method", "Source-backed recall", "Examples"], [
        ["Budding", "Bud appears and grows on the parent, then detaches after maturation", "Hydra, Sponge, Yeast"],
        ["Fragmentation", "Parent body breaks into fragments, each fragment grows into an adult", "Hydra"],
      ]),
      recall_data: recall("Which asexual method uses a bud that detaches after maturation?", "Budding."),
      importance: 4,
      source_page: 90,
      sort_order: 6,
    }),
    card(chapterId, "vegetative-propagation-examples", {
      title: "Vegetative Propagules",
      card_type: "examples",
      body: "Vegetative propagation forms offspring from vegetative propagules in plants.",
      table_data: table(["Propagule", "Exact source example"], [
        ["Buds or eyes", "Potato tuber"],
        ["Rhizome", "Banana and ginger"],
        ["Adventitious buds", "Bryophyllum leaf margins"],
        ["Bulbil", "Agave"],
        ["Offset", "Water hyacinth"],
        ["Other listed propagules", "Runner, sucker, tuber, bulb etc."],
      ]),
      recall_data: recall("Which plant has adventitious buds on leaf margins?", "Bryophyllum.", [], ["Potato tuber, banana, ginger, Agave, water hyacinth"]),
      importance: 5,
      source_page: 90,
      sort_order: 7,
    }),
    card(chapterId, "asexual-structures", {
      title: "Asexual Reproductive Structures",
      card_type: "examples",
      body: "The source names specialized asexual structures across groups.",
      table_data: table(["Structure", "Source-backed example/detail"], [
        ["Zoospores", "Microscopic motile structures in some algae and protists"],
        ["Conidia", "Penicillium"],
        ["Gemmules", "Sponge"],
        ["Asexual reproduction", "Common in algae and fungi; during adverse conditions they shift to sexual reproduction"],
      ]),
      recall_data: recall("Which asexual structure is listed for Penicillium?", "Conidia."),
      importance: 4,
      source_page: 91,
      sort_order: 8,
    }),
    card(chapterId, "asexual-vs-sexual", {
      title: "Asexual vs Sexual Reproduction",
      card_type: "comparison",
      body: "Sexual reproduction is elaborate, complex and slow compared with asexual reproduction.",
      table_data: table(["Feature", "Asexual reproduction", "Sexual reproduction"], [
        ["Parent/gametes", "Single parent; no male and female gamete fusion", "Male and female gametes from same or different individuals"],
        ["Offspring", "Identical to parent and each other", "Not identical to parents or among themselves"],
        ["Speed/complexity", "Simple and common in simple organisms", "Elaborate, complex and slow"],
      ]),
      recall_data: recall("Which reproduction type produces non-identical offspring?", "Sexual reproduction."),
      importance: 5,
      source_page: 91,
      sort_order: 9,
    }),
    card(chapterId, "life-phases", {
      title: "Juvenile, Reproductive and Senescent Phases",
      card_type: "classification",
      body: "Organisms pass through phase changes before, during and after reproductive maturity.",
      table_data: table(["Phase", "Source-backed recall"], [
        ["Juvenile phase", "Period of growth before reproductive maturity"],
        ["Vegetative phase", "Juvenile phase in plants"],
        ["Reproductive phase", "Flowering indicates beginning of reproductive phase in higher plants"],
        ["Senescence", "End of reproductive phase with body changes such as slowing metabolism, ultimately leading to death"],
      ]),
      recall_data: recall("What is the juvenile phase called in plants?", "Vegetative phase."),
      importance: 5,
      source_page: 91,
      sort_order: 10,
    }),
    card(chapterId, "unusual-flowering-and-breeders", {
      title: "Unusual Flowering and Breeder Types",
      card_type: "fact",
      body: "The source highlights unusual flowering periodicity and breeding patterns.",
      table_data: table(["Cue", "Source-backed detail"], [
        ["Bamboo species", "Flower only once in their lifetime after 50-100 years, produce many fruits and die"],
        ["Strobilanthus kunthiana", "Flowers once in 12 years"],
        ["Seasonal breeders", "Reproductive cycles only during favourable seasons"],
        ["Continuous breeders", "Reproductively active throughout reproductive phase"],
      ]),
      recall_data: recall("Which listed plant flowers once in 12 years?", "Strobilanthus kunthiana."),
      importance: 5,
      source_page: 91,
      sort_order: 11,
    }),
    card(chapterId, "oestrus-vs-menstrual", {
      title: "Oestrus vs Menstrual Cycle",
      card_type: "comparison",
      body: "Placental mammals show cyclical changes during the reproductive phase.",
      table_data: table(["Cycle", "Source organisms"], [
        ["Oestrus cycle", "Non-primate mammals such as cows, sheep, rat, deer, dog, tiger etc."],
        ["Menstrual cycle", "Primates such as monkeys, apes and humans"],
      ]),
      recall_data: recall("Which cycle occurs in primates?", "Menstrual cycle."),
      importance: 4,
      source_page: 91,
      sort_order: 12,
    }),
    card(chapterId, "sexual-reproduction-events", {
      title: "Sexual Reproduction Events",
      card_type: "sequence",
      body: "Sexual reproduction is divided into pre-fertilisation, fertilisation and post-fertilisation events.",
      diagram_data: { type: "bio-reproduction-events" },
      table_data: table(["Event", "Source-backed recall"], [
        ["Pre-fertilisation", "Events before gamete fusion; includes gametogenesis and gamete transfer"],
        ["Fertilisation or syngamy", "Fusion of gametes to form a diploid zygote"],
        ["Post-fertilisation", "Events after zygote formation, including embryogenesis"],
      ]),
      recall_data: recall("Name the two pre-fertilisation events.", "Gametogenesis and gamete transfer."),
      importance: 5,
      source_page: 91,
      sort_order: 13,
    }),
    card(chapterId, "gametes-and-sexuality", {
      title: "Gametes and Sexuality",
      card_type: "classification",
      body: "Gametes may be similar or distinct, and organisms may be bisexual or unisexual.",
      table_data: table(["Term", "Source-backed recall", "Examples"], [
        ["Homogametes or isogametes", "Similar gametes that cannot be categorized as male or female", "Some algae such as Cladophora"],
        ["Heterogametes", "Distinct male and female gametes", "Fucus, humans"],
        ["Bisexual plant", "Male and female reproductive structures in one individual", "Hibiscus, Pisum"],
        ["Monoecious plant", "Male and female flowers on same plant", "Cucurbits, coconuts, Chara"],
        ["Dioecious plant", "Male and female flowers on different plants", "Papaya, date palm, Marchantia"],
      ]),
      recall_data: recall("What are similar gametes called?", "Homogametes or isogametes."),
      importance: 5,
      source_page: 91,
      sort_order: 14,
    }),
    card(chapterId, "chromosome-numbers", {
      title: "Diploid and Haploid Numbers",
      card_type: "fact",
      body: "The source lists chromosome numbers in meiocytes and gametes.",
      table_data: table(["Organism", "Meiocyte 2n", "Gamete n"], [
        ["Human being", "46", "23"],
        ["Housefly", "12", "6"],
        ["Rat", "42", "21"],
        ["Dog", "78", "39"],
        ["Cat", "38", "19"],
        ["Fruit fly", "8", "4"],
        ["Ophioglossum", "1260", "630"],
        ["Apple", "34", "17"],
        ["Rice", "24", "12"],
        ["Maize", "20", "10"],
        ["Potato", "48", "24"],
        ["Onion", "16", "8"],
      ]),
      recall_data: recall("What is the gamete chromosome number of Ophioglossum in the source?", "630."),
      importance: 5,
      source_page: 92,
      sort_order: 15,
    }),
    card(chapterId, "gamete-transfer", {
      title: "Gamete Transfer",
      card_type: "process",
      body: "Male gametes generally need a medium to move towards the female gamete.",
      table_data: table(["Group/case", "Source-backed transfer detail"], [
        ["Simple plants", "Water is the medium; many male gametes are produced"],
        ["Seed plants", "Pollen grains carry male gametes; ovule carries egg"],
        ["Peas", "Anther and stigma are close, enabling easy pollen transfer"],
        ["Cross-pollinating plants", "Pollination transfers pollen to stigma; pollen tube carries male gametes to ovule"],
      ]),
      recall_data: recall("What carries male gametes in seed plants?", "Pollen grains."),
      importance: 5,
      source_page: 92,
      sort_order: 16,
    }),
    card(chapterId, "external-vs-internal-fertilisation", {
      title: "External vs Internal Fertilisation",
      card_type: "comparison",
      body: "Fertilisation may occur outside or inside the organism.",
      diagram_data: { type: "bio-fertilisation-types" },
      table_data: table(["Feature", "External fertilisation", "Internal fertilisation"], [
        ["Site", "Outside the body in external medium, usually water", "Inside the body of the organism"],
        ["Examples", "Many algae, bony fishes and amphibians", "Terrestrial organisms, reptiles, birds, mammals, bryophytes, pteridophytes, gymnosperms, angiosperms"],
        ["Gamete output", "Large number of gametes released into surrounding medium", "Many sperms are produced but the number of eggs is very low"],
        ["Protection", "Offspring are vulnerable to predators", "Better protection in the organism"],
      ]),
      recall_data: recall("Which fertilisation type usually occurs in water outside the body?", "External fertilisation."),
      importance: 5,
      source_page: 92,
      sort_order: 17,
    }),
    card(chapterId, "parthenogenesis", {
      title: "Parthenogenesis",
      card_type: "fact",
      body: "The source notes that female gametes may develop into new organisms without fertilisation.",
      table_data: table(["Term", "Examples listed"], [
        ["Parthenogenesis", "Rotifers, honeybees, some lizards and birds such as turkey"],
      ]),
      recall_data: recall("Name one source example of parthenogenesis.", "Honeybee.", ["Other listed examples include rotifers, some lizards and turkey."]),
      importance: 4,
      source_page: 92,
      sort_order: 18,
    }),
    card(chapterId, "zygote-and-embryogenesis", {
      title: "Zygote and Embryogenesis",
      card_type: "process",
      body: "The zygote is the vital link between organisms of one generation and the next.",
      table_data: table(["Cue", "Source-backed recall"], [
        ["Zygote", "Diploid cell formed by syngamy"],
        ["Haplontic life cycle", "Zygote divides by meiosis to form haploid spores"],
        ["Embryogenesis", "Development of embryo from zygote"],
        ["Cell division", "Increases number of cells"],
        ["Cell differentiation", "Forms specialized tissues and organs"],
      ]),
      recall_data: recall("What two processes occur during embryogenesis?", "Cell division and cell differentiation."),
      importance: 5,
      source_page: 92,
      sort_order: 19,
    }),
    card(chapterId, "oviparous-vs-viviparous", {
      title: "Oviparous vs Viviparous",
      card_type: "comparison",
      body: "Embryonic development after fertilisation differs in oviparous and viviparous animals.",
      table_data: table(["Feature", "Oviparous", "Viviparous"], [
        ["Development", "Fertilized or unfertilized eggs are laid", "Zygote develops into a young one inside the female body"],
        ["Examples/detail", "Reptiles and birds lay fertilized eggs with a hard calcareous shell", "Most mammals"],
        ["Survival", "Eggs hatch after incubation", "Young ones have better care and protection, so chances of survival are greater"],
      ]),
      recall_data: recall("Which condition gives better care and protection in the source?", "Viviparous condition."),
      importance: 5,
      source_page: 92,
      sort_order: 20,
    }),
  ];
}

function floweringPlantCards(chapterId) {
  return [
    card(chapterId, "flower-reproductive-parts", {
      title: "Flower Reproductive Parts",
      card_type: "classification",
      body: "Flowers are the sites of sexual reproduction in angiosperms.",
      table_data: table(["Part", "Source-backed recall"], [
        ["Androecium", "Whorl of stamens; male reproductive part"],
        ["Gynoecium", "Female reproductive part; one or more pistils"],
        ["Stamen", "Filament plus anther"],
        ["Pistil", "Stigma, style and ovary"],
      ]),
      recall_data: recall("What are the two main reproductive parts of a flower?", "Androecium and gynoecium."),
      importance: 5,
      source_page: 93,
      sort_order: 1,
    }),
    card(chapterId, "anther-structure", {
      title: "Anther Structure",
      card_type: "diagram",
      body: "A typical angiosperm anther is bilobed, dithecous and tetragonal.",
      diagram_data: { type: "bio-anther-microsporangium" },
      table_data: table(["Cue", "Source-backed recall"], [
        ["Anther", "Terminal, bilobed structure"],
        ["Dithecous", "Each anther lobe has two thecae"],
        ["Microsporangia", "Four microsporangia, two in each lobe"],
        ["Pollen sacs", "Microsporangia develop into pollen sacs packed with pollen grains"],
      ]),
      recall_data: recall("How many microsporangia are present in a typical anther?", "Four."),
      importance: 5,
      source_page: 93,
      sort_order: 2,
    }),
    card(chapterId, "microsporangium-wall", {
      title: "Microsporangium Wall Layers",
      card_type: "classification",
      body: "The microsporangium is surrounded by four wall layers.",
      table_data: table(["Layer", "Source-backed role"], [
        ["Epidermis", "Protection"],
        ["Endothecium", "Protection and dehiscence"],
        ["Middle layers", "Protection and dehiscence"],
        ["Tapetum", "Nourishes developing pollen grains; dense cytoplasm and generally more than one nucleus"],
      ]),
      recall_data: recall("Which anther wall layer nourishes developing pollen grains?", "Tapetum."),
      importance: 5,
      source_page: 93,
      sort_order: 3,
    }),
    card(chapterId, "microsporogenesis", {
      title: "Microsporogenesis",
      card_type: "sequence",
      body: "Microsporogenesis forms microspores from pollen mother cells by meiosis.",
      table_data: table(["Step", "Source-backed event"], [
        ["1", "Sporogenous tissue occupies centre of young anther"],
        ["2", "Each sporogenous cell becomes a microspore mother cell or pollen mother cell"],
        ["3", "PMC undergoes meiosis"],
        ["4", "Microspore tetrads are formed"],
        ["5", "Microspores dissociate and develop into pollen grains"],
      ]),
      recall_data: recall("What is microsporogenesis?", "Formation of microspores from pollen mother cell by meiosis."),
      importance: 5,
      source_page: 93,
      sort_order: 4,
    }),
    card(chapterId, "pollen-grain", {
      title: "Pollen Grain",
      card_type: "diagram",
      body: "Pollen grain is the male gametophyte.",
      diagram_data: { type: "bio-pollen-grain" },
      table_data: table(["Part", "Source-backed recall"], [
        ["Size", "Generally spherical, about 25-50 micrometre in diameter"],
        ["Exine", "Hard outer layer made of sporopollenin"],
        ["Germ pore", "Aperture where sporopollenin is absent"],
        ["Intine", "Thin continuous layer made of cellulose and pectin"],
        ["Vegetative cell", "Bigger cell with abundant food reserve and large irregular nucleus"],
        ["Generative cell", "Small spindle-shaped cell floating in vegetative cytoplasm"],
      ]),
      recall_data: recall("Which pollen wall layer contains sporopollenin?", "Exine.", [], [], ["Germ pores are apertures where sporopollenin is absent."]),
      importance: 5,
      source_page: 94,
      sort_order: 5,
    }),
    card(chapterId, "two-celled-vs-three-celled-pollen", {
      title: "Two-Celled vs Three-Celled Pollen",
      card_type: "neet_trap",
      body: "Pollen shedding stage varies among angiosperms.",
      table_data: table(["Stage", "Source-backed detail"], [
        ["2-celled pollen", "More than 60% of angiosperms shed pollen grains at this stage"],
        ["3-celled pollen", "In remaining species, generative cell divides mitotically to form two male gametes before pollen grains are shed"],
      ]),
      recall_data: recall("At which stage are pollen grains shed in more than 60% of angiosperms?", "2-celled stage."),
      importance: 5,
      source_page: 94,
      sort_order: 6,
    }),
    card(chapterId, "pollen-viability-and-use", {
      title: "Pollen Viability and Uses",
      card_type: "fact",
      body: "Pollen viability depends on temperature and humidity and varies across plants.",
      table_data: table(["Cue", "Source-backed detail"], [
        ["Cereals such as rice and wheat", "Pollen viability is 30 minutes"],
        ["Some Leguminoseae, Rosaceae and Solanaceae", "Pollen viability is for months"],
        ["Liquid nitrogen", "Pollen grains can be stored for years in liquid nitrogen at -196°C"],
        ["Parthenium or carrot grass", "Pollen can cause chronic respiratory disorders such as asthma and bronchitis"],
      ]),
      recall_data: recall("How long is pollen viability in cereals such as rice and wheat?", "30 minutes."),
      importance: 5,
      source_page: 94,
      sort_order: 7,
    }),
    card(chapterId, "gynoecium-and-pistil", {
      title: "Gynoecium and Pistil",
      card_type: "classification",
      body: "A pistil has stigma, style and ovary.",
      table_data: table(["Structure", "Source-backed recall"], [
        ["Monocarpellary", "Gynoecium with one pistil"],
        ["Multicarpellary syncarpous", "More than one pistil fused"],
        ["Multicarpellary apocarpous", "More than one pistil free"],
        ["Stigma", "Landing platform for pollen grains"],
        ["Style", "Slender part below stigma"],
        ["Ovary", "Basal bulged part with ovarian cavity or locule"],
        ["Placenta", "Tissue inside ovary where ovules arise"],
      ]),
      recall_data: recall("What is the landing platform for pollen grains?", "Stigma."),
      importance: 5,
      source_page: 94,
      sort_order: 8,
    }),
    card(chapterId, "ovule-structure", {
      title: "Ovule Structure",
      card_type: "diagram",
      body: "The ovule is attached to the placenta by a funicle.",
      diagram_data: { type: "bio-ovule" },
      table_data: table(["Part", "Source-backed recall"], [
        ["Funicle", "Stalk by which ovule is attached to placenta"],
        ["Hilum", "Junction between ovule and funicle"],
        ["Integuments", "Protective layers that encircle ovule except at micropyle"],
        ["Micropyle", "Opening at the ovule tip"],
        ["Chalaza", "Basal part opposite micropyle"],
        ["Nucellus", "Mass of cells with abundant reserve food"],
        ["Embryo sac", "Female gametophyte located in nucellus"],
      ]),
      recall_data: recall("Which ovule part lies opposite the micropyle?", "Chalaza."),
      importance: 5,
      source_page: 94,
      sort_order: 9,
    }),
    card(chapterId, "megasporogenesis", {
      title: "Megasporogenesis",
      card_type: "sequence",
      body: "Megasporogenesis forms megaspores from the megaspore mother cell.",
      table_data: table(["Step", "Source-backed event"], [
        ["1", "Single megaspore mother cell differentiates in the micropylar region of nucellus"],
        ["2", "MMC undergoes meiosis"],
        ["3", "Four megaspores are formed"],
        ["4", "Only one megaspore is functional in the majority of flowering plants"],
        ["5", "Other three megaspores degenerate"],
      ]),
      recall_data: recall("In most flowering plants, how many megaspores remain functional?", "One."),
      importance: 5,
      source_page: 94,
      sort_order: 10,
    }),
    card(chapterId, "embryo-sac-formation", {
      title: "Embryo Sac Formation",
      card_type: "sequence",
      body: "The mature embryo sac is 8-nucleate and 7-celled.",
      diagram_data: { type: "bio-embryo-sac" },
      table_data: table(["Stage/part", "Source-backed recall"], [
        ["Functional megaspore", "Develops into female gametophyte by monosporic development"],
        ["Nuclear divisions", "2-nucleate, then 4-nucleate, then 8-nucleate stages"],
        ["Cellular organization", "6 nuclei enclosed by cell walls, 2 polar nuclei in central cell"],
        ["Egg apparatus", "Two synergids and one egg at micropylar end"],
        ["Filiform apparatus", "Present at micropylar tip of synergids; guides pollen tubes"],
        ["Antipodals", "Three cells at chalazal end"],
      ]),
      recall_data: recall("What is the mature embryo sac organization?", "8-nucleate and 7-celled."),
      importance: 5,
      source_page: 94,
      sort_order: 11,
    }),
    card(chapterId, "autogamy-geitonogamy-xenogamy", {
      title: "Autogamy vs Geitonogamy vs Xenogamy",
      card_type: "comparison",
      body: "Pollination is transfer of pollen from anther to stigma.",
      table_data: table(["Type", "Source-backed definition", "Genetic note/examples"], [
        ["Autogamy", "Pollen from anther to stigma of the same flower", "Viola, Oxalis and Commelina show cleistogamous flowers"],
        ["Geitonogamy", "Pollen from anther to stigma of another flower on the same plant", "Functionally cross-pollination but genetically similar to autogamy"],
        ["Xenogamy", "Pollen from anther to stigma of a different plant", "Brings genetically different pollen"],
      ]),
      recall_data: recall("Which pollination is genetically similar to autogamy but functionally cross-pollination?", "Geitonogamy.", [], [], ["Xenogamy involves a different plant."]),
      importance: 5,
      source_page: 95,
      sort_order: 12,
    }),
    card(chapterId, "wind-water-animal-pollination", {
      title: "Pollination Agents",
      card_type: "comparison",
      body: "The source contrasts wind, water and animal pollination.",
      table_data: table(["Agent", "Source-backed adaptations/examples"], [
        ["Wind", "Enormous pollen, light non-sticky pollen, exposed stamens, large feathery stigma; common in grasses"],
        ["Water", "Rare, about 30 genera mostly monocots; Vallisneria, Hydrilla and Zostera"],
        ["Animals", "Bees, butterflies, flies, beetles, wasps, ants, moths, sunbirds, humming birds, bats, lemurs, rodents, reptiles"],
      ]),
      recall_data: recall("Which abiotic pollination is common in grasses?", "Wind pollination."),
      importance: 5,
      source_page: 95,
      sort_order: 13,
    }),
    card(chapterId, "pollination-special-cases", {
      title: "Pollination Special Cases",
      card_type: "examples",
      body: "The source names several high-yield examples and exceptions in pollination.",
      table_data: table(["Cue", "Source-backed detail"], [
        ["Cleistogamous flowers", "Do not open; produce assured seed-set even without pollinators"],
        ["Water hyacinth and water lily", "Aquatic plants whose flowers emerge above water and are pollinated by insects or wind"],
        ["Amorphophallus", "Tallest flower of about 6 feet"],
        ["Yucca and moth", "Mutualistic relationship; both cannot complete life cycles without each other"],
        ["Nectar robbers", "Animals that consume nectar without bringing pollination"],
      ]),
      recall_data: recall("Which source example has mutualism with moth?", "Yucca."),
      importance: 5,
      source_page: 95,
      sort_order: 14,
    }),
    card(chapterId, "outbreeding-devices", {
      title: "Outbreeding Devices",
      card_type: "classification",
      body: "Outbreeding devices discourage self-pollination and encourage cross-pollination.",
      table_data: table(["Device", "Source-backed recall"], [
        ["Asynchrony", "Pollen release and stigma receptivity are not synchronized"],
        ["Spatial separation", "Anther and stigma are placed in different positions"],
        ["Self-incompatibility", "Genetic mechanism preventing self-pollen germination or pollen tube growth"],
        ["Unisexuality", "Monoecious castor and maize prevent autogamy; dioecious papaya prevents autogamy and geitonogamy"],
      ]),
      recall_data: recall("Which outbreeding device prevents self pollen germination or pollen tube growth?", "Self-incompatibility."),
      importance: 5,
      source_page: 96,
      sort_order: 15,
    }),
    card(chapterId, "artificial-hybridisation", {
      title: "Artificial Hybridisation",
      card_type: "sequence",
      body: "Artificial hybridisation uses only desired pollen grains for crop improvement.",
      table_data: table(["Step", "Source-backed event"], [
        ["1", "Emasculation: remove anthers from bisexual flower bud before anther dehiscence"],
        ["2", "Bag the emasculated flower with butter paper"],
        ["3", "Dust desired pollen on receptive stigma"],
        ["4", "Rebag the flower and allow fruit development"],
        ["Unisexual flowers", "Emasculation is not needed; female flower buds are bagged before opening"],
      ]),
      recall_data: recall("What is emasculation?", "Removal of anthers from a bisexual flower bud before anther dehiscence.", [], [], ["Emasculation is not needed in unisexual flowers."]),
      importance: 5,
      source_page: 96,
      sort_order: 16,
    }),
    card(chapterId, "pollen-pistil-interaction", {
      title: "Pollen-Pistil Interaction",
      card_type: "process",
      body: "The pistil recognizes compatible and incompatible pollen by chemical components.",
      table_data: table(["Step", "Source-backed event"], [
        ["1", "Pollen lands on stigma"],
        ["2", "Pistil accepts compatible pollen and rejects incompatible pollen"],
        ["3", "Pollen germinates through germ pore"],
        ["4", "Pollen tube grows through stigma and style to ovary"],
        ["5", "Pollen tube enters ovule through micropyle and then one synergid through filiform apparatus"],
      ]),
      recall_data: recall("Which structure guides pollen tube entry into a synergid?", "Filiform apparatus."),
      importance: 5,
      source_page: 96,
      sort_order: 17,
    }),
    card(chapterId, "double-fertilisation", {
      title: "Double Fertilisation",
      card_type: "process",
      body: "Double fertilisation is unique to flowering plants.",
      diagram_data: { type: "bio-double-fertilisation" },
      table_data: table(["Fusion", "Source-backed result"], [
        ["Syngamy", "One male gamete fuses with egg nucleus to form diploid zygote"],
        ["Triple fusion", "Other male gamete fuses with two polar nuclei to form triploid primary endosperm nucleus"],
        ["Double fertilisation", "Syngamy plus triple fusion"],
        ["After triple fusion", "Central cell becomes primary endosperm cell and develops into endosperm"],
      ]),
      recall_data: recall("What two fusion events together constitute double fertilisation?", "Syngamy and triple fusion.", [], [], ["Triple fusion forms triploid PEN, not zygote."]),
      importance: 5,
      source_page: 96,
      sort_order: 18,
    }),
    card(chapterId, "endosperm", {
      title: "Endosperm",
      card_type: "classification",
      body: "Endosperm develops from the primary endosperm cell and stores reserve food for the embryo.",
      table_data: table(["Type/detail", "Source-backed recall"], [
        ["Free-nuclear endosperm", "PEN undergoes successive nuclear divisions to give free nuclei"],
        ["Cellular endosperm", "Cell wall formation follows free nuclear divisions"],
        ["Tender coconut water", "Free-nuclear endosperm"],
        ["White kernel of coconut", "Cellular endosperm"],
      ]),
      recall_data: recall("What is tender coconut water in the source?", "Free-nuclear endosperm."),
      importance: 5,
      source_page: 97,
      sort_order: 19,
    }),
    card(chapterId, "embryo-development", {
      title: "Embryo Development",
      card_type: "sequence",
      body: "Embryo develops at the micropylar end where the zygote is situated.",
      table_data: table(["Stage/part", "Source-backed recall"], [
        ["Sequence", "Zygote -> pro-embryo -> globular -> heart-shaped -> mature embryo"],
        ["Dicot embryo", "Embryonal axis and two cotyledons"],
        ["Epicotyl", "Portion above cotyledons; terminates in plumule"],
        ["Hypocotyl", "Portion below cotyledons; terminates in radicle"],
        ["Monocot embryo", "One cotyledon; grass cotyledon is scutellum"],
        ["Coleorrhiza and coleoptile", "Radicle/root cap enclosed by coleorrhiza; shoot apex and leaf primordia enclosed by coleoptile"],
      ]),
      recall_data: recall("What is the cotyledon of grasses called?", "Scutellum."),
      importance: 5,
      source_page: 97,
      sort_order: 20,
    }),
    card(chapterId, "seed-types", {
      title: "Albuminous vs Non-Albuminous Seeds",
      card_type: "comparison",
      body: "Mature seeds may or may not retain endosperm.",
      table_data: table(["Seed type", "Source-backed recall", "Examples"], [
        ["Non-albuminous or ex-albuminous", "No residual endosperm because it is completely consumed during embryo development", "Pea, groundnut, beans"],
        ["Albuminous", "Retain a part of endosperm", "Wheat, maize, barley, castor, coconut"],
        ["Perisperm", "Remnant nucellus", "Black pepper, beet etc."],
      ]),
      recall_data: recall("Which seed type retains part of the endosperm?", "Albuminous seed."),
      importance: 5,
      source_page: 97,
      sort_order: 21,
    }),
    card(chapterId, "seed-viability", {
      title: "Seed Viability",
      card_type: "fact",
      body: "Seed viability varies from months to thousands of years in source examples.",
      table_data: table(["Example", "Source-backed value"], [
        ["Mature seed moisture", "10-15% moisture by mass"],
        ["Lupinus arcticus", "Estimated 10,000 years of dormancy; germinated and flowered"],
        ["Phoenix dactylifera", "2000-year-old viable date palm seed from King Herod's palace near Dead Sea"],
      ]),
      recall_data: recall("What moisture range is stated for mature dry seeds?", "10-15% moisture by mass."),
      importance: 5,
      source_page: 97,
      sort_order: 22,
    }),
    card(chapterId, "true-false-parthenocarpic-fruits", {
      title: "True, False and Parthenocarpic Fruits",
      card_type: "classification",
      body: "Fruit develops as ovary and ovules transform after fertilisation, with source-backed exceptions.",
      table_data: table(["Fruit type", "Source-backed recall", "Examples"], [
        ["True fruit", "Fruit formed only from ovary", "Most plants"],
        ["False fruit", "Thalamus also contributes to fruit formation", "Apple, strawberry, cashew"],
        ["Parthenocarpic fruit", "Fruit formed without fertilisation", "Banana"],
      ]),
      recall_data: recall("Which listed fruit is parthenocarpic?", "Banana."),
      importance: 5,
      source_page: 98,
      sort_order: 23,
    }),
    card(chapterId, "apomixis-polyembryony", {
      title: "Apomixis and Polyembryony",
      card_type: "comparison",
      body: "Apomixis is asexual seed formation that mimics sexual reproduction.",
      table_data: table(["Term", "Source-backed recall", "Examples"], [
        ["Apomixis", "Seed formation without fertilisation", "Asteraceae and grasses"],
        ["Diploid egg route", "Diploid egg cell forms embryo without reduction division and fertilisation", "Source mechanism"],
        ["Nucellar embryo route", "Nucellar cells around embryo sac divide, protrude into embryo sac and develop into embryos", "Citrus and Mango varieties"],
        ["Polyembryony", "Occurrence of more than one embryo in a seed", "Seen when more embryos form in one ovule"],
      ]),
      recall_data: recall("What is polyembryony?", "Occurrence of more than one embryo in a seed."),
      importance: 5,
      source_page: 98,
      sort_order: 24,
    }),
  ];
}

function humanReproductionCards(chapterId) {
  return [
    card(chapterId, "male-reproductive-system", {
      title: "Male Reproductive System",
      card_type: "classification",
      body: "The male reproductive system includes paired testes, accessory ducts, accessory glands and external genitalia.",
      diagram_data: { type: "bio-male-reproductive-route" },
      table_data: table(["Part", "Source-backed recall"], [
        ["Testes", "Primary sex organs; produce sperms and testosterone"],
        ["Accessory ducts", "Rete testis, vasa efferentia, epididymis and vas deferens"],
        ["Accessory glands", "Seminal vesicles, prostate and bulbourethral glands"],
        ["Penis", "External genitalia and copulatory organ"],
      ]),
      recall_data: recall("What are the primary sex organs in males?", "Testes."),
      importance: 5,
      source_page: 99,
      sort_order: 1,
    }),
    card(chapterId, "testis-values", {
      title: "Testis Source Values",
      card_type: "fact",
      body: "The source gives several exact testis values.",
      table_data: table(["Cue", "Exact value/detail"], [
        ["Scrotal temperature", "2-2.5°C less than body temperature"],
        ["Testis length", "4-5 cm"],
        ["Testis width", "2-3 cm"],
        ["Testicular lobules", "About 250 compartments"],
        ["Seminiferous tubules per lobule", "1-3 coiled seminiferous tubules"],
      ]),
      recall_data: recall("Why are testes present in scrotum?", "Scrotum helps maintain low temperature, 2-2.5°C less than body temperature, needed for spermatogenesis."),
      importance: 5,
      source_page: 99,
      sort_order: 2,
    }),
    card(chapterId, "male-duct-route", {
      title: "Male Duct Route",
      card_type: "sequence",
      body: "Sperm pass from seminiferous tubules to the urethral meatus through accessory ducts.",
      table_data: table(["Order", "Route"], [
        ["1", "Seminiferous tubules"],
        ["2", "Rete testis"],
        ["3", "Vasa efferentia"],
        ["4", "Epididymis"],
        ["5", "Vas deferens"],
        ["6", "Ejaculatory duct"],
        ["7", "Urethra"],
        ["8", "Urethral meatus"],
      ]),
      recall_data: recall("Which duct comes after rete testis in the male route?", "Vasa efferentia."),
      importance: 5,
      source_page: 99,
      sort_order: 3,
    }),
    card(chapterId, "sertoli-vs-leydig", {
      title: "Sertoli vs Leydig Cells",
      card_type: "comparison",
      body: "Sertoli cells and Leydig cells support different parts of male reproduction.",
      table_data: table(["Cell", "Location", "Source-backed function"], [
        ["Sertoli cells", "Seminiferous tubules", "Support and nourish spermatogonia/sperms; secrete factors for spermiogenesis under FSH"],
        ["Leydig cells", "Interstitial spaces outside seminiferous tubules", "Secrete androgens under LH stimulation"],
      ]),
      recall_data: recall("Which cells secrete androgens?", "Leydig cells.", [], [], ["Sertoli cells nourish and support developing sperms."]),
      importance: 5,
      source_page: 99,
      sort_order: 4,
    }),
    card(chapterId, "accessory-glands-and-semen", {
      title: "Accessory Glands and Semen",
      card_type: "concept",
      body: "Seminal plasma plus sperms form semen.",
      table_data: table(["Cue", "Source-backed detail"], [
        ["Seminal vesicles, prostate and Cowper's glands", "Produce seminal plasma"],
        ["Seminal plasma", "Rich in fructose, calcium and enzymes"],
        ["Semen", "Seminal plasma with sperms"],
        ["Cowper's gland", "Secretes alkaline fluid and lubricates penis"],
      ]),
      recall_data: recall("What makes up semen?", "Seminal plasma along with sperms."),
      importance: 4,
      source_page: 99,
      sort_order: 5,
    }),
    card(chapterId, "female-reproductive-system", {
      title: "Female Reproductive System",
      card_type: "classification",
      body: "The female reproductive system includes ovaries, ducts, external genitalia and mammary glands.",
      table_data: table(["Part", "Source-backed recall"], [
        ["Ovaries", "Primary female sex organs; produce ova and ovarian hormones"],
        ["Oviducts", "Fallopian tubes that transport ova"],
        ["Uterus", "Womb; inverted pear-shaped organ"],
        ["Cervix and vagina", "Cervical canal and vagina form the birth canal"],
        ["Mammary glands", "Functional only in females"],
      ]),
      recall_data: recall("What are the primary female sex organs?", "Ovaries."),
      importance: 5,
      source_page: 100,
      sort_order: 6,
    }),
    card(chapterId, "oviduct-uterus-vagina", {
      title: "Oviduct, Uterus and Vagina",
      card_type: "classification",
      body: "The oviduct has infundibulum, ampulla and isthmus; the uterus has three wall layers.",
      table_data: table(["Structure", "Source-backed recall"], [
        ["Oviduct length", "10-12 cm"],
        ["Infundibulum", "Funnel-shaped part with fimbriae"],
        ["Ampulla", "Wider part of oviduct"],
        ["Isthmus", "Narrow part joining uterus"],
        ["Perimetrium", "External thin uterine membrane"],
        ["Myometrium", "Middle thick smooth muscle layer"],
        ["Endometrium", "Inner glandular and vascular layer"],
      ]),
      recall_data: recall("Which oviduct part has fimbriae?", "Infundibulum."),
      importance: 5,
      source_page: 100,
      sort_order: 7,
    }),
    card(chapterId, "external-genitalia-and-hymen", {
      title: "External Genitalia and Hymen Trap",
      card_type: "neet_trap",
      body: "The source cautions that hymen is not a reliable indicator of virginity or sexual experience.",
      table_data: table(["Structure", "Source-backed recall"], [
        ["External genitalia", "Mons pubis, labia majora, labia minora, hymen and clitoris"],
        ["Hymen", "Membrane partially covering vaginal opening"],
        ["Trap", "Hymen can be broken by cycling, horse riding, sudden fall, jolt or insertion; can persist after coitus"],
      ]),
      recall_data: recall("Is hymen a reliable indicator of virginity in the source?", "No."),
      importance: 5,
      source_page: 100,
      sort_order: 8,
    }),
    card(chapterId, "mammary-gland", {
      title: "Mammary Gland Structure",
      card_type: "fact",
      body: "Each breast contains mammary lobes made of alveoli that secrete milk.",
      table_data: table(["Cue", "Source-backed detail"], [
        ["Mammary lobes", "15-20 in each breast"],
        ["Alveoli", "Clusters of cells that secrete milk stored in lumen"],
        ["Mammary tubules", "Alveoli open into tubules"],
        ["Mammary duct", "Tubules of each lobe join to form a mammary duct"],
        ["Ampulla and lactiferous duct", "Several mammary ducts form ampulla connected to lactiferous duct"],
      ]),
      recall_data: recall("Where is milk stored in the mammary gland?", "In the lumen of alveoli."),
      importance: 4,
      source_page: 100,
      sort_order: 9,
    }),
    card(chapterId, "spermatogenesis-sequence", {
      title: "Spermatogenesis Sequence",
      card_type: "sequence",
      body: "Spermatogenesis forms spermatozoa in seminiferous tubules.",
      table_data: table(["Order", "Source-backed stage"], [
        ["1", "Spermatogonia 2n (46 chromosomes)"],
        ["2", "Primary spermatocytes (2n)"],
        ["3", "Secondary spermatocytes n (23)"],
        ["4", "Spermatids (n)"],
        ["5", "Spermatozoa (n)"],
      ]),
      recall_data: recall("How many spermatids are formed from each primary spermatocyte?", "4 spermatids."),
      importance: 5,
      source_page: 100,
      sort_order: 10,
    }),
    card(chapterId, "spermiogenesis-vs-spermiation", {
      title: "Spermiogenesis vs Spermiation",
      card_type: "comparison",
      body: "The source distinguishes sperm formation from sperm release.",
      table_data: table(["Term", "Source-backed recall"], [
        ["Spermiogenesis", "Spermatids transform into sperm"],
        ["Spermiation", "Sperm heads embedded in Sertoli cells are released into lumen of seminiferous tubules"],
      ]),
      recall_data: recall("Which term means release of sperms into seminiferous tubule lumen?", "Spermiation.", [], [], ["Spermiogenesis is transformation of spermatids into sperm."]),
      importance: 5,
      source_page: 100,
      sort_order: 11,
    }),
    card(chapterId, "hormonal-control-spermatogenesis", {
      title: "Hormonal Control of Spermatogenesis",
      card_type: "process",
      body: "GnRH from hypothalamus stimulates anterior pituitary gonadotropins.",
      table_data: table(["Hormone", "Source-backed action"], [
        ["GnRH", "Stimulates anterior pituitary to secrete LH and FSH"],
        ["LH", "Acts on Leydig cells and stimulates androgen secretion"],
        ["Androgens", "Stimulate spermatogenesis"],
        ["FSH", "Acts on Sertoli cells and stimulates secretion of factors for spermiogenesis"],
      ]),
      recall_data: recall("Which hormone acts on Leydig cells?", "LH."),
      importance: 5,
      source_page: 101,
      sort_order: 12,
    }),
    card(chapterId, "sperm-structure", {
      title: "Sperm Structure",
      card_type: "diagram",
      body: "A mature sperm has head, middle piece and tail.",
      diagram_data: { type: "bio-sperm-structure" },
      table_data: table(["Part/value", "Source-backed recall"], [
        ["Length", "About 60 micrometre (0.06 mm)"],
        ["Head", "Oval; nucleus and acrosome"],
        ["Acrosome", "Formed from Golgi complex; contains lytic enzymes"],
        ["Middle piece", "Axial filament surrounded by mitochondria and cytoplasm"],
        ["Tail", "Central axial filament; produces undulating movement"],
        ["Normal fertility", "At least 60% sperms normal shape and size, 40% vigorous motility"],
      ]),
      recall_data: recall("Which sperm part contains lytic enzymes?", "Acrosome."),
      importance: 5,
      source_page: 101,
      sort_order: 13,
    }),
    card(chapterId, "oogenesis-sequence", {
      title: "Oogenesis Sequence",
      card_type: "sequence",
      body: "Oogenesis starts in embryonic stage and resumes around ovulation/fertilisation.",
      table_data: table(["Order", "Source-backed stage"], [
        ["1", "Oogonia 2n (46 chromosomes) formed at foetal stage"],
        ["2", "Primary oocyte 2n grows and is arrested in prophase-I"],
        ["3", "First meiotic division prior to ovulation forms secondary oocyte (n) and first polar body (n)"],
        ["4", "Second meiotic division during fertilisation forms ovum (n) and second polar body (n)"],
      ]),
      recall_data: recall("When is the second meiotic division completed in oogenesis?", "During fertilisation."),
      importance: 5,
      source_page: 101,
      sort_order: 14,
    }),
    card(chapterId, "oogenesis-values", {
      title: "Oogenesis Source Values",
      card_type: "fact",
      body: "The source gives exact values for oogonia, follicles and ovum size.",
      table_data: table(["Cue", "Source-backed value"], [
        ["Oogonia formed in embryonic stage", "2 million egg mother cells within each ovary"],
        ["Primary follicles left at puberty", "60,000-80,000 in each ovary"],
        ["Ovum diameter", "About 0.2 mm"],
        ["Ovum membranes", "Plasma membrane, zona pellucida and corona radiata"],
      ]),
      recall_data: recall("How many primary follicles are left in each ovary at puberty in the source?", "60,000-80,000."),
      importance: 5,
      source_page: 101,
      sort_order: 15,
    }),
    card(chapterId, "spermatogenesis-vs-oogenesis", {
      title: "Spermatogenesis vs Oogenesis",
      card_type: "comparison",
      body: "The source compares male and female gametogenesis.",
      table_data: table(["Feature", "Spermatogenesis", "Oogenesis"], [
        ["Site", "Testis", "Ovary"],
        ["Growth phase", "Limited growth phase", "Elaborated growth phase"],
        ["Product from one primary cell", "4 sperms", "One ovum"],
        ["Polar bodies", "No polar body formation", "Polar bodies are formed"],
        ["Timing", "Begins at puberty and extends up to senility", "Begins embryonic stage, suspends up to puberty and ceases around age fifty"],
      ]),
      recall_data: recall("How many ova form from one primary oocyte?", "One ovum."),
      importance: 5,
      source_page: 101,
      sort_order: 16,
    }),
    card(chapterId, "menstrual-cycle-overview", {
      title: "Menstrual Cycle Overview",
      card_type: "fact",
      body: "Menstrual cycle is the cyclic event from one menstruation to the next during reproductive life.",
      diagram_data: { type: "bio-menstrual-cycle" },
      table_data: table(["Cue", "Source-backed recall"], [
        ["Duration", "28 or 29 days"],
        ["Seen in", "Humans and other primates"],
        ["Includes", "Ovarian cycle and uterine cycle"],
        ["Menarche", "First menstruation during puberty"],
        ["Menopause", "Cessation of menstrual cycle around 50 years of age"],
      ]),
      recall_data: recall("What is the usual menstrual cycle duration in the source?", "28 or 29 days."),
      importance: 5,
      source_page: 102,
      sort_order: 17,
    }),
    card(chapterId, "menstrual-cycle-phases", {
      title: "Menstrual Cycle Phases",
      card_type: "sequence",
      body: "The source gives exact day ranges for menstrual-cycle phases.",
      table_data: table(["Phase", "Days", "Source-backed recall"], [
        ["Menstrual phase", "1-5th day", "Menstrual flow lasts 3-5 days if ovum is not fertilized"],
        ["Follicular or proliferative phase", "5-13th day", "FSH stimulates follicles; oestrogens proliferate endometrium"],
        ["Ovulatory phase", "14th day", "LH surge induces rupture of Graafian follicle and ovulation"],
        ["Secretory or luteal phase", "15-28th day", "Corpus luteum secretes progesterone; endometrium becomes vascular, thick and soft"],
      ]),
      recall_data: recall("On which day does ovulation occur in the source?", "14th day.", [], [], ["LH surge induces ovulation."]),
      importance: 5,
      source_page: 102,
      sort_order: 18,
    }),
    card(chapterId, "fsh-vs-lh", {
      title: "FSH vs LH in Reproduction",
      card_type: "comparison",
      body: "FSH and LH have distinct roles in male and female reproduction.",
      table_data: table(["Hormone", "Male source-backed role", "Female source-backed role"], [
        ["FSH", "Acts on Sertoli cells and stimulates factors for spermiogenesis", "Stimulates development of primary follicles into Graafian follicles and oestrogen secretion"],
        ["LH", "Acts on Leydig cells and stimulates androgen secretion", "LH surge induces ovulation and corpus luteum formation/maintenance"],
      ]),
      recall_data: recall("Which hormone surge induces ovulation?", "LH surge."),
      importance: 5,
      source_page: 102,
      sort_order: 19,
    }),
    card(chapterId, "fertilisation-site-and-route", {
      title: "Fertilisation Site and Route",
      card_type: "sequence",
      body: "Fertilisation occurs in the ampullary region of the fallopian tube.",
      diagram_data: { type: "bio-fertilisation-implantation" },
      table_data: table(["Route", "Source-backed path"], [
        ["Sperm route", "Vagina -> cervical canal -> uterus -> isthmus -> ampullary region"],
        ["Ovum route", "Ovary -> fimbriae -> infundibulum -> ampullary region"],
        ["Condition", "Fertilisation happens only if ovum and sperms are transported simultaneously"],
        ["Block to polyspermy", "Zona pellucida changes block entry of additional sperms"],
      ]),
      recall_data: recall("Where does fertilisation occur?", "Ampullary region of fallopian tube."),
      importance: 5,
      source_page: 102,
      sort_order: 20,
    }),
    card(chapterId, "cleavage-to-implantation", {
      title: "Cleavage to Implantation",
      card_type: "sequence",
      body: "The zygote cleaves as it moves through the isthmus towards uterus.",
      table_data: table(["Stage", "Source-backed recall"], [
        ["Cleavage", "Mitotic divisions forming 2, 4, 8 and 16 blastomeres"],
        ["Morula", "Embryo with 8-16 blastomeres"],
        ["Blastocyst", "Morula transforms into blastocyst"],
        ["Trophoblast", "Outer layer that nourishes inner cell mass and attaches to endometrium"],
        ["Implantation", "Blastocyst becomes embedded in endometrium"],
        ["Gastrula", "Three-layered structure with ectoderm, mesoderm and endoderm"],
      ]),
      recall_data: recall("What is the embryo with 8-16 blastomeres called?", "Morula."),
      importance: 5,
      source_page: 103,
      sort_order: 21,
    }),
    card(chapterId, "placenta-functions", {
      title: "Placenta Functions",
      card_type: "concept",
      body: "Placenta is the structural and functional unit between foetus and maternal body.",
      table_data: table(["Function", "Source-backed detail"], [
        ["Exchange", "Supplies O2 and nutrients from mother to foetus"],
        ["Removal", "Removes CO2 and excretory wastes from foetus"],
        ["Barrier", "Acts as barrier between foetus and mother"],
        ["Endocrine", "Secretes hCG, hPL, oestrogens, progesterone and relaxin"],
        ["Connection", "Connected to embryo by umbilical cord"],
      ]),
      recall_data: recall("Name two placental hormones listed in the source.", "hCG and hPL.", ["Placenta also secretes oestrogens, progesterone and relaxin."]),
      importance: 5,
      source_page: 103,
      sort_order: 22,
    }),
    card(chapterId, "embryo-milestones", {
      title: "Embryo Development Milestones",
      card_type: "fact",
      body: "The source gives visible developmental milestones during pregnancy.",
      table_data: table(["Time", "Source-backed milestone"], [
        ["After one month", "Heart is formed"],
        ["End of second month", "Limbs and digits are developed"],
        ["End of 12 weeks", "Major organs including limbs and external genital organs are well developed"],
        ["During 5th month", "First movement of foetus and appearance of hair on head"],
        ["End of 24 weeks", "Body covered with fine hair, eyelids separate and eyelashes formed"],
        ["End of 9 months", "Ready for delivery"],
      ]),
      recall_data: recall("When is the heart formed in the embryo according to the source?", "After one month."),
      importance: 5,
      source_page: 103,
      sort_order: 23,
    }),
    card(chapterId, "gestation-parturition-lactation", {
      title: "Gestation, Parturition and Lactation",
      card_type: "process",
      body: "Parturition is induced by a neuroendocrine mechanism.",
      table_data: table(["Cue", "Source-backed recall"], [
        ["Human gestation", "9 months"],
        ["Other examples", "Cats: 2 months; dogs: 2 months; elephants: 21 months"],
        ["Foetal ejection reflex", "Signals from foetus and placenta induce mild uterine contractions"],
        ["Oxytocin", "Released from maternal pituitary; causes stronger uterine contractions"],
        ["After birth", "Placenta and umbilical cord remnants expelled after parturition"],
        ["Colostrum", "Yellowish milk in initial days; contains antibodies essential for newborn resistance"],
      ]),
      recall_data: recall("Which hormone drives stronger uterine contractions during parturition?", "Oxytocin."),
      importance: 5,
      source_page: 103,
      sort_order: 24,
    }),
  ];
}

function reproductiveHealthCards(chapterId) {
  return [
    card(chapterId, "reproductive-health-definition", {
      title: "Reproductive Health",
      card_type: "concept",
      body: "According to WHO, reproductive health is total well-being in all aspects of reproduction.",
      table_data: table(["Aspect", "Source-backed phrase"], [
        ["Physical", "Included in reproductive health"],
        ["Emotional", "Included in reproductive health"],
        ["Behavioural", "Included in reproductive health"],
        ["Social", "Included in reproductive health"],
      ]),
      recall_data: recall("How does WHO define reproductive health in this source?", "Total well-being in all aspects of reproduction: physical, emotional, behavioural and social."),
      importance: 5,
      source_page: 104,
      sort_order: 1,
    }),
    card(chapterId, "rch-and-sex-education", {
      title: "RCH and Sex Education",
      card_type: "concept",
      body: "India initiated reproductive health programmes as family planning in 1951.",
      table_data: table(["Cue", "Source-backed recall"], [
        ["RCH programmes", "Deal with reproduction-related awareness, birth control, pregnancy care, post-natal care, breastfeeding and equal opportunities"],
        ["Sex education", "Provides right information and avoids myths and misconceptions"],
        ["Safe practices", "Includes reproductive organs, adolescence changes, safe and hygienic sexual practices, STDs and AIDS"],
      ]),
      recall_data: recall("When did India initiate family planning programmes?", "1951."),
      importance: 4,
      source_page: 104,
      sort_order: 2,
    }),
    card(chapterId, "population-explosion-values", {
      title: "Population Explosion Values",
      card_type: "fact",
      body: "The source gives exact population values and control measures.",
      table_data: table(["Cue", "Source-backed value/detail"], [
        ["World population", "About 2 billion in 1900, about 6 billion by 2000 and 7.2 billion in 2011"],
        ["India population", "Nearly 350 million at independence, 1 billion by 2000, crossed 1.2 billion in May 2011"],
        ["2011 growth rate", "Less than 2% or 20/1000/year"],
        ["Marriageable age", "Females 18 years; males 21 years"],
        ["Slogan", "Hum Do Hamare Do"],
      ]),
      recall_data: recall("What statutory marriageable ages are stated?", "Females 18 years and males 21 years."),
      importance: 5,
      source_page: 104,
      sort_order: 3,
    }),
    card(chapterId, "ideal-contraceptive", {
      title: "Ideal Contraceptive",
      card_type: "fact",
      body: "The source lists properties of an ideal contraceptive.",
      table_data: table(["Property", "Source-backed detail"], [
        ["Use", "User-friendly and easily available"],
        ["Effect", "Effective and reversible"],
        ["Side effects", "No or least side-effects"],
        ["Sexual act", "Should not interfere with sexual drive, desire and sexual act"],
      ]),
      recall_data: recall("Should an ideal contraceptive interfere with sexual drive?", "No."),
      importance: 4,
      source_page: 104,
      sort_order: 4,
    }),
    card(chapterId, "natural-contraception", {
      title: "Natural Methods",
      card_type: "comparison",
      body: "Natural or traditional methods avoid chances of ovum and sperms meeting.",
      table_data: table(["Method", "Source-backed recall"], [
        ["Periodic abstinence", "Avoid coitus from day 10 to 17 of menstrual cycle, the fertile period"],
        ["Coitus interruptus", "Withdraw penis before ejaculation to avoid insemination"],
        ["Lactational amenorrhea", "Absence of menstrual cycle and ovulation due to intense lactation; effective up to 6 months following parturition"],
      ]),
      recall_data: recall("What is the fertile-period abstinence window in the source?", "Day 10 to 17 of menstrual cycle."),
      importance: 5,
      source_page: 104,
      sort_order: 5,
    }),
    card(chapterId, "barrier-methods", {
      title: "Barrier Methods",
      card_type: "classification",
      body: "Barrier methods prevent physical meeting of sperm and ovum.",
      table_data: table(["Barrier", "Source-backed recall"], [
        ["Condoms", "Rubber/latex sheath; male condom covers penis and female condom covers vagina and cervix"],
        ["Condom advantage", "Protects from STDs and AIDS; easily available, disposable and gives privacy"],
        ["Diaphragms, cervical caps and vaults", "Inserted into female reproductive tract to cover cervix; reusable"],
        ["Spermicides", "Creams, jellies and foams used with barriers to increase contraceptive efficiency"],
      ]),
      recall_data: recall("Which barrier method protects from STDs and AIDS in the source?", "Condoms."),
      importance: 5,
      source_page: 104,
      sort_order: 6,
    }),
    card(chapterId, "iud-types", {
      title: "IUD Types",
      card_type: "classification",
      body: "IUDs are inserted in the uterus through vagina by doctors or nurses.",
      table_data: table(["IUD type", "Source-backed action", "Examples"], [
        ["Non-medicated IUDs", "Retard sperm motility and have spermicidal effect", "Lippes loop"],
        ["Copper releasing IUDs", "Cu ions suppress motility and fertilising capacity of sperms", "CuT, Cu7, Multiload 375"],
        ["Hormone releasing IUDs", "Make uterus unsuitable for implantation and cervix hostile to sperms", "Progestasert, LNG-20"],
      ]),
      recall_data: recall("Which IUD example releases copper?", "CuT.", ["Cu7 and Multiload 375 are also listed."]),
      importance: 5,
      source_page: 104,
      sort_order: 7,
    }),
    card(chapterId, "oral-injectable-emergency-contraception", {
      title: "Oral, Injectable and Emergency Contraception",
      card_type: "classification",
      body: "Hormonal contraceptives inhibit ovulation/implantation and thicken cervical mucus.",
      table_data: table(["Method", "Source-backed recall"], [
        ["Pills", "Taken daily for 21 days starting within first five days of menstrual cycle, followed by 7-day gap"],
        ["Saheli", "Non-steroidal once-a-week pill developed by CDRI Lucknow"],
        ["Injectables/implants", "Progestogens or progestogen-oestrogen combinations; effective periods much longer"],
        ["Emergency contraception", "Progestogens/progestogen-oestrogen combinations and IUDs within 72 hours of coitus"],
      ]),
      recall_data: recall("What is Saheli?", "A non-steroidal once-a-week oral contraceptive for females developed by CDRI Lucknow."),
      importance: 5,
      source_page: 105,
      sort_order: 8,
    }),
    card(chapterId, "vasectomy-vs-tubectomy", {
      title: "Vasectomy vs Tubectomy",
      card_type: "comparison",
      body: "Surgical methods block gamete transport and are very effective, but reversibility is poor.",
      table_data: table(["Procedure", "Sex", "Source-backed action"], [
        ["Vasectomy", "Male", "Small part of vas deferens is removed or tied through a small incision on scrotum"],
        ["Tubectomy", "Female", "Small part of fallopian tube is removed or tied through abdomen or vagina"],
      ]),
      recall_data: recall("Which duct is cut or tied in vasectomy?", "Vas deferens.", [], [], ["Tubectomy acts on the fallopian tube."]),
      importance: 5,
      source_page: 105,
      sort_order: 9,
    }),
    card(chapterId, "contraceptive-methods-comparison", {
      title: "Contraceptive Methods Comparison",
      card_type: "comparison",
      body: "The source groups contraceptive methods by how they prevent conception.",
      diagram_data: { type: "bio-contraceptive-methods" },
      table_data: table(["Group", "Main source-backed mechanism", "Examples"], [
        ["Natural", "Avoid ovum and sperms meeting", "Periodic abstinence, withdrawal, lactational amenorrhea"],
        ["Barrier", "Prevent physical meeting of sperm and ovum", "Condoms, diaphragms, cervical caps, vaults"],
        ["IUD", "Increase phagocytosis of sperms; type-specific effects", "Lippes loop, CuT, LNG-20"],
        ["Hormonal", "Inhibit ovulation/implantation and thicken cervical mucus", "Pills, Saheli, injectables"],
        ["Surgical", "Block gamete transport", "Vasectomy, tubectomy"],
      ]),
      recall_data: recall("Which contraception group blocks gamete transport?", "Surgical methods."),
      importance: 5,
      source_page: 105,
      sort_order: 10,
    }),
    card(chapterId, "mtp", {
      title: "Medical Termination of Pregnancy",
      card_type: "fact",
      body: "MTP is intentional or voluntary termination of pregnancy before full term.",
      table_data: table(["Cue", "Source-backed value/detail"], [
        ["Also called", "Induced abortion"],
        ["Worldwide number", "45 to 50 million MTPs per year, about 1/5th of conceived pregnancies"],
        ["India", "Legalised MTP in 1971 with strict conditions"],
        ["Safe timing", "First trimester, up to 12 weeks"],
        ["Risk", "Second trimester abortions are very risky"],
      ]),
      recall_data: recall("Up to what timing are MTPs safe in the source?", "First trimester, up to 12 weeks."),
      importance: 5,
      source_page: 105,
      sort_order: 11,
    }),
    card(chapterId, "mtp-amendment-and-amniocentesis", {
      title: "MTP Amendment and Amniocentesis",
      card_type: "neet_trap",
      body: "The source explicitly warns about illegal MTP and misuse of amniocentesis.",
      table_data: table(["Cue", "Source-backed detail"], [
        ["2017 amendment", "Within first 12 weeks on opinion of one registered medical practitioner"],
        ["12-24 weeks", "Opinion of two registered medical practitioners"],
        ["Amniocentesis", "Amniotic fluid is taken to analyse foetal cells and dissolved substances"],
        ["Misuse", "Foetal sex determination followed by MTP if foetus is female"],
      ]),
      recall_data: recall("For 12-24 weeks, whose opinion is required in the source?", "Two registered medical practitioners."),
      importance: 5,
      source_page: 105,
      sort_order: 12,
    }),
    card(chapterId, "stds", {
      title: "Sexually Transmitted Diseases",
      card_type: "examples",
      body: "STDs are diseases or infections transmitted through sexual intercourse.",
      table_data: table(["Cue", "Source-backed recall"], [
        ["Examples", "Gonorrhoea, syphilis, genital herpes, chlamydiasis, genital warts, trichomoniasis, hepatitis-B and AIDS"],
        ["Other transmission for hepatitis-B and HIV", "Needles, surgical instruments, blood transfusion and infected mother to foetus"],
        ["Curability", "Except hepatitis-B, genital herpes and HIV, other diseases are completely curable if detected early and treated properly"],
        ["High-risk age", "15-24 years"],
      ]),
      recall_data: recall("Which listed STDs are exceptions to complete curability in the source?", "Hepatitis-B, genital herpes and HIV."),
      importance: 5,
      source_page: 105,
      sort_order: 13,
    }),
    card(chapterId, "std-prevention", {
      title: "STD Prevention",
      card_type: "fact",
      body: "The source lists prevention steps for STDs.",
      table_data: table(["Prevention", "Source-backed recall"], [
        ["Partners", "Avoid sex with unknown partners or multiple partners"],
        ["Barrier", "Always use condoms during coitus"],
        ["Doubt/symptoms", "Consult a qualified doctor for early detection and complete treatment"],
      ]),
      recall_data: recall("Which barrier is specifically advised to prevent STDs?", "Condoms."),
      importance: 4,
      source_page: 105,
      sort_order: 14,
    }),
    card(chapterId, "infertility", {
      title: "Infertility",
      card_type: "concept",
      body: "Infertility is inability to conceive or produce children after 2 years of unprotected sexual cohabitation.",
      table_data: table(["Cue", "Source-backed recall"], [
        ["Definition window", "2 years of unprotected sexual cohabitation"],
        ["Reasons", "Physical, congenital, diseases, drugs, immunological or psychological"],
        ["ART", "Technologies used to correct infertility problems"],
      ]),
      recall_data: recall("What time window defines infertility in this source?", "2 years of unprotected sexual cohabitation."),
      importance: 5,
      source_page: 105,
      sort_order: 15,
    }),
    card(chapterId, "ivf-zift-iut", {
      title: "IVF, ZIFT and IUT",
      card_type: "classification",
      body: "IVF forms a zygote under simulated laboratory conditions, followed by embryo transfer.",
      diagram_data: { type: "bio-art-flow" },
      table_data: table(["Technique", "Source-backed recall"], [
        ["IVF or test tube baby programme", "Ova and sperms are collected and induced to form zygote in laboratory"],
        ["ZIFT", "Zygote or early embryo with up to 8 blastomeres transferred into fallopian tube"],
        ["IUT", "Embryo with more than 8 blastomeres transferred into uterus"],
      ]),
      recall_data: recall("Which ART transfers an embryo with more than 8 blastomeres into uterus?", "IUT.", [], [], ["ZIFT is up to 8 blastomeres into fallopian tube."]),
      importance: 5,
      source_page: 106,
      sort_order: 16,
    }),
    card(chapterId, "gift-icsi-ai-iui", {
      title: "GIFT, ICSI, AI and IUI",
      card_type: "classification",
      body: "The source lists ART methods for different infertility situations.",
      table_data: table(["Technique", "Source-backed recall"], [
        ["GIFT", "Ovum from donor transferred into fallopian tube of another female who cannot produce ovum but can provide suitable environment"],
        ["ICSI", "Single sperm injected directly into an egg in laboratory"],
        ["AI", "Semen from husband or donor artificially introduced into vagina or uterus"],
        ["IUI", "Artificial insemination into uterus"],
      ]),
      recall_data: recall("Which ART injects a single sperm directly into an egg?", "ICSI."),
      importance: 5,
      source_page: 106,
      sort_order: 17,
    }),
    card(chapterId, "art-comparison-and-problems", {
      title: "ART Comparison and Problems",
      card_type: "comparison",
      body: "ART helps infertility but has practical and social limitations in the source.",
      table_data: table(["Cue", "Source-backed detail"], [
        ["ZIFT vs IUT", "Up to 8 blastomeres to fallopian tube vs more than 8 blastomeres to uterus"],
        ["GIFT vs ICSI", "Donor ovum transfer vs direct sperm injection into egg"],
        ["AI/IUI use", "Male inability to inseminate female or low sperm counts"],
        ["Problems", "Needs specialized professionals and expensive instrumentation; available in very few centres"],
        ["Other problems", "Emotional, religious and social problems"],
        ["Alternative", "Legal adoption is a good method"],
      ]),
      recall_data: recall("What is the key ZIFT vs IUT distinction?", "ZIFT transfers up to 8 blastomeres into fallopian tube; IUT transfers more than 8 blastomeres into uterus."),
      importance: 5,
      source_page: 106,
      sort_order: 18,
    }),
  ];
}

const biologyBatch7CardsBySlug = {
  "reproduction-in-organisms": reproductionOrganismsCards,
  "sexual-reproduction-in-flowering-plants": floweringPlantCards,
  "human-reproduction": humanReproductionCards,
  "reproductive-health": reproductiveHealthCards,
};

export function getBiologyBatch7Chapters() {
  return BIOLOGY_BATCH_7_CHAPTER_DEFINITIONS.map((item) => ({
    id: chapter(item.slug),
    subject_id: "neet-biology",
    title: item.title,
    slug: item.slug,
    sort_order: item.sort_order,
    source_page: item.source_page,
  }));
}

export function getBiologyBatch7Cards() {
  return BIOLOGY_BATCH_7_CHAPTER_DEFINITIONS.flatMap((item) => biologyBatch7CardsBySlug[item.slug](chapter(item.slug)));
}
