export const BIOLOGY_BATCH_5_CHAPTER_DEFINITIONS = [
  { title: "Breathing and Exchange of Gases", slug: "breathing-and-exchange-of-gases", sort_order: 15, source_page: 69 },
  { title: "Body Fluid and Circulation", slug: "body-fluid-and-circulation", sort_order: 16, source_page: 72 },
  { title: "Excretory Products and their Elimination", slug: "excretory-products-and-their-elimination", sort_order: 17, source_page: 76 },
  { title: "Locomotion and Movement", slug: "locomotion-and-movement", sort_order: 18, source_page: 79 },
];

const chapter = (slug) => `neet-biology-${slug}`;

function table(columns, rows) {
  return { columns, rows };
}

function sections(items) {
  return { sections: items };
}

function recall(question, answer, key_points = [], examples = [], neet_traps = []) {
  return { recall_question: question, reveal_answer: answer, key_points, examples, neet_traps };
}

function card(chapterId, slug, payload) {
  return {
    id: `${chapterId}-${slug}`,
    chapter_id: chapterId,
    formulas: [],
    variables: [],
    conditions: [],
    table_data: null,
    diagram_data: null,
    diagram_svg: null,
    is_active: true,
    ...payload,
  };
}

function breathingCards(chapterId) {
  return [
    card(chapterId, "respiration-vs-breathing", {
      title: "Respiration vs Breathing",
      card_type: "comparison",
      body: "Respiration releases energy by oxidation of nutrients in living cells; breathing exchanges atmospheric O2 with cellular CO2.",
      table_data: table(["Term", "Recall answer"], [
        ["Respiration", "Oxidation of nutrients in living cells to release energy for biological work."],
        ["Breathing", "Exchange of O2 from atmosphere with CO2 produced by cells."],
      ]),
      recall_data: recall("Which process releases energy by oxidation of nutrients?", "Respiration."),
      importance: 4,
      source_page: 69,
      sort_order: 1,
    }),
    card(chapterId, "respiratory-organs", {
      title: "Respiratory Organs Across Animals",
      card_type: "examples",
      body: "The source links respiratory organs to animal groups.",
      table_data: table(["Respiratory surface", "Source examples"], [
        ["General body surface", "Sponges, coelenterates, flatworms etc."],
        ["Skin/moist cuticle", "Earthworms, leech, amphibians etc."],
        ["Tracheal tubes", "Insects, centipede, millipede, spider."],
        ["Gills", "Fishes, tadpoles, prawn."],
        ["Lungs", "Most vertebrates."],
      ]),
      recall_data: recall("Which respiratory organ is listed for insects?", "Tracheal tubes.", ["Centipede, millipede and spider are also listed with tracheal tubes."]),
      importance: 4,
      source_page: 69,
      sort_order: 2,
    }),
    card(chapterId, "respiratory-pathway", {
      title: "Human Respiratory Pathway",
      card_type: "sequence",
      body: "Air moves through the conducting part before reaching the exchange region.",
      diagram_data: { type: "bio-respiratory-pathway" },
      table_data: table(["Order", "Part"], [
        ["1", "External nostrils"],
        ["2", "Nasal passage and nasal chamber"],
        ["3", "Pharynx"],
        ["4", "Glottis and larynx"],
        ["5", "Trachea"],
        ["6", "Primary, secondary and tertiary bronchi"],
        ["7", "Bronchioles and terminal bronchioles"],
        ["8", "Respiratory bronchiole and alveolar duct"],
      ]),
      recall_data: recall("What comes after trachea in the source pathway?", "Primary bronchi.", ["The pathway continues to secondary bronchi, tertiary bronchi, bronchioles, terminal bronchioles, respiratory bronchiole and alveolar duct."]),
      importance: 5,
      source_page: 69,
      sort_order: 3,
    }),
    card(chapterId, "conducting-and-exchange-parts", {
      title: "Conducting Part vs Exchange Part",
      card_type: "comparison",
      body: "The source separates air transport from gas exchange.",
      table_data: table(["Part", "Source-backed role"], [
        ["Conducting part", "Transports atmospheric air into alveoli, clears foreign particles, humidifies air and brings air to body temperature."],
        ["Respiratory/exchange part", "Alveoli and ducts where gas exchange occurs."],
        ["Alveoli", "Structural and functional units of lungs."],
      ]),
      recall_data: recall("What are the structural and functional units of lungs?", "Alveoli."),
      importance: 5,
      source_page: 69,
      sort_order: 4,
    }),
    card(chapterId, "larynx-epiglottis-pleura", {
      title: "Larynx, Epiglottis and Pleura",
      card_type: "fact",
      body: "Small anatomy details are repeatedly tested.",
      table_data: table(["Structure", "Recall detail"], [
        ["Larynx", "Sound box or voice box; helps sound production."],
        ["Epiglottis", "Closes the glottis to prevent entry of food into the larynx."],
        ["Trachea/bronchi/initial bronchioles", "Supported by incomplete cartilaginous half rings."],
        ["Pleura", "Double layer: outer parietal and inner visceral; pleural fluid prevents friction."],
        ["Lungs", "Right lung has 3 lobes and left lung has 2 lobes."],
      ]),
      recall_data: recall("Which lung has 3 lobes in the source?", "Right lung.", [], [], ["Left lung has 2 lobes."]),
      importance: 4,
      source_page: 69,
      sort_order: 5,
    }),
    card(chapterId, "steps-of-respiration", {
      title: "Five Steps of Respiration",
      card_type: "sequence",
      body: "The source gives respiration as a five-step flow from ventilation to cellular respiration.",
      table_data: table(["Step", "Process"], [
        ["1", "Pulmonary ventilation or breathing"],
        ["2", "Gas exchange between lung alveoli and blood"],
        ["3", "Transport of O2 and CO2 by blood"],
        ["4", "Gas exchange between blood and tissues"],
        ["5", "Cellular or tissue respiration"],
      ]),
      recall_data: recall("What is the first step of respiration in the source?", "Pulmonary ventilation or breathing."),
      importance: 4,
      source_page: 69,
      sort_order: 6,
    }),
    card(chapterId, "inspiration-vs-expiration", {
      title: "Inspiration vs Expiration",
      card_type: "comparison",
      body: "Breathing depends on thoracic volume and pulmonary pressure changes.",
      diagram_data: { type: "bio-breathing-mechanics" },
      table_data: table(["Feature", "Inspiration", "Expiration"], [
        ["Nature", "Active intake of air", "Passive expelling of air"],
        ["Diaphragm", "Contracts and flattens", "Relaxes"],
        ["External intercostals", "Lift ribs and sternum", "Relax"],
        ["Thoracic volume", "Increases", "Decreases"],
        ["Intra-pulmonary pressure", "Falls below atmospheric pressure", "Rises above atmospheric pressure"],
        ["Forceful expiration", "-", "Abdominal and internal inter-costal muscles contract"],
      ]),
      recall_data: recall("Why does air enter during inspiration?", "Intra-pulmonary pressure falls below atmospheric pressure.", ["Diaphragm contraction and rib movement increase thoracic and pulmonary volume."]),
      importance: 5,
      source_page: 70,
      sort_order: 7,
    }),
    card(chapterId, "respiratory-volumes", {
      title: "Respiratory Volumes",
      card_type: "fact",
      body: "Use the handbook values exactly for NEET recall.",
      table_data: table(["Volume", "Definition", "Source value"], [
        ["TV", "Air inspired or expired during normal respiration", "About 500 ml; 6000-8000 ml per minute"],
        ["IRV", "Additional air inspired by forceful inspiration", "2500-3000 ml"],
        ["ERV", "Additional air expired by forceful expiration", "1000-1100 ml"],
        ["RV", "Air remaining after forcible expiration", "1100-1200 ml"],
        ["Dead space", "Respiratory tract from nostrils to terminal bronchi not involved in gas exchange", "About 150 ml"],
      ]),
      recall_data: recall("What is tidal volume according to the source?", "About 500 ml.", ["The source also states 6000-8000 ml per minute."]),
      importance: 5,
      source_page: 70,
      sort_order: 8,
    }),
    card(chapterId, "respiratory-capacities", {
      title: "Respiratory Capacities",
      card_type: "fact",
      body: "Capacities combine respiratory volumes.",
      table_data: table(["Capacity", "Formula or definition", "Source value"], [
        ["IC", "TV + IRV; total air inspired after normal expiration", "3000-3500 ml"],
        ["EC", "TV + ERV; total air expired after normal inspiration", "1500-1600 ml"],
        ["FRC", "ERV + RV; air remaining after normal expiration", "2100-2300 ml"],
        ["VC", "ERV + TV + IRV; air breathed in after forced expiration or out after forced inspiration", "3500-4500 ml"],
        ["TLC", "RV + ERV + TV + IRV or VC + RV", "5000-6000 ml"],
      ]),
      recall_data: recall("Which capacity equals ERV + RV?", "Functional residual capacity (FRC)."),
      importance: 5,
      source_page: 70,
      sort_order: 9,
    }),
    card(chapterId, "respiratory-rate-cycle", {
      title: "Respiratory Cycle and Rate",
      card_type: "fact",
      body: "A respiratory cycle is an inspiration plus expiration.",
      table_data: table(["Recall cue", "Source value"], [
        ["Respiratory cycle", "One inspiration + one expiration"],
        ["Normal respiratory rate", "12-16 times/min"],
        ["Instrument", "Spirometer or respirometer measures respiratory rate"],
      ]),
      recall_data: recall("What is one respiratory cycle?", "An inspiration and an expiration."),
      importance: 4,
      source_page: 70,
      sort_order: 10,
    }),
    card(chapterId, "partial-pressure-table", {
      title: "Partial Pressures in Gas Exchange",
      card_type: "table",
      body: "O2 and CO2 diffuse according to partial-pressure gradients.",
      diagram_data: { type: "bio-alveolus-exchange" },
      table_data: table(["Site", "pO2 (mm Hg)", "pCO2 (mm Hg)"], [
        ["Atmospheric air", "159", "0.3"],
        ["Alveoli", "104", "40"],
        ["Deoxygenated blood", "40", "45"],
        ["Oxygenated blood", "95", "40"],
        ["Tissues", "40", "45"],
      ]),
      recall_data: recall("Why does O2 diffuse from alveoli into blood?", "Alveolar pO2 is 104 mm Hg while deoxygenated blood pO2 is 40 mm Hg."),
      importance: 5,
      source_page: 70,
      sort_order: 11,
    }),
    card(chapterId, "diffusion-membrane", {
      title: "Diffusion Membrane",
      card_type: "fact",
      body: "Gas exchange depends on gradient, solubility, membrane thickness and surface area.",
      table_data: table(["Layer/factor", "Source-backed recall"], [
        ["Layer 1", "Squamous epithelium of alveoli"],
        ["Layer 2", "Endothelium of alveolar capillaries"],
        ["Layer 3", "Basement substance"],
        ["Thickness", "0.5 µm"],
        ["CO2 solubility", "20-25 times higher than O2"],
      ]),
      recall_data: recall("Why does CO2 diffuse efficiently despite a small pressure difference?", "CO2 solubility is 20-25 times higher than O2."),
      importance: 5,
      source_page: 70,
      sort_order: 12,
    }),
    card(chapterId, "oxygen-transport", {
      title: "Oxygen Transport",
      card_type: "concept",
      body: "Most oxygen is transported by haemoglobin as oxyhaemoglobin.",
      diagram_data: { type: "bio-oxygen-dissociation" },
      table_data: table(["Mode/factor", "Source-backed detail"], [
        ["Dissolved in plasma", "3%"],
        ["By haemoglobin", "97% as oxyhaemoglobin"],
        ["Hb capacity", "Each Hb has 4 haem units and carries 4 O2 molecules"],
        ["Alveoli favour binding", "High pO2, low pCO2, lesser H+ and lower temperature"],
        ["Tissues favour release", "Low pO2, high pCO2, high H+ and high temperature"],
        ["Delivery", "Every 100 ml oxygenated blood delivers around 5 ml O2 to tissues"],
      ]),
      recall_data: recall("How much O2 is transported by haemoglobin?", "97%.", ["It is transported as oxyhaemoglobin."]),
      importance: 5,
      source_page: 70,
      sort_order: 13,
    }),
    card(chapterId, "carbon-dioxide-transport", {
      title: "Carbon Dioxide Transport",
      card_type: "concept",
      body: "CO2 moves mainly as bicarbonates; carbonic anhydrase is abundant in RBCs.",
      formulas: [{ label: "CO2 conversion", latex: "CO_2 + H_2O \\rightleftharpoons H_2CO_3 \\rightleftharpoons HCO_3^- + H^+" }],
      table_data: table(["Mode", "Source-backed share/detail"], [
        ["Carbonic acid", "7% as CO2 dissolved in plasma water to form carbonic acid"],
        ["Carbamino-haemoglobin", "20-25% bound with haemoglobin"],
        ["Bicarbonates", "70%"],
        ["Carbonic anhydrase", "Present in RBCs and in very small quantity in plasma"],
        ["Delivery", "Every 100 ml deoxygenated blood delivers about 4 ml CO2 to alveoli"],
      ]),
      recall_data: recall("What is the main transport form of CO2 in the source?", "Bicarbonates, about 70%."),
      importance: 5,
      source_page: 71,
      sort_order: 14,
    }),
    card(chapterId, "oxygen-vs-carbon-dioxide-transport", {
      title: "O2 vs CO2 Transport",
      card_type: "comparison",
      body: "The source gives distinct dominant transport modes for oxygen and carbon dioxide.",
      table_data: table(["Feature", "O2", "CO2"], [
        ["Major transport form", "Oxyhaemoglobin", "Bicarbonates"],
        ["Minor dissolved fraction", "3% in plasma", "7% as carbonic acid"],
        ["Protein-bound form", "97% by haemoglobin", "20-25% as carbamino-haemoglobin"],
        ["Per 100 ml blood", "Oxygenated blood delivers around 5 ml O2 to tissues", "Deoxygenated blood delivers about 4 ml CO2 to alveoli"],
      ]),
      recall_data: recall("Which gas is mainly transported as bicarbonates?", "CO2.", [], [], ["O2 is mainly transported as oxyhaemoglobin."]),
      importance: 5,
      source_page: 71,
      sort_order: 15,
    }),
    card(chapterId, "respiration-regulation", {
      title: "Regulation of Respiration",
      card_type: "classification",
      body: "Respiration is regulated mainly by centres and receptors responding to CO2 and H+.",
      table_data: table(["Component", "Role in source"], [
        ["Respiratory rhythm centre", "Inspiratory and expiratory centres in medulla oblongata regulate respiratory rhythms."],
        ["Pneumotaxic centre", "In pons; moderates respiratory rhythm by reducing inspiration duration and altering rate."],
        ["Chemosensitive area", "Adjacent to rhythm centre; activated by increased CO2 and H+."],
        ["Aortic arch and carotid artery receptors", "Recognize CO2 and H+ changes and send signals."],
        ["Oxygen", "Role is quite insignificant."],
      ]),
      recall_data: recall("Which respiratory regulator has a quite insignificant role in the source?", "Oxygen.", [], [], ["CO2 and H+ are the major chemical cues."]),
      importance: 5,
      source_page: 71,
      sort_order: 16,
    }),
    card(chapterId, "respiratory-disorders", {
      title: "Respiratory Disorders",
      card_type: "comparison",
      body: "The source lists three respiratory disorders and their key cause-effect recall.",
      table_data: table(["Disorder", "Source-backed recall"], [
        ["Asthma", "Difficulty in breathing with wheezing due to inflammation of bronchi and bronchioles."],
        ["Emphysema", "Damage of alveolar walls decreases respiratory surface; major cause is cigarette smoking."],
        ["Occupational respiratory disorders", "Long exposure to dust can cause inflammation, fibrosis and lung damage."],
      ]),
      recall_data: recall("Which disorder damages alveolar walls and decreases respiratory surface?", "Emphysema.", [], [], ["Cigarette smoking is stated as a major cause."]),
      importance: 5,
      source_page: 71,
      sort_order: 17,
    }),
  ];
}

function circulationCards(chapterId) {
  return [
    card(chapterId, "open-vs-closed-circulation", {
      title: "Open vs Closed Circulatory System",
      card_type: "comparison",
      body: "The source compares circulatory systems by vessel confinement and examples.",
      table_data: table(["Feature", "Open", "Closed"], [
        ["Blood path", "Pumped through large vessels into open spaces or cavities called sinuses", "Blood flows through blood vessels"],
        ["Regulation", "Less precise", "More advantageous because flow can be precisely regulated"],
        ["Examples", "Arthropods and molluscs", "Annelids and chordates"],
      ]),
      recall_data: recall("Which circulatory system has blood in sinuses?", "Open circulatory system."),
      importance: 4,
      source_page: 72,
      sort_order: 1,
    }),
    card(chapterId, "heart-chambers-animal-groups", {
      title: "Chambered Hearts in Vertebrates",
      card_type: "classification",
      body: "Heart chambers differ across vertebrate groups.",
      table_data: table(["Group", "Heart chamber pattern"], [
        ["Fishes", "2-chambered heart: an atrium and a ventricle"],
        ["Amphibians", "3-chambered heart: two atria and one ventricle"],
        ["Reptiles except crocodiles", "3-chambered heart with incompletely partitioned ventricle"],
        ["Crocodiles, birds and mammals", "4-chambered heart"],
      ]),
      recall_data: recall("Which reptiles are listed with a 4-chambered heart?", "Crocodiles."),
      importance: 4,
      source_page: 72,
      sort_order: 2,
    }),
    card(chapterId, "single-incomplete-double-double", {
      title: "Single, Incomplete Double and Double Circulation",
      card_type: "comparison",
      body: "The source classifies circulation by mixing and circuit pattern.",
      diagram_data: { type: "bio-double-circulation" },
      table_data: table(["Type", "Source-backed recall", "Examples"], [
        ["Single circulation", "Deoxygenated blood goes heart → gills → body → heart; heart is venous", "Fishes"],
        ["Incomplete double circulation", "Oxygenated and deoxygenated blood mix in a single ventricle", "Amphibians and reptiles"],
        ["Double circulation", "No mixing; right side handles deoxygenated blood and left side handles oxygenated blood", "Birds and mammals"],
      ]),
      recall_data: recall("Which circulation has no mixing in the source?", "Double circulation."),
      importance: 5,
      source_page: 72,
      sort_order: 3,
    }),
    card(chapterId, "plasma-composition", {
      title: "Plasma Composition",
      card_type: "fact",
      body: "Plasma forms 55% of blood and is straw-coloured, slightly alkaline and viscous.",
      table_data: table(["Component", "Source value/detail"], [
        ["Plasma share", "55% of blood"],
        ["Formed elements", "45% of blood"],
        ["pH", "7.4"],
        ["Water", "90-92%"],
        ["Plasma proteins", "6-8%"],
        ["Serum", "Plasma without clotting factors"],
      ]),
      recall_data: recall("What is serum?", "Plasma without clotting factors."),
      importance: 5,
      source_page: 72,
      sort_order: 4,
    }),
    card(chapterId, "plasma-proteins", {
      title: "Plasma Proteins",
      card_type: "comparison",
      body: "The source assigns specific roles to the major plasma proteins.",
      table_data: table(["Protein", "Function"], [
        ["Fibrinogen", "Blood clotting"],
        ["Globulins", "Antibodies and defence"],
        ["Albumins", "Osmotic balance and regulation of BP"],
      ]),
      recall_data: recall("Which plasma protein helps osmotic balance and BP regulation?", "Albumins."),
      importance: 4,
      source_page: 72,
      sort_order: 5,
    }),
    card(chapterId, "formed-elements-comparison", {
      title: "RBC vs WBC vs Platelets",
      card_type: "comparison",
      body: "Formed elements differ in count, origin, lifespan and function.",
      table_data: table(["Feature", "RBC", "WBC", "Platelets"], [
        ["Other name", "Erythrocytes", "Leucocytes", "Thrombocytes"],
        ["Key structure", "Biconcave, non-nucleated, no mitochondria/Golgi etc.", "Colourless and nucleated", "Colourless non-nucleated cell fragments"],
        ["Count", "5-5.5 millions/mm3", "6000-8000/mm3", "1.5-3.5 lakhs/mm3"],
        ["Formation", "Red bone marrow", "Bone marrow, lymph glands and spleen", "Megakaryocytes in bone marrow"],
        ["Lifespan", "120 days", "1-15 days", "7 days"],
        ["Function", "CO2 and O2 transports", "Immune system", "Blood clotting"],
      ]),
      recall_data: recall("Which formed elements are non-nucleated cell fragments?", "Platelets.", [], [], ["Blood is treated as a fluid connective tissue in this chapter."]),
      importance: 5,
      source_page: 72,
      sort_order: 6,
    }),
    card(chapterId, "rbc-haemoglobin-spleen", {
      title: "RBC Recall Values",
      card_type: "fact",
      body: "RBC facts are numerical and source-specific.",
      table_data: table(["Cue", "Source-backed answer"], [
        ["Colour", "Red due to haemoglobin"],
        ["Normal Hb concentration", "12-16 g/100 ml"],
        ["RBC count", "5-5.5 millions/mm3"],
        ["Lifespan", "120 days"],
        ["Destroyed in", "Spleen, called graveyard of RBCs"],
      ]),
      recall_data: recall("Which organ is called the graveyard of RBCs?", "Spleen."),
      importance: 5,
      source_page: 72,
      sort_order: 7,
    }),
    card(chapterId, "wbc-types", {
      title: "WBC Type Comparison",
      card_type: "comparison",
      body: "Granulocytes and agranulocytes are compared by percentage and role.",
      table_data: table(["WBC type", "Percentage", "Source-backed role"], [
        ["Neutrophils", "60-65%", "Soldiers of body; phagocytosis"],
        ["Eosinophils", "2-3%", "Resist infections and cause allergic reactions"],
        ["Basophils", "0.5-1%", "Secrete histamine, serotonin, heparin etc.; cause inflammatory reactions"],
        ["Lymphocytes", "20-25%", "B and T lymphocytes; immune responses and antibodies"],
        ["Monocytes", "6-8%", "Largest WBC; phagocytosis"],
      ]),
      recall_data: recall("Which WBC is largest in the source?", "Monocytes."),
      importance: 5,
      source_page: 72,
      sort_order: 8,
    }),
    card(chapterId, "coagulation-flow", {
      title: "Blood Coagulation Flow",
      card_type: "process",
      body: "The source gives clotting as an enzyme conversion sequence ending in fibrin clot.",
      table_data: table(["Step", "Event"], [
        ["1", "Clumped platelets and tissues release thromboplastin"],
        ["2", "Thromboplastin forms thrombokinase or prothrombinase"],
        ["3", "Thrombokinase hydrolyses prothrombin to thrombin in presence of Ca2+"],
        ["4", "Thrombin converts soluble fibrinogen into insoluble fibrin"],
        ["5", "Fibrin threads trap damaged blood cells and form clot or coagulum"],
      ]),
      recall_data: recall("Which ion is required for prothrombin to thrombin conversion in the source?", "Ca2+."),
      importance: 4,
      source_page: 72,
      sort_order: 9,
    }),
    card(chapterId, "abo-blood-groups", {
      title: "ABO Blood Group Table",
      card_type: "table",
      body: "ABO grouping is based on antigens on RBCs and antibodies in plasma.",
      table_data: table(["Group", "Antigen", "Antibody", "Donates to", "Receives from"], [
        ["A", "A", "Anti-B", "A, AB", "A, O"],
        ["B", "B", "Anti-A", "B, AB", "B, O"],
        ["AB", "A, B", "Nil", "AB only", "A, B, AB, O"],
        ["O", "Nil", "Anti-A, Anti-B", "A, B, AB, O", "O only"],
      ]),
      recall_data: recall("Which ABO group is the universal recipient in the source?", "AB.", ["O is the universal donor."]),
      importance: 5,
      source_page: 73,
      sort_order: 10,
    }),
    card(chapterId, "abo-neet-trap", {
      title: "ABO Antigen-Antibody Trap",
      card_type: "neet_trap",
      body: "Agglutination occurs when interacting antigens and antibodies are mixed.",
      table_data: table(["RBC antigen", "Plasma antibody that reacts"], [
        ["A", "Anti-A"],
        ["B", "Anti-B"],
      ]),
      recall_data: recall("What causes agglutination in ABO transfusion?", "Interaction between matching RBC antigens and plasma antibodies.", [], [], ["Do not pair group A with anti-B for agglutination; antigen A reacts with anti-A."]),
      importance: 5,
      source_page: 73,
      sort_order: 11,
    }),
    card(chapterId, "rh-factor", {
      title: "Rh Factor and Erythroblastosis Foetalis",
      card_type: "concept",
      body: "Rh factor is an RBC antigen; Rh incompatibility can harm later Rh+ foetuses of an Rh- mother.",
      table_data: table(["Cue", "Source-backed detail"], [
        ["Rh+ve", "Rh antigen present on RBCs"],
        ["Rh-ve", "Rh antigen absent"],
        ["Frequency", "Nearly 80% humans are Rh+ve"],
        ["Anti-Rh antibodies", "Not naturally found"],
        ["Prevention", "Anti-Rh antibodies to mother immediately after first delivery"],
      ]),
      recall_data: recall("Why is Rh matching needed before transfusion?", "An Rh-ve person can develop anti-Rh antibodies after receiving Rh+ blood, causing agglutination on later exposure."),
      importance: 5,
      source_page: 73,
      sort_order: 12,
    }),
    card(chapterId, "artery-vs-vein", {
      title: "Artery vs Vein",
      card_type: "comparison",
      body: "Blood vessels are named by direction relative to the heart, not by oxygenation.",
      table_data: table(["Feature", "Artery", "Vein"], [
        ["Direction", "Carry blood from heart to tissues", "Carry blood to heart"],
        ["Usual oxygenation", "Oxygenated", "Deoxygenated"],
        ["Exception", "Pulmonary artery is deoxygenated", "Pulmonary vein is oxygenated"],
        ["Smaller branches", "Arterioles", "Venules"],
        ["Wall", "Three layers; tunica media stronger", "Three-layered but tunica media comparatively thin"],
      ]),
      recall_data: recall("Which artery carries deoxygenated blood?", "Pulmonary artery.", [], [], ["Arteries and veins are defined by direction, not oxygen level."]),
      importance: 5,
      source_page: 73,
      sort_order: 13,
    }),
    card(chapterId, "heart-anatomy", {
      title: "Human Heart Anatomy",
      card_type: "classification",
      body: "The source describes the human heart as a four-chambered mesodermal organ in the mediastinum.",
      table_data: table(["Structure", "Source-backed detail"], [
        ["Pericardium", "Double layered; pericardial fluid reduces friction"],
        ["Septa", "Inter-atrial and inter-ventricular septa separate chambers"],
        ["Tricuspid valve", "Between right atrium and right ventricle"],
        ["Bicuspid/mitral valve", "Between left atrium and left ventricle"],
        ["Semilunar valves", "At openings of pulmonary artery and aorta; prevent backflow"],
      ]),
      recall_data: recall("Which valve lies between left atrium and left ventricle?", "Bicuspid or mitral valve."),
      importance: 5,
      source_page: 73,
      sort_order: 14,
    }),
    card(chapterId, "heart-blood-flow", {
      title: "Heart Blood-Flow Route",
      card_type: "sequence",
      body: "Blood flow through the heart is one-way because of valves.",
      diagram_data: { type: "bio-heart-flow" },
      table_data: table(["Side", "Route"], [
        ["Right side", "Vena cava → Right atrium → Tricuspid valve → Right ventricle → Pulmonary artery"],
        ["Left side", "Pulmonary veins → Left atrium → Bicuspid/mitral valve → Left ventricle → Aorta"],
      ]),
      recall_data: recall("Which major vessel leaves the right ventricle?", "Pulmonary artery.", [], [], ["Pulmonary artery carries deoxygenated blood."]),
      importance: 5,
      source_page: 73,
      sort_order: 15,
    }),
    card(chapterId, "conducting-system", {
      title: "Cardiac Conducting System",
      card_type: "sequence",
      body: "Nodal tissue generates and conducts impulses through the heart.",
      diagram_data: { type: "bio-cardiac-conduction" },
      table_data: table(["Part", "Source-backed recall"], [
        ["SAN", "Right upper corner of right atrium; initiates and maintains contraction"],
        ["AVN", "Lower left corner of right atrium close to AV septum"],
        ["AV bundle", "Passes through AV septa and divides into right and left branches"],
        ["Purkinje fibres", "Fine fibres through ventricular musculature"],
        ["Pacemaker", "SAN, with 70-75 action potentials/min"],
      ]),
      recall_data: recall("What is the natural pacemaker of the human heart?", "SA node.", ["It initiates and maintains contraction with 70-75 action potentials/min."]),
      importance: 5,
      source_page: 73,
      sort_order: 16,
    }),
    card(chapterId, "cardiac-cycle", {
      title: "Cardiac Cycle",
      card_type: "process",
      body: "One heartbeat is one cardiac cycle and takes 0.8 seconds in the source.",
      table_data: table(["Stage", "Valve state / event"], [
        ["Joint diastole", "All chambers relaxed; tricuspid and bicuspid valves open; semilunar valves closed"],
        ["Atrial systole", "SAN action potential contracts atria; flow into ventricles increases about 30%"],
        ["Ventricular systole", "AVN/AV bundle conduct impulse; AV valves close; semilunar valves open"],
        ["Ventricular diastole", "Ventricles relax; semilunar valves close; AV valves open by atrial pressure"],
      ]),
      recall_data: recall("How long is one cardiac cycle in the source?", "0.8 seconds."),
      importance: 5,
      source_page: 74,
      sort_order: 17,
    }),
    card(chapterId, "heart-sounds-output", {
      title: "Heart Sounds and Cardiac Output",
      card_type: "fact",
      body: "The source gives the standard heart rate, stroke volume and cardiac output.",
      table_data: table(["Cue", "Source-backed answer"], [
        ["Normal heartbeat", "70-75/min, average 72/min"],
        ["Stroke volume", "About 70 ml"],
        ["Cardiac output", "Stroke volume × heart rate = 70 × 72 = about 5000 ml or 5 litres"],
        ["Lub", "Closure of tricuspid and bicuspid valves"],
        ["Dub", "Closure of semilunar valves"],
      ]),
      recall_data: recall("What causes the lub sound?", "Closure of tricuspid and bicuspid valves."),
      importance: 5,
      source_page: 74,
      sort_order: 18,
    }),
    card(chapterId, "ecg-waves", {
      title: "ECG Waves",
      card_type: "classification",
      body: "An electrocardiogram represents electrical activity during the cardiac cycle.",
      diagram_data: { type: "bio-ecg" },
      table_data: table(["Wave/complex", "Source-backed meaning"], [
        ["P wave", "Excitation or depolarization of atria during atrial systole"],
        ["QRS complex", "Depolarization of ventricles during ventricular systole"],
        ["T wave", "Repolarisation of ventricles"],
      ]),
      recall_data: recall("Which ECG part represents ventricular depolarization?", "QRS complex."),
      importance: 5,
      source_page: 74,
      sort_order: 19,
    }),
    card(chapterId, "pulmonary-vs-systemic", {
      title: "Pulmonary vs Systemic Circulation",
      card_type: "comparison",
      body: "Double circulation separates lung and body circuits.",
      table_data: table(["Feature", "Pulmonary circulation", "Systemic circulation"], [
        ["Start", "Right ventricle", "Left ventricle"],
        ["Route", "Pulmonary artery → lungs → pulmonary veins", "Aorta → arteries → arterioles → capillaries → venules → veins → vena cava"],
        ["End", "Left atrium", "Right atrium"],
        ["Function", "Oxygenates blood", "Provides nutrients/O2 and removes CO2/harmful substances"],
      ]),
      recall_data: recall("Where does pulmonary circulation end?", "Left atrium."),
      importance: 5,
      source_page: 74,
      sort_order: 20,
    }),
    card(chapterId, "portal-coronary-circulation", {
      title: "Portal and Coronary Circulation",
      card_type: "fact",
      body: "The source names two special circulations.",
      table_data: table(["Circulation", "Source-backed recall"], [
        ["Hepatic portal system", "Hepatic portal vein carries blood from intestine to liver before systemic circulation."],
        ["Coronary circulation", "Coronary vessels circulate blood to and from cardiac musculature."],
      ]),
      recall_data: recall("Which vessel carries blood from intestine to liver before systemic circulation?", "Hepatic portal vein."),
      importance: 4,
      source_page: 74,
      sort_order: 21,
    }),
    card(chapterId, "cardiac-regulation", {
      title: "Regulation of Cardiac Activity",
      card_type: "comparison",
      body: "The heart is myogenic, with regulation by ANS and adrenal medullary hormones.",
      table_data: table(["Regulator", "Source-backed effect"], [
        ["Nodal tissues", "Auto-regulate the myogenic heart"],
        ["Sympathetic nerves", "Increase heartbeat rate, strength of ventricular contraction and cardiac output"],
        ["Parasympathetic nerves", "Decrease heartbeat, conduction and cardiac output"],
        ["Adrenal medullary hormones", "Increase cardiac output"],
      ]),
      recall_data: recall("What does sympathetic stimulation do to cardiac output?", "Increases cardiac output."),
      importance: 4,
      source_page: 75,
      sort_order: 22,
    }),
    card(chapterId, "lymph", {
      title: "Lymph and Lymphatic System",
      card_type: "concept",
      body: "Lymph is tissue fluid that enters lymphatic vessels and drains into major veins.",
      table_data: table(["Cue", "Source-backed detail"], [
        ["Composition", "Colourless fluid with same mineral distribution as plasma; contains lymphocytes"],
        ["Exchange role", "Middleman between blood and tissues for nutrients and gases"],
        ["Transport role", "Carries liver plasma proteins to blood; transports digested fats, fat soluble vitamins and hormones"],
        ["Defence role", "Filters bacteria and foreign particles; lymph nodes produce WBC and antibodies"],
      ]),
      recall_data: recall("Which lymph vessels transport digested fats?", "Lacteals."),
      importance: 5,
      source_page: 75,
      sort_order: 23,
    }),
    card(chapterId, "circulatory-disorders", {
      title: "Circulatory Disorders",
      card_type: "comparison",
      body: "The source distinguishes blood pressure, coronary artery disease and heart failure terms.",
      table_data: table(["Disorder", "Source-backed recall"], [
        ["Hypertension", "Repeated BP of 140/90 or above; normal BP is 120/80 mm Hg"],
        ["CAD/atherosclerosis", "Calcium, fat, cholesterol and fibrous tissue deposited in coronary arteries, narrowing lumen"],
        ["Angina", "Acute chest pain due to O2 deficiency to heart muscles from improper blood flow"],
        ["Heart failure", "Inability to pump enough blood; lung congestion is main symptom"],
        ["Cardiac arrest", "Heart stops beating"],
        ["Heart attack", "Sudden damage of heart muscle due to inadequate blood supply"],
      ]),
      recall_data: recall("What BP value shows hypertension in the source?", "Repeated blood pressure of 140/90 or above.", ["Normal BP is 120/80 mm Hg."]),
      importance: 5,
      source_page: 75,
      sort_order: 24,
    }),
  ];
}

function excretionCards(chapterId) {
  return [
    card(chapterId, "ammonotelic-ureotelic-uricotelic", {
      title: "Ammonotelic vs Ureotelic vs Uricotelic",
      card_type: "comparison",
      body: "Nitrogenous wastes differ in toxicity, water need and animal examples.",
      table_data: table(["Type", "Waste", "Water/toxicity recall", "Source examples"], [
        ["Ammonotelism", "NH3", "Highly toxic, soluble, needs excess water", "Aquatic invertebrates, aquatic insects, bony fishes, aquatic amphibians etc."],
        ["Ureotelism", "Urea", "Less toxic; moderate water", "Cartilaginous fishes, frogs, toads, alligators, turtles, mammals etc."],
        ["Uricotelism", "Uric acid", "Water insoluble, less toxic; no water needed", "Insects, some land crustaceans, land snails, terrestrial reptiles and birds"],
      ]),
      recall_data: recall("Which nitrogenous waste needs excess water for excretion?", "Ammonia or NH3.", [], [], ["Ureotelism and uricotelism help in water conservation."]),
      importance: 5,
      source_page: 76,
      sort_order: 1,
    }),
    card(chapterId, "excretory-organs-examples", {
      title: "Excretory Organs Across Animals",
      card_type: "examples",
      body: "The source lists animal groups with their excretory organs.",
      table_data: table(["Organ", "Source examples / role"], [
        ["Protonephridia or flame cells", "Flatworms, rotifers, some annelids and Amphioxus; primarily osmoregulation"],
        ["Nephridia", "Annelids; nitrogenous wastes and osmoregulation"],
        ["Malpighian tubules", "Insects; nitrogenous wastes and osmoregulation"],
        ["Antennal or green glands", "Crustaceans such as prawn"],
        ["Kidneys", "Higher animals"],
      ]),
      recall_data: recall("What are the excretory organs of insects in the source?", "Malpighian tubules.", [], [], ["They also help in osmoregulation."]),
      importance: 5,
      source_page: 76,
      sort_order: 2,
    }),
    card(chapterId, "human-urinary-system", {
      title: "Human Urinary System",
      card_type: "classification",
      body: "The human excretory system consists of kidneys, ureters, urinary bladder and urethra.",
      diagram_data: { type: "bio-urinary-system" },
      table_data: table(["Part", "Recall cue"], [
        ["Kidneys", "Paired reddish brown bean-shaped organs"],
        ["Ureters", "Carry urine from kidneys"],
        ["Urinary bladder", "Stores urine"],
        ["Urethra", "Passage for urine out of the body"],
      ]),
      recall_data: recall("Name the four parts of the human excretory system.", "Kidneys, ureters, urinary bladder and urethra."),
      importance: 4,
      source_page: 76,
      sort_order: 3,
    }),
    card(chapterId, "kidney-structure-values", {
      title: "Kidney Structure and Values",
      card_type: "fact",
      body: "Kidney size and structure values are source-specific.",
      table_data: table(["Cue", "Source-backed answer"], [
        ["Position", "Between last thoracic and 3rd lumbar vertebra"],
        ["Size", "10-12 cm long, 5-7 cm wide, 2-3 cm thick"],
        ["Weight", "Average 120-170 gm"],
        ["Capsule", "Tough 3-layer fibrous renal capsule"],
        ["Hilum", "Concave entry/exit for blood vessels, nerves, lymphatic ducts and ureter"],
        ["Nephrons", "Nearly one million tubular nephrons in each kidney"],
      ]),
      recall_data: recall("How many nephrons are present in each kidney according to the source?", "Nearly one million."),
      importance: 5,
      source_page: 76,
      sort_order: 4,
    }),
    card(chapterId, "cortex-medulla-pyramids", {
      title: "Cortex, Medulla and Pyramids",
      card_type: "classification",
      body: "The kidney has an outer cortex and inner medulla.",
      table_data: table(["Region", "Source-backed detail"], [
        ["Cortex", "Outer region; extends between medullary pyramids as renal columns or Columns of Bertini"],
        ["Medulla", "Inner region with medullary or renal pyramids"],
        ["Pyramids", "Project into calyces"],
        ["Renal pelvis", "Hilum leads into renal pelvis with calyces"],
      ]),
      recall_data: recall("What are Columns of Bertini?", "Cortical extensions between medullary pyramids."),
      importance: 4,
      source_page: 76,
      sort_order: 5,
    }),
    card(chapterId, "nephron-structure", {
      title: "Nephron Structure",
      card_type: "classification",
      body: "The nephron is the structural and functional unit of kidney.",
      diagram_data: { type: "bio-nephron-flow" },
      table_data: table(["Part", "Source-backed recall"], [
        ["Glomerulus", "Tuft of capillaries formed by afferent arteriole; blood leaves by efferent arteriole"],
        ["Bowman's capsule", "Encloses glomerulus"],
        ["Malpighian body", "Glomerulus + Bowman's capsule"],
        ["Tubule order", "PCT → Henle's loop → DCT → collecting duct"],
        ["Vasa recta", "U-shaped minute vessel parallel to Henle's loop"],
      ]),
      recall_data: recall("What forms the Malpighian body?", "Glomerulus and Bowman's capsule."),
      importance: 5,
      source_page: 76,
      sort_order: 6,
    }),
    card(chapterId, "cortical-vs-juxtamedullary-nephron", {
      title: "Cortical vs Juxtamedullary Nephron",
      card_type: "comparison",
      body: "The source gives both percentage and loop/vasa recta differences.",
      table_data: table(["Feature", "Cortical nephron", "Juxtamedullary nephron"], [
        ["Percentage", "85%", "15%"],
        ["Henle's loop", "Short; extends little into medulla", "Long; extends deep into medulla"],
        ["Vasa recta", "Absent or reduced", "Present"],
      ]),
      recall_data: recall("Which nephron type has a long loop of Henle and vasa recta?", "Juxtamedullary nephron."),
      importance: 5,
      source_page: 76,
      sort_order: 7,
    }),
    card(chapterId, "urine-formation-overview", {
      title: "Urine Formation Overview",
      card_type: "sequence",
      body: "Urine formation has three source-listed processes.",
      table_data: table(["Order", "Process"], [
        ["1", "Glomerular filtration or ultrafiltration"],
        ["2", "Selective reabsorption"],
        ["3", "Tubular secretion"],
      ]),
      recall_data: recall("What are the three processes of urine formation?", "Filtration, reabsorption and secretion."),
      importance: 5,
      source_page: 77,
      sort_order: 8,
    }),
    card(chapterId, "glomerular-filtration", {
      title: "Glomerular Filtration",
      card_type: "process",
      body: "Blood pressure filters plasma through a three-layer filtration membrane into Bowman's capsule.",
      table_data: table(["Cue", "Source-backed detail"], [
        ["Filtration layers", "Endothelium of glomerular vessels, epithelium of Bowman's capsule and basement membrane"],
        ["Podocytes", "Leave filtration slits or slit pores"],
        ["Filtered material", "Almost all plasma except proteins"],
        ["Blood filtered", "1100-1200 ml per minute"],
        ["GFR", "125 ml/min or 180 litres/day"],
      ]),
      recall_data: recall("What is normal GFR in the source?", "125 ml/min or 180 litres/day."),
      importance: 5,
      source_page: 77,
      sort_order: 9,
    }),
    card(chapterId, "reabsorption-values", {
      title: "Selective Reabsorption Values",
      card_type: "fact",
      body: "Most filtrate is reabsorbed; only a small volume becomes urine.",
      table_data: table(["Cue", "Source-backed value/detail"], [
        ["Filtrate per day", "180 litres"],
        ["Reabsorbed", "99%"],
        ["Normal urine", "1.5 litres"],
        ["Active reabsorption", "Glucose, amino acids, Na+"],
        ["Passive reabsorption", "Nitrogenous wastes and water in initial segments"],
      ]),
      recall_data: recall("How much filtrate is reabsorbed according to the source?", "99%."),
      importance: 5,
      source_page: 77,
      sort_order: 10,
    }),
    card(chapterId, "pct-loop-dct-collecting-duct", {
      title: "PCT vs Loop vs DCT vs Collecting Duct",
      card_type: "comparison",
      body: "Tubular parts differ in permeability and reabsorption roles.",
      table_data: table(["Part", "Source-backed role"], [
        ["PCT", "Reabsorbs most nutrients and 70-80% electrolytes and water; brush border cuboidal epithelium"],
        ["Descending limb", "Permeable to water, almost impermeable to electrolytes"],
        ["Ascending limb", "Impermeable to water, transports electrolytes, dilutes filtrate"],
        ["DCT", "Conditional reabsorption of Na+ and water"],
        ["Collecting duct", "Reabsorbs large water, concentrates urine and allows small urea into medullary interstitium"],
      ]),
      recall_data: recall("Which nephron part reabsorbs 70-80% electrolytes and water?", "PCT.", [], [], ["PCT has simple cuboidal brush border epithelium."]),
      importance: 5,
      source_page: 77,
      sort_order: 11,
    }),
    card(chapterId, "filtration-reabsorption-secretion", {
      title: "Filtration vs Reabsorption vs Secretion",
      card_type: "comparison",
      body: "The three urine-formation processes move materials in different directions.",
      table_data: table(["Process", "Direction / role"], [
        ["Filtration", "Blood plasma except proteins passes into Bowman's capsule"],
        ["Reabsorption", "Useful substances and water move from filtrate back to blood"],
        ["Secretion", "H+, K+ and NH3 are secreted to maintain ionic and acid-base balance"],
      ]),
      recall_data: recall("Which urine-formation process maintains acid-base balance by H+, K+ and NH3 secretion?", "Tubular secretion."),
      importance: 5,
      source_page: 77,
      sort_order: 12,
    }),
    card(chapterId, "counter-current-mechanism", {
      title: "Counter-Current Mechanism",
      card_type: "process",
      body: "Henle's loop and vasa recta create and preserve the medullary gradient for concentrated urine.",
      diagram_data: { type: "bio-counter-current" },
      table_data: table(["Cue", "Source-backed detail"], [
        ["Counter-current", "Filtrate in Henle limbs and blood in vasa recta flow in opposite directions"],
        ["Gradient", "Cortex 300 mOsmolL-1 to inner medulla 1200 mOsmolL-1"],
        ["Gradient substances", "NaCl and urea"],
        ["NaCl route", "Transported by ascending limb, exchanged with descending vasa recta, returned by ascending vasa recta"],
        ["Final concentration", "DCT and collecting duct produce urine four times concentrated than initial filtrate"],
      ]),
      recall_data: recall("Which two structures form the counter-current mechanism?", "Henle's loop and vasa recta."),
      importance: 5,
      source_page: 77,
      sort_order: 13,
    }),
    card(chapterId, "micturition", {
      title: "Micturition Reflex",
      card_type: "process",
      body: "Micturition is a neural reflex triggered by bladder stretch.",
      table_data: table(["Step", "Event"], [
        ["1", "Urinary bladder fills and stretches"],
        ["2", "Stretch receptors send impulses to CNS"],
        ["3", "CNS sends motor messages"],
        ["4", "Bladder smooth muscles contract"],
        ["5", "Urethral sphincter relaxes and urine is released"],
      ]),
      recall_data: recall("What triggers the micturition reflex?", "Stretching of the urinary bladder."),
      importance: 4,
      source_page: 77,
      sort_order: 14,
    }),
    card(chapterId, "urine-values", {
      title: "Urine Values",
      card_type: "fact",
      body: "The source gives daily urine and urea values plus urine pH.",
      table_data: table(["Cue", "Source value"], [
        ["Adult urine", "1 to 1.5 litres/day"],
        ["Urea", "25-30 gm/day"],
        ["Urine pH", "Slightly acidic pH 6.0"],
        ["Lung excretion", "CO2 at 200 mL/minute plus water"],
      ]),
      recall_data: recall("What is the urine pH stated in the source?", "Slightly acidic pH 6.0."),
      importance: 5,
      source_page: 77,
      sort_order: 15,
    }),
    card(chapterId, "other-excretory-organs-human", {
      title: "Other Human Excretory Organs",
      card_type: "classification",
      body: "Besides kidneys, lungs, liver, skin and saliva eliminate wastes.",
      table_data: table(["Organ", "Excretory role"], [
        ["Lungs", "Remove CO2 and water"],
        ["Liver", "Bile contains bilirubin, biliverdin, cholesterol, degraded steroid hormones, vitamins and drugs"],
        ["Sweat glands", "Remove water, NaCl, urea and lactic acid; cooling effect"],
        ["Sebaceous glands", "Eliminate sterols, hydrocarbons and waxes through sebum"],
        ["Saliva", "Eliminates small nitrogenous wastes"],
      ]),
      recall_data: recall("Which skin secretion gives a protective oily covering?", "Sebum."),
      importance: 4,
      source_page: 78,
      sort_order: 16,
    }),
    card(chapterId, "adh-regulation", {
      title: "ADH Regulation of Kidney Function",
      card_type: "process",
      body: "ADH is released when osmoreceptors detect decreased body fluid volume.",
      table_data: table(["Step", "Source-backed event"], [
        ["1", "Decrease in body fluid activates osmoreceptors"],
        ["2", "Hypothalamus releases ADH or vasopressin"],
        ["3", "ADH stimulates water reabsorption from DCT and collecting duct"],
        ["4", "Diuresis is prevented and body fluid volume increases"],
        ["5", "ADH also constricts blood vessels, increasing BP, glomerular blood flow and GFR"],
      ]),
      recall_data: recall("Where does ADH increase water reabsorption in the source?", "DCT and collecting duct."),
      importance: 5,
      source_page: 78,
      sort_order: 17,
    }),
    card(chapterId, "jga-raas-anf", {
      title: "JGA, RAAS and ANF",
      card_type: "process",
      body: "JGA responds to reduced glomerular flow/pressure/GFR; ANF checks the renin-angiotensin mechanism.",
      table_data: table(["Regulator", "Source-backed role"], [
        ["JGA", "Cellular modification of DCT and afferent arteriole at contact; regulates GFR"],
        ["Renin", "Released by JG cells when glomerular blood flow, pressure or GFR falls"],
        ["Angiotensin II", "Vasoconstrictor; increases glomerular BP/GFR and activates aldosterone release"],
        ["Aldosterone", "Causes reabsorption of Na+ and water from distal tubule"],
        ["ANF", "Released by atria when blood flow increases; causes vasodilation and decreases BP"],
      ]),
      recall_data: recall("Which factor checks the renin-angiotensin mechanism?", "Atrial Natriuretic Factor (ANF)."),
      importance: 5,
      source_page: 78,
      sort_order: 18,
    }),
    card(chapterId, "excretory-disorders", {
      title: "Excretory Disorders",
      card_type: "comparison",
      body: "The source lists kidney disorders and treatment.",
      table_data: table(["Condition", "Source-backed recall"], [
        ["Uremia", "Accumulation of urea in blood due kidney malfunction; may lead renal failure"],
        ["Renal calculi", "Stone or insoluble crystallized salts such as oxalates in kidney"],
        ["Glomerulonephritis", "Inflammation of glomeruli"],
        ["Hemodialysis", "Removal of urea using a dialyzing unit or artificial kidney"],
        ["Kidney transplantation", "Ultimate method for acute renal failures; close relative minimizes rejection chance"],
      ]),
      recall_data: recall("What is uremia?", "Accumulation of urea in blood due to kidney malfunction."),
      importance: 5,
      source_page: 78,
      sort_order: 19,
    }),
    card(chapterId, "hemodialysis-flow", {
      title: "Hemodialysis Flow",
      card_type: "sequence",
      body: "The source describes hemodialysis as diffusion of nitrogenous wastes across a porous membrane.",
      table_data: table(["Step", "Event"], [
        ["1", "Blood is drained from an artery"],
        ["2", "Heparin is added and blood is pumped into dialyzing unit"],
        ["3", "Blood flows through coiled cellophane tube surrounded by dialyzing fluid"],
        ["4", "Dialyzing fluid has plasma-like composition except nitrogenous wastes"],
        ["5", "Nitrogenous wastes move out by concentration gradient"],
        ["6", "Purified blood returns through a vein after anti-heparin"],
      ]),
      recall_data: recall("Why do nitrogenous wastes move out during hemodialysis?", "The dialyzing fluid lacks nitrogenous wastes, creating a concentration gradient."),
      importance: 4,
      source_page: 78,
      sort_order: 20,
    }),
  ];
}

function locomotionCards(chapterId) {
  return [
    card(chapterId, "locomotion-vs-movement", {
      title: "Locomotion vs Movement",
      card_type: "concept",
      body: "Locomotion is voluntary movement resulting in change in location.",
      table_data: table(["Recall cue", "Source detail"], [
        ["Core distinction", "All locomotion are movements but all movements are not locomotion."],
        ["Paramoecium", "Cilia help in movement of food through cytopharynx and in locomotion."],
        ["Hydra", "Tentacles capture prey and help in locomotion."],
        ["Limbs", "Help change body postures and help locomotion."],
      ]),
      recall_data: recall("Are all movements locomotion?", "No. All locomotion are movements, but all movements are not locomotion."),
      importance: 5,
      source_page: 79,
      sort_order: 1,
    }),
    card(chapterId, "types-of-movement", {
      title: "Types of Movement",
      card_type: "classification",
      body: "The source lists amoeboid, ciliary, muscular and flagellar movement.",
      table_data: table(["Movement", "Mechanism", "Source examples"], [
        ["Amoeboid", "Pseudopodia formed by streaming of protoplasm; microfilaments help", "Amoeba, macrophages and leucocytes"],
        ["Ciliary", "By cilia", "Trachea removes dust/foreign substances; oviducts move ova"],
        ["Muscular", "By muscles", "Movement of limbs"],
        ["Flagellar", "By flagella", "Spermatozoa, sponge canal system water current, Euglena"],
      ]),
      recall_data: recall("Which movement type is used by macrophages and leucocytes?", "Amoeboid movement."),
      importance: 5,
      source_page: 79,
      sort_order: 2,
    }),
    card(chapterId, "muscle-properties", {
      title: "Human Muscular System",
      card_type: "fact",
      body: "Muscles are mesodermal in origin and constitute 40-50% of body weight.",
      table_data: table(["Property", "Source-backed recall"], [
        ["Origin", "Mesodermal"],
        ["Body weight", "40-50%"],
        ["Properties", "Excitability, contractility, extensibility and elasticity"],
      ]),
      recall_data: recall("What percentage of body weight is muscle in the source?", "40-50%."),
      importance: 4,
      source_page: 79,
      sort_order: 3,
    }),
    card(chapterId, "skeletal-smooth-cardiac", {
      title: "Skeletal vs Visceral vs Cardiac Muscle",
      card_type: "comparison",
      body: "Muscles are classified by location, striation, control and fatigue.",
      table_data: table(["Feature", "Skeletal", "Visceral", "Cardiac"], [
        ["Location", "Attached to skeleton", "In visceral organs", "In heart wall"],
        ["Striations", "Present", "Absent", "Present"],
        ["Control", "Voluntary", "Involuntary", "Involuntary"],
        ["Blood supply", "Rich", "Poor", "Rich"],
        ["Fatigue", "Fatigue muscle", "Non-fatigue", "Non-fatigue"],
        ["Nuclei", "Multinucleate", "Uninucleate", "Uninucleate"],
        ["Mitochondria", "More", "Less", "More"],
      ]),
      recall_data: recall("Which striated muscle is involuntary?", "Cardiac muscle.", [], [], ["Cardiac muscle is involuntary and non-fatigue in the source."]),
      importance: 5,
      source_page: 79,
      sort_order: 4,
    }),
    card(chapterId, "striated-muscle-structure", {
      title: "Structure of Striated Muscle",
      card_type: "classification",
      body: "Skeletal muscle is organized from fascicles to myofibrils.",
      table_data: table(["Level", "Source-backed recall"], [
        ["Muscle", "Made of muscle bundles or fascicles held by fascia"],
        ["Fascicle", "Contains many muscle fibres"],
        ["Muscle fibre", "Lined by sarcolemma enclosing sarcoplasm"],
        ["Myofibrils", "Myofilaments inside muscle fibre"],
        ["Sarcomere", "Region between two Z-lines; functional unit of muscle contraction"],
      ]),
      recall_data: recall("What is the functional unit of muscle contraction?", "Sarcomere."),
      importance: 5,
      source_page: 79,
      sort_order: 5,
    }),
    card(chapterId, "sarcomere-bands", {
      title: "A Band, I Band, H Zone and M Line",
      card_type: "comparison",
      body: "Band identity depends on actin and myosin distribution.",
      diagram_data: { type: "bio-sarcomere" },
      table_data: table(["Part", "Source-backed recall"], [
        ["I-band", "Light isotropic band; contains actin; bisected by Z-line"],
        ["A-band", "Dark anisotropic band; contains actin and myosin arranged parallel"],
        ["H band / H zone", "Lighter middle region of A-band formed only of myosin"],
        ["M-line", "Thin dark line through centre of H-zone"],
        ["Sarcomere", "Region between two Z-lines"],
      ]),
      recall_data: recall("Which band contains only actin in the source?", "I-band.", [], [], ["A-band contains actin and myosin; H-zone has only myosin."]),
      importance: 5,
      source_page: 79,
      sort_order: 6,
    }),
    card(chapterId, "actin-vs-myosin", {
      title: "Actin vs Myosin Filaments",
      card_type: "comparison",
      body: "The source details the protein composition of thin and thick filaments.",
      table_data: table(["Feature", "Actin filament", "Myosin filament"], [
        ["Main polymer", "Two F-actins forming a double helix", "Many meromyosins"],
        ["Monomer", "G-actin", "Meromyosin"],
        ["Associated proteins", "Tropomyosin and troponin", "HMM/cross arm and LMM tail"],
        ["Resting state", "Troponin subunit masks binding sites for myosin", "Globular head has ATPase activity, ATP binding and actin active sites"],
      ]),
      recall_data: recall("Which protein masks myosin binding sites on actin at rest?", "Troponin subunit."),
      importance: 5,
      source_page: 79,
      sort_order: 7,
    }),
    card(chapterId, "sliding-filament-sequence", {
      title: "Sliding Filament Mechanism",
      card_type: "sequence",
      body: "Muscle contraction occurs by sliding of thin filaments over thick filaments.",
      diagram_data: { type: "bio-sliding-filament" },
      table_data: table(["Step", "Source-backed event"], [
        ["1", "Impulse from CNS reaches neuromuscular junction via motor neuron"],
        ["2", "Acetylcholine generates action potential in sarcolemma"],
        ["3", "Ca2+ is released from sarcoplasmic cisternae into sarcoplasm"],
        ["4", "Ca binds troponin and unmasks myosin active sites on actin"],
        ["5", "Myosin head uses ATP hydrolysis energy to form cross bridge"],
        ["6", "Actin is pulled toward centre of A-band; sarcomere shortens"],
        ["7", "New ATP breaks cross bridge; cycle repeats"],
        ["8", "Ca2+ is pumped back and relaxation occurs"],
      ]),
      recall_data: recall("What exposes myosin binding sites during muscle contraction?", "Ca2+ binding to troponin.", ["This unmasks active sites on actin."]),
      importance: 5,
      source_page: 80,
      sort_order: 8,
    }),
    card(chapterId, "contraction-band-changes", {
      title: "Band Changes During Contraction",
      card_type: "neet_trap",
      body: "During contraction, Z-lines move inward and sarcomere shortens.",
      table_data: table(["Part", "Change in source"], [
        ["I-band", "Shortens"],
        ["A-band", "Retains length"],
        ["H-zone", "Disappears as actin filaments partially overlap"],
        ["Z-line", "Pulled inward"],
      ]),
      recall_data: recall("Which band retains length during contraction?", "A-band.", [], [], ["I-bands shorten; A-bands retain length."]),
      importance: 5,
      source_page: 80,
      sort_order: 9,
    }),
    card(chapterId, "red-vs-white-muscle", {
      title: "Red vs White Muscle Fibres",
      card_type: "comparison",
      body: "The source contrasts red aerobic and white muscle fibres.",
      table_data: table(["Feature", "Red muscles", "White muscle"], [
        ["Colour reason", "Red due to myoglobin", "White due to lesser myoglobin"],
        ["Mitochondria", "More", "Less"],
        ["Metabolism", "Aerobic", "Anaerobic"],
        ["Contraction", "Slow and sustained", "Fast contraction for short period"],
      ]),
      recall_data: recall("Which muscle fibre type has more myoglobin?", "Red muscle fibres."),
      importance: 4,
      source_page: 80,
      sort_order: 10,
    }),
    card(chapterId, "muscle-fatigue", {
      title: "Muscle Fatigue",
      card_type: "fact",
      body: "Repeated muscle activation leads to lactic acid accumulation.",
      table_data: table(["Cue", "Source-backed detail"], [
        ["Cause", "Accumulation of lactic acid"],
        ["Reason", "Anaerobic breakdown of glycogen in muscles"],
        ["Reaction time", "Varies in different muscles"],
      ]),
      recall_data: recall("What causes muscle fatigue in the source?", "Accumulation of lactic acid due to anaerobic breakdown of glycogen."),
      importance: 4,
      source_page: 80,
      sort_order: 11,
    }),
    card(chapterId, "skeletal-system-overview", {
      title: "Human Skeletal System Overview",
      card_type: "fact",
      body: "Human skeletal system has 206 bones and a few cartilages.",
      table_data: table(["Part", "Bone count / included structures"], [
        ["Total", "206 bones"],
        ["Axial skeleton", "80 bones: head, vertebral column, sternum and ribs"],
        ["Appendicular skeleton", "126 bones: limbs and girdles"],
      ]),
      recall_data: recall("How many bones are in the human skeletal system?", "206 bones."),
      importance: 5,
      source_page: 80,
      sort_order: 12,
    }),
    card(chapterId, "head-bones", {
      title: "Bones of Head",
      card_type: "classification",
      body: "Bones of head include skull, hyoid and ear ossicles.",
      table_data: table(["Part", "Source count/detail"], [
        ["Head bones", "29"],
        ["Skull", "22: cranial bones 8 and facial bones 14"],
        ["Hyoid", "1 U-shaped bone below buccal cavity"],
        ["Ear ossicles", "3 x 2 = 6: malleus, incus and stapes"],
        ["Skull articulation", "With atlas by 2 occipital condyles; dicondylic skull"],
      ]),
      recall_data: recall("What makes the human skull dicondylic in the source?", "It articulates with atlas using 2 occipital condyles."),
      importance: 5,
      source_page: 80,
      sort_order: 13,
    }),
    card(chapterId, "vertebral-column", {
      title: "Vertebral Column",
      card_type: "fact",
      body: "The vertebral column is formed of 26 vertebrae.",
      table_data: table(["Region", "Source count"], [
        ["Cervical", "7"],
        ["Thoracic", "12"],
        ["Lumbar", "5"],
        ["Sacral", "1 fused"],
        ["Coccygeal", "1 fused"],
      ]),
      recall_data: recall("How many cervical vertebrae are present in almost all mammals?", "7."),
      importance: 5,
      source_page: 80,
      sort_order: 14,
    }),
    card(chapterId, "ribs-types", {
      title: "Types of Ribs",
      card_type: "classification",
      body: "The source classifies 12 pairs of ribs into true, false and floating ribs.",
      table_data: table(["Rib type", "Pairs", "Attachment"], [
        ["True ribs", "First 7 pairs", "Attached to thoracic vertebrae and sternum by hyaline cartilage"],
        ["Vertebrochondral false ribs", "8th, 9th and 10th pairs", "Join the 7th rib by hyaline cartilage"],
        ["Floating ribs", "11th and 12th pairs", "No ventral connection with sternum or other ribs"],
      ]),
      recall_data: recall("Which ribs are floating ribs?", "11th and 12th pairs."),
      importance: 5,
      source_page: 81,
      sort_order: 15,
    }),
    card(chapterId, "appendicular-skeleton", {
      title: "Appendicular Skeleton Counts",
      card_type: "table",
      body: "Appendicular skeleton includes limb bones and girdles.",
      table_data: table(["Part", "Source count/detail"], [
        ["Forelimbs", "30 x 2 = 60: humerus, radius, ulna, carpals 8, metacarpals 5, phalanges 14"],
        ["Hindlimbs", "30 x 2 = 60: femur, patella, tibia, fibula, tarsals 7, metatarsals 5, phalanges 14"],
        ["Pectoral girdles", "2 x 2 = 4: clavicle and scapula"],
        ["Pelvic girdles", "2 coxal bones; each from ilium, ischium and pubis"],
      ]),
      recall_data: recall("Which cavity of the pelvic girdle articulates with the thigh bone?", "Acetabulum."),
      importance: 5,
      source_page: 81,
      sort_order: 16,
    }),
    card(chapterId, "joints-comparison", {
      title: "Fibrous vs Cartilaginous vs Synovial Joints",
      card_type: "comparison",
      body: "Joints are points of contact between bones, or between bones and cartilages.",
      table_data: table(["Joint type", "Movement", "Source example"], [
        ["Fibrous", "Immovable", "Sutures between skull bones"],
        ["Cartilaginous", "Slightly movable", "Joints between adjacent vertebrae"],
        ["Synovial", "Movable", "Fluid filled synovial cavity between articulating surfaces"],
      ]),
      recall_data: recall("Which joint type has a fluid-filled synovial cavity?", "Synovial joint."),
      importance: 5,
      source_page: 81,
      sort_order: 17,
    }),
    card(chapterId, "synovial-joint-types", {
      title: "Types of Synovial Joint",
      card_type: "examples",
      body: "Preserve the exact source examples for synovial joints.",
      table_data: table(["Joint", "Examples"], [
        ["Ball & socket", "Shoulder joint & hip joints"],
        ["Hinge joint", "Knee joint, elbow joint, phalanges joints"],
        ["Pivot joint", "Joints between atlas & axis"],
        ["Gliding joint", "Joints between carpals"],
        ["Saddle joint", "Joints between carpal & metacarpal of thumb"],
      ]),
      recall_data: recall("Which synovial joint occurs between atlas and axis?", "Pivot joint."),
      importance: 5,
      source_page: 81,
      sort_order: 18,
    }),
    card(chapterId, "muscular-skeletal-disorders", {
      title: "Muscular and Skeletal Disorders",
      card_type: "comparison",
      body: "The source lists six disorders with key cause or effect.",
      table_data: table(["Disorder", "Source-backed recall"], [
        ["Myasthenia gravis", "Autoimmune disorder affecting neuromuscular junction; fatigue, weakening and paralysis of skeletal muscles"],
        ["Muscular dystrophy", "Progressive degeneration of skeletal muscles; mostly genetic"],
        ["Tetany", "Rapid muscle spasm due to low Ca2+ in body fluid"],
        ["Arthritis", "Inflammation of joints"],
        ["Osteoporosis", "Age-related decreased bone mass and increased fractures; decreased estrogen common cause"],
        ["Gout", "Inflammation of joints due to accumulation of uric acid crystals"],
      ]),
      recall_data: recall("Which disorder affects the neuromuscular junction?", "Myasthenia gravis."),
      importance: 5,
      source_page: 81,
      sort_order: 19,
    }),
  ];
}

const biologyBatch5CardsBySlug = {
  "breathing-and-exchange-of-gases": breathingCards,
  "body-fluid-and-circulation": circulationCards,
  "excretory-products-and-their-elimination": excretionCards,
  "locomotion-and-movement": locomotionCards,
};

export function getBiologyBatch5Chapters() {
  return BIOLOGY_BATCH_5_CHAPTER_DEFINITIONS.map((item) => ({
    id: chapter(item.slug),
    subject_id: "neet-biology",
    title: item.title,
    slug: item.slug,
    sort_order: item.sort_order,
    source_page: item.source_page,
  }));
}

export function getBiologyBatch5Cards() {
  return BIOLOGY_BATCH_5_CHAPTER_DEFINITIONS.flatMap((item) => biologyBatch5CardsBySlug[item.slug](chapter(item.slug)));
}
