export const CHEMISTRY_INORGANIC_BATCH_1_CHAPTER_DEFINITIONS = [
  { title: "Periodic Table & Periodicity", slug: "periodic-table-periodicity", sort_order: 11 },
  { title: "Chemical Bonding", slug: "chemical-bonding", sort_order: 12 },
];

const chapter = (track, slug) => `${track}-chemistry-${slug}`;

const vars = {
  Z: { latex: "Z", symbol: "$Z$", meaning: "actual nuclear charge or atomic number" },
  sigma: { latex: "\\sigma", symbol: "$\\sigma$", meaning: "shielding or screening constant" },
  Zeff: { latex: "Z_{eff}", symbol: "$Z_{eff}$", meaning: "effective nuclear charge" },
  r: { latex: "r", symbol: "$r$", meaning: "radius or internuclear distance depending on context" },
  IE: { latex: "IE", symbol: "$IE$", meaning: "ionisation energy" },
  EA: { latex: "EA", symbol: "$EA$", meaning: "electron affinity" },
  chi: { latex: "\\chi", symbol: "$\\chi$", meaning: "electronegativity" },
  mu: { latex: "\\mu", symbol: "$\\mu$", meaning: "dipole moment" },
  q: { latex: "q", symbol: "$q$", meaning: "magnitude of charge" },
  d: { latex: "d", symbol: "$d$", meaning: "distance of separation" },
  Nb: { latex: "N_b", symbol: "$N_b$", meaning: "number of electrons in bonding molecular orbitals" },
  Na: { latex: "N_a", symbol: "$N_a$", meaning: "number of electrons in antibonding molecular orbitals" },
};

function card(chapterId, slug, payload) {
  return {
    id: `${chapterId}-${slug}`,
    chapter_id: chapterId,
    table_data: null,
    diagram_data: null,
    diagram_svg: null,
    is_active: true,
    ...payload,
  };
}

function periodicCards(chapterId) {
  return [
    card(chapterId, "periodic-table-development", {
      title: "Development of Periodic Table",
      card_type: "table",
      body: "The source opens with early periodic classifications and Mendeleev's periodic law.",
      formulas: [],
      variables: [],
      conditions: ["Mendeleev's periodic law: physical and chemical properties of elements are periodic functions of their atomic masses."],
      table_data: {
        columns: ["Classification", "Source-backed point"],
        rows: [
          ["Dobereiner's triads", "Similar elements arranged in groups of three."],
          ["Newland's law of octave", "Chemical properties were correlated with atomic masses."],
          ["Lother Meyer's classification", "Atomic masses were plotted against atomic volumes."],
          ["Mendeleev's table", "Properties were treated as periodic functions of atomic masses."],
        ],
      },
      importance: 3,
      source_page: 34,
      sort_order: 1,
    }),
    card(chapterId, "period-lengths", {
      title: "Mendeleev Period Lengths",
      card_type: "table",
      body: "The handbook lists period number, element count, and period name.",
      formulas: [],
      variables: [],
      conditions: [],
      table_data: {
        columns: ["Period", "Number of elements", "Called as"],
        rows: [
          ["1st, $n=1$", "2", "Very short period"],
          ["2nd, $n=2$", "8", "Short period"],
          ["3rd, $n=3$", "8", "Short period"],
          ["4th, $n=4$", "18", "Long period"],
          ["5th, $n=5$", "18", "Long period"],
          ["6th, $n=6$", "32", "Very long period"],
          ["7th, $n=7$", "19", "Incomplete period"],
        ],
      },
      importance: 4,
      source_page: 34,
      sort_order: 2,
    }),
    card(chapterId, "modern-law-periods-groups", {
      title: "Modern Periodic Law, Periods and Groups",
      card_type: "concept",
      body: "The source defines modern periodic law, periodicity, and the cause of periodicity.",
      formulas: [],
      variables: [],
      conditions: [
        "Modern periodic law: when elements are arranged in increasing atomic number, similar properties repeat after a regular interval.",
        "Periodicity is due to recurrence of similar valence-shell electronic configurations.",
        "Periods correspond to the principal quantum number of the valence shell.",
        "Groups contain elements with similar valence-shell electronic configuration.",
      ],
      importance: 5,
      source_page: 35,
      sort_order: 3,
    }),
    card(chapterId, "block-classification", {
      title: "Block Classification",
      card_type: "table",
      body: "The source classifies elements by block and gives the general electronic configurations.",
      formulas: [],
      variables: [],
      conditions: [],
      table_data: {
        columns: ["Block", "Groups/source position", "General electronic configuration"],
        rows: [
          ["s-block", "Groups 1 and 2; extreme left", "$[\\text{inert gas}]\\ ns^{1-2}$"],
          ["p-block", "Groups 13 to 18", "$[\\text{inert gas}]\\ ns^2np^{1-6}$"],
          ["d-block", "Groups 3 to 12", "$[\\text{inert gas}]\\ (n-1)d^{1-10}ns^{1-2}$"],
          ["f-block", "All f-block elements belong to 3rd group", "$(n-2)f^{1-14}(n-1)d^{0-1}ns^2$"],
        ],
      },
      importance: 5,
      source_page: 37,
      sort_order: 4,
    }),
    card(chapterId, "period-group-block-prediction", {
      title: "Predicting Period, Group and Block",
      card_type: "table",
      body: "The handbook gives rules for period, block, and group prediction from electronic configuration.",
      formulas: [],
      variables: [],
      conditions: [],
      table_data: {
        columns: ["Prediction", "Source-backed rule"],
        rows: [
          ["Period", "Principal quantum number of valence shell."],
          ["Block", "Type of subshell receiving the last electron."],
          ["s-block group", "Group no. = number of valence electrons."],
          ["p-block group", "Group no. = 10 + number of valence electrons."],
          ["d-block group", "Group no. = electrons in $(n-1)d$ subshell + electrons in valence shell."],
        ],
      },
      importance: 5,
      source_page: 37,
      sort_order: 5,
    }),
    card(chapterId, "metals-diagonal-relationship", {
      title: "Metals, Metalloids and Diagonal Relationship",
      card_type: "mixed",
      body: "The source lists metal/nonmetal placement, metalloids, and the diagonal relationship.",
      formulas: [],
      variables: [],
      conditions: [
        "Metals appear on the left hand side and comprise more than 78% of all known elements.",
        "Nonmetals are located at the top right hand side; their oxides are generally acidic.",
        "Metalloids listed: B, Si, Ge, As, Sb and Te.",
        "Diagonal relationship shown: Li-Na/Mg, Be-Mg/Al, B-Al/Si pattern from 2nd to 3rd period.",
      ],
      diagram_data: { type: "chem-diagonal-relationship" },
      importance: 4,
      source_page: 39,
      sort_order: 6,
    }),
    card(chapterId, "effective-charge-radius", {
      title: "Effective Nuclear Charge and Atomic Radius",
      card_type: "table",
      body: "The radius section defines effective nuclear charge and compares covalent, van der Waals, and metallic radii.",
      formulas: [
        { latex: "Z_{eff}=Z-\\sigma" },
        { latex: "r_n\\propto\\frac{1}{Z}" },
      ],
      variables: [vars.Z, vars.sigma, vars.Zeff, vars.r],
      conditions: ["Shielding effect can be determined using Slater's rules.", "Magnitude order shown: $r_{covalent}<r_{crystal}<r_{van\\ der\\ Waals}$."],
      table_data: {
        columns: ["Radius", "Source-backed definition"],
        rows: [
          ["Covalent radius", "One-half distance between nuclei of like atoms bonded by a single covalent bond."],
          ["van der Waals radius", "One-half internuclear distance between adjacent atoms in two nearest neighbouring molecules in solid state."],
          ["Metallic radius", "One-half distance between nuclei of adjacent metal atoms in the metallic crystal lattice."],
        ],
      },
      importance: 5,
      source_page: 39,
      sort_order: 7,
    }),
    card(chapterId, "radius-trends-ions", {
      title: "Radius Trends and Ionic Radius",
      card_type: "table",
      body: "The source compares variation in a period and group, then defines cation and anion radius behavior.",
      formulas: [],
      variables: [vars.Zeff],
      conditions: [],
      table_data: {
        sections: [
          {
            title: "Atomic radius trends",
            columns: ["Across a period", "Down a group"],
            rows: [
              ["Nuclear charge increases by one unit.", "Nuclear charge increases by more than one unit."],
              ["$Z_{eff}$ also increases.", "$Z_{eff}$ almost remains constant because screening increases."],
              ["Number of orbitals remains constant; radii decrease left to right.", "Number of orbitals increases; size increases top to bottom."],
            ],
          },
          {
            title: "Ionic radius",
            columns: ["Ion", "Source-backed behavior"],
            rows: [
              ["Cation", "Formed by loss of electrons; smaller than parent atom."],
              ["Anion", "Formed by gain of electrons; larger than parent atom."],
            ],
          },
        ],
      },
      importance: 5,
      source_page: 40,
      sort_order: 8,
    }),
    card(chapterId, "ionisation-electron-gain", {
      title: "Ionisation Energy and Electron Gain Enthalpy",
      card_type: "formula",
      body: "The source defines ionisation energy and electron gain enthalpy and lists their driving factors.",
      formulas: [
        { latex: "M(g)\\xrightarrow{IE_1}M^+(g)+e^-" },
        { latex: "M^+(g)+IE_2\\rightarrow M^{2+}(g)+e^-" },
        { latex: "IE_1<IE_2<IE_3<\\cdots" },
        { latex: "X(g)+e^-(g)\\rightarrow X^-(g)" },
        { latex: "\\text{Electron affinity}\\propto\\frac{1}{\\text{Atomic size}}" },
        { latex: "\\text{Electron affinity}\\propto Z_{eff}" },
        { latex: "\\text{Electron affinity}\\propto\\frac{1}{\\text{Screening effect}}" },
      ],
      variables: [vars.IE, vars.Zeff],
      conditions: ["Ionisation energy decreases with atomic size and increases with nuclear charge.", "Penetration order shown for the same energy level: $s>p>d>f$.", "Across a period electron gain enthalpy becomes more negative; down a group it becomes less negative."],
      importance: 5,
      source_page: 41,
      sort_order: 9,
    }),
    card(chapterId, "electronegativity-scales", {
      title: "Electronegativity Scales",
      card_type: "formula",
      body: "The source defines electronegativity and gives Pauling and Mulliken relations.",
      formulas: [
        { label: "Pauling scale, kcal/mol", latex: "\\Delta=X_A-X_B=0.208\\sqrt{E_{A-B}-\\sqrt{E_{A-A}\\times E_{B-B}}}" },
        { label: "Pauling scale, kJ/mol", latex: "\\Delta=X_A-X_B=0.1017\\sqrt{E_{A-B}-\\sqrt{E_{A-A}\\times E_{B-B}}}" },
        { label: "Mulliken scale", latex: "\\chi_M=\\frac{IE+EA}{2}" },
        { latex: "\\chi_P=1.35(\\chi_M)^{1/2}-1.37" },
      ],
      variables: [vars.chi, vars.IE, vars.EA],
      conditions: ["The source notes Mulliken's values are about 2.8 times larger than Pauling's values."],
      importance: 5,
      source_page: 42,
      sort_order: 10,
    }),
    card(chapterId, "reactivity-trends", {
      title: "Oxidation States and Reactivity Trends",
      card_type: "mixed",
      body: "The source closes the chapter with valence/oxidation-state periodicity and oxide/reactivity trends.",
      formulas: [],
      variables: [],
      conditions: [
        "Variable valence is particularly characteristic of transition elements and actinoids.",
        "In a group, basic nature of oxides increases or acidic nature decreases.",
        "In a period, oxides vary from basic to acidic.",
        "Oxides of Be, Al, Zn, Sn, As, Pb and Sb are amphoteric.",
      ],
      table_data: {
        columns: ["Across-period oxide examples", "Character shown"],
        rows: [
          ["$Na_2O$", "Strongly basic"],
          ["$MgO$", "Basic"],
          ["$Al_2O_3$", "Amphoteric"],
          ["$SiO_2$", "Weakly acidic"],
          ["$P_4O_{10}$", "Acidic"],
          ["$SO_3$", "Acidic"],
          ["$Cl_2O_7$", "Strongly acidic"],
        ],
      },
      diagram_data: { type: "chem-periodic-trends" },
      importance: 5,
      source_page: 42,
      sort_order: 11,
    }),
  ];
}

function bondingCards(chapterId) {
  return [
    card(chapterId, "ionic-bond-conditions", {
      title: "Ionic Bond Formation Conditions",
      card_type: "table",
      body: "The source says ionic compound formation depends on ion formation and ionic arrangement in the crystalline lattice.",
      formulas: [
        { latex: "M(g)\\rightarrow M^+(g)+e^-" },
        { latex: "X(g)+e^-\\rightarrow X^-(g)" },
        { latex: "M^+(g)+X^-(g)\\rightarrow MX(s)" },
      ],
      variables: [],
      conditions: [],
      table_data: {
        columns: ["Condition", "Source-backed statement"],
        rows: [
          ["Electronegativity difference", "Must be larger."],
          ["Ionisation enthalpy", "Electropositive element must be low."],
          ["Electron gain enthalpy", "Negative value for electronegative element should be high."],
          ["Lattice enthalpy", "For the ionic solid must be high."],
        ],
      },
      importance: 5,
      source_page: 43,
      sort_order: 1,
    }),
    card(chapterId, "lattice-enthalpy", {
      title: "Lattice Enthalpy",
      card_type: "formula",
      body: "The handbook defines lattice enthalpy and gives the factors affecting lattice energy.",
      formulas: [
        { latex: "\\text{Lattice energy}\\propto\\frac{1}{r_+ + r_-}" },
        { latex: "\\text{Lattice energy}\\propto Z_+,Z_-" },
      ],
      variables: [vars.r],
      conditions: ["$r_+ + r_-$ is inter-ionic distance.", "$Z_+$ and $Z_-$ are cation and anion charges in terms of electronic charge.", "Born-Haber cycle interrelates energy terms during formation of an ionic compound."],
      importance: 5,
      source_page: 43,
      sort_order: 2,
    }),
    card(chapterId, "ionic-properties-fajan", {
      title: "Ionic Properties and Fajan's Rule",
      card_type: "table",
      body: "The source lists properties of ionic compounds and factors that increase covalent character by polarization.",
      formulas: [],
      variables: [],
      conditions: ["Fajan's rule: greater polarization of anion in a molecule means more covalent character."],
      table_data: {
        sections: [
          {
            title: "Ionic compound properties",
            columns: ["Property", "Source-backed note"],
            rows: [
              ["Physical state", "At room temperature, ionic compounds exist in solid or solution phase, not gaseous state."],
              ["Isomerism", "Simple ionic compounds do not show isomerism; isomorphism is important."],
              ["Electrical conductivity", "Molten state and aqueous solutions conduct because ions are free to move."],
              ["Solubility", "Soluble in polar solvents like water with high dielectric constant."],
            ],
          },
          {
            title: "Covalent character factors",
            columns: ["Factor", "Relation with polarization"],
            rows: [
              ["Size of cation", "$\\propto\\frac{1}{\\text{polarisation}}$"],
              ["Size of anion", "$\\propto\\text{polarisation}$"],
              ["Charge on cation", "$\\propto\\text{polarisation}$"],
              ["Charge on anion", "$\\propto\\text{polarisation}$"],
              ["Pseudo inert gas configuration", "Listed as a factor for cation."],
            ],
          },
        ],
      },
      diagram_data: { type: "chem-fajan-polarization" },
      importance: 5,
      source_page: 44,
      sort_order: 3,
    }),
    card(chapterId, "covalent-coordinate-bonds", {
      title: "Covalent and Coordinate Bonds",
      card_type: "table",
      body: "The source defines covalent bond by electron sharing and coordinate bond by donation of an electron pair by one atom.",
      formulas: [],
      variables: [],
      conditions: [],
      table_data: {
        columns: ["Bond", "Source-backed definition or condition"],
        rows: [
          ["Covalent bond", "Formed by sharing valence electrons between atoms to form molecules."],
          ["Covalent condition", "Each bond is formed by sharing an electron pair between atoms."],
          ["Covalent condition", "Each combining atom contributes at least one electron to the shared pair."],
          ["Covalent condition", "Combining atoms attain outer-shell noble gas configuration through sharing."],
          ["Coordinate bond", "Contribution of an electron pair is made by one atom while sharing is done by both."],
          ["Coordinate examples", "$NH_4^+$, $O_3$, $H_2SO_4$, $HNO_3$, $H_3O^+$, $N_2O$, $[Cu(NH_3)_4]^{2+}$"],
        ],
      },
      importance: 5,
      source_page: 45,
      sort_order: 4,
    }),
    card(chapterId, "formal-charge-octet", {
      title: "Formal Charge and Octet Rule Limits",
      card_type: "formula",
      body: "The source gives the formal-charge expression and lists limitations of the octet rule.",
      formulas: [
        { latex: "\\text{F.C.}=\\text{valence electrons in free atom}-\\text{non-bonding electrons}-\\frac{1}{2}(\\text{bonding electrons})" },
      ],
      variables: [],
      conditions: [
        "Formal charges help select the lowest-energy Lewis structure.",
        "Octet-rule limitations listed: incomplete octet, odd-electron molecules, expanded octet, and other drawbacks.",
        "Examples shown include $LiCl$, $BeH_2$, $BCl_3$, $AlCl_3$, $BF_3$, $NO$, $NO_2$, $PF_5$, $SF_6$ and $H_2SO_4$.",
      ],
      importance: 5,
      source_page: 46,
      sort_order: 5,
    }),
    card(chapterId, "bond-energy-overlap", {
      title: "Bond Energy and Orbital Overlap",
      card_type: "mixed",
      body: "The source introduces orbital overlap through the covalent bond energy curve for hydrogen and then classifies sigma and pi bonds.",
      formulas: [
        { latex: "H_2(g)+435.8\\ kJ\\ mol^{-1}\\rightarrow H(g)+H(g)" },
      ],
      variables: [],
      conditions: ["Bond length shown for $H_2$ is 74 pm.", "Orbital overlap forms a covalent bond by pairing opposite-spin valence-shell electrons."],
      diagram_data: { type: "chem-overlap-sigma-pi" },
      importance: 4,
      source_page: 47,
      sort_order: 6,
    }),
    card(chapterId, "sigma-pi-bonds", {
      title: "Sigma and Pi Bonds",
      card_type: "table",
      body: "The source separates covalent bonds by type of orbital overlap.",
      formulas: [],
      variables: [],
      conditions: ["Sigma bond is stronger than pi bond because overlap is larger in sigma bonding."],
      table_data: {
        columns: ["Bond", "Source-backed overlap"],
        rows: [
          ["Sigma bond", "End-to-end or head-on overlap along the internuclear axis."],
          ["Sigma examples shown", "s-s, s-p, and p-p overlapping."],
          ["Pi bond", "p-orbitals overlap with axes parallel to each other and perpendicular to the internuclear axis."],
        ],
      },
      importance: 5,
      source_page: 48,
      sort_order: 7,
    }),
    card(chapterId, "vsepr-postulates", {
      title: "VSEPR Postulates",
      card_type: "formula",
      body: "The source lists VSEPR postulates and the order of electron-pair repulsion.",
      formulas: [
        { latex: "lp-lp>lp-bp>bp-bp" },
      ],
      variables: [],
      conditions: [
        "Shape depends on valence-shell electron pairs around the central atom.",
        "Electron pairs repel and occupy positions that minimize repulsion and maximize distance.",
        "Multiple bond is treated as a single super pair.",
        "VSEPR can be applied to any resonance structure representing a molecule.",
      ],
      importance: 5,
      source_page: 48,
      sort_order: 8,
    }),
    card(chapterId, "hybridisation-steric", {
      title: "Hybridisation and Steric Number",
      card_type: "mixed",
      body: "The handbook gives salient hybridisation features and the Gillespie steric-number rule.",
      formulas: [
        { latex: "\\text{Steric No.}=\\text{number of atoms bonded}+\\text{number of lone pairs left}" },
      ],
      variables: [],
      conditions: ["Number of hybrid orbitals equals the number of atomic orbitals hybridised.", "Hybrid orbitals are equivalent in energy and shape.", "Orbitals undergo hybridisation, not electrons."],
      table_data: {
        columns: ["Steric number", "Hybridisation", "Geometry"],
        rows: [
          ["2", "$sp$", "Linear"],
          ["3", "$sp^2$", "Trigonal planar"],
          ["4", "$sp^3$", "Tetrahedral"],
          ["5", "$sp^3d$", "Trigonal bipyramidal"],
          ["6", "$sp^3d^2$", "Octahedral"],
          ["7", "$sp^3d^3$", "Pentagonal bipyramidal"],
        ],
      },
      diagram_data: { type: "chem-vsepr-shapes" },
      importance: 5,
      source_page: 49,
      sort_order: 9,
    }),
    card(chapterId, "d-orbital-hybridisation", {
      title: "Hybridisation Involving d-Orbitals",
      card_type: "table",
      body: "The source lists which d-orbitals are involved in selected hybridisation types.",
      formulas: [],
      variables: [],
      conditions: [],
      table_data: {
        columns: ["Hybridisation", "Type of d-orbital involved"],
        rows: [
          ["$sp^3d$", "$d_{z^2}$"],
          ["$sp^3d^2$", "$d_{x^2-y^2}$ and $d_{z^2}$"],
          ["$sp^3d^3$", "$d_{x^2-y^2}$, $d_{z^2}$ and $d_{xy}$"],
          ["$dsp^2$", "$d_{x^2-y^2}$"],
        ],
      },
      importance: 4,
      source_page: 49,
      sort_order: 10,
    }),
    card(chapterId, "mot-principles-ordering", {
      title: "MOT Principles and O2/F2 Ordering",
      card_type: "mixed",
      body: "The source introduces MOT and gives the increasing energy order for molecular orbitals of $O_2$ and $F_2$.",
      formulas: [
        { latex: "\\sigma1s<\\sigma^*1s<\\sigma2s<\\sigma^*2s<\\sigma2p_z<(\\pi2p_x=\\pi2p_y)<(\\pi^*2p_x=\\pi^*2p_y)<\\sigma^*2p_z" },
      ],
      variables: [],
      conditions: ["Combining atomic orbitals must have same or nearly same energy, same symmetry about molecular axis, and maximum overlap."],
      diagram_data: { type: "chem-mo-energy" },
      importance: 5,
      source_page: 50,
      sort_order: 11,
    }),
    card(chapterId, "bond-order-magnetic", {
      title: "Bond Order, Bond Length and Magnetic Nature",
      card_type: "formula",
      body: "The source links MO occupancy to stability, bond type, bond length, and magnetic nature.",
      formulas: [
        { latex: "\\text{Bond order}=\\frac{1}{2}(N_b-N_a)" },
      ],
      variables: [vars.Nb, vars.Na],
      conditions: [
        "Positive bond order means stable molecule; negative or zero bond order means unstable molecule.",
        "Integral bond order values 1, 2 and 3 correspond to single, double and triple bonds.",
        "Bond length decreases as bond order increases.",
        "If all molecular orbitals are doubly occupied, the substance is diamagnetic.",
      ],
      importance: 5,
      source_page: 50,
      sort_order: 12,
    }),
    card(chapterId, "dipole-moment", {
      title: "Dipole Moment",
      card_type: "formula",
      body: "The dipole moment section gives the basic definition, Debye conversions, and resultant moment relation.",
      formulas: [
        { latex: "\\mu=q\\times d" },
        { latex: "1D=3.33564\\times10^{-30}\\ C m" },
        { latex: "1\\ Debye=1\\times10^{-18}\\ e.s.u.\\ cm" },
        { latex: "R=\\sqrt{P^2+Q^2+2PQ\\cos\\theta}" },
      ],
      variables: [vars.mu, vars.q, vars.d],
      conditions: ["A molecule has dipole moment if vector summation of individual moment vectors is non-zero."],
      diagram_data: { type: "chem-dipole-resultant" },
      importance: 5,
      source_page: 51,
      sort_order: 13,
    }),
    card(chapterId, "resonance", {
      title: "Resonance and Resonance Hybrid",
      card_type: "concept",
      body: "The source defines resonance and resonance hybrid using ozone and benzene-style structures.",
      formulas: [],
      variables: [],
      conditions: [
        "Resonance: two or more structures involving identical position of atom can be written for a compound.",
        "Resonance hybrid is the actual structure of all different possible structures written without violating maximum covalence rules.",
      ],
      importance: 4,
      source_page: 51,
      sort_order: 14,
    }),
    card(chapterId, "hydrogen-bonding", {
      title: "Hydrogen Bonding",
      card_type: "table",
      body: "The source gives H-bond conditions and separates intra- and intermolecular hydrogen bonding.",
      formulas: [],
      variables: [],
      conditions: ["Required for H-bond: F, O or N linked to H; smaller electronegative atom; lone pair on electronegative atom."],
      table_data: {
        columns: ["Type", "Source-backed note"],
        rows: [
          ["Intramolecular H-bonding", "Hydrogen atom is between two highly electronegative atoms within the same molecule."],
          ["Intramolecular condition", "Planar 5- or 6-membered ring with minimum strain during ring closure."],
          ["Intermolecular H-bonding", "Formed between two different molecules of same or different compounds."],
          ["HF chain", "Hydrogen bonds link F of one molecule with H of another, forming zig-zag chain $(HF)_n$."],
        ],
      },
      importance: 5,
      source_page: 52,
      sort_order: 15,
    }),
    card(chapterId, "intermolecular-metallic-special", {
      title: "Intermolecular, Metallic and Special Bonds",
      card_type: "table",
      body: "The source closes the core bonding section with weak intermolecular forces, metallic bond models, electron-deficient bonding, and back bonding.",
      formulas: [
        { latex: "\\text{van der Waals force}\\propto\\text{molecular mass}" },
        { latex: "\\text{van der Waals force}\\propto\\text{boiling point}" },
      ],
      variables: [],
      conditions: ["Back bonding increases bond strength and decreases bond length.", "Extent of back bonding in boron trihalides: $BF_3>BCl_3>BBr_3$."],
      table_data: {
        columns: ["Topic", "Source-backed item"],
        rows: [
          ["Intermolecular attractions", "Ion-dipole, dipole-dipole, ion-induced dipole, dipole-induced dipole, London/dispersion forces."],
          ["Metallic bond models", "Electron-sea model and band model."],
          ["Electron-deficient bonding", "3c-2e bonds in $B_2H_6$, $Al_2(CH_3)_6$, $BeH_2(s)$ and bridging metal carbonyls."],
          ["Back bonding", "One bonded atom has vacant orbitals and the other has non-bonded electron pair."],
        ],
      },
      importance: 4,
      source_page: 53,
      sort_order: 16,
    }),
  ];
}

function cardsForTrack(track) {
  return [
    ...periodicCards(chapter(track, "periodic-table-periodicity")),
    ...bondingCards(chapter(track, "chemical-bonding")),
  ];
}

export function getChemistryInorganicBatch1Chapters(track) {
  return CHEMISTRY_INORGANIC_BATCH_1_CHAPTER_DEFINITIONS.map((definition) => ({
    id: chapter(track, definition.slug),
    subject_id: `${track}-chemistry`,
    title: definition.title,
    slug: definition.slug,
    sort_order: definition.sort_order,
  }));
}

export function getChemistryInorganicBatch1Cards(track) {
  return cardsForTrack(track);
}
