export const BIOLOGY_BATCH_11_CHAPTER_DEFINITIONS = [
  { title: "Organisms and Population", slug: "organisms-and-population", sort_order: 33, source_page: 135 },
  { title: "Ecosystem", slug: "ecosystem", sort_order: 34, source_page: 140 },
  { title: "Biodiversity and Conservation", slug: "biodiversity-and-conservation", sort_order: 35, source_page: 144 },
];

const chapter = (slug) => `neet-biology-${slug}`;

function table(columns, rows) {
  return { columns, rows };
}

function recall(question, answer, key_points = [], examples = [], neet_traps = []) {
  return { recall_question: question, reveal_answer: answer, key_points, examples, neet_traps };
}

function card(chapterId, slug, payload) {
  return {
    id: `${chapterId}-${slug}`,
    chapter_id: chapterId,
    formulas: [],
    variables: [],
    conditions: [],
    table_data: null,
    diagram_data: null,
    diagram_svg: null,
    is_active: true,
    ...payload,
  };
}

function organismsPopulationCards(chapterId) {
  return [
    card(chapterId, "ecology-habitat-niche", {
      title: "Habitat and Niche",
      card_type: "comparison",
      body: "Ecology studies interactions among organisms and between organisms and the abiotic environment.",
      table_data: table(["Term", "Source-backed recall", "Examples/details"], [
        ["Ecology", "Study of interactions among organisms and between organism and physical environment", "Organisms, Populations, Communities and Biomes"],
        ["Habitat", "Different habitats form due to regional and local variations within a biome", "Rajasthan desert, rain-soaked Meghalaya forests, deep ocean trenches, thermal springs, compost pits and intestine microbes"],
        ["Niche", "Distinct role and position of an organism in its environment", "Each organism tolerates conditions and uses resources"],
      ]),
      recall_data: recall("What is niche?", "Distinct role and position of an organism in its environment.", [], [], ["Habitat is place/context; niche is role and position."]),
      importance: 5,
      source_page: 135,
      sort_order: 1,
    }),
    card(chapterId, "abiotic-factors", {
      title: "Major Abiotic Factors",
      card_type: "classification",
      body: "Temperature, water, light and soil shape organism distribution and survival.",
      table_data: table(["Factor", "Source-backed recall"], [
        ["Temperature", "Most ecologically relevant environmental factor; affects enzyme kinetics, basal metabolism and physiological functions"],
        ["Water", "Second most important factor; plant productivity and distribution depend on water"],
        ["Light", "Needed by plants for photosynthesis; photoperiod affects flowering, foraging, reproduction and migration"],
        ["Soil", "Composition, grain size, aggregation, pH, minerals and topography determine vegetation and animals"],
      ]),
      recall_data: recall("Which abiotic factor is called most ecologically relevant?", "Temperature."),
      importance: 5,
      source_page: 135,
      sort_order: 2,
    }),
    card(chapterId, "thermal-salinity-tolerance", {
      title: "Tolerance Terms",
      card_type: "comparison",
      body: "The source classifies organisms by temperature and salinity tolerance ranges.",
      table_data: table(["Pair", "Wide tolerance", "Narrow tolerance"], [
        ["Temperature", "Eurythermal", "Stenothermal"],
        ["Salinity", "Euryhaline", "Stenohaline"],
      ]),
      recall_data: recall("Which organisms tolerate a wide range of salinities?", "Euryhaline organisms."),
      importance: 5,
      source_page: 135,
      sort_order: 3,
    }),
    card(chapterId, "regulator-conformer", {
      title: "Regulator vs Conformer",
      card_type: "comparison",
      body: "Regulators maintain homeostasis; conformers change with surroundings.",
      table_data: table(["Feature", "Regulator", "Conformer"], [
        ["Internal environment", "Maintains stable internal environment by physiological and behavioural means", "Body temperature or osmotic concentration changes with surroundings"],
        ["Examples", "All birds and mammals, very few lower vertebrates and invertebrates", "99% animals and nearly all plants"],
        ["Cost", "Thermoregulation is energetically expensive, especially for small animals", "Avoids the cost of maintaining constant internal environment"],
        ["Graph cue", "Internal level stays steady", "Internal level follows external level"],
      ]),
      recall_data: recall("Why are very small animals rare in Polar Regions?", "They lose body heat very fast and must spend much energy to generate body heat.", [], [], ["Most animals are conformers, not regulators."]),
      importance: 5,
      source_page: 136,
      sort_order: 4,
    }),
    card(chapterId, "migration-suspend", {
      title: "Migration vs Suspension",
      card_type: "comparison",
      body: "Organisms may escape stress temporarily or suspend activity through dormant forms.",
      table_data: table(["Response", "Source-backed recall", "Examples"], [
        ["Migrate", "Move temporarily from stressful habitat to a hospitable area and return when stress is over", "Migratory birds from Siberia at Keolado National Park, Bharatpur"],
        ["Suspend in microbes/lower plants", "Thick walled spores survive unfavourable conditions and germinate under suitable conditions", "Bacteria, fungi and lower plants"],
        ["Suspend in higher plants", "Seeds and vegetative reproductive structures reduce metabolic activity during stress", "Germinate under favourable moisture and temperature"],
        ["Suspend in animals", "Dormancy or slowed development", "Hibernation, aestivation and diapause"],
      ]),
      recall_data: recall("Which suspended-development stage is listed for zooplanktons?", "Diapause."),
      importance: 5,
      source_page: 136,
      sort_order: 5,
    }),
    card(chapterId, "hibernation-aestivation-diapause", {
      title: "Hibernation, Aestivation and Diapause",
      card_type: "neet_trap",
      body: "The suspension examples differ by season or developmental state.",
      table_data: table(["Term", "Source-backed example"], [
        ["Hibernation", "Bears during winter"],
        ["Aestivation", "Some snails and fishes during summer"],
        ["Diapause", "Stage of suspended development of many zooplanktons in lakes and ponds"],
      ]),
      recall_data: recall("Which term applies to summer dormancy in some snails and fishes?", "Aestivation.", [], [], ["Hibernation is winter; aestivation is summer."]),
      importance: 5,
      source_page: 136,
      sort_order: 6,
    }),
    card(chapterId, "adaptations", {
      title: "Adaptations",
      card_type: "classification",
      body: "Adaptation is a morphological, physiological or behavioural attribute enabling survival and reproduction.",
      table_data: table(["Adaptation", "Source-backed examples"], [
        ["Kangaroo rat", "Internal fat oxidation gives water; concentrated urine uses minimal water"],
        ["Desert plants", "Thick cuticle, sunken stomata, CAM pathway and Opuntia leaves reduced to spines"],
        ["Allen's Rule", "Mammals from colder climates have shorter ears and limbs to reduce heat loss"],
        ["Aquatic mammals", "Seals have blubber below skin as insulator"],
        ["High altitude", "Acclimatization increases RBC and breathing rate and decreases haemoglobin binding capacity"],
        ["Behavioural", "Desert lizards bask in sun or move to shade; some species burrow into soil"],
      ]),
      recall_data: recall("Which desert plant example has leaves reduced to spines?", "Opuntia."),
      importance: 5,
      source_page: 136,
      sort_order: 7,
    }),
    card(chapterId, "population-attributes", {
      title: "Population Attributes",
      card_type: "comparison",
      body: "Population density changes through births, deaths and movement.",
      table_data: table(["Attribute", "Source-backed recall", "Effect on density"], [
        ["Population", "Group of individuals of same species in a geographical area, sharing or competing for resources and potentially reproducing", "Base unit"],
        ["Natality (B)", "Number of births in a population during a given period", "Increases"],
        ["Mortality (D)", "Number of deaths in a population during a given period", "Decreases"],
        ["Immigration (I)", "Individuals of same species coming into habitat from elsewhere", "Increases"],
        ["Emigration (E)", "Individuals leaving the habitat", "Decreases"],
        ["Sex ratio", "Population has a sex ratio, e.g. 60% females and 40% males", "Attribute"],
      ]),
      recall_data: recall("Which two factors increase population density?", "Natality and immigration.", [], [], ["Emigration decreases density; immigration increases it."]),
      importance: 5,
      source_page: 137,
      sort_order: 8,
    }),
    card(chapterId, "age-pyramids", {
      title: "Age Pyramids",
      card_type: "diagram",
      body: "Age pyramids show population age distribution and growth status.",
      diagram_data: { type: "bio-age-pyramids" },
      table_data: table(["Pyramid", "Source label"], [
        ["Expanding", "Growing"],
        ["Stable", "Stable"],
        ["Declining", "Declining"],
      ]),
      recall_data: recall("Which age-pyramid status indicates a growing population?", "Expanding."),
      importance: 5,
      source_page: 137,
      sort_order: 9,
    }),
    card(chapterId, "population-growth-equations", {
      title: "Population Growth Equations",
      card_type: "fact",
      body: "The source gives exact symbols for density change and exponential growth.",
      table_data: table(["Equation/value", "Source-backed meaning"], [
        ["Nt+1 = Nt + [(B + I) - (D + E)]", "Population density at time t + 1"],
        ["dN/dt = (b - d) x N", "Increase or decrease in N during unit time"],
        ["dN/dt = rN", "When (b - d) = r"],
        ["Nt = N0 ert", "Integral form of exponential growth equation"],
        ["e = 2.71828", "Base of natural logarithms"],
      ]),
      recall_data: recall("What does r represent in population growth?", "Intrinsic rate of natural increase."),
      importance: 5,
      source_page: 137,
      sort_order: 10,
    }),
    card(chapterId, "growth-models", {
      title: "Exponential vs Logistic Growth",
      card_type: "diagram",
      body: "Unlimited resources give a J-shaped curve; limited resources give a sigmoid curve.",
      diagram_data: { type: "bio-population-growth-curves" },
      table_data: table(["Feature", "Exponential growth", "Logistic growth"], [
        ["Resource condition", "Unlimited resources", "Limited resources"],
        ["Curve", "J-shaped curve", "Sigmoid curve"],
        ["Source name", "Exponential or geometric fashion", "Verhulst-Pearl Logistic Growth"],
        ["Equation", "dN/dt = rN", "dN/dt = rN((K - N) / K)"],
        ["K", "Not used", "Carrying capacity"],
      ]),
      recall_data: recall("Which growth curve occurs under unlimited resources?", "Exponential growth, J-shaped curve.", [], [], ["K represents carrying capacity in logistic growth."]),
      importance: 5,
      source_page: 138,
      sort_order: 11,
    }),
    card(chapterId, "r-values-life-history", {
      title: "r Values and Life History",
      card_type: "fact",
      body: "Life-history traits evolve under limited abiotic and biotic components of habitat.",
      table_data: table(["Cue", "Source-backed value/example"], [
        ["Norway rat r", "0.015"],
        ["Flour beetle r", "0.12"],
        ["Human population in India (1981) r", "0.0205"],
        ["Breed once", "Pacific salmon fish and bamboo"],
        ["Breed many times", "Most birds and mammals"],
        ["Many small offspring", "Oysters and pelagic fishes"],
        ["Few large offspring", "Birds and mammals"],
      ]),
      recall_data: recall("What r value is given for human population in India (1981)?", "0.0205."),
      importance: 5,
      source_page: 137,
      sort_order: 12,
    }),
    card(chapterId, "interaction-matrix", {
      title: "Population Interaction Matrix",
      card_type: "diagram",
      body: "Interspecific interactions are represented with +, - and 0 effects.",
      diagram_data: { type: "bio-interaction-matrix" },
      table_data: table(["Interaction", "Species A", "Species B", "Source meaning"], [
        ["Mutualism", "+", "+", "Both species benefitted"],
        ["Competition", "-", "-", "Both species harmed"],
        ["Predation", "+", "-", "Predator benefitted; prey harmed"],
        ["Parasitism", "+", "-", "Parasite benefitted; host harmed"],
        ["Commensalism", "+", "0", "One benefitted; other unaffected"],
        ["Amensalism", "-", "0", "One harmed; other unaffected"],
      ]),
      recall_data: recall("Which interaction is + and 0?", "Commensalism."),
      importance: 5,
      source_page: 138,
      sort_order: 13,
    }),
    card(chapterId, "predation", {
      title: "Predation",
      card_type: "concept",
      body: "Predators control prey populations and maintain species diversity.",
      table_data: table(["Cue", "Source-backed examples"], [
        ["Predator context", "Carnivores and herbivores are predators in a broad ecological context"],
        ["Phytophagous insects", "About 25% insects"],
        ["Prickly pear cactus", "Introduced in Australia in 1920's and later controlled by cactus-feeding predator moth"],
        ["Pisaster", "Removal caused extinction of over 10 invertebrate species within a year"],
        ["Prey defenses", "Camouflage, poisons, thorns and chemicals"],
        ["Chemical defenses", "Calotropis cardiac glycosides; nicotine, caffeine, quinine, strychnine and opium"],
      ]),
      recall_data: recall("Which starfish example shows predators maintain diversity?", "Pisaster."),
      importance: 5,
      source_page: 138,
      sort_order: 14,
    }),
    card(chapterId, "competition", {
      title: "Competition",
      card_type: "concept",
      body: "Competition lowers fitness of one species in the presence of another.",
      table_data: table(["Cue", "Source-backed detail"], [
        ["Definition", "Fitness of one species or r value is significantly lower in presence of another species"],
        ["Unrelated competitors", "Flamingoes and fishes compete for zooplankton in shallow South American lakes"],
        ["Interference competition", "Feeding efficiency reduced by inhibitory presence of another species even when resources are abundant"],
        ["Abingdon tortoise", "Extinct within a decade after goats were introduced in Galapagos Islands"],
        ["Connell experiment", "Removing Balanus allowed Chthamalus to colonize intertidal zone"],
        ["Gause principle", "Two closely related species competing for same resources cannot co-exist indefinitely in limited resources"],
        ["Resource partitioning", "Species divide limited resources by feeding times or foraging patterns"],
      ]),
      recall_data: recall("What is competitive release?", "Expansion of distributional range when competing species is removed."),
      importance: 5,
      source_page: 139,
      sort_order: 15,
    }),
    card(chapterId, "parasitism", {
      title: "Parasitism",
      card_type: "comparison",
      body: "Parasites harm hosts and often show specialized adaptations.",
      table_data: table(["Type/cue", "Source-backed recall", "Examples"], [
        ["Parasite adaptations", "Loss of sense organs, adhesive organs or suckers, loss of digestive system and high reproductive capacity", "Host-specific parasites co-evolve"],
        ["Ectoparasites", "Feed on external surface of host", "Lice on humans, ticks on dogs, copepods on marine fishes, Cuscuta on hedge plants"],
        ["Endoparasites", "Live inside host body at sites such as liver, kidney, lungs and RBC", "Life cycles are more complex"],
        ["Brood parasitism", "Parasitic birds lay eggs in host nest and let host incubate them", "Cuckoo and crow"],
        ["Female mosquito", "Not considered parasite in source", "Needs blood for reproduction, not as food"],
      ]),
      recall_data: recall("Why is female mosquito not considered a parasite in the source?", "It needs blood only for reproduction, not as food.", [], [], ["Cuscuta has no chlorophyll and derives nutrition from host."]),
      importance: 5,
      source_page: 139,
      sort_order: 16,
    }),
    card(chapterId, "commensalism-mutualism", {
      title: "Commensalism vs Mutualism",
      card_type: "comparison",
      body: "Commensalism benefits one without affecting the other; mutualism benefits both.",
      table_data: table(["Interaction", "Source-backed examples"], [
        ["Commensalism", "Orchid on mango branch; barnacles on whale; cattle egret with grazing cattle; clown fish with sea anemone"],
        ["Mutualism", "Lichen between fungus and algae/cyanobacteria; mycorrhizae between fungi and higher plant roots"],
        ["Fig and wasp", "Fig species pollinated only by partner wasp; fig offers developing seeds as larval food"],
        ["Ophrys sexual deceit", "Petal resembles female bee; male bee pseudocopulates and transfers pollen"],
      ]),
      recall_data: recall("Which interaction is shown by lichen?", "Mutualism."),
      importance: 5,
      source_page: 139,
      sort_order: 17,
    }),
  ];
}

function ecosystemCards(chapterId) {
  return [
    card(chapterId, "ecosystem-basics", {
      title: "Ecosystem Structure",
      card_type: "classification",
      body: "An ecosystem is a functional unit where organisms interact with each other and the physical environment.",
      table_data: table(["Component", "Source-backed recall"], [
        ["Terrestrial ecosystems", "Forest, grassland and desert"],
        ["Aquatic ecosystems", "Pond, lake, wetland, river and estuary"],
        ["Man-made ecosystems", "Crop fields and aquarium"],
        ["Global ecosystem", "Entire biosphere"],
        ["Stratification", "Vertical distribution of species at different levels; trees, shrubs, herbs and grasses in forest"],
      ]),
      recall_data: recall("What is stratification in an ecosystem?", "Vertical distribution of different species occupying different levels."),
      importance: 5,
      source_page: 140,
      sort_order: 1,
    }),
    card(chapterId, "pond-ecosystem", {
      title: "Pond as Ecosystem",
      card_type: "concept",
      body: "A pond is a shallow, simple, self-sustainable water body with all basic ecosystem components.",
      table_data: table(["Component/function", "Source-backed examples"], [
        ["Abiotic components", "Water and soil deposit"],
        ["Climatic conditions", "Solar input, temperature cycle and day-length"],
        ["Autotrophs", "Phytoplankton, some algae and floating, submerged and marginal plants"],
        ["Consumers", "Zooplankton, free swimming and bottom dwelling forms"],
        ["Decomposers", "Fungi, bacteria and flagellates"],
        ["Four functions", "Productivity, decomposition, energy flow and nutrient cycling"],
      ]),
      recall_data: recall("What are the four basic ecosystem functions?", "Productivity, decomposition, energy flow and nutrient cycling."),
      importance: 5,
      source_page: 140,
      sort_order: 2,
    }),
    card(chapterId, "productivity", {
      title: "GPP vs NPP",
      card_type: "comparison",
      body: "Primary productivity is biomass production by plants during photosynthesis.",
      table_data: table(["Term", "Source-backed recall"], [
        ["Primary production", "Biomass produced per unit area over time by plants during photosynthesis"],
        ["Productivity", "Rate of biomass production"],
        ["GPP", "Rate of production of organic matter during photosynthesis"],
        ["NPP", "Available biomass for consumption to heterotrophs"],
        ["Equation", "NPP = GPP - R"],
        ["Secondary productivity", "Rate of formation of new organic matter by consumers"],
      ]),
      recall_data: recall("What is the source equation for NPP?", "NPP = GPP - R.", [], [], ["GPP includes plant respiration losses; NPP is available biomass."]),
      importance: 5,
      source_page: 140,
      sort_order: 3,
    }),
    card(chapterId, "productivity-values", {
      title: "Productivity Values",
      card_type: "fact",
      body: "The source gives whole-biosphere and ocean NPP values.",
      table_data: table(["Cue", "Source-backed value"], [
        ["Annual NPP of whole biosphere", "About 170 billion tons dry weight of organic matter"],
        ["Ocean surface share", "About 70% of surface"],
        ["Ocean productivity", "Only 55 billion tons"],
        ["Primary production units", "Weight (g-2) or energy (kcal m-2)"],
        ["Productivity units", "g-2 yr-1 or (kcal m-2) yr-1"],
      ]),
      recall_data: recall("What annual NPP value is given for the whole biosphere?", "About 170 billion tons dry weight."),
      importance: 5,
      source_page: 140,
      sort_order: 4,
    }),
    card(chapterId, "decomposition-process", {
      title: "Decomposition Process",
      card_type: "process",
      body: "Decomposition breaks complex organic matter into inorganic substances.",
      diagram_data: { type: "bio-decomposition-flow" },
      table_data: table(["Step", "Source-backed event"], [
        ["Fragmentation", "Detritivores such as earthworm break detritus into smaller particles"],
        ["Leaching", "Water soluble inorganic nutrients go into soil horizon and precipitate as unavailable salts"],
        ["Catabolism", "Bacterial and fungal enzymes degrade detritus into simpler inorganic substances"],
        ["Humification", "Humus accumulates; resistant to microbial action and serves as nutrient reservoir"],
        ["Mineralization", "Microbes degrade humus and release inorganic nutrients"],
      ]),
      recall_data: recall("What is raw material for decomposition called?", "Detritus."),
      importance: 5,
      source_page: 140,
      sort_order: 5,
    }),
    card(chapterId, "decomposition-factors", {
      title: "Factors Affecting Decomposition",
      card_type: "comparison",
      body: "Detritus chemistry and climate control decomposition rate.",
      table_data: table(["Factor", "Slower", "Faster"], [
        ["Chemical composition", "Lignin and chitin rich detritus", "Nitrogen and water-soluble substances like sugars"],
        ["Climate", "Low temperature and anaerobiosis inhibit decomposition", "Warm and moist environment favours decomposition"],
      ]),
      recall_data: recall("Which detritus chemistry slows decomposition?", "Rich in lignin and chitin."),
      importance: 5,
      source_page: 140,
      sort_order: 6,
    }),
    card(chapterId, "energy-flow", {
      title: "Energy Flow",
      card_type: "process",
      body: "Energy decreases at successive trophic levels, and the number of GFC trophic levels is restricted by 10% law.",
      diagram_data: { type: "bio-trophic-energy" },
      table_data: table(["Cue", "Source-backed recall"], [
        ["Energy source", "Sun is the only source for all ecosystems except deep sea hydro-thermal ecosystem"],
        ["PAR", "Less than 50% of incident solar radiation is photosynthetically active radiation"],
        ["Plant capture", "Plants capture only 2-10% of PAR"],
        ["10% law", "Only 10% energy is transferred to each trophic level from the lower trophic level"],
        ["Standing crop", "Amount of living material in a trophic level at a given time"],
      ]),
      recall_data: recall("What percentage of energy is transferred between trophic levels according to 10% law?", "Only 10%."),
      importance: 5,
      source_page: 141,
      sort_order: 7,
    }),
    card(chapterId, "food-chain-types", {
      title: "Grazing vs Detritus Food Chain",
      card_type: "comparison",
      body: "The source distinguishes food chains by whether feeding begins with living plants or detritus.",
      table_data: table(["Feature", "Grazing Food Chain (GFC)", "Detritus Food Chain (DFC)"], [
        ["Beginning", "Primary consumer feeds on living plants", "Primary consumer feeds on dead organic matter"],
        ["Aquatic ecosystem", "Major conduit for energy flow", "Less emphasized"],
        ["Terrestrial ecosystem", "Less energy than DFC", "Much energy flows through DFC"],
        ["Connections", "May connect with DFC at some levels", "Some DFC organisms are prey to GFC animals"],
        ["Food web", "Interconnections of food chains", "Interconnections of food chains"],
      ]),
      recall_data: recall("Which food chain is major energy conduit in aquatic ecosystems?", "Grazing Food Chain."),
      importance: 5,
      source_page: 141,
      sort_order: 8,
    }),
    card(chapterId, "ecological-pyramids", {
      title: "Ecological Pyramids",
      card_type: "diagram",
      body: "Ecological pyramids represent food chains as number, biomass or energy pyramids.",
      diagram_data: { type: "bio-ecological-pyramids" },
      table_data: table(["Pyramid", "Source-backed recall", "Exception/trap"], [
        ["Number", "Grassland example upright", "Inverted when insects feed on a tree"],
        ["Biomass", "Shows sharp decrease in biomass at higher trophic levels", "In sea, inverted because fish biomass exceeds phytoplankton biomass"],
        ["Energy", "Primary producers convert only 1% of sunlight available to them into NPP", "Always upright because energy is lost as heat at each trophic level"],
      ]),
      recall_data: recall("Which ecological pyramid is always upright?", "Pyramid of energy.", [], [], ["Number and biomass can be inverted; energy is always upright."]),
      importance: 5,
      source_page: 141,
      sort_order: 9,
    }),
    card(chapterId, "pyramid-limitations", {
      title: "Ecological Pyramid Limitations",
      card_type: "neet_trap",
      body: "Pyramids simplify food chains and miss several real ecosystem features.",
      table_data: table(["Limitation", "Source-backed detail"], [
        ["Same species", "Does not consider same species belonging to two or more trophic levels"],
        ["Food web", "Assumes a simple food chain that never exists in nature and does not accommodate food web"],
        ["Saprophytes", "Saprophytes are not included"],
      ]),
      recall_data: recall("Are saprophytes included in ecological pyramids in the source?", "No."),
      importance: 5,
      source_page: 142,
      sort_order: 10,
    }),
    card(chapterId, "succession-basics", {
      title: "Ecological Succession",
      card_type: "concept",
      body: "Succession is gradual, slow and predictable change toward a climax community.",
      table_data: table(["Term", "Source-backed recall"], [
        ["Succession", "Change in species composition of an area leading to a climax community"],
        ["Climax community", "Community in equilibrium with environment"],
        ["Sere", "Entire sequence of communities that successively change in an area"],
        ["Seral stage", "Individual transitional community"],
        ["Pioneer species", "Species invading a bare area"],
        ["During succession", "Species diversity, number of species/organisms and total biomass increase"],
      ]),
      recall_data: recall("What are species invading a bare area called?", "Pioneer species."),
      importance: 5,
      source_page: 142,
      sort_order: 11,
    }),
    card(chapterId, "primary-secondary-succession", {
      title: "Primary vs Secondary Succession",
      card_type: "comparison",
      body: "Primary succession begins where no living organisms existed; secondary follows loss of existing organisms.",
      table_data: table(["Feature", "Primary succession", "Secondary succession"], [
        ["Starting area", "No living organisms ever existed", "Existing organisms are lost"],
        ["Examples", "Newly cooled lava, bare rock, newly created pond or reservoir", "Abandoned farm lands, burned or cut forests, flooded lands"],
        ["Soil/sediment", "Fertile soil must be formed", "Some soil or sediment is present"],
        ["Speed", "Very slow", "Faster than primary succession"],
      ]),
      recall_data: recall("Which succession is faster in the source?", "Secondary succession."),
      importance: 5,
      source_page: 142,
      sort_order: 12,
    }),
    card(chapterId, "hydrarch-xerarch", {
      title: "Hydrarch vs Xerarch Succession",
      card_type: "comparison",
      body: "Both plant succession paths lead toward mesic conditions.",
      table_data: table(["Type", "Starting condition", "Direction"], [
        ["Hydrarch succession", "Wetter areas", "Hydric to mesic conditions"],
        ["Xerarch succession", "Dry areas", "Xeric to mesic conditions"],
      ]),
      recall_data: recall("Which succession progresses from xeric to mesic conditions?", "Xerarch succession."),
      importance: 5,
      source_page: 142,
      sort_order: 13,
    }),
    card(chapterId, "succession-sequences", {
      title: "Succession Sequences",
      card_type: "sequence",
      body: "The source gives stage orders for primary succession on rocks and in water.",
      diagram_data: { type: "bio-succession-sequence" },
      table_data: table(["Succession", "Source-backed sequence"], [
        ["Primary succession on rocks", "Lichens -> small plants like bryophytes -> bigger plants -> forest"],
        ["Primary succession in water", "Phytoplankton -> rooted-submerged plants -> rooted-floating angiosperms -> free-floating plants -> reed-swamp -> marsh-meadow -> scrub -> trees"],
      ]),
      recall_data: recall("What pioneer species begins primary succession on rocks?", "Lichens."),
      importance: 5,
      source_page: 142,
      sort_order: 14,
    }),
    card(chapterId, "nutrient-cycling", {
      title: "Nutrient Cycling",
      card_type: "comparison",
      body: "Nutrients are recycled through ecosystem components and reservoirs.",
      table_data: table(["Term/cycle", "Source-backed recall"], [
        ["Standing state", "Amount of nutrients such as C, N, P and Ca in soil at a given time"],
        ["Nutrient cycling", "Movement of nutrient elements through various components of ecosystem"],
        ["Gaseous cycle", "Reservoir exists in atmosphere; examples Nitrogen and Carbon cycles"],
        ["Sedimentary cycle", "Reservoir located in Earth's crust; examples Sulphur and Phosphorus cycles"],
      ]),
      recall_data: recall("Which nutrient cycle type has reservoir in Earth's crust?", "Sedimentary cycle."),
      importance: 5,
      source_page: 142,
      sort_order: 15,
    }),
    card(chapterId, "carbon-phosphorus", {
      title: "Carbon vs Phosphorus Cycle",
      card_type: "comparison",
      body: "The source contrasts carbon and phosphorus by atmospheric input and gaseous exchange.",
      table_data: table(["Feature", "Carbon cycle", "Phosphorus cycle"], [
        ["Reservoir", "Atmosphere about 1%, organisms 49% dry weight, oceans 71% dissolved carbon, fossil fuel etc.", "Rock in the form of phosphates"],
        ["Annual fixation", "4 x 10^13 kg carbon fixed in biosphere through photosynthesis annually", "No annual fixation value given"],
        ["Atmospheric input", "Higher", "Much smaller"],
        ["Gaseous exchange", "There is gaseous exchange between organism and environment", "Gaseous exchange is negligible"],
      ]),
      recall_data: recall("What is the natural reservoir of phosphorus?", "Rock in the form of phosphates."),
      importance: 5,
      source_page: 143,
      sort_order: 16,
    }),
    card(chapterId, "ecosystem-services", {
      title: "Ecosystem Services",
      card_type: "fact",
      body: "Ecosystem services are products of ecosystem processes.",
      table_data: table(["Cue", "Source-backed detail"], [
        ["Forest services", "Purify air and water, mitigate droughts and floods, cycle nutrients, generate fertile soils, provide wildlife habitat, maintain biodiversity, pollinate crops and store carbon"],
        ["Robert Costanza", "Tried to put price tags on nature's life-support services"],
        ["Total value", "US $ 33 trillion a year"],
        ["Global GNP comparison", "Nearly twice global gross national product, US $ 18 trillion"],
        ["Soil formation", "About 50% of total cost"],
        ["Climate regulation and wildlife habitat", "About 6% each"],
      ]),
      recall_data: recall("What average annual value is given for ecosystem services?", "US $ 33 trillion a year."),
      importance: 5,
      source_page: 143,
      sort_order: 17,
    }),
  ];
}

function biodiversityCards(chapterId) {
  return [
    card(chapterId, "biodiversity-levels", {
      title: "Levels of Biodiversity",
      card_type: "comparison",
      body: "Biodiversity ranges from cellular macromolecules to biomes.",
      table_data: table(["Level", "Source-backed recall", "Example"], [
        ["Genetic diversity", "Diversity shown by a single species at genetic level", "Rauwolfia vomitoria potency and concentration of reserpine; India has >50,000 rice strains and 1000 mango varieties"],
        ["Species diversity", "Diversity at species level", "Western Ghats have greater amphibian species than Eastern Ghats"],
        ["Ecological diversity", "Diversity at ecosystem level", "India has deserts, rain forests, mangroves, coral reefs, wetlands, estuaries and alpine meadows"],
      ]),
      recall_data: recall("Who popularized the term biodiversity?", "Edward Wilson."),
      importance: 5,
      source_page: 144,
      sort_order: 1,
    }),
    card(chapterId, "global-india-biodiversity", {
      title: "Global and Indian Species Diversity",
      card_type: "fact",
      body: "The source uses IUCN 2004 and Robert May's estimates for species counts.",
      table_data: table(["Cue", "Source-backed value"], [
        ["IUCN 2004 described species", "More than 1.5 million"],
        ["Robert May global estimate", "About 7 million species"],
        ["Recorded so far", "Only 22% of total species"],
        ["Animals vs plants/fungi", "Animals above 70%; plants including Plantae and Fungi 22%"],
        ["Insects", "70% of animals; out of every 10 animals, 7 are insects"],
        ["India land area/species share", "2.4% land area and 8.1% species diversity"],
        ["India recorded species", "Nearly 45,000 plant species and twice as many animals"],
      ]),
      recall_data: recall("What percentage of world land area does India have in the source?", "2.4%."),
      importance: 5,
      source_page: 144,
      sort_order: 2,
    }),
    card(chapterId, "latitudinal-gradient", {
      title: "Latitudinal Gradient",
      card_type: "comparison",
      body: "Species diversity decreases from equator to poles.",
      table_data: table(["Region", "Source-backed value/detail"], [
        ["Tropics", "23.5° N to 23.5° S; more species than temperate or polar areas"],
        ["Colombia", "About 1400 bird species"],
        ["India", "> 1200 bird species"],
        ["New York (41° N)", "105 bird species"],
        ["Greenland (71° N)", "56 bird species"],
        ["Ecuador", "Up to 10 times vascular plant species compared to Midwest USA temperate forest"],
      ]),
      recall_data: recall("How does species diversity change from equator to poles?", "It decreases from the equator to the poles."),
      importance: 5,
      source_page: 144,
      sort_order: 3,
    }),
    card(chapterId, "amazon-biodiversity", {
      title: "Amazonian Rain Forest Diversity",
      card_type: "fact",
      body: "The source calls tropical Amazonian rain forest the greatest biodiversity on earth.",
      table_data: table(["Group", "Source-backed count"], [
        ["Plants", "> 40000 species"],
        ["Fishes", "3000 species"],
        ["Birds", "1300 species"],
        ["Mammals", "427 species"],
        ["Amphibians", "427 species"],
        ["Reptiles", "378 species"],
        ["Invertebrates", "> 1,25,000 species"],
      ]),
      recall_data: recall("Which rainforest is called greatest biodiversity on earth?", "Tropical Amazonian rain forest."),
      importance: 5,
      source_page: 144,
      sort_order: 4,
    }),
    card(chapterId, "species-area", {
      title: "Species-Area Relationship",
      card_type: "diagram",
      body: "Alexander von Humboldt found species richness increases with explored area up to a limit.",
      diagram_data: { type: "bio-species-area" },
      table_data: table(["Equation/value", "Source-backed meaning"], [
        ["S = CA^Z", "Species richness-area relationship"],
        ["S", "Species richness"],
        ["A", "Area"],
        ["C", "Y-intercept"],
        ["Z", "Slope of the line or regression coefficient"],
        ["Log S = log C + Z log A", "Straight line on logarithmic scale"],
        ["Small areas Z", "0.1 to 0.2"],
        ["Large areas Z", "0.6 to 1.2"],
        ["Frugivorous birds and mammals Z", "1.15"],
      ]),
      recall_data: recall("What does Z represent in species-area relationship?", "Slope of the line, or regression coefficient."),
      importance: 5,
      source_page: 144,
      sort_order: 5,
    }),
    card(chapterId, "importance-rivet", {
      title: "Species Diversity Importance",
      card_type: "concept",
      body: "More species stabilise ecosystem processes and productivity.",
      table_data: table(["Cue", "Source-backed recall"], [
        ["David Tilman", "Plots with more species show less year-to-year variation in total biomass"],
        ["Diversity effect", "Increased diversity contributes to higher productivity"],
        ["Rivet popper hypothesis", "Analogy proposed by Paul Ehrlich"],
        ["Rivet analogy", "Species are rivets in an airplane ecosystem"],
        ["Key species", "Loss of rivets on wings is more dangerous than loss from seats/windows"],
      ]),
      recall_data: recall("Who proposed rivet popper hypothesis?", "Paul Ehrlich."),
      importance: 5,
      source_page: 145,
      sort_order: 6,
    }),
    card(chapterId, "biodiversity-loss-stats", {
      title: "Biodiversity Loss Statistics",
      card_type: "fact",
      body: "The source uses IUCN Red List 2004 values for extinction and threat.",
      table_data: table(["Cue", "Source-backed value"], [
        ["Extinct in last 500 years", "784 species: 338 vertebrates, 359 invertebrates and 87 plants"],
        ["Examples", "Dodo, Quagga, Thylacine, Stellar's sea cow and 3 tiger subspecies Bali, Javan, Caspian"],
        ["Disappeared in last 20 years", "27 species"],
        ["Threatened", "More than 15,500 species"],
        ["Threat percentages", "12% birds, 23% mammals, 32% amphibians, 31% gymnosperms"],
        ["Current extinction rate", "100 - 1000 times faster than pre-human times"],
        ["Future trend", "Nearly 50% species might be extinct within next 100 years"],
      ]),
      recall_data: recall("How many species were extinct in the last 500 years according to IUCN Red List 2004?", "784 species."),
      importance: 5,
      source_page: 145,
      sort_order: 7,
    }),
    card(chapterId, "evil-quartet", {
      title: "The Evil Quartet",
      card_type: "diagram",
      body: "The source frames the four major causes of biodiversity loss as the Evil Quartet.",
      diagram_data: { type: "bio-evil-quartet" },
      table_data: table(["Cause", "Source-backed examples"], [
        ["Habitat loss and fragmentation", "Tropical rain forests lost from 14% to 6%; Amazon cut for soya beans or cattle grasslands"],
        ["Over-exploitation", "Stellar's sea cow and Passenger pigeon extinct"],
        ["Alien species invasions", "Nile Perch in Lake Victoria; Parthenium, Lantana, Eicchornia; African Catfish Clarias gariepinus"],
        ["Co-extinction", "Host extinction causes parasite extinction; plant-pollinator mutualism loss"],
      ]),
      recall_data: recall("What is the most important cause of biodiversity loss in the source?", "Habitat loss and fragmentation."),
      importance: 5,
      source_page: 145,
      sort_order: 8,
    }),
    card(chapterId, "conservation-reasons", {
      title: "Why Conserve Biodiversity?",
      card_type: "comparison",
      body: "The source gives narrowly utilitarian, broadly utilitarian and ethical arguments.",
      table_data: table(["Reason", "Source-backed recall"], [
        ["Narrowly utilitarian", "Economic benefits: food, firewood, fibre, construction material, industrial products and medicines"],
        ["Drug/medicine value", "More than 25% drugs are derived from plants; 25,000 plant species have medicinal value"],
        ["Broadly utilitarian", "Ecosystem services such as Amazon producing 20% of earth's atmospheric O2, pollination and aesthetic pleasures"],
        ["Ethical", "Every species has intrinsic value and humans have a moral duty to care for well-being"],
      ]),
      recall_data: recall("Which forest is called lung of the planet?", "Amazon forest."),
      importance: 5,
      source_page: 145,
      sort_order: 9,
    }),
    card(chapterId, "in-situ-ex-situ", {
      title: "In Situ vs Ex Situ Conservation",
      card_type: "diagram",
      body: "Biodiversity conservation is on site or off site.",
      diagram_data: { type: "bio-conservation-types" },
      table_data: table(["Feature", "In situ conservation", "Ex situ conservation"], [
        ["Meaning", "Conservation of genetic resources within natural or human-made ecosystems in which they occur", "Conservation of organisms outside their habitats"],
        ["Examples", "National Parks, Sanctuaries, Biosphere reserves, cultural landscapes and natural monuments", "Genetic resource centres, zoological parks, wildlife safari parks, botanical gardens, gene banks and cryopreservation"],
        ["National Park", "Strictly reserved for wildlife; private ownership, cultivation and grazing prohibited", "Not applicable"],
        ["Sanctuary", "Protection only to animals; timber/minor forest products/private ownership allowed if animals are not harmed", "Not applicable"],
      ]),
      recall_data: recall("Which conservation type occurs outside natural habitat?", "Ex situ conservation.", [], [], ["In situ is on site; ex situ is off site."]),
      importance: 5,
      source_page: 145,
      sort_order: 10,
    }),
    card(chapterId, "protected-areas-sacred-groves", {
      title: "Protected Areas and Sacred Groves",
      card_type: "fact",
      body: "The source gives India protected-area counts and sacred grove examples.",
      table_data: table(["Cue", "Source-backed detail"], [
        ["India protected-area counts", "14 Biosphere Reserves, 90 National Parks and 448 wildlife sanctuaries"],
        ["National park example", "Eravikulam National Park in Kerala"],
        ["Sanctuary example", "Periyar wildlife sanctuary in Kerala"],
        ["Sacred groves", "Forest fragments communally protected based on religious beliefs"],
        ["Sacred grove examples", "Khasi and Jaintia Hills, Aravalli Hills, Western Ghat regions of Karnataka and Maharashtra, Sarguja, Chanda and Bastar"],
      ]),
      recall_data: recall("How many National Parks does India have in the source?", "90 National Parks."),
      importance: 5,
      source_page: 145,
      sort_order: 11,
    }),
    card(chapterId, "hotspots-international", {
      title: "Hotspots and International Efforts",
      card_type: "classification",
      body: "Hotspots are rich, endemic and threatened regions; international efforts set conservation objectives.",
      table_data: table(["Cue", "Source-backed detail"], [
        ["Hotspots", "Regions with very high species richness, high endemism and high threat"],
        ["World hotspots", "34 hotspots"],
        ["Indian biodiversity regions", "Western Ghats & Sri Lanka, Indo-Burma and Himalaya"],
        ["Hotspot land area", "All hotspots together cover only < 2% of earth's land area"],
        ["Extinction reduction", "Protection of hotspots reduced ongoing extinctions by 30%"],
        ["Earth Summit/CBD", "Rio de Jeneiro, 1992; conservation, sustainable use and benefit sharing"],
        ["World Summit", "Johannesburg, South Africa, 2002; 190 countries pledged to reduce current biodiversity-loss rate"],
      ]),
      recall_data: recall("Name the three hotspots covering India's biodiversity regions in the source.", "Western Ghats & Sri Lanka, Indo-Burma and Himalaya."),
      importance: 5,
      source_page: 146,
      sort_order: 12,
    }),
  ];
}

const biologyBatch11CardsBySlug = {
  "organisms-and-population": organismsPopulationCards,
  ecosystem: ecosystemCards,
  "biodiversity-and-conservation": biodiversityCards,
};

export function getBiologyBatch11Chapters() {
  return BIOLOGY_BATCH_11_CHAPTER_DEFINITIONS.map((item) => ({
    id: chapter(item.slug),
    subject_id: "neet-biology",
    title: item.title,
    slug: item.slug,
    sort_order: item.sort_order,
    source_page: item.source_page,
  }));
}

export function getBiologyBatch11Cards() {
  return BIOLOGY_BATCH_11_CHAPTER_DEFINITIONS.flatMap((item) => biologyBatch11CardsBySlug[item.slug](chapter(item.slug)));
}
