export const BIOLOGY_BATCH_8_CHAPTER_DEFINITIONS = [
  { title: "Principles of Inheritance and Variation", slug: "principles-of-inheritance-and-variations", sort_order: 25, source_page: 107 },
  { title: "Molecular Basis of Inheritance", slug: "molecular-basis-of-inheritance", sort_order: 26, source_page: 147 },
  { title: "Evolution", slug: "evolution", sort_order: 27, source_page: 113 },
];

const chapter = (slug) => `neet-biology-${slug}`;

function table(columns, rows) {
  return { columns, rows };
}

function recall(question, answer, key_points = [], examples = [], neet_traps = []) {
  return { recall_question: question, reveal_answer: answer, key_points, examples, neet_traps };
}

function card(chapterId, slug, payload) {
  return {
    id: `${chapterId}-${slug}`,
    chapter_id: chapterId,
    formulas: [],
    variables: [],
    conditions: [],
    table_data: null,
    diagram_data: null,
    diagram_svg: null,
    is_active: true,
    ...payload,
  };
}

function inheritanceCards(chapterId) {
  return [
    card(chapterId, "genetics-terms", {
      title: "Genetics Core Terms",
      card_type: "concept",
      body: "Genetics studies inheritance, heredity and variation of characters.",
      table_data: table(["Term", "Source-backed recall"], [
        ["Genetics", "Study of inheritance, heredity and variation of characters; or study of genes and chromosomes"],
        ["Inheritance", "Transmission of characters from parents to progeny"],
        ["Variation", "Difference between parents and offspring"],
        ["Character", "A heritable feature, such as eye colour"],
        ["Trait", "Variant of a character, such as brown eye or blue eye"],
        ["Allele", "Alternative form of a gene, such as T and t for height"],
      ]),
      recall_data: recall("What is inheritance?", "Transmission of characters from parents to progeny."),
      importance: 5,
      source_page: 107,
      sort_order: 1,
    }),
    card(chapterId, "genotype-vs-phenotype", {
      title: "Genotype vs Phenotype",
      card_type: "comparison",
      body: "Phenotype is visible expression; genotype is genetic constitution.",
      table_data: table(["Term", "Source-backed meaning"], [
        ["Phenotype", "Physical expression of a character"],
        ["Genotype", "Genetic constitution of a character"],
      ]),
      recall_data: recall("Which term means genetic constitution of a character?", "Genotype.", [], [], ["Phenotype is physical expression."]),
      importance: 5,
      source_page: 107,
      sort_order: 2,
    }),
    card(chapterId, "homozygous-vs-heterozygous", {
      title: "Homozygous vs Heterozygous",
      card_type: "comparison",
      body: "Allelic similarity or dissimilarity determines homozygous and heterozygous conditions.",
      table_data: table(["Term", "Source-backed recall", "Examples"], [
        ["Homozygous", "Chromosome pair carries similar alleles of a gene; pure line or true breeding", "TT, tt, YY, yy"],
        ["Heterozygous", "Chromosome pair carries dissimilar alleles of a gene", "Tt, Yy"],
      ]),
      recall_data: recall("Which condition is also called pure line?", "Homozygous."),
      importance: 5,
      source_page: 107,
      sort_order: 3,
    }),
    card(chapterId, "mendel-pea-work", {
      title: "Mendel and Garden Pea",
      card_type: "fact",
      body: "Gregor Mendel conducted hybridization experiments on garden peas for seven years.",
      table_data: table(["Cue", "Source-backed detail"], [
        ["Scientist", "Gregor Mendel, Father of genetics"],
        ["Plant", "Garden pea, Pisum sativum"],
        ["Duration", "7 years, 1856-1863"],
        ["Cross steps", "Select contrasting plants, emasculate female parent, pollinate, collect and germinate seeds"],
      ]),
      recall_data: recall("Which plant did Mendel use for hybridization experiments?", "Garden pea, Pisum sativum."),
      importance: 5,
      source_page: 107,
      sort_order: 4,
    }),
    card(chapterId, "pea-contrasting-traits", {
      title: "Seven Pea Contrasting Traits",
      card_type: "fact",
      body: "Mendel selected seven pairs of true breeding pea varieties.",
      table_data: table(["Character", "Dominant", "Recessive"], [
        ["Stem height", "Tall", "Dwarf"],
        ["Flower colour", "Violet", "White"],
        ["Flower position", "Axial", "Terminal"],
        ["Pod shape", "Inflated", "Constricted"],
        ["Pod colour", "Green", "Yellow"],
        ["Seed shape", "Round", "Wrinkled"],
        ["Seed colour", "Yellow", "Green"],
      ]),
      recall_data: recall("In pea seed colour, which trait is dominant in the source?", "Yellow."),
      importance: 5,
      source_page: 107,
      sort_order: 5,
    }),
    card(chapterId, "monohybrid-cross", {
      title: "Monohybrid Cross",
      card_type: "diagram",
      body: "A monohybrid cross involves two plants differing in one character pair.",
      diagram_data: { type: "bio-monohybrid-cross" },
      table_data: table(["Stage", "Source-backed recall"], [
        ["Parent cross", "Tall pea plant crossed with dwarf pea plant"],
        ["F1", "Tt, tall"],
        ["F2 phenotypic ratio", "3 Tall : 1 Dwarf = 3:1"],
        ["F2 genotypic ratio", "1 Homozygous tall : 2 Heterozygous tall : 1 Homozygous dwarf = 1:2:1"],
      ]),
      recall_data: recall("What is the monohybrid phenotypic ratio?", "3 Tall : 1 Dwarf = 3:1."),
      importance: 5,
      source_page: 107,
      sort_order: 6,
    }),
    card(chapterId, "law-of-dominance", {
      title: "Law of Dominance",
      card_type: "concept",
      body: "Mendel's first law explains dominance in a dissimilar pair of factors.",
      table_data: table(["Statement point", "Source-backed wording"], [
        ["Control", "Characters are controlled by discrete units called factors"],
        ["Pairing", "Factors occur in pairs"],
        ["Dominance", "In a dissimilar pair, one member dominates the other"],
      ]),
      recall_data: recall("Which Mendelian law says factors occur in pairs?", "Law of dominance."),
      importance: 5,
      source_page: 108,
      sort_order: 7,
    }),
    card(chapterId, "law-of-segregation", {
      title: "Law of Segregation",
      card_type: "concept",
      body: "Alleles of a character pair segregate during gamete formation.",
      table_data: table(["Parent condition", "Gametes produced"], [
        ["Homozygous parent", "Similar gametes"],
        ["Heterozygous parent", "Two kinds of gametes"],
      ]),
      recall_data: recall("Which Mendelian law explains separation of alleles during gamete formation?", "Law of segregation."),
      importance: 5,
      source_page: 108,
      sort_order: 8,
    }),
    card(chapterId, "backcross-testcross", {
      title: "Backcross and Testcross",
      card_type: "comparison",
      body: "Testcross is used to find the unknown genotype of a character.",
      table_data: table(["Cross", "Source-backed recall"], [
        ["Backcross", "Cross between a hybrid and any parent"],
        ["Testcross", "Crossing an organism with dominant phenotype to a recessive individual"],
        ["Monohybrid test cross ratio", "1:1"],
        ["All violet result", "Unknown flower is homozygous dominant"],
        ["50% violet, 50% white", "Unknown flower is heterozygous"],
      ]),
      recall_data: recall("What is the monohybrid test cross ratio?", "1:1."),
      importance: 5,
      source_page: 107,
      sort_order: 9,
    }),
    card(chapterId, "dihybrid-cross", {
      title: "Dihybrid Cross",
      card_type: "diagram",
      body: "A dihybrid cross studies two pairs of contrasting characters.",
      diagram_data: { type: "bio-dihybrid-ratio" },
      table_data: table(["Cue", "Source-backed detail"], [
        ["Parent cross", "RRYY x rryy"],
        ["F1", "RrYy, round yellow"],
        ["Gametes", "RY, Ry, rY, ry"],
        ["F2 phenotypic ratio", "9 Round yellow : 3 Round green : 3 Wrinkled yellow : 1 Wrinkled green = 9:3:3:1"],
        ["F2 genotypic ratio", "1:2:1:2:4:2:1:2:1"],
      ]),
      recall_data: recall("What is Mendel's dihybrid phenotypic ratio?", "9:3:3:1."),
      importance: 5,
      source_page: 108,
      sort_order: 10,
    }),
    card(chapterId, "law-independent-assortment", {
      title: "Law of Independent Assortment",
      card_type: "concept",
      body: "Mendel's third law is based on results of dihybrid crosses.",
      table_data: table(["Cue", "Source-backed statement"], [
        ["Basis", "Dihybrid crosses"],
        ["Statement", "When two pairs of traits are combined in a hybrid, segregation of one pair of characters is independent of the other pair of characters"],
      ]),
      recall_data: recall("Which law is based on dihybrid crosses?", "Law of independent assortment."),
      importance: 5,
      source_page: 108,
      sort_order: 11,
    }),
    card(chapterId, "dominance-concept", {
      title: "Concept of Dominance",
      card_type: "concept",
      body: "Dominance depends on the functional effect of alleles in a heterozygote.",
      table_data: table(["Allele/product", "Source-backed outcome"], [
        ["Unmodified allele", "Generally dominant and represents original phenotype"],
        ["Modified allele", "Generally recessive"],
        ["Normal or less efficient enzyme", "May produce same phenotype as unmodified allele"],
        ["Non-functional enzyme or no enzyme", "Phenotype depends on functioning unmodified allele; modified allele becomes recessive"],
      ]),
      recall_data: recall("What kind of allele is generally recessive in the dominance concept?", "Modified allele."),
      importance: 4,
      source_page: 108,
      sort_order: 12,
    }),
    card(chapterId, "incomplete-dominance", {
      title: "Incomplete Dominance",
      card_type: "comparison",
      body: "Incomplete dominance produces an intermediate heterozygous phenotype.",
      table_data: table(["Cue", "Source-backed detail"], [
        ["Definition", "Heterozygous offspring shows intermediate character between parental characteristics"],
        ["Examples", "Snapdragon or dog flower, Antirrhinum sp.; Mirabilis jalapa or 4 O'clock plant"],
        ["Cross result", "Red x white produces pink"],
        ["Phenotypic ratio", "1 Red : 2 Pink : 1 White"],
        ["Genotypic ratio", "1 (RR) : 2 (Rr) : 1 (rr)"],
      ]),
      recall_data: recall("What phenotype appears in the heterozygote in snapdragon incomplete dominance?", "Pink flower.", [], [], ["Here phenotypic and genotypic ratios are same."]),
      importance: 5,
      source_page: 108,
      sort_order: 13,
    }),
    card(chapterId, "codominance-abo", {
      title: "Codominance and ABO",
      card_type: "comparison",
      body: "In codominance, both alleles of a gene are expressed in a hybrid.",
      table_data: table(["Cue", "Source-backed detail"], [
        ["Example", "ABO blood grouping in human"],
        ["Gene", "Gene I"],
        ["Alleles", "I^A, I^B and i"],
        ["I^A and I^B together", "Both express their own types of sugars"],
        ["i allele", "Does not produce any sugar"],
      ]),
      recall_data: recall("Which ABO genotype shows codominance?", "I^A I^B.", [], [], ["Codominance is not the same as multiple allelism."]),
      importance: 5,
      source_page: 108,
      sort_order: 14,
    }),
    card(chapterId, "abo-genotypes", {
      title: "ABO Genotype Table",
      card_type: "fact",
      body: "The source lists genotype-to-phenotype outcomes for ABO blood groups.",
      table_data: table(["Genotype", "Blood type"], [
        ["I^A I^A", "A"],
        ["I^A i", "A"],
        ["I^B I^B", "B"],
        ["I^B i", "B"],
        ["I^A I^B", "AB"],
        ["ii", "O"],
      ]),
      recall_data: recall("Which genotype gives blood group O?", "ii."),
      importance: 5,
      source_page: 108,
      sort_order: 15,
    }),
    card(chapterId, "multiple-alleles-polygenic-pleiotropy", {
      title: "Multiple Alleles, Polygenic Inheritance and Pleiotropy",
      card_type: "comparison",
      body: "These inheritance patterns extend beyond simple Mendelian dominance.",
      table_data: table(["Pattern", "Source-backed recall", "Examples"], [
        ["Multiple allelism", "Presence of more than two alleles of a gene to govern same character; only two alleles are present in an individual", "ABO blood grouping"],
        ["Polygenic inheritance", "Traits controlled by several genes; phenotype reflects additive contribution of alleles and environmental influence", "Human skin colour, human height"],
        ["Pleiotropy", "A single gene exhibits multiple phenotypic expressions", "Starch synthesis in pea, sickle cell anaemia, phenylketonuria"],
      ]),
      recall_data: recall("Which pattern has more than two alleles in a population?", "Multiple allelism."),
      importance: 5,
      source_page: 109,
      sort_order: 16,
    }),
    card(chapterId, "chromosomal-theory", {
      title: "Chromosomal Theory of Inheritance",
      card_type: "classification",
      body: "Sutton and Boveri connected chromosome behaviour with Mendelian factors.",
      diagram_data: { type: "bio-chromosomal-theory" },
      table_data: table(["Cue", "Source-backed detail"], [
        ["Year", "1902"],
        ["Proposed by", "Walter Sutton and Theodore Boveri"],
        ["Core idea", "Pairing and separation of chromosomes lead to segregation of factors they carry"],
        ["Statement", "Chromosomes are vehicles of heredity"],
        ["Morgan", "Proved chromosomal theory using fruit flies, Drosophila melanogaster"],
      ]),
      recall_data: recall("Who proposed chromosomal theory of inheritance?", "Walter Sutton and Theodore Boveri."),
      importance: 5,
      source_page: 109,
      sort_order: 17,
    }),
    card(chapterId, "drosophila-genetic-study", {
      title: "Drosophila as Genetic Material",
      card_type: "fact",
      body: "Morgan used fruit flies for genetic study because they are experimentally convenient.",
      table_data: table(["Source reason", "Detail"], [
        ["Medium", "Grow on simple synthetic medium"],
        ["Life cycle", "12-14 days"],
        ["Breeding", "Can be done throughout the year"],
        ["Progeny", "Hundreds of progenies per mating"],
        ["Sex distinction", "Male and female flies are easily distinguishable; male is smaller"],
        ["Variation", "Many hereditary variations visible with low power microscopes"],
      ]),
      recall_data: recall("What is Drosophila's life cycle duration in the source?", "12-14 days."),
      importance: 4,
      source_page: 109,
      sort_order: 18,
    }),
    card(chapterId, "linkage-vs-recombination", {
      title: "Linkage vs Recombination",
      card_type: "comparison",
      body: "Linked genes do not show independent assortment; recombination generates non-parental combinations.",
      diagram_data: { type: "bio-linkage-recombination" },
      table_data: table(["Term", "Source-backed recall"], [
        ["Linkage", "Physical association of two or more genes on a chromosome"],
        ["Recombination", "Generation of non-parental gene combinations due to independent assortment or crossing over"],
        ["Tight linkage", "Low recombination"],
        ["Loose linkage", "High recombination"],
      ]),
      recall_data: recall("Which linked genes show low recombination?", "Tightly linked genes."),
      importance: 5,
      source_page: 110,
      sort_order: 19,
    }),
    card(chapterId, "morgan-recombination-values", {
      title: "Morgan Recombination Values",
      card_type: "fact",
      body: "Morgan's Drosophila crosses showed deviation from 9:3:3:1 because of linkage.",
      table_data: table(["Gene pair", "Source-backed linkage/recombination"], [
        ["White eye and yellow body", "Very tightly linked; only 1.3% recombination"],
        ["White eye and miniature wing", "Loosely linked; 37.2% recombination"],
        ["Sturtevant", "Used recombination frequency to measure distance between genes and map chromosome positions"],
      ]),
      recall_data: recall("Which Morgan gene pair showed 1.3% recombination?", "White eye and yellow body."),
      importance: 5,
      source_page: 110,
      sort_order: 20,
    }),
    card(chapterId, "sex-determination-systems", {
      title: "Sex Determination Systems",
      card_type: "comparison",
      body: "Sex chromosomes involved in sex determination are called allosomes.",
      diagram_data: { type: "bio-sex-determination" },
      table_data: table(["System", "Source-backed pattern", "Examples"], [
        ["XX-XO", "Male heterogametic XO, female homogametic XX", "Many insects such as grasshopper"],
        ["XX-XY", "Male heterogametic X and Y, female homogametic X only", "Human and Drosophila"],
        ["ZZ-ZW", "Male homogametic ZZ, female heterogametic Z and W", "Birds"],
        ["Haplodiploid", "Females diploid from fertilised eggs, males haploid from unfertilised eggs", "Honeybee"],
      ]),
      recall_data: recall("Which sex-determination system shows female heterogamety?", "ZZ-ZW mechanism."),
      importance: 5,
      source_page: 110,
      sort_order: 21,
    }),
    card(chapterId, "human-sex-determination", {
      title: "Human Sex Determination",
      card_type: "fact",
      body: "In humans, the sperm determines whether the offspring is male or female.",
      table_data: table(["Cue", "Source-backed value/detail"], [
        ["Human chromosomes", "23 pairs: 22 pairs autosomes and 1 pair sex chromosomes"],
        ["Female", "XX; produces ovum with X chromosome"],
        ["Male", "XY; produces 50% sperms with X and 50% with Y"],
        ["Probability", "Equal probability of fertilisation with sperm carrying X or Y chromosome"],
      ]),
      recall_data: recall("In humans, which gamete determines sex of offspring?", "Sperm."),
      importance: 5,
      source_page: 110,
      sort_order: 22,
    }),
    card(chapterId, "honeybee-sex-determination", {
      title: "Honeybee Haplodiploidy",
      card_type: "fact",
      body: "Honeybee sex determination depends on number of chromosome sets.",
      table_data: table(["Individual", "Source-backed origin/chromosomes"], [
        ["Female queen or worker", "Fertilised egg; diploid, 32 chromosomes"],
        ["Male drone", "Unfertilised egg by parthenogenesis; haploid, 16 chromosomes"],
        ["Male sperm formation", "By mitosis"],
        ["Family relation trap", "Males do not have father and cannot have sons, but have grandfather and can have grandsons"],
      ]),
      recall_data: recall("How many chromosomes does a male honeybee have in the source?", "16 chromosomes."),
      importance: 5,
      source_page: 110,
      sort_order: 23,
    }),
    card(chapterId, "mutation-types", {
      title: "Mutation Types",
      card_type: "classification",
      body: "Mutation is a sudden heritable change in DNA sequence that changes genotype and phenotype.",
      table_data: table(["Type", "Source-backed recall", "Example/detail"], [
        ["Point mutation", "Change or substitution in a single base pair of DNA", "Sickle cell anaemia"],
        ["Frame-shift mutation", "Deletion or insertion of base pairs shifts DNA sequences", "Insertion/deletion"],
        ["Chromosomal abnormality", "Loss, gain or abnormal arrangement of chromosome/DNA segment", "Seen in cancer cells"],
        ["Mutagens", "Agents inducing mutation", "UV radiation, alpha, beta, gamma rays, X-ray, mustard gas, phenol, formalin"],
      ]),
      recall_data: recall("What mutation type is caused by substitution in a single base pair?", "Point mutation."),
      importance: 5,
      source_page: 111,
      sort_order: 24,
    }),
    card(chapterId, "mendelian-vs-chromosomal-disorders", {
      title: "Mendelian vs Chromosomal Disorders",
      card_type: "comparison",
      body: "Genetic disorders arise from changes in genes or chromosomes.",
      table_data: table(["Disorder class", "Source-backed cause", "Examples"], [
        ["Mendelian disorders", "Alteration or mutation in a single gene", "Haemophilia, colour blindness, sickle-cell anaemia, phenylketonuria, thalassemia, cystic fibrosis"],
        ["Chromosomal disorders", "Absence, excess or abnormal arrangement of one or more chromosomes", "Down's syndrome, Klinefelter's syndrome, Turner's syndrome"],
      ]),
      recall_data: recall("Which disorder class is caused by mutation in a single gene?", "Mendelian disorders."),
      importance: 5,
      source_page: 111,
      sort_order: 25,
    }),
    card(chapterId, "x-linked-disorders", {
      title: "Haemophilia and Colour Blindness",
      card_type: "comparison",
      body: "Both source disorders are sex-linked X-linked recessive disorders.",
      table_data: table(["Disorder", "Source-backed recall"], [
        ["Haemophilia", "Protein involved in blood clotting is affected; simple cut causes non-stop bleeding; Queen Victoria was a carrier"],
        ["Colour blindness", "Defect in red or green cone of eye; failure to discriminate red and green colour"],
        ["Colour blindness frequency", "8% of males and about 0.4% of females"],
        ["Carrier woman son", "Son of heterozygous woman has 50% chance of being colour blind"],
      ]),
      recall_data: recall("Which X-linked disorder affects blood clotting?", "Haemophilia."),
      importance: 5,
      source_page: 111,
      sort_order: 26,
    }),
    card(chapterId, "sickle-cell-anaemia", {
      title: "Sickle-Cell Anaemia",
      card_type: "neet_trap",
      body: "Sickle-cell anaemia is an autosome linked recessive disease caused by a point mutation.",
      table_data: table(["Cue", "Source-backed detail"], [
        ["Inheritance", "Autosome linked recessive"],
        ["Genotypes", "HbA HbA normal; HbA HbS carrier; HbS HbS affected"],
        ["Protein change", "Glutamic acid replaced by Valine at sixth position of beta-globin chain"],
        ["Codon change", "GAG to GUG at sixth codon of beta-globin gene"],
        ["RBC shape", "Biconcave disc changes to elongated sickle-like structure under low oxygen tension"],
      ]),
      recall_data: recall("Which amino acid replaces glutamic acid in sickle-cell anaemia?", "Valine.", [], [], ["Sickle-cell anaemia is qualitative; thalassemia is quantitative in the source."]),
      importance: 5,
      source_page: 111,
      sort_order: 27,
    }),
    card(chapterId, "phenylketonuria", {
      title: "Phenylketonuria",
      card_type: "fact",
      body: "Phenylketonuria is an autosomal recessive inborn error of metabolism.",
      table_data: table(["Cue", "Source-backed detail"], [
        ["Enzyme", "Phenyl alanine hydroxylase"],
        ["Normal conversion", "Phenylalanine to tyrosine"],
        ["Affected condition", "Enzyme is lacking"],
        ["Result", "Phenylalanine accumulates and converts into phenyl pyruvic acid and derivatives"],
        ["Effect", "Accumulation in brain causing mental retardation; excretion through urine"],
      ]),
      recall_data: recall("Which enzyme is deficient in phenylketonuria?", "Phenyl alanine hydroxylase."),
      importance: 5,
      source_page: 112,
      sort_order: 28,
    }),
    card(chapterId, "thalassemia", {
      title: "Thalassemia",
      card_type: "comparison",
      body: "Thalassemia is an autosome-linked recessive blood disease due to mutation or deletion.",
      table_data: table(["Type/cue", "Source-backed detail"], [
        ["Effect", "Reduced synthesis of alpha or beta globin chains of haemoglobin"],
        ["Alpha thalassemia", "Production of alpha globin chain affected; controlled by HBA1 and HBA2 on chromosome 16 of each parent"],
        ["Beta thalassemia", "Production of beta globin chain affected; controlled by HBB on chromosome 11 of each parent"],
        ["Thalassemia vs sickle-cell", "Thalassemia is quantitative; sickle-cell anaemia is qualitative"],
      ]),
      recall_data: recall("Which globin-chain disorder is quantitative in the source?", "Thalassemia."),
      importance: 5,
      source_page: 112,
      sort_order: 29,
    }),
    card(chapterId, "chromosomal-disorders", {
      title: "Chromosomal Disorders",
      card_type: "comparison",
      body: "Aneuploidy is gain or loss of chromosomes; polyploidy is increase in a whole set.",
      table_data: table(["Disorder", "Source-backed karyotype/cause", "Key features"], [
        ["Down's syndrome", "Additional chromosome 21; 45 A + XX or 45 A + XY, i.e. 47 chromosomes", "Short stature, small round head, broad flat face, simian crease, congenital heart disease"],
        ["Klinefelter's syndrome", "Additional X chromosome in male; 44 A + XXY, i.e. 47 chromosomes", "Gynaecomastia, sterile, mentally retarded"],
        ["Turner's syndrome", "Absence of one X chromosome in female; 44 A + X0, i.e. 45 chromosomes", "Sterile, rudimentary ovaries, lack of secondary sexual characters, dwarf, mentally retarded"],
      ]),
      recall_data: recall("Which syndrome has genetic constitution 44 A + XXY?", "Klinefelter's syndrome."),
      importance: 5,
      source_page: 112,
      sort_order: 30,
    }),
  ];
}

function molecularCards(chapterId) {
  return [
    card(chapterId, "genetic-material-overview", {
      title: "DNA and RNA as Genetic Material",
      card_type: "concept",
      body: "Nucleic acids are the building blocks of genetic material.",
      table_data: table(["Cue", "Source-backed recall"], [
        ["DNA", "Genetic material in most organisms"],
        ["RNA", "Genetic material in some viruses; mostly functions as messengers"],
        ["RNA world", "RNA was the first genetic material; acts as genetic material and catalyst"],
        ["DNA from RNA", "DNA evolved from RNA for stability"],
      ]),
      recall_data: recall("What is the genetic material in most organisms?", "DNA."),
      importance: 5,
      source_page: 147,
      sort_order: 1,
    }),
    card(chapterId, "nucleotide-vs-nucleoside", {
      title: "Nucleotide vs Nucleoside",
      card_type: "comparison",
      body: "Polynucleotides are polymers of nucleotides.",
      table_data: table(["Term", "Source-backed components/bond"], [
        ["Nucleoside", "Nitrogenous base linked to OH of 1' C pentose sugar through N-glycosidic linkage"],
        ["Nucleotide", "Phosphate group linked to OH of 5' C of a nucleoside through phosphoester linkage"],
        ["Dinucleotide", "Two nucleotides linked by 3'-5' phosphodiester bond"],
        ["Polynucleotide", "More nucleotides linked together"],
      ]),
      recall_data: recall("Which bond links two nucleotides in a dinucleotide?", "3'-5' phosphodiester bond."),
      importance: 5,
      source_page: 147,
      sort_order: 2,
    }),
    card(chapterId, "purines-vs-pyrimidines", {
      title: "Purines vs Pyrimidines",
      card_type: "comparison",
      body: "Nitrogen bases are purines or pyrimidines.",
      table_data: table(["Base group", "Bases", "Source-backed note"], [
        ["Purines", "Adenine and Guanine", "A and G"],
        ["Pyrimidines", "Cytosine, Thymine and Uracil", "Thymine only in DNA; Uracil only in RNA"],
      ]),
      recall_data: recall("Which nitrogen bases are purines?", "Adenine and Guanine.", [], [], ["Thymine is present only in DNA; Uracil only in RNA."]),
      importance: 5,
      source_page: 147,
      sort_order: 3,
    }),
    card(chapterId, "dna-double-helix", {
      title: "DNA Double Helix",
      card_type: "diagram",
      body: "Watson and Crick proposed the double helix model of DNA in 1953.",
      diagram_data: { type: "bio-dna-double-helix" },
      table_data: table(["Feature", "Source-backed detail"], [
        ["Chains", "Two polynucleotide chains coiled in right-handed fashion"],
        ["Backbone", "Sugar and phosphates"],
        ["Polarity", "Antiparallel: one strand 5'->3' and other 3'->5'"],
        ["Base pairing", "A=T with 2 hydrogen bonds; C=G with 3 hydrogen bonds"],
        ["Uniform distance", "Purine comes opposite pyrimidine"],
      ]),
      recall_data: recall("What base pairs with adenine in DNA?", "Thymine, with 2 hydrogen bonds."),
      importance: 5,
      source_page: 147,
      sort_order: 4,
    }),
    card(chapterId, "dna-dimensions", {
      title: "DNA Dimensions and Counts",
      card_type: "fact",
      body: "The source gives exact DNA structural values and genome sizes.",
      table_data: table(["Cue", "Source-backed value"], [
        ["Pitch of helix", "3.4 nm (34 A)"],
        ["Base pairs in each turn", "10"],
        ["Distance between adjacent base pairs", "0.34 nm (3.4 A)"],
        ["phi 174 bacteriophage", "5386 nucleotides"],
        ["Bacteriophage lambda", "48502 base pairs"],
        ["E. coli", "4.6 x 10^6 bp"],
        ["Haploid human DNA", "3.3 x 10^9 bp"],
        ["Length of human DNA", "2.2 m"],
      ]),
      recall_data: recall("What is the distance between adjacent DNA base pairs?", "0.34 nm (3.4 A)."),
      importance: 5,
      source_page: 147,
      sort_order: 5,
    }),
    card(chapterId, "chargaff-rule", {
      title: "Chargaff's Rule",
      card_type: "fact",
      body: "Erwin Chargaff's rule relates base proportions in DNA.",
      formulas: [{ label: "Chargaff relation", latex: "[A]+[G]=[T]+[C]\\;\\text{ or }\\;\\frac{[A]+[G]}{[T]+[C]}=1" }],
      table_data: table(["Base relation", "Source-backed detail"], [
        ["A and T", "Proportion of A is equal to T"],
        ["G and C", "Proportion of G is equal to C"],
      ]),
      recall_data: recall("If A is 30.7% in DNA, what is T according to Chargaff's rule?", "30.7%.", ["The source states A equals T and G equals C."]),
      importance: 5,
      source_page: 147,
      sort_order: 6,
    }),
    card(chapterId, "dna-packaging", {
      title: "DNA Packaging",
      card_type: "diagram",
      body: "Eukaryotic DNA wraps around histone octamers to form nucleosomes.",
      diagram_data: { type: "bio-nucleosome-packaging" },
      table_data: table(["Cue", "Source-backed recall"], [
        ["Prokaryotes", "Negatively charged DNA is held with positively charged proteins to form nucleoid"],
        ["Histones", "Positively charged basic proteins rich in lysines and arginines"],
        ["Histone octamer", "8 histones form histone octamer"],
        ["Nucleosome", "DNA wrapped around histone octamer"],
        ["Typical nucleosome", "Contains 200 bp"],
        ["Human nucleosomes", "3.3 x 10^7"],
      ]),
      recall_data: recall("How many histones form a histone octamer?", "8 histones."),
      importance: 5,
      source_page: 147,
      sort_order: 7,
    }),
    card(chapterId, "euchromatin-vs-heterochromatin", {
      title: "Euchromatin vs Heterochromatin",
      card_type: "comparison",
      body: "Chromatin has two forms in the source.",
      table_data: table(["Feature", "Euchromatin", "Heterochromatin"], [
        ["Packing", "Loosely packed", "Densely packed"],
        ["Activity", "Transcriptionally active", "Inactive"],
        ["Staining", "Stains light", "Stains dark"],
      ]),
      recall_data: recall("Which chromatin is transcriptionally active?", "Euchromatin."),
      importance: 5,
      source_page: 148,
      sort_order: 8,
    }),
    card(chapterId, "griffith-experiment", {
      title: "Griffith Transforming Principle",
      card_type: "process",
      body: "Griffith used mice and Streptococcus pneumoniae to show transformation.",
      diagram_data: { type: "bio-griffith-experiment" },
      table_data: table(["Injection", "Result"], [
        ["S-strain", "Mice die"],
        ["R-strain", "Mice live"],
        ["Heat-killed S-strain", "Mice live"],
        ["Heat-killed S-strain + live R-strain", "Mice die"],
      ]),
      recall_data: recall("What did Griffith call the transferred factor?", "Transforming principle."),
      importance: 5,
      source_page: 148,
      sort_order: 9,
    }),
    card(chapterId, "avery-macleod-mccarty", {
      title: "Avery, MacLeod and McCarty",
      card_type: "process",
      body: "They determined the biochemical nature of Griffith's transforming principle.",
      table_data: table(["Treatment", "Source-backed conclusion"], [
        ["Proteases and RNases", "Digestion of protein and RNA did not affect transformation"],
        ["DNase", "Digestion of DNA inhibited transformation"],
        ["Conclusion", "DNA caused transformation of R cells to S cells; DNA was the transforming principle"],
      ]),
      recall_data: recall("Which enzyme treatment inhibited transformation?", "DNase."),
      importance: 5,
      source_page: 148,
      sort_order: 10,
    }),
    card(chapterId, "hershey-chase", {
      title: "Hershey-Chase Experiment",
      card_type: "process",
      body: "The blender experiment proved DNA is the genetic material.",
      table_data: table(["Label", "Source-backed result"], [
        ["P32", "Radioactive DNA, because only DNA contains phosphorus"],
        ["S35", "Radioactive protein, because protein contains sulphur"],
        ["Radioactive DNA viruses", "Bacteria became radioactive; DNA entered bacteria"],
        ["Radioactive protein viruses", "Bacteria were not radioactive; proteins did not enter bacteria"],
      ]),
      recall_data: recall("Which isotope labelled DNA in Hershey-Chase?", "P32."),
      importance: 5,
      source_page: 148,
      sort_order: 11,
    }),
    card(chapterId, "dna-vs-rna-genetic-material", {
      title: "DNA vs RNA as Genetic Material",
      card_type: "comparison",
      body: "DNA is better for storage; RNA is better for transmission of genetic information.",
      table_data: table(["Feature", "DNA", "RNA"], [
        ["Stability/reactivity", "Less reactive and stable", "Highly reactive and unstable"],
        ["Strands", "Double stranded", "Single stranded"],
        ["Base", "Presence of thymine", "Presence of uracil"],
        ["Sugar", "Absence of 2'-OH", "Presence of 2'-OH"],
        ["Role", "Better for storage of genetic information", "Better for transmission; directly codes protein synthesis"],
      ]),
      recall_data: recall("Why is DNA better for storage in the source?", "It is more stable due to double stranded nature, thymine and absence of 2'-OH."),
      importance: 5,
      source_page: 148,
      sort_order: 12,
    }),
    card(chapterId, "central-dogma", {
      title: "Central Dogma",
      card_type: "diagram",
      body: "Francis Crick proposed central dogma of molecular biology.",
      diagram_data: { type: "bio-central-dogma" },
      table_data: table(["Flow", "Source-backed recall"], [
        ["Central dogma", "Genetic information flows from DNA -> RNA -> Protein"],
        ["Reverse transcription", "In some viruses, information flows from RNA to DNA"],
      ]),
      recall_data: recall("Who proposed central dogma?", "Francis Crick."),
      importance: 5,
      source_page: 149,
      sort_order: 13,
    }),
    card(chapterId, "semiconservative-replication", {
      title: "Semiconservative Replication",
      card_type: "concept",
      body: "Watson and Crick proposed semiconservative replication.",
      table_data: table(["Cue", "Source-backed recall"], [
        ["Replication", "Copying of DNA from parental DNA"],
        ["Model", "Parental DNA strands act as templates for new complementary strands"],
        ["After replication", "Each DNA molecule has one parental and one new strand"],
        ["Proved by", "Matthew Messelson and Franklin Stahl in 1958"],
      ]),
      recall_data: recall("What does semiconservative replication mean?", "Each new DNA molecule has one parental strand and one new strand."),
      importance: 5,
      source_page: 149,
      sort_order: 14,
    }),
    card(chapterId, "meselson-stahl", {
      title: "Messelson-Stahl Experiment",
      card_type: "process",
      body: "E. coli DNA shifted from heavy to light nitrogen showed semiconservative replication.",
      table_data: table(["Stage", "Source-backed result"], [
        ["15NH4Cl medium", "15N incorporated into newly synthesized heavy DNA"],
        ["After one generation or 20 minutes in 14NH4Cl", "DNA density intermediate or hybrid"],
        ["After second generation or 40 minutes", "Equal amounts of hybrid DNA and light DNA"],
        ["Taylor and colleagues, 1958", "Vicia faba radioactive thymidine experiments proved chromosome DNA also replicates semiconservatively"],
      ]),
      recall_data: recall("What appeared after one generation in Messelson-Stahl?", "Intermediate or hybrid DNA."),
      importance: 5,
      source_page: 149,
      sort_order: 15,
    }),
    card(chapterId, "replication-machinery", {
      title: "Replication Machinery",
      card_type: "sequence",
      body: "Replication starts at origin and proceeds at replication forks.",
      diagram_data: { type: "bio-replication-fork" },
      table_data: table(["Step/component", "Source-backed role"], [
        ["Origin or ori", "Point where DNA replication starts"],
        ["Replicon", "Unit of replication with one origin"],
        ["Helicase", "Breaks H-bonds so strands unwind and separate"],
        ["Replication fork", "Y-shaped structure formed by unwinding"],
        ["Primase", "Synthesizes a small RNA primer"],
        ["DNA polymerase", "Adds nucleotides and can proof-read"],
        ["DNA ligase", "Joins Okazaki fragments"],
      ]),
      recall_data: recall("Which enzyme joins Okazaki fragments?", "DNA ligase."),
      importance: 5,
      source_page: 149,
      sort_order: 16,
    }),
    card(chapterId, "leading-vs-lagging", {
      title: "Leading vs Lagging Strand",
      card_type: "comparison",
      body: "Both strands are synthesized in 5'->3' direction, but one is continuous and one discontinuous.",
      table_data: table(["Feature", "Leading strand", "Lagging strand"], [
        ["Synthesis", "Continuous stretch", "Small stretches or Okazaki fragments"],
        ["Direction", "5'->3'", "5'->3'"],
        ["Joining", "No Okazaki fragment joining described", "Okazaki fragments joined by DNA ligase"],
      ]),
      recall_data: recall("Which strand has Okazaki fragments?", "Lagging strand.", [], [], ["Both new strands are formed in 5'->3' direction in the source."]),
      importance: 5,
      source_page: 149,
      sort_order: 17,
    }),
    card(chapterId, "replication-values", {
      title: "Replication Values",
      card_type: "fact",
      body: "The source gives specific replication timing values.",
      table_data: table(["Cue", "Source-backed value"], [
        ["E. coli replication completion", "18 minutes"],
        ["E. coli rate", "2000 bp per second"],
        ["Eukaryotic DNA replication", "S-phase of cell cycle"],
        ["Failure of cell division after DNA replication", "Polyploidy"],
      ]),
      recall_data: recall("When does DNA replication occur in eukaryotes?", "S-phase of cell cycle."),
      importance: 5,
      source_page: 149,
      sort_order: 18,
    }),
    card(chapterId, "transcription-overview", {
      title: "Transcription Overview",
      card_type: "concept",
      body: "Transcription copies genetic information from one DNA strand into RNA.",
      table_data: table(["Cue", "Source-backed detail"], [
        ["Base pairing", "Adenine pairs with uracil instead of thymine"],
        ["Enzyme", "DNA-dependent RNA polymerase"],
        ["Polymerization", "Only in 5'->3' direction"],
        ["Template strand", "3'->5' strand; RNA is built from this"],
        ["Coding strand", "5'->3' strand; copied to RNA"],
      ]),
      recall_data: recall("Which strand acts as template during transcription?", "3'->5' template strand."),
      importance: 5,
      source_page: 149,
      sort_order: 19,
    }),
    card(chapterId, "transcription-unit", {
      title: "Transcription Unit",
      card_type: "diagram",
      body: "A transcription unit lies between initiation and termination sites.",
      diagram_data: { type: "bio-transcription-unit" },
      table_data: table(["Region", "Source-backed recall"], [
        ["Promoter", "Binding site for RNA polymerase; located towards 5'-end upstream"],
        ["Structural gene", "Region between promoter and terminator where transcription takes place"],
        ["Terminator", "Site where transcription stops; located towards 3'-end downstream"],
      ]),
      recall_data: recall("Where does RNA polymerase bind in a transcription unit?", "Promoter."),
      importance: 5,
      source_page: 150,
      sort_order: 20,
    }),
    card(chapterId, "monocistronic-vs-polycistronic", {
      title: "Monocistronic vs Polycistronic",
      card_type: "comparison",
      body: "Structural genes differ in eukaryotes and prokaryotes.",
      table_data: table(["Feature", "Monocistronic structural genes", "Polycistronic structural genes"], [
        ["Seen in", "Eukaryotes", "Prokaryotes"],
        ["Split genes", "Coding exons interrupted by introns", "No split genes"],
        ["mRNA", "Exons appear in processed mRNA; introns do not", "Multiple coding regions function together"],
      ]),
      recall_data: recall("Which sequences appear in processed mRNA?", "Exons."),
      importance: 5,
      source_page: 150,
      sort_order: 21,
    }),
    card(chapterId, "transcription-steps", {
      title: "Transcription Steps",
      card_type: "sequence",
      body: "In bacteria, one RNA polymerase catalyses synthesis of all types of RNA.",
      table_data: table(["Step", "Source-backed event"], [
        ["Initiation", "RNA polymerase binds promoter; sigma factor initiates RNA synthesis"],
        ["Elongation", "RNA chain synthesized in 5'->3' direction with ATP, GTP, UTP and CTP"],
        ["Termination", "rho factor binds RNA polymerase and terminates transcription"],
      ]),
      recall_data: recall("Which factor terminates bacterial transcription?", "rho factor."),
      importance: 5,
      source_page: 150,
      sort_order: 22,
    }),
    card(chapterId, "rna-polymerases-processing", {
      title: "Eukaryotic RNA Polymerases and Processing",
      card_type: "classification",
      body: "Eukaryotic primary transcripts contain exons and introns and require processing.",
      table_data: table(["Process/enzyme", "Source-backed detail"], [
        ["RNA polymerase I", "Transcribes rRNAs: 28S, 18S and 5.8S"],
        ["RNA polymerase II", "Transcribes hnRNA, precursor of mRNA"],
        ["RNA polymerase III", "Transcribes tRNA, 5S rRNA and snRNAs"],
        ["Splicing", "Introns removed and exons joined"],
        ["Capping", "Methyl guanosine triphosphate cap added to 5' end of hnRNA"],
        ["Tailing", "200-300 adenylate residues added at 3' end"],
      ]),
      recall_data: recall("Which RNA polymerase transcribes hnRNA?", "RNA polymerase II."),
      importance: 5,
      source_page: 150,
      sort_order: 23,
    }),
    card(chapterId, "genetic-code-features", {
      title: "Genetic Code Features",
      card_type: "classification",
      body: "A codon is a sequence of three bases determining a single amino acid.",
      table_data: table(["Feature", "Source-backed detail"], [
        ["Triplet", "Three-letter code; 64 codons"],
        ["Coding codons", "61 codons code for amino acids"],
        ["Stop codons", "UAA, UAG and UGA"],
        ["Universal", "UUU codes for Phenylalanine from bacteria to human, with exceptions in mitochondrial codons and some protozoans"],
        ["Comma less", "No punctuation between adjacent codons"],
        ["Non-overlapping", "Codons do not overlap"],
        ["Degenerate", "More than one codon can code one amino acid except AUG and UGG"],
        ["Unambiguous and specific", "One codon specifies only one amino acid"],
        ["AUG", "Codes Methionine and acts as initiator codon"],
      ]),
      recall_data: recall("Name the three stop codons.", "UAA, UAG and UGA."),
      importance: 5,
      source_page: 151,
      sort_order: 24,
    }),
    card(chapterId, "genetic-code-scientists", {
      title: "Genetic Code Scientists",
      card_type: "fact",
      body: "The source links several scientists to deciphering the genetic code.",
      table_data: table(["Scientist", "Source-backed contribution"], [
        ["George Gamow", "Suggested code should be made of 3 nucleotides for 20 amino acids"],
        ["Har Gobind Khorana", "Developed chemical method for synthesizing RNA molecules with defined base combinations"],
        ["Marshall Nirenberg", "Developed cell-free system for protein synthesis"],
        ["Severo Ochoa", "Polynucleotide phosphorylase used to polymerize RNA with defined sequences in template-independent manner"],
      ]),
      recall_data: recall("Who suggested the triplet nature of genetic code?", "George Gamow."),
      importance: 4,
      source_page: 150,
      sort_order: 25,
    }),
    card(chapterId, "types-of-rna", {
      title: "Types of RNA",
      card_type: "classification",
      body: "The source lists mRNA, rRNA and tRNA roles.",
      table_data: table(["RNA", "Source-backed role"], [
        ["mRNA", "Provides template for translation"],
        ["rRNA", "Structural and catalytic role during translation; 23S rRNA in bacteria acts as ribozyme"],
        ["tRNA", "Brings amino acids for protein synthesis and reads genetic code"],
      ]),
      recall_data: recall("Which RNA acts as adapter molecule?", "tRNA."),
      importance: 5,
      source_page: 151,
      sort_order: 26,
    }),
    card(chapterId, "trna", {
      title: "tRNA Structure",
      card_type: "fact",
      body: "tRNA is called adapter molecule because it links codon reading with amino-acid binding.",
      table_data: table(["Part", "Source-backed recall"], [
        ["Anticodon loop", "Has bases complementary to codon"],
        ["Amino acid acceptor end", "Amino acid binds here"],
        ["Ribosome binding loop", "Listed tRNA part"],
        ["Enzyme binding loop", "Listed tRNA part"],
        ["2-D structure", "Clover-leaf"],
        ["3-D structure", "Inverted L"],
        ["Stop codons", "No tRNAs for stop codons"],
      ]),
      recall_data: recall("What is the 2-D structure of tRNA like?", "Clover-leaf."),
      importance: 5,
      source_page: 151,
      sort_order: 27,
    }),
    card(chapterId, "translation-steps", {
      title: "Translation Steps",
      card_type: "sequence",
      body: "Translation polymerizes amino acids into a polypeptide according to mRNA codons.",
      diagram_data: { type: "bio-translation-flow" },
      table_data: table(["Step", "Source-backed event"], [
        ["Charging or aminoacylation", "Amino acid activated with ATP and linked to cognate tRNA by aminoacyl tRNA synthetase"],
        ["Initiation", "Small ribosomal subunit binds mRNA at start codon AUG; initiator tRNA binds P site"],
        ["Elongation", "Second aminoacyl tRNA binds A site and peptide bond forms by peptidyl transferase"],
        ["Termination", "Release factor binds stop codon and translation terminates"],
      ]),
      recall_data: recall("Which enzyme charges tRNA?", "Aminoacyl tRNA synthetase."),
      importance: 5,
      source_page: 151,
      sort_order: 28,
    }),
    card(chapterId, "transcription-vs-translation", {
      title: "Transcription vs Translation",
      card_type: "comparison",
      body: "Transcription makes RNA from DNA; translation makes polypeptide from mRNA.",
      table_data: table(["Feature", "Transcription", "Translation"], [
        ["Definition", "Copying genetic information from one DNA strand into RNA", "Polymerisation of amino acids to form polypeptide based on mRNA codons"],
        ["Main enzyme/machine", "DNA-dependent RNA polymerase", "Ribosome"],
        ["Direction/process", "RNA polymerized in 5'->3' direction", "Ribosome moves codon to codon"],
        ["Product", "RNA", "Polypeptide"],
      ]),
      recall_data: recall("Which process produces a polypeptide?", "Translation."),
      importance: 5,
      source_page: 151,
      sort_order: 29,
    }),
    card(chapterId, "lac-operon", {
      title: "Lac Operon",
      card_type: "diagram",
      body: "Lac operon controls lactose metabolism in E. coli and was proposed by Francois Jacob and Jacque Monod.",
      diagram_data: { type: "bio-lac-operon" },
      table_data: table(["Part", "Source-backed role"], [
        ["Regulatory or inhibitor i gene", "Codes repressor protein"],
        ["z gene", "Codes beta-galactosidase; hydrolyses lactose to galactose and glucose"],
        ["y gene", "Codes permease; increases permeability to beta-galactosides"],
        ["a gene", "Codes transacetylase"],
        ["No lactose", "Repressor binds operator and blocks RNA polymerase movement"],
        ["Lactose/allolactose present", "Inducer binds repressor, operator becomes free and transcription starts"],
      ]),
      recall_data: recall("What is the inducer in lac operon?", "Lactose or allolactose."),
      importance: 5,
      source_page: 152,
      sort_order: 30,
    }),
    card(chapterId, "gene-expression-levels", {
      title: "Gene Expression Levels",
      card_type: "classification",
      body: "In eukaryotes, gene expression can be regulated at multiple levels.",
      table_data: table(["Level", "Source-backed recall"], [
        ["Transcriptional level", "Formation of primary transcript"],
        ["Processing level", "Splicing, capping etc."],
        ["Transport level", "Transport of mRNA from nucleus to cytoplasm"],
        ["Translational level", "Formation of polypeptide"],
        ["Induction", "A set of genes is switched on when substrate is added"],
        ["Repression", "Genes to produce a metabolite are turned off when product is added"],
      ]),
      recall_data: recall("What is induction in gene expression?", "Switching on a set of genes to metabolize an added substrate."),
      importance: 4,
      source_page: 152,
      sort_order: 31,
    }),
    card(chapterId, "hgp-overview-goals", {
      title: "Human Genome Project",
      card_type: "fact",
      body: "HGP was the first mega project for sequencing nucleotides and mapping genes in the human genome.",
      table_data: table(["Cue", "Source-backed detail"], [
        ["Genome", "Entire DNA in haploid set of chromosomes"],
        ["Human genome packaging", "DNA packed in 23 chromosomes"],
        ["Human genome size", "About 3 x 10^9 bp"],
        ["Project duration", "1990-2003"],
        ["Coordinated by", "U.S. Department of Energy and National Institute of Health"],
        ["Goal", "Identify estimated genes and sequence 3 billion chemical base pairs of human DNA"],
      ]),
      recall_data: recall("What was the duration of HGP in the source?", "1990-2003."),
      importance: 5,
      source_page: 152,
      sort_order: 32,
    }),
    card(chapterId, "hgp-methodology", {
      title: "HGP Methodology",
      card_type: "sequence",
      body: "The source outlines sequencing from DNA isolation to computer alignment.",
      table_data: table(["Step/approach", "Source-backed recall"], [
        ["ESTs", "Focused on identifying all genes expressed as RNA"],
        ["Sequence annotation", "Sequencing coding and non-coding genome then assigning functions"],
        ["Procedure", "Isolate DNA -> random fragments -> clone in host using BAC/YAC -> sequence by automated DNA sequencers -> arrange overlapping regions -> align using computer programs"],
        ["Bioinformatics", "Application of computer science and information technology to biology and medicine"],
        ["Last sequenced chromosome", "Chromosome 1, May 2006"],
      ]),
      recall_data: recall("Which chromosome was last sequenced in HGP?", "Chromosome 1 in May 2006."),
      importance: 5,
      source_page: 153,
      sort_order: 33,
    }),
    card(chapterId, "hgp-salient-features", {
      title: "HGP Salient Features",
      card_type: "fact",
      body: "The source gives exact findings from the Human Genome Project.",
      table_data: table(["Feature", "Source-backed value/detail"], [
        ["Human genome bases", "3164.7 million nucleotide bases"],
        ["Genes", "About 30,000"],
        ["Average gene", "3000 bases"],
        ["Largest known human gene", "Dystrophin on X-chromosome, 2.4 million bases"],
        ["Similarity", "99.9% nucleotide bases are same in all people"],
        ["Difference", "0.1% or 3 x 10^6 bp makes every individual unique"],
        ["Protein-coding genome", "Less than 2%"],
        ["SNPs", "About 1.4 million locations"],
        ["Chromosomes", "Chromosome I has most genes, 2968; Y has fewest, 231"],
      ]),
      recall_data: recall("What percentage of human genome codes for proteins in the source?", "Less than 2%."),
      importance: 5,
      source_page: 153,
      sort_order: 34,
    }),
    card(chapterId, "dna-fingerprinting-basis", {
      title: "DNA Fingerprinting Basis",
      card_type: "concept",
      body: "DNA fingerprinting identifies similarities and differences in DNA fragments of two individuals.",
      table_data: table(["Cue", "Source-backed detail"], [
        ["Developed by", "Alec Jeffreys, 1985"],
        ["Satellite DNA", "Small peaks of repetitive DNA separated from bulk genomic DNA"],
        ["VNTR", "Variable number tandem repeats; tandemly repeated DNA sequence in many copy numbers"],
        ["Size of VNTR", "0.1 to 20 kb"],
        ["Specificity", "VNTR is specific from person to person"],
        ["Exception", "DNA fingerprint differs in everyone except monozygotic identical twins"],
      ]),
      recall_data: recall("What does VNTR stand for?", "Variable number tandem repeats."),
      importance: 5,
      source_page: 153,
      sort_order: 35,
    }),
    card(chapterId, "dna-fingerprinting-steps", {
      title: "DNA Fingerprinting Steps",
      card_type: "sequence",
      body: "The source presents DNA fingerprinting as Southern blotting technique.",
      table_data: table(["Step", "Source-backed event"], [
        ["1", "Isolation of DNA from cells, blood stains, semen stains, saliva, hair roots, bone, skin etc."],
        ["2", "Digestion of DNA by restriction endonucleases"],
        ["3", "Separation of DNA fragments by gel electrophoresis"],
        ["4", "Transfer DNA fragments to nitrocellulose or nylon membranes"],
        ["5", "Hybridization using radioactive labelled VNTR probe"],
        ["6", "Detection by autoradiography"],
      ]),
      recall_data: recall("Which probe is used in DNA fingerprinting?", "Radioactive labelled VNTR probe."),
      importance: 5,
      source_page: 153,
      sort_order: 36,
    }),
    card(chapterId, "dna-fingerprinting-applications", {
      title: "DNA Fingerprinting Applications",
      card_type: "examples",
      body: "PCR can increase sensitivity so DNA from a single cell is enough.",
      table_data: table(["Application", "Source-backed use"], [
        ["Forensic tool", "Solve paternity, rape, murder etc."],
        ["Medical", "Diagnosis of genetic diseases"],
        ["Evolutionary", "Determine phylogenetic status of animals"],
        ["Population", "Determine population and genetic diversities"],
      ]),
      recall_data: recall("Which technique increases DNA fingerprinting sensitivity?", "Polymerase chain reaction, PCR."),
      importance: 5,
      source_page: 154,
      sort_order: 37,
    }),
  ];
}

function evolutionCards(chapterId) {
  return [
    card(chapterId, "evolution-overview", {
      title: "Evolution Overview",
      card_type: "concept",
      body: "Evolution is an orderly change from one form to another.",
      table_data: table(["Cue", "Source-backed recall"], [
        ["Evolutionary Biology", "Study of evolutionary history of life forms"],
        ["Big Bang", "Universe originated about 20 billion years ago by a singular huge explosion"],
        ["Earth formed", "About 4.5 billion years ago"],
        ["Life appeared", "Almost four billion years ago"],
      ]),
      recall_data: recall("What is evolutionary biology?", "Study of evolutionary history of life forms."),
      importance: 5,
      source_page: 113,
      sort_order: 1,
    }),
    card(chapterId, "origin-of-life-theories", {
      title: "Origin of Life Theories",
      card_type: "comparison",
      body: "The source contrasts older origin theories with chemical evolution.",
      table_data: table(["Theory", "Source-backed recall"], [
        ["Spontaneous generation or abiogenesis", "Life came out of decaying and rotting matter; disproved by Louis Pasteur"],
        ["Biogenesis", "Life originates from pre-existing life; proposed by Francisco Redi, Spallanzani and Louis Pasteur"],
        ["Panspermia", "Units of life or spores transferred to different planets including earth"],
        ["Special creation", "Living things created by supernatural power"],
        ["Chemical evolution", "First life originated from non-living inorganic and organic molecules; proposed by Oparin and Haldane"],
      ]),
      recall_data: recall("Who proposed chemical evolution in the source?", "Oparin and Haldane."),
      importance: 5,
      source_page: 113,
      sort_order: 2,
    }),
    card(chapterId, "urey-miller", {
      title: "Urey-Miller Experiment",
      card_type: "process",
      body: "Urey and Miller experimentally supported chemical evolution.",
      diagram_data: { type: "bio-urey-miller" },
      table_data: table(["Cue", "Source-backed detail"], [
        ["Scientists", "Harold Urey and Stanley Miller"],
        ["Condition", "Primitive-earth-like high temperature, volcanic storms and reducing atmosphere"],
        ["Gases", "CH4, NH3, H2O and H2"],
        ["Temperature", "800°C"],
        ["Result", "Some amino acids were formed"],
        ["Similar experiments", "Formation of sugars, nitrogen bases, pigment and fats"],
      ]),
      recall_data: recall("What was formed in Urey-Miller experiment?", "Some amino acids."),
      importance: 5,
      source_page: 113,
      sort_order: 3,
    }),
    card(chapterId, "first-life-forms", {
      title: "First Life Forms",
      card_type: "fact",
      body: "The source gives a compact origin timeline.",
      table_data: table(["Time", "Source-backed event"], [
        ["3 billion years ago", "First non-cellular forms of life originated"],
        ["Non-cellular forms", "Self-replicating metabolic capsule containing RNA, proteins, polysaccharides etc."],
        ["2000 mya", "First cellular forms of life appeared"],
        ["Photosynthetic cells", "Some cells could release O2 as light reaction in photosynthesis"],
      ]),
      recall_data: recall("When did first non-cellular forms of life originate in the source?", "3 billion years ago."),
      importance: 5,
      source_page: 113,
      sort_order: 4,
    }),
    card(chapterId, "fossil-evidence", {
      title: "Fossil Evidence",
      card_type: "classification",
      body: "Fossils are remnants of life forms found in rocks and are written documents of evolution.",
      table_data: table(["Use of fossils", "Source-backed example/detail"], [
        ["Phylogeny", "Study evolutionary history; example horse evolution"],
        ["Connecting link", "Example Archaeopteryx"],
        ["Extinct animals", "Example dinosaurs"],
        ["Geological periods", "Analyse fossils in different sedimentary rock layers"],
      ]),
      recall_data: recall("Which source example is a connecting link?", "Archaeopteryx."),
      importance: 5,
      source_page: 113,
      sort_order: 5,
    }),
    card(chapterId, "homologous-vs-analogous", {
      title: "Homologous vs Analogous Organs",
      card_type: "comparison",
      body: "Homology indicates common ancestry; analogy indicates convergent evolution.",
      diagram_data: { type: "bio-homology-analogy" },
      table_data: table(["Feature", "Homologous organs", "Analogous organs"], [
        ["Structure/origin", "Fundamentally similar structure and origin", "Different structure and origin"],
        ["Function", "Different functions", "Similar function"],
        ["Evolution", "Divergent evolution", "Convergent evolution"],
        ["Examples", "Human hand, whale flipper, bat wing, cheetah foot; Bougainvillea thorn and Cucurbita tendril", "Insect wing and bird wing; octopus and mammal eyes; penguin and dolphin flipper; sweet potato and potato"],
      ]),
      recall_data: recall("Which organs indicate divergent evolution?", "Homologous organs.", [], [], ["Analogous organs indicate convergent evolution."]),
      importance: 5,
      source_page: 113,
      sort_order: 6,
    }),
    card(chapterId, "adaptive-radiation", {
      title: "Adaptive Radiation",
      card_type: "concept",
      body: "Adaptive radiation is evolution of different species from an ancestor in a geographical area starting from a point.",
      table_data: table(["Cue", "Source-backed detail"], [
        ["Type", "A type of divergent evolution"],
        ["Examples", "Darwin's finches in Galapagos Islands, Australian marsupials, placental mammals in Australia"],
        ["Multiple radiations in isolated area", "Results in convergent evolution"],
        ["Example", "Australian marsupials and placental mammals"],
      ]),
      recall_data: recall("Darwin's finches are an example of what?", "Adaptive radiation."),
      importance: 5,
      source_page: 114,
      sort_order: 7,
    }),
    card(chapterId, "marsupial-placental-comparison", {
      title: "Marsupial and Placental Mammal Pairings",
      card_type: "examples",
      body: "The source pairs Australian marsupials with placental mammals.",
      table_data: table(["Placental mammal", "Australian marsupial"], [
        ["Mole", "Marsupial mole"],
        ["Ant eater", "Numbat or ant eater"],
        ["Mouse", "Marsupial mouse"],
        ["Lemur", "Spotted cuscus"],
        ["Flying squirrel", "Flying phalanger"],
        ["Bobcat", "Tasmanian tiger cat"],
        ["Wolf", "Tasmanian wolf"],
      ]),
      recall_data: recall("Which marsupial corresponds to placental wolf?", "Tasmanian wolf."),
      importance: 4,
      source_page: 114,
      sort_order: 8,
    }),
    card(chapterId, "biochemical-embryological-evidence", {
      title: "Biochemical and Embryological Evidence",
      card_type: "comparison",
      body: "The source includes biochemical similarities and embryological observations.",
      table_data: table(["Evidence", "Source-backed recall"], [
        ["Biochemical", "Similarities in proteins, genes, biomolecules and metabolism indicate common ancestry"],
        ["Embryological", "Ernst Haeckel observed common features in vertebrate embryos absent in adults"],
        ["Gill slits", "All vertebrate embryos, including human, develop vestigial gill slits behind head; functional only in fish"],
        ["Rejection", "Karl Ernst von Baer rejected Haeckel's proposal; embryos never pass through adult stages of other animals"],
      ]),
      recall_data: recall("Who rejected Haeckel's embryological proposal?", "Karl Ernst von Baer."),
      importance: 4,
      source_page: 114,
      sort_order: 9,
    }),
    card(chapterId, "industrial-melanism", {
      title: "Industrial Melanism",
      card_type: "process",
      body: "Industrial melanism is source evidence for natural selection.",
      table_data: table(["Period", "Source-backed observation/reason"], [
        ["Before industrialization, 1850s", "More white-winged moths, Biston betularia, than dark melanised moths"],
        ["Reason before", "White lichens covered trees; white moths survived, dark moths picked by predators"],
        ["After industrialization, 1920", "More dark-winged moths and fewer white-winged moths developed"],
        ["Reason after", "Tree trunks darkened by smoke and soot; no lichens; dark moths survived"],
      ]),
      recall_data: recall("Which moth form increased after industrialization?", "Dark-winged or melanised moths."),
      importance: 5,
      source_page: 114,
      sort_order: 10,
    }),
    card(chapterId, "lamarck-vs-darwin", {
      title: "Lamarckism vs Darwinism",
      card_type: "comparison",
      body: "The source contrasts inheritance of acquired characters with natural selection.",
      table_data: table(["Theory", "Source-backed recall", "Examples/influence"], [
        ["Lamarckism", "Evolution by inheritance of acquired characters developed by use and disuse of organs", "Long neck of giraffe; disappearance of limbs in snakes"],
        ["Darwinism", "Theory of natural selection", "Based on H.M.S. Beagle voyage; influenced by Thomas Malthus"],
        ["Wallace", "Came to similar conclusions as Darwin", "Malay Archepelago"],
      ]),
      recall_data: recall("Which theory is based on use and disuse of organs?", "Lamarckism."),
      importance: 5,
      source_page: 114,
      sort_order: 11,
    }),
    card(chapterId, "natural-selection-flow", {
      title: "Natural Selection Flow",
      card_type: "process",
      body: "Natural selection selects organisms with better favourable and heritable variation.",
      diagram_data: { type: "bio-natural-selection-flow" },
      table_data: table(["Fact", "Source-backed recall"], [
        ["Heritable minor variations", "Beneficial or harmful to organisms"],
        ["Overproduction", "Population size grows exponentially due to maximum reproduction"],
        ["Limited resources", "Resources do not increase with population size"],
        ["Struggle for existence", "Competition among organisms for resources"],
        ["Survival of the fittest", "Organisms with beneficial variations use resources better, survive and reproduce"],
      ]),
      recall_data: recall("What does nature select for in Darwin's example?", "Fitness."),
      importance: 5,
      source_page: 114,
      sort_order: 12,
    }),
    card(chapterId, "mutation-theory", {
      title: "Mutation Theory",
      card_type: "comparison",
      body: "Hugo de Vries proposed mutation theory of evolution using Oenothera lamarckiana.",
      table_data: table(["Variation", "Source-backed nature"], [
        ["Darwinian variation", "Minor, slow and directional; results in gradual evolution"],
        ["Mutational variation", "Sudden, random and directionless"],
        ["Saltation", "Speciation by single step, large mutation"],
        ["Origin of variation", "Mutation is the origin of variation for evolution"],
      ]),
      recall_data: recall("Who proposed mutation theory of evolution?", "Hugo de Vries."),
      importance: 5,
      source_page: 115,
      sort_order: 13,
    }),
    card(chapterId, "hardy-weinberg", {
      title: "Hardy-Weinberg Principle",
      card_type: "diagram",
      body: "Allele frequencies remain stable generation to generation in absence of disturbing factors.",
      diagram_data: { type: "bio-hardy-weinberg" },
      formulas: [{ label: "Hardy-Weinberg equation", latex: "p^2+2pq+q^2=1" }],
      table_data: table(["Term", "Source-backed recall"], [
        ["Gene pool", "Total genes and their alleles in a population"],
        ["Genetic equilibrium", "Gene pool remains constant"],
        ["Sum allelic frequencies", "1"],
        ["Frequency of AA", "p^2"],
        ["Frequency of Aa", "2pq"],
        ["Frequency of aa", "q^2"],
      ]),
      recall_data: recall("What is the Hardy-Weinberg equation in the source?", "p^2 + 2pq + q^2 = 1."),
      importance: 5,
      source_page: 115,
      sort_order: 14,
    }),
    card(chapterId, "hardy-weinberg-factors", {
      title: "Factors Affecting Hardy-Weinberg Equilibrium",
      card_type: "classification",
      body: "Changes in allele frequencies disturb Hardy-Weinberg equilibrium and indicate evolution.",
      table_data: table(["Factor", "Source-backed recall"], [
        ["Gene migration or gene flow", "Gene flow from one population to another changes gene frequencies in both populations"],
        ["Genetic drift", "Gene flow by chance causing frequency change; may produce founder effect"],
        ["Mutation", "Forms new phenotypes and can lead to speciation over generations"],
        ["Genetic recombination", "Reshuffling of gene combinations during crossing over"],
        ["Natural selection", "Stabilizing, directional or disruptive selection"],
      ]),
      recall_data: recall("What is founder effect?", "When the original drifted population becomes founders after genetic drift changes frequency."),
      importance: 5,
      source_page: 115,
      sort_order: 15,
    }),
    card(chapterId, "selection-types", {
      title: "Selection Types",
      card_type: "comparison",
      body: "The source lists three types of natural selection.",
      table_data: table(["Selection type", "Source-backed recall"], [
        ["Stabilizing selection", "More individuals acquire mean character value and variation is reduced"],
        ["Directional selection", "Individuals of one extreme are more favoured"],
        ["Disruptive selection", "Individuals of both extremes are more favoured"],
      ]),
      recall_data: recall("Which selection favours both extremes?", "Disruptive selection."),
      importance: 4,
      source_page: 115,
      sort_order: 16,
    }),
    card(chapterId, "geological-time-scale", {
      title: "Geological Time Scale",
      card_type: "sequence",
      body: "The source gives four eras in geological time scale.",
      table_data: table(["Era", "Time/source recall"], [
        ["Proterozoic", "2500-541 mya"],
        ["Palaeozoic", "540-252 mya"],
        ["Mesozoic", "252-66 mya; age of reptiles and gymnosperms"],
        ["Cenozoic", "66-0 mya; age of mammals and angiosperms"],
      ]),
      recall_data: recall("Which era is called the age of reptiles and gymnosperms?", "Mesozoic era."),
      importance: 5,
      source_page: 115,
      sort_order: 17,
    }),
    card(chapterId, "evolution-timeline", {
      title: "Evolution Timeline Highlights",
      card_type: "sequence",
      body: "The source lists major biological events across eras.",
      table_data: table(["Time", "Source-backed event"], [
        ["500 mya", "Invertebrates were formed"],
        ["450 mya", "First land organisms or plants appeared"],
        ["400 mya", "Arthropods invaded land"],
        ["350 mya", "Jawless fishes evolved; lobefins evolved to first amphibians"],
        ["320 mya", "Sea weeds and few plants existed"],
        ["200 mya", "Some land reptiles went back into water to evolve fish-like reptiles such as Ichthyosaurs"],
        ["65 mya", "Dinosaurs suddenly disappeared"],
      ]),
      recall_data: recall("When did first land plants appear according to the source?", "450 mya."),
      importance: 5,
      source_page: 115,
      sort_order: 18,
    }),
    card(chapterId, "human-evolution-timeline", {
      title: "Human Evolution Timeline",
      card_type: "diagram",
      body: "The source gives a sequence from Dryopithecus to Homo sapiens.",
      diagram_data: { type: "bio-human-evolution-timeline" },
      table_data: table(["Time/form", "Source-backed trait"], [
        ["15 mya: Dryopithecus and Ramapithecus", "Hairy, walked like gorillas and chimpanzee; Dryopithecus ape-like, Ramapithecus man-like"],
        ["3-4 mya: man-like primates", "Walked upright in eastern Africa; height up to 4 feet"],
        ["2 mya: Australopithecus", "East African grasslands; hunted with stone weapons; ate fruits"],
        ["Homo habilis", "First human-like being; brain 650-800 cc; did not eat meat"],
        ["1.5 mya: Homo erectus", "Java man; brain 900 cc; ate meat"],
        ["1 lakh-40,000 years ago: Homo neanderthalensis", "Brain 1400 cc; East and Central Asia; used hides; buried dead"],
        ["75,000-10,000 years ago: Homo sapiens", "Modern man"],
      ]),
      recall_data: recall("Which hominid is called first human-like being in the source?", "Homo habilis."),
      importance: 5,
      source_page: 116,
      sort_order: 19,
    }),
    card(chapterId, "human-evolution-sequence", {
      title: "Human Evolution Sequence",
      card_type: "sequence",
      body: "The source gives the exact sequence of human evolution.",
      table_data: table(["Order", "Form"], [
        ["1", "Dryopithecus"],
        ["2", "Ramapithecus"],
        ["3", "Australopithecus"],
        ["4", "Homo habilis"],
        ["5", "H. erectus"],
        ["6", "H. neanderthalensis"],
        ["7", "H. sapiens"],
      ]),
      recall_data: recall("Which form comes after Ramapithecus in the source sequence?", "Australopithecus."),
      importance: 5,
      source_page: 116,
      sort_order: 20,
    }),
  ];
}

const biologyBatch8CardsBySlug = {
  "principles-of-inheritance-and-variations": inheritanceCards,
  "molecular-basis-of-inheritance": molecularCards,
  evolution: evolutionCards,
};

export function getBiologyBatch8Chapters() {
  return BIOLOGY_BATCH_8_CHAPTER_DEFINITIONS.map((item) => ({
    id: chapter(item.slug),
    subject_id: "neet-biology",
    title: item.title,
    slug: item.slug,
    sort_order: item.sort_order,
    source_page: item.source_page,
  }));
}

export function getBiologyBatch8Cards() {
  return BIOLOGY_BATCH_8_CHAPTER_DEFINITIONS.flatMap((item) => biologyBatch8CardsBySlug[item.slug](chapter(item.slug)));
}
