export const BIOLOGY_BATCH_2_CHAPTER_DEFINITIONS = [
  { title: "Morphology of Flowering Plants", slug: "morphology-of-flowering-plants", sort_order: 5, source_page: 21 },
  { title: "Anatomy of Flowering Plants", slug: "anatomy-of-flowering-plants", sort_order: 6, source_page: 27 },
];

const chapter = (slug) => `neet-biology-${slug}`;

function table(columns, rows) {
  return { columns, rows };
}

function sections(items) {
  return { sections: items };
}

function recall(question, answer, key_points = [], examples = [], neet_traps = []) {
  return { recall_question: question, reveal_answer: answer, key_points, examples, neet_traps };
}

function card(chapterId, slug, payload) {
  return {
    id: `${chapterId}-${slug}`,
    chapter_id: chapterId,
    formulas: [],
    variables: [],
    conditions: [],
    table_data: null,
    diagram_data: null,
    diagram_svg: null,
    is_active: true,
    ...payload,
  };
}

function morphologyCards(chapterId) {
  return [
    card(chapterId, "plant-body-root-shoot", {
      title: "Morphology and Plant Body",
      card_type: "concept",
      body: "Morphology is the study of external forms of organisms. A flowering plant has a root system and a shoot system.",
      recall_data: recall("What are the two main parts of a flowering plant?", "Root system and shoot system.", [
        "Root system is the underground part.",
        "Shoot system is the portion above the ground.",
      ]),
      importance: 4,
      source_page: 21,
      sort_order: 1,
    }),
    card(chapterId, "root-systems-comparison", {
      title: "Tap, Fibrous and Adventitious Roots",
      card_type: "comparison",
      body: "Root systems are grouped by origin of the primary root and replacement roots.",
      diagram_data: { type: "bio-root-systems" },
      table_data: table(["Root system", "Recall cue", "Source examples"], [
        ["Tap root", "Primary root from radicle persists with lateral roots; seen in dicots.", "Mustard plant"],
        ["Fibrous root", "Primary root is short lived and replaced by many roots from base of stem; seen in monocots.", "Wheat"],
        ["Adventitious root", "Roots arise from parts other than radicle.", "Grass, Monstera and banyan tree"],
      ]),
      recall_data: recall("How do tap, fibrous and adventitious roots differ?", "Tap root persists from radicle; fibrous roots replace the short-lived primary root; adventitious roots arise from parts other than radicle.", [], ["Mustard plant", "Wheat", "Grass, Monstera and banyan tree"]),
      importance: 5,
      source_page: 21,
      sort_order: 2,
    }),
    card(chapterId, "root-regions", {
      title: "Regions of the Root",
      card_type: "diagram",
      body: "The root tip has root cap, meristematic region, elongation region and maturation region.",
      diagram_data: { type: "bio-root-regions" },
      table_data: table(["Region", "Recall answer"], [
        ["Root cap", "Covering at apex; protects tender apex."],
        ["Meristematic activity", "Above root cap; small, thin-walled cells with dense protoplasm divide repeatedly."],
        ["Elongation", "Just above meristematic region; cells elongate and enlarge, helping root grow in length."],
        ["Maturation", "Proximal to elongation zone; cells differentiate and mature."],
        ["Root hairs", "Very fine thread-like epidermal structures behind elongation region; absorb water and minerals."],
      ]),
      recall_data: recall("In which region are root hairs formed?", "Behind the region of elongation, in the region of maturation.", ["Root hairs are very fine, delicate, thread-like structures formed from epidermal cells."], [], ["Root hairs belong to the maturation region, not the meristematic region."]),
      importance: 5,
      source_page: 21,
      sort_order: 3,
    }),
    card(chapterId, "root-modifications", {
      title: "Root Modifications",
      card_type: "comparison",
      body: "Roots may be modified for functions other than absorption and conduction.",
      table_data: table(["Modification", "Recall cue", "Source examples"], [
        ["Storage roots", "Swollen roots for food storage.", "Tap roots of carrot, turnips and adventitious roots of sweet potato"],
        ["Prop roots", "Hanging structures that support banyan tree.", "Banyan tree"],
        ["Stilt roots", "Supporting roots from lower nodes of stem.", "Maize & sugarcane"],
        ["Pneumatophores", "Roots come out of ground and grow vertically upwards to get oxygen for respiration.", "Rhizophora growing in swampy areas"],
      ]),
      recall_data: recall("Which root modification helps plants growing in swampy areas get oxygen?", "Pneumatophores.", ["They come out of the ground and grow vertically upwards to get oxygen for respiration."], ["Rhizophora"], ["Do not confuse stilt roots for support with pneumatophores for respiration."]),
      importance: 5,
      source_page: 21,
      sort_order: 4,
    }),
    card(chapterId, "root-functions", {
      title: "Functions of Root",
      card_type: "fact",
      body: "The source lists absorption, anchorage, storage and synthesis of plant growth regulators as root functions.",
      table_data: table(["Function", "Source wording"], [
        ["Absorption", "Absorption of water and minerals from the soil."],
        ["Anchorage", "Provide a proper anchorage to the plant parts."],
        ["Storage", "Storage of reserve food material."],
        ["Synthesis", "Synthesis of plant growth regulators."],
      ]),
      recall_data: recall("List the four functions of root given in the source.", "Absorption, anchorage, storage and synthesis of plant growth regulators."),
      importance: 4,
      source_page: 21,
      sort_order: 5,
    }),
    card(chapterId, "stem-definition-functions", {
      title: "Stem, Nodes and Internodes",
      card_type: "concept",
      body: "Stem is the ascending axis from plumule. Nodes bear leaves; internodes are portions between two nodes.",
      table_data: table(["Stem feature", "Recall answer"], [
        ["Origin", "Ascending part of the axis that develops from plumule of a germinating seed."],
        ["Bears", "Branches, leaves, flowers, fruits, terminal or axillary buds, nodes and internodes."],
        ["Nodes", "Regions of stem where leaves are born."],
        ["Internodes", "Portions between two nodes."],
        ["Functions", "Spreading branches, conduction of water/minerals/photosynthates, food storage, support, protection and vegetative propagation."],
      ]),
      recall_data: recall("What is the difference between node and internode?", "Nodes are stem regions where leaves are born; internodes are portions between two nodes."),
      importance: 4,
      source_page: 21,
      sort_order: 6,
    }),
    card(chapterId, "stem-modifications", {
      title: "Stem Modifications",
      card_type: "comparison",
      body: "Modified stems perform storage, climbing, protection, photosynthesis and vegetative propagation.",
      table_data: table(["Modification", "Recall cue", "Source examples"], [
        ["Underground stems", "Food storage and perennation.", "Potato, ginger, turmeric, zaminkand, Colocasia"],
        ["Stem tendrils", "Slender, spirally coiled axillary-bud structures for climbing.", "Gourds (cucumber, pumpkins, watermelon) & grapevines"],
        ["Thorns", "Woody, straight, pointed structures from axillary buds for protection.", "Citrus, Bougainvillea"],
        ["Phylloclade", "Green, flattened or fleshy cylindrical stem with chlorophyll for photosynthesis in arid regions.", "Opuntia (flattened stem), Euphorbia (cylindrical stem)"],
        ["Stolon", "Slender lateral branch from base; grows aerially then arches down to touch ground.", "Mint & jasmine"],
        ["Offset", "Lateral branch with short internodes; node bears rosette of leaves and tuft of roots.", "Pistia and Eichhornia"],
        ["Sucker", "Lateral branches from basal underground part, grow horizontally below soil and come out obliquely upward.", "Banana, Pineapple & Chrysanthemum"],
      ]),
      recall_data: recall("Which stem modifications are source examples of vegetative spread?", "Stolon, offset and sucker.", ["Underground stems of grass, strawberry etc. spread to new niches."], ["Mint & jasmine", "Pistia and Eichhornia", "Banana, Pineapple & Chrysanthemum"]),
      importance: 5,
      source_page: 21,
      sort_order: 7,
    }),
    card(chapterId, "leaf-parts", {
      title: "Parts of a Leaf",
      card_type: "diagram",
      body: "A typical leaf has leaf base, petiole and lamina.",
      diagram_data: { type: "bio-leaf-parts" },
      table_data: table(["Part", "Recall answer"], [
        ["Leaf base", "Attaches leaf to stem; may bear stipules; in monocots expands into a sheath; in some leguminous plants becomes pulvinus."],
        ["Petiole", "Helps hold leaf blade to light; flexible petioles allow fluttering in wind."],
        ["Lamina", "Green expanded part with veins and veinlets; prominent middle vein is midrib."],
      ]),
      recall_data: recall("Name the three main parts of a typical leaf.", "Leaf base, petiole and lamina.", ["Lamina is also called leaf blade."], [], ["Pulvinus is a swollen leaf base in some leguminous plants."]),
      importance: 5,
      source_page: 22,
      sort_order: 8,
    }),
    card(chapterId, "venation-comparison", {
      title: "Reticulate vs Parallel Venation",
      card_type: "comparison",
      body: "Venation is arrangement of veins and veinlets in leaf lamina.",
      diagram_data: { type: "bio-venation" },
      table_data: table(["Venation", "Recall answer", "Seen in"], [
        ["Reticulate", "Veinlets form a network.", "Dicotyledons"],
        ["Parallel", "Veins run parallel to each other within a lamina.", "Monocotyledons"],
      ]),
      recall_data: recall("Which venation is typical of dicots and which of monocots?", "Reticulate in dicotyledons; parallel in monocotyledons."),
      importance: 5,
      source_page: 22,
      sort_order: 9,
    }),
    card(chapterId, "simple-compound-leaves", {
      title: "Simple vs Compound Leaf",
      card_type: "comparison",
      body: "The difference depends on whether lamina incisions reach the midrib and form leaflets.",
      table_data: table(["Leaf type", "Recall answer", "Bud trap"], [
        ["Simple leaf", "Lamina is entire or incisions do not touch midrib.", "Bud is seen in axil of petiole."],
        ["Compound leaf", "Incisions reach midrib, breaking lamina into several leaflets.", "Bud is seen in axil of petiole, not in axil of leaflets."],
      ]),
      recall_data: recall("What is the key difference between simple and compound leaves?", "In compound leaves, incisions reach the midrib and form leaflets; in simple leaves they do not.", [], [], ["A bud is not seen in the axil of leaflets of a compound leaf."]),
      importance: 5,
      source_page: 22,
      sort_order: 10,
    }),
    card(chapterId, "pinnate-palmate-compound", {
      title: "Pinnately vs Palmately Compound Leaf",
      card_type: "comparison",
      body: "Compound leaves are grouped by how leaflets attach.",
      table_data: table(["Type", "Recall answer", "Source example"], [
        ["Pinnately compound", "Many leaflets are present on a common axis, the rachis, which represents the midrib.", "Neem"],
        ["Palmately compound", "Leaflets are attached at a common point at the tip of petiole.", "Silk cotton"],
      ]),
      recall_data: recall("Which compound leaf has leaflets on a rachis?", "Pinnately compound leaf.", ["Palmately compound leaf has leaflets at a common point."], ["Neem", "Silk cotton"]),
      importance: 4,
      source_page: 22,
      sort_order: 11,
    }),
    card(chapterId, "phyllotaxy", {
      title: "Phyllotaxy Types",
      card_type: "diagram",
      body: "Phyllotaxy is the pattern of arrangement of leaves on the stem or branch.",
      diagram_data: { type: "bio-phyllotaxy" },
      table_data: table(["Type", "Recall answer", "Source examples"], [
        ["Alternate", "A single leaf arises at each node in alternate manner.", "China rose, mustard & sun flower"],
        ["Opposite", "A pair of leaves arise at each node and lie opposite to each other.", "Calotropis and guava"],
        ["Whorled", "More than two leaves arise at a node and form a whorl.", "Alstonia"],
      ]),
      recall_data: recall("What are the three types of phyllotaxy?", "Alternate, opposite and whorled.", [], ["China rose, mustard & sun flower", "Calotropis and guava", "Alstonia"]),
      importance: 5,
      source_page: 22,
      sort_order: 12,
    }),
    card(chapterId, "leaf-modifications", {
      title: "Leaf Modifications",
      card_type: "examples",
      body: "Leaves can be modified for climbing, defence, storage, food synthesis or insectivory.",
      table_data: table(["Modification", "Recall cue", "Source examples"], [
        ["Tendrils", "For climbing.", "Peas"],
        ["Spines", "For defense.", "Cacti"],
        ["Fleshy leaves", "To store food.", "Onion and garlic"],
        ["Expanded green petioles", "Leaves are small and short-lived; petioles synthesise food.", "Australian acacia"],
        ["Insectivorous leaves", "Modified leaves.", "Pitcher plant, Venus-fly trap"],
      ]),
      recall_data: recall("In Australian acacia, which part expands and synthesises food?", "The petiole.", ["Leaves are small and short-lived."], ["Australian acacia"]),
      importance: 4,
      source_page: 22,
      sort_order: 13,
    }),
    card(chapterId, "flower-inflorescence", {
      title: "Flower and Inflorescence",
      card_type: "concept",
      body: "A flower is a modified shoot. Inflorescence is the arrangement of a cluster of flowers on the floral axis.",
      table_data: table(["Term", "Recall answer"], [
        ["Flower", "Modified shoot where shoot apical meristem changes to floral meristem."],
        ["Solitary flower", "When a shoot tip transforms into a flower."],
        ["Inflorescence", "Arrangement of cluster of flowers on the floral axis."],
      ]),
      recall_data: recall("What happens to internodes when shoot apex becomes a flower?", "Internodes do not elongate and the axis gets condensed.", ["The apex produces floral appendages laterally at successive nodes instead of leaves."]),
      importance: 4,
      source_page: 22,
      sort_order: 14,
    }),
    card(chapterId, "racemose-cymose", {
      title: "Racemose vs Cymose Inflorescence",
      card_type: "comparison",
      body: "Inflorescences differ by whether the main axis keeps growing or terminates in a flower.",
      table_data: table(["Type", "Main axis", "Flower order"], [
        ["Racemose", "Continues to grow.", "Flowers are borne laterally in acropetal succession."],
        ["Cymose", "Terminates in a flower and is limited in growth.", "Flowers are borne in basipetal order."],
      ]),
      recall_data: recall("Racemose vs cymose: what is the growth and flower-order distinction?", "Racemose has a continuously growing main axis with acropetal succession; cymose terminates in a flower with basipetal order."),
      importance: 5,
      source_page: 22,
      sort_order: 15,
    }),
    card(chapterId, "flower-general-terms", {
      title: "Basic Flower Terms",
      card_type: "classification",
      body: "A flower has pedicel, thalamus and four whorls; bracts and sex are useful classification cues.",
      table_data: table(["Cue", "Recall answer"], [
        ["Pedicel", "Stalk of flower."],
        ["Thalamus/receptacle", "Swollen end of pedicel."],
        ["Bract", "Reduced leaf found at base of pedicel."],
        ["Bracteate / ebracteate", "Flowers with bracts / without bracts."],
        ["Whorls", "Calyx, corolla, androecium and gynoecium."],
        ["Accessory organs", "Calyx and corolla."],
        ["Reproductive organs", "Androecium and gynoecium."],
        ["Perianth", "Calyx and corolla not distinct, as in lily."],
        ["Bisexual / unisexual", "Both androecium and gynoecium / either only androecium or only gynoecium."],
      ]),
      recall_data: recall("Which floral whorls are accessory and which are reproductive?", "Accessory: calyx and corolla. Reproductive: androecium and gynoecium.", [], [], ["Perianth is used when calyx and corolla are not distinct."]),
      importance: 5,
      source_page: 23,
      sort_order: 16,
    }),
    card(chapterId, "flower-symmetry", {
      title: "Flower Symmetry",
      card_type: "diagram",
      body: "Flowers are classified as actinomorphic, zygomorphic or asymmetric based on symmetry.",
      diagram_data: { type: "bio-flower-symmetry" },
      table_data: table(["Type", "Recall answer", "Source examples"], [
        ["Actinomorphic", "Can be divided into two equal radial halves in any radial plane through centre.", "Mustard, datura, chilli"],
        ["Zygomorphic", "Can be divided into two similar halves only in a particular vertical plane.", "Pea, gulmohur, bean, Cassia"],
        ["Asymmetric", "Cannot be divided into two similar halves by any vertical plane through centre.", "Canna"],
      ]),
      recall_data: recall("Which flower symmetry has only one vertical plane of division?", "Zygomorphic.", [], ["Pea, gulmohur, bean, Cassia"]),
      importance: 5,
      source_page: 23,
      sort_order: 17,
    }),
    card(chapterId, "floral-appendage-numbers", {
      title: "Trimerous, Tetramerous, Pentamerous",
      card_type: "fact",
      body: "Flowers are also classified by number of floral appendages.",
      table_data: table(["Term", "Recall answer"], [
        ["Trimerous", "Floral appendages are multiple of 3."],
        ["Tetramerous", "Floral appendages are multiple of 4."],
        ["Pentamerous", "Floral appendages are multiple of 5."],
      ]),
      recall_data: recall("What do trimerous, tetramerous and pentamerous mean?", "Floral appendages in multiples of 3, 4 and 5 respectively."),
      importance: 4,
      source_page: 23,
      sort_order: 18,
    }),
    card(chapterId, "ovary-position", {
      title: "Hypogynous, Perigynous and Epigynous",
      card_type: "diagram",
      body: "These types depend on the position of calyx, corolla and androecium with respect to ovary on thalamus.",
      diagram_data: { type: "bio-ovary-position" },
      table_data: table(["Type", "Position cue", "Ovary", "Source examples"], [
        ["Hypogynous", "Gynoecium highest; other parts below it.", "Superior", "Mustard, China rose & brinjal"],
        ["Perigynous", "Gynoecium in centre; other parts on rim of thalamus at same level.", "Half inferior", "Plum, rose, peach"],
        ["Epigynous", "Thalamus encloses and fuses with ovary; other parts arise above ovary.", "Inferior", "Guava, cucumber, ray florets of sunflower"],
      ]),
      recall_data: recall("Which ovary type is found in epigynous flowers?", "Inferior ovary.", [], ["Guava, cucumber, ray florets of sunflower"], ["Perigynous has a half inferior ovary."]),
      importance: 5,
      source_page: 23,
      sort_order: 19,
    }),
    card(chapterId, "calyx-corolla-aestivation", {
      title: "Calyx, Corolla and Aestivation",
      card_type: "comparison",
      body: "Calyx is made of sepals, corolla of petals, and aestivation is their arrangement in the floral bud.",
      diagram_data: { type: "bio-aestivation" },
      table_data: sections([
        {
          title: "Calyx and corolla",
          columns: ["Whorl", "Recall answer"],
          rows: [
            ["Calyx", "Outermost whorl made of sepals; may be gamosepalous or polysepalous."],
            ["Corolla", "Whorl inner to calyx made of petals; may be gamopetalous or polypetalous."],
          ],
        },
        {
          title: "Aestivation types",
          columns: ["Type", "Recall cue", "Source examples"],
          rows: [
            ["Valvate", "Margins just touch without overlapping.", "Calotropis"],
            ["Twisted", "One margin overlaps next one and so on.", "China rose, lady's finger & cotton"],
            ["Imbricate", "Margins overlap, but not in any particular direction.", "Cassia & gulmohur"],
            ["Vexillary", "Standard overlaps wings, which overlap keel.", "Pea & bean"],
          ],
        },
      ]),
      recall_data: recall("Which aestivation has standard, wings and keel?", "Vexillary (papilionaceous).", ["Largest standard overlaps two lateral wings; wings overlap two smallest anterior petals (keel)."], ["Pea & bean"]),
      importance: 5,
      source_page: 23,
      sort_order: 20,
    }),
    card(chapterId, "androecium-terms", {
      title: "Androecium Terms",
      card_type: "classification",
      body: "Androecium is the male reproductive part composed of stamens.",
      table_data: table(["Term", "Recall answer", "Source examples"], [
        ["Stamen", "Male reproductive organ with filament and anther." , ""],
        ["Anther", "Usually bilobed; each lobe has two pollen-sacs where pollen grains are produced.", ""],
        ["Staminode", "Sterile stamen.", ""],
        ["Epipetalous", "Stamens attached to petals.", "Brinjal"],
        ["Epiphyllous", "Stamens attached to perianth.", "Lily"],
        ["Polyandrous", "Stamens are free.", ""],
        ["Monadelphous", "Stamens united into one bundle.", "China rose"],
        ["Diadelphous", "Stamens united into two bundles.", "Pea"],
        ["Polyadelphous", "Stamens united into more than two bundles.", "Citrus"],
      ]),
      recall_data: recall("What is a staminode?", "A sterile stamen.", ["Epipetalous: stamens attached to petals.", "Epiphyllous: stamens attached to perianth."], ["Brinjal", "Lily"]),
      importance: 5,
      source_page: 23,
      sort_order: 21,
    }),
    card(chapterId, "gynoecium-terms", {
      title: "Gynoecium and Pistil Terms",
      card_type: "classification",
      body: "Gynoecium is the female reproductive part made of one or more carpels.",
      table_data: table(["Term", "Recall answer", "Source examples"], [
        ["Stigma", "Receptive surface for pollen grains, usually at tip of style.", ""],
        ["Style", "Elongated tube connecting ovary to stigma.", ""],
        ["Ovary", "Enlarged basal part bearing one or more ovules attached to placenta.", ""],
        ["Placenta", "Flattened, cushion-like structure to which ovules attach.", ""],
        ["Apocarpous", "Carpels are free.", "Lotus and rose"],
        ["Syncarpous", "Carpels are fused.", "Mustard and tomato"],
      ]),
      recall_data: recall("Apocarpous vs syncarpous: what is the difference?", "Apocarpous carpels are free; syncarpous carpels are fused.", [], ["Lotus and rose", "Mustard and tomato"]),
      importance: 5,
      source_page: 24,
      sort_order: 22,
    }),
    card(chapterId, "placentation-types", {
      title: "Placentation Types",
      card_type: "diagram",
      body: "Placentation is the arrangement of ovules on placenta within the ovary.",
      diagram_data: { type: "bio-placentation" },
      table_data: table(["Type", "Recall cue", "Source examples"], [
        ["Marginal", "Placenta forms a ridge along ventral suture; ovules borne in two rows.", "Pea"],
        ["Axile", "Placenta is axial; ovules attached in multilocular ovary.", "China rose, tomato and lemon"],
        ["Parietal", "Ovules develop on inner wall or peripheral part; one-chambered ovary may become two-chambered by false septum.", "Mustard and Argemone"],
        ["Basal", "Placenta develops at base of ovary with a single ovule.", "Sunflower, marigold"],
        ["Free central", "Ovules borne on central axis and septa are absent.", "Dianthus and Primrose"],
      ]),
      recall_data: recall("Which placentation has ovules on a central axis with septa absent?", "Free central placentation.", [], ["Dianthus and Primrose"], ["Axile is axial in a multilocular ovary; free central has septa absent."]),
      importance: 5,
      source_page: 24,
      sort_order: 23,
    }),
    card(chapterId, "fruit-drupe", {
      title: "Fruit and Drupe",
      card_type: "fact",
      body: "Fruit is a ripened ovary developed after fertilisation; parthenocarpic fruit forms without fertilisation.",
      table_data: table(["Term", "Recall answer", "Source examples"], [
        ["Fruit", "Ripened ovary developed after fertilisation; characteristic feature of flowering plants.", ""],
        ["Parthenocarpic fruit", "Fruit formed without fertilisation of the ovary.", ""],
        ["Drupe", "One seeded fruit from monocarpellary superior ovary.", "Mango & coconut"],
        ["Pericarp", "Fruit wall, dry or fleshy; fleshy pericarp has epicarp, mesocarp and endocarp.", ""],
        ["Mango pericarp", "Thin epicarp, fleshy edible mesocarp and stony hard endocarp.", "Mango"],
        ["Coconut mesocarp", "Fibrous.", "Coconut"],
      ]),
      recall_data: recall("What is a drupe according to the source examples?", "Mango and coconut are drupes; they are one seeded and develop from monocarpellary superior ovaries.", ["Pericarp may be dry or fleshy."]),
      importance: 4,
      source_page: 24,
      sort_order: 24,
    }),
    card(chapterId, "dicot-monocot-seed", {
      title: "Dicot vs Monocot Seed",
      card_type: "diagram",
      body: "Seed is a mature ovule developed after fertilisation and is made of seed coat and embryo.",
      diagram_data: { type: "bio-seed-comparison" },
      table_data: table(["Feature", "Dicot seed", "Monocot seed"], [
        ["Cotyledons", "Two cotyledons.", "One large shield-shaped cotyledon called scutellum."],
        ["Examples", "Gram & pea; bean, gram and pea are non-endospermous.", "Wheat, maize; orchids are non-endospermic."],
        ["Seed coat", "Outer testa and inner tegmen; hilum and micropyle present.", "In cereals such as maize, seed coat is membranous and generally fused with fruit wall."],
        ["Food storage", "Cotyledons often fleshy and full of reserve food; castor has endosperm formed due to double fertilisation.", "Endosperm bulky; aleurone layer separates embryo."],
        ["Protective sheaths", "Radicle and plumule at ends of embryonal axis.", "Plumule protected by coleoptile; radicle by coleorhiza."],
      ]),
      recall_data: recall("Which monocot seed structure is the shield-shaped cotyledon?", "Scutellum.", ["Coleoptile protects plumule; coleorhiza protects radicle.", "Aleurone layer is the protein layer outside the embryo in monocot seed."], ["Wheat, maize", "Orchids"]),
      importance: 5,
      source_page: 24,
      sort_order: 25,
    }),
    card(chapterId, "floral-formula-symbols", {
      title: "Floral Formula Symbols",
      card_type: "fact",
      body: "Semi-technical description begins with habit, vegetative characters, then floral characters, followed by floral diagram and formula.",
      table_data: table(["Symbol", "Meaning in source"], [
        ["Br", "Bracteates"],
        ["K", "Calyx"],
        ["C", "Corolla"],
        ["P", "Perianth"],
        ["A", "Androecium"],
        ["G", "Gynoecium"],
        ["G", "Superior ovary"],
        ["G", "Inferior ovary"],
        ["♂", "Male"],
        ["♀", "Female"],
        ["⚥", "Bisexual"],
        ["⊕", "Actinomorphic"],
        ["%", "Zygomorphic"],
      ]),
      recall_data: recall("What do K, C, A and G denote in a floral formula?", "K = calyx, C = corolla, A = androecium, G = gynoecium.", ["Fusion is shown by brackets; adhesion by a line above symbols.", "A floral diagram gives number, arrangement and relation of floral parts."]),
      importance: 5,
      source_page: 25,
      sort_order: 26,
    }),
    card(chapterId, "fabaceae-family", {
      title: "Fabaceae Family",
      card_type: "classification",
      body: "Fabaceae was earlier called Papilonoideae, a subfamily of Leguminosae.",
      table_data: sections([
        { title: "Vegetative characters", columns: ["Character", "Source detail"], rows: [["Habit", "Trees, shrubs, herbs; root with root nodules."], ["Stem", "Erect or climber."], ["Leaves", "Alternate, pinnately compound or simple; leaf base, pulvinate; stipulate; venation reticulate."]] },
        { title: "Floral characters", columns: ["Character", "Source detail"], rows: [["Inflorescence", "Racemose."], ["Flower", "Bisexual, zygomorphic."], ["Calyx", "Sepals five, gamosepalous; valvate/imbricate aestivation."], ["Corolla", "Petals five, polypetalous, papilionaceous; vexillary aestivation."], ["Androecium", "Ten, diadelphous, anther dithecous."], ["Gynoecium", "Ovary superior, mono carpellary, unilocular with many ovules, style single."], ["Fruit/seed", "Fruit: legume; seed: one to many, non-endospermic."], ["Floral formula", "%⚥K(5) C1+2+(2) A(9)+1 G1"]] },
        { title: "Economic importance", columns: ["Use", "Source examples"], rows: [["Pulses", "Gram, arhar, sem, moong, soyabean"], ["Edible oil", "Soyabean, groundnut"], ["Dye", "Indigofera"], ["Fibres", "Sun hemp"], ["Fodder", "Sesbania, Trifolium"], ["Ornamentals", "Lupin, sweet pea"], ["Medicine", "Muliathi"]] },
      ]),
      recall_data: recall("Which family has vexillary aestivation and diadelphous androecium?", "Fabaceae.", ["Flower is bisexual and zygomorphic.", "Fruit is legume; seed is one to many and non-endospermic."], ["Pisum sativum (pea)"]),
      importance: 5,
      source_page: 25,
      sort_order: 27,
    }),
    card(chapterId, "solanaceae-family", {
      title: "Solanaceae Family",
      card_type: "classification",
      body: "Solanaceae is the potato family, widely distributed in tropics, subtropics and temperate zones.",
      table_data: sections([
        { title: "Vegetative characters", columns: ["Character", "Source detail"], rows: [["Habit", "Plants mostly herbs, shrubs and small trees."], ["Stem", "Herbaceous rarely woody, aerial; erect, cylindrical, branched, solid or hollow, hairy or glabrous, underground stem in potato (Solanum tuberosum)."], ["Leaves", "Alternate, simple, rarely pinnately compound, exstipulate; venation reticulate."]] },
        { title: "Floral characters", columns: ["Character", "Source detail"], rows: [["Inflorescence", "Solitary, axillary or cymose as in Solanum."], ["Flower", "Bisexual, actinomorphic."], ["Calyx", "Sepals five, united, persistent, valvate aestivation."], ["Corolla", "Petals five, united; valvate aestivation."], ["Androecium", "Stamens five, epipetalous."], ["Gynoecium", "Bicarpellary obligately placed, syncarpous; ovary superior, bilocular, placenta swollen with many ovules, axile."], ["Fruits/seeds", "Fruits: berry or capsule. Seeds: many, endospermous."], ["Floral formula", "⊕⚥K(5) C(5) A(5) G(2)"]] },
        { title: "Economic importance", columns: ["Use", "Source examples"], rows: [["Food", "Tomato, brinjal, potato"], ["Spice", "Chilli"], ["Medicine", "Belladonna, ashwagandha"], ["Fumigatory", "Tobacco"], ["Ornamentals", "Petunia"]] },
      ]),
      recall_data: recall("Which family has epipetalous stamens and axile placentation with many ovules?", "Solanaceae.", ["Flower is bisexual and actinomorphic.", "Fruits are berry or capsule; seeds are many and endospermous."], ["Solanum nigrum (makoi)"]),
      importance: 5,
      source_page: 25,
      sort_order: 28,
    }),
    card(chapterId, "liliaceae-family", {
      title: "Liliaceae Family",
      card_type: "classification",
      body: "Liliaceae is a characteristic representative of monocotyledonous plants.",
      table_data: sections([
        { title: "Vegetative characters", columns: ["Character", "Source detail"], rows: [["Habit", "Perennial herbs with underground bulbs/corms/rhizomes."], ["Leaves", "Mostly basal, alternate, linear, exstipulate with parallel venation."]] },
        { title: "Floral characters", columns: ["Character", "Source detail"], rows: [["Inflorescence", "Solitary / cymose; often umbellate clusters."], ["Flower", "Bisexual; actinomorphic."], ["Perianth", "Tepal six (3+3), often united into tube; valvate aestivation."], ["Androecium", "Stamen six, (3+3)."], ["Gynoecium", "Tricarpellary, syncarpous, ovary superior, trilocular with many ovules; axile placentation."], ["Fruit/seed", "Fruit: capsule, rarely berry. Seed: endospermous."], ["Floral formula", "⊕⚥P(3+3) A3+3 G(3)"]] },
        { title: "Economic importance", columns: ["Use", "Source examples"], rows: [["Ornamentals", "Tulip, Gloriosa"], ["Medicine", "Aloe"], ["Vegetables", "Asparagus"], ["Colchicines", "Colchicum autumnale"]] },
      ]),
      recall_data: recall("Which family has six tepals arranged 3+3 and parallel venation?", "Liliaceae.", ["Perianth often united into tube with valvate aestivation.", "Gynoecium is tricarpellary, syncarpous, superior and trilocular."], ["Allium cepa (onion)"]),
      importance: 5,
      source_page: 26,
      sort_order: 29,
    }),
    card(chapterId, "family-comparison", {
      title: "Fabaceae vs Solanaceae vs Liliaceae",
      card_type: "comparison",
      body: "Family recall is fastest when habit, symmetry, perianth/corolla, androecium, gynoecium and examples are compared.",
      table_data: table(["Feature", "Fabaceae", "Solanaceae", "Liliaceae"], [
        ["Representative identity", "Earlier called Papilonoideae; subfamily of Leguminosae.", "Potato family.", "Representative of monocotyledonous plants."],
        ["Flower", "Bisexual, zygomorphic.", "Bisexual, actinomorphic.", "Bisexual; actinomorphic."],
        ["Corolla/perianth", "Papilionaceous, vexillary.", "Corolla united, valvate.", "Perianth tepal six (3+3), often united into tube."],
        ["Androecium", "Ten, diadelphous.", "Stamens five, epipetalous.", "Stamen six, (3+3)."],
        ["Ovary/placentation", "Superior, mono carpellary, unilocular.", "Superior, bilocular, axile.", "Superior, trilocular, axile."],
        ["Source plant shown", "Pisum sativum (pea)", "Solanum nigrum (makoi)", "Allium cepa (onion)"],
      ]),
      recall_data: recall("How do the three source families separate in one line?", "Fabaceae is zygomorphic with papilionaceous/vexillary corolla; Solanaceae is actinomorphic with epipetalous stamens; Liliaceae is monocot with tepals 3+3.", [], ["Pisum sativum (pea)", "Solanum nigrum (makoi)", "Allium cepa (onion)"]),
      importance: 5,
      source_page: 26,
      sort_order: 30,
    }),
  ];
}

function anatomyCards(chapterId) {
  return [
    card(chapterId, "anatomy-tissues", {
      title: "Anatomy and Tissue",
      card_type: "concept",
      body: "Anatomy is the study of internal structure. A tissue is a group of cells having common origin and function.",
      recall_data: recall("How are plant tissues grouped by capability of cell division?", "Meristematic and permanent.", ["Meristematic tissues divide actively; permanent tissues lose ability to divide."]),
      importance: 4,
      source_page: 27,
      sort_order: 1,
    }),
    card(chapterId, "meristem-types", {
      title: "Meristematic Tissues",
      card_type: "classification",
      body: "Meristems are grouped by position into apical, intercalary and lateral meristems.",
      diagram_data: { type: "bio-meristem-positions" },
      table_data: table(["Meristem", "Position/function", "Source notes/examples"], [
        ["Apical", "Tips of roots and shoots; produce primary tissues.", "Root apical meristem, shoot apical meristem; axillary bud can form branch or flower."],
        ["Intercalary", "Occur between mature tissues.", "Occur in grasses and regenerate parts removed by grazing herbivores."],
        ["Secondary/lateral", "Occur in mature regions of roots and shoots; cylindrical meristems.", "Seen in gymnosperms and dicots; fascicular vascular cambium, interfascicular cambium & cork cambium."],
      ]),
      recall_data: recall("Which meristems are primary and which produce secondary tissues?", "Apical and intercalary are primary; secondary/lateral meristems produce secondary tissues.", ["Lateral meristems are seen in gymnosperms and dicots."]),
      importance: 5,
      source_page: 27,
      sort_order: 2,
    }),
    card(chapterId, "permanent-tissues", {
      title: "Permanent Tissues",
      card_type: "classification",
      body: "Cells produced by primary and secondary meristems become specialized and lose ability to divide.",
      table_data: table(["Type", "Recall answer"], [
        ["Simple permanent tissues", "All cells similar in structure and function."],
        ["Complex permanent tissues", "Made of more than one type of cells that work together as a unit."],
      ]),
      recall_data: recall("What are the two types of permanent tissues?", "Simple and complex."),
      importance: 4,
      source_page: 27,
      sort_order: 3,
    }),
    card(chapterId, "simple-permanent-comparison", {
      title: "Parenchyma, Collenchyma and Sclerenchyma",
      card_type: "comparison",
      body: "Simple permanent tissues are parenchyma, collenchyma and sclerenchyma.",
      table_data: table(["Tissue", "Cell/wall features", "Functions / examples"], [
        ["Parenchyma", "Cells generally isodiametric; thin cellulose walls; closely packed or small intercellular spaces.", "Photosynthesis, storage, secretion etc."],
        ["Collenchyma", "Below epidermis in dicot plants; cells with thickened corners due to cellulose, hemicellulose and pectin; no intercellular spaces.", "Mechanical support to young stem and petiole; chloroplast-containing cells assimilate food."],
        ["Sclerenchyma", "Long, narrow cells with thick lignified walls and pits; usually dead without protoplasts.", "Mechanical support; fibres and sclereids."],
      ]),
      recall_data: recall("Which simple permanent tissue is usually dead and lignified?", "Sclerenchyma.", ["It has thick and lignified cell walls and usually no protoplasts.", "It includes fibres and sclereids."]),
      importance: 5,
      source_page: 27,
      sort_order: 4,
    }),
    card(chapterId, "fibres-sclereids", {
      title: "Fibres vs Sclereids",
      card_type: "comparison",
      body: "Sclerenchyma is divided by form, structure, origin and development.",
      table_data: table(["Type", "Recall answer", "Source examples"], [
        ["Fibres", "Thick-walled, elongated and pointed cells, generally occurring in groups.", ""],
        ["Sclereids", "Spherical, oval or cylindrical, highly thickened dead cells with very narrow lumen.", "Fruit walls of nuts; pulp of guava, pear and sapota; seed coats of legumes and leaves of tea"],
      ]),
      recall_data: recall("Where does the source place sclereids?", "Fruit walls of nuts; pulp of guava, pear and sapota; seed coats of legumes and leaves of tea."),
      importance: 4,
      source_page: 27,
      sort_order: 5,
    }),
    card(chapterId, "xylem-elements", {
      title: "Xylem Elements",
      card_type: "comparison",
      body: "Xylem conducts water and minerals and provides mechanical strength.",
      table_data: table(["Element", "Recall answer"], [
        ["Tracheids", "Elongated tube-like dead cells with thick lignified walls and tapering ends; protoplasm absent."],
        ["Vessels", "Long cylindrical tube-like structures made of vessel members with lignified walls and large central cavity; characteristic of angiosperms; gymnosperms lack vessels."],
        ["Xylem fibres", "Highly thickened walls and obliterated central lumens; septate or aseptate."],
        ["Xylem parenchyma", "Living, thin-walled cells with cellulosic walls; store starch/fat and tannins; ray parenchyma conducts water radially."],
      ]),
      recall_data: recall("Which xylem element is characteristic of angiosperms and absent in gymnosperms?", "Vessels.", ["Tracheids and vessels are main water transporting elements in flowering plants."]),
      importance: 5,
      source_page: 28,
      sort_order: 6,
    }),
    card(chapterId, "protoxylem-metaxylem-endarch-exarch", {
      title: "Protoxylem, Metaxylem, Endarch and Exarch",
      card_type: "comparison",
      body: "Primary xylem is protoxylem and metaxylem; their position gives endarch or exarch arrangement.",
      table_data: table(["Term", "Recall answer"], [
        ["Protoxylem", "First formed primary xylem."],
        ["Metaxylem", "Later formed primary xylem."],
        ["Endarch", "In stems, protoxylem lies towards centre (pith), metaxylem towards periphery."],
        ["Exarch", "In roots, protoxylem lies towards periphery, metaxylem towards centre."],
      ]),
      recall_data: recall("Endarch vs exarch: where is protoxylem?", "Endarch: protoxylem towards centre; exarch: protoxylem towards periphery.", [], [], ["Stems are endarch; roots are exarch."]),
      importance: 5,
      source_page: 28,
      sort_order: 7,
    }),
    card(chapterId, "phloem-elements", {
      title: "Phloem Elements",
      card_type: "comparison",
      body: "In angiosperms, phloem has sieve tube elements, companion cells, phloem parenchyma and phloem fibres.",
      table_data: table(["Element", "Recall answer"], [
        ["Sieve tube elements", "Long tube-like structures arranged longitudinally; associated with companion cells; end walls form sieve plates; mature element lacks nucleus."],
        ["Companion cells", "Specialized parenchymatous cells closely associated with sieve tube elements; maintain pressure gradient in sieve tubes."],
        ["Phloem parenchyma", "Elongated tapering cylindrical cells with dense cytoplasm and nucleus; stores food and substances like resins, latex and mucilage; absent in most monocots."],
        ["Phloem fibres", "Sclerenchymatous bast fibres; generally absent in primary phloem but found in secondary phloem; dead at maturity; jute, flax and hemp used commercially."],
      ]),
      recall_data: recall("Which phloem elements are absent in gymnosperms?", "Sieve tubes and companion cells.", ["Gymnosperms have albuminous cells and sieve cells."], [], ["Phloem parenchyma is absent in most monocots."]),
      importance: 5,
      source_page: 28,
      sort_order: 8,
    }),
    card(chapterId, "xylem-vs-phloem", {
      title: "Xylem vs Phloem",
      card_type: "comparison",
      body: "Xylem and phloem are complex permanent tissues that work as conducting tissues.",
      table_data: table(["Feature", "Xylem", "Phloem"], [
        ["Main transport", "Water and minerals from roots to stem and leaves.", "Food materials from leaves to other parts."],
        ["Strength/support", "Also provides mechanical strength.", "Phloem fibres provide mechanical support and protection to soft tissues."],
        ["Angiosperm elements", "Tracheids, vessels, xylem fibres, xylem parenchyma.", "Sieve tube elements, companion cells, phloem parenchyma, phloem fibres."],
        ["Gymnosperm note", "Gymnosperms lack vessels.", "Gymnosperms lack sieve tubes and companion cells."],
      ]),
      recall_data: recall("What do xylem and phloem transport?", "Xylem transports water and minerals; phloem transports food materials."),
      importance: 5,
      source_page: 28,
      sort_order: 9,
    }),
    card(chapterId, "tissue-systems", {
      title: "Tissue Systems",
      card_type: "classification",
      body: "Based on structure and location, tissue systems are epidermal, ground and vascular.",
      table_data: table(["Tissue system", "Recall answer"], [
        ["Epidermal", "Outer-most covering; comprises epidermal cells, stomata and epidermal appendages."],
        ["Ground", "All tissues except epidermis and vascular bundles; simple tissues in cortex, pericycle, pith and medullary rays; mesophyll in leaves."],
        ["Vascular", "Complex tissues xylem and phloem."],
      ]),
      recall_data: recall("Which tissues constitute ground tissue?", "All tissues except epidermis and vascular bundles.", ["In leaves, ground tissue is chloroplast-containing mesophyll."]),
      importance: 4,
      source_page: 29,
      sort_order: 10,
    }),
    card(chapterId, "epidermis-stomata-appendages", {
      title: "Epidermis, Stomata and Appendages",
      card_type: "classification",
      body: "Epidermal tissue system covers the plant body and includes epidermis, stomata, root hairs and trichomes.",
      table_data: table(["Structure", "Recall answer"], [
        ["Epidermis", "Outermost layer of primary plant body; usually single-layered; compact parenchymatous cells; cuticle prevents water loss and is absent in roots."],
        ["Stomata", "Present in epidermis of leaves; regulate transpiration and gaseous exchange."],
        ["Guard cells", "Bean-shaped, dumbbell-shaped in grasses; possess chloroplasts and regulate opening/closing."],
        ["Subsidiary cells", "Specialized epidermal cells near guard cells."],
        ["Stomatal apparatus", "Stomatal aperture, guard cells and surrounding subsidiary cells together."],
        ["Root hairs", "Unicellular epidermal elongations that absorb water and minerals."],
        ["Trichomes", "Stem epidermal hairs, usually multicellular; may be branched/unbranched, soft/stiff, secretory; reduce water loss."],
      ]),
      recall_data: recall("What makes up the stomatal apparatus?", "Stomatal aperture, guard cells and surrounding subsidiary cells.", [], [], ["Guard cells are dumbbell shaped in grasses."]),
      importance: 5,
      source_page: 29,
      sort_order: 11,
    }),
    card(chapterId, "vascular-bundles", {
      title: "Vascular Bundle Types",
      card_type: "diagram",
      body: "Xylem and phloem together constitute vascular bundles.",
      diagram_data: { type: "bio-vascular-bundles" },
      table_data: table(["Basis", "Type", "Recall answer", "Seen in / example"], [
        ["Cambium", "Open", "Cambium present between phloem and xylem; forms secondary xylem and phloem.", "Dicotyledonous stems"],
        ["Cambium", "Closed", "Cambium absent; secondary tissues not formed.", "Monocotyledons"],
        ["Arrangement", "Radial", "Xylem and phloem arranged alternately on different radii.", "Roots"],
        ["Arrangement", "Conjoint", "Xylem and phloem jointly situated at same radius; phloem usually outer to xylem.", "Stems and leaves"],
      ]),
      recall_data: recall("Open vs closed vascular bundle: what is the decisive feature?", "Presence or absence of cambium.", ["Open bundles can form secondary xylem and phloem.", "Closed bundles do not form secondary tissues."]),
      importance: 5,
      source_page: 29,
      sort_order: 12,
    }),
    card(chapterId, "dicot-monocot-root", {
      title: "Dicot Root vs Monocot Root",
      card_type: "comparison",
      body: "Root T.S. comparison focuses on stele, xylem patches, pith and secondary growth.",
      diagram_data: { type: "bio-dicot-monocot-root" },
      table_data: table(["Feature", "Dicot root", "Monocot root"], [
        ["Tissue organization", "Epiblema, cortex, endodermis and stele.", "Epidermis, cortex, endodermis, pericycle, vascular bundles and pith."],
        ["Root hairs", "Many epiblema cells protrude as unicellular root hairs.", "Shown with epidermis/root hair."],
        ["Xylem bundles", "2-4 xylem and phloem patches.", "Usually more than six (polyarch) xylem bundles."],
        ["Pith", "Small or inconspicuous.", "Large and well developed."],
        ["Secondary growth", "Cambium ring later develops between xylem and phloem.", "Does not undergo secondary growth."],
      ]),
      recall_data: recall("Which root is polyarch in the source?", "Monocot root.", ["Monocot root has usually more than six xylem bundles.", "Pith is large and well developed."], [], ["Lateral roots and vascular cambium initiation occur in pericycle of dicot root."]),
      importance: 5,
      source_page: 29,
      sort_order: 13,
    }),
    card(chapterId, "dicot-root-stele-trap", {
      title: "Dicot Root Stele and Pericycle",
      card_type: "neet_trap",
      body: "In dicot root, all tissues inner to endodermis constitute stele.",
      table_data: table(["Stele part", "Source detail"], [
        ["Pericycle", "A few layers of thick-walled parenchymatous cells next to endodermis; initiation of lateral roots and vascular cambium during secondary growth occurs here."],
        ["Pith", "Innermost region; small or inconspicuous."],
        ["Conjunctive tissue", "Parenchymatous cells between xylem and phloem."],
        ["Vascular bundles", "2-4 xylem and phloem patches; cambium ring later develops."],
      ]),
      recall_data: recall("From which tissue do lateral roots initiate in dicot root according to the source?", "Pericycle.", ["Vascular cambium during secondary growth also initiates in pericycle cells."], [], ["Lateral roots arise from pericycle."]),
      importance: 5,
      source_page: 29,
      sort_order: 14,
    }),
    card(chapterId, "dicot-monocot-stem", {
      title: "Dicot Stem vs Monocot Stem",
      card_type: "comparison",
      body: "Stem anatomy differs in bundle arrangement, bundle type, hypodermis and ground tissue.",
      diagram_data: { type: "bio-dicot-monocot-stem" },
      table_data: table(["Feature", "Dicot stem", "Monocot stem"], [
        ["Hypodermis", "Few layers of collenchymatous cells below epidermis.", "Sclerenchymatous hypodermis."],
        ["Vascular bundles", "Large in number, arranged in a ring; characteristic of dicot stem.", "Many scattered vascular bundles."],
        ["Bundle type", "Each bundle is conjoint, open, with endarch protoxylem.", "Bundles are conjoint and closed."],
        ["Ground tissue", "Cortex, pericycle, medullary rays and pith distinct.", "Large, conspicuous parenchymatous ground tissue."],
        ["Extra note", "Endodermis has starch grains, called starch sheath.", "Phloem parenchyma absent; water-containing cavities in vascular bundles."],
      ]),
      recall_data: recall("What is the vascular bundle type of dicot stem?", "Conjoint, open and with endarch protoxylem.", [], [], ["Monocot stem bundles are conjoint and closed."]),
      importance: 5,
      source_page: 30,
      sort_order: 15,
    }),
    card(chapterId, "dicot-monocot-leaf", {
      title: "Dicot Leaf vs Monocot Leaf",
      card_type: "comparison",
      body: "Dicot leaf is dorsiventral; monocot leaf is isobilateral.",
      diagram_data: { type: "bio-leaf-anatomy" },
      table_data: table(["Feature", "Dicot dorsiventral leaf", "Monocot isobilateral leaf"], [
        ["Main parts", "Epidermis, mesophyll and vascular system.", "Similar in many ways but shows listed differences."],
        ["Stomata", "Abaxial epidermis generally bears more stomata than adaxial epidermis; adaxial may lack stomata.", "Stomata present on both epidermal surfaces."],
        ["Mesophyll", "Differentiated into palisade and spongy parenchyma.", "Not differentiated into palisade and spongy parenchyma."],
        ["Special cells", "Bundle sheath surrounds vascular bundles.", "Bulliform cells in grasses along veins on adaxial epidermis."],
        ["Venation reflection", "Reticulate venation varies vein thickness.", "Parallel venation reflected in nearly similar vascular bundle sizes except main veins."],
      ]),
      recall_data: recall("Where are bulliform cells found according to the source?", "In grasses, certain adaxial epidermal cells along the veins become bulliform cells.", ["Turgid bulliform cells expose leaf surface; flaccid cells make leaves curl inward to minimize water loss."], [], ["Abaxial epidermis generally has more stomata in dorsiventral dicot leaf."]),
      importance: 5,
      source_page: 30,
      sort_order: 16,
    }),
    card(chapterId, "secondary-growth-basics", {
      title: "Secondary Growth Basics",
      card_type: "process",
      body: "Primary growth increases length; secondary growth increases girth of dicot plants.",
      table_data: table(["Term", "Recall answer"], [
        ["Primary growth", "Growth of roots and stems in length with apical meristem."],
        ["Secondary growth", "Increase in girth of dicot plants."],
        ["Lateral meristems involved", "Vascular cambium and cork cambium."],
      ]),
      recall_data: recall("Which meristems are involved in secondary growth?", "Vascular cambium and cork cambium.", ["Secondary growth is increase in girth of dicot plants."], [], ["Secondary growth does not occur in monocotyledons as stated in source."]),
      importance: 5,
      source_page: 30,
      sort_order: 17,
    }),
    card(chapterId, "cambial-ring", {
      title: "Formation of Cambial Ring",
      card_type: "sequence",
      body: "In young dicot stem, vascular cambium begins in patches and later forms a complete ring.",
      diagram_data: { type: "bio-secondary-growth" },
      table_data: table(["Step", "Recall answer"], [
        ["1", "Cambium present between primary xylem and primary phloem is intrafascicular cambium."],
        ["2", "Medullary cells adjoining intrafascicular cambium become meristematic."],
        ["3", "They form interfascicular cambium."],
        ["4", "A continuous cambium ring is formed."],
      ]),
      recall_data: recall("What is the difference between intra- and interfascicular cambium?", "Intrafascicular cambium is between primary xylem and phloem; interfascicular cambium forms from adjoining medullary cells.", ["Together they form a continuous cambial ring."]),
      importance: 5,
      source_page: 30,
      sort_order: 18,
    }),
    card(chapterId, "cambial-ring-activity", {
      title: "Activity of Cambial Ring",
      card_type: "process",
      body: "Cambial ring cuts off cells inward and outward, producing secondary vascular tissues.",
      table_data: table(["Direction", "Product / effect"], [
        ["Towards pith", "Cells mature into secondary xylem."],
        ["Towards periphery", "Cells mature into secondary phloem."],
        ["Inner side activity", "More active; more secondary xylem than secondary phloem is produced."],
        ["Phloem fate", "Primary and secondary phloems gradually get crushed due to accumulation of secondary xylem."],
        ["Medullary rays", "Narrow parenchyma bands through secondary xylem and phloem in radial directions."],
      ]),
      recall_data: recall("Does cambium produce more secondary xylem or secondary phloem?", "More secondary xylem.", ["Cambium is more active on the inner side than on the outer side."]),
      importance: 5,
      source_page: 31,
      sort_order: 19,
    }),
    card(chapterId, "spring-autumn-wood", {
      title: "Spring Wood vs Autumn Wood",
      card_type: "comparison",
      body: "Seasonal cambial activity produces alternate rings of spring wood and autumn wood.",
      table_data: table(["Feature", "Spring wood / early wood", "Autumn wood / late wood"], [
        ["Seasonal cambium activity", "Spring: cambium very active.", "Winter: cambium less active."],
        ["Xylary elements", "Many, vessels with wider cavities.", "Fewer, vessels narrow."],
        ["Colour/density", "Lighter in colour and lower density.", "Darker and higher density."],
      ]),
      recall_data: recall("Which wood is lighter and lower density?", "Spring wood (early wood).", ["Autumn wood is darker and higher density.", "Alternate concentric rings form annual rings."], [], ["Annual rings are used to estimate age of tree: dendrochronology."]),
      importance: 5,
      source_page: 31,
      sort_order: 20,
    }),
    card(chapterId, "heartwood-sapwood", {
      title: "Heartwood vs Sapwood",
      card_type: "comparison",
      body: "Secondary xylem of old trees differentiates into central heartwood and peripheral sapwood.",
      table_data: table(["Feature", "Heartwood", "Sapwood"], [
        ["Position", "Central part of secondary xylem.", "Peripheral region of secondary xylem."],
        ["State/colour", "Hard, dead, dark brown, highly lignified, non-functional.", "Living and lighter in colour."],
        ["Deposits", "Tannins, resins, oils, gums, aromatic substances, essential oils etc.", ""],
        ["Function", "Mechanical support to stem.", "Conduction of water and minerals from root to leaf."],
      ]),
      recall_data: recall("Which part conducts water: heartwood or sapwood?", "Sapwood.", ["Heartwood is hard, dead, dark brown and non-functional.", "Sapwood is living and lighter in colour."]),
      importance: 5,
      source_page: 31,
      sort_order: 21,
    }),
    card(chapterId, "cork-cambium-periderm-bark", {
      title: "Cork Cambium, Periderm and Bark",
      card_type: "classification",
      body: "Cork cambium replaces broken outer protective layers during secondary growth.",
      table_data: table(["Term", "Recall answer"], [
        ["Phellogen / cork cambium", "Meristematic tissue usually developing in cortex; couple of layers thick, narrow, thin-walled, nearly rectangular cells."],
        ["Phellem / cork", "Outer cells cut off by phellogen; impervious to water due to suberin deposition."],
        ["Phelloderm / secondary cortex", "Inner cells cut off by phellogen; parenchymatous."],
        ["Periderm", "Phellogen, phellem and phelloderm collectively."],
        ["Bark", "Non-technical term for all tissues exterior to vascular cambium, such as periderm and secondary phloem."],
        ["Early/soft bark", "Formed early in season."],
        ["Late/hard bark", "Formed towards end of season."],
      ]),
      recall_data: recall("What three tissues collectively form periderm?", "Phellogen, phellem and phelloderm.", ["Phellem is cork; phelloderm is secondary cortex."], [], ["Bark is a non-technical term."]),
      importance: 5,
      source_page: 31,
      sort_order: 22,
    }),
    card(chapterId, "lenticels", {
      title: "Lenticels",
      card_type: "fact",
      body: "At certain regions, phellogen cuts off closely arranged parenchymatous cells on the outer side; these rupture epidermis and form lenticels.",
      recall_data: recall("What is the function of lenticels?", "They permit gas exchange between the outer atmosphere and internal tissue of the stem.", ["Lenticels are lens-shaped openings and occur in most woody trees."]),
      importance: 4,
      source_page: 31,
      sort_order: 23,
    }),
    card(chapterId, "secondary-growth-roots", {
      title: "Secondary Growth in Roots",
      card_type: "process",
      body: "In dicot root, vascular cambium is completely secondary in origin.",
      table_data: table(["Stage", "Recall answer"], [
        ["Origin", "From tissue just below phloem bundles, a portion of pericycle above protoxylem."],
        ["Shape", "Forms complete and continuous wavy ring."],
        ["Later", "Becomes circular."],
        ["Further events", "Similar to dicotyledon stem."],
        ["Occurrence", "Also occurs in stems and roots of gymnosperms; does not occur in monocotyledons."],
      ]),
      recall_data: recall("In dicot root, what is the origin of vascular cambium?", "Completely secondary in origin, from tissue below phloem bundles: a portion of pericycle above protoxylem.", [], [], ["Secondary growth does not occur in monocotyledons."]),
      importance: 5,
      source_page: 31,
      sort_order: 24,
    }),
  ];
}

export function getBiologyBatch2Chapters() {
  return BIOLOGY_BATCH_2_CHAPTER_DEFINITIONS.map((chapterDef) => ({
    id: chapter(chapterDef.slug),
    subject_id: "neet-biology",
    title: chapterDef.title,
    slug: chapterDef.slug,
    sort_order: chapterDef.sort_order,
  }));
}

export function getBiologyBatch2Cards() {
  return [
    ...morphologyCards(chapter("morphology-of-flowering-plants")),
    ...anatomyCards(chapter("anatomy-of-flowering-plants")),
  ];
}
