import fs from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import Papa from "papaparse";
import { createClient } from "@supabase/supabase-js";
process.loadEnvFile(".env.local");
const APPLY=process.argv.includes("--apply"), ROOT=process.cwd(), DIR=path.join(ROOT,"tmp/neet-2020-clean/structured");
const DATASET=path.join(DIR,"neet-2020-structured-draft.json"), CSV=path.join(DIR,"neet-2020-structured.csv"), REPORT=path.join(DIR,"publish-report.json");
const imageFields=["question_image","option_a_image","option_b_image","option_c_image","option_d_image"];
for(const k of ["NEXT_PUBLIC_SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"])if(!process.env[k])throw new Error(`${k} required`);
const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL,process.env.SUPABASE_SERVICE_ROLE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});
function review(q){const a=q.correct_option,label=a.toUpperCase(),v=q[`option_${a}`],pic=q[`option_${a}_image`];return `**Correct option: ${label}**\n\n${v}${pic?`\n\nThe corresponding graph is shown with option ${label}.`:""}`}
async function upload(f,n,k){const ext=path.extname(f)||".png",object=`neet-ug-2020/set-e4/structured/q${String(n).padStart(3,"0")}-${k.replaceAll("_","-")}${ext}`;const{error}=await supabase.storage.from("pyq-images").upload(object,await fs.readFile(f),{contentType:ext===".png"?"image/png":"image/jpeg",upsert:true});if(error)throw new Error(`Q${n} ${k}: ${error.message}`);return supabase.storage.from("pyq-images").getPublicUrl(object).data.publicUrl}
async function main(){
 const data=JSON.parse(await fs.readFile(DATASET,"utf8"));if(data.length!==180||data.some((q,i)=>q.number!==i+1))throw new Error("Expected 1..180");
 const bad=[];for(const q of data){for(const f of ["question","option_a","option_b","option_c","option_d"])if(!String(q[f]||"").trim())bad.push(`Q${q.number} empty ${f}`);const t=[q.question,q.option_a,q.option_b,q.option_c,q.option_d].join(" ");if(/[�□]|[\uE000-\uF8FF]|[]/u.test(t))bad.push(`Q${q.number} glyph`);if(!/^[a-d]$/.test(q.correct_option))bad.push(`Q${q.number} answer`)}if(bad.length)throw new Error(bad.join("\n"));
 const{data:existing,error:ce}=await supabase.from("pyq_questions").select("*").eq("exam","NEET").eq("year",2020).eq("paper_code","NEET 2020 Set E4").order("question_number");if(ce)throw ce;if(existing.length!==180||existing.some((q,i)=>q.question_number!==i+1))throw new Error(`Expected 180 existing E4 rows in sequence; found ${existing.length}`);
 await fs.writeFile(path.join(DIR,"live-backup-before-repair.json"),JSON.stringify(existing,null,2));
 const{data:exam,error:ee}=await supabase.from("pyq_questions").select("exam_id").eq("exam","NEET").not("exam_id","is",null).limit(1).single();if(ee)throw ee;
 const records=[];for(const q of data){const r={exam:"NEET",exam_type:"NEET UG",year:2020,attempt:"NEET UG 2020",shift:"Single Shift",paper_code:"NEET 2020 Set E4",exam_id:exam.exam_id,subject:q.subject,chapter:q.chapter,question_type:"MCQ",question:q.question,option_a:q.option_a,option_b:q.option_b,option_c:q.option_c,option_d:q.option_d,correct_option:q.correct_option.toUpperCase(),explanation:review(q),explanation_image:null,marks_positive:4,marks_negative:-1,question_number:q.number,display_order:q.number,status:"PUBLISHED"};for(const k of imageFields)r[k]=q[k]?(APPLY?await upload(q[k],q.number,k):q[k]):null;records.push(r)}
 await fs.writeFile(CSV,Papa.unparse(records,{newline:"\n"}));const report={mode:APPLY?"apply":"dry-run",total:180,subjects:Object.fromEntries(["Physics","Chemistry","Biology"].map(x=>[x,records.filter(q=>q.subject===x).length])),tables:records.filter(q=>q.question.includes("\n|")).length,questionImages:records.filter(q=>q.question_image).length,optionImages:records.reduce((n,q)=>n+imageFields.slice(1).filter(k=>q[k]).length,0)};
 if(APPLY){const updates=records.map((r,i)=>({...r,id:existing[i].id}));for(let i=0;i<180;i+=30){const{error}=await supabase.from("pyq_questions").upsert(updates.slice(i,i+30),{onConflict:"id"});if(error)throw new Error(`Update batch ${i+1}-${i+30}: ${error.message}`)}const{data:v,error}=await supabase.from("pyq_questions").select("question_number,subject,question,option_a,option_b,option_c,option_d,correct_option,explanation,explanation_image,question_image,option_a_image,option_b_image,option_c_image,option_d_image").eq("exam","NEET").eq("year",2020).eq("paper_code","NEET 2020 Set E4").order("question_number");if(error)throw error;report.verified={total:v.length,sequence:v.every((q,i)=>q.question_number===i+1),subjects:Object.fromEntries(["Physics","Chemistry","Biology"].map(x=>[x,v.filter(q=>q.subject===x).length])),empty:v.filter(q=>[q.question,q.option_a,q.option_b,q.option_c,q.option_d].some(x=>!String(x||"").trim())).length,badReview:v.filter(q=>!String(q.explanation||"").startsWith("**Correct option:")).length,explanationImages:v.filter(q=>q.explanation_image).length,questionImages:v.filter(q=>q.question_image).length,optionImages:v.reduce((n,q)=>n+imageFields.slice(1).filter(k=>q[k]).length,0)};if(report.verified.total!==180||!report.verified.sequence||report.verified.empty||report.verified.badReview||report.verified.explanationImages||report.verified.questionImages!==3||report.verified.optionImages!==4)throw new Error(`Verification failed ${JSON.stringify(report.verified)}`)}
 await fs.writeFile(REPORT,JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
}
main().catch(e=>{console.error(e);process.exit(1)});
