import fs from "node:fs/promises";
import { createClient } from "@supabase/supabase-js";
process.loadEnvFile(".env.local");
const s=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL,process.env.SUPABASE_SERVICE_ROLE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});
const code=process.argv[2], m=code?.match(/^JEE-MAIN-25-(\d\d)APR-S([12])$/); if(!m)throw new Error("Expected JEE-MAIN-25-02APR-S1");
const [,day,shift]=m, data=JSON.parse(await fs.readFile(`tmp/jee-main-2025-april-clean/${code}/manifest.json`,"utf8")); if(data.length!==75)throw new Error(`${code}: incomplete manifest`);
const exam={exam:"JEE",exam_type:"JEE Main",year:2025,attempt:`${Number(day)} Apr`,shift:`Shift ${shift}`,paper_code:code,exam_date:`2025-04-${day}`,duration_minutes:180,total_marks:300,status:"PUBLISHED",is_published:true};
let {data:e,error}=await s.from("pyq_exams").select("id").eq("paper_code",code).maybeSingle();if(error)throw error;if(e){const r=await s.from("pyq_exams").update(exam).eq("id",e.id);if(r.error)throw r.error}else{const r=await s.from("pyq_exams").insert(exam).select("id").single();if(r.error)throw r.error;e=r.data}
const {data:legacy,error:legacyError}=await s.from("pyq_questions").select("id,question").eq("paper_code",code);if(legacyError)throw legacyError;const byNumber=new Map();for(const row of legacy){const n=Number(String(row.question||"").match(/^\s*Question\s+(\d+)\s*:/i)?.[1]);if(n>=1&&n<=75&&!byNumber.has(n))byNumber.set(n,row.id)}
for(const q of data){const key=`jee-main-2025-april-clean/${code}/q${String(q.number).padStart(2,"0")}.png`;const u=await s.storage.from("pyq-images").upload(key,await fs.readFile(q.image_path),{contentType:"image/png",upsert:true});if(u.error)throw u.error;const img=s.storage.from("pyq-images").getPublicUrl(key).data.publicUrl;const numerical=q.question_type==="NUMERICAL",answer=String(q.answer);const row={exam_id:e.id,exam:exam.exam,exam_type:exam.exam_type,year:exam.year,attempt:exam.attempt,shift:exam.shift,paper_code:code,question_number:q.number,display_order:q.number,subject:q.subject,chapter:"Unmapped",question_type:q.question_type,question:`Question ${q.number}: Refer to the source image.`,option_a:"Option 1",option_b:"Option 2",option_c:"Option 3",option_d:"Option 4",correct_option:numerical?"a":"abcd"[Number(answer)-1]||"a",numerical_answer:numerical&&answer!=="DROP"?Number(answer):null,explanation:`Official NTA answer key: ${answer}.`,question_image:img,status:"PUBLISHED",marks_positive:4,marks_negative:numerical?0:1};const old=byNumber.get(q.number);const r=old?await s.from("pyq_questions").update(row).eq("id",old):await s.from("pyq_questions").insert(row);if(r.error)throw r.error}console.log(code);
