import json

questions = [
  {
    "question_number": 61,
    "paper_code": "JEE-MAIN-13-23APR",
    "attempt": "23 Apr",
    "shift": "Online",
    "subject": "Mathematics",
    "official_ans_num": 1,
    "correct_option": "a",
    "image_path": "/Users/ateebfatmi/Desktop/prepzii/tmp/jee-main-2013/JEE-MAIN-13-23APR/crops/q61.png",
    "question_text": "The least integral value $\\alpha$ of $x$ such that $\\frac{x-5}{x^2+5x-14} > 0$, satisfies :",
    "option_a": "$\\alpha^2 + 3\\alpha - 4 = 0$",
    "option_b": "$\\alpha^2 - 5\\alpha + 4 = 0$",
    "option_c": "$\\alpha^2 - 7\\alpha + 6 = 0$",
    "option_d": "$\\alpha^2 + 5\\alpha - 6 = 0$",
    "has_diagram": False,
    "chapter": "Linear Inequalities"
  },
  {
    "question_number": 62,
    "paper_code": "JEE-MAIN-13-23APR",
    "attempt": "23 Apr",
    "shift": "Online",
    "subject": "Mathematics",
    "official_ans_num": 1,
    "correct_option": "a",
    "image_path": "/Users/ateebfatmi/Desktop/prepzii/tmp/jee-main-2013/JEE-MAIN-13-23APR/crops/q62.png",
    "question_text": "Let $a = \\text{Im}\\left(\\frac{1+z^2}{2iz}\\right)$, where $z$ is any non-zero complex number. The set $A = \\{a : |z| = 1 \\text{ and } z \\neq \\pm 1\\}$ is equal to :",
    "option_a": "$(-1, 1)$",
    "option_b": "$[-1, 1]$",
    "option_c": "$[0, 1)$",
    "option_d": "$(-1, 0]$",
    "has_diagram": False,
    "chapter": "Complex Numbers and Quadratic Equations"
  },
  {
    "question_number": 63,
    "paper_code": "JEE-MAIN-13-23APR",
    "attempt": "23 Apr",
    "shift": "Online",
    "subject": "Mathematics",
    "official_ans_num": 3,
    "correct_option": "c",
    "image_path": "/Users/ateebfatmi/Desktop/prepzii/tmp/jee-main-2013/JEE-MAIN-13-23APR/crops/q63.png",
    "question_text": "The sum of the series : $(2)^2 + 2(4)^2 + 3(6)^2 + \\dots \\text{ upto } 10 \\text{ terms is :}$",
    "option_a": "$11300$",
    "option_b": "$11200$",
    "option_c": "$12100$",
    "option_d": "$12300$",
    "has_diagram": False,
    "chapter": "Sequences and Series"
  },
  {
    "question_number": 64,
    "paper_code": "JEE-MAIN-13-23APR",
    "attempt": "23 Apr",
    "shift": "Online",
    "subject": "Mathematics",
    "official_ans_num": 3,
    "correct_option": "c",
    "image_path": "/Users/ateebfatmi/Desktop/prepzii/tmp/jee-main-2013/JEE-MAIN-13-23APR/crops/q64.png",
    "question_text": "If $a_1, a_2, a_3, \\dots, a_n, \\dots$ are in A.P. such that $a_4 - a_7 + a_{10} = m$, then the sum of first $13$ terms of this A.P., is :",
    "option_a": "$10m$",
    "option_b": "$12m$",
    "option_c": "$13m$",
    "option_d": "$15m$",
    "has_diagram": False,
    "chapter": "Sequences and Series"
  },
  {
    "question_number": 65,
    "paper_code": "JEE-MAIN-13-23APR",
    "attempt": "23 Apr",
    "shift": "Online",
    "subject": "Mathematics",
    "official_ans_num": 4,
    "correct_option": "d",
    "image_path": "/Users/ateebfatmi/Desktop/prepzii/tmp/jee-main-2013/JEE-MAIN-13-23APR/crops/q65.png",
    "question_text": "The sum of the rational terms in the binomial expansion of $\\left(2^{\\frac{1}{2}} + 3^{\\frac{1}{5}}\\right)^{10}$ is :",
    "option_a": "$25$",
    "option_b": "$32$",
    "option_c": "$9$",
    "option_d": "$41$",
    "has_diagram": False,
    "chapter": "Binomial Theorem"
  },
  {
    "question_number": 66,
    "paper_code": "JEE-MAIN-13-23APR",
    "attempt": "23 Apr",
    "shift": "Online",
    "subject": "Mathematics",
    "official_ans_num": 1,
    "correct_option": "a",
    "image_path": "/Users/ateebfatmi/Desktop/prepzii/tmp/jee-main-2013/JEE-MAIN-13-23APR/crops/q66.png",
    "question_text": "The number of solutions of the equation $\\sin 2x - 2\\cos x + 4\\sin x = 4$ in the interval $[0, 5\\pi]$ is :",
    "option_a": "$3$",
    "option_b": "$5$",
    "option_c": "$4$",
    "option_d": "$6$",
    "has_diagram": False,
    "chapter": "Trigonometric Functions"
  },
  {
    "question_number": 67,
    "paper_code": "JEE-MAIN-13-23APR",
    "attempt": "23 Apr",
    "shift": "Online",
    "subject": "Mathematics",
    "official_ans_num": 4,
    "correct_option": "d",
    "image_path": "/Users/ateebfatmi/Desktop/prepzii/tmp/jee-main-2013/JEE-MAIN-13-23APR/crops/q67.png",
    "question_text": "If two lines $L_1$ and $L_2$ in space, are defined by\n$$L_1 = \\{x = \\sqrt{\\lambda}y + (\\sqrt{\\lambda} - 1), z = (\\sqrt{\\lambda} - 1)y + \\sqrt{\\lambda}\\} \\text{ and}$$\n$$L_2 = \\{x = \\sqrt{\\mu}y + (1 - \\sqrt{\\mu}), z = (1 - \\sqrt{\\mu})y + \\sqrt{\\mu}\\}$$\nthen $L_1$ is perpendicular to $L_2$, for all nonnegative reals $\\lambda$ and $\\mu$, such that :",
    "option_a": "$\\sqrt{\\lambda} + \\sqrt{\\mu} = 1$",
    "option_b": "$\\lambda \\neq \\mu$",
    "option_c": "$\\lambda + \\mu = 0$",
    "option_d": "$\\lambda = \\mu$",
    "has_diagram": False,
    "chapter": "Three Dimensional Geometry"
  },
  {
    "question_number": 68,
    "paper_code": "JEE-MAIN-13-23APR",
    "attempt": "23 Apr",
    "shift": "Online",
    "subject": "Mathematics",
    "official_ans_num": 1,
    "correct_option": "a",
    "image_path": "/Users/ateebfatmi/Desktop/prepzii/tmp/jee-main-2013/JEE-MAIN-13-23APR/crops/q68.png",
    "question_text": "Let $\\theta_1$ be the angle between two lines $2x + 3y + c_1 = 0$ and $-x + 5y + c_2 = 0$ and $\\theta_2$ be the angle between two lines $2x + 3y + c_1 = 0$ and $-x + 5y + c_3 = 0$, where $c_1, c_2, c_3$ are any real numbers :\n\n**Statement-1:** If $c_2$ and $c_3$ are proportional, then $\\theta_1 = \\theta_2$.\n\n**Statement-2:** $\\theta_1 = \\theta_2$ for all $c_2$ and $c_3$.",
    "option_a": "Statement-1 is true, Statement-2 is true; Statement-2 is a correct explanation of Statement-1.",
    "option_b": "Statement-1 is true, Statement-2 is true; Statement-2 is not a correct explanation of Statement-1.",
    "option_c": "Statement-1 is false; Statement-2 is true.",
    "option_d": "Statement-1 is true; Statement-2 is false.",
    "has_diagram": False,
    "chapter": "Straight Lines"
  },
  {
    "question_number": 69,
    "paper_code": "JEE-MAIN-13-23APR",
    "attempt": "23 Apr",
    "shift": "Online",
    "subject": "Mathematics",
    "official_ans_num": 2,
    "correct_option": "b",
    "image_path": "/Users/ateebfatmi/Desktop/prepzii/tmp/jee-main-2013/JEE-MAIN-13-23APR/crops/q69.png",
    "question_text": "If the circle $x^2 + y^2 - 6x - 8y + (25 - a^2) = 0$ touches the axis of $x$, then $a$ equals :",
    "option_a": "$0$",
    "option_b": "$\\pm 4$",
    "option_c": "$\\pm 2$",
    "option_d": "$\\pm 3$",
    "has_diagram": False,
    "chapter": "Conic Sections"
  },
  {
    "question_number": 70,
    "paper_code": "JEE-MAIN-13-23APR",
    "attempt": "23 Apr",
    "shift": "Online",
    "subject": "Mathematics",
    "official_ans_num": 2,
    "correct_option": "b",
    "image_path": "/Users/ateebfatmi/Desktop/prepzii/tmp/jee-main-2013/JEE-MAIN-13-23APR/crops/q70.png",
    "question_text": "The point of intersection of the normals to the parabola $y^2 = 4x$ at the ends of its latus rectum is :",
    "option_a": "$(0, 2)$",
    "option_b": "$(3, 0)$",
    "option_c": "$(0, 3)$",
    "option_d": "$(2, 0)$",
    "has_diagram": False,
    "chapter": "Conic Sections"
  },
  {
    "question_number": 71,
    "paper_code": "JEE-MAIN-13-23APR",
    "attempt": "23 Apr",
    "shift": "Online",
    "subject": "Mathematics",
    "official_ans_num": 4,
    "correct_option": "d",
    "image_path": "/Users/ateebfatmi/Desktop/prepzii/tmp/jee-main-2013/JEE-MAIN-13-23APR/crops/q71.png",
    "question_text": "A tangent to the hyperbola $\\frac{x^2}{4} - \\frac{y^2}{2} = 1$ meets $x$-axis at $P$ and $y$-axis at $Q$. Lines $PR$ and $QR$ are drawn such that $OPRQ$ is a rectangle (where $O$ is the origin). Then $R$ lies on :",
    "option_a": "$\\frac{4}{x^2} + \\frac{2}{y^2} = 1$",
    "option_b": "$\\frac{2}{x^2} - \\frac{4}{y^2} = 1$",
    "option_c": "$\\frac{2}{x^2} + \\frac{4}{y^2} = 1$",
    "option_d": "$\\frac{4}{x^2} - \\frac{2}{y^2} = 1$",
    "has_diagram": False,
    "chapter": "Conic Sections"
  },
  {
    "question_number": 72,
    "paper_code": "JEE-MAIN-13-23APR",
    "attempt": "23 Apr",
    "shift": "Online",
    "subject": "Mathematics",
    "official_ans_num": 1,
    "correct_option": "a",
    "image_path": "/Users/ateebfatmi/Desktop/prepzii/tmp/jee-main-2013/JEE-MAIN-13-23APR/crops/q72.png",
    "question_text": "For integers $m$ and $n$, both greater than $1$, consider the following three statements :\n$P : m \\text{ divides } n$\n$Q : m \\text{ divides } n^2$\n$R : m \\text{ is prime}$\n\nthen :",
    "option_a": "$Q \\wedge R \\rightarrow P$",
    "option_b": "$P \\wedge Q \\rightarrow R$",
    "option_c": "$Q \\rightarrow R$",
    "option_d": "$Q \\rightarrow P$",
    "has_diagram": False,
    "chapter": "Mathematical Reasoning"
  },
  {
    "question_number": 73,
    "paper_code": "JEE-MAIN-13-23APR",
    "attempt": "23 Apr",
    "shift": "Online",
    "subject": "Mathematics",
    "official_ans_num": 4,
    "correct_option": "d",
    "image_path": "/Users/ateebfatmi/Desktop/prepzii/tmp/jee-main-2013/JEE-MAIN-13-23APR/crops/q73.png",
    "question_text": "If the median and the range of four numbers $\\{x, y, 2x + y, x - y\\}$, where $0 < y < x < 2y$, are $10$ and $28$ respectively, then the mean of the numbers is :",
    "option_a": "$18$",
    "option_b": "$10$",
    "option_c": "$5$",
    "option_d": "$14$",
    "has_diagram": False,
    "chapter": "Statistics"
  },
  {
    "question_number": 74,
    "paper_code": "JEE-MAIN-13-23APR",
    "attempt": "23 Apr",
    "shift": "Online",
    "subject": "Mathematics",
    "official_ans_num": 2,
    "correct_option": "b",
    "image_path": "/Users/ateebfatmi/Desktop/prepzii/tmp/jee-main-2013/JEE-MAIN-13-23APR/crops/q74.png",
    "question_text": "If the extremities of the base of an isosceles triangle are the points $(2a, 0)$ and $(0, a)$ and the equation of one of the sides is $x = 2a$, then the area of the triangle, in square units, is :",
    "option_a": "$\\frac{5}{4}a^2$",
    "option_b": "$\\frac{5}{2}a^2$",
    "option_c": "$\\frac{25a^2}{4}$",
    "option_d": "$5a^2$",
    "has_diagram": False,
    "chapter": "Straight Lines"
  },
  {
    "question_number": 75,
    "paper_code": "JEE-MAIN-13-23APR",
    "attempt": "23 Apr",
    "shift": "Online",
    "subject": "Mathematics",
    "official_ans_num": 2,
    "correct_option": "b",
    "image_path": "/Users/ateebfatmi/Desktop/prepzii/tmp/jee-main-2013/JEE-MAIN-13-23APR/crops/q75.png",
    "question_text": "On the sides $AB, BC, CA$ of a $\\triangle ABC$, $3, 4, 5$ distinct points (excluding vertices $A, B, C$) are respectively chosen. The number of triangles that can be constructed using these chosen points as vertices are :",
    "option_a": "$210$",
    "option_b": "$205$",
    "option_c": "$215$",
    "option_d": "$220$",
    "has_diagram": False,
    "chapter": "Permutations and Combinations"
  },
  {
    "question_number": 76,
    "paper_code": "JEE-MAIN-13-23APR",
    "attempt": "23 Apr",
    "shift": "Online",
    "subject": "Mathematics",
    "official_ans_num": 4,
    "correct_option": "d",
    "image_path": "/Users/ateebfatmi/Desktop/prepzii/tmp/jee-main-2013/JEE-MAIN-13-23APR/crops/q76.png",
    "question_text": "Let $R = \\{(x, y) : x, y \\in N \\text{ and } x^2 - 4xy + 3y^2 = 0\\}$, where $N$ is the set of all natural numbers. Then the relation $R$ is :",
    "option_a": "reflexive but neither symmetric nor transitive.",
    "option_b": "symmetric and transitive.",
    "option_c": "reflexive and symmetric.",
    "option_d": "reflexive and transitive.",
    "has_diagram": False,
    "chapter": "Relations and Functions"
  },
  {
    "question_number": 77,
    "paper_code": "JEE-MAIN-13-23APR",
    "attempt": "23 Apr",
    "shift": "Online",
    "subject": "Mathematics",
    "official_ans_num": 2,
    "correct_option": "b",
    "image_path": "/Users/ateebfatmi/Desktop/prepzii/tmp/jee-main-2013/JEE-MAIN-13-23APR/crops/q77.png",
    "question_text": "Let $A$, other than $I$ or $-I$, be a $2 \\times 2$ real matrix such that $A^2 = I$, $I$ being the unit matrix. Let $\\text{Tr}(A)$ be the sum of diagonal elements of $A$.\n\n**Statement-1:** $\\text{Tr}(A) = 0$\n\n**Statement-2:** $\\det(A) = -1$",
    "option_a": "Statement-1 is true; Statement-2 is false.",
    "option_b": "Statement-1 is true; Statement-2 is true; Statement-2 is not a correct explanation for Statement-1.",
    "option_c": "Statement-1 is true; Statement-2 is true; Statement-2 is a correct explanation for Statement-1.",
    "option_d": "Statement-1 is false; Statement-2 is true.",
    "has_diagram": False,
    "chapter": "Matrices"
  },
  {
    "question_number": 78,
    "paper_code": "JEE-MAIN-13-23APR",
    "attempt": "23 Apr",
    "shift": "Online",
    "subject": "Mathematics",
    "official_ans_num": 3,
    "correct_option": "c",
    "image_path": "/Users/ateebfatmi/Desktop/prepzii/tmp/jee-main-2013/JEE-MAIN-13-23APR/crops/q78.png",
    "question_text": "**Statement-1:** The system of linear equations\n$$x + (\\sin\\alpha)y + (\\cos\\alpha)z = 0$$\n$$x + (\\cos\\alpha)y + (\\sin\\alpha)z = 0$$\n$$x - (\\sin\\alpha)y - (\\cos\\alpha)z = 0$$\nhas a non-trivial solution for only one value of $\\alpha$ lying in the interval $\\left(0, \\frac{\\pi}{2}\\right)$.\n\n**Statement-2:** The equation in $\\alpha$\n$$\\begin{vmatrix} \\cos\\alpha & \\sin\\alpha & \\cos\\alpha \\\\ \\sin\\alpha & \\cos\\alpha & \\sin\\alpha \\\\ \\cos\\alpha & -\\sin\\alpha & -\\cos\\alpha \\end{vmatrix} = 0$$\nhas only one solution lying in the interval $\\left(0, \\frac{\\pi}{2}\\right)$.",
    "option_a": "Statement-1 is true, Statement-2 is true; Statement-2 is not a correct explanation for Statement-1.",
    "option_b": "Statement-1 is true, Statement-2 is true; Statement-2 is a correct explanation for Statement-1.",
    "option_c": "Statement-1 is true, Statement-2 is false.",
    "option_d": "Statement-1 is false, Statement-2 is true.",
    "has_diagram": False,
    "chapter": "Determinants"
  },
  {
    "question_number": 79,
    "paper_code": "JEE-MAIN-13-23APR",
    "attempt": "23 Apr",
    "shift": "Online",
    "subject": "Mathematics",
    "official_ans_num": 3,
    "correct_option": "c",
    "image_path": "/Users/ateebfatmi/Desktop/prepzii/tmp/jee-main-2013/JEE-MAIN-13-23APR/crops/q79.png",
    "question_text": "$S = \\tan^{-1}\\left(\\frac{1}{n^2+n+1}\\right) + \\tan^{-1}\\left(\\frac{1}{n^2+3n+3}\\right) + \\dots + \\tan^{-1}\\left(\\frac{1}{1+(n+19)(n+20)}\\right)$, then $\\tan S$ is equal to :",
    "option_a": "$\\frac{20}{401+20n}$",
    "option_b": "$\\frac{n}{n^2+20n+1}$",
    "option_c": "$\\frac{20}{n^2+20n+1}$",
    "option_d": "$\\frac{n}{401+20n}$",
    "has_diagram": False,
    "chapter": "Inverse Trigonometric Functions"
  },
  {
    "question_number": 80,
    "paper_code": "JEE-MAIN-13-23APR",
    "attempt": "23 Apr",
    "shift": "Online",
    "subject": "Mathematics",
    "official_ans_num": 2,
    "correct_option": "b",
    "image_path": "/Users/ateebfatmi/Desktop/prepzii/tmp/jee-main-2013/JEE-MAIN-13-23APR/crops/q80.png",
    "question_text": "Let $f$ be a composite function of $x$ defined by $f(u) = \\frac{1}{u^2+u-2}$, $u(x) = \\frac{1}{x-1}$. Then the number of points $x$ where $f$ is discontinuous is :",
    "option_a": "$4$",
    "option_b": "$3$",
    "option_c": "$2$",
    "option_d": "$1$",
    "has_diagram": False,
    "chapter": "Continuity and Differentiability"
  },
  {
    "question_number": 81,
    "paper_code": "JEE-MAIN-13-23APR",
    "attempt": "23 Apr",
    "shift": "Online",
    "subject": "Mathematics",
    "official_ans_num": 4,
    "correct_option": "d",
    "image_path": "/Users/ateebfatmi/Desktop/prepzii/tmp/jee-main-2013/JEE-MAIN-13-23APR/crops/q81.png",
    "question_text": "If $f(x) = \\sin(\\sin x)$ and $f''(x) + \\tan x f'(x) + g(x) = 0$, then $g(x)$ is :",
    "option_a": "$\\cos^2 x \\cos(\\sin x)$",
    "option_b": "$\\sin^2 x \\cos(\\cos x)$",
    "option_c": "$\\sin^2 x \\sin(\\cos x)$",
    "option_d": "$\\cos^2 x \\sin(\\sin x)$",
    "has_diagram": False,
    "chapter": "Continuity and Differentiability"
  },
  {
    "question_number": 82,
    "paper_code": "JEE-MAIN-13-23APR",
    "attempt": "23 Apr",
    "shift": "Online",
    "subject": "Mathematics",
    "official_ans_num": 2,
    "correct_option": "b",
    "image_path": "/Users/ateebfatmi/Desktop/prepzii/tmp/jee-main-2013/JEE-MAIN-13-23APR/crops/q82.png",
    "question_text": "If the curves $\\frac{x^2}{\\alpha} + \\frac{y^2}{4} = 1$ and $y^3 = 16x$ intersect at right angles, then a value of $\\alpha$ is :",
    "option_a": "$2$",
    "option_b": "$\\frac{4}{3}$",
    "option_c": "$\\frac{1}{2}$",
    "option_d": "$\\frac{3}{4}$",
    "has_diagram": False,
    "chapter": "Application of Derivatives"
  },
  {
    "question_number": 83,
    "paper_code": "JEE-MAIN-13-23APR",
    "attempt": "23 Apr",
    "shift": "Online",
    "subject": "Mathematics",
    "official_ans_num": 3,
    "correct_option": "c",
    "image_path": "/Users/ateebfatmi/Desktop/prepzii/tmp/jee-main-2013/JEE-MAIN-13-23APR/crops/q83.png",
    "question_text": "The cost of running a bus from $A$ to $B$ is $\\text{Rs. } (av + b/v)$ where $v\\text{ km/h}$ is the average speed of the bus. When the bus travels at $30\\text{ km/h}$, the cost comes out to be $\\text{Rs. } 75$ while at $40\\text{ km/h}$, it is $\\text{Rs. } 65$. Then the most economical speed (in $\\text{km/h}$) of the bus is :",
    "option_a": "$45$",
    "option_b": "$50$",
    "option_c": "$60$",
    "option_d": "$40$",
    "has_diagram": False,
    "chapter": "Application of Derivatives"
  },
  {
    "question_number": 84,
    "paper_code": "JEE-MAIN-13-23APR",
    "attempt": "23 Apr",
    "shift": "Online",
    "subject": "Mathematics",
    "official_ans_num": 1,
    "correct_option": "a",
    "image_path": "/Users/ateebfatmi/Desktop/prepzii/tmp/jee-main-2013/JEE-MAIN-13-23APR/crops/q84.png",
    "question_text": "If a curve passes through the point $\\left(2, \\frac{7}{2}\\right)$ and has slope $\\left(1 - \\frac{1}{x^2}\\right)$ at any point $(x, y)$ on it, then the ordinate of the point on the curve whose abscissa is $-2$ is :",
    "option_a": "$-\\frac{3}{2}$",
    "option_b": "$\\frac{3}{2}$",
    "option_c": "$\\frac{5}{2}$",
    "option_d": "$-\\frac{5}{2}$",
    "has_diagram": False,
    "chapter": "Differential Equations"
  },
  {
    "question_number": 85,
    "paper_code": "JEE-MAIN-13-23APR",
    "attempt": "23 Apr",
    "shift": "Online",
    "subject": "Mathematics",
    "official_ans_num": 2,
    "correct_option": "b",
    "image_path": "/Users/ateebfatmi/Desktop/prepzii/tmp/jee-main-2013/JEE-MAIN-13-23APR/crops/q85.png",
    "question_text": "The integral $\\int \\frac{x\\,dx}{2-x^2+\\sqrt{2-x^2}}$ equals :",
    "option_a": "$\\log \\left|1 + \\sqrt{2+x^2}\\right| + c$",
    "option_b": "$-\\log \\left|1 + \\sqrt{2-x^2}\\right| + c$",
    "option_c": "$-x \\log \\left|1 - \\sqrt{2-x^2}\\right| + c$",
    "option_d": "$x \\log \\left|1 - \\sqrt{2+x^2}\\right| + c$",
    "has_diagram": False,
    "chapter": "Integrals"
  },
  {
    "question_number": 86,
    "paper_code": "JEE-MAIN-13-23APR",
    "attempt": "23 Apr",
    "shift": "Online",
    "subject": "Mathematics",
    "official_ans_num": 4,
    "correct_option": "d",
    "image_path": "/Users/ateebfatmi/Desktop/prepzii/tmp/jee-main-2013/JEE-MAIN-13-23APR/crops/q86.png",
    "question_text": "The value of $\\int_{-\\pi/2}^{\\pi/2} \\frac{\\sin^2 x}{1+2^x}\\,dx$ is :",
    "option_a": "$\\pi$",
    "option_b": "$\\frac{\\pi}{2}$",
    "option_c": "$4\\pi$",
    "option_d": "$\\frac{\\pi}{4}$",
    "has_diagram": False,
    "chapter": "Integrals"
  },
  {
    "question_number": 87,
    "paper_code": "JEE-MAIN-13-23APR",
    "attempt": "23 Apr",
    "shift": "Online",
    "subject": "Mathematics",
    "official_ans_num": 2,
    "correct_option": "b",
    "image_path": "/Users/ateebfatmi/Desktop/prepzii/tmp/jee-main-2013/JEE-MAIN-13-23APR/crops/q87.png",
    "question_text": "The area under the curve $y = |\\cos x - \\sin x|$, $0 \\le x \\le \\frac{\\pi}{2}$, and above $x$-axis is :",
    "option_a": "$2\\sqrt{2}$",
    "option_b": "$2\\sqrt{2} - 2$",
    "option_c": "$2\\sqrt{2} + 2$",
    "option_d": "$0$",
    "has_diagram": False,
    "chapter": "Application of Integrals"
  },
  {
    "question_number": 88,
    "paper_code": "JEE-MAIN-13-23APR",
    "attempt": "23 Apr",
    "shift": "Online",
    "subject": "Mathematics",
    "official_ans_num": 2,
    "correct_option": "b",
    "image_path": "/Users/ateebfatmi/Desktop/prepzii/tmp/jee-main-2013/JEE-MAIN-13-23APR/crops/q88.png",
    "question_text": "If $\\vec{a}$ and $\\vec{b}$ are non-collinear vectors, then the value of $\\alpha$ for which the vectors $\\vec{u} = (\\alpha - 2)\\vec{a} + \\vec{b}$ and $\\vec{v} = (2 + 3\\alpha)\\vec{a} - 3\\vec{b}$ are collinear is :",
    "option_a": "$\\frac{3}{2}$",
    "option_b": "$\\frac{2}{3}$",
    "option_c": "$-\\frac{3}{2}$",
    "option_d": "$-\\frac{2}{3}$",
    "has_diagram": False,
    "chapter": "Vector Algebra"
  },
  {
    "question_number": 89,
    "paper_code": "JEE-MAIN-13-23APR",
    "attempt": "23 Apr",
    "shift": "Online",
    "subject": "Mathematics",
    "official_ans_num": 2,
    "correct_option": "b",
    "image_path": "/Users/ateebfatmi/Desktop/prepzii/tmp/jee-main-2013/JEE-MAIN-13-23APR/crops/q89.png",
    "question_text": "If the projections of a line segment on the $x$, $y$ and $z$-axes in $3$-dimensional space are $2$, $3$ and $6$ respectively, then the length of the line segment is :",
    "option_a": "$12$",
    "option_b": "$7$",
    "option_c": "$9$",
    "option_d": "$6$",
    "has_diagram": False,
    "chapter": "Three Dimensional Geometry"
  },
  {
    "question_number": 90,
    "paper_code": "JEE-MAIN-13-23APR",
    "attempt": "23 Apr",
    "shift": "Online",
    "subject": "Mathematics",
    "official_ans_num": 1,
    "correct_option": "a",
    "image_path": "/Users/ateebfatmi/Desktop/prepzii/tmp/jee-main-2013/JEE-MAIN-13-23APR/crops/q90.png",
    "question_text": "$A$, $B$, $C$ try to hit a target simultaneously but independently. Their respective probabilities of hitting the targets are $\\frac{3}{4}, \\frac{1}{2}, \\frac{5}{8}$. The probability that the target is hit by $A$ or $B$ but not by $C$ is :",
    "option_a": "$\\frac{21}{64}$",
    "option_b": "$\\frac{7}{8}$",
    "option_c": "$\\frac{7}{32}$",
    "option_d": "$\\frac{9}{64}$",
    "has_diagram": False,
    "chapter": "Probability"
  }
]

output_path = "/Users/ateebfatmi/Desktop/prepzii/scratch/transcribed/23apr_mathematics.json"
with open(output_path, "w", encoding="utf-8") as f:
    json.dump(questions, f, ensure_ascii=False, indent=2)

print("Successfully written 30 questions to", output_path)
